### ISSUE TITLE
com.alibaba.druid.support.http.stat.WebAppStat 占用大量内存，如何处理？

### ISSUE THREAD

**Issue by hnmas** [alibaba/druid#1007]
web项目中使用了druid，运行一段时间后，发现内存占用持续上涨，将内存dump出来后分析，发现以下信息：
One instance of "com.alibaba.druid.support.http.stat.WebAppStat" loaded by "org.apache.catalina.loader.WebappClassLoader @ 0x700060088" occupies 2,361,715,064 (87.93%) bytes. The memory is accumulated in one instance of "java.util.LinkedHashMap" loaded by "<system class loader>".
WebAppStat对象占用了2G多的内存，并且手动执行垃圾回收回收不掉，昨确定哪的原因呢？

**Comment by hnmas** [comment]
补充一下，内存占用的都是老年代内存。

**Comment by geeksun** [comment]
这个问题后来怎么解决的？

**Comment by carson0116** [comment]
这个问题咋解决的？

**Comment by Maizioo** [comment]
遇到同样的问题，怎么解决的呢？

**Comment by ddd0000** [comment]
遇到同样的问题，各位是怎么解决的？

**Comment by zhouchengfei** [comment]
遇到同样的问题，各位是怎么解决的？

**Comment by zhouchengfei** [comment]
是不是 定时 com.alibaba.druid.stat.DruidStatManagerFacade.getInstance().resetAll();

**Comment by RayCJ92** [comment]
版本号？

**Comment by lizongbo** [comment]
自己开启mergesql的特性，或及时清理数据。或者禁用statfilter
