### ISSUE TITLE
开启PSCache后，Oracle下使用Spring的NamedParameterJdbcTemplate执行insert操作，在第二次insert时会报错

### ISSUE THREAD

**Issue by PromethS** [alibaba/druid#1012]
各位好。在开启PSCache后，用Spring的NamedParameterJdbcTemplate.update(String sql, SqlParameterSource paramSource,KeyHolder generatedKeyHolder, String keyColumnNames[])执行insert操作，并需得到主键ID（序列）时，在首次执行是正常的，第二次就会报错。
错误信息如下：org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [INSERT INTO SM_REL_ACC_ORG(REL_ID) values(SM_REL_ACC_ORG_SEQ.NEXTVAL)]; SQL state [null]; error code [17041]; 索引中丢失  IN 或 OUT 参数:: 1;
如果改成不获取主键ID则就不会报错，或把PSCache关闭也不会有问题。
注：Druid的版本为1.0.16（maven最新版本）

**Comment by cherliu** [comment]
我也遇到相同的问题了，使用jdbcTemplate，配置druid连接池，同一张表第二次insert总是报：索引中丢失 IN 或 OUT 参数::X
我反复对比了参数类型，并没有什么问题，根据PromethS的情况试着把PSCache关闭，成功了。
注：Druid的版本为1.1.10（目前最新）
说明：我使用IDEA的debug模式调试失败，而我的同事使用eclipse调试成功，目前原因尚未找到，麻烦druid开发工程师能解答下这个问题，谢谢！

**Comment by wsdl-king** [comment]
我也遇到相同的问题了,...... 插入成功 then 失败```循环的节奏

**Comment by lizongbo** [comment]
请使用最新版验证
