### ISSUE TITLE
how to reset pool if I change user/password credential in the database

### ISSUE THREAD

**Issue by qmz** [alibaba/druid#1013]
RT，对于DBCP，https://issues.apache.org/jira/browse/DBCP-8.
当用Druid替换DBCP时用户密码变更该如何处理呢，DruidDataSource#getConnection已经声明不支持。这种业务场景是如何处理的呢。

非常感谢。

**Comment by wenshao** [comment]
用户名都不同了，就应该使用多个连接池啊

**Comment by qmz** [comment]
嗯，目前采用了close后new的方式，那我close掉这个issue
