### ISSUE TITLE
com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, active 20, maxActive 20

### ISSUE THREAD

**Issue by YaoYufeng** [alibaba/druid#1014]
以前公司用的是oracle，设置的最大连接数量是20，没有问题。 现在公司用的是mysql，在最大连接数量不变的情况下发现druid创建了很多连接，但是不复用，一直sleep，等到了时间才回收，到达最高链接数量后再请求则直接报标题异常，重启tomcat解决。
设置成200的最大连接数还是有问题，不知道是不是设置的问题，求教
 
<bean id="dataSource_zyo" 
                class="com.alibaba.druid.pool.DruidDataSource"
		init-method="init" destroy-method="close" p:url="${jdbc.zyo.url}"
		p:username="${jdbc.user}" p:password="${jdbc.password}" p:filters="stat"
		p:maxActive="20" p:initialSize="1" p:maxWait="60000" p:minIdle="1"
		p:timeBetweenEvictionRunsMillis="3000" p:minEvictableIdleTimeMillis="300000"
		p:validationQuery="SELECT 'x' FROM DUAL" p:testWhileIdle="true" p:testOnBorrow="false"
		p:testOnReturn="false" p:poolPreparedStatements="false"/>

**Comment by YaoYufeng** [comment]
查看代码后发现，是自己代码的问题，有的没有关闭连接

**Comment by kingkeivn** [comment]
你这里不是用的mybatis吗？
