### ISSUE TITLE
wildfly集成druid

### ISSUE THREAD

**Issue by slieer** [alibaba/druid#1017]
druid，怎么和wildfly or jboss eap 6.4 集成？
能不能取代jboss eap中自带的db connection pooling?
或者在jboss eap，通过配置persistence.xml来实现使用druil ?

**Comment by wenshao** [comment]
没用过wildfy，⊙﹏⊙b汗

**Comment by dachuanz** [comment]
jboss 改名了

**Comment by slieer** [comment]
通过配置persistence.xml方式, 可以把druid接进去，但不太优雅。能扩展datasource，就好了。
