### ISSUE TITLE
使用nginx负载之后无法获取客户端真实IP？

### ISSUE THREAD

**Issue by denghp** [alibaba/druid#1019]
我在web.xml中配置的DruidStatView添加限制IP参数
```
<init-param>
            <param-name>allow</param-name>
            <param-value>192.168.1.1/24,10.0.0.1/24</param-value>
</init-param>
```
使用nginx负载后，无法拦截客户端的访问，查看代码发现：
```
com.alibaba.druid.support.http。ResourceServlet 

 protected String getRemoteAddress(HttpServletRequest request) {
        String remoteAddress = null;
        
        if (remoteAddressHeader != null) {
            remoteAddress = request.getHeader(remoteAddressHeader);
        }
        
        if (remoteAddress == null) {
            remoteAddress = request.getRemoteAddr();
        }
        
        return remoteAddress;
    }
```
这里是无法获取客户端真实的IP实现，但是我发现：
```
com.alibaba.druid.util.DruidWebUtils
public static String getRemoteAddr(HttpServletRequest request) {
        String ip = request.getHeader("x-forwarded-for");
        if (ip == null || ip.length() == 0 || "unknown".equalsIgnoreCase(ip)) {
            ip = request.getHeader("Proxy-Client-IP");
        }
        if (ip == null || ip.length() == 0 || "unknown".equalsIgnoreCase(ip)) {
            ip = request.getHeader("WL-Proxy-Client-IP");
        }
        if (ip == null || ip.length() == 0 || "unknown".equalsIgnoreCase(ip)) {
            ip = request.getRemoteAddr();
        }

        return ip;
    }
```
通过这个函数是能正常获取的，不清楚为什么上面的位置没有更调用这个函数？

**Comment by feiyan35488** [comment]
google一下就能解决

**Comment by shi1991** [comment]
在 location 中加入下类配置：
`proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr; 
proxy_set_header REMOTE-HOST $remote_addr; 
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`
在Java代码中通过
`public static String getRemoteAddr(HttpServletRequest request) {
        String ip = request.getHeader("x-forwarded-for");
        if (ip == null || ip.length() == 0 || "unknown".equalsIgnoreCase(ip)) {
            ip = request.getHeader("Proxy-Client-IP");
        }
        if (ip == null || ip.length() == 0 || "unknown".equalsIgnoreCase(ip)) {
            ip = request.getHeader("WL-Proxy-Client-IP");
        }
        if (ip == null || ip.length() == 0 || "unknown".equalsIgnoreCase(ip)) {
            ip = request.getRemoteAddr();
        }

        return ip;
    }`
