### ISSUE TITLE
Communications link failure problem

### ISSUE THREAD

**Issue by qiuyinglanshan** [alibaba/druid#1022]
##### 1.问题描述

应用druid连接池，长时间没有请求造成的数据库连接超时，抛出异常：
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
##### 2.尝试方法

 期望通过testWhileIdle = true 结合validationQuery每隔30s更新连接的状态，但结果是不会30s执行select 'x'语句（通过日志和stat监控中sql得到）。

```
    <property name="validationQuery" value="SELECT 'x'" />
    <property name="testOnBorrow" value="true" />
    <property name="testOnReturn" value="false" />
    <property name="testWhileIdle" value="true" />
    <property name="timeBetweenEvictionRunsMillis" value="30000" />
    <property name="numTestsPerEvictionRun" value="3" />
    <property name="minEvictableIdleTimeMillis" value="600000" />
```
##### 3其他方案

已在DBCP连接池测试，testWhileIdle=true是奏效的。

**Comment by hifor** [comment]
碰到一样的问题
我连接的是两个库，一个是MSSQL，一个是MYSQL
MSSQL都正常，就是MYSQL出现跟你一样的问题
MYSQL版本:5.5.36
默认wait_timeout    28800

解决方法:
`
<property name="validationQuery" value="select 1" />
<property name="testOnBorrow" value="true" />
<property name="testWhileIdle" value="true"/>
`
没有设置其他参数，也就是每次连接都判断连接是否有效，感觉影响性能

**Comment by ddatsh** [comment]
+1

**Comment by wustrive2008** [comment]
遇到同样的问题

**Comment by testerlife** [comment]
遇到了同样的问题  我来试试2楼的方法

**Comment by wenshao** [comment]
通常是申请连接后长时间不使用导致的。比如：
Connection conn = ...;
... // 常会时间间隔，比如30分钟
Statement stmt = conn.createStatement();
stmt.executeQuery("select ...");

**Comment by testerlife** [comment]
使用了2楼的方法  配置后确实解决问题了

**Comment by minotaursu** [comment]
多个应用遇到同样的问题

**Comment by Xanthuim** [comment]
> 通常是申请连接后长时间不使用导致的。比如：
> Connection conn = ...;
> ... // 长时间操作，比如30分钟
> Statement stmt = conn.createStatement();
> stmt.executeQuery("select ...");

归根结底还是代码问题了？

**Comment by qiuyinglanshan** [comment]
非常抱歉，忘了关闭这个问题了，
二楼的办法应该是对的，没有测试哦。

**Comment by git10135405** [comment]
只能牺牲性能解决这个问题吗
