### ISSUE TITLE
find a bug of druid when parse 'not'  key word in where condition

### ISSUE THREAD

**Issue by digdeep126** [alibaba/druid#1049]
public static void main(String[] args){
	String sql = "select * from company where id=1 and not (name='e') and addr='a'";
	SQLStatementParser parser = new MySqlStatementParser(sql); 
	SQLStatement statement = parser.parseStatement();
	System.out.println(statement.toString());
}
the result as follows:
SELECT *
FROM company
WHERE id = 1
	AND NOT (name = 'e'
	AND addr = 'a')

**Comment by wuyongwen** [comment]
测试druid 1.0.9版本没有问题

**Comment by digdeep126** [comment]
master分支 和 1.0.14 是肯定存在该bug

**Comment by wenshao** [comment]
bug是存在的，已经修复，等新版本吧

**Comment by digdeep126** [comment]
wenshao真快！自己正调试中，这快就修复了...

**Comment by digdeep126** [comment]
改一行代码就把bug fix掉了...

**Comment by digdeep126** [comment]
建议，修复 bug 时，不能仅仅修复最新的版本，比如该bug从1.0.14之前就开始存在，一直到1.0.16，这些版本的bug都应该修复，不能仅仅在1.0.17中进行修复就完了。其它版本也应该修复并发布 bug fix 的版本。不然我们要直接从1.0.14升级到1.0.17有一些兼容性问题需要另外处理，比较麻烦。而且需要大量测试工作......
