### ISSUE TITLE
log4j2 打印sql

### ISSUE THREAD

**Issue by pengliaoye** [alibaba/druid#1055]

**Comment by wenshao** [comment]
不支持么？

**Comment by pengliaoye** [comment]
怎么配置也。我一直没打印出来

**Comment by lliule** [comment]
怎么配置Log才能打印出执行的sql语句啊。没有一个线程的eg吗？

**Comment by pengliaoye** [comment]
<property name="proxyFilters">
	        <list>
	            <ref bean="log-filter"/>
	        </list>
	    </property>
	     
	</bean>
	
	<bean id="log-filter" class="com.alibaba.druid.filter.logging.Log4jFilter">
		<property name="statementPrepareAfterLogEnabled" value="false" />
		<property name="statementExecuteAfterLogEnabled" value="false" />
	
        <property name="statementExecutableSqlLogEnable" value="true" />
  	</bean>
