### ISSUE TITLE
druid 1.0.16中sql parser的一个bug

### ISSUE THREAD

**Issue by joaboo** [alibaba/druid#1060]
如下sql：select distinct c1, c2 from TBL
在执行PagerUtils.count(sql, JdbcConstants.MYSQL)后，出来居然是SELECT DISTINCT COUNT(*) FROM TBL，相当不科学啊。。。

**Comment by dachuanz** [comment]
com.alibaba.druid.sql.parser.SQLParserUtils 这个类里面没有处理distinct

**Comment by wenshao** [comment]
bug已经修复，等druid 1.0.17吧

**Comment by guixincui** [comment]
SELECT DISTINCT col1, col2 FROM TB ；  这种情况count sql还是有问题。

**Comment by guixincui** [comment]
判断逻辑是`if (option == SQLSetQuantifier.DISTINCT && queryBlock.getSelectList().size() == 1)` ，实际上这里getSelectList() 长度大于1
