### ISSUE TITLE
springboot security加druid时候 监控页面浏览器显示html源码 不加security 没问题

### ISSUE THREAD

**Issue by zhaiyuyong** [alibaba/druid#1064]

**Comment by angelsinklowcn** [comment]
.headers().frameOptions().sameOrigin().contentTypeOptions().disable() 加上这行代码就能正常显示了

**Comment by joey0720080246** [comment]
@yangziran  加在哪里啊? 谢谢!

**Comment by yangziran** [comment]
Spring Security 配置

**Comment by jackBaozz** [comment]
看了下，感觉跟浏览器也有关系。
chrome下，访问http://127.0.0.1:9815/druid，它就直接返回没权限？？？
其他浏览器，访问http://127.0.0.1:9815/druid，就会跳转到 http://127.0.0.1:9815/druid/index.html 就可以正常访问了。
