### ISSUE TITLE
当项目中有多个日志jar包时，配置失效？

### ISSUE THREAD

**Issue by cser-feng** [alibaba/druid#1081]
项目中存在log4j 和 slf4j 两种，配置使用slf4j没用,查看代码是优先使用log4j,导致配置了slf4j失效

**Comment by wenshao** [comment]
你可以通过JVM启动参数配置，-Ddruid.logType=slf4j

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AEdruid%E5%86%85%E7%BD%AE%E7%9A%84log%E5%AE%9E%E7%8E%B0
