### ISSUE TITLE
配置statefilter后，执行alter table yourtable truncate partition(part0)报错

### ISSUE THREAD

**Issue by fsyyyhl** [alibaba/druid#1083]
同样执行alter table yourtable add partition...也会报错
清空分区抛出异常：com.alibaba.druid.sql.parser.ParserException: error LPAREN 
增加分区抛出异常：com.alibaba.druid.sql.parser.ParserException: TODO : VALUES values

**Comment by wenshao** [comment]
什么数据库？什么版本？另能提供完整SQL语句么？

**Comment by wenshao** [comment]
这是mysql 5.7的语法，已经支持，等新版本1.0.18吧

**Comment by fsyyyhl** [comment]
oracle数据库，执行合并sql的时候报错，虽然不会影响功能，但看到报错总觉得不爽
图为执行分区表添加分区的sql报错
![image](https://cloud.githubusercontent.com/assets/6166434/17199513/053fc55e-54b0-11e6-8032-fcb22851cfd2.png)
