### ISSUE TITLE
testWhileIdle不起作用?

### ISSUE THREAD

**Issue by triffic-tang** [alibaba/druid#1101]
经过测试发现，应用在一段不活跃期(大约两个小时)之后，执行数据库连接时一直在等待中，debug发现`JdbcUtils.close(realConnection)`一直执行不下去，等待16分钟之后，才抛出`java.net.SocketException: Broken pipe`异常，我们推测在连接空闲一段时间之后，防火墙drop了应用到Oracle数据库之间的连接。

看了Druid的文档，发现配置`testWhileIdle=true`，则每隔一段时间执行`validationQuery`，对我们项目来说，这样可以防止防火墙drop空闲的数据库连接，但好像没有起作用，是我理解错了么，还是哪里设置不对。

找了些原先的issue，比如：
#594
#870

求指教，`testWhileIdle`的设置并未达到预期效果。

**Comment by wenshao** [comment]
druid的testWhileIdle和dbcp逻辑有点不一样，不是保活，而是取出时检测。针对你这种情况，容我再想想

**Comment by jerrycave** [comment]
确实如你@wenshao 所说，仔细看了下代码，Druid确实没有定时检测连接有效性的机制，后面想了个折中的办法，戳[http://www.triffic.cc/index.php/2016/03/11/druid-oracle-firewall/](url)，目前测试来看好像是正常的。

**Comment by wenshao** [comment]
新增加了参数maxEvictableIdleTimeMillis来处理这个问题https://github.com/alibaba/druid/commit/b66c366f93da2a7cd7324c7bb4ee9c08a748d7b2

**Comment by alchemystar** [comment]
我在DestroyThread里面加上了心跳连接的代码，还在测试阶段：
        //After the remove,we do heartbeat
        if (connections.length > 1) {
            for (int i = 0; i < heartBeatCount; i++) {
                try {
                    lock.lockInterruptibly();
                } catch (InterruptedException e) {
                    return;
                }
                //we get the first connection to do heartbeat with Locking
                DruidConnectionHolder connection = connections[0];
                if (connection == null || connection.getConnection() == null) {
                    LOG.info("The connection array is empty,no need hearbeat");
                    return;
                }
                //we remove it from the connection arrays with Locking
                try {
                    System.arraycopy(connections, 1, connections, 0, poolingCount - 1);
                    Arrays.fill(connections, poolingCount - 1, poolingCount, null);
                    poolingCount -= 1;
                } catch (Exception e) {
                    LOG.error("Remove connection from arrays,exception caught", e);
                } finally {
                    lock.unlock();
                }
                //now we can do the heartBeat without lock
                boolean validate = testConnectionInternal(connection.getConnection());
                LOG.info("now we do heartbeat");
                if (!validate) {
                    LOG.info("skip not validate connection.");
                    //if empty signal it
                    discardConnection(connection.getConnection());
                    destroyCount.incrementAndGet();
                    //if not valid,close it and do the next heart beat
                    continue;
                } else {
                    //we can't use lockInterruptibly,beacuse the connectin may lost
                    lock.lock();
                    //if valid,put the connection back
                    try {
                        //the poolingCount can increase
                        if(poolingCount < maxActive){
                            //if notempty not signal it
                            putLast(connection, System.currentTimeMillis());
                        }else{
                            discardConnection(connection.getConnection());
                            destroyCount.incrementAndGet();
                        }
                    } catch (Exception e) {
                        LOG.error("heartbeat put last exception caught ", e);
                    } finally {
                        lock.unlock();
                    }

                }
            }

**Comment by wenshao** [comment]
加上心跳不是好主意

**Comment by alchemystar** [comment]
心跳有神马问题么？线上流量一低，就容易出现getConnection Error

**Comment by wenshao** [comment]
druid-1.0.18应该解决这个问题了啊，你实时看？

**Comment by jc213** [comment]
maxEvictableIdleTimeMillis参数解决mysql 本身的连接断开，对于通过交换机访问数据库，由于交换机对长连接时效限制，导致tcp连接断开，也会出现长时间等待连接的情况（15分钟/30分钟），有可行的解决方案吗？

**Comment by jc213** [comment]
druid-1.0.18已经尝试了，还是有这个问题。

**Comment by jerrycave** [comment]
1、可以在数据库服务器侧加入定时检测的机制，以保活；
2、如果druid-1.0.18版本还是没解决这个问题，看来也只能在应用侧加入定时探测的机制；
@jc213

**Comment by jc213** [comment]
@jerrycave 
通过线上升级到drudi-1.0.18后，参数maxEvictableIdleTimeMillis不使用默认值，而是在配置文件中指定为600000，代码`<property name="maxEvictableIdleTimeMillis"><value>600000</value></property>`，目前线上再未发现长时间等待连接情况，还会继续跟进，你可以参考。

**Comment by 18691886351** [comment]
@guopengdreams @jerrycave 我在1.0.20也遇到这个问题。
netstat -an|grep 1521
物理连接是正常的，但是能看到发送队列中阻塞了94个字节。
<property name="testWhileIdle" value="true" />
<property name="timeBetweenEvictionRunsMillis" value="600000" />
<property name="validationQuery" value="SELECT 'x' FROM DUAL" />
应该是没有起作用，我在数据库查看最近执行的sql，并没有查询到执行的语句。

**Comment by HiAscend** [comment]
[https://github.com/alibaba/druid/issues/1568](url)

**Comment by charpty** [comment]
按照如下配置，数据主动关闭连接配置的是8个小时，但是发现没起作用
```
               // 配置间隔多久才进行一次检测需要关闭的空闲连接，单位是毫秒
		dataSource.setTimeBetweenEvictionRunsMillis(50000); // DEFAULT(60秒) = 60 * 1000
		// 配置一旦重试多次失败后等待多久再继续重试连接，单位是毫秒
		dataSource.setTimeBetweenConnectErrorMillis(18000); // DEFAULT(30秒) = 30 * 1000

		// 配置一个连接在池中最小生存的时间，单位是毫秒
		dataSource.setMinEvictableIdleTimeMillis(300000); // DEFAULT(半小时) = 1000 * 60 * 30
		// 这个特性能解决 MySQL 服务器8小时关闭连接的问题
		dataSource.setMaxEvictableIdleTimeMillis(25200000); // DEFAULT(7小时) = 1000 * 60 * 60 * 7
		// 允许物理连接最大存活时间，单位是毫秒
		// dataSource.setPhyTimeoutMillis(-1); // DEFAULT = -1
		// dataSource.setTestWhileIdle(true);
```

**Comment by minotaursu** [comment]
+1

**Comment by xmh51** [comment]
@charpty  你们解决了没？我也遇到了类似的问题

**Comment by wrke1990** [comment]
> @xmh51 我把检查时间改下并升级版本后没出现过了，另外也设置了jdbc连接的属性

能分享下借据方案吗？遇到同样的问题。

**Comment by xmh51** [comment]
检查下 事务是否长时间持有线程。

**Comment by xmh51** [comment]
> > @xmh51 我把检查时间改下并升级版本后没出现过了，另外也设置了jdbc连接的属性
> 
> 能分享下借据方案吗？遇到同样的问题。

检查下是否有线程长时间持有连接（比如长时间开启事务）。

**Comment by tangguochang** [comment]
> 检查下 事务是否长时间持有线程。
这条建议很靠谱啊，问题解决。谢谢

**Comment by xunzhaoderen** [comment]
https://github.com/alibaba/druid/releases/tag/1.0.28
新版本加入了keepAlive配置

**Comment by lizongbo** [comment]
请使用最新版验证

**Comment by superchangme** [comment]
是不是有interactive_timeout这个失效时间，keepAlive检测也没有用吖
