### ISSUE TITLE
解析Oracle带keep()函数的SQL时报异常

### ISSUE THREAD

**Issue by grayros** [alibaba/druid#1103]
scott用户，druid-1.0.17：
SQL语句：<code>SELECT MIN(t.deptno) KEEP(DENSE_RANK FIRST ORDER BY t.sal) a FROM emp t</code>
异常：<code>Caused by: java.sql.SQLException: sql injection violation, syntax error: TODO : KEEP KEEP : SELECT MIN(t.deptno) KEEP(DENSE_RANK FIRST ORDER BY t.sal) a FROM emp t</code>
<code>Caused by: com.alibaba.druid.sql.parser.ParserException: TODO : KEEP KEEP</code>
这个函数能不能用？能的话要怎么弄？

**Comment by wenshao** [comment]
收到，将会尽快修复
