### ISSUE TITLE
［重要］能否给出一份详细的配置文档及配置项介绍

### ISSUE THREAD

**Issue by zxj19880903** [alibaba/druid#1121]
@高铁
      你好，能否给出一份比较详细的配置文档及配置项的详细说明，这样可以快速的接入druid，也可以
对配置项有更深刻的理解
谢谢！

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98 这个不能满足需求么？

**Comment by zxj19880903** [comment]
嗯
    已经在看了，很感谢！
