### ISSUE TITLE
druid我log4jdbc一起使用的是后会出现not support oracle driver 1.0

### ISSUE THREAD

**Issue by strivezsh** [alibaba/druid#1124]
#default.driver=net.sf.log4jdbc.DriverSpy
#default.url=jdbc:log4jdbc:oracle:thin:@127.0.0.1:1521:orcl
default.driver=oracle.jdbc.OracleDriver
default.url=jdbc:oracle:thin:@127.0.0.1:1521:orcl
用上面的驱动就会报错
下面的就可以
ojdbc14_10.2.0.5.jar 驱动版本是这个 数据库是10GR2

**Comment by wenshao** [comment]
你更新一下oracle jdbc driver吧 
http://www.oracle.com/technetwork/database/features/jdbc/default-2280470.html

**Comment by strivezsh** [comment]
我觉得不是驱动的问题
同样的jar包 只是 写的驱动 不一样 才报的错
在写net.sf.log4jdbc.DriverSpy这个驱动的时候 没有去加载正确的jar包

**Comment by strivezsh** [comment]
@wenshao 
我找到问题了
log4jdbc只有驱动类在调用acceptsURL connect getPropertyInfo
这三个方法的时候 才会初始化 真是的驱动
否则 在获取版本的时候 判断 真是的 驱动为null 然后返回版本号为0
妹的 难道要我改源码么....
public int getMinorVersion()
	{
		if (lastUnderlyingDriverRequested == null)
		{
			return 0;
		}
		else
		{
			return lastUnderlyingDriverRequested.getMinorVersion();
		}
	}

**Comment by strivezsh** [comment]
又研究了一下文档 发现durid 也能实现log4jdbc的功能
<bean id="log-filter" class="com.alibaba.druid.filter.logging.Slf4jLogFilter">
	    <property name="connectionLogEnabled" value="false" />
	    <property name="statementLogEnabled" value="false" />
	    <property name="resultSetLogEnabled" value="false" />
	    <property name="statementExecutableSqlLogEnable" value="true" />
</bean>
配置这个 把最下面那个打开就可以了

**Comment by genericyzh** [comment]
@strivezsh 我也遇到同样的问题，但是按照这样添加bean后也还是同样的报错，请指教

**Comment by genericyzh** [comment]
我的锅，配置文件写错了。。

**Comment by hieastz** [comment]
druid和log4jdbc一起使用报错这个解决了吗？
