### ISSUE TITLE
【重要】【加急】关于新增过滤器最优的方式

### ISSUE THREAD

**Issue by boboChina** [alibaba/druid#1125]
目前我的做法是自己下载源码自己打包，因为需要在druid-filter.properties中添加过滤器，有没有在jar外编码的方式，这样我就可以一直用最新版本的jar了

**Comment by wenshao** [comment]
为啥有这个需求？

**Comment by boboChina** [comment]
加一个加密解密的中间件，我自己写了一个filter继承FilterAdapter 然后写自己的逻辑

**Comment by boboChina** [comment]
把自己写的过滤器上传了，不用看逻辑，看看包名，类名就大概知道了，如果是个常规需求楼主可以实现一套放到druid里面去


[DesensitizationConvert.java.txt](https://github.com/alibaba/druid/files/187728/DesensitizationConvert.java.txt)
[DesensitizationFilter.java.txt](https://github.com/alibaba/druid/files/187730/DesensitizationFilter.java.txt)
[DesensitizationParameter.java.txt](https://github.com/alibaba/druid/files/187731/DesensitizationParameter.java.txt)

**Comment by whx4J8** [comment]
我是直接将自定义的filter配置到proxyFilters中
`
		<property name="proxyFilters">
			<list>
				<ref bean="braveLogFilter"/>
			</list>
		</property>
`

然后像Log4jFilter一样继承LogFilter实现Log4jFilterMBean
`
public class BraveLogFilter extends LogFilter implements Log4jFilterMBean 
`

现在已经可以使用了,非常感谢您的解答

**Comment by wenshao** [comment]
支持的，你看这个代码
```java
// com.alibaba.druid.pool.DruidDataSource.initFromSPIServiceLoader
private void initFromSPIServiceLoader() {

    String property = System.getProperty("druid.load.spifilter.skip");
    if (property != null) {
        return;
    }

    ServiceLoader<Filter> druidAutoFilterLoader = ServiceLoader.load(Filter.class);

    for (Filter autoFilter : druidAutoFilterLoader) {
        AutoLoad autoLoad = autoFilter.getClass().getAnnotation(AutoLoad.class);
        if (autoLoad != null && autoLoad.value()) {
            if (LOG.isInfoEnabled()) {
                LOG.info("load filter from spi :" + autoFilter.getClass().getName());
            }
            addFilter(autoFilter);
        }
    }
}
```

**Comment by zone1511** [comment]
how to control the filter load sequence if using AutoLoad Annotation?
