### ISSUE TITLE
druid能否作为Hive的连接池

### ISSUE THREAD

**Issue by Fly365** [alibaba/druid#1127]
你好，在连接Hive时，能否使用druid作为Hive的连接池配置使用，和关系型数据库一样可以正常使用，非常感谢您的帮助！！！

**Comment by wenshao** [comment]
可以啊，符合jdbc规范的就可以

**Comment by Fly365** [comment]
非常感谢您的帮助，再次感谢帮助！！

**Comment by ffpeng90** [comment]
像各种sql on hadoop的组件，一般都会提供jdbc接口， 这些jdbc链接，都能通过druid来管理和监控么？
