### ISSUE TITLE
spring，springmvc，mybatis，tomcat整合报下面的错，有人遇到过吗？

### ISSUE THREAD

**Issue by serical** [alibaba/druid#1133]
Annotation-specified bean name 'log' for bean class [com.mysql.jdbc.log.Log] conflicts with existing, non-compatible bean definition of same name and class [com.alibaba.druid.support.logging.Log]

**Comment by HiAscend** [comment]
我也遇到了这种情况，请问该如何解决？配置如下
 <spring.version>4.2.5.RELEASE</spring.version>
<spring.mybatis.version>1.3.0</spring.mybatis.version>
<mybatis.version>3.4.0</mybatis.version>
<druid.version>1.0.29</druid.version>
<mysql.jdbc.version>5.1.41</mysql.jdbc.version>

**Comment by serical** [comment]
不要意思 才看到😅
https://github.com/serical/blogs/blob/master/java/Idea%E6%95%B4%E5%90%88spring%EF%BC%8Cspringmvc%EF%BC%8Cmybatis%EF%BC%8Ctomcat%E9%81%87%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98.md#2
两个log冲突的问题

2017-03-25 10:58 GMT+08:00 sugar <notifications@github.com>:

**Comment by KevinBlandy** [comment]
我也遇到这个问题了  => https://springboot.io/t/topic/3379
 @serical @HiAscend 大佬们怎么处理的？
