### ISSUE TITLE
连接远程MYSQL数据库，超时异常

### ISSUE THREAD

**Issue by massinger** [alibaba/druid#1136]
本机地址192.168.31.11，连接这样一个地址jdbc:mysql://191.168.31.66:3306/gpgc?useUnicode=true&characterEncoding=UTF-8
如果把后面的url参数去掉，可正常连接
加上后面的useUnicode和chartset就会变成连接超时

在本地数据库则不会出现这样的情况

**Comment by boboChina** [comment]
和druid无关，先看看你配置文件的编码  &是不是需要转义  再看看你安装的mysql支不支持这些字符集
或者你先用dbcp先试验一下。

**Comment by wenshao** [comment]
这个和druid无关，先关闭啦
