### ISSUE TITLE
druid不能解析"select * FROM a JOIN b ON a.c=b.c AND 其它条件.."这种形式.

### ISSUE THREAD

**Issue by yx91490** [alibaba/druid#1151]
解析的时候因为没有出现关键字where而没有解析出条件来,但是在mysql或者db2上测试连接条件后面可以跟其它条件.使用的是最新1.0.18版.

**Comment by wenshao** [comment]
请提供完整的sql样本

**Comment by yx91490** [comment]
SELECT TABLE1.F_0201, TABLE2.F_0204, TABLE1.F_0802, TABLE1.F_0810
	FROM TABLE1
		JOIN TABLE2 ON TABLE2.F_0201 = TABLE1.F_0201
			AND TABLE1.F_0802 BETWEEN '199501' AND '199502'
			AND TABLE1.F_0840 = '1'
			AND TABLE1.F_0810 IS NULL

**Comment by zhujunxxxxx** [comment]
测试过你这个SQL，可以解析出来呀！

**Comment by yx91490** [comment]
不是说解析不出来,可能我理解的解析有点偏差,我是想要它更智能一些.让on后面只接连接的条件,其他条件放到wherelist里面.

**Comment by zhujunxxxxx** [comment]
这个只是提供解析，并不提供这种优化操作
