### ISSUE TITLE
1.0.16版本无法解析多个并列语句

### ISSUE THREAD

**Issue by boboChina** [alibaba/druid#1152]
update tab set a=1 where id=1;update tab set a=1 where id=2;

**Comment by wenshao** [comment]
什么数据库？

**Comment by boboChina** [comment]
mysql   后来在连接字符串中加上了allowMultiQueries=true  可以正常执行了  但是拦截器不拦截这个sql了

**Comment by wenshao** [comment]
缺省就是拦截的啊，不支持一次执行多条语句

**Comment by boboChina** [comment]
可能楼主没遇到这个情况，没事已经解决了，后面如果还有兄弟遇到这种需要沟通的可以联系我
