### ISSUE TITLE
通过用户名密码访问总是提示用户名或者密码出错

### ISSUE THREAD

**Issue by Leonardawp** [alibaba/druid#1153]
<servlet>       
  		<servlet-name>DruidStatView</servlet-name>     
  		<servlet-class>com.alibaba.druid.support.http.StatViewServlet</servlet-class>
  		
  		<init-param>
        	<param-name>resetEnable</param-name>
        	<param-value>false</param-value>
    	</init-param>
    	<init-param>
			
			<param-name>loginUsername</param-name>
			<param-value>admin</param-value>
		</init-param>
		<init-param>
			
			<param-name>loginPassword</param-name>
			<param-value>admin</param-value>
		</init-param>
	</servlet>   
	<servlet-mapping>     
   		<servlet-name>DruidStatView</servlet-name>  
   		<url-pattern>/druid/*</url-pattern>
 	</servlet-mapping>

**Comment by Leonardawp** [comment]
问题解决了，是其他的filter影响的。你们的产品很棒，就是sql解析有点问题。加油！

**Comment by wenshao** [comment]
sql解析如果遇到问题，请反馈，我会隔一段时间修复一次
