### ISSUE TITLE
关于#1125的追问 

### ISSUE THREAD

**Issue by boboChina** [alibaba/druid#1159]
怀着崇高的敬意追问一下：
   现状是druid在高速发展，新版本更新很快，但是我确实有需要要在jdbc层编程，需要增加自己的过滤器，看源码的思路是配置文件中配置一下,然后那个filterManager去载入。目前我就是修改了druid-filter.properties 然后新增自己的filter 。已经投入生产了。但是一直在发现bug，一直也在社区反馈。目前最头疼的就是主干升级了我要去比对文件然后更新过来 这样子好尴尬。能不能提供jar外编程的插件方式。
详解#1125

**Comment by han-feng** [comment]
有没有试过，在自己项目jar包中添加META-INF/druid-filter.properties文件，这个文件里只定义自己的过滤器别名，保证过滤器名字不与已有的重复即可。

**Comment by boboChina** [comment]
这种方式适合单一项目，但是我改写的jar是作为公共组件放到maven的私服作为很多项目调用的，不能在每个子项目都去修改的，谢谢楼上的建议

**Comment by han-feng** [comment]
你自己增加的过滤器的META-INF/druid-filter.properties文件可以放在你自己的公共组件jar里呀，看了一下FilterManager，可以支持这种方式的。

**Comment by wenshao** [comment]
@boboChina 请确认@han-feng 的答案是否满足你的需求，如有问题尽快反馈，周末我会发布一个小的更新版本

**Comment by boboChina** [comment]
@wenshao   楼主  han-feng的我试过了  和classloader绑定有关系 不可取 。然后：
    public void test_loadFilter() throws Exception {
        Exception error = null;

        try {
            FilterManager.loadFilter(new ArrayList<Filter>(), ErrorFilter.class.getName());
        } catch (SQLException e) {
            error = e;
        }
        Assert.assertNotNull(error);
    }
    
    public void test_loadFilter_2() throws Exception {
        Exception error = null;
        
        try {
            FilterManager.loadFilter(new ArrayList<Filter>(), ErrorFilter.class.getName());
        } catch (SQLException e) {
            error = e;
        }
        Assert.assertNotNull(error);
    }
    

    public static class ErrorFilter extends FilterAdapter {

        public ErrorFilter(){
            throw new RuntimeException();
        }
    }

这种方式也是jar内部的方式。需要的是jar外的方式

**Comment by wenshao** [comment]
用jvm启动参数-D也可以的，比如
```java
-Ddruid.filters=stat,wall
```
