### ISSUE TITLE
security springboot druid 

### ISSUE THREAD

**Issue by licker001** [alibaba/druid#1162]
整合druid 新增servlet后 无法进入匹配路径无法进去，每次都找不到页面404，都没有进去servlet

**Comment by licker001** [comment]
package sample.mybatis.druid;

import javax.servlet.annotation.WebFilter;
import javax.servlet.annotation.WebInitParam;

import com.alibaba.druid.support.http.WebStatFilter;

/**
 * Druid的StatFilter
 */
@WebFilter(filterName="druidWebStatFilter",urlPatterns="/*",
    initParams={
        @WebInitParam(name="exclusions",value="*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico")// 忽略资源
})
public class DruidStatFilter extends WebStatFilter  {

}

**Comment by licker001** [comment]
package sample.mybatis.druid;

import javax.servlet.annotation.WebInitParam;
import javax.servlet.annotation.WebServlet;

import org.springframework.boot.web.servlet.ServletComponentScan;

import com.alibaba.druid.support.http.StatViewServlet;

//@ServletComponentScan
@SuppressWarnings("serial")
@WebServlet(urlPatterns = "/druid/*", 
    initParams={
            @WebInitParam(name="resetEnable",value="false")// 禁用HTML页面上的“Reset All”功能
    })
public class DruidStatViewServlet extends StatViewServlet {
	
}

**Comment by wenshao** [comment]
你的代码是什么意思？

**Comment by cjsky666** [comment]
我也是这样springboot 整合durid之后 localhost:8080/durid/index.html报index.html404错误 进不去  说是在application.java类上添加@ServletComponentScan 注解就可以 但是无效~~~

**Comment by lizongbo** [comment]
请使用最新版验证
