### ISSUE TITLE
希望增加一个功能，获取select语句最终选出字段

### ISSUE THREAD

**Issue by Janzee** [alibaba/druid#1164]
包含子查询的sql语句，比如
select u.name, u.age from (select * from user) u;
想要获取到name和age这两个字段目前暂不支持，只能获取到子查询中的*，而且子查询的别名u这个字段暂不支持语法分析，希望以后可以得到支持，谢谢

**Comment by boboChina** [comment]
目前sqlparser这一块确实做的相对没那么完善 坐等吧

**Comment by boboChina** [comment]
可以获取，提问要严谨啊，楼主很忙，把回答问题的时间留给真正需要回答的问题
MySqlStatementParser parser = new MySqlStatementParser(sql);
		List<SQLStatement> statementList = parser.parseStatementList();
		for (SQLStatement statement : statementList) {
		    if (statement instanceof SQLSelectStatement) {
			SQLSelect select = ((SQLSelectStatement) statement).getSelect();
			SQLSelectQueryBlock query = (SQLSelectQueryBlock) select.getQuery();
			System.out.println(query.getSelectList());//这里打印的就是name，age
			if(query.getFrom() instanceof SQLSubqueryTableSource){
			    SQLSubqueryTableSource ssts = (SQLSubqueryTableSource)query.getFrom();
			    MySqlSelectQueryBlock mssqb = (MySqlSelectQueryBlock) ssts.getSelect().getQuery();
			    System.out.println(mssqb.getSelectList());//这里打印的就是子查询的*
			}

看完源码再提问，楼主就可以省出来时间回答我的问题了

**Comment by Janzee** [comment]
多谢 @boboChina 解答，主要是现在没有搞清楚API怎么用法，我试了一下，用你的方法确实可以获取到
