### ISSUE TITLE
希望能在源码中增加注释

### ISSUE THREAD

**Issue by jaune162** [alibaba/druid#1165]
阿里是国内做开源做的最好的公司，阿里让我看到了国内开源的希望。
希望能在代码中添加更多的注释以便大家学习源码

**Comment by boboChina** [comment]
写的好的代码就是注释  没这个必要去写一堆看名字就懂的注释  倒是主要的一些模块的设计思想 时序图之类的可以弄一下

**Comment by wenshao** [comment]
好建议，但是好多，做不完

**Comment by yx91490** [comment]
可不可以先定一个注释的规范,然后将整个系统分解成一个个小的部分,然后由社区来做,您审阅后合并?

**Comment by lizongbo** [comment]
用AI辅助来阅读代码吧
