### ISSUE TITLE
getConnection报已关闭的连接的问题

### ISSUE THREAD

**Issue by fevermxp** [alibaba/druid#1167]
testWhileIdle，validationQuery，timeBetweenEvictionRunsMillis均已设置，但从监控页面的SQL执行来看，链接验证并没有按照设置的时间工作。当与数据库连接不稳定或者连接长时间未操作造成数据库连接time_out时，向连接池请求连接会报已关闭连接的错误，只能重启tomcat恢复。有解决办法吗？

**Comment by p0mp0k0** [comment]
同样的问题，我在网上搜了一下，看到很多人都遇到这个问题，但都没解

**Comment by wenshao** [comment]
什么版本？

**Comment by fevermxp** [comment]
温少，目前使用的版本就是1.0.18，数据库是oracle，数据库是远程数据库存在网络闪断的可能性。JDBC直连的话也会出现断开，但是下次请求就会恢复，使用连接池不能自动恢复连接。
