### ISSUE TITLE
使用spring boot ，Druid的内置监控页面出错。

### ISSUE THREAD

**Issue by zsumore** [alibaba/druid#1168]
/druid/datasource.html 页面数据正常；
/druid/sql.html  页面不显示SQL查询记录数据，但程序能正确读取数据库数据

spring boot Druid初始化代码
@Bean
    public ServletRegistrationBean dispatcherRegistration(DispatcherServlet dispatcherServlet) {
        ServletRegistrationBean registration = new ServletRegistrationBean(dispatcherServlet);
        registration.addUrlMappings("/*");
        //printStacks();
        return registration;
    }

```
@Bean
public ServletRegistrationBean servletRegistrationBean() throws ServletException {
    //printStacks();
    ServletRegistrationBean registration = new ServletRegistrationBean(new StatViewServlet(), "/druid/*");
    registration.setLoadOnStartup(0);
    return registration;
}
```

**Comment by zsumore** [comment]
希望增加spring boot 的Druid配置说明

**Comment by lizongbo** [comment]
请使用最新版验证
