### ISSUE TITLE
如何解决内存泄漏问题

### ISSUE THREAD

**Issue by Kumhy** [alibaba/druid#1173]
IDE开发部署项目的时候配置有问题，修改后热部署报以下警告，并且上一次部署时获取连接的线程还在继续，一直都是获取连接错误。

`20-Apr-2016 22:54:25.958 WARNING [http-apr-8181-exec-21] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [springmvc] appears to have started a thread named [Druid-ConnectionPool-Create-242721800] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1990)
20-Apr-2016 22:54:25.959 WARNING [http-apr-8181-exec-21] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [springmvc] appears to have started a thread named [Druid-ConnectionPool-Destroy-242721800] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:2032)`

​

**Comment by wenshao** [comment]
需要调用DruidDataSource.close方法
