### ISSUE TITLE
DruidDataSourceFactory.createDataSource 不能读取配置文件name属性

### ISSUE THREAD

**Issue by Kumhy** [alibaba/druid#1174]
prop:
name=test
url=jdbc:mysql://localhost:3306/test 
username=root
password=123456

DruidDataSource dataSource = (DruidDataSource) DruidDataSourceFactory.createDataSource(prop);

通过DruidDataSourceFactory.createDataSource创建的DruidDataSource，在DruidStatView看到是没有生效的

**Comment by wenshao** [comment]
已经支持，请等待新版本
