### ISSUE TITLE
在DB2中不能把concat解析为关键字,只能解析为函数

### ISSUE THREAD

**Issue by yx91490** [alibaba/druid#1190]
sql解析器解析下面的sql语句时会抛出异常,而该sql语句能正常执行.

	SELECT A.F_0201, A.F_0301, A.F_0802, A.F_2100
	FROM A, B
	WHERE B.F_2211 = '5'
		AND A.F_0301 = B.F_0301
		AND Substr(B.F_0815, 1, 4) concat  Substr ( B.F_0815,5,2 ) > A.F_0802
		AND A.F_2100 > 0
	UNION
	SELECT A.F_0201, A.F_0301, A.F_0802, A.F_2100
	FROM A
	WHERE A.F_0301 NOT IN (SELECT F_0301
			FROM B)
		AND A.F_2100 > 0

**Comment by wenshao** [comment]
能够提供语法文档么？这样也支持？

**Comment by yx91490** [comment]
只找到了这些,能用上吗?

1. ftp://ftp.software.ibm.com/ps/products/db2/info/vr95/pdf/en_US/db2s1e950.pdf
(此ftp服务器下还有许多不同版本的sql reference.)
2. http://www.ibm.com/support/knowledgecenter/SSGLW6_5.2.0/com.ibm.p8.ce.dev.ce.doc/query_sql_syntax_db2.htm?lang=zh

**Comment by wenshao** [comment]
应该不影响运行吧？如果你只是配置了filters="stat"，只会打印错误日志，不影响运行

**Comment by wenshao** [comment]
已经解决，等1.0.19版本吧，预计一个星期内会发布
