### ISSUE TITLE
采用config.file来定义数据源则dbType获取不了，返回NULL

### ISSUE THREAD

**Issue by rainsoft** [alibaba/druid#1193]
if (this.dbType == null || this.dbType.length() == 0) {
                this.dbType = JdbcUtils.getDbType(jdbcUrl, null);
            }

            for (Filter filter : filters) {
                filter.init(this);
            }

DruidDataSource的init方法中，dbType的赋值在filter.init前，如果我们采用ConfigFilter来配置数据源，由于jdbcUrl是在ConfigFilter中才会设置，所以dbType就获取不了，能否调整一下上述代码的顺序？

**Comment by wenshao** [comment]
你说的对，你来提交一个patch？

**Comment by wenshao** [comment]
问题解决，请等几天后发布新版本1.0.19
