### ISSUE TITLE
数据库session连接过高问题

### ISSUE THREAD

**Issue by wwg88888888** [alibaba/druid#1195]
hi，
     由于我的应用部署了一个集群，在正式环境中有多个应用使用同一个oracle数据库实例，只是用户有区别，在使用过程中，由于每个应用集群的每个节点都配置了连接池属性，造成数据库session连接过高，导致数据库无法正常访问。针对这类问题，有什么好的办法吗？

**Comment by boboChina** [comment]
你做rac咯

**Comment by wenshao** [comment]
减少每个应用的连接数量，druid连接池的一些设计就是为了省连接而做的
