### ISSUE TITLE
Mysql连接泄露问题

### ISSUE THREAD

**Issue by eXcellme** [alibaba/druid#1202]
Mysql服务器wait_timeout为120秒，发现数据库连接池使用的数据库连接，在一段时间后tcp连接会变成can't identify protocol，导致句柄数逐渐累积（removeAbandoned功能已经开启）

**Comment by wenshao** [comment]
你的意思是removeAbandoned不起作用？

**Comment by eXcellme** [comment]
是的，我用的1.0.14版本的，查了线上几个应用都有类似问题，我们的mysql wait_timeout时间配置是2分钟，我用wireshark查看发现连接空闲2分钟后mysql服务器发来主动关闭的tcp包，应用这边的连接没有正常关闭，有一部分从CLOSE_WAIT变成了can't identify protocol。
准备升级高版本测试，看了下maxEvictableIdleTimeMillis和phyTimeoutMillis好像都是解决这个问题的，不知应该选哪个？

**Comment by zhangjianweibj** [comment]
removeAbandonedTimeout 时间设置依据是什么？

**Comment by eXcellme** [comment]
@zhangjianweibj 我设置的3分钟，调试用

**Comment by zhangjianweibj** [comment]
是这个参数 timeBetweenEvictionRunsMillis起作用，检测空闲连接的时间间隔

**Comment by eXcellme** [comment]
@zhangjianweibj timeBetweenEvictionRunsMillis我设置的50秒

**Comment by eXcellme** [comment]
升级到1.0.19，一个系统配置maxEvictableIdleTimeMillis为100000毫秒，phyTimeoutMillis为-1，观察can't identify protocol ，过一会儿会出现，但是数量会有变化，有降低有增加。查看dao日志，发现在执行validateQuery时，抛出了异常"com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure "。
另一个系统配置maxEvictableIdleTimeMillis为100000毫秒，phyTimeoutMillis为110000，观察can't identify protocol ，没有出现，且没有异常。

**Comment by zhangjianweibj** [comment]
你的mysql wait_timeout时间配置是2分钟=120000，你试试phyTimeoutMillis小于120000其他的数值有效吗？感觉maxEvictableIdleTimeMillis，timeBetweenEvictionRunsMillis参数没起作用。
