### ISSUE TITLE
sql分页插件对sqlserver支持有问题

### ISSUE THREAD

**Issue by truechuan** [alibaba/druid#1205]
sqlserver sql  = select * from test t with (nolock)
PagerUtils.limit(sql,dbType,page.getStartRow(),page.getPageSize());
 当参数带了with (nolock) 时，解析的sql类似是 select top 10 * from test with (nolock) t
这个语法是错误的，应该是select top 10 * from test t with (nolock)

**Comment by wenshao** [comment]
收到

**Comment by wenshao** [comment]
问题已经修复，请等待下一个版本1.0.19发布，预计一个星期内

**Comment by truechuan** [comment]
有没有群什么的，我自己编译代码来操作吧

发自我的 iPhone

**Comment by wenshao** [comment]
有钉钉群

**Comment by truechuan** [comment]
给个群账号呢  我搜温少找不到你哈

发自我的 iPhone
