### ISSUE TITLE
select truncate() 支持的问题

### ISSUE THREAD

**Issue by zhuam** [alibaba/druid#1208]
```sql
select truncate(12.0123,2);
```
mysql直连给出的结果会是 12.01

但通过druid 查询报错：
ERROR 1064 (HY000): com.alibaba.druid.sql.parser.ParserException: ERROR. token : TRUNCATE, pos : 15

**Comment by wenshao** [comment]
用的是啥版本？

**Comment by wenshao** [comment]
问题解决

**Comment by zhuam** [comment]
THANKS

**Comment by naxiwer** [comment]
谢谢
