### ISSUE TITLE
当数据库列中使用了ORACLE数据库关键字Exception时报错

### ISSUE THREAD

**Issue by mfkvfn** [alibaba/druid#1211]
为了记录异常信息到Oracle数据库日志表中，sql为
insert into sys_log(ID,EXCEPTION) values(?,?)
会报错。原因是druid中认为EXCEPTION是oracle关键字。改成
insert into sys_log(ID,"EXCEPTION") values(?,?)
也不行。

不用druid的话以上2条语句都能正常执行，用了druid都无法执行。

注：ID为char(32)类型，EXCEPTION为CLOB。

**Comment by wenshao** [comment]
你在filters上配置了wall（SQL防火墙）？

**Comment by wenshao** [comment]
如果没有配置filters="wall"，那样只会打印error log。同时我也修正了此问题，等过几天发布新版本吧

**Comment by mfkvfn** [comment]
filters只配置了config,stat。已自己下载并编译mater代码，测试通过，期待新版本。
另外，你们响应issue速度很快。赞一个。
