### ISSUE TITLE
druid 1.0.16 prepareCall报connection holder is null

### ISSUE THREAD

**Issue by p0mp0k0** [alibaba/druid#1229]
运行一段时间后就会报，感觉像是连接超时断掉了，但配置了
testOnBorrow    true
testOnReturn    true
testWhileIdle   true

仍然是这个现象

**Comment by wenshao** [comment]
你是存在跨线程使用连接么？

**Comment by p0mp0k0** [comment]
没有，是单独启动了一个连接池专门给调用存储过程使用，但存储过程不常用，只有在偶尔的特定情况下会调用，服务刚启动不会报错，就是长时间闲置后再调用就会报这个错，该加的参数都加了

**Comment by wenshao** [comment]
什么版本？如果是不常使用的连接池，你升级到1.0.18之后的版本不会有这个问题

**Comment by p0mp0k0** [comment]
标题就写了版本的 1.0.16
升级到1.0.18还需要配其他什么参数吗？

**Comment by wenshao** [comment]
升级到1.0.18或者1.0.19都可以，原因是mysql server处理8小时空闲的连接，执行语句之后testWhileIdle之后，有些场景服务端会突然断开

**Comment by wenshao** [comment]
关闭了连接然后再使用也会出现这个错误

**Comment by janchengwang** [comment]
我的版本是1.0.13,我是在定时器里面获取数据库连接就报这个错误了。其他都好好的。

**Comment by lizongbo** [comment]
请使用最新版验证
