### ISSUE TITLE
DruidDataSource不能destroy，要去掉init-method="init"

### ISSUE THREAD

**Issue by zhanglei86** [alibaba/druid#1234]
## druid配置连接mysql
<bean id="dataSource1" class="com.alibaba.druid.pool.DruidDataSource" init-method="init" destroy-method="close">

## tomcat报错
11-May-2016 12:03:14.574 WARNING [http-nio-8080-exec-3]
org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads
The web application [ytst-api-framework] appears to have started a thread named [Druid-ConnectionPool-Destroy-934370022]
but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:2032)

去掉init-method="init"配置，问题解决。

请问：是我的mysql权限问题，还是DruidDataSource.destroy的Bug?不加init-method="init",会存在什么风险？

**Comment by wenshao** [comment]
tomcat报警而已吧？

**Comment by zhanglei86** [comment]
把init-method="init"又加上了，好像是不影响服务启动，暂时没try到之前服务失败的问题，继续跟踪吧。
刚把服务部署到阿里云ECS，连接公网mysql库，出现的连接池问题，导致应用服务启动失败（tomcat能正常）。
谢谢回复！
