### ISSUE TITLE
使用druid解析sql批量插入语句时出错，无法解析

### ISSUE THREAD

**Issue by leezongjie** [alibaba/druid#1237]
使用SQLUtils.parseStatements(sql,dbtype)解析sql语句，在进行解析类似insert into t (id,name) values (?,?), (?,?), (?,?)批量插入语句时，出现错误，表现在解析完一个插入列后便结束后面的解析，造成下一个COMMA无法解析的错误，
src/main/java/com/alibaba/druid/sql/parser/SQLStatementParser.java   line:1475-1481
`        if (lexer.token() == Token.VALUES) {
            lexer.nextToken();
            accept(Token.LPAREN);
            SQLInsertStatement.ValuesClause values = new SQLInsertStatement.ValuesClause();
            this.exprParser.exprList(values.getValues(), values);
            insertStatement.setValues(values);
            accept(Token.RPAREN);
        }`

@wenshao 这是否是一个bug？或者使用方式不正确？如果是bug，可否尽快修复

**Comment by wenshao** [comment]
没指定dbType？比如说dbType="mysql"

**Comment by leezongjie** [comment]
已经指定了，db2

**Comment by wenshao** [comment]
这个是mysql的专有语法吧，db2有支持这个？

**Comment by leezongjie** [comment]
支持的，中小数据量时一直在这么用，我们有个新组件中使用到druid分析sql，有项目组提出在使用过程中报错，发现是这个原因，希望druid可以支持这个语法，目前打算临时改用BATCH提交

**Comment by wenshao** [comment]
已经支持，请等待下一个版本
