### ISSUE TITLE
强烈要求增加数据库连接的保活功能

### ISSUE THREAD

**Issue by zpa3x60** [alibaba/druid#1269]
testWhileIdle 能不能做成用守护线程测试连接的活性？也就是定时发心跳检测连接的活性。

因为我们这边由于网络，防火墙，数据库oracle原因。连接很不可靠。如果获取连接已经断了，在做testWhileIdle测试时，得经过JDBK中配置CONNECT_TIMEOUT和readTimeout后才能知道此链接不可用，太耗时间了。
你们为了mysql 8小时原因增加了maxEvictableIdleTimeMillis属性，为什么不增加守护线程发心跳来检查连接活性？
Druid 版本 1.0.20

**Comment by wenshao** [comment]
收到

**Comment by zhanyigo** [comment]
@wenshao 请问会加入这个功能吗？我们也同样有这个问题。

Druid版本：1.0.9、1.0.31

**Comment by lizongbo** [comment]
请使用最新版验证效果
