### ISSUE TITLE
druid不能解析以full为别名的sql

### ISSUE THREAD

**Issue by terryzhu** [alibaba/druid#1270]
druid不支持select full full from t1的语句
其中full为一个列名,第二个full为别名
但是mysql db是可以接受这条sql而不报错的

**Comment by zhangjianweibj** [comment]
改成：select full as full from t1

**Comment by wenshao** [comment]
为什么一定要这么写呢？

**Comment by terryzhu** [comment]
主要是有ORM框架,不写as,把所有列名都隐式地声明了一个alias发到db

**Comment by wenshao** [comment]
已经支持，请使用新版本 https://github.com/alibaba/druid/releases/tag/1.0.30
