### ISSUE TITLE
druid解析ddl失败-字段名是关键字解析失败

### ISSUE THREAD

**Issue by djjsindy** [alibaba/druid#1271]
收集到的关键字：
comment
sequence
open
user
view
begin
function
sequence
enable
primary
end
close
escape
disable
cast
row

如果列名或者index等名字是关键字，那么会导致sql解析失败

**Comment by gonedays** [comment]
关键字需要用反单引号``括起来

**Comment by wenshao** [comment]
本来就不应该支持，先关闭啦
