### ISSUE TITLE
MysqlWallTest23同一个条件不同的测试结果，为何？？？

### ISSUE THREAD

**Issue by zhangjianweibj** [alibaba/druid#1272]
public void test_true() throws Exception {
        Assert.assertTrue(WallUtils.isValidateMySql(//
        "select count(*) total from utao_goods where 1=1  and pprice between 0 and 99999 and state=1")); //
    }
    
    public void test_false() throws Exception {
        Assert.assertFalse(WallUtils.isValidateMySql(//
        "select count(*) total from utao_goods where pprice between 0 and 99999 and state=1 and 1=1")); //
    }

**Comment by wenshao** [comment]
永真条件（1=1）前置注入风险小，后置的风险很大
