### ISSUE TITLE
DruidDataSource inited 多次，停不下来

### ISSUE THREAD

**Issue by xiaopan0513** [alibaba/druid#1278]
[INFO ] 2016-06-06 23:29:57,841 com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:638) init - {dataSource-1407} inited
[INFO ] 2016-06-06 23:29:57,853 com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:638) init - {dataSource-1408} inited
[INFO ] 2016-06-06 23:29:57,863 com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:638) init - {dataSource-1409} inited

配置文件如下：
  <bean id="stat-filter" class="com.alibaba.druid.filter.stat.StatFilter">
    
    <property name="slowSqlMillis" value="2000" />
      <property name="logSlowSql" value="true" />
  </bean>

  <bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource" init-method="init" destroy-method="close">
      
      <property name="url" value="${jdbc.url}" />
      <property name="username" value="${jdbc.username}" />
      <property name="password" value="${jdbc.password}" />

```
  <!-- 配置初始化大小、最小、最大 -->
  <property name="initialSize" value="1" />
  <property name="minIdle" value="1" />
  <property name="maxActive" value="20" />

  <!-- 配置获取连接等待超时的时间 -->
  <property name="maxWait" value="${jdbc.maxWait}" />

  <!-- 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 -->
  <property name="timeBetweenEvictionRunsMillis" value="60000" />

  <!-- 配置一个连接在池中最小生存的时间，单位是毫秒 -->
  <property name="minEvictableIdleTimeMillis" value="300000" />

  <!-- 测试有效用的SQL Query -->
  <property name="validationQuery" value="SELECT 'x'" />
  <!-- 连接空闲时测试是否有效 -->
  <property name="testWhileIdle" value="true" />
  <!-- 获取连接时测试是否有效 -->
  <property name="testOnBorrow" value="false" />
  <!-- 归还连接时是否测试有效 -->
  <property name="testOnReturn" value="false" />

  <!-- 超过时间限制是否回收 -->
  <!--<property name="removeAbandoned" value="true" />-->
  <!-- 超时时间；单位为秒。180秒=3分钟 -->
  <!--<property name="removeAbandonedTimeout" value="180" />-->

  <!-- 打开PSCache，并且指定每个连接上PSCache的大小 分库分表较多的数据库，建议配置为false -->
  <property name="poolPreparedStatements" value="false" />
  <property name="maxPoolPreparedStatementPerConnectionSize" value="20" />

  <!-- 定期把监控数据输出到日志中 -->
  <!-- <property name="timeBetweenLogStatsMillis" value="300000" /> -->

  <property name="proxyFilters">
    <list>
      <!-- 配置监控统计拦截的filters -->
        <ref bean="stat-filter" />
    </list>
  </property>
```

  </bean>

**Comment by zhangjianweibj** [comment]
看初始化代码，inited变量是volatile，并不能保证多线程的同时并发访问。不过这样的情况很少见吧。
protected volatile boolean                         inited                                    = false;
<img width="731" alt="default" src="https://cloud.githubusercontent.com/assets/18585129/17841381/67bb374c-684a-11e6-827f-83de40275463.png">

**Comment by liuyuanyuan** [comment]
这个问题我也遇到过，明明是使用同一个DataSource来getConnection,但日志确是持续在init 新的 datasource，导致连接也很多，执行close也没有关闭。很奇怪的现象。

**Comment by lizongbo** [comment]
请使用最新版验证
