### ISSUE TITLE
监控页面，看不到URI部分带`.json`后缀的详情。

### ISSUE THREAD

**Issue by renfufei** [alibaba/druid#1279]
1.0.14版本是好的，URI监控，详情: 类似于 [/druid/weburi-detail.html?uri=/./qrcode/input.php](http://www.cncounter.com/druid/weburi-detail.html?uri=/./qrcode/input.php) 这样的URI。

但是在1.0.18版本，URI详情就是空的。 请问是什么原因?

**Comment by wenshao** [comment]
1.0.20版本是否也有类似的问题？

**Comment by renfufei** [comment]
经过简单的验证。 发现不是版本问题。 1.0.14 - 1.0.20 都是一样的表现。
初步判定是 后缀名为 `.json`的请求,不能得到URI详情信息。

是否是因为 StatViewServlet 对 `json` 后缀名做了某种拦截?
例如: `/druid/weburi-detail.html?uri=/qrcode/ajax/genqrcode.json`

假若在 SpringMVC 中配置同一个方法给2个访问路径:
`@RequestMapping(value = {"/qrcode/ajax/genqrcode.json","/qrcode/ajax/genqrcode.jpeg"})`
则 `.jpeg`路径是OK的，而 `.json` 的详情就是看不到,  `.php`或者其他后缀也是可以看到统计信息的。


感谢!

**Comment by renfufei** [comment]
具体为: `/druid/weburi-/qrcode/ajax/genqrcode.json.json` 类似这样的请求，返回的内容为:
`{"ResultCode":1,"Content":null}`
