### ISSUE TITLE
定时连接有效性检查的支持

### ISSUE THREAD

**Issue by kenny319** [alibaba/druid#1281]
我们发现druid并没有像其他连接池一样有一个独立的线程用于定时检查连接的有效性，但是大部分的生产环境中的数据库都会有连接超时设置比如两分钟，导致的问题是系统一旦超过两分钟没有流量所有的连接都会被数据库关闭，而一旦短时间内有较大流量进来时（部分业务场景如秒杀等），部分请求可能会由于排队等待创建连接而导致响应时间过长，尤其在大量服务化和分库的场景下，等待服务的响应时间会被放大。
请问这个设计的初衷是什么？
当前该如何这种burst traffic的问题？
后续是否可以提供相关的功能支持？

**Comment by zpa3x60** [comment]
由于没这个功能，我都想从druid换成出其它的连接池了。因为性能稳定是第一。

**Comment by daokunzhu1107** [comment]
没看源码，难道testWhileIdle=true的参数配置是假的

**Comment by daokunzhu1107** [comment]
还有 timeBetweenEvictionRunsMillis

**Comment by daokunzhu1107** [comment]
看了一下源码，还真没有。
因为druid是参考dbcp的配置来的，那相关的参数其实是没有合理使用的。
testWhileIdle，是否在空闲时测试，即测试空闲连接
timeBetweenEvictionRunsMillis 测试空闲连接的回收线程间隔多长时间运行一次
numTestsPerEvictionRun 每次回收线程运行时，测试几个连接
在druid里面numTestsPerEvictionRun 这个参数被废弃了，没有使用。
timeBetweenEvictionRunsMillis 使用的莫名其妙，在获取连接时，如果连接的空闲时间大于此值就测试，这显然不符合本属性意义，如果对比也应该取minEvictableIdleTimeMillis（可回收的最小时间）值才对

**Comment by codedad1983** [comment]
你要的应该是druid里的keepAlive机制吧。
