### ISSUE TITLE
parseCreateDatabase没有解析default charset和default collate

### ISSUE THREAD

**Issue by myzhan** [alibaba/druid#1283]
druid版本：1.0.9
测试代码抛出异常
String sql = "create database user default charset=utf8 default collate=utf8_general_ci;"
MySqlStatementParser parser = new MySqlStatementParser(sql);
List<SQLStatement> statementList = parser.parseStatementList();

**Comment by wenshao** [comment]
已支持，但这个什么鬼语法，和文档不一样的！

**Comment by myzhan** [comment]
哈哈，这个应该是MySQL自己的语法

[官方文档](https://dev.mysql.com/doc/refman/5.5/en/create-database.html)

**Comment by ljq132008** [comment]
create database user default charset=utf8 collate=utf8_general_ci;
如果不加default好像解析有问题，与前面的options一起解析成SQLBinaryOpExpr了
druid-1.1.23版本
