### ISSUE TITLE
DruidDataSource 为什么不实现接口 java.io.Closeable

### ISSUE THREAD

**Issue by moonfruit** [alibaba/druid#1288]
既然类 DruidDataSource 包含了方法 close()，那为什么不实现接口 java.io.Closeable ?
实现 Closeable 这个接口对 DruidDataSource 改动非常小，却能带来很多好处：
一、可以使用 java 7 引入的 try-with-resources 语法，实现自动关闭；
二、在 springframework 中，可以自动识别接口 Closeable，将 close() 方法自动注册为 bean 的 destroy method。这样即使忘记配置这个属性，也没关系。

**Comment by wenshao** [comment]
本来就实现了啊，你用的是什么版本？
