### ISSUE TITLE
建议增加配置项以支持使用 JDBC4 的新接口 Connection.isValid() 替代 validationQuery

### ISSUE THREAD

**Issue by moonfruit** [alibaba/druid#1289]
建议增加配置项以支持使用 JDBC4 的新接口 Connection.isValid() 替代 validationQuery。

**Comment by wenshao** [comment]
没必要，各个新版驱动isValid的底层的实现是一样的，而且这容易导致驱动版本不兼容。

**Comment by lizongbo** [comment]
已经有JDBC4ValidConnectionChecker，请使用最新版验证
