### ISSUE TITLE
feature: 连接的最大存活时间

### ISSUE THREAD

**Issue by ChinaXing** [alibaba/druid#1297]
一条连接被打开后，频繁使用，按照druid的设计，只要每次空闲时间很短暂，未达到evict的时间长度。将不会清除。那么存在一条连接被永久使用的情况（在繁忙的时候）。

能否增加一个设置或者功能点：单条连接在服务多少请求或者存活多长时间后，被evict。

这样做的好处： 对于通过proxy 到后端db的情况，可以避免负载不均衡。

HikariCP 已经实现这个功能：maxLifeTime.

**Comment by wenshao** [comment]
druid也有这样的功能：
maxEvictableIdleTimeMillis
