### ISSUE TITLE
druid能使用log4j2打印日志吗

### ISSUE THREAD

**Issue by Shalousun** [alibaba/druid#1300]
druid能使用log4j2打印日志吗

**Comment by renfufei** [comment]
原则上,可以使用任意的Log实现来打印日志。 但是 Druid使用的是 Log4j框架的API，所以，很多时候你需要通过一个转接口来将API调用转发给Log实现。

例如: 使用 slf4j 转接 和 logback 实现的 MAVEN 依赖配置如下所示(需要指定版本号): 

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>log4j-over-slf4j</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>jcl-over-slf4j</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <scope>runtime</scope>
        </dependency>

log4j2也是一样的道理

**Comment by wenshao** [comment]
已经支持，等1.0.23版本吧。配置filter可以使用filters="log4j2"，参考文档这里 https://github.com/alibaba/druid/wiki/%E5%86%85%E7%BD%AEFilter%E7%9A%84%E5%88%AB%E5%90%8D
