### ISSUE TITLE
MySQL语法解析错误

### ISSUE THREAD

**Issue by mzsea** [alibaba/druid#1303]
druid版本：1.0.20
mysql版本：5.5.54
示例语句：select \* from test1 where name like 'A%' limit 10  union select \* from test1 where name like 'B%' limit 20
解析为：(SELECT \* FROM test1 WHERE name LIKE 'A%' LIMIT 10) UNION (SELECT \* FROM test1 WHERE name LIKE 'B%' LIMIT 20)
示例语句数据库执行效果：(SELECT \* FROM test1 WHERE name LIKE 'A%' LIMIT 10) UNION (SELECT \* FROM test1 WHERE name LIKE 'B%') LIMIT 20

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.4
问题已经修复，请使用新版本
