### ISSUE TITLE
SchemaStatVisitor无法解析cast函数条件

### ISSUE THREAD

**Issue by ljhabc1982** [alibaba/druid#1307]
String dbType = JdbcConstants.MYSQL;
String sql = "select t.a,t.b from t where cast(replace(t.statdate, '-','') as decimal) >=20160626 ";
List<SQLStatement> stmtList = SQLUtils.parseStatements(sql, dbType);
SQLStatement stmt = stmtList.get(0);
SchemaStatVisitor ssv = SQLUtils.createSchemaStatVisitor(dbType);
stmt.accept(ssv);
List<Condition> conditions = ssv.getConditions();
//这里conditions 无元素

**Comment by wenshao** [comment]
已支持cast表达式，但是还是不能支持replace(t.statdate, '-','')

**Comment by ljhabc1982** [comment]
replace(t.statdate, '-','')不打算支持吗
