### ISSUE TITLE
Spring Boot DB2数据库无法创建序列

### ISSUE THREAD

**Issue by Acris** [alibaba/druid#1308]
如图：
使用Spring Boot + Druid + DB2时，提示语法错误无法创建序列，但是语句是没有问题的。

![1.png](https://ooo.0o0.ooo/2016/06/24/576cd0fcde8ec.png)
![2.png](https://ooo.0o0.ooo/2016/06/24/576cd0fd85b78.png)

**Comment by wenshao** [comment]
已经修复，请等1.0.21版本
