### ISSUE TITLE
开始事物语法支持

### ISSUE THREAD

**Issue by wangyu4882** [alibaba/druid#1309]
Version:1.0.20

不支持mysql的语法： begin
参考：https://dev.mysql.com/doc/refman/5.7/en/commit.html

不支持sqlserver的语法:  BEGIN TRANSACTION
参考：https://msdn.microsoft.com/en-us/library/ms188929.aspx

**Comment by renfufei** [comment]
JDBC驱动有专用的事务API。这类语句不属于增删改查的一部分。

**Comment by wangyu4882** [comment]
1. 在 .net 环境下。  mysql 驱动会使用 “begin” 来启动事物。 
2. 无法强制用户不使用这些sql.

所以请麻烦支持一下对这类sql的解析。 谢谢啦

**Comment by wenshao** [comment]
支持mysql begin语法啊，你用的是什么版本？

**Comment by wangyu4882** [comment]
你好。 我使用 druid版本 1.0.20.  

SQL：  begin

报错信息如下：
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'begin',expect END, actual EOF begin
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:232)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:240)

看起来像是将开启事物的begin,  当做了 begin...end 的begin

**Comment by wenshao** [comment]
为什么不用START TRANSACTION

**Comment by wangyu4882** [comment]
我们 无法控制用户不使用begin 来启动事物。
而且 。 在 .net 环境下。 mysql 驱动会使用 “begin” 来启动事物。

**Comment by lizongbo** [comment]
最新版已经支持了。
