### ISSUE TITLE
druid解析db2 order by 后含有fetch的sql语句时抛出异常

### ISSUE THREAD

**Issue by leezongjie** [alibaba/druid#1311]
项目在使用druid解析db2语句，当含有order by  fetch 语句时无法解析，如：
SELECT * FROM TASK_POLICE_QUERY_BATCH WHERE STATUS = '0' ORDER BY PRIORITY FETCH FIRST 100 ROWS ONLY，如果换成子查询，将order by  与 fetch 分离开则可以，如：
SELECT * FROM (SELECT * FROM TASK_POLICE_QUERY_BATCH WHERE STATUS = '0' ORDER BY PRIORITY) FETCH FIRST 100 ROWS ONLY，即目前druid不支持order by后跟有fecth操作的语句，mysql下类似语法是支持的，如：
SELECT * FROM TASK_POLICE_QUERY_BATCH WHERE STATUS = '0'  ORDER BY PRIORITY limit 1,90。

上次有个批量插入语句的问题，新版本已经修复啦，谢谢@wenshao ，现在这个问题烦请看一下~

**Comment by wenshao** [comment]
能说一下你们用在什么场景么？

**Comment by wenshao** [comment]
已经支持，请等待最近发布1.0.21版本

**Comment by leezongjie** [comment]
谢谢支持，我们做了一个自动缓存组建，使用druid分析各种sql语句，用来获取执行的是查询还是更新操作，操作的是哪些表，根据这些信息来自动更新缓存，分析效果不错，目前就是偶尔有些语法的语句没法分析，但是因为是用在缓存上，所以出错时并不影响正常使用，只不过本次缓存不起作用
