### ISSUE TITLE
druid长时间无操作无法保持连接！！

### ISSUE THREAD

**Issue by maxid** [alibaba/druid#1316]
纯原生JAVA项目中，Druid作为MySQL连接池时（MySQL默认为8小时没操作就断开），测试场景为10小时不进行任何查询，就算配置了testWhileIdle=true，也不能保持连接，配置如下:
source.mysql.url=jdbc:mysql://127.0.0.1:3306/xxx
source.mysql.username=root
source.mysql.password=xxx
source.mysql.driver=com.mysql.jdbc.Driver
source.mysql.initialSize=10
source.mysql.minIdle=10
source.mysql.maxActive=100
source.mysql.maxWait=60000
source.mysql.timeBetweenEvictionRunsMillis=10000
source.mysql.minEvictableIdleTimeMillis=300000
source.mysql.validationQuery=select 1
source.mysql.testWhileIdle=true
source.mysql.testOnBorrow=false
source.mysql.testOnReturn=false
source.mysql.removeAbandoned=true
source.mysql.removeAbandonedTimeout=1800
source.mysql.logAbandoned=false
source.mysql.poolPreparedStatements=false
source.mysql.maxPoolPreparedStatementPerConnectionSize=20
source.mysql.filters=stat,wall

10小时后查询，报：
java.sql.SQLException: The last packet successfully received from the server was 63,920,837 milliseconds ago.  The last packet sent successfully to the server was 63,920,858 milliseconds ago.

**Comment by strivezsh** [comment]
是不是mysql数据库的问题?
http://www.cnblogs.com/davidwang456/p/4425913.html

**Comment by maxid** [comment]
@strivezsh 不是，这些都尝试过

**Comment by daokunzhu1107** [comment]
你的测试代码是啥，感觉不应该有问题的。
如果是你先获取connection，然后等待10个小时再操作，这肯定有问题。

**Comment by zhangjianweibj** [comment]
看工程里的测试类DruidDataSourceTest_testOnWhileIdleFailed，testWhileIdle不是用来保持长连接的有效。而是为了对已经取到的connection进行连接有效性的检测用的。

**Comment by daokunzhu1107** [comment]
如果你的新能要求不是非常高，把testOnBorrow设置为true，每次从连接池里面获取连接时都会测试连接的有效性。这个是获取一个稳定连接最简单有效的手段。

**Comment by xiegengcai** [comment]
毫无疑问是 @maxid 的连接池配少了某些属性
```XML
<property name="validationQuery" value="SELECT 'x'" />
<property name="validationQueryTimeout" value="3600" />
```

**Comment by maxid** [comment]
@xiegengcai 
那试试加上validationQueryTimeout

**Comment by xiegengcai** [comment]
@maxid 另外看看你的MySQL保持连接时间是不是被改了

**Comment by maxid** [comment]
看了源码，druid并没有定时器来捡查连接，只是在每次查询的时候检查过期连接，因此只有是使用量很低的情况下，就会出现以上问题，估计因为阿里的查询量非常大，因此不考虑对此种情况的支持

**Comment by maxid** [comment]
durid未实现Timer检查连接，只考虑了在getConntion时进行连接检查，估计不太适会查询量非常小的项目

**Comment by zhaojianyong** [comment]
用的什么版本的Druid？最新版本的支持maxEvictableIdleTimeMillis参数，默认7小时。原来minEvictableIdleTimeMillis只会把连接数降到minIdle。如果现在连接池的连接数等于minIdle，那连接就不会被close。现在，增加了maxEvictableIdleTimeMillis。如果，连接空闲时间大于maxEvictableIdleTimeMillis，那么，这连接就会被close掉。

**Comment by maxid** [comment]
用的是最新版本，如果几天都不会有一次查询的情况下，连minIdle都保持不了

**Comment by lizongbo** [comment]
请使用最新版本验证
开启keepAlive
