### ISSUE TITLE
db2 select item 中存在IDENTITY关键字时，解析出错

### ISSUE THREAD

**Issue by leezongjie** [alibaba/druid#1328]
由于历史项目原因，有个表中的字段名称为IDENTITY，同样也是db2关键字，这样我们在分析语句：
SELECT ID,IDENTITY,BUSICODE FROM BUSINESS_ENTERPRISE_BUSIINFO WHERE  SYSCODE= '603' ORDER BY INTIME desc FETCH first 1 rows only

时出错，分析到IDENTITY时认为是关键字，便无法解析了，但是该语句在db2中的执行时没有问题的，db2会分析上下文环境来判断该字段是不是关键字。
目前我们临时添加了引号来避免该问题，如下：
SELECT ID, “IDENTITY”, BUSICODE FROM BUSINESS_ENTERPRISE_BUSIINFO
也在新开发项目中避免使用关键字作为表字段。

在select item的分析中，仅仅通过匹配关键字的方式就认为是关键字好像不太合理。

**Comment by wenshao** [comment]
已支持，请等待1.0.23版本吧
