### ISSUE TITLE
数据源创建失败后建议终止CreateConnectionThread线程

### ISSUE THREAD

**Issue by gooree** [alibaba/druid#1336]
数据源创建失败后，后台CreateConnectionThread线程不断报错，即时设置了connectionErrorRetryAttempts也不起作用。建议超过失败重试次数后就终止该线程。

**Comment by zhangjianweibj** [comment]
DruidDataSource源码1973行开始，CreateConnectionThread函数里面。errorCount>connectionErrorRetryAttempts条件不成立，会一直出现打印日志的情况。如果breakAfterAcquireFailure设置为true，就会停止

                    if (errorCount > connectionErrorRetryAttempts && timeBetweenConnectErrorMillis > 0) {
                        if (breakAfterAcquireFailure) {
                            break;
                        }

                        try {
                            Thread.sleep(timeBetweenConnectErrorMillis);
                        } catch (InterruptedException interruptEx) {
                            break;
                        }
                    }

**Comment by gooree** [comment]
多谢回复，设置breakAfterAcquireFailure为true后该问题已解决。
