### ISSUE TITLE
DruidDataSource errorCount > connectionErrorRetryAttempts情况处理

### ISSUE THREAD

**Issue by zhangjianweibj** [alibaba/druid#1338]
```
                if (errorCount > connectionErrorRetryAttempts && timeBetweenConnectErrorMillis > 0) {
                    if (breakAfterAcquireFailure) {
                        break;
                    }

                    try {
                        Thread.sleep(timeBetweenConnectErrorMillis);
                    } catch (InterruptedException interruptEx) {
                        break;
                    }
                }
```

这个地方的errorCount 已经大于了 connectionErrorRetryAttempts为何还要进行Thread.sleep(timeBetweenConnectErrorMillis);感觉没必要，可以直接break

**Comment by gooree** [comment]
确实感觉这个地方逻辑有点问题，应该是先判断breakAfterAcquireFailure，如果为true立即跳出循环。否则再判断errorCount>connectionErrorRetryAttempts，如果为true也跳出循环，否则的话才进入休眠。

**Comment by ihaolin** [comment]
breakAfterAcquireFailure如果为false，这里会睡一段时间(timeBetweenConnectErrorMillis)后，再次继续重试创建连接。

**Comment by seeyoula** [comment]
connectionErrorRetryAttempts错误重试次数吧，但是感觉跟错误重试建立连接间隔有点不协调。。。
如果errorCount < connectionErrorRetryAttempts，立即重试啦。
当errorCount > connectionErrorRetryAttempts时，再去判断是否终止重试breakAfterAcquireFailure，不终止才会去sleep  timeBetweenConnectErrorMillis后在进行重试。

**Comment by tjzfg** [comment]
无解？

**Comment by zouhuajian** [comment]
> ```
>                 if (errorCount > connectionErrorRetryAttempts && timeBetweenConnectErrorMillis > 0) {
>                     if (breakAfterAcquireFailure) {
>                         break;
>                     }
> 
>                     try {
>                         Thread.sleep(timeBetweenConnectErrorMillis);
>                     } catch (InterruptedException interruptEx) {
>                         break;
>                     }
>                 }
> ```
> 
> 这个地方的errorCount 已经大于了 connectionErrorRetryAttempts为何还要进行Thread.sleep(timeBetweenConnectErrorMillis);感觉没必要，可以直接break
但是它这个线程只创建一次，如果break出去，后面这个数据库恢复了，连接无法创建了，我觉得还是应加长它重试的时间，保持此线程的存在。

**Comment by zouhuajian** [comment]
> ```
>                 if (errorCount > connectionErrorRetryAttempts && timeBetweenConnectErrorMillis > 0) {
>                     if (breakAfterAcquireFailure) {
>                         break;
>                     }
> 
>                     try {
>                         Thread.sleep(timeBetweenConnectErrorMillis);
>                     } catch (InterruptedException interruptEx) {
>                         break;
>                     }
>                 }
> ```
> 
> 这个地方的errorCount 已经大于了 connectionErrorRetryAttempts为何还要进行Thread.sleep(timeBetweenConnectErrorMillis);感觉没必要，可以直接break

但是它这个线程只创建一次，如果break出去，后面这个数据库恢复了，连接无法创建了，我觉得还是应加长它重试的时间，保持此线程的存在。

**Comment by zouhuajian** [comment]
> ```
>                 if (errorCount > connectionErrorRetryAttempts && timeBetweenConnectErrorMillis > 0) {
>                     if (breakAfterAcquireFailure) {
>                         break;
>                     }
> 
>                     try {
>                         Thread.sleep(timeBetweenConnectErrorMillis);
>                     } catch (InterruptedException interruptEx) {
>                         break;
>                     }
>                 }
> ```
> 
> 这个地方的errorCount 已经大于了 connectionErrorRetryAttempts为何还要进行Thread.sleep(timeBetweenConnectErrorMillis);感觉没必要，可以直接break

但是它这个线程只创建一次，如果break出去，后面这个数据库恢复了，连接无法创建了，我觉得还是应重试，并且加长它睡眠的时间，保持此线程的存在。

**Comment by imaffe** [comment]
DruidDataSourceFactory.createDataSource 同样也不支持connectionErrorRetryAttempts这个参数

**Comment by lizongbo** [comment]
请使用最新版本验证
