### ISSUE TITLE
Wall在alter table union语句报错

### ISSUE THREAD

**Issue by pop-lee** [alibaba/druid#1340]
在修改merge table的情况下，alter table语句现在还不支持union的操作吗？
MySQL merge表引擎

**Comment by pop-lee** [comment]
分别试用了1.0.18和1.0.23，在SQLStatement的parseStatementList方法中没有找到UNION，然后printError了

**Comment by wenshao** [comment]
能提供相应的SQL么？

**Comment by pop-lee** [comment]
alert table 表名
unoin (拆分表1,拆分表2);
MySQL MRG_MyISAM引擎，拆分表为MyISAM引擎

**Comment by pop-lee** [comment]
@wenshao

**Comment by wenshao** [comment]
mysql有这样的语法？我看文档找不到啊

**Comment by pop-lee** [comment]
@wenshao 
http://dev.mysql.com/doc/refman/5.7/en/merge-storage-engine.html
MySQL5.7中的MERGE引擎，专门用来连接拆分表的引擎

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/commit/fa4621af4ba6a46bd6faaa4fb00fa2854dc2a1bf

**Comment by wenshao** [comment]
已经支持，等下一个版本1.1.24吧，如果你是阿里内部用户，可以用快照版本1.1.24-SNAPSHOT

**Comment by pop-lee** [comment]
@wenshao 多谢多谢，太速度啦~！
