### ISSUE TITLE
是否有方法根据datasource生成这个datasource对应的数据库的建表脚本？

### ISSUE THREAD

**Issue by tywo45** [alibaba/druid#1342]
是否有方法根据datasource生成这个datasource对应的数据库的建表脚本？譬如输入参数是datasource1，输出的字符串是create table ...这样的SQL脚本，谢谢！

**Comment by wenshao** [comment]
这个有较大工作量，我想想啊

**Comment by wenshao** [comment]
```java
String dbType = JdbcConstants.ORACLE;
String createTableScript = JdbcUtils.getCreateTableScript(dbType, conn);
```

**Comment by wenshao** [comment]
问题已解决，请用新版本
https://github.com/alibaba/druid/releases/tag/1.1.2

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/wiki/getCreateTableScript

**Comment by tywo45** [comment]
感谢！太敬业了！

**Comment by learningtcc** [comment]
哇哦，大佬就是这么的平易近人
