### ISSUE TITLE
Druid的数据库密码加密问题

### ISSUE THREAD

**Issue by lsgggg123** [alibaba/druid#1354]
看了下源码实现。使用的是privateKey加密，publicKey解密，而且密文和publicKey都可以通过配置文件取得，用ConfigTools.decrypt(publicKey, 密文)不就解密出来密码了？

**Comment by lsgggg123** [comment]
![image](https://cloud.githubusercontent.com/assets/15649907/17363332/587220c2-59ac-11e6-9524-b808719bffaa.png)
这里看出来明显publicKey和密码都在一起的。

**Comment by wenshao** [comment]
这个只能保证一定程度的安全，比明文安全一些，但不能保证绝对安全的

**Comment by ncc0706** [comment]
整合SpringBoot的时候怎么配置
