### ISSUE TITLE
执行正确，却报com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual QUES %

### ISSUE THREAD

**Issue by cyuanxin** [alibaba/druid#1358]
我用的mysql，orm用mybatis，然后发现 select *  from xx WHERE ( t6.company_name LIKE "%"?"%"  or  t6.company_name LIKE "%"?"%" ) 执行类似这种语句，就报这个错误。。之前也是执行一个语句，然后报这个错误 ，也是类似有多个"%"?"%" 就报错。代码是正确运行的。

**Comment by wenshao** [comment]
这样的语法mysql支持？？

**Comment by cyuanxin** [comment]
支持呀。。您认为哪里不支持。。。模糊查询 %？% 这样不都正常嘛。。。

**Comment by wenshao** [comment]
```sql
LIKE "%"?"%" 
```
这样的语法，你认为是正常的？

**Comment by cyuanxin** [comment]
你是指应该用 “%?%” 吗 ， 刚才那个是可以运行的。。。

**Comment by wenshao** [comment]
刚测试过了，mysql也不支持这样的语法
```
select * from t1 where f1 LIKE "%"?"%";
```
运行报错
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?"%"' at line 1

mysql的语法解析有时候不能正确发现语法错误，你这个明显是语法错误的，建议修改SQL
