### ISSUE TITLE
怎么对commons-lang产生了依赖？

### ISSUE THREAD

**Issue by chpinck** [alibaba/druid#1364]
java.lang.NoClassDefFoundError: org/apache/commons/lang/math/NumberUtils
	com.alibaba.druid.sql.parser.Lexer.decimalValue(Lexer.java:1288)

<dependency>
    <groupId>commons-lang</groupId>
    <artifactId>commons-lang</artifactId>
    <version>2.6</version>
</dependency>

**Comment by wenshao** [comment]
这个确实是不恰当依赖，下个版本就会去掉依赖，合并代码的时候没看仔细，谢谢反馈。

**Comment by chpinck** [comment]
下个版本大概什么时候发布，我想尽快更新，谢谢！

**Comment by chpinck** [comment]
看了你修改的代码
import org.apache.commons.lang.math.NumberUtils;
这句没有删除

**Comment by wenshao** [comment]
是的，import还没去掉，不过应不会影响使用的。新版本已发布1.0.25
