### ISSUE TITLE
druid 初始化建立物理连接很慢

### ISSUE THREAD

**Issue by hyuming** [alibaba/druid#1368]
09:42:46,451 DEBUG [DefaultListableBeanFactory] Invoking init method  'init' on bean with name 'dataSource'
09:42:48,155 DEBUG [Connection] {conn-10001} connected
09:42:49,928 DEBUG [Connection] {conn-10002} connected
09:42:52,074 DEBUG [Connection] {conn-10003} connected
09:42:54,525 DEBUG [Connection] {conn-10004} connected
09:42:56,997 DEBUG [Connection] {conn-10005} connected
09:43:01,990 DEBUG [Connection] {conn-10006} connected
09:43:04,078 DEBUG [Connection] {conn-10007} connected
09:43:04,131 DEBUG [Connection] {conn-10008} connected
09:43:06,430 DEBUG [Connection] {conn-10009} connected
09:43:06,501 DEBUG [Connection] {conn-10010} connected
09:43:07,933 DEBUG [Connection] {conn-10011} connected
09:43:07,988 DEBUG [Connection] {conn-10012} connected
09:43:09,917 DEBUG [Connection] {conn-10013} connected
09:43:09,969 DEBUG [Connection] {conn-10014} connected
09:43:11,849 DEBUG [Connection] {conn-10015} connected
09:43:14,833 DEBUG [Connection] {conn-10016} connected
09:43:17,234 DEBUG [Connection] {conn-10017} connected
09:43:17,285 DEBUG [Connection] {conn-10018} connected
09:43:21,029 DEBUG [Connection] {conn-10019} connected
09:43:21,082 DEBUG [Connection] {conn-10020} connected
09:43:21,092 INFO  [DruidDataSource] {dataSource-1} inited

**Comment by hyuming** [comment]
设置了初始化个数为20个

**Comment by wenshao** [comment]
初始化设置为0，启动就会很快了，需要启动很快么？如果启动快，部署的服务器多，会对数据库造成压力的

**Comment by hyuming** [comment]
实际上可以缓慢启动

**Comment by weichong-maoxiaotong** [comment]
请问， 如何实现的   druid 初始化建立物理连接???

**Comment by lizongbo** [comment]
这个是数据库自身响应很慢导致的。
