### ISSUE TITLE
WallFilter是否可以拦截一些自定义不规范的SQL?

### ISSUE THREAD

**Issue by ihaolin** [alibaba/druid#1369]
你好，
如题，比如，不希望开发人员一次性查询超过1000条的数据等，WallFilter似乎不支持，或者需要自己定义Filter来作吗？

**Comment by wenshao** [comment]
好主意，下个版本补上支持

**Comment by wenshao** [comment]
已经支持，请使用新版本 https://github.com/alibaba/druid/releases/tag/1.0.30
