### ISSUE TITLE
 druid 1.0.24版本 setTestOnBorrow 为 true 后进入死循环无法获取到连接

### ISSUE THREAD

**Issue by galfordliu** [alibaba/druid#1371]
设置

setTestOnBorrow = true ，validationQuery=select 1

在
public DruidPooledConnection getConnectionDirect(long maxWaitMillis) throws SQLException

此函数进入死循环，再也无法获取到连接。

**Comment by zhangjianweibj** [comment]
![qq 20160819095755](https://cloud.githubusercontent.com/assets/18585129/17796518/949ef900-65f3-11e6-96ea-49ddea81710d.png)


方法处理没问题，他这个不是死循环，是乐观锁的处理方式。把打印日志贴出来。
