### ISSUE TITLE
URI监控定时刷新时间过短的问题

### ISSUE THREAD

**Issue by renfufei** [alibaba/druid#1379]
URI监控, 访问地址为: `/druid/weburi.html`
通过Network看到，返回的数据为570KB左右。
导致的问题为： 同时有多个请求发送到 `/druid/weburi.json?orderBy=URI&orderType=desc&page=1&perPageCount=1000000`
网速稍慢的情况下,每个请求都在等待，大约10秒左右才接收完毕.
结果： 页面数据不刷新
期望：能配置自动刷新时间；以及可以临时暂停刷新；perPageCount 默认值也过大

**Comment by wenshao** [comment]
开源需要大家一起来参与，你来通过pull request来提一个patch来修改一下？

**Comment by renfufei** [comment]
收到

**Comment by renfufei** [comment]
已修正并进行基本的测试。 相关链接:  [http监控页面新增部分功能#1393](https://github.com/alibaba/druid/pull/1393)
