### ISSUE TITLE
开启防火墙的情况下 SHOW FULL TABLES WHERE Table_type != 'VIEW'  会被拒绝

### ISSUE THREAD

**Issue by zhuam** [alibaba/druid#1380]
com.alibaba.druid.sql.ast.statement.SQLShowTablesStatement not allow 

跟踪代码进入  com.alibaba.druid.wall.spi.WallVisitorUtils 类，关于下面的方法
public static void preVisitCheck(WallVisitor visitor, SQLObject x) {
  ...
}
没有SQLShowTablesStatement 的判断，也没有开关， 直接进入了 else 逻辑

   } else {
            allow = config.isNoneBaseStatementAllow();
            errorCode = ErrorCode.NONE_BASE_STATEMENT_NOT_ALLOW;
            denyMessage = x.getClass() + " not allow";
   } 
造成 com.alibaba.druid.sql.ast.statement.SQLShowTablesStatement not allow

**Comment by zhuam** [comment]
druid-1.0.24 之前没有 SQLShowTablesStatement ，不存在这个问题， 该问题发生在 1.0.24 上

**Comment by wenshao** [comment]
什么数据库？

**Comment by wenshao** [comment]
问题重现并修复，等下个版本吧，预计在9月3日之前发布

**Comment by zhuam** [comment]
OK thanks
