### ISSUE TITLE
mysql 解析出错 

### ISSUE THREAD

**Issue by ljhabc1982** [alibaba/druid#1407]
druidt版本1.0.25
减号语法出错，bufPos值错误
String sql = "SELECT t.id-t.id from system_conn t ";
System.out.println(sql);
SQLStatementParser parse = SQLParserUtils.createSQLStatementParser(sql, dbType);
List<SQLStatement> list = parse.parseStatementList();
SQLStatement stmt = list.get(0);
System.out.println(SQLUtils.toSQLString(stmt,dbType));
执行结果：SELECT t.id-.id
FROM system_conn t
 减号后面表名t被删除了

druidt版本1.0.18不会有这个问题

**Comment by wenshao** [comment]
mysql支持这样的语法哈。。

**Comment by ljhabc1982** [comment]
mysql所有减法解析都会出错啊

**Comment by ljhabc1982** [comment]
应该是减法是解析bufPos没有+1，直接continue了

**Comment by wenshao** [comment]
是的有这个问题，问题重现了

**Comment by ljhabc1982** [comment]
MySqlLexer 
 if (ch == '-' && pos < text.length() - 1) {
                        char next_char = text.charAt(pos + 1);
                        if (isIdentifierChar(next_char)) {
                            continue;
                        }
}

**Comment by wenshao** [comment]
问题重现并且解决，谢谢反馈
