### ISSUE TITLE
内置监控界面提供SQL格式化和分析的功能

### ISSUE THREAD

**Issue by wenshao** [alibaba/druid#141]
在内置监控界面中，提供SQL格式化和分析用了哪些表哪些字段，类似于目前SQL-Deail页面。

**Comment by liuwenru** [comment]
请问有无关于详细的监控值的单位的说明文档，例如在区间分布上我可以知道单位是毫秒的，但是在【URI监控】中请求时间为找到相关的单位说明，应该是毫秒，但是我希望准确的说明文档，谢谢～
