### ISSUE TITLE
mysql create table语句解析错误

### ISSUE THREAD

**Issue by sanli** [alibaba/druid#1420]
测试过程中发现解析mysql create table命令有个异常，语句如下：
create table `test`.`simple_test` (
  `col_key` bigint(20) not null auto_increment,
  `col1` varchar(45) null,
  `col2` tinyint(4) null,
  `col3` datetime null,
  `col4` timestamp null default current_timestamp on update current_timestamp,
  primary key (`col_key`),
  unique index `v1_unique` (`col_key` asc)) , 
错误如下：
err:com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual ASC asc

好像是不能正确处理“unique index `v1_unique` (`col_key` asc)” 这一段，不知道是否确实是一个bug。

druid版本： 1.0.14，

**Comment by wenshao** [comment]
问题已解决，请等待1.0.26版本
