### ISSUE TITLE
session ip change too many问题怎么解决

### ISSUE THREAD

**Issue by pandboy** [alibaba/druid#1423]
错误 现象：ERROR WebSessionStat:265 - session ip change too many
看源码是remoteAddresses长度大于256打印的错误日志，
版本：1.0.22

**Comment by renfufei** [comment]
尝试 配置 Filter 的 `realIpHeader` 初始化参数，或者断点调试看看http请求头中的信息。

**Comment by pandboy** [comment]
@renfufei 被攻击会产生这个错误日志打印
