### ISSUE TITLE
postgresql配置druid.stat.mergeSql=true执行update(update语句中存在from)报错

### ISSUE THREAD

**Issue by suifengpiao4515** [alibaba/druid#1430]
UPDATE sys_account AS a SET online = 2 FROM auto_handler_online o WHERE a.id = o.account_id AND a.online != 2
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :' = 2 FROM auto_handler_online o WHE',expect FROM, actual FROM FROM
还有也不支持字符串函数 substring('Thomas' from 2 for 3)

**Comment by wenshao** [comment]
什么版本？

**Comment by wenshao** [comment]
问题已经修复，等待下个版本吧，如果是公司内的用户，请联系我发布快照
