### ISSUE TITLE
建议对 RESTful 风格的URI进行监控信息合并

### ISSUE THREAD

**Issue by renfufei** [alibaba/druid#1434]
最近错误日志输出了一个信息: `uriSessionMapFullCount is full`
查看代码发现是 [WebAppStat.java#getURIStat()](https://github.com/alibaba/druid/blob/master/src/main/java/com/alibaba/druid/support/http/stat/WebAppStat.java#L277) 方法输出的, 原因可能是URI 日志的个数超过了默认的1000条。

能不能增加某个配置, 使得REST风格的多个请求的统计信息合并为一条。
例如:

```
/someApp/api/userinfo/1
/someApp/api/userinfo/2
/someApp/api/userinfo/3
/someApp/api/userinfo/...
```

感谢!

**Comment by renfufei** [comment]
看了一下源码，感觉可以在获取监控结果时，根据相关配置/模式对结果信息进行合并。至于前面的整个流程，都不用修改。

**Comment by iamyuzhe** [comment]
怎么实现呢
