### ISSUE TITLE
druid版本1.0.26最小连接数怎么没有用

### ISSUE THREAD

**Issue by 3056075** [alibaba/druid#1442]
最小空闲连接数配置为10，过了几个小时后，池中连接数为3，有7个物理关闭掉了。
池中连接数不应该最小保持为10个吗？怎么变成3个了？
1.0.22版本好像没有这个问题。

部分配置参数：

> ```
>    
>     <property name="maxActive" value="200" />
>     <property name="initialSize" value="10" />
>     
>     <property name="maxWait" value="30000" />
>     <property name="minIdle" value="10" />
> ```

监控页面上看到的是：
 池中连接数    3

**Comment by 3056075** [comment]
com.alibaba.druid.pool.DruidDataSource类的方法 public void shrink(boolean checkTime)
在：

> commit b66c366f93da2a7cd7324c7bb4ee9c08a748d7b2
Author: 高铁 <shaojin.wensj@alibaba-inc.com> 2016-03-11 21:26:40
Committer: 高铁 <shaojin.wensj@alibaba-inc.com> 2016-03-11 21:26:40
Parent: fa102ee0a3071837a7beb19a7ca6028075937d73 (changed DruidDataSource discardConnectiion filling logic)
Child: c445f3965d3a0f431db80c1e8f4d254040de8da3 (bug fixed for phyTimeoutMillis)
Branches: master, origin/master

support maxEvictableIdleTimeMillis

这次变更中代码2225行，循环最大值从checkCount改成了poolingCount，是不是这里有问题？？？

**Comment by 3056075** [comment]
类DruidDataSource 中第2280行
if (checkTime && i < checkCount) {
                        evictList.add(connection);
                    } else if (idleMillis > maxEvictableIdleTimeMillis) {
                        evictList.add(connection);
                    }

看到了，如果空闲时间超过maxEvictableIdleTimeMillis值，则一定会清理。导致连接池中数量少于minIdle。
maxEvictableIdleTimeMillis默认为7个小时。

**Comment by lizongbo** [comment]
请使用最新版验证
