### ISSUE TITLE
使用connectionProperties配置密文密码含有符号时不能正确连接数据库

### ISSUE THREAD

**Issue by DR-YangLong** [alibaba/druid#1446]
RT，原文密码2016!!abc，然后用java -cp druid-1.0.26.jar com.alibaba.druid.filter.config.ConfigTools 2016!!abc生成密文和publicKey，配置到datasource配置项，连接不了数据库。
关键配置：
 <property name="filters" value="stat,config"/>
<property name="connectionProperties" value="config.decrypt=true;config.decrypt.key=${my.publicKey}"/>

**Comment by DR-YangLong** [comment]
有问题的版本 mysql5.6.17，用'5.7.15-0ubuntu0.16.04.1'就没问题

**Comment by wenshao** [comment]
感觉和Druid无关哦

**Comment by lizongbo** [comment]
请使用最新版验证
