### ISSUE TITLE
SpringBoot + Druid + Spring Cloud Hystrix出现UnsupportedOperationException

### ISSUE THREAD

**Issue by Antergone** [alibaba/druid#1450]
SpringBoot: 1.4.1
Druid: 1.0.25

如题配置，会出现UnsupportedOperationException。
发现是DruidAbstractDataSource里setDriverClassName时 inited已经是true， 使用dbcp不存在此问题，不知是我配置问题，还是Druid兼容问题

**Comment by wenshao** [comment]
连接池初始化之后不允许再修改driverClassName，不过我可以补上检测如果相等则忽略

**Comment by wenshao** [comment]
druid是能自动识别driverClassName的，你可以不配置这个，问题就不存在啦

**Comment by Antergone** [comment]
哈哈 我还是觉得加上检测比较好，因为配置里面都会写driverClassName
username之类的貌似也有这个问题

**Comment by wenshao** [comment]
已经支持，请使用1.0.27
