### ISSUE TITLE
log4j2 filter 日志一条sql会出现三次，如何只获取到可执行的那条sql？

### ISSUE THREAD

**Issue by joviqiao** [alibaba/druid#1451]
![249082c8-c9df-4eb9-85e9-6f1fb3e6cb6e](https://cloud.githubusercontent.com/assets/13116366/19468487/294fc140-9549-11e6-96db-9928be0f7596.png)

配置log4j2 日志，只想获取到 可执行的那一条日志，如何过滤？
<bean id="log-filter" class="com.alibaba.druid.filter.logging.Log4j2Filter">
        <property name="statementExecutableSqlLogEnable" value="true"/>
    </bean>

**Comment by livem** [comment]
```
Slf4jLogFilter sql_log_filter = new Slf4jLogFilter();
sql_log_filter.setConnectionLogEnabled(false);
sql_log_filter.setStatementLogEnabled(false);
sql_log_filter.setStatementExecutableSqlLogEnable(true);
sql_log_filter.setResultSetLogEnabled(false);
```

**Comment by joviqiao** [comment]
我去试试，谢谢

**Comment by livem** [comment]
你用 `log4j2` 要调整为其他 `filter` ，我项目里面是在使用 `slf4` + `logback` 的

**Comment by cdma** [comment]
@livem 我用slf4+logback死活出不来sql呢？
spring配置：
<property name="proxyFilters">
            <list>
                <ref bean="log-filter"/>
            </list>
        </property>

<bean id="log-filter" class="com.alibaba.druid.filter.logging.Slf4jLogFilter">
        <property name="resultSetLogEnabled" value="false" />
        <property name="statementExecutableSqlLogEnable" value="true"/>
    </bean>

logback配置：
<logger name="com.alibaba.druid">
        <level value="TRACE" />
    </logger>

**Comment by joviqiao** [comment]
我的已经解决，主要是 使用 log4j2 ，不需要在web.xml中进行配置， 就解决了这个问题。

**Comment by livem** [comment]
@cdma spring 里面的配置还要研究一下
