### ISSUE TITLE
为什么url中的端口号无效，而一直使用默认端口3306 ？？？

### ISSUE THREAD

**Issue by guozhouwei** [alibaba/druid#1453]
jdbc:ejdbc:mysql://192.168.113.4:14444/camxxp?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull

这是我的url，为什么druid连接的是端口3306？

![image](https://cloud.githubusercontent.com/assets/16585863/19560176/f24e1f5c-9705-11e6-8e11-e411be14f85a.png)

**Comment by guozhouwei** [comment]
查到了 <dependency>
				<groupId>mysql</groupId>
				<artifactId>mysql-connector-java</artifactId>
				<version>5.1.9</version>
			</dependency>
是这个问题。。。 换了版本就好了。。。。

**Comment by wenshao** [comment]
那我关闭issue啦
