### ISSUE TITLE
odps sql parser 解析alter失败

### ISSUE THREAD

**Issue by melin** [alibaba/druid#1455]
odps sql parser 解析下面两种类型的alter失败：
alter table adl_smeta_column_indi_rule_relation_sdt add columns (rule_level string);
ALTER TABLE adl_smeta_indi_rule_relation_sdt CHANGE COLUMN indi_level COMMENT 'xxxx';

**Comment by frank-zx** [comment]
1.1.19版本 解析Hive SQL以下语句：
alter table testtable add columns (TJ04 STRING COMMENT '产品4',TJ05 STRING COMMENT '产品5');
同样会出错。
解决办法同ODPS。
希望可以修正。
