### ISSUE TITLE
1.0.26版本MySQL连接检测使用的是通用的检测实现导致出现连接断开未重连问题

### ISSUE THREAD

**Issue by tsubasa617** [alibaba/druid#1473]
查询时会获取连接（DruidDataSource.getConnectionDirect），在内部会检测连接的状态（DruidDataSource.testConnectionInternal）,检测时使用validConnectionChecker.isValidConnection。

之前使用的是1.0.18，一切正常，看代码是使用了MySqlValidConnectionChecker 重载的校验方法。

而换成1.0.26后，连接闲置一段时间后再使用，就出现了下面的异常：
`ERROR com.alibaba.druid.pool.DruidDataSource:1243] discard connection
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 1,463,838 milliseconds ago.  The last packet sent successfully to the server was 1,463,839 mill
iseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configure
d values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.`
跟代码发现在这个版本中，没有使用到MySqlValidConnectionChecker 的校验方法，而是父类ValidConnectionCheckerAdapter 的，而**由于我们的配置没有配置校验用的sql**，直接返回了true（表示连接有效），导致问题的发生。
为什么没用到父类的呢？因为父类没有重写该方法，原来方法的名字被改为了“validConnection”。

首先，我们如果配置了校验用的sql，也就不会有这个问题（这个没有亲自测试），于是这个issue可能也算不上是bug。
比较关心的是，这个validConnection看源码并没有地方使用到，修改时间是2016年5月31日，使用父类的而不是MySQL的实现，出发点是什么呢？

请百忙之中解答下，谢谢！

**Comment by tsubasa617** [comment]
solved in 1.0.27

**Comment by liujw1234** [comment]
1.1.23 中又遇到这个问题了
