### ISSUE TITLE
如何让wall过滤器支持BEGIN/END语法

### ISSUE THREAD

**Issue by roc-cn** [alibaba/druid#1489]
oracle数据库
我之前 一次插入多条用的是
`begin
insert ******;
insert ******;
end;`

但是 升级到 druid 1.0.26 后 wall 过滤器 不允许 这样
提示 SQLBlockStatement 不允许执行

这个判断是在哪里进行的！？如何设置wall让其放行BEGIN/END;呢！？

**Comment by wenshao** [comment]
已经支持，将会在1.0.27版本中支持

**Comment by wenshao** [comment]
已经支持，请使用1.0.27版本 https://github.com/alibaba/druid/releases/tag/1.0.27
