### ISSUE TITLE
[ODPS]解析insert partition后有Hint出错

### ISSUE THREAD

**Issue by zillionbrains** [alibaba/druid#1493]
insert overwrite table ff partition (c='c',d='d') select /\*+mapjoin(tt)\*/ id,name from tt;

**Comment by wenshao** [comment]
已修复，和#1495 是同一个问题

**Comment by wenshao** [comment]
已经支持，请使用1.0.27版本 https://github.com/alibaba/druid/releases/tag/1.0.27
