### ISSUE TITLE
[ODPS]SQLSelect类equals方法语义不正确

### ISSUE THREAD

**Issue by zillionbrains** [alibaba/druid#1507]
equals会认为两个不同的SQLSelect相等

List<SQLStatement> stmtsA = SQLUtils.parseStatements("select * from a", JdbcConstants.ODPS);
List<SQLStatement> stmtsB = SQLUtils.parseStatements("select * from b", JdbcConstants.ODPS);
SQLSelect selectA = ((SQLSelectStatement) stmtsA.get(0)).getSelect();
SQLSelect selectB = ((SQLSelectStatement) stmtsB.get(0)).getSelect();
boolean eq = selectA.equals(selectB);
assertTrue(eq);

**Comment by wenshao** [comment]
已经解决，如果是内部用户，可以用这个快照：http://mvnrepo.alibaba-inc.com/mvn/snapshots/com/alibaba/druid/1.0.27-SNAPSHOT/

**Comment by wenshao** [comment]
已经支持，请使用1.0.27版本 https://github.com/alibaba/druid/releases/tag/1.0.27
