### ISSUE TITLE
增加keepalive功能

### ISSUE THREAD

**Issue by Zeratulllll** [alibaba/druid#1520]
在设定参数的时间间隔，使用ping指令或者testQuery去保持连接处于活跃状态，避免被MySQL空闲超时干掉。

**Comment by liwenxian** [comment]
这几天测试的结果：minEvictableIdleTimeMillis 这个设置过小的话（30分、1分钟等），keepalive也保持不住最小连接数。 使用的版本是1.0.31

**Comment by liwenxian** [comment]
从控制台上 KeepAlive检测次数  一直是0

**Comment by lizongbo** [comment]
已经有该特性
