### ISSUE TITLE
Druid解析SQL出错

### ISSUE THREAD

**Issue by errorize** [alibaba/druid#1542]
测试SQL样本：select c1 from t1 t where t.c2=1 and (t.c3=1 or t.c3=5)，使用Druid解析会丢掉t.c3=5。Debug一下发现是方法com.alibaba.druid.sql.dialect.oracle.visitor.OracleParameterizedOutputVisitor.visit(SQLBinaryOpExpr)导致的问题，求解！！！

**Comment by errorize** [comment]
不过我使用Debug测试发现，修改方法com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.mergeEqual(SQLExpr, SQLExpr)的“binaryA.getLeft().toString().equals(binaryB.getLeft().toString()) ”修改为“binaryA.equals(binaryB)”即可解决问题。还是很佩服温少的大神之作！！！

**Comment by wenshao** [comment]
这个设计是故意的哈

**Comment by errorize** [comment]
温少，能说一下具体原因吗？你的思想超出我的理解能力了。

**Comment by wenshao** [comment]
参数化就是用来合并SQL.
```
select * from t where id = 1
select * from t where id = 1 or id = 2
select * from t where id = 1 or id = 2 or id = 3
select * from t where id = 1 or id = 2 or id = 3 or id = 4
```
这些SQL都可以认为是同一个SQL模板
