### ISSUE TITLE
MySql Druid1.0.26 Communication Link Fail

### ISSUE THREAD

**Issue by ro9er** [alibaba/druid#1545]
有一个线上项目使用的Druid，这个项目的数据库查询不会特别频繁，是不定期的离散的访问，前段时间发现经常爆出Communication Link Fail。询问过DBA数据库的链接超时时间设置的是1个小时。这边之前按照DBCP的设置是设置好了numTestsPerEvictionRun和timeBetweenEvictionRunsMillis保证了能够在超时时间之内把db链接排出去，但是druid的设计我看是不太一样的。
首先numTestsPerEvictionRun是没用的。
我在源码中看到貌似开了一个DestroyThread来做相同的事情，在minIdle以外的用minEvictableIdleTimeMillis去做判断，而在minIdle内的用maxEvictableIdleTimeMillis来做判断，但是我都设置了这两个参数到我认为准确的值，但是还是会出现Communication Link Fail，请问是否是我的配置有问题，或者是这是一个bug？
配置properties如下：
druid.maxActive=50
druid.maxIdle=30
druid.maxWait=1000
druid.removeAbandoned=true
druid.removeAbandonedTimeout=180
druid.timeBetweenEvictionRunsMillis=30000
druid.minEvictableIdleTimeMillis=600000
druid.maxEvictableIdleTimeMillis=1500000
druid.validationQuery=SELECT 1 FROM DUAL
druid.testWhileIdle=true 
druid.testOnBorrow=false
druid.testOnReturn=false
druid.poolPreparedStatements=true
druid.numTestsPerEvictionRun=30

**Comment by lizongbo** [comment]
请使用最新版本验证
