### ISSUE TITLE
Druid是一个JDBC组件库，包括数据库连接池、SQL Parser等组件。DruidDataSource是最好的数据库连接池。

### ISSUE THREAD

**Issue by 3792274** [alibaba/druid#1549]
我只想问下，和  HikariJSON（https://github.com/brettwooldridge/HikariJSON）
相比，性能如何？

**Comment by pansw2** [comment]
J2EE交流QQ群129478078 ，两年以上J2EE开发经验者请进。新手勿进。

**Comment by lizongbo** [comment]
Druid里的json类只是很轻量的json处理逻辑。
