### ISSUE TITLE
Druid+SQLite+LIMIT错误

### ISSUE THREAD

**Issue by leonhoo** [alibaba/druid#1556]
使用Druid连接SQLite时,如果使用LIMIT关键字,会出现com.alibaba.druid.sql.parser.ParserException expect IDENTIFIER, actual IDENT...的错误.
Druid版本为1.0.27

**Comment by pansw2** [comment]
J2EE交流QQ群129478078 ，两年以上J2EE开发经验者请进。新手勿进。

**Comment by wenshao** [comment]
已经支持，请使用1.0.28版本
