### ISSUE TITLE
多线程下java工程(非web工程)整合druid+spring的问题

### ISSUE THREAD

**Issue by Moouna** [alibaba/druid#1562]
我希望使用druid数据源以及spring的一些注解（@autowired、@Transactional等）来对项目进行分层，但是在多线程的环境下使用druid发现了一些问题不知道是不是我的配置问题，
在同时开启100个线程，并且maxActive<=100的时候DruidDataSource获取connection会造成所有线程全部在running状态而在maxActive>100的时候所有的线程都正常执行并且顺利释放了连接。无论怎么测试都是如此的情况一旦线程数大于maxActive，获取connection的时候便会出现问题。
`<bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource" init-method="init" destroy-method="close">
		
		<property name="driverClassName" value="${jdbc.driverClass}"></property>
		<property name="url" value="${jdbc.jdbcUrl}"></property>
		<property name="username" value="${jdbc.user}"></property>
		<property name="password" value="${jdbc.password}"></property>
		<property name="filters" value="config" />
     	<property name="connectionProperties" value="config.decrypt=true;config.decrypt.key=${jdbc.publicKey}" />
     	<property name="asyncCloseConnectionEnable" value="${druid.asyncCloseConnectionEnable}"></property>
		
		
		<property name="initialSize" value="${druid.initialSize}"></property>
		
		<property name="maxActive" value="${druid.maxActive}"></property>
		
		<property name="poolPreparedStatements" value="${druid.poolPreparedStatements}"></property>
		
		<property name="maxOpenPreparedStatements" value="${druid.maxOpenPreparedStatements}"></property>
		
		
		
		<property name="testOnBorrow" value="${druid.testOnBorrow}"></property>
		
		<property name="testOnReturn" value="${druid.testOnReturn}"></property>
		
		<property name="testWhileIdle" value="${druid.testWhileIdle}"></property>
		
		<property name="timeBetweenEvictionRunsMillis" value="${druid.timeBetweenEvictionRunsMillis}"></property>
		
		<property name="connectionInitSqls" value="${druid.connectionInitSqls}"></property>
		
		
	</bean>`
`druid.initialSize = 3
druid.maxActive = 4
druid.poolPreparedStatements = false
druid.maxOpenPreparedStatements = -1
druid.validationQuery = select 1 from dual
druid.testOnBorrow = false
druid.testOnReturn = false
druid.testWhileIdle = true
druid.timeBetweenEvictionRunsMillis = 300000
druid.connectionInitSqls =select 1 from dual
druid.asyncCloseConnectionEnable=true`

**Comment by pansw2** [comment]
J2EE交流QQ群129478078 ，两年以上J2EE开发经验者请进。新手勿进。

**Comment by hyy80488** [comment]
我也遇到同样问题，请问是有什么配置不对的么

**Comment by hyy80488** [comment]
我也遇到同样问题，请问是有什么配置不对的么
