### ISSUE TITLE
Sql Parser不支持MySql的DATE_ADD函数

### ISSUE THREAD

**Issue by monkey-an** [alibaba/druid#1567]
druid:1.0.27
SQL:select DATE_ADD(now(),INTERVAL -1 day);
Exception:com.alibaba.druid.sql.parser.ParserException: TODO
Please confirm this problem,thx!

**Comment by wenshao** [comment]
什么数据库？

**Comment by wenshao** [comment]
已经支持，请使用新版本 https://github.com/alibaba/druid/releases/tag/1.0.30
