### ISSUE TITLE
希望 DruidDataSource  能够支持 v$session.program参数

### ISSUE THREAD

**Issue by wangjh29qq** [alibaba/druid#1574]
希望 DruidDataSource  能够支持 v$session.program参数

例如
```
  <property name="properties"> 
        <map>   
           <entry key="user" value="zhangsan"/> 
            <entry key="password" value="zhangsan"/>
            <entry key="v$session.program" value="myprogram"/> 
        </map> 
     </property>
```

这样，在oracle数据库里的v$session视图里的program列 都能看到具体的program

c3p0 支持 v$session.program参数, 见
http://xiaobai1023.iteye.com/blog/455333

**Comment by wenshao** [comment]
可以通过setConnectionProperties来配置达到同样效果

**Comment by jxf114208** [comment]
是这样设置吗：
`dataSource.setConnectionProperties("v$session.program=abc;");`
其他都不用管了？oracle就能识别了？

**Comment by wangjh29qq** [comment]
知道了，在 ApplicationContext.xml    配置文件中，按如下配置：

<bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource"
          init-method="init" destroy-method="close">         
        
        <property name="url" value="${jdbc.jdbcUrl}"/>         
        <property name="username" value="${jdbc.user}"/>
        <property name="password" value="${jdbc.password}"/>
        <property name="connectionProperties" value="v$session.program= JDBC_THIN_CLIENT_A" />
</bean>
