### ISSUE TITLE
监控不到事务

### ISSUE THREAD

**Issue by ji4597056** [alibaba/druid#1575]
用的springboot框架，开启事务使用@EnableTransactionManagement，事务方法使用@Transactional，但是所有的监控sql都显示事务中，事务提交数和事务回滚数为0或者空白

**Comment by lizongbo** [comment]
![image](https://github.com/alibaba/druid/assets/1670666/d8b70668-8733-459e-bf2c-127f1c4d06c8)

请使用1.2.20.事务数正常。
