### ISSUE TITLE
druid jmx 监控  DruidDataSource

### ISSUE THREAD

**Issue by weiboyiyou** [alibaba/druid#1581]
druid jmx 监控  DruidDataSource ，配置的datasource 每次重启 id  发生变化，有没有起他方式可以固定监控到，而不用每次重启要修改 jmx  监控的 datasource id ?

**Comment by baibaluo** [comment]
同样的问题，如果ID可以固定，或者换成dataSourceName，就可以很容易配合Zabbix的自动发现机制了。

**Comment by weiboyiyou** [comment]
是的，有没有什么变通的办法可以做到？

**Comment by weiboyiyou** [comment]
可以自己写代码：
public class Jmxfordruid {
  public static void main(String[] args) throws Exception { 
	  if (args.length<=0){
		  System.out.print("使用方式:请数据jmx地址,监控主备的数据源,已经监控属性！");
		  System.exit(1);
	  }
	  String addr=args[0];
	  String flag=args[1]; //master slave noslave
	  String attr=args[2]; 
	  String jmxurl="service:jmx:rmi:///jndi/rmi://"+addr+"/jmxrmi";
	  //"service:jmx:rmi:///jndi/rmi://192.168.32.12:59067/jmxrmi"
      JMXServiceURL url = new JMXServiceURL(jmxurl);  
      JMXConnector conn = JMXConnectorFactory.connect(url);  
      MBeanServerConnection mbsc = conn.getMBeanServerConnection();
      Set<ObjectName> mbeans = mbsc.queryNames(null,null);
      for (ObjectName ob : mbeans) {  
         if(ob.toString().contains("com.alibaba.druid:type=DruidDataSource,id")){
        	 ObjectName datasource = new ObjectName(ob.toString());
             if(flag.contentEquals("slave")){
            	 if(mbsc.getAttribute(datasource,"Url").toString().contains("bak")){
            	  System.out.println(mbsc.getAttribute(datasource,attr));
            	 }
             }
             if(flag.contentEquals("master")){
            	 if(!(mbsc.getAttribute(datasource,"Url").toString().contains("bak"))){
            	  System.out.println(mbsc.getAttribute(datasource,attr));
            	 }
             }
         }
    }  
  }
}
