### ISSUE TITLE
无法登陆druid控制台，和spring security 一起使用

### ISSUE THREAD

**Issue by quan01994** [alibaba/druid#1587]
这是我的security配置
![image](https://cloud.githubusercontent.com/assets/20533465/22109889/a3860606-de94-11e6-99a9-4c8827c64c31.png)
这是我的druid配置
![image](https://cloud.githubusercontent.com/assets/20533465/22109917/be4dc578-de94-11e6-9bcb-8115cda847df.png)
出现的问题
![image](https://cloud.githubusercontent.com/assets/20533465/22110136/9d4cc4b8-de95-11e6-8672-44e146047f93.png)
这是我的springboot版本和druid版本
![image](https://cloud.githubusercontent.com/assets/20533465/22110156/b10897e8-de95-11e6-9945-37417d01e5ca.png)
![image](https://cloud.githubusercontent.com/assets/20533465/22110159/b586e89c-de95-11e6-8056-6a2ea8984b82.png)

如果去掉security就一切正常
是不是我的配置有问题啊

**Comment by quan01994** [comment]
已经解决了。。。。

**Comment by Hisen158** [comment]
@quan01994 why issuse? pls finsh with full  solutions to  help other guys.

**Comment by quan01994** [comment]
@Hisen158  这是我第一次issuse 

这是我的解决办法
在spring boot 中的spring security配置中，一定要这样配置
千万不要用 successForwardUrl()
这是成功的配置 
![image](https://cloud.githubusercontent.com/assets/20533465/22139873/ef89cc38-df23-11e6-86d3-6189db05f024.png)
