### ISSUE TITLE
use flyway  failed startup for: sql injection violation, comment not allow

### ISSUE THREAD

**Issue by yililiangbaikai** [alibaba/druid#1594]
What version of Flyway are you using?

4.0.3

Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API

What database are you using (type & version)?

mysql5.7

What operating system are you using?

windows&linux

What did you do?

I use Druid database connection pool, the fault seems to it's default setting don't allow comment in sql execution.

What did you expect to see?
the sql above is absolutely ok, it's totally a defect . Please fix it as soon as possible. thx a lot.
What did you see instead?

Caused by: org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException: 
Script failed
-------------
SQL State  : null
Error Code : 0
Message    : sql injection violation, comment not allow : CREATE TABLE `db`.`table_version` (
    `installed_rank` INT NOT NULL,
    `version` VARCHAR(50),
    `description` VARCHAR(200) NOT NULL,
    `type` VARCHAR(20) NOT NULL,
    `script` VARCHAR(1000) NOT NULL,
    `checksum` INT,
    `installed_by` VARCHAR(100) NOT NULL,
    `installed_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `execution_time` INT NOT NULL,
    `success` BOOL NOT NULL,
    -- Add the primary key as part of the CREATE TABLE statement in case `innodb_force_primary_key` is enabled
    CONSTRAINT `table_version_pk`PRIMARY KEY (`installed_rank`)
) ENGINE=InnoDB

**Comment by yililiangbaikai** [comment]
wallconfig可以解决这个问题。
`
    
    <bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource" init-method="init" destroy-method="close">
        
        <property name="url" value="${connection.url}"/>
        <property name="username" value="${connection.username}"/>
        <property name="password" value="${connection.password}"/>

        
        <property name="initialSize" value="${druid.initialSize}"/>
        <property name="minIdle" value="${druid.minIdle}"/>
        <property name="maxActive" value="${druid.maxActive}"/>

        
        <property name="maxWait" value="${druid.maxWait}"/>
        
        <property name="timeBetweenEvictionRunsMillis" value="${druid.timeBetweenEvictionRunsMillis}" />

        
        <property name="minEvictableIdleTimeMillis" value="${druid.minEvictableIdleTimeMillis}" />

        <property name="validationQuery" value="${druid.validationQuery}" />
        <property name="testWhileIdle" value="${druid.testWhileIdle}" />
        <property name="testOnBorrow" value="${druid.testOnBorrow}" />
        <property name="testOnReturn" value="${druid.testOnReturn}" />

        
        <property name="poolPreparedStatements" value="${druid.poolPreparedStatements}" />
        <property name="maxPoolPreparedStatementPerConnectionSize" value="${druid.maxPoolPreparedStatementPerConnectionSize}" />

        
        
        <property name="proxyFilters">
	          <list>
	              <ref bean="wallFilter"/>
	              <ref bean="statFilter"/>
	          </list>
      	</property>
    </bean>
    
    <bean id="statFilter" class="com.alibaba.druid.filter.stat.StatFilter">  
	    <property name="slowSqlMillis" value="10000" />  
	    <property name="logSlowSql" value="true" />  
	</bean>
	
    <bean id="wallFilterConfig" class="com.alibaba.druid.wall.WallConfig" init-method="init">
	      
	      <property name="dir" value="" />
	      <property name="commentAllow" value="true" />
    </bean>
    
  	<bean id="wallFilter" class="com.alibaba.druid.wall.WallFilter">
      	<property name="dbType" value="mysql" />
      	<property name="config" ref="wallFilterConfig" />
  	</bean>`

**Comment by baikeh** [comment]
@yililiangbaikai 最新的springboot2.x上这个配置不起作用，可否给看看？ `druid.filter.wall.config.comment-allow: true`
