### ISSUE TITLE
不支持ODPS多路输出解析

### ISSUE THREAD

**Issue by zillionbrains** [alibaba/druid#1605]
from sale_detail
        insert overwrite table sale_detail_multi partition (sale_date='2010', region='china' )
            select shop_name, customer_id, total_price
        insert overwrite table sale_detail_multi partition (sale_date='2011', region='china' )
            select shop_name, customer_id, total_price;

**Comment by wenshao** [comment]
应该支持的啊，你用的是druid什么版本？

**Comment by zillionbrains** [comment]
1.0.27，是后面支持的吗？

**Comment by wenshao** [comment]
如下的写法现在是支持的：
```sql
from (select * from sale_detail)
insert overwrite table sale_detail_multi partition (sale_date='2010', region='china' )
select shop_name, customer_id, total_price
insert overwrite table sale_detail_multi partition (sale_date='2011', region='china' )
select shop_name, customer_id, total_price;
```
后续会支持你上面的写法
