### ISSUE TITLE
druid +SQLite + limit 前 + order by时 出错

### ISSUE THREAD

**Issue by caishuai163** [alibaba/druid#1611]
ERROR: com.alibaba.druid.filter.stat.StatFilter - merge sql error, dbType sqlite, sql : select * from  表名  ORDER BY id DESC limit 0,10
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'DESC limit 0,10',expect LIMIT, actual LIMIT limit

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.4
问题已经修复，请使用新版本
