### ISSUE TITLE
关于解析外键：ON DELETE NO ACTION ON UPDATE NO ACTION

### ISSUE THREAD

**Issue by 694551594** [alibaba/druid#1612]
com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser类的877行：
` } else if (identifierEquals("ON")) {
            lexer.nextToken();
            if (identifierEquals("ACTION")) {
                option = Option.NO_ACTION;
                lexer.nextToken();
            } else {
                throw new ParserException("syntax error, expect ACTION, actual " + lexer.token() + " "
                                          + lexer.stringVal());
            }
        } else {`

“ON”是不是应该是“NO”啊？
我跟了下代码，如果是ON的话这个if条件永远也不会成立的。

**Comment by wenshao** [comment]
能提供重现问题的sql么？

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
