### ISSUE TITLE
com.alibaba.druid.proxy.DruidDriver本意是否是想设计成单例？

### ISSUE THREAD

**Issue by 34benma** [alibaba/druid#1634]
看源码是发现一个小小的问题，com.alibaba.druid.proxy.DruidDriver这个类本意是否是想设计成单线程单例？但是构造函数却又是public

不知是我理解不到位还是代码的一点点小小瑕疵？

版本 V1.0.27

**Comment by wenshao** [comment]
内部使用单例，但会有很多场景需要通过classname反射构造的，所有构造函数public。
