### ISSUE TITLE
Oracle驱动使用Druid报出AbstractMethodError异常

### ISSUE THREAD

**Issue by ascrutae** [alibaba/druid#1636]
我的oracle jdbc的驱动包版本是jdk1.3编译的，而Druid在运行过程中会使用jdk1.7新增了一些接口比如说Preparedstatement的unwraps方法，所以出现AbstractMethodError的错误(如下图).请问下如何支持这些老版本的驱动？
![9c37e43f2c8e16536f012f4794d69af2](https://cloud.githubusercontent.com/assets/12436447/23829156/671278e0-0724-11e7-8cd2-ae105d015d66.jpg)

**Comment by wenshao** [comment]
能升级新版本驱动么？

**Comment by flywhitebirds** [comment]
升级ojdbc6就没问题了。
