### ISSUE TITLE
The last packet successfully received from the server was 21,891 milliseconds ago

### ISSUE THREAD

**Issue by YanXs** [alibaba/druid#1639]
使用DHCP数据库重启后请求不会报错，使用druid会报The last packet successfully received from the server was 21,891 milliseconds ago异常

**Comment by onlyzzw** [comment]
@YanXs ,你好我也遇到这个问题了，报错信息和你一样，请问你是怎么解决的？

**Comment by YanXs** [comment]
@onlyzzw 我之前说DHCP不会报错是不对的，我在另一个Issue中解释了，数据重启一样会出现这个异常，至于解决办法我觉得有两种方式（单库无负载均衡）:1，如果数据库重启，重启对应的应用。2，如果对性能要求一般，开启testOnBorrow。
