### ISSUE TITLE
日志 filters 中的某些属性还不能配置么？如  connectionCommitAfterLogEnable 这类

### ISSUE THREAD

**Issue by H-hao** [alibaba/druid#1646]
在xml中配置了后报错。
 org.springframework.beans.NotWritablePropertyException: Invalid property 'connectionCommitAfterLogEnable' of bean class [com.alibaba.druid.filter.logging.Log4jFilter]: Bean property 'connectionCommitAfterLogEnable'` is not writable or has an invalid setter method`. Did you mean 'connectionCommitAfterLogEnabled'?

**Comment by wenshao** [comment]
少了一个字母d
