### ISSUE TITLE
druid会发了kill命令吗？

### ISSUE THREAD

**Issue by guozhouwei** [alibaba/druid#1649]
如果SQL太慢了（比如查询速度很慢）, druid会发了个kill命令杀掉吗？ 如果有，如何设置这个时间？

**Comment by ananas-hebo** [comment]
这个功能 没必要吧

**Comment by wenshao** [comment]
如果你设置了executeQueryTimeOut，mysql driver会发，而不是dataSource发。

**Comment by Yaccc** [comment]
JDBC driver在设置了timeout的情况下会发
