### ISSUE TITLE
建议wiki中的带有中文的url美化处理下

### ISSUE THREAD

**Issue by crane-yuan** [alibaba/druid#1657]
比如：

将这个url
https://greasyfork.org/zh-CN/scripts/25697-%E6%96%B0%E6%B5%AA%E5%BE%AE%E5%8D%9A%E4%B8%80%E9%94%AE%E6%B8%85%E7%A9%BA

改为：
https://greasyfork.org/zh-CN/scripts/25697-新浪微博一键清空

这样url的信息比较完整些，希望你们可以采纳我的建议，谢谢了。

**Comment by wenshao** [comment]
权限是开放的，你直接帮改了？

**Comment by crane-yuan** [comment]
@wenshao 已经把我发现的一些小问题都改了 :smile:
