### ISSUE TITLE
配置连接池之后，每次访问数据库仍然新建SqlSession

### ISSUE THREAD

**Issue by changdy** [alibaba/druid#1660]
以连续的两次访问数据库为例：
//第一次
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@4474cc30] was not registered for synchronization because synchronization is not active
JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@3881726d] will not be managed by Spring
//select * from dual
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@4474cc30]
//第二次
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@151d520e] was not registered for synchronization because synchronization is not active
JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@3881726d] will not be managed by Spring
//select * from dual
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@151d520e]

可以看到每次访问数据库仍然会新建一个SqlSession。dataSource配置已经确保无误。mybatis中也配置了<property name="dataSource" ref="dataSource"/>。不知道还有没有其他需要配置的地方。
* mysql-connector-java：6.0.5
* druid：1.0.29
* org.springframework：4.3.6.RELEASE
* mybatis-spring：1.3.1
* mybatis ：3.4.2
* tomcat：8.5.11
* jdk：8

谢谢

**Comment by Leviathans** [comment]
我也遇到同样的问题，请问怎么回事？

**Comment by Leviathans** [comment]
@changdy

**Comment by changdy** [comment]
@Leviathans 
参考 https://www.zhihu.com/question/57568941 lllllustrator的回答。

**Comment by xdp6688** [comment]
同样的问题，无解啊

**Comment by changdy** [comment]
@xdp6688 
楼上已经给回复.

**Comment by xdp6688** [comment]
参考楼上的做法，但是还是不行

**Comment by xdp6688** [comment]
项目里边又shiro和dubbo，会不会和什么冲突了

**Comment by Future2100** [comment]
需要在service上加@Transactional

**Comment by XINJIN422** [comment]
@changdy lllllustrator 的结果并不对, 即使配置了事务, 每次请求仍然会 Creating a new SqlSession, 因为SqlSession 和 Connection 并不是一个概念; 如果配置了数据库连接池, 可以看到 Fetching JDBC Connection from DataSource;

**Comment by blankhang** [comment]
+1

**Comment by pauljy** [comment]
> @changdy lllllustrator 的回答并不对, 即使配置了事务, 每次请求仍然会 Creating a new SqlSession, 因为SqlSession 和 Connection 并不是一个概念; 如果配置了数据库连接池, 可以看到 Fetching JDBC Connection from DataSource;

感觉这个说法是对的 详见这个说明：https://www.pianshen.com/article/2747380017/
