### ISSUE TITLE
druid-1.0.29 是否对oracle12c的分页语法不支持？

### ISSUE THREAD

**Issue by qw3376803** [alibaba/druid#1661]
```
Error querying database.  Cause: java.sql.SQLException: sql injection violation, syntax error: syntax error, expect FIRST, actual NEXT : 
	SELECT 
   .....此处省略
       ORDER BY CREATE_TIME DESC OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY 
```

**Comment by dachuanz** [comment]
看代码，应该是还没支持

**Comment by qw3376803** [comment]
👍 是的。我也代码搜索了下没找到相关代码，：)

**Comment by wenshao** [comment]
收到，尽快支持

**Comment by qw3376803** [comment]
感谢！！

**Comment by jounzhang** [comment]
居然已经有前人出现过这个问题了，我也提了一个这个isuse

**Comment by tianlucode** [comment]
请问这个问题啥时候可以修复呢？谢谢！

**Comment by lizongbo** [comment]
验证了了一下，解析正常，但是重新生成的sql里，next 处理成了 first ，看上去不影响功能。

 String sql = "select * from aa  ORDER BY CREATE_TIME DESC OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY";

预期:select * from aa order by create_time desc offset 0 rows fetch next 10 rows only
实际:select * from aa order by create_time desc offset 0 rows fetch first 10 rows only
