### ISSUE TITLE
个人感觉监控session页面应该是显示系统中有效的session而不是所有建立过的session

### ISSUE THREAD

**Issue by javyuan** [alibaba/druid#1666]
druid版本：1.0.11
即使http中的session失效了，在web应用中已经不存在了，但该session信息还是在sessionStatMap中，还会显示在Session监控页面，个人感觉这里监控session应该是系统中有效的session而不是所有建立过的session，个人理解，不妥勿怪。

**Comment by javyuan** [comment]
本来想自己写个listener监控session，然后从sessionStatMap中把对应的session清掉，但是sessionStatMap是private的还没有get方法，WebAppStauUtils中也没有提供remove sessionStatMap的方法。

**Comment by lizongbo** [comment]
现在是设置了size上限为1000的map来存的，没有监听session销毁事件。以后看谁有需求，再来考虑优化效果。
