### ISSUE TITLE
MySQL语法解析问题

### ISSUE THREAD

**Issue by rickycoder** [alibaba/druid#1679]
version:1.0.15
```sql
ALTER TABLE T 2 ADD INDEX (d), ADD UNIQUE (a),ADD UNIQUE INDEX IUNIQ_AREA_ID_LOCK(AREA_ID,CHECK_DATE,LOCK_TIME) ;
```

```java
MySqlStatementParser parser = new MySqlStatementParser(sql);
SQLStatement statement = parser.parseStatement();
MySqlAlterTableStatement ats=(MySqlAlterTableStatement )statement ;
ats..getItems().size();// size=0 
```
期望现象应该是ParserException 语法错误，以下是MySQL5.6的报错信息：
[SQL]ALTER TABLE T 2 ADD INDEX (d), ADD UNIQUE (a),ADD UNIQUE INDEX IUNIQ_AREA_ID_LOCK(AREA_ID,CHECK_DATE,LOCK_TIME) ;
[Err] 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '2 ADD INDEX (d), ADD UNIQUE (a),ADD UNIQUE INDEX IUNIQ_AREA_ID_LOCK(AREA_ID,CHEC' at line 1

**Comment by LamentWy** [comment]
ALTER TABLE **T 2** ADD INDEX (d), ADD UNIQUE (a),ADD UNIQUE INDEX IUNIQ_AREA_ID_LOCK(AREA_ID,CHECK_DATE,LOCK_TIME) ;
SQL语法错误，注意加粗部分

**Comment by lizongbo** [comment]
现在是解析没有报错，重新生成的sql 是“alter table t” ，后面再看幺幺做成抛异常的。
