### ISSUE TITLE
logs优化

### ISSUE THREAD

**Issue by weishuwei** [alibaba/druid#1682]
比如在DruidDataSource的785行（版本1.0.29），日志为LOG.info("{dataSource-" + this.getID() + "} inited");
如果有多个datasource的话，通过id是比较难识别到底是那个datasource，希望加一下name等信息，或者有个地方打印了id对应的name是什么

**Comment by wenshao** [comment]
已经支持，请使用新版本 https://github.com/alibaba/druid/releases/tag/1.0.30
