### ISSUE TITLE
postgreSql数据库，操作json报错

### ISSUE THREAD

**Issue by shuzijun** [alibaba/druid#1689]
java.sql.SQLException: sql injection violation, syntax error: ERROR. token : GTGT, pos : 22 : SELECT
			"result" ->> 'PROD_TYPE_NAME' ,
			"result" ->> 'IMAGES'
		FROM
			mobile_info_cnmo

**Comment by wenshao** [comment]
新版本是好的，更新版本试试看  https://github.com/alibaba/druid/releases/tag/1.0.29
