### ISSUE TITLE
Slf4jLogFilter日志打印SQL错误的问题

### ISSUE THREAD

**Issue by FreeMan19901113** [alibaba/druid#1694]
持久层用是MyBatis，由于特殊情况不能贴日志太打印信息，所以只能描述一下。
mybatis执行的sql语句是
select count(0) 
from tb_user 
where 
(login_name like '%j%' and v_sort between 1 and 10 )
 or 
(display_name like '%j%' and v_sort between 1 and 10 ) 
但是日志打印出来是
select count(0)
from tb_user 
where 
login_name like '%j%' and v_sort between 1 and 10  
or  
display_name like '%j%' and v_sort between 1 and 10 
语句中的括号没有了，虽然执行的是正确的语句但是在调试上会造成误导。
请大神看看！日志实现是slf4j

**Comment by CodingOX** [comment]
补充下：使用的是mybatis自带的example的用法，此处问题发生在使用or条件拼接2个criteria的时候。

**Comment by wenshao** [comment]
这个现在的实现中要加上括号有点麻烦

**Comment by wenshao** [comment]
问题已解决，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.3
