### ISSUE TITLE
druid 打印出的sql可以不换行吗

### ISSUE THREAD

**Issue by Darkknightxrb** [alibaba/druid#1696]
druid 打印出的sql可以不换行吗，方便在日志中查看，换行的话grep的时候不能完整显示sql

**Comment by walle1027** [comment]
<bean id="logFilter" class="com.alibaba.druid.filter.logging.Log4j2Filter">
	<property name="statementSqlFormatOption">
		<bean class="com.alibaba.druid.sql.SQLUtils.FormatOption">
			<property name="parameterized" value="false"/>
			<property name="prettyFormat" value="false"/>
			<property name="uppCase" value="false"/>
		</bean>
	</property>
</bean>

这样配置就可以了
