### ISSUE TITLE
druid-spring-boot-starter

### ISSUE THREAD

**Issue by lihengming** [alibaba/druid#1701]
#1692 昨天看到该Issues，加之近来项目也在使用Spring Boot + Druid。由于Spring Boot官方默认不支持Druid导致连接池配置较为繁琐，Spring监控的Aop部分也比较麻烦。所以，今天利用工作之余编写了druid-spring-boot-starter项目，但不知该如何合并，暂时将初始化版本放在了自己的仓库[druid-spring-boot-starter](https://github.com/lihengming/druid-spring-boot-starter)，望指教，已尽微博之力。

**Comment by wenshao** [comment]
在右上角的fork按钮，将druid fork到个人的repository中，将修改commit到自己的repository的druid项目中，然后通过Pull Request提交过来，我合并就好了。希望你按这个流程来参与进来，一起完善这个项目。

**Comment by lihengming** [comment]
已Pull Request，由于没有parent pom我没有创建maven module，你来处理吧。

**Comment by wenshao** [comment]
parent pom注释掉就好了

**Comment by lihengming** [comment]
ok
