### ISSUE TITLE
希望PageUtils.hasUnorderedLimit方法能过滤掉嵌套的order by在limit之前的sql

### ISSUE THREAD

**Issue by yangxinying** [alibaba/druid#1710]
您好，之前跟您沟通过，希望PageUtils.hasUnorderedLimit能够识别并过滤掉如下种类的sql：
select * from (select * from test t order by id desc) z  limit 100  如果order by出现在limit前面，则认为是正常的sql；

**Comment by wenshao** [comment]
已经支持，请使用新版本 https://github.com/alibaba/druid/releases/tag/1.0.30
