### ISSUE TITLE
状态机检测工具

### ISSUE THREAD

**Issue by likaer** [alibaba/druid#1714]
业务背景： 目前很多系统在更新对象的当前状态的过程前可能没有充分判断该对象的前置状态，因此在一些状态机变化的情况下的情况下，会导致对象状态变更未遵循合理的状态机。

工具诉求：基于以上业务背景， 希望能够在SQL执行前， 检测所有SQL， 当该SQL在set状态A字段的时候， 该SQL的where语句应该包含判断状态A的当前状态为对应的前置状态，来避免状态机的异常流转。

期望的实现：

        1. 提供一个接口给外围系统实现，接口定义如下：
                入参：数据源， 表名。
                返回：该表下所有需要控制的状态类型的字段， 以及对应的前置状态。

                ExampleCode：
		boolean check(String table, Map<String, Object> setValues, Map<String, 
                                             List<Object>> filterValues) {
                }

        2. 检测逻辑：
                根据接口返回的状态和前置状态， 分析SQL是否存在set状态类型的字段，如果是， 那么where语
                句必须包含判断该状态的当前状态满足对应的前置状态，否则进入“异常处理机制”。

                ExampleSql:
                update invoice set invoice_status = 'ENABLE', GMT_MODIFIED = SYSDATE, MODIFIER = 'kaer.lke' 
                WHERE INVOICE_NO = '123456' AND INVOICE_STATUS = 'DISABLED';

                此时调用getPrefixValues(datasource, "invoice", "invoice_status", "ENABLE")
               1. 返回 ["DISABLED"] , 检测通过。
               2. 返回 ["NEW", "DISABLED"] , 检测通过。                  
               3. 返回 [] , 检测通过。                
               4. 返回 ["NEW"] , 检测失败， 进入异常处理机制。                  

        3. 异常处理机制：
                提供一个配置化参数来控制异常的处理方式。
                    如果当前开关为打开， 那么抛出异常，并且不执行此SQL。
                    如果当前开关为关闭， 那么记录ERROR日志（具体的SQL信息）， 依然执行此SQL。

        4. 关于使用：
                希望通过spring简单注入该工具类（简单配置化）。

                ExampleCode:
                <bean id="statusBo" class="**. TableStatusBoImpl"/>
                <bean class="*.DruidSQLStatusMonitor">
                                <property name="tableStatusBo" ref="statusBo"/>
                </bean>

    ​    ​5. 性能的损耗：
    ​    ​    ​    ​希望能提供相关的性能损耗报告。

    ​    ​6. 多数据源的兼容性：
    ​    ​    ​    ​当系统配置多个数据源的情况，能同时支持多个数据源有不同配置。

**Comment by wenshao** [comment]
没想清楚怎么实现

**Comment by xiaooc** [comment]
我们的思路是，解析出来update语句中，set子句的字段及取值，然后判断该取值相关的原值是否出现在where子句中。
字段出现计算的场景先不考虑，但是别名希望能够考虑进来。

**Comment by wenshao** [comment]
问题已解决，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.3
