### ISSUE TITLE
distinct的情况下，总件数获取错误

### ISSUE THREAD

**Issue by brood-wangxr** [alibaba/druid#1715]
SQL文中包含distinct的情况下，获取到的总件数是distinct前的件数。
因为SQL为：SELECT DISTINCT COUNT(*) FROM XXX 
应该把distinct放在count内或者count的时候放在最外层。

**Comment by wenshao** [comment]
什么意思？没看懂

**Comment by brood-wangxr** [comment]
分页查询的时候，需要获取总件数，场景如下：
比如SQL文为：【select distinct a.col1,a.col2 from test a 】这时候实际件数为10件，其中重复的有5件。
框架拼出来的总件数检索SQL-_COUNT文为：【SELECT DISTINCT COUNT(*) FROM test a】 
这样获取到的件数为distinct之前的件数，为10件。但实际应该是5件（去重之后的件数）

**Comment by zmwxiaoming** [comment]
distinct不与具体的字段名写一起,这样写起作用么

**Comment by wenshao** [comment]
懂你的意思了，是PageUtils的实现不对

**Comment by brood-wangxr** [comment]
版本：druid-1.0.26.jar，例子如下：
执行SQL：select distinct a.col1,a.col2 from test a
求总件数的SQL：select distinct count(*) from test a（重复的数据件数也被统计）
正确的写法： select count(*) from (select distinct  a.col1,a.col2 from test a) （去掉重复后计算件数）
PS:高铁<notifications@github.com>回信，说懂我说的意思了，您可以通过测试SQL试试。

**Comment by guixincui** [comment]
对，我也遇到这个问题了。select count(distinct ...) 和 select distinct count(...) 两个不一样，应该是前者才对。

**Comment by guixincui** [comment]
前面这个issue只解决了distinct * 或者distinct后面只有1个列的情况。
https://github.com/alibaba/druid/issues/1060

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.1
问题已经修复，请使用新版本
