### ISSUE TITLE
oracle 搭配 log4jdbc（非内置的）时候报错：not support oracle driver 1.0

### ISSUE THREAD

**Issue by CodingOX** [alibaba/druid#1717]
1. log4jdbc使用的不是内置的log4jdbc而是：
`        <dependency>
            <groupId>org.bgee.log4jdbc-log4j2</groupId>
            <artifactId>log4jdbc-log4j2-jdbc4.1</artifactId>
            <version>1.16</version>
        </dependency>`
[因为内置的log4jdbc输出SQL会出现问题，具体问题已提出issues：](https://github.com/alibaba/druid/issues/1694)

2.已经排查排除是oracle的jar包的问题，一是因为如果我将driverClassName和jdbcurl改为正常的不加log4jdbc时候使用正常。二是因为使用log4jdbc但是连接池改用c3p0、HikariCP数据连接池此问题不报错。

**Comment by wenshao** [comment]
用Druid内置的LogFilter吧
https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_LogFilter

**Comment by CodingOX** [comment]
@wenshao Druid内置的LogFilter对于部分业务打印的SQL有问题，详细情况已经反馈：
https://github.com/alibaba/druid/issues/1694
感觉陷入死循环了。用内置的打印SQL出错，用第三方又不支持要报错 0.0

**Comment by wenshao** [comment]
使用log4jdbc报什么错误了？

**Comment by CodingOX** [comment]
包括主要信息是：not support oracle driver 1.0。
源码位置是在druid判定oracle版本号的时候，获取oracle版本号返回值的时候报错。

**Comment by 54104** [comment]
自己继承driverspy，重写构造方法，方法内判断版本为1，则调用acceptsURL，地址不用真实数据库地址，符合规则即可，主要是用此方法初始化下driver
最后driverClassName 配置自己写的driverspy，可以解决这个问题。
不过这是个bug啊，都不修复的吗？我看16年就有人提这个问题了。。

**Comment by wenshao** [comment]
建议放弃log4jdbc，使用Druid内置的LogFilter吧
https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_LogFilter

**Comment by reason-github** [comment]
> 建议放弃log4jdbc，使用Druid内置的LogFilter吧
> https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_LogFilter

内置logfilter用过，为啥又换回log4jdbc了呢？是因为记录的信息不如log4jdbc啊，仅日志记录这块，log4jdbc是记录最清晰，配置最简单的了
