### ISSUE TITLE
编写Jetty JNDI配置Druid数据源的例子

### ISSUE THREAD

**Issue by wenshao** [alibaba/druid#172]
文档写在这里：https://github.com/AlibabaTech/druid/wiki/%E9%85%8D%E7%BD%AE_JNDI_Jetty

1、分别提供Jetty 6/7/8各个版本的配置
2、要求配置提供者测试可用

参考文档
http://wiki.eclipse.org/Jetty/Feature/JNDI

**Comment by jacobpeng** [comment]
该问题是否已解决？jetty 8.1.5.v20120716下仍存在
