### ISSUE TITLE
druid 能使用logback么？

### ISSUE THREAD

**Issue by gaojia0814** [alibaba/druid#1723]

**Comment by wenshao** [comment]
遇到什么问题了？

**Comment by 1091662876** [comment]
估计和我的问题类似，我的logback基于slf4j,然后自动判断会判断为log4j,不过项目里没log4j，jcl-commons-logging,log4j-over-slf4j也没，有个jcl-over-slf4j，如果没猜错我项目里有隐藏的log4j，虽然我还没找到，然后日志就输出不了了。
    不过总感觉没配置环境变量的时候，这个加载顺序可以考虑调整下，slf4j   log4j2   log4j，好处在于，slf4j是正统，接口的方式，其次有slf4j大多少不了那几个桥接的包，就等于有了log4j  jcl这些。。
    在jvm添加启动参数Ddruid.logType或者在容器启动的监听里设置环境变量都可以解决这个问题
    据说filters设置成slf4j再加上META-INF下的配置文件也行

**Comment by 1091662876** [comment]
不过有一点很纳闷，Druid使用slf4j，其他的日志自己桥接呗，其实也不错啊，也就加2个jar的事

**Comment by kgdngitfk** [comment]
整个项目的使用的是logback作为日志的实现只能输出启动时的一行日志INFO  c.a.d.p.DruidDataSource:655 - {dataSource-1} inited
其它执行的sql都 没有办法通过 日志输出

**Comment by jackBaozz** [comment]
`
        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>log4j-over-slf4j</artifactId>
            <version>1.7.25</version>
        </dependency>
        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.26</version>
        </dependency>
        
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.3</version>
        </dependency>
`


加上这个
然后配置 logback-spring.xml

**Comment by xem1987** [comment]
> 整个项目的使用的是logback作为日志的实现只能输出启动时的一行日志INFO c.a.d.p.DruidDataSource:655 - {dataSource-1} inited
> 其它执行的sql都 没有办法通过 日志输出

兄弟，我也遇到这样的问题，你解决了吗？
我加了配置，也无效
```
spring.datasource.druid.filter.slf4j.enabled=true
spring.datasource.druid.filter.slf4j.statement-executable-sql-log-enable=true
```

**Comment by duwei54** [comment]
@xem1987 
配置加上
```
logging:
  level:
    druid.sql: debug
```

**Comment by psc0606** [comment]
我调试发现，得把日志级别设置DEBUG级别才行，文档中没有说明，有点坑人。不然只有这么一点日志。
