### ISSUE TITLE
Request for Maven Central 1.0.30 release

### ISSUE THREAD

**Issue by bobtiernay-okta** [alibaba/druid#1728]
Hi,

A lot of great stuff has gone into the current release and I was hoping we can promote this to central. 

ps. I didn't see any documentation for your release schedule or a forum so I'm creating this here. Sorry if this isn't the appropriate venue.

**Comment by wenshao** [comment]
Will be released on May 14th

**Comment by wenshao** [comment]
Has been released.  https://github.com/alibaba/druid/releases/tag/1.0.30
