### ISSUE TITLE
为什么我感觉监控这个东西很费性能啊

### ISSUE THREAD

**Issue by lazyfighter** [alibaba/druid#1730]
我把监控加到我们线上的cms  进行监控，第一个sql监控的页面的打开超级慢，页面渲染也是非常卡，  2000条 没有分页 ， 第二个session的监控 为什么不是有效的session啊   是系统建立过全部的session  另外能不能分页？  这个东西是我配置的不对  还是它本身很浪费性能

**Comment by wenshao** [comment]
这么多SQL，估计是没有参数化导致的，https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatFilter 参考这个文档的第4点 SQL合并配置

**Comment by lazyfighter** [comment]
ok  谢谢
