### ISSUE TITLE
参数化解析bug: 两个同名字段的where or条件会被合并成一个

### ISSUE THREAD

**Issue by qxo** [alibaba/druid#1745]
* before: `select * from test_tab1 where state=1 or state=3`

* after: 
```
SELECT *
FROM test_tab1
WHERE state = ?
size:[[1, 3]]
```

我已定位到是ParameterizedOutputVisitorUtils中merge或mergeEqual的实现问题
@wenshao 出来解释一下什么情况可以这样：
```
git blame -L 166,289  ParameterizedOutputVisitorUtils.java
....
a8bd3b249a (温少    2012-03-31 08:40:29 +0800 220)         // ID = ? OR ID = ? => ID = ?
```

**Comment by wenshao** [comment]
故意解析成这样的，因为程序中会存在类似如下的动态拼接的情况：
```sql
where id = 1 or id = 2 or id = 3 ...
```
在ibatis/mybatis下比较常见，这时候需要合并为同一个sql模板

**Comment by qxo** [comment]
Are you sure ?  

你的意思是`select * from test_tab1 where state=1 or state=3` 解析成sql模板`SELECT *
FROM test_tab1
WHERE state = ?`  然后执行多次？  麻烦给个样例
如只执行一次prepared sql 据我所知道不太可能（PreparedStatement.setArray 各个jdbc驱动基本不支持)

另外设计上ExportParameterVisitor应该只是对sql进行参数化处理，默认不应该进行sql进行转换，要转换也应调用方明确指定下进行！

**Comment by wenshao** [comment]
jdbc不是这样的，但是监控的合并SQL逻辑当前是这样的

**Comment by wenshao** [comment]
很抱歉，这个issue被遗漏太久了

**Comment by qxo** [comment]
今天看到，此问题在遗漏中，故修复之：） 
参见: #2500

**Comment by lizongbo** [comment]
代码距离现在太久了，不方便合并，因此关掉。
有需要的请重新提交新的pr
