### ISSUE TITLE
maven无法下载druid-spring-boot-starter

### ISSUE THREAD

**Issue by yzmdxt** [alibaba/druid#1748]
引入了示例中的<dependency>
          <groupId>com.alibaba</groupId>
          <artifactId>druid-spring-boot-starter</artifactId>
          <version>1.0.29-SNAPSHOT</version>
      </dependency>但是提示无法找到这个包，请问怎么解决？

**Comment by lihengming** [comment]
还没有发布，暂时还不能使用。

**Comment by wenshao** [comment]
预计这个周末回发布新版本，稍等吧

**Comment by DarkRake** [comment]
我发现还没发布呢，坐等发布

**Comment by wenshao** [comment]
最近忙不过来，预计还要延后一个星期

**Comment by wenshao** [comment]
已修复问题，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.0
