### ISSUE TITLE
关于druid-spring-boot-starter

### ISSUE THREAD

**Issue by cuisongliu** [alibaba/druid#1749]
前不久做了一个版本的spring-boot-start ,后来才发现 @lihengming  也做了一个版本，一看没提交到中央仓库我就接着做了。http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22druid-spring-boot-starter%22  最新版本(1.0.31.03 刚刚提交版本 可能有时间延迟)测试可用. 项目主页为 https://github.com/cuisongliu/druid-boot-starter.

**Comment by lihengming** [comment]
建议等待 @wenshao 发布后使用官方版本，相比之下代码会更完善些，比如

- 多数据源的支持
- Spring关联监控的支持

**Comment by cuisongliu** [comment]
嗯嗯，等等看 @wenshao  到底是wiki引入还是说直接在[alibaba](https://github.com/alibaba) 下新建项目.

**Comment by lihengming** [comment]
沟通过，不单独建项目，暂时放在alibaba/druid下。

**Comment by wcwangjianjie** [comment]
大概什么时候会发布官方版

**Comment by cuisongliu** [comment]
@wcwangjianjie  https://github.com/cuisongliu/druid-boot-starter 可以用阿里官网没发布我就给把我的发布了。

```
  <dependency>
   <groupId>com.cuisongliu</groupId>
   <artifactId>druid-spring-boot-starter</artifactId>
   <version>1.0.31.06</version>
 </dependency>
```

**Comment by wenshao** [comment]
已修复问题，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.0
