### ISSUE TITLE
druid数据源配置中的占位符不生效

### ISSUE THREAD

**Issue by krisjin** [alibaba/druid#1752]
> <property name="driverClassName" value="${jdbc_driver}"/>
        <property name="url" value="${jdbc_url}" />
        <property name="username" value="${jdbc_usrename}"/>
        <property name="password" value="${jdbc_password}"/>

使用spring的占位符解析配置，没有生效。

**Comment by lihengming** [comment]
这和druid没关系吧...

**Comment by krisjin** [comment]
其它的占位符都支持的哈

**Comment by krisjin** [comment]
有试过吗@lihengming

**Comment by kuaitou286** [comment]
这个没问题啊  我们项目里边也是这样

![image](https://cloud.githubusercontent.com/assets/10684972/26382675/872ef5ac-4060-11e7-83fb-949f4b86862c.png)


![image](https://cloud.githubusercontent.com/assets/10684972/26382662/721fbf16-4060-11e7-90a6-57c76f40393b.png)

**Comment by krisjin** [comment]
使用spring 4.26版本试试

**Comment by hao0111** [comment]
是没引入配置文件吧？这和druid没关系的，使用都正常
