### ISSUE TITLE
你好 我想问一下我们有master 以及 slave数据源

### ISSUE THREAD

**Issue by lazyfighter** [alibaba/druid#1756]
![qq 20170523142951](https://cloud.githubusercontent.com/assets/17143488/26341063/53fcc5a2-3fc4-11e7-903e-029afd847fcc.png)

我想把这两个数据源的sql合并到一起  但是在 页面上不知道为什么还是显示多个sql

![image](https://cloud.githubusercontent.com/assets/17143488/26341090/6b8c4922-3fc4-11e7-878b-29b779ce487f.png)

求个为大神帮忙解答下

**Comment by wenshao** [comment]
使用jvm参数
```
-Ddruid.useGloalDataSourceStat=true
```
或者配置
```java
druidDataSource.setUseGlobalDataSourceStat(true);
```
