### ISSUE TITLE
datasource close之后，createScheduler线程池还在后台创建连接

### ISSUE THREAD

**Issue by sunjun-csu** [alibaba/druid#1758]
druid初始化时传入了一个全局的createScheduler；但是在close时没有处理线程池里schedule出去的task，在datasource close之后，CreateConnectionTask依然会被调度执行，而CreateConnectionTask的run方法里如果创建连接失败会继续schedule任务去创建。

                try {
                    physicalConnection = createPhysicalConnection();
                } catch (SQLException e) {
                    LOG.error("create connection error, url: " + jdbcUrl, e);

                    errorCount++;
                    
                    if (failFast) {
                        lock.lock();
                        try {
                            notEmpty.signalAll();
                        } finally {
                            lock.unlock();
                        }
                    }

                    if (errorCount > connectionErrorRetryAttempts && timeBetweenConnectErrorMillis > 0) {
                        if (breakAfterAcquireFailure) {
                            lock.lock();
                            try {
                                createTaskCount--;
                            } finally {
                                lock.unlock();
                            }
                            return;
                        }

                        this.errorCount = 0; // reset errorCount
                        createScheduler.schedule(this, timeBetweenConnectErrorMillis, TimeUnit.MILLISECONDS);
                        return;
                    }
                }

**Comment by wenshao** [comment]
已修复问题，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.0
