### ISSUE TITLE
class com.alibaba.druid.sql.ast.statement.SQLCommentStatement not allow

### ISSUE THREAD

**Issue by zzx8170** [alibaba/druid#1759]
druid 版本：1.0.29

sql is:
COMMENT ON COLUMN "TB_CRM_MATERIAL"."INVALID_TIME" IS '生效时间'

调用方法：
OracleStatementParser parser = new OracleStatementParser(sql);
SQLStatement statement = parser.parseStatement();// 分号之后多语句忽略
OracleWallProvider provider = new OracleWallProvider();
provider.getConfig().setCommentAllow(true);
WallCheckResult result1 = provider.check(sql);

执行报：class com.alibaba.druid.sql.ast.statement.SQLCommentStatement not allow

**Comment by zzx8170** [comment]
1.0.27 和 1.0.28 都尝试了，问题一样

**Comment by wenshao** [comment]
已修复问题，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.0

**Comment by zzx8170** [comment]
之前partition bug解决，但comment问题在1.1.0中仍然存在，难道是我用错了吗？


sql is:
COMMENT ON COLUMN "TB_CRM_MATERIAL"."INVALID_TIME" IS '生效时间'

调用方法：
OracleStatementParser parser = new OracleStatementParser(sql);
SQLStatement statement = parser.parseStatement();// 分号之后多语句忽略
OracleWallProvider provider = new OracleWallProvider();
provider.getConfig().setCommentAllow(true);
WallCheckResult result1 = provider.check(sql);

执行报：class com.alibaba.druid.sql.ast.statement.SQLCommentStatement not allow

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.1
问题已经修复，请使用新版本

**Comment by baikeh** [comment]
1.1.14 版本的springboot配置了：`druid.filter.wall.config.comment-allow: true`，依然拦截 comment (mysql)
