### ISSUE TITLE
建表语句的注释无法解析出

### ISSUE THREAD

**Issue by wyzssw** [alibaba/druid#1762]
使用druid 版本1.0.29

比如我有建表语句
```sql
-- table-name-bean-name:some --
CREATE TABLE `some_table` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键'
}
```
我想通过druid的SQLUtils获取 `table-name-bean-name:some` 注释
目的为了做代码生成(表名对应java bean名称)，但是无法获取该表注释，不知道什么方式可以获取

**Comment by wenshao** [comment]
已修复问题，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.0

**Comment by wyzssw** [comment]
👍

**Comment by frank-zx** [comment]
1.1.16版本 解析hive建表语句 也会丢失注释
