### ISSUE TITLE
数据库连接回滚数统计有误?

### ISSUE THREAD

**Issue by chensenlai** [alibaba/druid#1773]
StatFilter.java中public void connection_rollback(FilterChain chain, ConnectionProxy connection) throws SQLException重复调用两次dataSourceStat.getConnectionStat().incrementConnectionRollbackCount();？

**Comment by wenshao** [comment]
是的，这是一个不够，预计在25的版本中会发布修复

**Comment by wenshao** [comment]
已修复问题，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.0
