### ISSUE TITLE
postgresql 语法不支持

### ISSUE THREAD

**Issue by NeedCuriosity** [alibaba/druid#1780]
druid + mybatis + spring
druid版本 1.0.31

插入语句中带有
#{time}::timestamp without time zone,

报异常：
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'tamp without time zone,
           ',expect RPAREN, actual IDENTIFIER without

实际数据插入成功

**Comment by wenshao** [comment]
能提供完整的SQL语句么？

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.1
问题已经修复，请使用新版本
