### ISSUE TITLE
druid-spring-boot-starter中无法用DruidDataSourceBuilder创建DruidDataSource

### ISSUE THREAD

**Issue by qq592304796** [alibaba/druid#1783]
DruidDataSourceBuilder中的properties并没有注入相关的配置，一直为空

**Comment by lihengming** [comment]
贴一下代码，配置我帮你看看。

**Comment by qq592304796** [comment]
以官方的DemoApplication为例
修改配置 
![application properties](https://user-images.githubusercontent.com/26601421/27226128-11cc5f2a-52d0-11e7-8cb1-90d976fb205b.png)
启动时自动装配DruidDataSourceAutoConfigure

![empty](https://user-images.githubusercontent.com/26601421/27226300-e56c03ee-52d0-11e7-899b-932e399729e6.png)
properties是空的

**Comment by lihengming** [comment]
走到这一行还没进行绑定操作，代码往下走才会绑定，有[单元测试](https://github.com/alibaba/druid/blob/master/druid-spring-boot-starter/src/test/java/com/alibaba/druid/spring/boot/DruidDataSourceTestCase.java)保证的。JDBC基础部分你也可以使用默认的前缀配置，如下。

- spring.datasource.url=
- spring.datasource.username=
- spring.datasource.password=
- spring.datasource.driver-class-name=

**Comment by lihengming** [comment]
走到这一行还没进行绑定操作，代码往下走才会绑定，有[单元测试](https://github.com/alibaba/druid/blob/master/druid-spring-boot-starter/src/test/java/com/alibaba/druid/spring/boot/DruidDataSourceTestCase.java)保证的。JDBC基础部分你也可以使用默认的前缀配置，如下。

- spring.datasource.url=
- spring.datasource.username=
- spring.datasource.password=
- spring.datasource.driver-class-name=

**Comment by wenshao** [comment]
已修复问题，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.0

**Comment by ddatsh** [comment]
1.1.0也还是空的啊？单元测试里同样是空啊
