### ISSUE TITLE
druid-spring-boot-starter中的WebStatFilter配置读取不到

### ISSUE THREAD

**Issue by qq592304796** [alibaba/druid#1785]
![default](https://user-images.githubusercontent.com/26601421/27267397-a0508602-54da-11e7-90a2-b5b1be707544.png)
DruidStatProperties中的statFilter属性名称不对应读取不到

![2](https://user-images.githubusercontent.com/26601421/27267406-b5690a78-54da-11e7-8a83-f7e9a3303d37.png)
![3](https://user-images.githubusercontent.com/26601421/27267407-b9d42e08-54da-11e7-9a63-517f9bfd0c0e.png)
README.md和DruidWebStatFilterConfiguration又是WebStatFilter
不知道这算不算bug

**Comment by lihengming** [comment]
确实是BUG，已PR。

**Comment by wenshao** [comment]
已修复问题，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.0

**Comment by wenshao** [comment]
已修复问题，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.0
