### ISSUE TITLE
druid-spring-boot-starter jar包下载不下来啊。

### ISSUE THREAD

**Issue by 472827074** [alibaba/druid#1787]
<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
            <version>1.0.29-SNAPSHOT</version>
        </dependency>
加入项目pom中，jar下不下来。请问有人遇到没？

**Comment by lihengming** [comment]
还没发布，可以先clone项目本地install使用。

**Comment by wenshao** [comment]
已修复问题，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.0
