### ISSUE TITLE
postgres expect RPAREN, actual RECURSIVE

### ISSUE THREAD

**Issue by DevilMayCrySamsara** [alibaba/druid#1789]
postgres  有RECURSIVE，递归查询，但是貌似druid不支持？

**Comment by DevilMayCrySamsara** [comment]
delete from itsm_system_role_menu where menu_id in(
        with RECURSIVE menuTemp(menu_id,parent_id)
        as (
        select menu_id ,parent_id from itsm_system_menu where menu_id in
         (  
            'M00006'
         ) 
        union all
        select a.menu_id ,a.parent_id from itsm_system_menu as a  INNER JOIN menuTemp b on a.parent_id=b.menu_id
        )
        select menu_id from menuTemp);

**Comment by wenshao** [comment]
已修复问题，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.0
