### ISSUE TITLE
建议依赖Web环境的配置，添加 @ConditionalOnWebApplication 注解

### ISSUE THREAD

**Issue by taolive** [alibaba/druid#1791]
建议依赖Web环境的配置，添加 @ConditionalOnWebApplication 注解
如：DruidStatViewServletConfiguration、DruidWebStatFilterConfiguration 2个配置类，要不然非Web环境会抛异常

**Comment by wenshao** [comment]
@lihengming

**Comment by wenshao** [comment]
已修复问题，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.0
