### ISSUE TITLE
druid不支持ddl语句

### ISSUE THREAD

**Issue by lanmolsz** [alibaba/druid#1794]
这个问题其实已经过了很久了，当时看到的原因是：因为druid号称是为监控而生的数据库，因此它会在执行sql的时候先对sql语句做语法解析，但是语法解析并不支持ddl语句，会导致执行的时候报错。
其实也并非一定要实现解析ddl的逻辑，这样的sql执行也和监控并没有什么关系，因此你们也可以直接忽略这种语句的解析即可。

**Comment by wenshao** [comment]
遇到什么ddl并不支持的？能反馈给我么？

**Comment by lanmolsz** [comment]
好的，我测试一下。给一个例子你们看看

**Comment by lanmolsz** [comment]
不好意思，今天才验证这个问题。
今天测试了运行ddl语句，结果并没有任何错误。
我记得当时报错的提示信息确实是告诉我无法正确的解析sql，不过由于当时项目时间比较紧，所以就直接换了一个数据库连接吃，并没有深入的去找更具体的原因，不过现在既然并没有重现这个问题，那就不存在无法解析这个问题了。我先关掉这个issue！
