### ISSUE TITLE
Spring boot  autoconfig下能否优化下setMinEvictableIdleTimeMillis与setMaxEvictableIdleTimeMillis顺序问题

### ISSUE THREAD

**Issue by Plen-wang** [alibaba/druid#1796]
在springboot下的@ConfigurationProperties自动属性注入的时候，由于spring框架自动注入bean属性数据，导致会优先设置setMaxEvictableIdleTimeMillis，此时还未进行 setMinEvictableIdleTimeMillis属性的设置，但是setMinEvictableIdleTimeMillis的默认值会成为setMaxEvictableIdleTimeMillis判断的值。导致检查失败。

**Comment by lihengming** [comment]
Spring Boot 在绑定属性的时候没有按照properties内配置项的顺序，貌似是按ascii码来排的序，建议maxEvictableIdleTimeMillis先自己通过Environment来配置，我看看Spring Boot源码，能不能优化。

**Comment by Plen-wang** [comment]
好的，非常感谢。

**Comment by lihengming** [comment]
@Plen-wang 下个版本会解决这个问题。

**Comment by Plen-wang** [comment]
辛苦了。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.1
问题已经修复，请使用新版本

**Comment by drtrang** [comment]
@Plen-wang 

问题的原因在这 https://github.com/drtrang/druid-spring-boot/issues/3#issuecomment-316932578
你应该是用了 `application.properties` 而不是 `application.yml`，YAML 格式会按照配置顺序赋值

**Comment by Plen-wang** [comment]
@drtrang 
嗯嗯，是的。用的是springboot 默认的properties属性文件配置的。

感谢，不知道YAML是根据顺序配置。用YAML是不是注入配置没有那么方便。

**Comment by Plen-wang** [comment]
@drtrang 
仔细看了下[drtrang/druid-spring-boot#3 (comment)](url)
明白原因了，谢谢大咖。

**Comment by ichavin** [comment]
1.1.13版本

**Comment by luzhaoren** [comment]
> 
> 
> druid-spring-boot-starter 1.1.13版本还存在此问题

确实仍然存在此问题

**Comment by lihengming** [comment]
@luzhaoren  在解决了，这个问题比较棘手，Spring 读取配置并不是按顺序读的，下个版本修复。

**Comment by wad12302** [comment]
2.0.x 还是存在

**Comment by bastYYJ** [comment]
1.1.21还是没修复

**Comment by nicolaslonely** [comment]
没有修复 ，如果使用nacos的话 很容易复现

**Comment by littlehui** [comment]
1.1.16版本还是如此
