### ISSUE TITLE
distinct多列的时候查询数量BUG

### ISSUE THREAD

**Issue by guixincui** [alibaba/druid#1803]
https://github.com/alibaba/druid/issues/1715

如果select distinct col1,col2... from tb ，这种情况count还是有问题。
即 queryBlock.getSelectList().size()大于1的情况。

if (option == SQLSetQuantifier.DISTINCT && queryBlock.getSelectList().size() == 1) {
	SQLSelectItem firstItem = queryBlock.getSelectList().get(0);
	SQLAggregateExpr exp = new SQLAggregateExpr("COUNT", SQLAggregateOption.DISTINCT);
	exp.addArgument(firstItem.getExpr());
	firstItem.setExpr(exp);
	queryBlock.setDistionOption(0);
    }

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.1
问题已经修复，请使用新版本
