### ISSUE TITLE
1.1.0中bug 1759没有修复啊

### ISSUE THREAD

**Issue by zzx8170** [alibaba/druid#1807]
之前提的partition bug解决，但comment被错误阻止问题在1.1.0中仍然存在，下面sql仍然报错，温少麻烦再看看，难道是我用错了吗？

sql is:
COMMENT ON COLUMN "TB_CRM_MATERIAL"."INVALID_TIME" IS '生效时间'

调用方法：
OracleStatementParser parser = new OracleStatementParser(sql);
SQLStatement statement = parser.parseStatement();// 分号之后多语句忽略
OracleWallProvider provider = new OracleWallProvider();
provider.getConfig().setCommentAllow(true);
WallCheckResult result1 = provider.check(sql);

执行报：class com.alibaba.druid.sql.ast.statement.SQLCommentStatement not allow

**Comment by zzx8170** [comment]
请温少优先解决一下，这个功能我们急等着用

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.1
问题已经修复，请使用新版本
