### ISSUE TITLE
Properties Configuration

### ISSUE THREAD

**Issue by ddknight** [alibaba/druid#1810]
I found source code in _com.alibaba.druid.pool.DruidDataSource_ that it can configed by property files in classpath.
such as **druid.url,druid.username,druid.password,druid.driverClassName** and so on.
I use spring framework's _org.springframework.beans.factory.config.PropertyPlaceholderConfigurer_ to read properties above in my project's classpath.
but datasource init failed.
How to fix it?

**Comment by ddknight** [comment]
There is some code in my project.
1.applicationContext.xml
`<bean class="org.springframework.beans.factory.config.PropertyPlaceholderConfigurer">`
`     <property name="location" value="classpath:app.properties"></property>`
`</bean>`
`<bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource" init-method="init" destroy-method="close">`
`    <property name="name" value="Datasource-APP"></property>`
`    <property name="filters" value="config"></property>`
`    <property name="connectionProperties" value="config.decrypt=true;config.decrypt.key=${druid.public.key}"></property>`
`</bean>`


2.app.properties
`druid.url=jdbc:oracle:thin:@localhost:1521/oseb`
`druid.username=ddknight`
`#Database Password`
`druid.password=YZLnPZy56Q0iPgje1fC90dQ5YpiOBZuNj0TRsyIbCcOjEsiJF4cnuT74Jl/JydqKAPPltJYpVIXXWsiasYHUwQ==`
`druid.driverClassName=oracle.jdbc.OracleDriver`
`#Database Public Key`
`druid.public.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAILKcDJonimZnHnQzjDBlmyMRp/b2o0KUKNxEhVb5G/5EzfvRpW/n+xmfljtWXo9TKaF7ofV4aa4zfkUh5wA3scCAwEAAQ==`

**Comment by chinaHewei** [comment]
I think you configured wrong, you can look at the document. Here is the [link](https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE).

Or you can configure it like this:

```XML
    <bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource"
          init-method="init" destroy-method="close">
        <property name="connectionProperties" value="config.decrypt=true;config.decrypt.key=${druid.public.key}"/>
        <property name="url" value="${druid.url}"/>
        <property name="password" value="${druid.password}"/>
        <property name="username" value="${druid.username}"/>
        <property name="driverClassName" value="${druid.driverClassName}"/>
    </bean>
```

**Comment by digitalsonic** [comment]
@ddknight please try to modify the `dataSource` bean like this, maybe it works for you:

```xml
<bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource" init-method="init" destroy-method="close">
    <property name="name" value="Datasource-APP"></property>
    <property name="url" value="${druid.url}"></property>
    <property name="username" value="${druid.username}"></property>
    <property name="password" value="${druid.password}"></property>
    <property name="filters" value="config"></property>

    <property name="connectProperties">
        <props>
            <prop key="config.decrypt">true</prop>
            <prop key="config.decrypt.key">${druid.public.key}</prop>
        </props>
    </property>
</bean>
```
Druid can't use the properties in Spring's Environment automaticaly, you should specify the placeholder by yourself.

**Comment by mercyblitz** [comment]
@ddknight
Is there some bean implementing  BeanFactoryPostProcessor , and then invoke ConfigurableListableBeanFactory#getBean method under postProcessBeanFactory method ？

If present , please remove those code, thus it's too early initializing bean to resolve placeholder from Environment.

**Comment by ddknight** [comment]
OK,i know what to do.I just think druid should be work like that,so i got that mistake.Thank you all.
