### ISSUE TITLE
关于对Druid Spring Boot Starter V1.1.0代码的优化

### ISSUE THREAD

**Issue by lihengming** [alibaba/druid#1813]
在Druid Spring Boot Starter 第一个版本发布后，收到了一些开发朋友们的建议与反馈，主要问题如下：
1. DruidDataSourceBuilder 的问题
```java
    public DruidDataSource build() {
        DruidDataSource dataSource = new DruidDataSource();
        maybeGetDriverClassName();
        bind(dataSource);
        return dataSource;
    }
    //use spring boot relaxed binding by reflection config druid . detail see Spring Boot Reference Relaxed binding section.
    private void bind(DruidDataSource result) {
        MutablePropertyValues properties = new MutablePropertyValues(this.properties);
        new RelaxedDataBinder(result)
                .withAlias("url", "jdbcUrl")
                .withAlias("username", "user")
                .bind(properties);
    }
```
上面这些代码其实并没有工作，真正工作的是```@ConfigurationProperties```注解的处理类```ConfigurationPropertiesBindingPostProcessor```、```PropertiesConfigurationFactory```，也就是说，将上述代码修改为下面这样

```
public DruidDataSource build() {
     return new DruidDataSource();
}
```
Spring Boot依旧可以根据配置文件帮你配置Druid，只要你在调用```DruidDataSourceBuilder.build()```的方法上面添加的有```@Bean```、```@ConfigurationProperties``` 注解。

2. 一些朋友希望IDE可以对这些配置文件进行提示，像下面这样
![](https://raw.githubusercontent.com/lihengming/shared-files/master/github-images/druid-ide.png)

3. Issue #1796  的问题
这是因为Spring Boot 使用一种[Relaxed binding](http://docs.spring.io/spring-boot/docs/1.5.5.BUILD-SNAPSHOT/reference/htmlsingle/#boot-features-external-config-relaxed-binding)的属性绑定机制进行配置文件与Bean属性的绑定（其实就是通过反射set），在绑定的时候并不会按你配置文件的顺序进行绑定，进而导致该问题的发生。

------------------

解决上面这些问题很简单，就是放弃使用```Relaxed binding```这种动态绑定的方式，创建```DruidDataSourceProperties``` 逐个设置，代码写起来有点麻烦，不过这是最直接有效的方式。但是放弃使用```Relaxed binding```会给创建多数据源造成麻烦，所以在```DruidDataSourceBuilder```提供了一个新的方法```public DruidDataSource build(Environment env, String prefix)```用来创建数据源，可以自己指定配置前缀，使用起来就像下面这样，不用使用```@ConfigurationProperties```注解。
```java
    @Bean
    @Primary
    public DataSource dataSourceOne(Environment env){
        return DruidDataSourceBuilder
                .create()
                .build(env, "spring.datasource.druid.one.");
    }
    @Bean
    public DataSource dataSourceTwo(Environment env){
        return DruidDataSourceBuilder
                .create()
                .build(env, "spring.datasource.druid.two.");
    }
```
Spring Boot 2.0也废弃了```RelaxedDataBinder```、```MutablePropertyValues ```类，这样也顺带兼容了Spring Boot 2.0。

--------------------

最近比较忙，没来得及优化，今天下午花了点时间优化了一下，commit comment太短了写不下，干脆写到Issue上了，欢迎大家preview代码，发现代码问题或者有什么好建议可以提出来或PR，这些优化会在下个版本发布，到时文档也会更新。当然，这些对Druid Spring Boot Starter 1.1.0的使用没有影响。

**Comment by lihengming** [comment]
@wenshao

**Comment by hao0111** [comment]
你好，发现多数据源通过Relaxed binding这种动态绑定的方式，DruidDataSourceBuilder类里的properties map对象实际并不会将对应的前缀属性set到map对象里，后来显示的使用@ConfigurationProperties pojo类映射（上过版本的）

**Comment by lihengming** [comment]
@hao0111 啥意思？

**Comment by 15036900300** [comment]
发现了一个问题，就是当前maven库中的druid-spring-boot-starter版本好像和git里面最新代码版本不一致，造成在application.properties中配置druid的属性不起作用，希望给解决一下

**Comment by lihengming** [comment]
@15036900300 代码肯定不一样啊，版本号都不一样… 那是1.1.0，这是之后加的代码…你Debug过确定不起作用或者去监控页面确定过配置不生效么…去看看Issue #1817 吧，就不重复解释了，本文也有解释请仔细看看再说，谢谢。

**Comment by lihengming** [comment]
想确认Druid Spring Boot Starter 1.1.0连接池配置是否生效请在任意一个Bean中注入一个DataSource，Debug查看，或者在监控页面查看，不要在DruidDataSourceBuilder.build()方法里里看一下就认为配置不生效，因为Spring Boot是在Bean创建时才对属性进行的动态绑定，上面我对此也有过解释，如果真的有问题的话，单元测试也不会通过的。

**Comment by hao0111** [comment]
@lihengming ，你提到的第一点 （DruidDataSourceBuilder 的问题），对方法的bean 添加@configurationproperties注解，对应的DruidDataSourceBuilder类里的properties map对象属性并没有被spring boot 自动注入application.properties对应的前缀值
‘MutablePropertyValues properties = new MutablePropertyValues(this.properties);’

**Comment by lihengming** [comment]
@hao0111 上面已经说过了，这些代码其实并没有工作，真正工作的是@ConfigurationProperties注解的处理类ConfigurationPropertiesBindingPostProcessor、PropertiesConfigurationFactory 在Bean创建时进行绑定，你可以Debug跟一下Spring Boot的这两个类，这次优化已经删除了这些代码，不必纠结于此。

**Comment by haoxuexiaoyao** [comment]
请问配置文件提示，gradle创建的项目下面添加了
`compile group: 'org.springframework.boot', name: 'spring-boot-configuration-processor', version: ‘1.5.4.RELEASE’`
这个依赖 还是没有提示 请问怎么处理呢 谢谢

**Comment by lihengming** [comment]
@haoxuexiaoyao 等下个版本发布就有了，不是说让你添加spring-boot-configuration-processor依赖，Druid Spring Boot Starter 的pom.xml里包含的有，我只是解释下IDE提示依靠的这个和ConfigurationProperties注解。

**Comment by haoxuexiaoyao** [comment]
@lihengming 明白了 谢谢

**Comment by 15036900300** [comment]
@lihengming 你好，我是通过去监控页面查看对应的配置项，发现是不起作用的，所以一直搞不明白了

**Comment by lihengming** [comment]
@15036900300 将配置和监控页实际显示的截个图我看看

**Comment by 15036900300** [comment]
@lihengming 请问你qq多少，或者邮箱多少，我把截图发给你

**Comment by lihengming** [comment]
@15036900300  89921218

**Comment by lihengming** [comment]
@15036900300  

1.1.0 Maven依赖
```
<dependency>
      <groupId>com.alibaba</groupId>
      <artifactId>druid-spring-boot-starter</artifactId>
      <version>1.1.0</version>
</dependency>
```
配置项
```
spring.datasource.druid.initialSize=12
spring.datasource.druid.maxActive=34
```
监控页面
![](http://chuantu.biz/t5/131/1499663990x1780971138.png)

**Comment by 15036900300** [comment]
@lihengming 我的查看你上图所示的地方，链接数也改变了，我配置了获取链接超时时间，但是我看监控里面好像没有修改

**Comment by wenshao** [comment]
请使用新版版本 https://github.com/alibaba/druid/releases/tag/1.1.1

**Comment by YGLTZX-YE** [comment]
@wenshao 有没有一个能用的DEMO，我配置的一直是404

**Comment by lihengming** [comment]
@YGLTZX-YE 文档下面写的有 DemoApplication

**Comment by jinzhaopo** [comment]
Description:

Binding to target [Bindable@3796ca50 type = ?, value = 'none', annotations = array<Annotation>[[empty]]] failed:

    Reason: Failed to bind properties under 'spring.datasource.druid.connection.connection-holder.data-source.connection-init-sqls[0]' to ?

Action:

Update your application's configuration
 | [LoggingFailureAnalysisReporter.java:42]

Process finished with exit code 1
项目启动的时候有时候报错，有时候不报错
[E2BC3D23-EE3A-48b1-9967-C4562F6A5400.txt](https://github.com/alibaba/druid/files/1909970/E2BC3D23-EE3A-48b1-9967-C4562F6A5400.txt)

**Comment by javase** [comment]
使用自定义的ApplicationListener加载Spring配置时出错，可以参考一下这个博客：
[https://blog.csdn.net/limenghua9112/article/details/81634774](url)
