### ISSUE TITLE
1.1.0中sql加分号解析的问题

### ISSUE THREAD

**Issue by zzx8170** [alibaba/druid#1815]
新版本中按照如下方式解析后的sql全部无法执行：
OracleStatementParser parser=new OracleStatementParser(allSql);
	List<SQLStatement> stmtList=parser.parseStatementList();
	for(SQLStatement stmt : stmtList) {
              st = connOracle.createStatement();
	      System.out.println(stmt.toString());
              st.execute(stmt.toString());
}

sql输出的文本正常，但执行全部报ORA-00911: 无效字符，发现是sql文本最后如果加‘；’则会报错，在之前版本加不加';'都是可以正常解析和执行的，希望恢复到旧版本的功能，向下兼容！

**Comment by wenshao** [comment]
这个是什么场景？

**Comment by zzx8170** [comment]
之前场景是用上面语句解析多条sql，比如：
select 1 from t1
select 2 from t2
select 3
from t3
多语句之间即使不加‘；’，只是单纯的换行都可以正常解析，sql中间有换行也能智能识别，非常神奇；新版本中则解析多行语句直接报错，每行结尾必须加‘；’才可以解析，希望能恢复以前版本。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/blob/f2708bb208a8e4d2139b2c6a9ca71ec632483d8a/src/test/java/com/alibaba/druid/demo/sql/Demo_for_issue_1815.java

1.1.1版本已经发布，看上面这里例子的是否满足你的需求

**Comment by zzx8170** [comment]
这个选项好用，只是源码没有太看懂，温少能简单介绍一下这个选项的功能吗？
SQLASTOutputVisitor.defaultPrintStatementAfterSemi = false;

**Comment by wenshao** [comment]
这个选项的作用是：是否打印语句后面的分号
