### ISSUE TITLE
最新发布的spring boot 集成druid 的jar什么时候在maven上面进行更新呢？

### ISSUE THREAD

**Issue by zhangmeichun** [alibaba/druid#1817]
最近在研究spring boot 集成 druid 发现使用jar之后数据库配置没有被读取，陷入无法自拔中。。。
问题描述：
看源码发现application 的system.getProperties()没有读取到applicaiton.properties的属性，而且DataSource里面匹配的key也不是定义的spring.dataSource.druid为前缀的。

直到刚刚看到昨天更新了最新代码。。。欲哭无泪😂那么什么时候能更新下maven呢

**Comment by lihengming** [comment]
不影响使用，在创建Bean的时候才会绑定，QQ已沟通。

**Comment by lihengming** [comment]
可以看看 issue #1788

**Comment by zhangmeichun** [comment]
非常感谢。。现在的我要关闭这个issue了
