### ISSUE TITLE
druid --not support oracle driver 1.0

### ISSUE THREAD

**Issue by fqtyfz** [alibaba/druid#182]
程序启动的时候报这个异常
not support oracle driver 1.0
不知道是什么原因！！

**Comment by icexyli** [comment]
# durid 当驱动为oracle的时候判断版本号
if (driver.getMajorVersion() < 10) {
                throw new SQLException("not support oracle driver " + driver.getMajorVersion() + "."
                                       + driver.getMinorVersion());
            }
# 但是oracle最新驱动返回版本号的方法是常量1
public int getMajorVersion() {
        return 1;
    }

**Comment by Guozq2014** [comment]
> # durid 当驱动为oracle的时候判断版本号
> if (driver.getMajorVersion() < 10) {
> throw new SQLException("not support oracle driver " + driver.getMajorVersion() + "."
> + driver.getMinorVersion());
> }
> 
> # 但是oracle最新驱动返回版本号的方法是常量1
> public int getMajorVersion() {
> return 1;
> }
用这个jar包，返回版本号为1：
		<dependency>
			<groupId>com.oracle</groupId>
			<artifactId>ojdbc14</artifactId>
			<version>1.0</version>
		</dependency>
