### ISSUE TITLE
程序连接没问题，部署到tomcat上就报Communications link failure

### ISSUE THREAD

**Issue by yangqingmang** [alibaba/druid#1821]
我用的是idea，当使用jetty插件启动的时候，就可以连上mysql，可以如果打包后部署到tomcat上，启动tomcat就回报：
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
……
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
……

请问这是什么原因？

**Comment by zhaoyunxing92** [comment]
@yangqingmang 你的问题解决了吗

**Comment by yangqingmang** [comment]
@zhaoyunxing92 之前换了个版本的数据库好了，但是现在公司某些原因又把数据库换回去了，又不行了

**Comment by renpengben** [comment]
解决了么？
