### ISSUE TITLE
druid-springboot-starter 1.1.1 still use druid 1.1.0

### ISSUE THREAD

**Issue by deae** [alibaba/druid#1828]
Hi
 Today I change the druid-springboot-starter from 1.1.0 -> 1.1.0, I find the dependency of druid still 1.1.0.
I think this maybe a mistake.

below is the starter pom file content.
<properties>
<druid.version>1.1.0</druid.version>
<spring-boot.version>1.5.3.RELEASE</spring-boot.version>
</properties>

**Comment by lihengming** [comment]
@wenshao

**Comment by lihengming** [comment]
@deae  Yes, it's a mistake, can use druid 1.1.1 dependency cover it,  next version will fix it.
```
<dependency>
	<groupId>com.alibaba</groupId>
	<artifactId>druid</artifactId>
	<version>1.1.1</version>
</dependency>
```

**Comment by wenshao** [comment]
问题修复，请用新版本
https://github.com/alibaba/druid/releases/tag/1.1.2
