### ISSUE TITLE
提供另外一个 Druid Spring Boot Starter

### ISSUE THREAD

**Issue by drtrang** [alibaba/druid#1829]
[Druid Spring Boot Starter](https://github.com/drtrang/druid-spring-boot)，支持开箱即用，提供完整的自动提示：https://github.com/drtrang/druid-spring-boot

**Comment by lihengming** [comment]
@drtrang 粗略看了下源码没看出来哪点更好用
1. 没有任何的单元测试
2. 不支持多数据源配置
3. 不支持Spring AOP配置
4. IDE自动提示官方同样完整覆盖

**Comment by drtrang** [comment]
@lihengming 回应之前的几个问题
1. [druid-spring-boot-samples](https://github.com/drtrang/druid-spring-boot/tree/master/druid-spring-boot-samples) 中包含单元测试，目前覆盖率 91%
2. 1.0.2 版本支持[多数据源](https://github.com/drtrang/druid-spring-boot/blob/master/docs/DruidMultiDataSource.md)，并且支持继承公共参数
3. 支持正则匹配
4. 你确定完整覆盖？我想配置 `asyncCloseConnectionEnable` 参数要怎么做？手动去声明 Bean？那还要 Starter 干吗，你的版本里只有 [DruidDataSourceProperties](https://github.com/alibaba/druid/blob/master/druid-spring-boot-starter/src/main/java/com/alibaba/druid/spring/boot/autoconfigure/DruidDataSourceProperties.java) 中已经定义的属性才支持自动配置。

之前提的 Issue，Druid 基本的 Filter 都不支持自动配置 https://github.com/alibaba/druid/issues/1823

**Comment by lihengming** [comment]
@drtrang 
不错，看来经过几天代码完善，你解决了上述的问题，不过我依然不认可你所说的比官方更好用的说法。

关于你说的“你的版本里只有 DruidDataSourceProperties 中已经定义的属性才支持自动配置"，这是因为使用Spring Boot ```ConfigurationPropertiesBindingPostProcessor``` 动态绑定会导致 #1796 问题的发生，不得不这样做，我想你的代码也会出现这个问题。

在放弃动态绑定后，我只对 [DruidDataSource配置属性列表](https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8) 内的参数提供配置支持，如果你需要```asyncCloseConnectionEnable```等”小众“参数配置的支持，很简单，提Issue我来完善或者直接提个PR即可，这都是小问题，举手之劳。```Filter```也一样，我不认为 #1800 的配置方式比配置文件要麻烦。

Druid Spring Boot Starter 本就是一个非常简单的项目，我不太理解为什么要去重复发明轮子，而不是一起维护、完善。

**Comment by drtrang** [comment]
最初的想法是提PR，但是代码改动太大，并且风格不一样。提供两个选择不是更好吗？用户可以自行选择更合适的。

技术本来就是不断的在造轮子，在造轮子的过程中，才会不断的突破自己，而不是拿来主义就好，同时也会更加符合自己的需求。

我只是觉得官方出品的东西，应该尽可能的覆盖更多场景，毕竟 Starter 的目的就是为了自动配置，如果需要手动配置才能完成，貌似和直接使用 Druid 没什么差别。

另，标题已改，之前语言欠妥。

**Comment by lxholding** [comment]
个人认为简单场景下有官方版本就好了，有超出此范围的需求肯定会自己去写自定义配置，根本用不上
