### ISSUE TITLE
配置 druid数据库后 inited这里就卡了

### ISSUE THREAD

**Issue by zhaoyunxing92** [alibaba/druid#1835]
![image](https://user-images.githubusercontent.com/18088210/28262250-ee12a65e-6b14-11e7-8a73-2e13c008ab20.png)
大神麻烦看下@wenshao
注：我在Tomcat7里面是不ok的但是在tomcat8里面就可以了

**Comment by lihengming** [comment]
可以贴下Spring配置

**Comment by zhaoyunxing92** [comment]
问题已经解决了，是死锁了，我们最后调整了代码@lihengming，感谢你的回答
