### ISSUE TITLE
请教一个问题，druid是如何保证一个线程如果多次获取的connection是同一个的？

### ISSUE THREAD

**Issue by slowlizard** [alibaba/druid#1836]
如果不是同一个Connection的话，事务可能会出问题。

**Comment by jounzhang** [comment]
我猜应该是ThreadLocal吧

**Comment by lynchlee** [comment]
你指的多次获取是什么意思呢？是指同一个线程中多次调用DruidDataSource#getConnection()?
如果是上面这个意思的话，Druid自身是保证不了这个事情的吧，要你自己取到一个连接然后保存起来重用吧．



`package cn.kenshinn.cube.app.config;

import com.alibaba.druid.pool.DruidDataSource;
import com.alibaba.druid.pool.DruidPooledConnection;

import java.sql.SQLException;

/**
 * Created by kenshinn on 17-7-28.
 */
public class Test {

    public static void main(String[] args) {
        DruidDataSource druidDataSource = new Test().syncerDataSource();
        try {
            DruidPooledConnection connection = druidDataSource.getConnection();
            DruidPooledConnection connection2 = druidDataSource.getConnection();
            DruidPooledConnection connection3 = druidDataSource.getConnection();

            System.out.println("foo");
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }


    private DruidDataSource syncerDataSource() {
        DruidDataSource dataSource = new DruidDataSource();

        try {
            dataSourceProperties(dataSource);
        } catch (Exception e){
            e.printStackTrace();
        }

        return dataSource;
    }


    private void dataSourceProperties(DruidDataSource dataSource) {
        String driverClass = "com.mysql.jdbc.Driver";
        dataSource.setDriverClassName(driverClass);

        String jdbcUrl = "jdbc:mysql://host:3306/test_db?characterEncoding=UTF-8&autoReconnect=true&useSSL=false";
        dataSource.setUrl(jdbcUrl);

        String username = "user";
        dataSource.setUsername(username);

        String password = "key";
        dataSource.setPassword(password);

        Integer initialPoolSize = 1;
        dataSource.setInitialSize(initialPoolSize);

        Integer connMinIdle = 1;
        dataSource.setMinIdle(connMinIdle);

        Integer connMaxActive = 150;
        dataSource.setMaxActive(connMaxActive);

        Integer maxWaitMillis = 60000;
        dataSource.setMaxWait(maxWaitMillis);

        Integer timeBetweenEvictionRunsMillis = 60000;
        dataSource.setTimeBetweenEvictionRunsMillis(timeBetweenEvictionRunsMillis);

        Integer minEvictableIdleTimeMillis = 300000;
        dataSource.setMinEvictableIdleTimeMillis(minEvictableIdleTimeMillis);

        dataSource.setValidationQuery("SELECT 1");
        dataSource.setTestOnBorrow(false);
        dataSource.setTestWhileIdle(true);
        dataSource.setTestOnReturn(false);

        dataSource.setPoolPreparedStatements(true);
        dataSource.setMaxPoolPreparedStatementPerConnectionSize(20);
        try {
            dataSource.setFilters("stat");
        } catch (SQLException e) {
            e.printStackTrace();
        }

        // always login
        dataSource.setLoginTimeout(0);

        dataSource.setRemoveAbandoned(true);
        dataSource.setRemoveAbandonedTimeout(30);
    }

}
`

**Comment by slowlizard** [comment]
是的。Druid 保证不了。Spring使用了 ThreadLocal来保证，不是由连接池来保证
