### ISSUE TITLE
merge sql error dbType postgresql

### ISSUE THREAD

**Issue by gongdear** [alibaba/druid#1841]
{com.alibaba.druid.filter.stat.StatFilter:148}-merge sql error, dbType postgresql, 
sql : select gid, kind, mapid, poi_id, telephone, admincode, x, y, zipcode, name, address, street, number,geom from public.v_poi order by public.v_poi.geom    <->    st_point(?,?) limit 1

developer environment:spring4.2.5.RELEASE mybatis3.3.1 druid1.1.1 redis3.0.5;
redis is used for cache;
but both result and cache are correct :)

**Comment by gongdear** [comment]
I try to repleace '<->' to 'st_distance' then console doesn't show any error , druid probably unsupported '<->'

**Comment by wenshao** [comment]
问题修复，请用新版本
https://github.com/alibaba/druid/releases/tag/1.1.2
