### ISSUE TITLE
可以使用其他数据源吗？

### ISSUE THREAD

**Issue by newEchartster** [alibaba/druid#1843]
可以不使用DruidDataSource作为数据源吗？
有没有使用其他DataSource的接口呢？

**Comment by wenshao** [comment]
如果你不想使用DruidDataSource，我为啥要给你做支持呢？

**Comment by newEchartster** [comment]
用肯定是用的，我的意思是在spring配置的是自己的datasource,但是使用时归根结底还是用的DruidDataSource

**Comment by newEchartster** [comment]
谢谢，我知道怎么弄了！
