### ISSUE TITLE
合并sql语句统计问题

### ISSUE THREAD

**Issue by qq592304796** [alibaba/druid#1844]
![originalsql](https://user-images.githubusercontent.com/26601421/28412429-c70b0e48-6d76-11e7-9cf3-81e83ba891ff.png)

![sql](https://user-images.githubusercontent.com/26601421/28412122-c6d16900-6d75-11e7-9dca-fddca2bfbe6c.png)

![fullsql](https://user-images.githubusercontent.com/26601421/28412512-037be08c-6d77-11e7-8089-fcf53002bf83.png)

![viewsql](https://user-images.githubusercontent.com/26601421/28412517-08260d06-6d77-11e7-9e53-b070718bd4a7.png)

记录的sql括号被去掉了

感觉对复杂的sql合并支持的不是很友好?不知道这算不算正常的情况

**Comment by lihengming** [comment]
这SQL确实蛮复杂 :-)，解析起来确实很费劲

**Comment by qq592304796** [comment]
这是算正常情况吗?
因为想要合并sql的功能,但是会影响到一些复杂的sql,很是纠结呀

**Comment by lihengming** [comment]
我怎么看着括号还在啊

![](https://user-images.githubusercontent.com/26601421/28412517-08260d06-6d77-11e7-9e53-b070718bd4a7.png)

**Comment by wenshao** [comment]
用新版本吧，并不会去掉括号了，比如1.1.2
