### ISSUE TITLE
你希望Druid Spring Boot Stater在原有基础上增加哪些Druid配置属性的支持？

### ISSUE THREAD

**Issue by lihengming** [alibaba/druid#1845]
```
spring.datasource.druid.url= # 或spring.datasource.url= 
spring.datasource.druid.username= # 或spring.datasource.username=
spring.datasource.druid.password= # 或spring.datasource.password=
spring.datasource.druid.driver-class-name= #或 spring.datasource.driver-class-name=
spring.datasource.druid.initial-size=
spring.datasource.druid.max-active=
spring.datasource.druid.min-idle=
spring.datasource.druid.max-wait=
spring.datasource.druid.pool-prepared-statements=
spring.datasource.druid.max-pool-prepared-statement-per-connection-size= 
spring.datasource.druid.max-open-prepared-statements=
spring.datasource.druid.validation-query=
spring.datasource.druid.validation-query-timeout=
spring.datasource.druid.test-on-borrow=
spring.datasource.druid.test-on-return=
spring.datasource.druid.test-while-idle=
spring.datasource.druid.time-between-eviction-runs-millis=
spring.datasource.druid.min-evictable-idle-time-millis=
spring.datasource.druid.max-evictable-idle-time-millis=
spring.datasource.druid.filters= 
```
上面是当前版本支持的配置属性，这与[Wiki中的DruidDataSource配置属性列表](https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8)是一致的，如果你觉得这些还不能满足你的需要的话，可以在下面回复你需要Stater支持的属性，在下个版本可以添加上。

**Comment by qq592304796** [comment]
![default](https://user-images.githubusercontent.com/26601421/28447593-36e8f882-6e04-11e7-9924-7d442ac513cb.png)
现在好像不支持单个filter的详细配置吧
我想说个过分的要求.可以把常用的全部加上吗,哈哈

**Comment by lihengming** [comment]
@qq592304796 这种高度自定义推荐使用这种方式  [常见问题#31](https://github.com/alibaba/druid/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#31-%E5%A6%82%E4%BD%95%E5%9C%A8spring-boot%E4%B8%AD%E6%B7%BB%E5%8A%A0%E8%87%AA%E5%AE%9A%E4%B9%89wallconfigfilter-)

**Comment by qq592304796** [comment]
好的 谢谢

**Comment by lihengming** [comment]
#1850 #1800 #1851 #1823

收集了下当前```Issue```的建议及问题，```V1.1.2```版本将在不改变原有```API```的基础上做以下优化：
- 对 DruidDataSource 内所有提供```set```方法的属性提供自动配置支持和 IDE 提示
- 提供常用 FIlter 的自动配置支持和 IDE 提示
- 优化多数据源自动配置支持并提供 IDE 提示

如果你还有其他建议或问题，请在下面回复，我尽量在```V1.1.2```版本解决。

**Comment by lihengming** [comment]
@qq592304796 V1.1.2已支持，请查看文档，升级版本。

**Comment by DarkRake** [comment]
是否支持多个源呢？我这边要连接四个源

**Comment by lihengming** [comment]
@DarkRake 一直都支持的，请看文档。

**Comment by wwsgithub** [comment]
你好，是否支持动态添加、或者修改数据源信息呢？主要是数据库服务动态化，地址会变

**Comment by lihengming** [comment]
@wwsgithub  这和Druid & Starter 已经没啥关系了。我认为基于 Spring 可以实现的，但需要自己写代码，数据库配置读取远程配置中心的（Spring Cloud有类似实现，使用Zookeeper也可以实现），当配置改变的时候进行刷新（手动/自动）。
