### ISSUE TITLE
怎么关闭监控

### ISSUE THREAD

**Issue by kun1988** [alibaba/druid#1846]
因为使用的是阿里云的数据库，里面有监控，我想关闭druid的监控，但是不行。
filters: wall,slf4j这里我没有加stat可还是能打开/druid/index.html看到统计
我是用的druid-spring-boot-starter 1.1.1

**Comment by qq592304796** [comment]
![default](https://user-images.githubusercontent.com/26601421/28447548-f64b791c-6e03-11e7-839b-4616b3faaa9d.png)
默认是true,需要手动配置

**Comment by kun1988** [comment]
@qq592304796 谢谢，确实这样就没有页面了，但是statFilter是否还是在统计呢？

**Comment by kun1988** [comment]
// set filters default value on StatViewServlet enabled.
        if (!"false".equals(env.getProperty("spring.datasource.druid.stat-view-servlet.enabled")))

**Comment by qq592304796** [comment]
web-stat-filter.enabled=false,就不会再统计了

**Comment by andy-hu1993** [comment]
旧版本没有这两个参数如何关闭？

**Comment by tanbaba** [comment]
> 旧版本没有这两个参数如何关闭？

spring:
  datasource:
    druid:
      WebStatFilter:
        enabled: false
      StatViewServlet:
        enabled: false
