### ISSUE TITLE
谓词IN使用函数date_format 解析模版参数为空

### ISSUE THREAD

**Issue by yucx** [alibaba/druid#1849]
原始SQL:
select 1 from a where c1 in (date_format(date_add(curdate(), INTERVAL -7 DAY), '%Y%m%d'))
模版： SELECT ? FROM a WHERE c1 IN (?)
参数: [1,[]]

**Comment by wenshao** [comment]
问题修复，请用新版本
https://github.com/alibaba/druid/releases/tag/1.1.2
