### ISSUE TITLE
spring boot  druid connectionProperties参数配置

### ISSUE THREAD

**Issue by lilaizhencn** [alibaba/druid#1850]
之前有这么一句配置spring.datasource.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
如果换成spring boot start的话没有这个参数了啊

**Comment by lihengming** [comment]
什么意思？spring.datasource.* 开头的都是 Spring Boot 提供的，去官方文档看了 没见这项配置

**Comment by lihengming** [comment]
@lilaizhencn 已经解决了，请更换为V1.1.2版本，使用 ```spring.datasource.druid.connection-properties=``` 或 ```spring.datasource.druid.connectionProperties=```

**Comment by lilaizhencn** [comment]
非常感谢

**Comment by laodaobazi** [comment]
@lilaizhencn 更换为V1.1.2版本，使用 spring.datasource.druid.connection-properties= 或 spring.datasource.druid.connectionProperties= 你测试过吗？ 我这里还是没有试成功
