### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by hxj688699** [alibaba/druid#1851]
1、添加常用属性connectionProperties配置
2、DruidDataSource build(DruidDataSourceProperties properties) 放开访问权限，原因DruidDataSource build(Environment env, String prefix)扩展的时候不能直接用属性名很别扭

**Comment by lihengming** [comment]
1. ```connectionProperties```下个版本会加上

2.
```java
@Bean
public DataSource dataSource(Environment env){
    DruidDataSource dataSource = DruidDataSourceBuilder
            .create()
            .build(env,"spring.datasource.druid.");//使用自定义前缀
    
    //dataSource.setProxyFilters(filters);//添加自定义Filter
    //...进行其他配置
    return dataSource;
}
```
直接调用```set```方法扩展，不能直接使用属性名是什么意思?```build(DruidDataSourceProperties properties) ```依赖```Environment```，单独放开没任何作用。

**Comment by hxj688699** [comment]
比如配置方式
1. buspring.datasource.druid.validationQuery=*
2. buspring.datasource.druid.validation-query=*
注：说名一下我的应用里边用的是1配置方式，我把build(DruidDataSourceProperties properties)放开为public, DruidDataSourceProperties  启动后已经由@ConfigurationProperties("spring.datasource.druid")组装好了
比如我想这么用配置1，然后这么扩展
@Bean
public DataSource dataSource(Environment env，DruidDataSourceProperties  properties){
    DruidDataSource dataSource = DruidDataSourceBuilder
            .create()
            .build(properties);//使用自定义前缀
    
    //dataSource.setProxyFilters(filters);//添加自定义Filter
    //...进行其他配置
    return dataSource;
}
用配置2可以这么用
DruidDataSourceBuilder
            .create()
            .build(env,"spring.datasource.druid.")
第一中就是我说druid的直接属性名,貌似现在1、2两种配置方式是互质的，1配置DruidDataSourceProperties  properties有值，2配置DruidDataSourceProperties  properties无值，我不确定第二种配置方式下面的方式是否能取到值

public DataSource dataSource(DruidDataSourceProperties properties, Environment env) {

        //if not found prefix 'spring.datasource.druid' jdbc properties ,'spring.datasource' prefix jdbc properties will be used.
        if (properties.getUsername() == null) {
            properties.setUsername(env.getProperty("spring.datasource.username"));
        }
        if (properties.getPassword() == null) {
            properties.setPassword(env.getProperty("spring.datasource.password"));
        }
        if (properties.getUrl() == null) {
            properties.setUrl(env.getProperty("spring.datasource.url"));
        }
        if (properties.getDriverClassName() == null) {
            properties.setDriverClassName(env.getProperty("spring.datasource.driver-class-name"));
        }

        DruidDataSource dataSource = DruidDataSourceBuilder
                .create()
                .build(properties);

        return dataSource;
    }

**Comment by hxj688699** [comment]
我都是通过1直接对应属性名这种方式配置的
spring.datasource.druid.initialSize = 2
spring.datasource.druid.minIdle = 2
spring.datasource.druid.maxActive = 30
spring.datasource.druid.validationQuery = SELECT 1 FROM DUAL
spring.datasource.druid.timeBetweenEvictionRunsMillis = 60000
spring.datasource.druid.testWhileIdle = true
...

**Comment by lihengming** [comment]
下版本优化

**Comment by lihengming** [comment]
@hxj688699 已经发布了 文档：https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter

```validation-query```，这种使用分次符拼接单词的命名是 Spring Boot 的标准推荐，你也可以使用小驼峰```validationQuery``` 的命名方式，效果是一样的。

>person.firstName | Standard camel case syntax.
>person.first-name | Dashed notation, recommended for use in .properties and .yml files.
>person.first_name | Underscore notation, alternative format for use in .properties and .yml files.
>PERSON_FIRST_NAME | Upper case format. Recommended when using a system environment variables.

详见 Spring Boot 官方文档关于这部分的介绍：http://docs.spring.io/spring-boot/docs/1.5.4.RELEASE/reference/htmlsingle/#boot-features-external-config-relaxed-binding
