### ISSUE TITLE
druid-spring-boot 升级到1.1.1版本 数据库加密连接时 无法连接数据库

### ISSUE THREAD

**Issue by cuipengcx** [alibaba/druid#1854]
以下时配置信息:
![2](https://user-images.githubusercontent.com/21178565/28500966-c0db8be8-7004-11e7-8049-d5856f05a575.png)
![3](https://user-images.githubusercontent.com/21178565/28500973-d6aa69b2-7004-11e7-8a58-e2c432b30d3b.png)

下面时错误信息：
![aq 8s 12 6zfr 9re6d4c c](https://user-images.githubusercontent.com/21178565/28500939-38924150-7004-11e7-8c7d-61f6da2a9ddc.png)

**注：１．１．０版本正常**

**Comment by lihengming** [comment]
@cuipengcx  HI，应该是V1.1.1不支持connectionPropreties的问题，等V1.1.2发布吧，今天或明天发。

**Comment by wenshao** [comment]
新版已发布
https://github.com/alibaba/druid/releases/tag/1.1.2
