### ISSUE TITLE
使用druidpool处理oracle的long类型数据出现内存泄漏问题

### ISSUE THREAD

**Issue by wenger1987** [alibaba/druid#1862]
使用druidpool处理oracle的long类型数据出现内存泄漏问题，对内存一直处于使用1个G左右的状态，使用内存分析工具发现是在oracle驱动读取是申请了byte数组，没能即使释放使得内存一直使得比较多

**Comment by wenshao** [comment]
不应该哈，是不是有ResultSet没有关闭？

**Comment by wenger1987** [comment]
我后来升级了驱动版本就没有这个问题了
