### ISSUE TITLE
druid-spring-boot-start密码加密问题

### ISSUE THREAD

**Issue by yangm1203** [alibaba/druid#1864]
java -jar druid-1.1.2.jar com.alibaba.druid.filter.config.ConfigTools  密码
生成privateKey、publicKey、password
配置1
> publicKey: xxxxxxxx
spring:
  datasource:
    url: jdbc:mysql://xxxxx:3306/xxxxxx?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: xxxxx
    password: xxxxxxxxx
    druid:
      connection-properties: config.decrypt=true;config.decrypt.key=${privateKey};

会报数据库连接错误，密码不对。
`java.sql.SQLException: Access denied for user 'xxxxx'@'xxxxxxxx' (using password: YES)`

配置2
> publicKey: xxxxxxxx
spring:
  datasource:
    url: jdbc:mysql://xxxxx:3306/xxxxxx?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: xxxxx
    password: xxxxxxxxx
    druid:
      connection-properties: config.decrypt=true;
连接成功。但是hibernate报错：
`[2017-07-26 16:19:38.896] [WARN] [17416] [            restartedMain] --- [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:132)] : HHH000342: Could not obtain connection to query metadata : Failed to decrypt.`

如果我单纯用druid没问题，用了start就会出错，是不是我哪里没配置对？

**Comment by lihengming** [comment]
@yangm1203 

Hi，你这个配置姿势不太对，我为你写了个FAQ，去看看吧，很简单。

[如何在 Spring Boot 中配置数据库密码加密？](https://github.com/alibaba/druid/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#32-%E5%A6%82%E4%BD%95%E5%9C%A8-spring-boot-%E4%B8%AD%E9%85%8D%E7%BD%AE%E6%95%B0%E6%8D%AE%E5%BA%93%E5%AF%86%E7%A0%81%E5%8A%A0%E5%AF%86)

**Comment by yangm1203** [comment]
@lihengming 
我找到问题了，并不是配置错了，而是待加密密码中不能有上尖号（^）。
例如：
1. `baI@134523esdfgr@sHicaIw^*(U` 坏的
2. `baI134523esdfgrsHicaIwU` 好的
3. `baI@134523esdfgr@sHicaIw*(U` 好的
4. `baI134523esdfgr@sHicaIw^U` 坏的

**Comment by lihengming** [comment]
好吧，但是我没见到你启用ConfigFilter呀😄

**Comment by yangm1203** [comment]
@lihengming 
配置了，只是没贴出来，`config：enable`和`filters：config`都试过了，只是今天换了一个密码简单的数据库又试了一下发现居然是^它的问题。
希望这个小问题能修复哈，毕竟啥样的密码都有可能出现哈。
谢谢。

**Comment by lihengming** [comment]
@yangm1203  好的，解决了就好，不用谢哈。

**Comment by a18516614541** [comment]
我想问下，这个拿到配置文件就可以解密，这样意义何在，没想清楚。。。。

**Comment by lihengming** [comment]
@a18516614541 
配置文件可以被随便获取的话，说明公司的代码仓库存在安全问题。

网络世界本来就没有绝对的安全，通过秘钥加密内容，那谁来保护这个秘钥呢？再用一个秘钥来加密这个密钥？那这个加密的秘钥放哪呢？即使把最终秘钥（比如HTTPS 根证书的秘钥）存放在在拥有视网膜扫描和荷枪实弹的警卫守护的机房当中，在爆发战争后也形同虚设。

**Comment by yuqi141421** [comment]
> 我想问下，这个拿到配置文件就可以解密，这样意义何在，没想清楚。。。。

我的理解是：可以将加密后的密码和公钥由不同的配置中心管理。应用启动时从配置中心拉取配置信息。
由于是分开存放的，在一定程度上是能保证安全性的。至少比明文管理要安全一点。

**Comment by dujunchen** [comment]
@yuqi141421 @lihengming 我问一下，这个生成的私钥是不是没用了？配置文件里面也不需要配置？

**Comment by mek1986** [comment]
> [@yuqi141421](https://github.com/yuqi141421) [@lihengming](https://github.com/lihengming) 我问一下，这个生成的私钥是不是没用了？配置文件里面也不需要配置？

同问，生成出来的私钥有用吗？有用的话也没说怎么用啊！
