### ISSUE TITLE
oracle create index加local或者global关键字报错

### ISSUE THREAD

**Issue by zzx8170** [alibaba/druid#1866]
sql：CREATE INDEX dbobjs_idx ON dbobjs (created) LOCAL

解析错误：syntax error, error in :'ted) LOCAL ',expect LPAREN, actual EOF LOCAL

sql：CREATE INDEX dbobjs_idx ON dbobjs (created) global
解析错误：multi-statement not allowerror (1) : class com.alibaba.druid.sql.dialect.oracle.ast.stmt.OracleExprStatement not allow

**Comment by zzx8170** [comment]
这几个问题怎么没人关注？

**Comment by wenshao** [comment]
问题已解决，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.3
