### ISSUE TITLE
oracle alter index 报错

### ISSUE THREAD

**Issue by zzx8170** [alibaba/druid#1868]
sql：alter index idx_t1 rebuild
解析报错：class com.alibaba.druid.sql.dialect.oracle.ast.stmt.OracleAlterIndexStatement not allow

**Comment by zzx8170** [comment]
这几个问题怎么没人关注？

**Comment by wenshao** [comment]
问题已解决，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.3
