### ISSUE TITLE
MSSQL 2012的一些语法解析异常

### ISSUE THREAD

**Issue by LeasonX** [alibaba/druid#1880]
SQL监控中，解析OFFSET FETCH语法时失败(类似于  SELECT First Name + ' ' + Last Name FROM Employees ORDER BY First Name OFFSET 10 ROWS FETCH NEXT 5 ROWS ONLY;  这种语句)，是因为现在的版本还没支持到MSSQL 2012吗？

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.4
问题已经修复，请使用新版本
