### ISSUE TITLE
是否支持动态修改连接池数量 ?

### ISSUE THREAD

**Issue by pengyonglei** [alibaba/druid#1881]
## 背景: 
我们现在的数据库连接数是2000个, 然后我们有一个服务A, 然后给A服务配置了maxActive为2000; 现在我们增加了一个服务B, 但是A和B两个服务共用这2000个连接, 那druid是否支持在A服务**不停机**的情况下, 动态将A服务的连接数修改为1000个, 然后我将B服务的连接数改为1000个 . 以此类推, 我会有多个服务, 所以需要在不停机的情况下, 动态修改连接数 .
 
## 问题
请问动态修改服务的连接数可以在现有的功能里面做到吗 ?

**Comment by pengyonglei** [comment]
@wenshao 这个可以实现吗?

**Comment by wenshao** [comment]
支持的

**Comment by pengyonglei** [comment]
那具体是怎么操作的呢 ? 有没有文档可以查阅 ? 请赐教 @wenshao

**Comment by pengyonglei** [comment]
那我如何验证我修改连接数量是否修改成功呢 ? @wenshao
