### ISSUE TITLE
阿里的开源项目，就这个维护频率高些...

### ISSUE THREAD

**Issue by oicq1699** [alibaba/druid#1882]
看了很久，就这个项目还是持续有人在维护更新的：）才敢用到项目上去。加油啊，别断更啊。

**Comment by ding-kai** [comment]
哎、没用啊，多少问题待解决又没人管的

**Comment by wenshao** [comment]
fastjson & druid都是持续维护7年了，维护一个广受广泛使用的开源项目很辛苦的
