### ISSUE TITLE
UNION SQL call SQLUtils.format() will return wrong value

### ISSUE THREAD

**Issue by yucx** [alibaba/druid#1894]
Hi, Here is a bug:
Original SQL:
select * from (
select seller_name from a where id < 100
UNION 
select seller_name from a where id < 100
) as temp limit 10

After SQLUtils.format(), the output would be:
SELECT *
FROM (
	(SELECT seller_name
	FROM a
	WHERE id < 100
	UNION
	SELECT seller_name
	FROM a
	WHERE id < 100)
) temp
LIMIT 10

There is syntax error after format:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ) temp LIMIT 10' at line 9

**Comment by wenshao** [comment]
问题已解决，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.3

**Comment by Viyond** [comment]
got
