### ISSUE TITLE
oracle解析create index 出现重复表空间字句

### ISSUE THREAD

**Issue by zzx8170** [alibaba/druid#1910]
driud版本：1.1.1

create index idx_t12 on t1(id) tablespace users online;
解析后：
CREATE INDEX idx_t12 ON t1(id)
TABLESPACE users ONLINE
TABLESPACE users

最后多了一个TABLESPACE users，如果前面不写tablespace字句，后面也不会有

**Comment by wenshao** [comment]
bug确认，将会在周末发布新版本修复问题。方便说一下你的使用场景么？

**Comment by zzx8170** [comment]
谢谢，还有#1866、#1867、#1868三个issue也能确认bug，希望一起修复，我们的场景是oracle自动调数，常用的ddl和dml语句都希望能解析！

**Comment by wenshao** [comment]
问题已解决，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.3
