### ISSUE TITLE
列名映射需求

### ISSUE THREAD

**Issue by stepenelope** [alibaba/druid#1912]
对于一个指定的sql，输入的列名在指定映射后需要替换成另外一个列名。
例如select a from t，输入a->b的映射，sql变为select b from t。
希望8月底前能完成。

**Comment by wenshao** [comment]
问题已解决，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.3
具体使用方法，请看相关的testcase代码

**Comment by fanchencloud** [comment]
> 问题已解决，请用新版本https://github.com/alibaba/druid/releases/tag/1.1.3 具体使用方法，请看相关的testcase代码

select b.* from boy b join girl g where b.age = g.age order by b.id;    可以替换成
SELECT `Replace1`.* FROM `Replace1` b JOIN `Replace2` g WHERE `Replace1`.`Replace3`= `Replace2`.`Replace4` ORDER BY `Replace1`.`Replace5`;

请问这种怎么替换呢
