### ISSUE TITLE
使用 PagerUtils.count方法有bug

### ISSUE THREAD

**Issue by oawang** [alibaba/druid#1913]
使用方法：String result = PagerUtils.count(sql, JdbcConstants.MYSQL);

1) 调用前SQL: select count(*) from (select DISTINCT u.username, u.phone from t_user u ) t
2) 调用后生成：select DISTINCT count(*) from t_order t
当t_user表不只有username, phone字段时，则两条SQL执行的结果不一样

**Comment by wenshao** [comment]
druid什么版本呢？

**Comment by oawang** [comment]
druid 1.0.28

**Comment by oawang** [comment]
目前druid 版本为1.0.28，新版本号 1.1.2已经修复这个bug,请问从1.0.28升级到1.1.2对现有影响吗

**Comment by wenshao** [comment]
没影响，升级吧

**Comment by oawang** [comment]
谢谢
