### ISSUE TITLE
oracle的几个ddl语句解析bug

### ISSUE THREAD

**Issue by zzx8170** [alibaba/druid#1923]
sql：CREATE INDEX dbobjs_idx ON dbobjs (created) LOCAL

解析错误：syntax error, error in :'ted) LOCAL ',expect LPAREN, actual EOF LOCAL

sql：CREATE INDEX dbobjs_idx ON dbobjs (created) global
解析错误：multi-statement not allowerror (1) : class com.alibaba.druid.sql.dialect.oracle.ast.stmt.OracleExprStatement not allow

sql：CREATE SEQUENCE "GJS_ZIXUN"."FINANCE_EXPLAIN_ID_GENERATOR" CACHE 2
解析报错：syntax error: TODO : pos 67, LITERAL_INT CACHE
经过测试：CACHE /ORDER/CYCLE 几个关键字都无法解析

sql：alter index idx_t1 rebuild
解析报错：class com.alibaba.druid.sql.dialect.oracle.ast.stmt.OracleAlterIndexStatement not allow

**Comment by wenshao** [comment]
已经支持，请问是用在什么场景？

**Comment by wenshao** [comment]
问题已解决，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.3
