### ISSUE TITLE
发现查询出来的时间有的时候会变成GMT+8北京时区

### ISSUE THREAD

**Issue by masterchengsheng** [alibaba/druid#1927]
我这边的数据是放在美西，时区是GMT-8的 最近发现查询出来的时间会（很少几个）自动的变成了GMT+8  是不是Druid需要配置对应的配置项

**Comment by masterchengsheng** [comment]
时间变成了GMT-0 不是GMT+8

**Comment by lizongbo** [comment]
这个是数据库连接参数设置的问题，跟druid无关。
