### ISSUE TITLE
SQLASTOutputVisitor存在bug

### ISSUE THREAD

**Issue by hupengjie** [alibaba/druid#1931]
public boolean visit(MergeInsertClause x) {
        print0(ucase ? "WHEN NOT MATCHED THEN INSERT" : "when not matched then insert");
        if (x.getColumns().size() > 0) {
            print(' ');
            printAndAccept(x.getColumns(), ", ");
        }
        print0(ucase ? " VALUES (" : " values (");
 

这里的insert后面的属性没有用小括号括起来。

**Comment by wenshao** [comment]
能提供验证SQL么？

**Comment by hupengjie** [comment]
@wenshao 
MERGE INTO tb_xxx_test t1
USING (SELECT '1' AS aa_item_id, '2' AS mem_test_id FROM dual) t2
ON (t1.aa_item_id = t2.aa_item_id AND t1.mem_test_id = t2.mem_test_id)
WHEN NOT MATCHED THEN
  INSERT aa_id, aa_item_id, gg_id, test_id
  VALUES
    (?,
     ?,
     ?,
     ?)

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.4
问题已经修复，请使用新版本
