### ISSUE TITLE
请问如何支持国产达梦数据库？

### ISSUE THREAD

**Issue by Wizzercn** [alibaba/druid#1936]
www.dameng.com  政府类项目要求使用这个数据库，比较悲催。
![1](https://user-images.githubusercontent.com/2408114/29809469-dca488ca-8cce-11e7-9547-093416312c79.png)

**Comment by kimmking** [comment]
感觉就是一个定制的mysql，可以试试按照mysql处理。

**Comment by wenshao** [comment]
可以考虑支持的哈，不过最近比较忙，要花一些时间的

**Comment by Wizzercn** [comment]
https://github.com/nutzam/nutz/commit/8c5d8a289a8e4781dfcbdeefd08c216761b923f9

**Comment by Wizzercn** [comment]
@kimmking @wenshao https://github.com/nutzam/nutz/commit/8c5d8a289a8e4781dfcbdeefd08c216761b923f9 嗯，nutz框架增加了支持，目前看，好像OK了

**Comment by wenshao** [comment]
WallFilter是SQL防火墙，需要全面支持语法解析，并不一样的

**Comment by Wizzercn** [comment]
@wenshao 据说它是兼容oracle的，只在少量个别地方有差别，改起来应该很快

**Comment by wenshao** [comment]
你们是什么应用场景需要在达梦数据库上使用SQL防火墙？

**Comment by 1091662876** [comment]
> 你们是什么应用场景需要在达梦数据库上使用SQL防火墙？达梦有公开的SQL语法手册么？

我这有,您需要不? qq:1091662876

**Comment by Wizzercn** [comment]
```
db.driver=dm.jdbc.driver.DmDriver
db.url=jdbc:dm://127.0.0.1:5236/dmtest
db.user=dmtest
db.pwd=dmtest
db.pool.max=50
db.pool.init=10
db.pool.min=1
db.pool.wait=60000
db.time.betw=60000
db.time.met=300000
db.query.val=SELECT 'x'
db.test.idle=true
db.test.borr=false
db.test.return=false
db.filters=stat
connectionProperties=druid.stat.slowSqlMillis=200
```
达梦基本和oracle差别不大,不使用sql防火墙就可以正常用了
