### ISSUE TITLE
druid为什么叫druid？

### ISSUE THREAD

**Issue by shadowmaner** [alibaba/druid#1944]
感觉这个名字好酷啊
它的中文翻译是“德鲁伊”，听到这个有一种神兽的感觉。。

**Comment by lihengming** [comment]
Dota里面有个英雄叫德鲁伊，哈哈，不过应该不是因为这个。

**Comment by shadowmaner** [comment]
炉石传说里面也有这个
难道是因为项目贡献者非常喜欢这个卡牌职业？嗯...表示非常好奇，希望能得到官方的回复 ;-)

**Comment by kimmking** [comment]
这个问题得问。。。@wenshao

**Comment by wenshao** [comment]
当时的老板ljw喜欢玩dota，他起的名字

**Comment by lihengming** [comment]
好吧，还真是因为 Dota 哈 : )

**Comment by livem** [comment]
有另一个开源项目 http://druid.io

**Comment by shadowmaner** [comment]
原来如此，非常非常......感谢抽出宝贵时间来回答这种没含量的问题。。
