### ISSUE TITLE
POSTGRESQL format 错误!

### ISSUE THREAD

**Issue by renxiaoyao** [alibaba/druid#1945]
POSTGRESQL格式化错误，原始SQL是像这样的：
`SELECT to_char((CreateDate || ' ' || CAST (HourArgment AS VARCHAR) || ':00:00') :: TIMESTAMP,'YYYY-MM-DD HH24') "intoTime "
FROM
	analyzedata.StatTime AS cs
WHERE 1 = 1
AND cs.CreateDate >= to_date( '2017-08-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS' )
AND cs.CreateDate <= to_date( '2017-08-31 23:00:00', 'YYYY-MM-DD HH24:MI:SS' )
GROUP BY to_char(( CreateDate || ' ' || CAST (HourArgment AS VARCHAR) || ':00:00') :: TIMESTAMP, 'YYYY-MM-DD HH24')`

用Druid里面的SQLUtils.format(originalSQL, JdbcConstants.POSTGRESQL)) 格式化输出来是这样的：

`SELECT to_char(CreateDate || ' ' || CAST(HourArgment AS VARCHAR) || ':00:00'::TIMESTAMP, 'YYYY-MM-DD HH24') AS "intoTime "
FROM analyzedata.StatTime cs
WHERE 1 = 1
	AND cs.CreateDate >= to_date('2017-08-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
	AND cs.CreateDate <= to_date('2017-08-31 23:00:00', 'YYYY-MM-DD HH24:MI:SS')
GROUP BY to_char(CreateDate || ' ' || CAST(HourArgment AS VARCHAR) || ':00:00'::TIMESTAMP, 'YYYY-MM-DD HH24')`
'to_char' 的两层括号 '(())' 被格式化成了一层'()'.

**Before:**
`to_char((CreateDate || ' ' || CAST (HourArgment AS VARCHAR) || ':00:00') :: TIMESTAMP,'YYYY-MM-DD HH24') "intoTime "`
**After:**
`to_char(CreateDate || ' ' || CAST(HourArgment AS VARCHAR) || ':00:00'::TIMESTAMP, 'YYYY-MM-DD HH24') AS "intoTime "`
Druid version: 1.1.2 (Github 最新版源码来下来也是一样的结果)
JVM：1.8

**Comment by wenshao** [comment]
这两个语义是一样的哈

**Comment by renxiaoyao** [comment]
这样格式化之后SQL就无法执行了，无论是jdbc还是Navicat客户端。

**Comment by wenshao** [comment]
问题确认并修复

**Comment by sunny920406** [comment]
厉害了我的哥

**Comment by renxiaoyao** [comment]
响应快准狠，TKS @wenshao
