### ISSUE TITLE
Druid空闲连接过多导致连接泄露

### ISSUE THREAD

**Issue by mmxf** [alibaba/druid#1948]
生产上我配置最小连接30,最小空闲连接30。最大连接50,testWhileIdle为true 由于程序处于一段空闲状态(大概几个小时没人访问或者间接性几个人访问)。等到与人访问系统的时候每次获取连接的时候都会校验连接有效性（调用testConnectionInternal这个方法）.此时在调用testConnectionInternal这个方法之前连接池中数已经减1了。逻辑打开次数也加1了。但是在校验的时候该连接有问题（目前不知道为什么有问题因为我MySQL默认连接是8个小时断开。也没有防火墙之类的）然后该连接也不会做物理上的关闭。池中数和逻辑打开次数也没做处理就导致我从监控界面误认为我的程序导致连接泄露(其实也算是连接泄露)这个问题怎么解决。难道只有把最小连接和最小空闲连接配置为1吗？

**Comment by lizongbo** [comment]
请升级使用最新版本。
