### ISSUE TITLE
com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual IDENTIFIER so

### ISSUE THREAD

**Issue by patdong** [alibaba/druid#1950]
用Oracle写的sql，里面有聚合函数，会报如题的异常，不知道是否已经解决了这问题。并告知哪个版本可用。谢谢

**Comment by wenshao** [comment]
请提供完整SQL

**Comment by patdong** [comment]
SELECT supReg.regId,supReg.Title,supReg.Docnum,supReg.Itemtype,
              supReg.urgent,supReg.Feedbackdate,supReg.Feedbackperoid,
              supReg.Feedbackday ,supReg.dateSend,
              supReg.status ,supReg.analysed,supReg.feedbackWay,t.note,
              COUNT(distinct supReg.regId) OVER() TOTALCOUNT
         from sup_registration supReg 
   inner join (select st.regid, to_char(wmsys.WM_CONCAT(distinct so.orgname)) as note from sup_task st
                inner join sys_org so on st.orgid=so.orgid
                group by st.regid ) t on t.regid = supReg.regid                 
        WHERE supReg.status in (2,3,4) and supType='0' 

这里的wmsys.WM_CONCAT聚合函数影响了

**Comment by wenshao** [comment]
新版本是支持的 https://github.com/alibaba/druid/releases/tag/1.1.3

**Comment by patdong** [comment]
可以了，谢谢。

**Comment by freelandforus** [comment]
你好，druid的1.1.2版本，postgresql写的sql，如果配置了filter为 “wall”，就报错了，详细错误如下：
java.sql.SQLException: sql injection violation, syntax error: syntax error, expect RPAREN, actual LITERAL_CHARS pos 135, line 1, column 114, token LITERAL_CHARS 2017-09-10 00:00:00 : select * from public.newtable where EXTRACT(EPOCH FROM timestamptz (column1))  >=  EXTRACT(EPOCH FROM timestamptz '2017-09-10 00:00:00') limit 10 offset 0
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:725)

**Comment by donaldjohn** [comment]
select count(*)
from shop_inquiry
WHERE 1 = 1
and (date_add(from_unixtime(create_time/1000), INTERVAL CONVERT(fbyxq, UNSIGNED INTEGER) MONTH) < now());
;

**Comment by wenshao** [comment]
@donaldjohn 你这个是什么数据库？

**Comment by donaldjohn** [comment]
@wenshao mysql呢

**Comment by donaldjohn** [comment]
@wenshao create_time是Java的时间戳， 存在数据库里用int存的， 比mysql的 unix_time多了三位， 所以， 除了1000， fbyxq 是 发布有效期的意思，单位是月，  字符串的， 需要转成整型， 上面的语句实现的是 查询 当前过期的记录数， 别问为什么这么写， 我也很无奈

**Comment by panhaox** [comment]
@wenshao 在使用SQL server的历史表时，会报错，但不影响执行，SQL直接在数据库中执行也是没问题的。报错信息是com.alibaba.druid.sql.parser.ParserException: syntax error, not support option : IDENTIFIER, pos 343, line 1, column 332, token IDENTIFIER SYSTEM_TIME
SQL 如下。
SELECT
	id,
	delFlag,
	deviceId,
	guaranteeStatus,
	machineStatus,
	maintainWay,
	serialNumber,
	bankBranch_id,
	installInfo_id,
	logisticsInfo_id,
	machineType_id,
	warrantyInfo_id,
	create_time,
	modify_time,
	createUserId,
	modifyUserId,
	style_id,
	qr_code,
	fineness,
	specialOperateFlag,
	seller,
	sysstarttime,
	sysendtime 
FROM
	core_machine FOR SYSTEM_TIME ALL m

**Comment by TianjoshuaYongxing** [comment]
用Oracle写的sql，里面有聚合函数，会报如题的异常
### The error may exist in class path resource [mapper/IssueDao.xml]
### The error may involve io.mojo.dao.IssueDao.test
### The error occurred while executing a query
### SQL: SELECT (xmlagg (xmlparse ( content ISSUE_COMMENT || ' ；'wellformed ) ORDER BY ISSUE_ID ).getclobval ()) AS PROGRESS_NOTES FROM TT_ISSUE_EXPAND
### Cause: java.sql.SQLException: sql injection violation, syntax error: syntax error, expect RPAREN, actual IDENTIFIER pos 60, line 2, column 41, token IDENTIFIER ISSUE_COMMENT : SELECT
(xmlagg (xmlparse ( content ISSUE_COMMENT || ' ；'wellformed ) ORDER BY ISSUE_ID ).getclobval ()) AS PROGRESS_NOTES
FROM
TT_ISSUE_EXPAND
; uncategorized SQLException; SQL state [null]; error code [0]; sql injection violation, syntax error: syntax error, expect RPAREN, actual IDENTIFIER pos 60, line 2, column 41, token IDENTIFIER ISSUE_COMMENT : SELECT
(xmlagg (xmlparse ( content ISSUE_COMMENT || ' ；'wellformed ) ORDER BY ISSUE_ID ).getclobval ()) AS PROGRESS_NOTES
FROM
TT_ISSUE_EXPAND; nested exception is java.sql.SQLException: sql injection violation, syntax error: syntax error, expect RPAREN, actual IDENTIFIER pos 60, line 2, column 41, token IDENTIFIER ISSUE_COMMENT : SELECT
(xmlagg (xmlparse ( content ISSUE_COMMENT || ' ；'wellformed ) ORDER BY ISSUE_ID ).getclobval ()) AS PROGRESS_NOTES
FROM
TT_ISSUE_EXPAND
org.springframework.jdbc.UncategorizedSQLException:
### Error querying database. Cause: java.sql.SQLException: sql injection violation, syntax error: syntax error, expect RPAREN, actual IDENTIFIER pos 60, line 2, column 41, token IDENTIFIER ISSUE_COMMENT : SELECT
(xmlagg (xmlparse ( content ISSUE_COMMENT || ' ；'wellformed ) ORDER BY ISSUE_ID ).getclobval ()) AS PROGRESS_NOTES
FROM
TT_ISSUE_EXPAND

**Comment by 1126280688** [comment]
这个是druid低版本的bug,他在1.2.20版本已经修复了，升级可解决问题

**Comment by nuanyou** [comment]
Oracle迁移OceanBase数据库，filters:开启 stat 时，发生merge sql error，druid 版本1.1和1.2测试，均报错，详细信息如下：c.a.druid.filter.stat.StatFilter 160 mergeSql : merge sql error, dbType oceanbase, druid-1.2.23, 
sql : 
select
  a.province,
  count(*)
from
  projectbasicmain a
where
  a.projectstatus = '2'
  and a.editorcomecode in (
    select
      c.COMCODE
    from
      projectCompany c
    start with
      c.comcode = ?
    connect by
      nocycle c.parentComCode = prior c.comcode
  )
group by
  a.province;
com.alibaba.druid.sql.parser.ParserException: syntax error, expect ), actual IDENTIFIER pos 243, line 1, column 243, token IDENTIFIER c

**Comment by 1126280688** [comment]
你好，我是余金龙，我已收到您的邮件，谢谢。
