### ISSUE TITLE
SQLUtils.toStatementList()解析SQLServer 语句报错

### ISSUE THREAD

**Issue by SuperFireFoxy** [alibaba/druid#1953]
error:
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'de]
GO
CREATE TABLE [dbo].[Adode]', expect IDENTIFIER, actual IDENTIFIER pos 133, line 5, column 26, token IDENTIFIER GO

SQLServer:
```
-- ----------------------------
-- Table structure for Adode
-- ----------------------------
DROP TABLE [dbo].[Adode]
GO
CREATE TABLE [dbo].[Adode] (
[Ad_Work_Start_Time] varchar(255) NULL,
[Ad_Work_Stop_Time] varchar(255) NULL,
[Ad_Wait_Start_Time] varchar(255) NULL,
[Ad_Wait_Stop_Time] varchar(255) NULL,
[Order_ID] varchar(255) NOT NULL
)
```

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.4
问题已经修复，请使用新版本
