### ISSUE TITLE
update, delete更新行数风险检查

### ISSUE THREAD

**Issue by willenfoo** [alibaba/druid#1954]
业务出现场景： 现在druid中有updateWhereNoneCheck和deleteWhereNoneCheck属性，来检查风险SQL，   一般在项目中，90%的更新只会更新一行数据，少部分会更新多条数据，    在mybatis动态SQL中，比如update table set name = 'name' where number= 'tomcat' and age = 18，  因为是动态sql， 如果因为bug导致number没有传进来， sql会变成 update table set name = 'name' where age = 18， 本来只更新一条数据， 结果更新了多条数据

功能扩展需求： 添加updateWhereRowCheck和deleteWhereRowCheck属性，如果设置为true，最多只能更新一条数据，  如果出现带 in 的SQL， 更新条数最多不超过in的集合， 比如 in(1, 2, 3)， 则最多更新3条数据。

麻烦请扩展下这个功能， 更好的控制风险SQL， 谢谢

**Comment by lizongbo** [comment]
这种情况需要自己实现Filter来定制检测逻辑。
