### ISSUE TITLE
SQL insert 语句解析后获取不到currentTable

### ISSUE THREAD

**Issue by YYYYYYYYYYYYYYYY** [alibaba/druid#1957]
刚刚接触这个两天，头皮发麻。。。
SQL语句：
INSERT INTO TS_AREA_DEC 
(AREA_ID,AREA_CODE,AREA_NAME,AREA_TYPE_ID,PHONE_AREA_CODE)
SELECT A.AREA_ID,A.AREA_CODE,B.AREA_NAME,A.AREA_TYPE_ID,B.PHONE_AREA_CODE 
FROM TS_AREA_SRC A,TS_AREA B 
WHERE A.AREA_ID = B.AREA_ID;
解析方法：
`public void formatSQL(String sql,String dbType) {
		String result = SQLUtils.format(sql, dbType);
		System.out.println("result : ");
		System.out.println(result);
		List<SQLStatement> stmsList = SQLUtils.parseStatements(sql, dbType);
		for (int i = 0; i < stmsList.size(); i++) {
			SQLStatement statement = stmsList.get(i);
			OracleSchemaStatVisitor visitor = new OracleSchemaStatVisitor();
			statement.accept(visitor);
			System.out.println();
			System.out.println("currentTable :　"+visitor.getCurrentTable());
			System.out.println();
			System.out.println("tables : "+visitor.getTables());
			System.out.println();
			System.out.println("relationships : "+visitor.getRelationships());
		}
	}`
输出结果：
`result : 
INSERT INTO TS_ATEA_DEC (AREA_ID, AREA_CODE, AREA_NAME, AREA_TYPE_ID, PHONE_AREA_CODE)
SELECT A.AREA_ID, A.AREA_CODE, B.AREA_NAME, A.AREA_TYPE_ID, B.PHONE_AREA_CODE
FROM TS_AREA_SRC A, TS_AREA B
WHERE A.AREA_ID = B.AREA_ID;

currentTable :　null

tables : {TS_ATEA_DEC=Insert, TS_AREA_SRC=Select, TS_AREA=Select}

relationships : [TS_AREA_SRC.AREA_ID = TS_AREA.AREA_ID]`

很明显可以看到currentTable是null；
但是神奇的问题是：
换了一个SQL语句：
`String sql = "INSERT INTO TS_AREA_DEC "
				+ "(AREA_ID,AREA_CODE,AREA_NAME,AREA_TYPE_ID,PHONE_AREA_CODE) "
				+ "SELECT AREA_ID,AREA_CODE,AREA_NAME,AREA_TYPE_ID,PHONE_AREA_CODE "
				+ "FROM TS_AREA_SRC";`
结果却有了currentTable
`result : 
INSERT INTO TS_AREA_DEC (AREA_ID, AREA_CODE, AREA_NAME, AREA_TYPE_ID, PHONE_AREA_CODE)
SELECT AREA_ID, AREA_CODE, AREA_NAME, AREA_TYPE_ID, PHONE_AREA_CODE
FROM TS_AREA_SRC

currentTable :　TS_AREA_DEC

tables : {TS_AREA_DEC=Insert, TS_AREA_SRC=Select}

relationships : []`
请各位大佬帮我分析一下原因。。。

**Comment by YYYYYYYYYYYYYYYY** [comment]
1.1.13已经没有getCurrentTable（）这个方法了吗？

**Comment by wenshao** [comment]
是的，用在什么场景？

**Comment by YYYYYYYYYYYYYYYY** [comment]
@wenshao 就是希望能够解析出目标表和源表各字段的关联关系，我之前是用getCurrentTable这个方法来获取目标表，但是有时候会解析不出来，后面更新到1.1.13版本就发现这个方法已经没有了。。。

**Comment by YYYYYYYYYYYYYYYY** [comment]
@wenshao 就是希望能够解析出目标表和源表各字段的关联关系，我之前是用getCurrentTable这个方法来获取目标表，但是有时候会解析不出来，后面更新到1.1.13版本就发现这个方法已经没有了。。。

**Comment by wenshao** [comment]
用table不可以么？getCurrentTable是内部方法，1.1.3之后修改了实现了，这个方法不存在了。

**Comment by YYYYYYYYYYYYYYYY** [comment]
@wenshao 因为使用getCurrentTable是直接能够获取到目标表的，getTables是获取全部的表之后还要做判断处理，所以之前用的都是getCurrentTable，但是有时候会获取不到值，就像一楼那种情况，后来更新到1.1.13后就发现方法直接没有了。。。

**Comment by wenshao** [comment]
修改为getTables吧

**Comment by YYYYYYYYYYYYYYYY** [comment]
@wenshao 恩，我去试一试。
