### ISSUE TITLE
数据库SQL-log中没有发现心跳检测语句的记录

### ISSUE THREAD

**Issue by Hinsteny** [alibaba/druid#1958]
下面是我的配置参数: 谁能解释一下呢？ 非常感谢
#数据库地址
PAYMENT_JDBC_URL=jdbc:mysql://10.2.1.7:3312/payment?useLocalSessionState=true&amp;autoReconnect=true&amp;zeroDateTimeBehavior=convertToNull
PAYMENT_JDBC_USER=paymentuser
PAYMENT_JDBC_PASSWORD=paymentuser
#配置初始化大小、最小、最大
PAYMENT_JDBC_INITIALSIZE=5
PAYMENT_JDBC_MINIDLE=5
PAYMENT_JDBC_MAXACTIVE=30
#获取连接等待超时的时间
PAYMENT_JDBC_MAXWAIT=60000
#用来检测连接是否有效的sql，要求是一个查询语句
PAYMENT_JDBC_VALIDATIONQUERY=SELECT 1 
#空闲连接检测周期，单位是毫秒
PAYMENT_JDBC_EVICTIONRUNSMILLIS=1000
#连接在池中最小生存的时间，单位是毫秒
PAYMENT_JDBC_EVICTABLEIDLETIMEMILLIS=300000
#定时输出统计信息到日志中
PAYMENT_JDBC_TIMEBETWEENLOGSTATSMILLIS=300000
#申请连接的时候检测，如果空闲时间大于空闲连接检测时间执行validationQuery检测连接是否有效
PAYMENT_JDBC_TESTWHILEIDLE=true
#申请连接时执行validationQuery检测连接是否有效，配置为true会降低性能
PAYMENT_JDBC_TESTONBORROW=true
#归还连接时执行validationQuery检测连接是否有效，配置为true会降低性能
PAYMENT_JDBC_TESTONRETURN=false

**Comment by wenshao** [comment]
缺省是不发心跳语句的，如果需要，配置keepAlive=true

**Comment by Hinsteny** [comment]
谢谢，已经解决，提个小建议，如果可以的话，还望多加点注释
