### ISSUE TITLE
Oracle创建表时提示 1003 - can't lock multi-table

### ISSUE THREAD

**Issue by Fxdemon** [alibaba/druid#1959]
1003 - can't lock multi-table

SQL:
create table  T_NAS_LOCK_BOOK
(
  ID             VARCHAR2(32) default SYS_GUID() not null,
  BANK_NO        VARCHAR2(12) not null,
  CUST_NO        VARCHAR2(32) not null,
  CUST_ACCTNO    VARCHAR2(32) not null,
  ACCT_NAME      VARCHAR2(128) not null,
  ACCT_BRAN_NO   VARCHAR2(12) not null,
  LOCK_TXN_DATE  DATE not null,
  LOCK_CHNL_ID   VARCHAR2(8) not null,
  LOCK_SEQ       VARCHAR2(28) not null,
  LOCK_TIME      DATE not null,
  STAT           CHAR(1) not null,
  CERT_TYPE      VARCHAR2(5) not null,
  CERT_NO        VARCHAR2(32) not null,
  UNLOCK_DATE    DATE,
  UNLOCK_BRAN_NO VARCHAR2(12),
  UNLOCK_OPER_NO VARCHAR2(12),
  AUTH_OPER_NO   VARCHAR2(12),
  UNLOCK_TIME    DATE,
  UNLOCK_SEQ     VARCHAR2(28),
  REMARK         VARCHAR2(180),
  REMARK1        VARCHAR2(32),
  REMARK2        VARCHAR2(64),
  CREAT_TIME     DATE,
  MODIFY_TIME    DATE,
  VIR_BANK_NO    VARCHAR2(12) not null
)
tablespace ACC_DATA_TBS
  pctfree 10
  initrans 1
  maxtrans 255;
comment on table  T_NAS_LOCK_BOOK
  is '锁定解锁登记簿';
comment on column  T_NAS_LOCK_BOOK.ID
  is 'PK';
comment on column  T_NAS_LOCK_BOOK.BANK_NO
  is '行别';
comment on column  T_NAS_LOCK_BOOK.CUST_NO
  is '客户号';
comment on column  T_NAS_LOCK_BOOK.CUST_ACCTNO
  is '客户账号';
comment on column  T_NAS_LOCK_BOOK.ACCT_NAME
  is '户名';
comment on column  T_NAS_LOCK_BOOK.ACCT_BRAN_NO
  is '账户归属网点';
comment on column  T_NAS_LOCK_BOOK.LOCK_TXN_DATE
  is '锁定交易日期';
comment on column  T_NAS_LOCK_BOOK.LOCK_CHNL_ID
  is '锁定渠道';
comment on column  T_NAS_LOCK_BOOK.LOCK_SEQ
  is '锁定交易流水号';
comment on column  T_NAS_LOCK_BOOK.LOCK_TIME
  is '锁定时间';
comment on column  T_NAS_LOCK_BOOK.STAT
  is '状态';
comment on column  T_NAS_LOCK_BOOK.CERT_TYPE
  is '证件类型';
comment on column  T_NAS_LOCK_BOOK.CERT_NO
  is '证件号码';
comment on column  T_NAS_LOCK_BOOK.UNLOCK_DATE
  is '解锁日期';
comment on column  T_NAS_LOCK_BOOK.UNLOCK_BRAN_NO
  is '解锁网点';
comment on column  T_NAS_LOCK_BOOK.UNLOCK_OPER_NO
  is '解锁柜员';
comment on column  T_NAS_LOCK_BOOK.AUTH_OPER_NO
  is '授权柜员';
comment on column  T_NAS_LOCK_BOOK.UNLOCK_TIME
  is '解锁时间';
comment on column  T_NAS_LOCK_BOOK.UNLOCK_SEQ
  is '解锁流水号';
comment on column  T_NAS_LOCK_BOOK.REMARK
  is '备注';
comment on column  T_NAS_LOCK_BOOK.REMARK1
  is '备用1';
comment on column  T_NAS_LOCK_BOOK.REMARK2
  is '备用2';
comment on column  T_NAS_LOCK_BOOK.CREAT_TIME
  is '创建时间';
comment on column  T_NAS_LOCK_BOOK.MODIFY_TIME
  is '最后修改时间';
comment on column  T_NAS_LOCK_BOOK.VIR_BANK_NO
  is '虚拟行别';
alter table  T_NAS_LOCK_BOOK
  add constraint PK_T_NAS_LOCK_BOOK primary key (ID)
  using index 
  tablespace ACC_IDX_TBS
  pctfree 10
  initrans 2
  maxtrans 255;
create index  IDX_T_NAS_LOCK_BOOK_1 on  T_NAS_LOCK_BOOK (BANK_NO, ACCT_BRAN_NO, LOCK_TXN_DATE, CUST_ACCTNO)
  tablespace ACC_IDX_TBS
  pctfree 10
  initrans 2
  maxtrans 255;
create index  IDX_T_NAS_LOCK_BOOK_2 on  T_NAS_LOCK_BOOK (BANK_NO, UNLOCK_BRAN_NO, UNLOCK_DATE, CUST_ACCTNO)
  tablespace ACC_IDX_TBS
  pctfree 10
  initrans 2
  maxtrans 255;
create unique index  IDX_T_NAS_LOCK_BOOK_UNI_1 on  T_NAS_LOCK_BOOK (BANK_NO, CUST_ACCTNO, LOCK_TXN_DATE, LOCK_SEQ)
  tablespace ACC_IDX_TBS
  pctfree 10
  initrans 2
  maxtrans 255;

**Comment by wenshao** [comment]
这个和druid没关系吧
