### ISSUE TITLE
关于merge into 中update语句的字段计算的问题

### ISSUE THREAD

**Issue by YYYYYYYYYYYYYYYY** [alibaba/druid#1970]
在 merge into中update语句中如果有的字段进行了计算，如：
WHEN MATCHED THEN UPDATE SET A.SUM_CHRG_YS = ROUND(B.TOTAL_CHARGE * 1.00 / 10000, 2), A.CHARGE = B.THIS_CHARGE;
解析出来的items变成了
[A.SUM_CHRG_YS = ROUND(com.alibaba.druid.sql.ast.expr.SQLBinaryOpExpr@4f6fff9f, 2), 
A.CHARGE = B.THIS_CHARGE]
想请教一下com.alibaba.druid.sql.ast.expr.SQLBinaryOpExpr@4f6fff9f代表的是什么意思，能不能直接将字段解析出来？
具体SQL语句如下：
MERGE INTO (
	SELECT *
	FROM KPI_M_CW_INCOME_FACT_BAK
	WHERE THE_DATE = '{THISMONTH}'
		AND AREA_LEVEL <= 1
		AND TYPE_ID = '2'
) A
USING (
	SELECT *
	FROM M_HEALTH_APPRAISE_LOAD
	WHERE THE_DATE = TRUNC(SYSDATE)
		AND AREA_LEVEL <= 1
) B ON (A.AREA_ID = B.AREA_ID
AND A.AREA_LEVEL = B.AREA_LEVEL) 
WHEN MATCHED THEN UPDATE SET A.SUM_CHRG_YS = ROUND(B.TOTAL_CHARGE * 1.00 / 10000, 2), A.CHARGE = B.THIS_CHARGE;

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.4
问题已经修复，请使用新版本
