### ISSUE TITLE
durid 1.0.29 sessionStatMap is full

### ISSUE THREAD

**Issue by jxf114208** [alibaba/druid#1976]
durid 1.0.29

以下是log4j的日志输出：
**ERROR [com.alibaba.druid.support.http.stat.WebAppStat] - sessionStatMap is full**

**Comment by wenshao** [comment]
session数量过多，sessionStatMap满了

**Comment by jxf114208** [comment]
这个是需要手动清空呢？还是可以配置成自动清空？

**Comment by bluntviola** [comment]
mark

**Comment by bluntviola** [comment]
/druid/datasource.html. 这个是druid监控管理平台，里面可以reset重置，也可以通过配置关闭统计信息，具体配置信息，可以参考。https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter

**Comment by dinghaixiang** [comment]
出现这个报错对系统有影响吗？

**Comment by lizongbo** [comment]
> 出现这个报错对系统有影响吗？

只要内存撑得住就没有影响。
