### ISSUE TITLE
物理连接打开次数很大，关闭的接近0,

### ISSUE THREAD

**Issue by smile2014** [alibaba/druid#1978]
物理连接打开次数很大，关闭的接近0，有什么解决办法吗。

**Comment by smile2014** [comment]
物理连接打开次数 | 604 | 产生的物理连接建立总数
-- | -- | --
物理关闭数量 | 4 | 产生的物理关闭总数




活跃连接数 | 600 | 当前连接池中活跃连接数
-- | -- | --
活跃连接数峰值 | 600 | 连接池中活跃连接数峰值

**Comment by smile2014** [comment]
* 初始化连接大小 | 20 | 连接池建立时创建的初始化连接数
-- | -- | --
* 最小空闲连接数 | 10 | 连接池中最小的活跃连接数
* 最大连接数 | 600 | 连接池中最大的活跃连接数

**Comment by smile2014** [comment]
是不是他连接不释放阿。

**Comment by taolive** [comment]
同样问题，尤其适用springboot后，都不会手动去关闭connection的，怎么破？
