### ISSUE TITLE
SQL Parser在解析insert select语句时获取的字段不全

### ISSUE THREAD

**Issue by YYYYYYYYYYYYYYYY** [alibaba/druid#1994]
SQL：
INSERT INTO MKTG_H_EXEC_RESULT_FACT
	(THE_DATE, AREA_ID, SCENE_ID, MKTG_CNT, MKTG_SUC_CNT
	, TASK_CNT, TASK_F_CNT, TASK_F_SUC_CNT, CON_CNT, CON_SUC_CNT)
SELECT TRUNC(SYSDATE), T1.AREA_ID
	, RTRIM(TO_CHAR(T2.PID))
	, SUM(T1.MKTG_CNT), SUM(T1.MKTG_SUC_CNT)
	, SUM(T1.TASK_CNT), SUM(T1.TASK_F_CNT)
	, SUM(T1.TASK_F_SUC_CNT), SUM(T1.CON_CNT)
	, SUM(T1.CON_SUC_CNT)
FROM MKTG_H_EXEC_RESULT_FACT T1, (
	SELECT DISTINCT MKTG_PLAN_LVL1_ID AS PID, MKTG_PLAN_LVL4_ID AS SCENE_ID
	FROM DMN_MKTG_PLAN_TYPE
	UNION ALL
	SELECT DISTINCT MKTG_PLAN_LVL2_ID AS PID, MKTG_PLAN_LVL4_ID AS SCENE_ID
	FROM DMN_MKTG_PLAN_TYPE_TWO
	WHERE MKTG_PLAN_LVL2_ID <> MKTG_PLAN_LVL4_ID
	UNION ALL
	SELECT DISTINCT MKTG_PLAN_LVL3_ID AS PID, MKTG_PLAN_LVL4_ID AS SCENE_ID
	FROM DMN_MKTG_PLAN_TYPE
	WHERE MKTG_PLAN_LVL3_ID <> MKTG_PLAN_LVL4_ID
) T2
WHERE T1.THE_DATE = TRUNC(SYSDATE)
	AND T1.SCENE_ID = T2.SCENE_ID
GROUP BY T1.AREA_ID, RTRIM(TO_CHAR(T2.PID))
解析出来的字段：
MKTG_H_EXEC_RESULT_FACT.THE_DATE
MKTG_H_EXEC_RESULT_FACT.AREA_ID
MKTG_H_EXEC_RESULT_FACT.SCENE_ID
MKTG_H_EXEC_RESULT_FACT.MKTG_CNT
MKTG_H_EXEC_RESULT_FACT.MKTG_SUC_CNT
MKTG_H_EXEC_RESULT_FACT.TASK_CNT
MKTG_H_EXEC_RESULT_FACT.TASK_F_CNT
MKTG_H_EXEC_RESULT_FACT.TASK_F_SUC_CNT
MKTG_H_EXEC_RESULT_FACT.CON_CNT
MKTG_H_EXEC_RESULT_FACT.CON_SUC_CNT
DMN_MKTG_PLAN_TYPE.MKTG_PLAN_LVL1_ID
DMN_MKTG_PLAN_TYPE.MKTG_PLAN_LVL4_ID
DMN_MKTG_PLAN_TYPE_TWO.MKTG_PLAN_LVL2_ID
DMN_MKTG_PLAN_TYPE_TWO.MKTG_PLAN_LVL4_ID
DMN_MKTG_PLAN_TYPE.MKTG_PLAN_LVL3_ID
很明显可以看到，只解析了后面的三个连在一起的select语句，第一个select语句的所有的字段都没有解析出来。
使用的解析方法：
`OracleStatementParser parser = new OracleStatementParser(sql);

SQLInsertStatement insertStatement = (SQLInsertStatement) parser.parseInsert();

OracleSchemaStatVisitor visitor = new OracleSchemaStatVisitor();

insertStatement.accept(visitor);

Collection<Column> columns = visitor.getColumns();

for (Column column : columns) {
	System.out.println(column);
}`

**Comment by YYYYYYYYYYYYYYYY** [comment]
如果将select语句提取出来，获取SQLSelectItem，获取到的字段变成了：
TRUNC(com.alibaba.druid.sql.dialect.oracle.ast.expr.OracleSysdateExpr@7a7b0070)
T1.AREA_ID
RTRIM(TO_CHAR(T2.PID))
com.alibaba.druid.sql.ast.expr.SQLAggregateExpr@4c67d6c2
com.alibaba.druid.sql.ast.expr.SQLAggregateExpr@62c08d21
com.alibaba.druid.sql.ast.expr.SQLAggregateExpr@1ca802c2
com.alibaba.druid.sql.ast.expr.SQLAggregateExpr@3fc80fb7
com.alibaba.druid.sql.ast.expr.SQLAggregateExpr@71c94436
com.alibaba.druid.sql.ast.expr.SQLAggregateExpr@b80772de
com.alibaba.druid.sql.ast.expr.SQLAggregateExpr@e2330fc
又没有将后面三个select语句的字段解析出来。
使用的提取select语句块的方法：
`SQLSelect select = insertStatement.getQuery();

SQLSelectQueryBlock queryBlock  = select.getQueryBlock();

List<SQLSelectItem> selectItems = queryBlock.getSelectList();

for (SQLSelectItem sqlSelectItem : selectItems) {
	System.out.println(sqlSelectItem);
}`

**Comment by wenshao** [comment]
@YYYYYYYYYYYYYYYY 你提了较多的SQL Parser类的需求，我想了解一下你们的使用情况，方便的话请加我微信 wenshaojin

**Comment by YYYYYYYYYYYYYYYY** [comment]
@wenshao 加了，希望您同意一下

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.4
问题已经修复，请使用新版本
