### ISSUE TITLE
datasource存在资源泄漏隐患

### ISSUE THREAD

**Issue by qudongfang** [alibaba/druid#1998]
数据库服务故障期间，启动使用druid库的server，可能存在线程资源泄漏隐患。

[常见问题](https://github.com/alibaba/druid/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)中，有提到

> 24. 如果DruidDataSource在init的时候失败了，不再使用，是否需要close
是的，如果DruidDataSource不再使用，必须调用close来释放资源，释放的资源包括关闭Create和Destory线程。

是不是在lib中做一些防御比较好？

另外：DruidDataSource的init方法打印的log与init的结果并不完全一致。如：init过程抛异常，finally仍打印初始化成功。

#1991

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.4
新版本新增加asyncInit配置，看是否能解决你的问题
