### ISSUE TITLE
作为firewall使用在mysql上的时候lock tables .. write过不了校验

### ISSUE THREAD

**Issue by sunsun314** [alibaba/druid#2000]
LOCK TABLES table_name write 在mysql防火墙校验的时候会过不了校验
debug发现是由于在校验lock tables table_name write之后跳转到
SQLStatementParser.parseStatementList循环的时候lexer.token的值为write
结果就会到 printError(lexer.token);

**Comment by wenshao** [comment]
应该是支持的哈，druid什么版本？

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.4
问题已经修复，请使用新版本
