### ISSUE TITLE
关于解析SYSDATE的问题

### ISSUE THREAD

**Issue by YYYYYYYYYYYYYYYY** [alibaba/druid#2001]
在解析SYSDATE这个字段时，只支持解析为com.alibaba.druid.sql.dialect.oracle.ast.expr.OracleSysdateExpr@7a7b0070这种形式吗？这样对解析结果不好进行处理啊，能不能支持直接解析为SYSDATE？

**Comment by YYYYYYYYYYYYYYYY** [comment]
在解析select 语句中的SYSDATE的字段时，如果使用的是getColums（）方法则SYSDATE不能被解析出来，使用getSelectList（）方法时获取的就是com.alibaba.druid.sql.dialect.oracle.ast.expr.OracleSysdateExpr@7a7b0070这种形式。

**Comment by wenshao** [comment]
SYSDATE不是column哈

**Comment by YYYYYYYYYYYYYYYY** [comment]
@wenshao 那要用什么方法才能解析出来呢？

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.4
问题已经修复，请使用新版本

**Comment by 14122573** [comment]
当sysdate在函数当中的时候，比如to_char(sysdate,'YYYYMMDD')的时候，使用getselectlist方法获取到的，还是对象 @wenshao
