### ISSUE TITLE
SQLUpdateStatement#output 输出where有误，直接调用了Object的toString

### ISSUE THREAD

**Issue by mashuai** [alibaba/druid#2015]
Druid版本1.1.3 
输入update语句
```SQL
update t set a=1,b=2 where a > 1
``` 
Parse 之后调用`SQLUpdateStatement`的 output语句输出：
```SQL
UPDATE t SET a = 1, b = 2 WHERE com.alibaba.druid.sql.ast.expr.SQLBinaryOpExpr@ca624a2d
```
调用输出的时候调用了   `SQLObjectImpl` 的
```Java
public void output(StringBuffer buf) {
        buf.append(super.toString());
    }
```
这里直接调用了Object的 toString，导致失败

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.4
问题已经修复，请使用新版本

**Comment by fly0wing** [comment]
我也遇到了类似的问题，版本1.1.4.
        String sql = "select t1.a-t2.b as a from t1 join t2 on t1.z=t2.z where t2.c='1'";
        MySqlSelectParser parser = new MySqlSelectParser(sql);
        MySqlSelectQueryBlock query = (MySqlSelectQueryBlock) parser.query();
        System.out.println("from\t:" + query.getFrom().toString());

输出:
from	:t1 JOIN t2 ON com.alibaba.druid.sql.ast.expr.SQLBinaryOpExpr@cb3f030
