### ISSUE TITLE
SpringBoot+Druid请教配置

### ISSUE THREAD

**Issue by iamchao1129** [alibaba/druid#2020]
如何配置监控地址为"/admin/druid"..

**Comment by lihengming** [comment]
很简单，使用Druid Spring Boot Starter，在你的配置文件中加入下面配置即可。 

```spring.datasource.druid.stat-view-servlet.url-pattern=/admin/druid/*```

**Comment by iamchao1129** [comment]
如此配置在访问/admin/druid/时会跳转到127.0.0.1:8080/druid/login.html (404), 而不是127.0.0.1:8080/admin/druid/login.html

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.4
问题已经修复，请使用新版本
