### ISSUE TITLE
监控配置BUG

### ISSUE THREAD

**Issue by idawnorg** [alibaba/druid#2021]
若项目部署到ROOT,监控路径配置为<url-pattern>/sys/druid/*</url-pattern>，访问的时候是有问题（404），没有了/sys/路径，访问的路径为：127.0.0.1:8080/druid/login.html,访问 127.0.0.1:8080/sys/druid/login.html没有问题，加上项目上下文也没有问题

**Comment by iamchao1129** [comment]
我正是想说这个事#2020

**Comment by idawnorg** [comment]
我再改源码试试

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.4
问题已经修复，请使用新版本
