### ISSUE TITLE
API changes report for Druid

### ISSUE THREAD

**Issue by lvc** [alibaba/druid#2025]
The review of API changes for the Druid library since 1.0.0 version: https://abi-laboratory.pro/java/tracker/timeline/druid/

Hope it will be helpful for users and maintainers of the library.

The report is generated by https://github.com/lvc/japi-compliance-checker for jars found at http://central.maven.org/maven2/com/alibaba/druid/ according to https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Thank you.

![druid-2](https://user-images.githubusercontent.com/1517837/31114201-92d5820e-a825-11e7-9db1-76049331a8c7.png)
![druid-1](https://user-images.githubusercontent.com/1517837/31114200-92d553b0-a825-11e7-80f9-c9b1fc5d1ca1.png)

**Comment by wenshao** [comment]
thank you. it's very useful.
