### ISSUE TITLE
 java9 的 支持!

### ISSUE THREAD

**Issue by vnobo** [alibaba/druid#2029]
JAVA9里面还是报错!

Errors occurred while build effective model from C:\Users\billb\.gradle\caches\modules-2\files-2.1\com.alibaba\druid\1.1.4\f8d7161d0bbf48bd82260080fc56f3ab80caff24\druid-1.1.4.pom:
    'dependencies.dependency.systemPath' for com.alibaba:jconsole:jar must specify an absolute path but is ${env.JAVA_HOME}/lib/jconsole.jar in com.alibaba:druid:1.1.4
    'dependencies.dependency.systemPath' for com.alibaba:tools:jar must specify an absolute path but is ${env.JAVA_HOME}/lib/tools.jar in com.alibaba:druid:1.1.4

**Comment by Cat7373** [comment]
这个我猜会跟 SpringBoot2 一起支持 0.0

**Comment by rill** [comment]
支持java9的版本大概什么时候推出？

**Comment by pkaq** [comment]
好像没动静了?

**Comment by lizongbo** [comment]
请使用最新版验证

**Comment by vnobo** [comment]
5 years have passed and it has finally been closed. Is it supported in java21?

**Comment by lizongbo** [comment]
> 5 years have passed and it has finally been closed. Is it supported in java21?

去年给Spring提bug的时候就验证了JDK17可以正常使用
https://github.com/spring-projects/spring-framework/issues/28138
现在我的测试项目就运行在JDK21上面，druid连接池正常使用，没有问题。
