### ISSUE TITLE
整合Springboot 2.0.0M4问题

### ISSUE THREAD

**Issue by chixinzei** [alibaba/druid#2030]
1.自动注入druid数据源属性空值失败，个人已经在帖子https://github.com/alibaba/druid/issues/1799 内使用忽略注入失败来修正问题，不知是否有问题？

2.从boot 2.0.0 M4开始，DataSourcePoolMetadataProvider包位置已经转移
从：org.springframework.boot.autoconfigure.jdbc.metadata
转移到：org.springframework.boot.jdbc.metadata
执行test类会报错：
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.autoconfigure.jdbc.metadata.DataSourcePoolMetadataProvider
，目前我只能尝试降级版本到2.0.0M3，包路径才能一致，也求解决办法支持M4或其他办法。

**Comment by lihengming** [comment]
先降级把，目前还不知道 Spring Boot 2.0 ,等正式版发布后会支持，目前变动还比较频繁。
