### ISSUE TITLE
format db2 建表语句出错

### ISSUE THREAD

**Issue by YYYYYYYYYYYYYYYY** [alibaba/druid#2033]
SQL：
CREATE TABLE MK.KPI_AREA_SORT_FACT_LATN_ID_MID
(
  LATN_ID           INTEGER,
  BUREAU_KEY        INTEGER,
  ADD_SUM           BIGINT,
  USER_ACCT         BIGINT,
  USER_ACCT_LY      BIGINT,
  TYPE_ID           INTEGER
)
  DATA CAPTURE NONE
  IN WH_APP_TEMP
  PARTITIONING KEY
(LATN_ID,BUREAU_KEY,ADD_SUM
 ) USING HASHING;

在对该语句进行format时报语法错误：syntax error, error in :'GER )DATA CAPTURE NONE IN WH_APP_TE', expect IDENTIFIER, actual IDENTIFIER pos 205, line 1, column 202, token IDENTIFIER DATA

但是对该语句进行解析时可以正常解析。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.5
