### ISSUE TITLE
db2 的format问题

### ISSUE THREAD

**Issue by YYYYYYYYYYYYYYYY** [alibaba/druid#2037]
SQL：
SELECT LATN_ID,
  CASE WHEN BUREAU_KEY = 116 THEN 46 ELSE BUREAU_KEY END BUREAU_KEY,
       SUM(COALESCE(ADD_USER_CNT, 0)) ADD_SUM, 
       0 USER_ACCT,
       0 USER_ACCT_LY
  FROM MK.M_BROAD_BAND_USER_FACT
 WHERE THE_DATE BETWEEN SUBSTR('{THISMONTH}', 1, 4) || '-01-01' AND '{THISMONTH}'
 GROUP BY LATN_ID,
  CASE WHEN BUREAU_KEY = 116 THEN 46 ELSE BUREAU_KEY END
 UNION ALL
SELECT LATN_ID,
  CASE WHEN BUREAU_KEY = 116 THEN 46 ELSE BUREAU_KEY END BUREAU_KEY,
       0 ADD_SUM,
       SUM(COALESCE(BILL_USER_CNT, 0)) USER_ACCT, 
       0 USER_ACCT_LY
  FROM MK.M_BROAD_BAND_USER_FACT
 WHERE THE_DATE = '{THISMONTH}'
 GROUP BY LATN_ID,
  CASE WHEN BUREAU_KEY = 116 THEN 46 ELSE BUREAU_KEY END
 UNION ALL
SELECT LATN_ID,
  CASE WHEN BUREAU_KEY = 116 THEN 46 ELSE BUREAU_KEY END BUREAU_KEY,
       0 ADD_SUM,
       0 USER_ACCT,
       SUM(COALESCE(BILL_USER_CNT, 0)) USER_ACCT_LY  
  FROM MK.M_BROAD_BAND_USER_FACT
 WHERE THE_DATE = DATE(SUBSTR('{THISMONTH}', 1, 4) || '-01-01') - 1 MONTHS
 GROUP BY LATN_ID,
  CASE WHEN BUREAU_KEY = 116 THEN 46 ELSE BUREAU_KEY END；
对其进行format时报syntax error, error in :' - 1 MONTHS GROUP BY LATN_ID,CASE W', expect IDENTIFIER, actual IDENTIFIER pos 924, line 1, column 918, token IDENTIFIER MONTHS错误，解析时可以正常解析。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.5 问题已修复，请用新版本
