### ISSUE TITLE
db2解析带有WITH UR的SQL语句时报错

### ISSUE THREAD

**Issue by YYYYYYYYYYYYYYYY** [alibaba/druid#2041]
在解析带有WITH UR的SQL语句时会报syntax error, expect ROLLUP, actual IDENTIFIER, pos 851, line 1, column 849, token IDENTIFIER UR的错误

**Comment by wenshao** [comment]
能否提供一下完整的SQL语句

**Comment by YYYYYYYYYYYYYYYY** [comment]
@wenshao 
INSERT INTO MK.KPI_AREA_SORT_FACT_LATN_ID_MID
SELECT LATN_ID,BUREAU_KEY,
       SUM(ADD_SUM),
       SUM(USER_ACCT),
       SUM(USER_ACCT_LY),
       1 
  FROM (
SELECT LATN_ID,
  CASE WHEN BUREAU_KEY = 116 THEN 46 ELSE BUREAU_KEY END BUREAU_KEY,
       SUM(COALESCE(USER_CNT_ADD, 0)) ADD_SUM, 
       0 USER_ACCT,
       0 USER_ACCT_LY
  FROM MK.M_USER_COUNT_FACT_CDMA
 WHERE THE_DATE BETWEEN SUBSTR('{THISMONTH}', 1, 4) || '-01-01' AND '{THISMONTH}'
   AND PAG_FLAG = 0
 GROUP BY LATN_ID,
  CASE WHEN BUREAU_KEY = 116 THEN 46 ELSE BUREAU_KEY END

UNION ALL
SELECT LATN_ID,
  CASE WHEN BUREAU_KEY = 116 THEN 46 ELSE BUREAU_KEY END BUREAU_KEY,
       0 ADD_SUM,
       SUM(COALESCE(USER_CNT_AMOUNT, 0)) USER_ACCT, 
       0 USER_ACCT_LY
  FROM MK.M_USER_COUNT_FACT_CDMA
 WHERE THE_DATE = '{THISMONTH}'
   AND PAG_FLAG = 0
 GROUP BY LATN_ID,
  CASE WHEN BUREAU_KEY = 116 THEN 46 ELSE BUREAU_KEY END
  
UNION ALL
SELECT LATN_ID,
  CASE WHEN BUREAU_KEY = 116 THEN 46 ELSE BUREAU_KEY END BUREAU_KEY,
       0 ADD_SUM,
       0 USER_ACCT,
       SUM(COALESCE(USER_CNT_AMOUNT, 0)) USER_ACCT_LY  
  FROM MK.M_USER_COUNT_FACT_CDMA
 WHERE THE_DATE = DATE(SUBSTR('{THISMONTH}', 1, 4) || '-01-01') - 1 MONTHS
   AND PAG_FLAG = 0 
 GROUP BY LATN_ID,
  CASE WHEN BUREAU_KEY = 116 THEN 46 ELSE BUREAU_KEY END
) T
GROUP BY LATN_ID,BUREAU_KEY
 WITH UR
;
而且也会对 WHERE THE_DATE = DATE(SUBSTR('{THISMONTH}', 1, 4) || '-01-01') - 1 MONTHS这边报语法错误

**Comment by wenshao** [comment]
问题重现并修复，等下一个版本吧，预计两个星期。如果着急自己编译一个版本

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.5 问题已修复，请用新版本
