### ISSUE TITLE
工程mvn后导入eclipse报错，Plugin execution not covered by lifecycle configuration

### ISSUE THREAD

**Issue by afei199002** [alibaba/druid#2048]
git clone 工程
mvn license:format
mvn clean install -Dmaven.test.skip=true
然后导入到eclipse

我搜了好久，没有解决，可以帮忙看下什么问题么，谢谢
下面是详细报错信息
Description	Resource	Path	Location	Type
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-resources-plugin:2.6:resources (execution: default-resources, phase: process-resources)	pom.xml	/druid	line 8	Maven Project Build Lifecycle Mapping Problem

Description	Resource	Path	Location	Type
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-resources-plugin:2.6:testResources (execution: default-testResources, phase: process-test-resources)	pom.xml	/druid	line 8	Maven Project Build Lifecycle Mapping Problem

Description	Resource	Path	Location	Type
Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:buildnumber-maven-plugin:1.1:create (execution: default, phase: validate)	pom.xml	/druid	line 215	Maven Project Build Lifecycle Mapping Problem

看意思像是插件的声明周期没有配置么？

**Comment by wenshao** [comment]
用idea试试

**Comment by afei199002** [comment]
@wenshao 谢谢，没想到这么快有作者回复  哈哈
我试试，

**Comment by afei199002** [comment]
idea 导入OK。
