### ISSUE TITLE
SHOW tables IN db_name 解析有误

### ISSUE THREAD

**Issue by sunsun314** [alibaba/druid#2053]
在mysql的官网中，show tables 语法如下  
SHOW [FULL] TABLES
  [{FROM | IN} db_name]
  [LIKE 'pattern' | WHERE expr]
但是在解析器中不支持show tables in db_name ......

**Comment by wenshao** [comment]
能否补上testcase，避免以后问题重现出现

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.5 问题已修复，请用新版本
