### ISSUE TITLE
符号‘~’解析有误

### ISSUE THREAD

**Issue by sunsun314** [alibaba/druid#2055]
现象：  
  ‘ ~ (id = 1) ’和‘ ~ id = 1”应该拥有不同的语义，但是通过druid解析的结果相同  
原因：  
  在解析过程中将~之后的内容当作一个表达式来解析，但实际上应该和‘!’的解析逻辑相同

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.5 问题已修复，请用新版本
