### ISSUE TITLE
UPDATE 中有两个INNER JOIN 时报错

### ISSUE THREAD

**Issue by bjxg** [alibaba/druid#2057]
1.1.4版本 UPDATE 中有两个INNER JOIN 时报错，SQL大概如下：
UPDATE t1
INNER JOIN t2 ON t1.id = t2.id
INNER JOIN t3 cm ON  t3.id2= t1.id2
 SET t1.name=..............

错误信息如下：
Caused by: java.lang.NullPointerException
	at com.alibaba.druid.wall.spi.WallVisitorUtils.checkUpdate(WallVisitorUtils.java:849)

看了下代码：

 public SQLName getTableName() {
       if (tableSource instanceof SQLExprTableSource) {
            return ((SQLExprTableSource) tableSource).getName();
        }

        if (tableSource instanceof SQLJoinTableSource) {
            SQLTableSource left = ((SQLJoinTableSource) tableSource).getLeft();
            if (left instanceof SQLExprTableSource) {
                return ((SQLExprTableSource) left).getName();
            }
        }
        return null;
}

这里的left其实还是SQLJoinTableSource，所以此方法直接return null 导致出现NullPointerException

**Comment by wenshao** [comment]
我增加了回归测试，问题没有重现 https://github.com/alibaba/druid/commit/9bd0b1456d091478113d5a122d50060d8518c968

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.5 问题已修复，请用新版本
