### ISSUE TITLE
监控页面重定向问题

### ISSUE THREAD

**Issue by smileLuckBoy** [alibaba/druid#2058]
1.1.4版本中，直接访问数据源URL：http://127.0.0.1:8080/druid/datasource.html，返回http://127.0.0.1:8080/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/login.html

**Comment by wenshao** [comment]
@idawnorg 你提交的patch似乎有问题

**Comment by l22576283** [comment]
确实如此，我在1.1.4也遇到了一样的问题
spring boot配置如下
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false              #禁用HTML页面上的“Reset All”功能
        login-username: admin
        login-password: admin123
        allow: 192.168.1.110,127.0.0.1  #IP白名单 (没有配置或者为空，则允许所有访问)
        deny: 192.168.16.111            #IP黑名单 (存在共同时，deny优先于allow)

每次重启会话丢失后，直接访问 http://localhost:8080/druid/login.html 是没有问题的，但是只要在没登录的情况访问其他的任意页面，例如 http://localhost:8080/druid/datasource.html 或者 http://localhost:8080/druid/abc 就会出现 重定向至 
http://127.0.0.1:8080/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/login.html 的问题

**Comment by lxglove** [comment]
**springboot 1.5.2引用druid 1.1.4**
application.properties配置如下：
spring.datasource.druid.stat-view-servlet.enabled=true
spring.datasource.druid.stat-view-servlet.url-pattern=/druid/*
spring.datasource.druid.stat-view-servlet.login-username=druid
spring.datasource.druid.stat-view-servlet.login-password=druid
浏览器：
http://127.0.0.1:8024/druid/login.html提交后效果
http://127.0.0.1:8024/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/druid/login.html

有解决办法吗 @wenshao

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.5 问题已修复，请用新版本
