### ISSUE TITLE
StatFilter扩展问题

### ISSUE THREAD

**Issue by sunchey11** [alibaba/druid#2061]
想做一个需求，
显示活动链接正在运行的sql，如果正在运行一个sql很慢的话，就可以直接在活动连接那里看到。
现在的想法是对StatFilter做子类，复写几个方法，需要用到StatFilter.buildSlowParameters方法，这个方法是private的，是否可以将他变为protected,这样就不需要整个方法拷贝出来了。
另外，internalAfterStatementExecute方法中的
 if (logSlowSql) {
                    LOG.error("slow sql " + millis + " millis. "。。。
 }
if里面那一行，是否可以做成一个protected函数,这样在有需要的时候也可以复写

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.5 问题已修复，请用新版本
