### ISSUE TITLE
spring-boot-druid-starter怎么配置connection-init-sqls

### ISSUE THREAD

**Issue by wpzym1125** [alibaba/druid#2072]
spring.datasource.druid.connection.connection-holder.data-source.connection-init-sqls[0] 不管怎么配都报这个错误，不配置也会报这个错误。谁知道怎么回事啊？

**Comment by lizongbo** [comment]
应该是这样写，只支持逗号隔开
`
spring.datasource.druid.connection-init-sqls=SET NAMES utf8mb4,SET NAMES utf8mb4

`
