### ISSUE TITLE
请问Druid是否可以提供一个预热连接的功能

### ISSUE THREAD

**Issue by TimeEraser** [alibaba/druid#2075]
曾做过测试这样一个测试：
           mysql在大量建立连接的过程中正常的SQL也会比较慢？
          我的思路是能不能在突发流量之前把连接预热好，事先建立好足够的连接在维护在内存中。
Druid是否考虑一下连接预热的功能？

**Comment by wenshao** [comment]
有的
```java
com.alibaba.druid.pool.DruidDataSource#fill()
com.alibaba.druid.pool.DruidDataSource#fill(int)
```

**Comment by TimeEraser** [comment]
找到了，谢谢 温少！

**Comment by kakakeven** [comment]
赞

**Comment by bigzuo** [comment]
请教两位大佬一下，这两个方法要如何使用呢？直接在 main 方法里面 new DruidDataSource().fill() 应该不对吧？

com.alibaba.druid.pool.DruidDataSource#fill()
com.alibaba.druid.pool.DruidDataSource#fill(int)
