### ISSUE TITLE
发现

### ISSUE THREAD

**Issue by yhb890430** [alibaba/druid#2077]
版本：1.1.3
spring版本:4.3.11.RELEASE
问题：在spring中配置数据源时，如果数据库连接的参数名称叫“url”，会和maven pom 里面的url标签冲突，
会直接取maven url标签中的值作为数据库连接

**Comment by kimmking** [comment]
spring boot？配置文件里是url= 这种吗？

**Comment by yhb890430** [comment]
是配置文件里面的但是不是springboot 就是springmvc

**Comment by yhb890430** [comment]
格式就是url=XXX
