### ISSUE TITLE
format DB2建表语句报错

### ISSUE THREAD

**Issue by YYYYYYYYYYYYYYYY** [alibaba/druid#2079]
SQL：
CREATE TABLE MK.M_DM_BASE_CHARGE_TMP1 
(PROD_ID    BIGINT, 
 ITEM_ID  SMALLINT, 
 CHARGE     BIGINT, 
 PAGES      BIGINT, 
 DURATION   BIGINT, 
 BILLING_DURATION BIGINT 
) DATA CAPTURE NONE   
IN MK_APP_TEMP   
INDEX IN WH_INDEX1   
PARTITIONING KEY    
(PROD_ID    
) USING HASHING

错误：
syntax error, error in :'P   INDEX IN WH_INDEX1   PARTITIO', expect INDEX, actual INDEX pos 216, line 9, column 16, token INDEX

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.6
问题已修复，请用新版本
