### ISSUE TITLE
关于merge into解析的几点需求

### ISSUE THREAD

**Issue by YYYYYYYYYYYYYYYY** [alibaba/druid#2089]
SQL：
MERGE INTO (
	SELECT *
	FROM KPI_M_CW_INCOME_FACT_BAK
	WHERE THE_DATE = '{THISMONTH}'
		AND AREA_LEVEL <= 1
		AND TYPE_ID = '2'
) A
USING (
	SELECT *
	FROM M_HEALTH_APPRAISE_LOAD
	WHERE THE_DATE = TRUNC(SYSDATE)
		AND AREA_LEVEL <= 1
) B ON (A.AREA_ID = B.AREA_ID
AND A.AREA_LEVEL = B.AREA_LEVEL) 
WHEN MATCHED THEN UPDATE SET A.SUM_CHRG_YS = ROUND(B.TOTAL_CHARGE * 1.00 / 10000, 2), A.CHARGE = B.THIS_CHARGE;

比如像这样的SQL，在解析时，into的table解析出来是(com.alibaba.druid.sql.ast.statement.SQLSelect@d25062e)，能不能像using一样将原来的Select语句解析出来

还有一个就是A.SUM_CHRG_YS = ROUND(B.TOTAL_CHARGE * 1.00 / 10000, 2)这个updateSetItem我使用getValue方法获取到的是ROUND(com.alibaba.druid.sql.ast.expr.SQLBinaryOpExpr@4b0a05e0, 2)这样的形式，能不能将com.alibaba.druid.sql.ast.expr.SQLBinaryOpExpr@4b0a05e0原本的内容解析出来，这个问题之前是issue #1970，您close掉了，今天发现还是无法将原本的内容解析出来。

**Comment by wenshao** [comment]
update语句的sql样本提供一下

**Comment by YYYYYYYYYYYYYYYY** [comment]
@wenshao 就是上面的merge into SQL语句里面的update内容：WHEN MATCHED THEN UPDATE SET A.SUM_CHRG_YS = ROUND(B.TOTAL_CHARGE * 1.00 / 10000, 2), A.CHARGE = B.THIS_CHARGE

**Comment by wenshao** [comment]
已经支持，如果着急自行编译一个版本试试看

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.6
问题已修复，请用新版本
