### ISSUE TITLE
监控页面部署到阿里云之后访问不了

### ISSUE THREAD

**Issue by a18516614541** [alibaba/druid#2092]
我在本地运行可以访问到，部署在阿里云上之后无法访问了。其余接口访问都正常，后台filter过滤到了/druid请求，没有报错。页面返回Sorry, you are not permitted to view this page.

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatViewServlet%E9%85%8D%E7%BD%AE
是配置IP控制的原因吧？

**Comment by a18516614541** [comment]
是的。。。强烈要求这个加个log，不然一脸蒙蔽

**Comment by a18516614541** [comment]
强烈要求这个加个log

**Comment by diaodiaofly** [comment]
allow和deny都没有任何指定ip  为何也出现本地能访问  部署服务器上就出现
Sorry, you are not permitted to view this page.

**Comment by hipzhang** [comment]
@diaodiaofly 怎么解决的，我也是本地可以，服务器不行
