### ISSUE TITLE
sql统计重复

### ISSUE THREAD

**Issue by Bobi-zhou** [alibaba/druid#2105]
在批量更新时数据量不一样导致druid认为是两条不同的sql：

如

update table set field=?;update table set field=?;
与
update table set field=?;update table set field=?;update table set field=?;

druid会记录两条这样的信息。。

**Comment by wenshao** [comment]
懂了，这个需要合并，会尽快加上哈，谢谢反馈

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.6
问题已修复，请用新版本
