### ISSUE TITLE
系统由JNDI+C3P0替换到Druid后zeroDateTimeBehavior=convertToNull失效

### ISSUE THREAD

**Issue by yansheng723** [alibaba/druid#2111]
如题, 现有系统为JNDI+C3P0+Mysql-connector建立的连接池配置.后端架构为spring2+hibernate.
由于连接地址较多, 为了提高运维效率,所以对这块进行了改造.
但是这样用了以后zeroDateTimeBehavior=convertToNull失效
改造后配置如下:
springContext-jdbc.xml

	<bean id="xxxDruidDataSourceWrapper" class="com.xes.global.routingDataSource.XXXDruidDataSourceWrapper"
        init-method="init" destroy-method="close">
    <property name="cityCodeArrayStr" value="${dataSource.cityCode}"/>
    <property name="defaultCityCodeStr" value="${dataSource.default.CityCode}"/>

    <property name="initialSize" value="${druid.initialSize}"/>
    <property name="minIdle" value="${druid.minIdle}"/>
    <property name="maxActive" value="${druid.maxActive}"/>
    <property name="maxWait" value="${druid.maxWait}"/>
    <property name="timeBetweenEvictionRunsMillis" value="${druid.timeBetweenEvictionRunsMillis}"/>
    <property name="minEvictableIdleTimeMillis" value="${druid.minEvictableIdleTimeMillis}"/>
    <property name="validationQuery" value="${druid.validationQuery}"/>
    <property name="testWhileIdle" value="${druid.testWhileIdle}"/>
    <property name="testOnBorrow" value="${druid.testOnBorrow}"/>
    <property name="testOnReturn" value="${druid.testOnReturn}"/>
    <property name="poolPreparedStatements" value="${druid.poolPreparedStatements}"/>
    <property name="maxPoolPreparedStatementPerConnectionSize" value="${druid.maxPoolPreparedStatementPerConnectionSize}"/>
    <property name="filters" value="${druid.filters}"/>

    <property name="driverSuffix" value="%s.jdbc.driverClass"/>
    <property name="urlSuffix" value="%s.jdbc.jdbcUrl"/>
    <property name="userSuffix" value="%s.jdbc.user"/>
    <property name="passwordSuffix" value="%s.jdbc.password"/>

    <property name="configs" ref="propertyConfigurer"/>
	</bean>
	<bean name="dataSourcesMaps" factory-bean="xxxDruidDataSourceWrapper" factory-method="build"/>
	
	<bean name="defaultDataSources" factory-bean="xxxDruidDataSourceWrapper" factory-method="getDefault"/>

	<bean id="dataSource" class="com.xes.global.routingDataSource.DynamicDataSource">
    <property name="targetDataSources" ref="dataSourcesMaps">
    </property>
    <property name="defaultTargetDataSource" ref="defaultDataSources"/>
	</bean>

jdbc.properties

	druid.initialSize=15
	druid.minIdle=15
	druid.maxIdle=100
	druid.maxActive=100
	
	druid.maxWait=60000
	druid.timeBetweenEvictionRunsMillis=60000
	druid.minEvictableIdleTimeMillis=300000
	
	druid.validationQuery=SELECT 'x'
	#druid.validationQuery=
	druid.testWhileIdle=true
	druid.testOnBorrow=false
	druid.testOnReturn=false
	
	druid.poolPreparedStatements=true
	druid.maxPoolPreparedStatementPerConnectionSize=20
	
	druid.filters=stat,log4j
	
	dataSource.cityCode=master010|slave010|
	dataSource.default.CityCode=master010
	
	##master010
	master010.jdbc.driverClass=com.mysql.jdbc.Driver
	master010.jdbc.jdbcUrl=jdbc:mysql://x.x.x.x:3306/beijing_xxgl?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
	master010.jdbc.user=xxx
	master010.jdbc.password=xxx

封装的代码如下
	@Data
	@Slf4j
	public class XXXDruidDataSourceWrapper {
	
	    private Logger log = LoggerFactory.getLogger(XESDruidDataSourceWrapper.class);
	
	    /**
	     * 管道分隔符
	     */
	    private static final String PIPE ="|";
	
	    /**
	     * Druid配置
	     */
	    private int initialSize;
	    private int minIdle;
	    private int maxActive;
	    private long maxWait;
	    private long timeBetweenEvictionRunsMillis;
	    private long minEvictableIdleTimeMillis;
	    private String validationQuery;
	    private boolean testWhileIdle;
	    private boolean testOnBorrow;
	    private boolean testOnReturn;
	    private boolean poolPreparedStatements;
	    private int maxPoolPreparedStatementPerConnectionSize;
	    private String filters;
	
	    /**
	     * 数据库配置后缀
	     */
	    private String driverSuffix;
	    private String urlSuffix;
	    private String userSuffix;
	    private String passwordSuffix;
	
	    private List<DruidDataSource> dataSourceList = Lists.newArrayList();
	
	    /**
	     * 配置文件的|风格连接池名称
	     */
	    private String cityCodeArrayStr;
	
	    /**
	     * 缺省CityCode连接池
	     */
	    private String defaultCityCodeStr;
	
	    private DruidDataSource defaultDruidDataSource;
	
	    private XXXPropertyPlaceholderConfigurer configs;
	
	    public Map<String, Object> build() throws SQLException {
	        Iterable<String> cityCodeArray = Splitter.on(PIPE)
	                .omitEmptyStrings()
	                .trimResults().split(cityCodeArrayStr);
	        Map<String, Object> dataSourceMap = Maps.newHashMap();
	            for (String cityCode : cityCodeArray) {
	                DruidDataSource druidDataSource = new DruidDataSource();
	                String driverClass = configs.getProperty(String.format(driverSuffix, cityCode));
	                druidDataSource.setDriverClassName(driverClass);
	                String jdbcUrl = configs.getProperty(String.format(urlSuffix, cityCode));
	                druidDataSource.setUrl(jdbcUrl);
	                String user = configs.getProperty(String.format(userSuffix, cityCode));
	                druidDataSource.setUsername(user);
	                String password = configs.getProperty(String.format(passwordSuffix, cityCode));
	                druidDataSource.setPassword(password);
	
	            /* 配置初始化大小、最小、最大 */
	                druidDataSource.setInitialSize(initialSize);
	                druidDataSource.setMinIdle(minIdle);
	                druidDataSource.setMaxActive(maxActive);
	
	            /*配置获取连接等待超时的时间*/
	                druidDataSource.setMaxWait(maxWait);
	            /*配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒*/
	                druidDataSource.setTimeBetweenEvictionRunsMillis(timeBetweenEvictionRunsMillis);
	
	            /*配置一个连接在池中最小生存的时间，单位是毫秒*/
	                druidDataSource.setMinEvictableIdleTimeMillis(minEvictableIdleTimeMillis);
	
	                druidDataSource.setValidationQuery(validationQuery);
	                druidDataSource.setTestWhileIdle(testWhileIdle);
	                druidDataSource.setTestOnBorrow(testOnBorrow);
	                druidDataSource.setTestOnReturn(testOnReturn);
	
	            /*
	               打开PSCache，并且指定每个连接上PSCache的大小  如果用Oracle，
	               则把poolPreparedStatements配置为true，mysql可以配置为false。
	            */
	                druidDataSource.setPoolPreparedStatements(poolPreparedStatements);
	                druidDataSource.setMaxPoolPreparedStatementPerConnectionSize(maxPoolPreparedStatementPerConnectionSize);
	
	            /*配置监控统计拦截的filters*/
	                druidDataSource.setFilters(filters);
	
	                log.info("Create DateSource. The source name is {}" , cityCode);
	                // 缺省连接池
	                if (defaultCityCodeStr.equals(cityCode)) {
	                    this.defaultDruidDataSource = druidDataSource;
	                }
	                dataSourceMap.put(cityCode, druidDataSource);
	                dataSourceList.add(druidDataSource);
	            }
	            log.info("The default datasource is {}", defaultCityCodeStr);
	        return dataSourceMap;
	    }
	
	    public void init() throws SQLException {
	        log.info("Initializing DateSource poll.");
	        for (DruidDataSource druidDataSource : dataSourceList) {
	            druidDataSource.init();
	        }
	        log.info("Initializing DateSource poll success.");
	    }
	
	    public void close() {
	        log.info("Closing dateSource poll.");
	        for (DruidDataSource druidDataSource : dataSourceList) {
	            druidDataSource.close();
	        }
	        log.info("Closing DateSource success.");
	    }
	}

**Comment by wenshao** [comment]
看不出什么原因，这个是url的配置，感觉和连接池无关的

**Comment by yansheng723** [comment]
初步排查可能是因为init和build顺序不一致导致的.但是也引入了init初始化慢的问题,连接url太多

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE
asyncInit是1.1.4中新增加的配置，如果有initialSize数量较多时，打开会加快应用启动时间。看是否能满足你的需求

**Comment by yansheng723** [comment]
找到问题原因了&amp;这个配置有问题.
