### ISSUE TITLE
关于SQLObject对象的clone能否带上attributes？

### ISSUE THREAD

**Issue by TimeEraser** [alibaba/druid#2114]
在实践过程中涉及到了SQLObject的克隆，但是克隆出来的SQLObject没有带上attribute的信息比如:
    SQLVariantRefExpr中的clone方法：
            SQLVariantRefExpr var =  new SQLVariantRefExpr(name, global);
            var.index = index;
            return var;
Druid能否将clone的过程中带上attribute的信息。

**Comment by wenshao** [comment]
只能做部分对象，因为太多了，不好做，你希望支持哪些对象呢？

**Comment by TimeEraser** [comment]
不好意思，最近比较忙没上来看。目前最主要的是SQLVariantRefExpr这个类，因为这个在分库分表的情况下我们要做拆分。

**Comment by TimeEraser** [comment]
另外想问个问题，关于SQL解析这一块
select * from a where id in (1, 2,3) 能归一化成select * from a where id in (?);
select * from a where (id,userId) in ((1,2), (2,3),(3,4)) 不能能归一化成
select * from a where id in ((?,?)) 或者select * from a where id in (?)

**Comment by wenshao** [comment]
可以的，这个是什么数据库的SQL？能说一下你的公司和应用场景么？

**Comment by TimeEraser** [comment]
我是mgj的数据库中间件这一块的。
这个归一化主要是用来做SQL的拦截、流控和监控用的。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
