### ISSUE TITLE
mysql set session xxxx语句解析会省略session关键字

### ISSUE THREAD

**Issue by sunsun314** [alibaba/druid#2115]
在一般情况下set session xxxx 和set xxxx没有区别，但是如果是在调整事务信息的情况下会有差异   
详情见官方文档Scope of Transaction Characteristics：
https://dev.mysql.com/doc/refman/5.7/en/set-transaction.html   
需要给对应的解析结果增添相应的标识

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.6
问题已修复，请用新版本
