### ISSUE TITLE
SQLSERVER 不能使用MERGE语法

### ISSUE THREAD

**Issue by richwxd** [alibaba/druid#2118]
jdbc方式正常，为什么druid会报错呢
mybatis+druid 1.1.5报错。jdbcTemplate+hikariCP没问题，NaviCat运行没问题。
MERGE INTO tb_device_category t1
USING ( select distinct device_category, factory_id from temp_device where device_category is not null
) t2 
on (t1.name = t2.device_category and t1.factory_id = t2.factory_id)
WHEN NOT MATCHED THEN
    INSERT (name, factory_id) values (t2.device_category, t2.factory_id);

**Comment by wenshao** [comment]
druid什么版本？能否提供完整SQL？

**Comment by richwxd** [comment]
版本1.1.5 SQLSERVER 2014 兼容模式 SQL SERVER 2012
MERGE INTO tb_device_category t1
        USING (
        select distinct device_category, factory_id from temp_changlin_device
        ) t2 on (t1.name = t2.device_category and t1.factory_id = t2.factory_id and t2.device_category is not null)
        WHEN NOT MATCHED THEN
          INSERT (name, factory_id) values (t2.device_category, t2.factory_id);

在navicat 上运行没问题。hikaricp+jdbctemplate方式没问题。druid+mybatis运行，报错。DruidParseException

**Comment by richwxd** [comment]
When will this new release available? 👍

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.6
问题已修复，请用新版本
