### ISSUE TITLE
ConfigFilter问题

### ISSUE THREAD

**Issue by miaoyinjun** [alibaba/druid#2120]
使用druid-spring-boot-starter
密码加密
1.spring.datasource.druid.filter.config.enabled = true不起作用，必须使用spring.datasource.druid.filters = config，才能支持spring.datasource.druid.connection-properties=config.decrypt=true;config.decrypt.key=###

**Comment by lihengming** [comment]
不应该呀，我试过的没问题，你把配置文件和使用的版本发一下。

**Comment by miaoyinjun** [comment]
@lihengming 谢谢，本地配置没有问题，配置文件放在apollo上就有问题
