### ISSUE TITLE
ERRORpos 97, GT state

### ISSUE THREAD

**Issue by maoguoxu** [alibaba/druid#2141]
2017-11-29 10:46:00,743 ERROR [com.alibaba.druid.filter.stat.StatFilter] - merge sql error, dbType sqlserver, sql : select count(1) From wms.pack_box_material a,wms.pack_box b where a.pb_id=b.pb_id 
and b.state< >2
and not exists(  select 1 From wms.box_pack_detail c where c.pm_id=a.pm_id )
and b.box_cid=?
com.alibaba.druid.sql.parser.ParserException: ERRORpos 97, GT state

语句没问题  为啥报这个错?

**Comment by wenshao** [comment]
```sql
b.state< >2
```
这个是合法的么？

**Comment by maoguoxu** [comment]
b.state<>2  是合同法的的  在sql  ide可执行的

**Comment by maoguoxu** [comment]
[SQL]select count(1) From wms.pack_box_material a,wms.pack_box b where a.pb_id=b.pb_id
and b.state< >2
and not exists( select 1 From wms.box_pack_detail c where c.pm_id=a.pm_id )

受影响的行: 0
时间: 0.009s

**Comment by wenshao** [comment]
这个是什么数据库？

**Comment by zmwxiaoming** [comment]
<>尖括号中间应该没有空格

**Comment by maoguoxu** [comment]
@wenshao sql2012

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
