### ISSUE TITLE
ODPS（MaxCompute）2.0 复杂数据类型不支持

### ISSUE THREAD

**Issue by chenfeicqq** [alibaba/druid#2145]
参见：
https://help.aliyun.com/document_detail/27821.html?spm=5176.doc27808.2.6.KGnrPC

![image](https://user-images.githubusercontent.com/2122266/33411972-b2e96aee-d5c3-11e7-83f3-ffc35927db5b.png)

**Comment by chenfeicqq** [comment]
c_names array <string> comment '城市名称列表',

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.6
问题已修复，请用新版本
