### ISSUE TITLE
why  XADataSource in druid only support mysql driver 5?

### ISSUE THREAD

**Issue by mathcad** [alibaba/druid#2146]
I use JTA with Atomikos + Druid + mysql connector java 6, but get a error in runtime, the log indicates that druid can not get a XAConnection, but getConnection works well.

I read the source code, in MySqlUtils.class, I found  the method 'createXAConnection' only support mysql driver 5, switch to5, it works.  How do you think?
![y eekikxl y8l8hd_wqnct](https://user-images.githubusercontent.com/11826915/33417677-63d633c8-d5dd-11e7-8ac6-e461220b588e.png)

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.6
bug fixed, please use new version.
