### ISSUE TITLE
Springboot 配置监控无效

### ISSUE THREAD

**Issue by ZhouZiHe** [alibaba/druid#2161]
我的配置是这个样子的,但是在监控上面没有起到作用,sql和web的应用统计都没有

   datasource:
        url: xxxxx
        username: xxxxx
        password: xxxxx
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            db-type: com.alibaba.druid.pool.DruidDataSource
            initial-size: 5
            max-active: 50
            min-idle: 5
            max-wait: 10
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            validation-query: select 'x'
            validation-query-timeout: 3000
            test-on-borrow: true
            test-on-return: false
            test-while-idle: true
            time-between-eviction-runs-millis: 60000
            filters: stat,wall,slf4jLog
            web-stat-filter.enabled: true 
            web-stat-filter.url-pattern: /druid/*
            web-stat-filter.exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
            web-stat-filter.session-stat-enable: true
            web-stat-filter.session-stat-max-count: 1000
            web-stat-filter.principal-session-name: namelist-admin-session
            web-stat-filter.principal-cookie-name: namelist-admin-cookie
            web-stat-filter.profile-enable: true
            stat-view-servlet.enabled: true #是否启用StatViewServlet默认值true
            stat-view-servlet.url-pattern: /druid/*
            stat-view-servlet.reset-enable: true
            stat-view-servlet.login-username: admin
            stat-view-servlet.login-password: admin
            stat-view-servlet.allow: 172.30.156.86
            stat-view-servlet.deny: 172.30.156.8
            aop-patterns: com.ifeng.zack.*.service.*,com.ifeng.zack.*.dao.*
    aop:
      proxy-target-class: true

**Comment by ZhouZiHe** [comment]
package com.ifeng.zack.common.config;

import org.apache.ibatis.session.SqlSessionFactory;
import org.mybatis.spring.SqlSessionFactoryBean;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.jdbc.DataSourceBuilder;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;

import javax.sql.DataSource;

@Configuration
@MapperScan(basePackages = "com.ifeng.zack.*.dao", sqlSessionFactoryRef = "SqlSessionFactory")
public class DataSourceConfig {

    @Primary
    @Bean(name = "DataSource")
    @ConfigurationProperties(prefix = "spring.datasource")
    public DataSource DataSource() {
        return DataSourceBuilder.create().build();
    }

    @Bean(name = "TransactionManager")
    @Primary
    public DataSourceTransactionManager dbTransactionManager() {
        return new DataSourceTransactionManager(DataSource());
    }

    @Bean(name = "SqlSessionFactory")
    @Primary
    public SqlSessionFactory dbSqlSessionFactory(@Qualifier("DataSource") DataSource DataSource) throws Exception {
        final SqlSessionFactoryBean sessionFactory = new SqlSessionFactoryBean();
        sessionFactory.setDataSource(DataSource);
        return sessionFactory.getObject();
    }

}

**Comment by ZhouZiHe** [comment]
我配置的datasource 是这个样子的

**Comment by zmwxiaoming** [comment]
druid也没有一个完整的支持springboot的例子

**Comment by andrewchen1** [comment]
web-stat-filter.url-pattern: /druid/*
stat-view-servlet.url-pattern: /druid/
这两个的配置是不是有可以考量一下
web-stat-filter.url-pattern 的地址是不是要被filter过滤的地址 是不是可以配置成 /
stat-view-servlet.url-pattern 是要被web ui 页面的mapper 地址 是不是可以配置成/druid/*  小萌新也不是很懂 ( 逃...

**Comment by zhaozhiguang** [comment]
@Primary
	@Bean
	@ConfigurationProperties(prefix = "spring.datasource")
	public DataSource DataSource() {
		return new DruidDataSource();
	}
