### ISSUE TITLE
换成druid之后，启动tomcat 报错 DataSource不能初始化；

### ISSUE THREAD

**Issue by yuanyp** [alibaba/druid#2164]
错误日志：
![image](https://user-images.githubusercontent.com/6846447/33656051-e3e7b8a8-daaf-11e7-8f22-099bc8f3c223.png)
原配置：
![image](https://user-images.githubusercontent.com/6846447/33656078-f5608a38-daaf-11e7-99d8-a48c9e5ccc59.png)
改成druid之后的配置：
![image](https://user-images.githubusercontent.com/6846447/33656090-fd88f6b4-daaf-11e7-92fa-8dc223a0166c.png)

什么原因？？

**Comment by winters1224** [comment]
查询超时值 -1 无效

有个参数值不合法吧

**Comment by CrackRen** [comment]
我这里也是，同一个工程，在其他几个服务器没碰到过，但是在如下环境里
系统：Windows2003 SP2 32位
JDK: jdk1.8.0_151
Tomcat : 8.5.24
SqlServer: 2008 R2
druid: 1.1.4,1.1.6都试了
运行时也会提示 查询超时值 -1 无效
![tim 20171208095456](https://user-images.githubusercontent.com/2989820/33747423-dcec52e4-dbfd-11e7-9621-b3b9f42ec044.png)

**Comment by CrackRen** [comment]
跟着源代码看 发现 要配置validationQueryTimeout别叫他等于-1就好了，但是为什么在其他服务器上好着呢

**Comment by wenshao** [comment]
很久很久以前有些版本是不校验的，是不是版本不一样

**Comment by yuanyp** [comment]
@CrackRen 怎么解决呢？我把validationQueryTimeout这个配置成3000然后 就这样了看下面图片；
![image](https://user-images.githubusercontent.com/6846447/33812697-2b11ad1c-de5a-11e7-9f3c-8409e441f41b.png)

卡着不动了；

**Comment by yuanyp** [comment]
是不是sqlserver不兼容啊

**Comment by yuanyp** [comment]
已经搞定了，
配置如下
![image](https://user-images.githubusercontent.com/6846447/33813361-32759b8c-de5e-11e7-962d-f9ee89217d50.png)
