### ISSUE TITLE
如何测试自定义的配置是否成功

### ISSUE THREAD

**Issue by git-stf-01** [alibaba/druid#2166]
请问我在springboot项目中引入了Druid，如何确认我自定义的配置是否成功？？
例如，最大最小等配置项，为什么我在监控页面看到的是这样的
![druid](https://user-images.githubusercontent.com/30710495/33696030-47d138f4-db3b-11e7-8f8e-64b964ff0c82.png)

###下面是我的properties文件（我不知道我的配置项是否成功应用了）：
#mybatis配置
mybatis.typeAliasesPackage=com.finet.boot.sbmd.domain
mybatis.mapperLocations=classpath:mapper/*.xml

#指定使用Druid连接池
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource

#数据库基本信息配置
spring.datasource.url=jdbc:mysql://192.168.10.16:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

#连接池配置信息
spring.datasource.druid.initial-size=1
spring.datasource.druid.max-active=100
spring.datasource.druid.min-idle=1
spring.datasource.druid.max-wait=60000
spring.datasource.druid.test-on-borrow=false
spring.datasource.druid.test-on-return=false
spring.datasource.druid.test-while-idle=true
spring.datasource.druid.min-evictable-idle-time-millis=300000

#打开PSCache，并且指定每个连接上PSCache的大小
spring.datasource.druid.pool-prepared-statements=true
spring.datasource.druid.max-pool-prepared-statement-per-connection-size=20

#配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
spring.datasource.druid.filters=stat,wall,logback
#通过connectProperties属性来打开mergeSql功能；慢SQL记录
spring.datasource.druid.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#合并多个DruidDataSource的监控数据
#spring.datasource.druid.useGlobalDataSourceStat=true

**Comment by git-stf-01** [comment]
果然没用到我的配置。。因为我加的依赖是druid，并不是druid-spring-boot-starter

**Comment by taotao0325** [comment]
> 果然没用到我的配置。。因为我加的依赖是druid，并不是druid-spring-boot-starter

你的什么原因？
