### ISSUE TITLE
mysql sql解析error，测试从1.1.3至1.1.6都有该问题，1.1.3之前版本正常

### ISSUE THREAD

**Issue by xiaoshuaishuai** [alibaba/druid#2167]
目前项目中使用的是1.0.29的版本，近期打算升级到最新版本1.1.6。
升级之后启动个别应用出现。
异常信息：

[ERROR] 2017-12-07 10:23:18,219 --main-- [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] sql injection violation, syntax error: syntax error, error in :'pe=? and cfgdatasou0_.module_name=?', expect AND, actual AND pos 790, line 1, column 787, token AND : select *(这里字段*代替了) from TABLENAME cfgdatasou0_ where cfgdatasou0_.type=? and cfgdatasou0_.module_name=? and cfgdatasou0_.node_type=? or cfgdatasou0_.type=? and cfgdatasou0_.module_name=? and cfgdatasou0_.node_type=? or cfgdatasou0_.type=? and cfgdatasou0_.module_name=? and cfgdatasou0_.node_type=? 

Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'pe=? and cfgdatasou0_.module_name=?', expect AND, actual AND pos 790, line 1, column 787, token AND
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:284)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:421)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:81)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:624)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:578)
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:785)
	... 59 common frames omitted

但是有部分应用启动正常，然后我对比了执行的sql发现在解析select *(这里字段*代替了) from TABLENAME cfgdatasou0_ where cfgdatasou0_.type=? and cfgdatasou0_.module_name=? and cfgdatasou0_.node_type=? or cfgdatasou0_.type=? and cfgdatasou0_.module_name=? and cfgdatasou0_.node_type=?
是正常的，对比发现少了一个or条件or cfgdatasou0_.type=? and cfgdatasou0_.module_name=? and cfgdatasou0_.node_type=? 

也就是说当我是where条件为where cfgdatasou0_.type=? and cfgdatasou0_.module_name=? and cfgdatasou0_.node_type=? or cfgdatasou0_.type=? and cfgdatasou0_.module_name=? and cfgdatasou0_.node_type=? or cfgdatasou0_.type=? and cfgdatasou0_.module_name=? and cfgdatasou0_.node_type=?  出错，我试了很多版本，在1.1.3之前的版本是正常的，1.1.3以后的版本都有这个问题，包括最新版本1.1.6。

一路跟了下dubug源码出现问题的在com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.        parseWhere(queryBlock);这一句，解析两个or条件正常，
WHERE cfgdatasou0_.type = ?
	AND cfgdatasou0_.module_name = ?
	AND cfgdatasou0_.node_type = ?
	OR cfgdatasou0_.type = ?
	AND cfgdatasou0_.module_name = ?
	AND cfgdatasou0_.node_type = ?，并且**lexer.token=EOF**结束状态是正常的。

异常情况下
(cfgdatasou0_.type = ?
	AND cfgdatasou0_.module_name = ?
	AND cfgdatasou0_.node_type = ?)
OR (cfgdatasou0_.type = ?
	AND cfgdatasou0_.module_name = ?
	AND cfgdatasou0_.node_type = ?)
OR cfgdatasou0_.type = ?  成这个样子了？？？？不全。。。并且**lexer.token=AND**

 if (parseStatementListDialect(statementList)) 这句返回false，接下来执行了 printError(lexer.token);丢出来了上面的异常。

相同的情况下，我用1.1.3之前版本是正常的。

**Comment by saber570** [comment]
我也遇到了，求官方解决。

**Comment by wenshao** [comment]
我添加了testcase，问题没有重现，比较奇怪了

**Comment by wenshao** [comment]
问题重现并解决

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本

**Comment by xiaoshuaishuai** [comment]
赞一个、问题已解决
