### ISSUE TITLE
关于druid连接池中拿不到连接的问题

### ISSUE THREAD

**Issue by ChangFeng2015** [alibaba/druid#2168]
我这边项目使用了druid作为连接池，但是时常出现connection holder is null，除了这个还有Lock wait timeout exceeded; try restarting transaction，我想分析一下第一个报错是不是由第二种第二种报错引起的，想问您，druid中的连接在产生锁等待超时后，对该连接有没有做相应的回收处理，没有回收连接的话，很可能导致过多的connection被占用

**Comment by ChangFeng2015** [comment]
不好意思，刚仔细看了下源码，是对当前的连接进行了释放
![image](https://user-images.githubusercontent.com/11408764/33702612-5584a80e-db5f-11e7-8101-cb80a74f4653.png)
![image](https://user-images.githubusercontent.com/11408764/33702652-89fcf906-db5f-11e7-9700-7b456ea96fa1.png)

**Comment by liuyandeng** [comment]
问题解决了吗
