### ISSUE TITLE
ORA-12592包错误,和ORA-01013 用户请求取消当前操作 问题.

### ISSUE THREAD

**Issue by breakenknife** [alibaba/druid#2175]
如下图.同一个连接,执行两次查询.第一次报"ORA-12592包错误",第二次查询才20毫秒就报
"ORA-01013 用户请求取消当前操作".但是配置的queryTimeout为11秒.持续几次报ORA-01013
后便恢复正常了. 第一个错误DBA估计是数据库bug或防火墙导致,但后面的几次ORA-01013感觉
就不太正常了.
两条都是高频的索引查询,不存在效率问题.这种情况一天大概出现一次.
数据库oracle11,驱动为ojdbc7-10.2.0.4.0. 烦请各位看下是什么原因.
![image](https://user-images.githubusercontent.com/12994391/33754064-94fff7d8-dc25-11e7-829e-1dc1001ec403.png)

**Comment by kenputon1** [comment]
我也遇到了ORA-01013，系统运行一段时间后出现，所有操作报这个错误，必须重启，没找到规律

**Comment by xiaoshitou123** [comment]
我也遇到了ORA-01013，系统运行一段时间后出现，所有操作报这个错误，然后刷新就行了，请求速速提供解决方案

**Comment by majinju** [comment]
是的，请官方关注

**Comment by diedai** [comment]
解决方法：https://juejin.im/post/6844904190263689230

**Comment by chanjarster** [comment]
我也是，似乎和sql频率无关，半夜凌晨业务低峰期也会产生，尝试keepAlive=true，先观察着

**Comment by jiangxinwei2008** [comment]
> 
> 
> 我也是，似乎和sql频率无关，半夜凌晨业务低峰期也会产生，尝试keepAlive=true，先观察着

观察得怎么样了？解决了吗

**Comment by chanjarster** [comment]
> > 我也是，似乎和sql频率无关，半夜凌晨业务低峰期也会产生，尝试keepAlive=true，先观察着
> 
> 观察得怎么样了？解决了吗

没有解决，后来换了Hikari连接池。

**Comment by chanjarster** [comment]
@wenshao 尝试了本楼提供的其他方法，没用。

后来怀疑和PSCache有关，于是关掉了PSCache `maxOpenPreparedStatements=-1`，还是有这个问题。之后换了HikariCP，它不启用PSCache，没有这个问题。所以这个问题似乎和PSCache无关。

**Comment by zhuchaolu** [comment]
官方一直没人重视，现在项目经常报ORA-01013问题

**Comment by itaot** [comment]
遇到过，官方能协助解决下吗？ @wenshao

**Comment by itaot** [comment]
后边发现更换oracle jdbc驱动可以解决此问题，数据库版本是11.2.0.4.0，jdbc驱动本来是ojdbc7的，更换为了ojdbc8-12.2.0.1.0

**Comment by itaot** [comment]
解决方案：升级oracle jdbc驱动包
https://editor.csdn.net/md/?articleId=115979336

**Comment by zengxp0605** [comment]
> 解决方案：升级oracle jdbc驱动包 https://editor.csdn.net/md/?articleId=115979336

大佬贴的是编辑地址啊，这个才对
https://blog.csdn.net/itaot/article/details/115979336
