### ISSUE TITLE
建触发器语句报错

### ISSUE THREAD

**Issue by welyss** [alibaba/druid#2183]
错误信息是：【Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'_app`@`%` TRIGGER `xxxxx', expect TRIGGER, actual VARIANT pos 30, line 1, column 27, token VARIANT】
是不是不支持DEFINER子句?

**Comment by wenshao** [comment]
能提供完整SQL么？

**Comment by welyss** [comment]
package druidtest;

import com.alibaba.druid.sql.ast.SQLStatement;
import com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser;
import com.alibaba.druid.sql.dialect.mysql.visitor.MySqlSchemaStatVisitor;

public class DruidTest {
	public static void main(String[] args) {
		MySqlStatementParser mssp = new MySqlStatementParser(
				" CREATE DEFINER=`test_app`@`%` TRIGGER `trg_xxx_update` AFTER UPDATE ON `txxx` FOR EACH ROW begin"
						+ "\ninsert into record_history_log (object, identity, action) values('txxx', new.object_id, 'UPDATE');"
						+ "\ninsert into record_history_log_sim (object, identity, action) values('txxx', new.object_id, 'UPDATE');end"
//				"create table aa (id int primary key)"
						);
		SQLStatement stmt = mssp.parseStatement();
		MySqlSchemaStatVisitor visitor = new MySqlSchemaStatVisitor();
		stmt.accept(visitor);
		System.out.println(visitor.getFeatures());
	}
}

**Comment by welyss** [comment]
`package druidtest;

import com.alibaba.druid.sql.ast.SQLStatement;
import com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser;
import com.alibaba.druid.sql.dialect.mysql.visitor.MySqlSchemaStatVisitor;

public class DruidTest {
	public static void main(String[] args) {
		MySqlStatementParser mssp = new MySqlStatementParser(
				" CREATE DEFINER=\`test_app\`\@\`%\` TRIGGER \`trg_xxx_update\` AFTER UPDATE ON \`txxx\` FOR EACH ROW begin"
						+ "\ninsert into record_history_log (object, identity, action) values('txxx', new.object_id, 'UPDATE');"
						+ "\ninsert into record_history_log_sim (object, identity, action) values('txxx', new.object_id, 'UPDATE');end"
//				"create table aa (id int primary key)"
						);
		SQLStatement stmt = mssp.parseStatement();
		MySqlSchemaStatVisitor visitor = new MySqlSchemaStatVisitor();
		stmt.accept(visitor);
		System.out.println(visitor.getFeatures());
	}
}
`
