### ISSUE TITLE
SQLUtils.toStatementList 解析 CREATE INDEX LOCAL ONLINE失败

### ISSUE THREAD

**Issue by dsmicoo** [alibaba/druid#2194]
SQLUtils.toStatementList 解析create index idx_id on t2(id) local online; 时会将此语句解析成"create index idx_id on t2(id) local" 和 "online" 两个语句 导致执行失败

**Comment by wenshao** [comment]
什么数据库类型?

**Comment by tangczc** [comment]
。。



Sent from my Mi phone
On 温绍 <notifications@github.com>, Dec 15, 2017 1:08 PM wrote:

什么数据库类型?

**Comment by dsmicoo** [comment]
oracle数据库
druid版本1.1.6

**Comment by JohnCailj** [comment]
你的数据库什么版本？ oracle 10g 不支持这个语法；
错误：`[72000][14016] ORA-14016: underlying table of a LOCAL partitioned index must be partitioned`
10g 语法文档：https://docs.oracle.com/cd/B19306_01/server.102/b14200/statements_5010.htm#i2125897

**Comment by JohnCailj** [comment]
你的数据库什么版本？ oracle 10g 不支持这个语法；
10g 语法文档：https://docs.oracle.com/cd/B19306_01/server.102/b14200/statements_5010.htm#i2125897

**Comment by dsmicoo** [comment]
11G的

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
