### ISSUE TITLE
MATERIALIZED VIEW无法解析

### ISSUE THREAD

**Issue by kizimini** [alibaba/druid#2211]
SQLUtils.parseStatements("DROP MATERIALIZED VIEW ATOM_MVIEW.NONAUTO_CLAIM_FOLDER_T;", "oracle");

Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: TODO : pos 17, line 1, column 5, token IDENTIFIER MATERIALIZED

**Comment by wenshao** [comment]
什么版本？什么数据库？能否提供完整SQL

**Comment by kizimini** [comment]
@wenshao 
druid版本: 1.1.6
数据库: oracle
脚本: 
DROP MATERIALIZED VIEW ATOM_MVIEW.NONAUTO_CLAIM_FOLDER_T;
--create materualized_view
CREATE MATERIALIZED VIEW ATOM_MVIEW.NONAUTO_CLAIM_FOLDER_T
PARTITION BY RANGE (BRANCH_COMPANY_CODE)
(  
  PARTITION P1010100 VALUES LESS THAN ('1020100')
    LOGGING
    NOCOMPRESS ,  
  PARTITION P1020100 VALUES LESS THAN ('1030100')
    LOGGING
    NOCOMPRESS ,  
  PARTITION P7040100 VALUES LESS THAN ('7050100')
    LOGGING
    NOCOMPRESS ,  
  PARTITION P7050100 VALUES LESS THAN ('7060100')
    LOGGING
    NOCOMPRESS ,  
  PARTITION P7060100 VALUES LESS THAN (MAXVALUE)
    LOGGING
    NOCOMPRESS
)
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD DEFERRED
REFRESH FAST ON DEMAND
WITH ROWID
AS SELECT * FROM atom.NONAUTO_CLAIM_FOLDER_T@IDS_44;

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
