### ISSUE TITLE
使用Druid 查询mysql字段为time的问题

### ISSUE THREAD

**Issue by xielaixiaohun** [alibaba/druid#2213]
环境：springboot
 <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>6.0.6</version>
        </dependency>

 <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
            <version>1.1.6</version>
        </dependency>

问题：mysql表的字段类型为：time，实体为LocalTime，表里字段的值为00:00:00查询出来的实体为14:00
23:59:59查询出来的实体为13:59:59，换成tomcat-jdbc查询出来就是正确的。
是Druid的时区的问题吗？有没有什么解决办法呢

**Comment by xielaixiaohun** [comment]
测过了，只要是time类型的字段，实体使用LocalTime，查询出来的时间会比真实时间早10小时

**Comment by swelltt0576** [comment]
肯定是你的时区设置问题。你需要从自己的时区设置上来解决问题。

**Comment by xielaixiaohun** [comment]
@swelltt0576 使用tomcat-jdbc查询出来就是正确的

**Comment by xielaixiaohun** [comment]
在URL后面加上东八区就可以了：&serverTimezone=GMT%2B8
