### ISSUE TITLE
升级到 druid-1.1.6 后 sqlserver 在 validateConnection 时报错

### ISSUE THREAD

**Issue by JaynLau** [alibaba/druid#2217]
升级到 druid-1.1.6 后报错：
java.sql.SQLException: The setQueryTimeout method requires a parameter value >= 0.
mssql-jdbc 和 jtds 驱动均报错，没有配置 validationQueryTimeout，但是在 druid-1.1.5 中没有问题

**Comment by dtype** [comment]
这边也报错了sql server

**Comment by wuyan2018** [comment]
spring boot 1.5.9 中使用sql server 连接根本就起不来，好像druid 1.1.6 对于sql server 根本就没测试啊

**Comment by wuyan2018** [comment]
会循环不同报错：16:53:39.813 [Druid-ConnectionPool-Create-2032399795] ERROR c.alibaba.druid.pool.DruidDataSource - create connection SQLException, url: jdbc:sqlserver://localhost:1433;integratedSecurity=true;databaseName=checkinginMS, errorCode 0, state null

**Comment by cena009** [comment]
是的，同样报错

**Comment by yangchunping1989** [comment]
在spring的datasource配置里加上一个配置就行。

**Comment by JaynLau** [comment]
#2210 1.1.6版本Druid连接MSSQLServer 2008 R2报错The query timeout value -1 is not valid.
fixed [https://github.com/alibaba/druid/releases/tag/1.1.8](url)
