### ISSUE TITLE
数字值超过Long.MAX_VALUE后，druid反向生成SQL时错误

### ISSUE THREAD

**Issue by blueswhisper** [alibaba/druid#2222]
原始SQL: `SELECT a from b where c <> 1  LIMIT 0, 18446744073709551615`
经过druid识别为语法树，然后再遍历语法树生成SQL时变为:
`SELECT a FROM b WHERE c <> 1 LIMIT 0, -1`

复现代码:

```java
String sql = "SELECT a from b where c <> 1  LIMIT 0, 18446744073709551615";
List<SQLStatement> sqlStatements = SQLUtils.parseStatements(sql, JdbcConstants.MYSQL);
StringBuilder sb = new StringBuilder();
MySqlOutputVisitor visitor = new MySqlOutputVisitor(sb);
visitor.setPrettyFormat(false);
sqlStatements.get(0).accept(visitor);
System.out.println(sb);
```
输出结果:
` SELECT a FROM b WHERE c <> 1 LIMIT 0, -1 `

[问题代码](https://github.com/alibaba/druid/blob/master/src/main/java/com/alibaba/druid/sql/visitor/SQLASTOutputVisitor.java#L1317) 调用`x.getNumber().longValue()` 时，如果数字值超过Long.MAX_VALUE将会得到未预期的赋值，而数据库是存在`unsigned bigint`类型的

@wenshao 有空修吗？ 没时间的话，我可以提PR。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.8
问题已修复，请使用新版本
