### ISSUE TITLE
双引号包裹的字符串解析为SQLIdentifierExpr

### ISSUE THREAD

**Issue by lixizhong** [alibaba/druid#2226]
`select * from t where op_date = date_format(DATE_ADD('2017-12-27', Interval -1 year), '%Y-%m-%d 00:00:00') `

如上的sql，用单引号包裹的字符串，生成ast后，被解析为SQLCharExpr，如果改成双引号，则全部识别为SQLIdentifierExpr

使用的druid版本：1.1.6 @wenshao

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
