### ISSUE TITLE
在使用AbstractRoutingDataSource时，Druid的DataSourceStat List只显示第一个DataSource

### ISSUE THREAD

**Issue by yosaku01** [alibaba/druid#2236]
使用Spring的AbstractRoutingDataSource进行数据源动态切换，在targetDataSource中添加了Db1,Db2,Db3三个DruidDataSource类型的数据源，且都已配置对应的Filters，但是在Druid监控画面中DataSourceStat List中只显示Db1的监控信息。

**Comment by yosaku01** [comment]
DataSource的Annotation位置放到接口方法上，没有放到实现类上，现在已经可以显示了。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatFilter
多个数据源，可以参考其中的第6点
