### ISSUE TITLE
SpringBoot2 兼容该提上日程了呀

### ISSUE THREAD

**Issue by Cat7373** [alibaba/druid#2254]
根据[SpringBoot2 里程碑计划](https://github.com/spring-projects/spring-boot/milestones)：
* `2.0.0.RC1`：2018-01-25
* `2.0.0.RC2`：2018-02-08
* `2.0.0.RELEASE`：2018-02-20

大概还有不到 40 天，`SpringBoot2`就要发布正式版了，感觉应该开始准备`SpringBoot2`的兼容了

**Comment by wenshao** [comment]
@lihengming

**Comment by wuyan2018** [comment]
@wenshao  为什么美女提问你回复的这么快呢？哈哈哈。。。。

**Comment by lihengming** [comment]
@Cat7373 在准备，SpringBoot2发布正式版后就会支持的

**Comment by lihengming** [comment]
不过改动有点大，并且要求JDK8，支持2.0后有些东西不兼容1.X，短时间内应该没有公司在生产中使用2.0吧

**Comment by Cat7373** [comment]
然而我们这已经用上了。。

**Comment by lihengming** [comment]
@Cat7373 用在生产了？ 你们公司技术负责人也太胆大了吧 出故障怎么办...

**Comment by perdonare** [comment]
https://spring.io/blog/2018/01/31/spring-boot-2-0-0-rc1-available-now
