### ISSUE TITLE
解析编码异常

### ISSUE THREAD

**Issue by mrxiaoqiang** [alibaba/druid#2255]
在建表时解析
```
CREATE TABLE `f_product` (
  `id` int(200) NOT NULL AUTO_INCREMENT,
 `type` enum('market','land','enterprise') CHARACTER SET utf8 DEFAULT NULL COMMENT 'comment',
 PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1DEFAULT CHARSET=utf8mb4
```
与
修改表
` `type` enum('market','land','enterprise') CHARACTER SET utf8 CHARSET utf8mb4 DEFAULT NULL COMMENT 'comment',`
时报错,估计是在MySqlExprParser 解析中未判断 CHARACTER

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
