### ISSUE TITLE
用druid 1.1.6 跑quartz 之后，整个连接池没什么反应了，然后tomcat卡住

### ISSUE THREAD

**Issue by richwxd** [alibaba/druid#2272]
每天半夜跑quartz的任务，然后早上发现tomcat就卡住了，这时候tomcat的没反应。但是如果做了redis缓存，那么数据能正常显示。这时候必须手工重启 tomcat 服务，才能正常使用。几乎每天如此。
是否quartz和druid联合之后会出这种问题，就是说不支持quartz的任务呢。如果是这样，针对quartz可能必须单独设置连接了。

druid配置：
`druid.maxActive=300
druid.initialSize=1
druid.minIdle=3
druid.maxWait=60000
druid.timeBetweenEvictionRunsMillis=100000
druid.minEvictableIdleTimeMillis=300000
druid.testWhileIdle=true
druid.testOnBorrow=false
druid.testOnReturn=false
druid.removeAbandoned=true
druid.removeAbandonedTimeout=180000
druid.logAbandoned=true
druid.filters=wall,stat,log4j2
druid.dbType=sqlserver
druid.validationQuery=SELECT 1
druid.validationQueryTimeout=30

hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
hibernate.show_sql=false
hibernate.format_sql=false
hibernate.hbm2ddl.auto=update

quartz.driverDelegateClass=org.quartz.impl.jdbcjobstore.MSSQLDelegate`

spring 配置
`<bean id="scheduler" class="org.springframework.scheduling.quartz.SchedulerFactoryBean">
	<property name="dataSource" ref="sataSource"/>
	<property name="transactionManager" ref="transactionManager"/>
	<property name="waitForJobsToCompleteOnShutdown" value="true"/>
	<property name="quartzProperties">
		<props>
			<prop key="org.quartz.scheduler.instanceName">QFS_SCHEDULER</prop>
			<prop key="org.quartz.scheduler.instanceId">AUTO</prop>
			<prop key="org.quartz.jobStore.driverDelegateClass">${quartz.driverDelegateClass}</prop>
			
			<prop key="org.quartz.threadPool.class">org.quartz.simpl.SimpleThreadPool</prop>
			<prop key="org.quartz.threadPool.threadCount">10</prop>
			<prop key="org.quartz.threadPool.threadPriority">5</prop>
			<prop key="org.quartz.jobStore.misfireThreshold">60000</prop>
			<prop key="org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread">true</prop>
			
			<prop key="org.quartz.jobStore.class">org.quartz.impl.jdbcjobstore.JobStoreTX</prop>
			
			<prop key="org.quartz.jobStore.isClustered">true</prop>
			<prop key="org.quartz.jobStore.clusterCheckinInterval">15000</prop>
			<prop key="org.quartz.jobStore.maxMisfiresToHandleAtATime">1</prop>

			<prop key="org.quartz.jobStore.misfireThreshold">12000</prop>
			
			<prop key="org.quartz.jobStore.tablePrefix">QRTZ_</prop>
		</props>
	</property>

	<property name="schedulerName" value="QfsScheduler"/>

	
	<property name="startupDelay" value="30"/>

	<property name="applicationContextSchedulerContextKey" value="applicationContextKey"/>

	
	<property name="overwriteExistingJobs" value="true"/>

	
	<property name="autoStartup" value="true"/>

</bean>`

配置了ehcache
`
<cache name="passwordRetryCache"
	   maxEntriesLocalHeap="2000"
	   timeToIdleSeconds="3600"
	   timeToLiveSeconds="0"
	   overflowToDisk="false">
</cache>

<cache name="sysTokenCache"
	   maxEntriesLocalHeap="3000"
	   maxBytesLocalDisk="10m"
	   memoryStoreEvictionPolicy="LRU"
	   timeToIdleSeconds="120"
	   timeToLiveSeconds="3600"
	   overflowToDisk="true"/>

<cache name="driverTokenCache"
	   maxEntriesLocalHeap="10000"
	   maxBytesLocalDisk="10m"
	   memoryStoreEvictionPolicy="LRU"
	   timeToIdleSeconds="120"
	   timeToLiveSeconds="3600"
	   overflowToDisk="true"/>

<cache name="driverCache"
	   maxEntriesLocalHeap="10000"
	   maxBytesLocalDisk="20m"
	   memoryStoreEvictionPolicy="LRU"
	   timeToIdleSeconds="120"
	   timeToLiveSeconds="3600"
	   overflowToDisk="true"/>

<cache name="factoryCache"
	   maxElementsInMemory="10"
	   maxBytesLocalDisk="2m"
	   memoryStoreEvictionPolicy="LRU"
	   timeToIdleSeconds="3600"
	   timeToLiveSeconds="3600"
	   overflowToDisk="true"
	   statistics="true">
</cache>

<cache name="roleCache"
	   maxElementsInMemory="200"
	   maxBytesLocalDisk="5m"
	   memoryStoreEvictionPolicy="LRU"
	   timeToIdleSeconds="3600"
	   timeToLiveSeconds="3600"
	   overflowToDisk="true"
	   statistics="true">
</cache>`

**Comment by richwxd** [comment]
quartz 调用了存储过程，单线程执行，为什么会卡住所有druid的连接呢。这个是很严重的问题。
现在为了绕过问题，单独为Quartz申请了一个SpringDataSource, 实际上就是一个Connection。自从用了这种方式，服务器再也没有卡住过。

**Comment by richwxd** [comment]
并且druid在执行quartz 的时候经常会报告慢查询警告，即使quartz里面1-2条数据. 数据库SqlServer 2016

**Comment by lijianghu** [comment]
大神，后续如何解决的？一个连接不能回收，会影响其他连接的性能还是在pool里面有死锁，导致竞争失败。

**Comment by richwxd** [comment]
这都很久的版本时候的事了。升级最新版本，如果还不行，就换成HikariCP吧。感觉是Druid再解码SQL的时候操作做多了，导致的问题。功能越少，这方面越不容易出问题。
没有哪种好不好，只有更适合。Druid不适合做调用存储过程。那么只好用hikaricp了。
