### ISSUE TITLE
druid解析SQL中表名的BUG

### ISSUE THREAD

**Issue by skiof007** [alibaba/druid#2280]
SELECT
  (SELECT count(*) FROM warn_condition_strategy WHERE user_id = 2510701 AND is_delete = 0 AND strategy_state IN
                                                                                              (1, 2, 6)) AS monitorNum,
  (SELECT count(*) FROM warn_condition_trade_history WHERE user_id = 2510701 AND date_sub(curdate(), INTERVAL 7 DAY) <= date(create_date)) AS recentEntrustNum,
  (SELECT count(*) FROM warn_condition_strategy WHERE user_id = 2510701 AND (is_delete = 1 OR strategy_state IN (3, 4, 5))) AS historyNum,
  (SELECT count(*) FROM warn_condition_trade_history WHERE user_id = 2510701 AND status = 1) AS unreadEntrustNum

这种SQL查询通过druid解析不出表名warn_condition_strategy ,必须改成group by 方式才可解析出来!

**Comment by skiof007** [comment]
感谢!

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
