### ISSUE TITLE
【alter table t_org drop primary key】oracle、db2下解析失败

### ISSUE THREAD

**Issue by wwyu8901** [alibaba/druid#2283]
如题：【alter table t_org drop primary key】这个语句在oracle、db2下解析失败，但很奇怪，mysql却能正常解析
![image](https://user-images.githubusercontent.com/32063277/35373554-f2cdbe20-01d9-11e8-8b54-cf9c5f5796e3.png)

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
