### ISSUE TITLE
db2：select rtrim(current_server), rtrim(current schema), rtrim(current_user) from sysibm.sysdummy1

### ISSUE THREAD

**Issue by xuanang** [alibaba/druid#2295]
主线版本，db2 sql解析失败，执行语句：select rtrim(current_server), rtrim(current schema), rtrim(current_user) from sysibm.sysdummy1
`测试代码：
public void  testRtrim(){
		DB2StatementParser parser = new DB2StatementParser(
				"select rtrim(current_server), rtrim(current schema), rtrim(current_user) from sysibm.sysdummy1");
		List<SQLStatement> statementList = parser.parseStatementList();
		System.out.println(statementList.get(0).toString());
}`
抛出的异常:
![image](https://user-images.githubusercontent.com/26472867/35502967-abd6a0ac-0519-11e8-8749-ef1523988e5d.png)

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
