### ISSUE TITLE
druid数据库密码密文配置报错来着

### ISSUE THREAD

**Issue by singAllSong** [alibaba/druid#2296]
现在项目中出现了很奇怪的一个问题，改成明文连接没问题，用密文后高频爆发access denied的错误，应用重启后大概能扛个把小时，然后就所有涉及数据库操作的接口都报access denied的异常，求解决

**Comment by wenshao** [comment]
现在有什么不支持的？mariadb用mysql就可以了啊？

**Comment by singAllSong** [comment]
真是秒回啊
