### ISSUE TITLE
SQLUtils.formatSQLServer格式化“ALTER TABLE”结果错误

### ISSUE THREAD

**Issue by renxiaoyao** [alibaba/druid#2301]
原始SQL： `ALTER TABLE kpiTarget ADD deleted tinyint DEFAULT 0`
预期格式化后：`ALTER TABLE kpiTarget ADD deleted tinyint DEFAULT 0`
用druid格式化：`ALTER TABLE kpiTarget
	ADD (deleted tinyint DEFAULT 0)` 
已经明显改变了语义。
druid版本：1.1.6 (2018.1.30更新最新版也是一样)

**Comment by renxiaoyao** [comment]
@wenshao

**Comment by renxiaoyao** [comment]
已修复！

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
