### ISSUE TITLE
MYSQL反引号的小问题

### ISSUE THREAD

**Issue by Oloong** [alibaba/druid#2303]
最新版本druid 1.1.6
一个带SCHEMA名和反引号的简单的查询：select * from \`db1\`.\`travelrecord\` a where a.id=1;
解析的表 : {db1\`.\`travelrecord=Select}
这个反引号没处理好呀，只要 schema名字带上"\`"和带上"\`"的表名同时出现,就会解析如上所示问题

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本

**Comment by Oloong** [comment]
你好，更新的很及时，必须赞！发现1.1.7 解析表名直接去除了schema名部分，这样很方便，但引发了另外的问题。比如跨库执行SQL问题，我们这边是直接禁止跨库SQL的，但现在不知如何判断该表是不是本SCHEMA中的表，因为现在好像取不到表的SCHEMA名称（若有方法请指明，希望提供帮助）。若表中含有SCHEMA名，能否保留一个取此表SCHEMA名的方法。如以下SQL：
SELECT  a.`id`, a.`name` FROM `test_db1`.`travelrecord` a WHERE a.createtime BETWEEN date_sub('2017-01-12', INTERVAL 1 DAY) AND now()；
SQLStatment.toString:
SELECT a.`id`, a.`name`
FROM `travelrecord` a
WHERE a.createtime BETWEEN date_sub('2017-01-12', INTERVAL 1 DAY) AND now()
此处在解析的时候去除了SCHEMA名称，会有改变语义的隐患。
