### ISSUE TITLE
db2：SET CURRENT SCHEMA = 'PAYROLL'语句解析不支持

### ISSUE THREAD

**Issue by xuanang** [alibaba/druid#2304]
master版本，db2解析器执行SET CURRENT SCHEMA = 'PAYROLL'语句出错，测试代码:
![image](https://user-images.githubusercontent.com/26472867/35613819-1a2e0902-06a8-11e8-9217-6e2ffdabd49c.png)
异常信息：
![image](https://user-images.githubusercontent.com/26472867/35613895-4455b69e-06a8-11e8-8bee-d8333bf522ee.png)

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
