### ISSUE TITLE
MYSQL between 条件问题

### ISSUE THREAD

**Issue by Oloong** [alibaba/druid#2306]
最新的druid 1.1.6 版本
between 条件解析问题
select * from travelrecord a where a.createtime between date_sub(now(),interval 1 day) and now();
conditions解析为：[travelrecord.createtime BETWEEN (null, Wed Jan 31 18:23:34 CST 2018)]

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
