### ISSUE TITLE
pgsql：ALTER TABLE t_user ADD column aaa VARCHAR(10)

### ISSUE THREAD

**Issue by xuanang** [alibaba/druid#2310]
主线版本：PGSQLStatementParser解析sql：ALTER TABLE t_user ADD column aaa VARCHAR(10)，最后变成了：ALTER TABLE t_user ADD (aaa VARCHAR(10))。
测试代码:
   public void  testAlterColumnAdd(){
		PGSQLStatementParser parser = new PGSQLStatementParser(
				"ALTER TABLE t_user ADD column aaa VARCHAR(10)");
		List<SQLStatement> statementList = parser.parseStatementList();
		System.out.println(statementList.get(0).toString());
 }
输出的信息：ALTER TABLE t_user ADD (aaa VARCHAR(10))

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
