### ISSUE TITLE
1.1.6 ->1.1.7 

### ISSUE THREAD

**Issue by licardoY** [alibaba/druid#2320]
使用1.16正常,使用1.17启动报:
java.lang.ClassNotFoundException: org.springframework.boot.actuate.endpoint.mvc.AbstractMvcEndpoint

**Comment by wenshao** [comment]
@lihengming

**Comment by LeaxusJoe** [comment]
更新到1.17之后遇到同样问题：java.lang.NoClassDefFoundError: org/springframework/boot/actuate/endpoint/mvc/AbstractMvcEndpoint

**Comment by jialechan** [comment]
我也遇到了

**Comment by lihengming** [comment]
@LeaxusJoe @jialechan  先用1.1.7  或者升级Spring Boot 版本到 1.5.10

**Comment by zhanglei86** [comment]
需要引入actuator依赖
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-actuator</artifactId>
</dependency>

**Comment by Carl-Xiao** [comment]
同样遇到这个问题

**Comment by kimmking** [comment]
请关注近期更新

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.8
问题已修复，请使用新版本
