### ISSUE TITLE
支持一下springboot2.0

### ISSUE THREAD

**Issue by jiaoge** [alibaba/druid#2324]
如题，马上都要发布2.0正式版了，可以支持一下了。

**Comment by Cat7373** [comment]
https://github.com/alibaba/druid/issues/2254

他们认为短期内不会有公司在生产生用`SpringBoot2`，因此短时间内不会兼容

然后窝就放弃了`Druid`，然后发现其实`SpringBoot2`默认的连接池也不错，性能也并不弱

**Comment by lihengming** [comment]
@jiaoge 2.0正式版发布前会支持~

**Comment by lihengming** [comment]
@Cat7373 我说的是不会有公司在生产上用非正式的版本，谢谢

**Comment by jiaoge** [comment]
RC版本和正式版本已经没什么大的区别了，所以针对RC版本出个新版本应该是没啥问题的。

对于这种底层库，我觉得既然已经出了这个starter，就应该保持更新，这样对于开源社区都是有好处的。
也利于更好的传播druid。更快的支持官方，这样得到的口碑是非常好的，有的时候技术选择就是这样的。

@Cat7373 你们没有必要因为这个放弃呀，这个有点激进了，druid-starter不支持的情况下，也可以使用xml获得支持的。

druid还是久经阿里巴巴生产环境考验的

@lihengming 春节前没几天咯，哈哈，可以倒计时了

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.8
问题已修复，请使用新版本
