### ISSUE TITLE
hello，我遇到一个parameter解析bug

### ISSUE THREAD

**Issue by iaskwho** [alibaba/druid#2327]
final String dbType = JdbcConstants.MYSQL;
List<Object> outParameters = new ArrayList<Object>();
String sql = "select count(0) from (select id from auth WHERE 1=1 AND/**/b=2  ORDER BY create_time DESC) as total";
String psql = ParameterizedOutputVisitorUtils.parameterize(sql, dbType, null, outParameters, VisitorFeature.OutputParameterizedQuesUnMergeInList);
System.out.println(outParameters);
<img width="920" alt="qq20180208-162517 2x" src="https://user-images.githubusercontent.com/6389808/35962515-af01d0be-0cec-11e8-8de7-61668b74be6a.png">

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.8
问题已修复，请使用新版本
