### ISSUE TITLE
druid 集成到springboot中yml文件   配置加密的数据库密码会报错

### ISSUE THREAD

**Issue by xiongwu1** [alibaba/druid#2328]
报错日志如下：
Access denied for user ‘root’'@'127.0.0.1' (using password: YES)

明文是可以操作数据库的

**Comment by lihengming** [comment]
配置发一下

**Comment by xiongwu1** [comment]
![image](https://user-images.githubusercontent.com/15642586/36009992-0a85f8b4-0d8a-11e8-9156-64c3bb3fabd5.png)

**Comment by lihengming** [comment]
配置不对，Spring Boot 默认不支持Druid，要用Druid Spring Boot Starter，spring.datasource.druid.* 这样配置，详情见文档：https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter

**Comment by songxinqiang** [comment]
配一个name就可以了
