### ISSUE TITLE
配置aop-patterns之后导致@EnableTransactionManagement的属性proxyTargetClass设置无效

### ISSUE THREAD

**Issue by qq592304796** [alibaba/druid#2330]
设置Spring监控AOP切入点
spring.datasource.druid.aop-patterns=xxx

导致@EnableTransactionManagement的属性proxyTargetClass设置无效

`Consider injecting the bean as one of its interfaces or forcing the use of CGLib-based proxies by setting proxyTargetClass=true on @EnableAsync and/or @EnableCaching.`

必须设置spring.aop.proxy-target-class=true才得以解决这个问题

**Comment by wenshao** [comment]
@lihengming

**Comment by lihengming** [comment]
@qq592304796  哈喽，我配置了`spring.datasource.druid.aop-patterns`并且加了`@EnableTransactionManagement(proxyTargetClass =true)
`问题没有重现，是不是还有其他的必要条件？

**Comment by qq592304796** [comment]
```
public class ServiceAImpl implements ServiceA {
      ....
}

public class ServiceAImpl implements ServiceA {
       /**
      *  这里注入ServiceAImpl会报错
      */
      @Autowired
       private ServiceAImpl serviceAImpl; 
      ....
}
```
`@EnableTransactionManagement(proxyTargetClass =true)`
配置proxyTargetClass =true之后，ServiceAImpl是可以成功注入

但是设置Spring监控AOP切入点之后
`spring.datasource.druid.aop-patterns=xxx`

启动程序报错
`Consider injecting the bean as one of its interfaces or forcing the use of CGLib-based proxies by setting proxyTargetClass=true on @EnableAsync and/or @EnableCaching.`


版本：release-1.1.6

**Comment by lihengming** [comment]
哦，知道了，我创建 DruidAop 默认设置 proxyTargetClass 为true就可以了，因为默认是false，导致是按接口进行代理的，而不是实现类，这个问题其实你把 `@Autowired
       private ServiceAImpl serviceAImpl; ` 修改为 `@Autowired
       private ServiceA serviceAImpl; ` 也是可以解决的。

**Comment by lihengming** [comment]
我将proxyTargetClass的默认设置修改为 true 吧，省的你们麻烦1.1.8版本解决。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.8
问题已修复，请使用新版本
