### ISSUE TITLE
DB2数据库下执行set schema DB2ADMIN出错

### ISSUE THREAD

**Issue by xuanang** [alibaba/druid#2332]
1.1.7版本，测试代码：
public void  testSetSchema(){
		DB2StatementParser parser = new DB2StatementParser(
				"set schema DB2ADMIN");
		List<SQLStatement> statementList = parser.parseStatementList();
		System.out.println(statementList.get(0).toString());
}
错误堆栈
![image](https://user-images.githubusercontent.com/26472867/36068676-98b8f500-0f15-11e8-9858-59057696f6da.png)

**Comment by wenshao** [comment]
是不是应该这样写？
```sql
set schema = DB2ADMIN
```

**Comment by xuanang** [comment]
这种语法也可以的，我在db2数据库执行过，没有问题的

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.8
问题已修复，请使用新版本
