### ISSUE TITLE
使用druid-spring-boot-starter加载，结合disconf首次读不到jdbc配置

### ISSUE THREAD

**Issue by zhanglei86** [alibaba/druid#2348]
项目使用`disconf`作为集中配置管理，首次启动是从服务器下载到`classpath:application.properties`，启动失败，二次启动读取已下载的配置，启动正常。

问题是：autoconfigure直接读不到jdbc配置，然后抛出异常。
```
org.springframework.context.annotation.AnnotationConfigApplicationContext|WARN|Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException:
Error creating bean with name 'dsMaster' defined in class path resource [com/cc/mbb/data/bootstrap/config/DruidDataSourceConfig.class]: Invocation of init method failed; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException:
Cannot determine embedded database driver class for database type NONE.
If you want an embedded database please put a supported one on the classpath. If you have database settings to be loaded from a particular profile you may need to active it (no profiles are currently active).
```

主要依赖
- spring-boot-starter-parent 1.5.10.RELEASE
- druid-spring-boot-starter 1.1.6

附件是debug日志
[debug-std.log](https://github.com/alibaba/druid/files/1747148/std.log)

**Comment by wenshao** [comment]
@lihengming

**Comment by lihengming** [comment]
@zhanglei86 配置文件麻烦发下

**Comment by zhanglei86** [comment]
感谢温绍和土豆，已经通过重写Environment方式做了临时解决，也回复邮件 @lihengming ，如果是初始化env造成，还请修复。

**Comment by lihengming** [comment]
我看了下，大致原因就是从配置服务器拉取的配置文件不能注入到Jar包内，导致Spring Boot启动时没有将配置文件绑定到Environment里面，Druid取不到配置就报错了。

有两种解决方案：
1. 如果启动Spring Boot时配置文件已经从配置服务器拉取下来了并且以文件的方式保存在本地，可以用 spring.config.location ，这个参数指定外部配置。例如：java -jar demo.jar --spring.config.location=/home/admin/application.properties

详情：https://docs.spring.io/spring-boot/docs/1.5.10.RELEASE/reference/htmlsingle/#boot-features-external-config-application-property-files
2. 可以在启动Spring Boot的时候从配置服务器拉取配置，然后追加到Environment里面，这个操作一定确保在初始化Bean的前面。

**Comment by zhanglei86** [comment]
用方案2，问题解决了，感谢土豆大神 :-)

问题还是出在disconf上
