### ISSUE TITLE
druid-spring-boot-starter 1.1.7版本连接sql 2008 报错! 而Spring boot 1.5.10.RELEASE+1.1.8 用maven不能下载druid-spring-boot-starter 1.1.8。

### ISSUE THREAD

**Issue by wuyan2018** [alibaba/druid#2352]
com.microsoft.sqlserver.jdbc.SQLServerException: The query timeout value -1 is not valid.

**Comment by wenshao** [comment]
@lihengming 看看

**Comment by qq592304796** [comment]
spring-boot-starter 1.1.8 用的是2.0.0.RC1,并不是release版本,需要自己在pom中配置repositories
`
<repositories>
    <repository>
        <id>spring-milestones</id>
        <name>Spring Milestones</name>
        <url>https://repo.spring.io/libs-milestone</url>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
    </repository>
</repositories>
`
感觉这是个组件,不应该去加载spring-boot, scope>provided

**Comment by wuyan2018** [comment]
如果 druid-spring-boot-starter 1.1.8只支持spring boot 2.0，那么能不能把druid-spring-boot-starter 1.1.7这个报错问题解决了。 也好让以前的spring boot  版本能用。 最好快点啊等着用呢，谢谢！

**Comment by wuyan2018** [comment]
druid 1.1.7 加druid.validation-query-timeout: 6000 参数可以解决报错问题了。 但是 spring-boot-devtools热部署怎么就找不到数据源了呢？### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is com.alibaba.druid.pool.DataSourceClosedException: dataSource already closed at Mon Feb 26 17:42:54 CST 2018

**Comment by lihengming** [comment]
@wuyan2018 有没有没一点问题的版本？我排查下。 主要没SqlServer，没法重现。

**Comment by wuyan2018** [comment]
@lihengming  报错com.microsoft.sqlserver.jdbc.SQLServerException: The query timeout value -1 is not valid 1.1.5报错但是能用，1.1.6和1.1.7一样 报错不能用。
 spring-boot-devtools热部署怎么就找不到数据源这个问题，1.1.5-1.1.7都一样，我也不知道是不是druid的问题。

**Comment by wuyan2018** [comment]
spring-boot-devtools热部署启动后添加数据库数据没问题，如果修改代码后就提示那个错误了

**Comment by lihengming** [comment]
不用druid-spring-boot-starter 单独引用 druid 呢？

**Comment by lihengming** [comment]
@qq592304796  一样的，虽然starter用的2.0.0.RC1，但是优先级还是实际项目中的版本，会覆盖整个的，你可以试试。

**Comment by qq592304796** [comment]
@lihengming 当才看了是会以项目中的为主，但还是需要自己在pom中配置repositories，不然架包就下载不下来，因为私库中只配置了maven的中央仓库
