### ISSUE TITLE
MySQL delete...from...join...语句解析异常

### ISSUE THREAD

**Issue by dingqianlong** [alibaba/druid#2355]
druid：1.1.8

`String sql = "delete a.* from teacher_1 a join teacher_2 b on a.teacher_id = b.teacher_id where a.day < b.day";`

解析结果：
Tables : {teacher_1=Delete, teacher_2=Delete, a.*=Delete}

存在的问题：
1）不应该解析出a.*；
2）表teacher_2视为Delete不合适吧；

**Comment by wenshao** [comment]
问题已经修复，请等下个版本发布吧，着急可以自行编译一个快照。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.9
问题已修复，请用新版本
