### ISSUE TITLE
使用druid-spring-boot-starter在系统启动时没有初始化

### ISSUE THREAD

**Issue by moonshy** [alibaba/druid#2361]
我在使用druid-spring-boot-starter时，配置和启动项目都没有问题，数据库也能正常访问。但是数据源在第一次访问数据库的时候才开始初始化，而且时间消费13s。是否有什么配置可以让数据源在系统启动时就加载呢？

**Comment by enhon1992** [comment]
[https://github.com/alibaba/druid/issues/2207](url)

**Comment by enhon1992** [comment]
[](https://github.com/alibaba/druid/issues/2207)

**Comment by enhon1992** [comment]
[#2207](https://github.com/alibaba/druid/issues/2207)

**Comment by moonshy** [comment]
druid-spring-boot-starter 1.1.8 和1.1.8_20180212这两个版本的jar都无法下载呢？

**Comment by enhon1992** [comment]
<dependency>
      <groupId>com.alibaba</groupId>
      <artifactId>druid-spring-boot-starter</artifactId>
      <version>1.1.8</version>
    </dependency>

**Comment by moonshy** [comment]
我用的就是你给的地址，但是就是无法下载，1.1.7包括以前的版本都可以下载

**Comment by enhon1992** [comment]
不会吧!你使用VPN试一下  我这边反正是可以的
