### ISSUE TITLE
spring-boot2.0RELEASE 发布了。配置druid-spring-boot-starter1.1.8 maven报错了

### ISSUE THREAD

**Issue by Kmegumi** [alibaba/druid#2368]
Failed to read artifact descriptor for com.alibaba:druid-spring-boot-starter:jar:1.1.8

**Comment by licardoY** [comment]
看下本地库里是不是已经有1.1.8文件夹,先删除,再update试试?我昨天是这么解决的

**Comment by moonshy** [comment]
我也遇到了。就是无法下载。

**Comment by zhagnfan** [comment]
com.alibaba:druid-spring-boot-starter:jar:1.1.8: Failed to read artifact descriptor for com.alibaba:druid-spring-boot-starter:jar:1.1.8: Could not find artifact org.springframework.boot:spring-boot-dependencies:pom:2.0.0.RC1

**Comment by BadGuyX** [comment]
我这里也是
![image](https://user-images.githubusercontent.com/14200813/36896336-3c86f6f0-1e4d-11e8-9c84-16dca1013dbe.png)

**Comment by BadGuyX** [comment]
我发现了，如果先配1.1.7，那么再配1.1.8就不会报错。。

**Comment by TurboHirsch** [comment]
因为1.1.8里面用的是spring boot 2.0.0.RC1的jar，这个jar已经没了。 需要修改到release版本。可以自己下载源码修改编译到私服上，

**Comment by lazydsr** [comment]
可以将本地仓库中的
![image](https://user-images.githubusercontent.com/11435621/36968187-bf903cfe-209c-11e8-916d-9c9a33e9338a.png)中
![image](https://user-images.githubusercontent.com/11435621/36968199-ce8312a4-209c-11e8-9fcb-588175513c9f.png)修改为正式版，就可以暂时使用了，等想修复之后可以直接将1.8那个文件夹删除就好了

**Comment by leechor** [comment]
有办法让Gradle忽略并不下载这个spring-boot版本吗?使用已有的spring-boot-start.2.0.0.REALSE

**Comment by BadGuyX** [comment]
我楼下有两位大佬已经提供方法了，你照着其中一个方法做，然后在 项目的 build.gradle 脚本里的 buildscript模块 里优先引用
mavenLocal() 就好了，或者在全局的 init.gradle 里把 mavenLocal() 加在第一位也行

2018-03-07 19:55 GMT+08:00 licho <notifications@github.com>:

**Comment by leechor** [comment]
已经这么操作了，谢谢。
 只是想知道在这种情况下，gradle可不可以指定所依赖模块的版本,而不用下载默认的模块版本.

**Comment by BadGuyX** [comment]
应该不可以吧，毕竟一般来说，同一个组织的一份工具的 jar包的只会有只会有版本上的区别。所以如果如果想要引入依赖了2.0.0.RELEASE 的
druid-spring-boot-starter，要么你用其他组织的 jar 包，要么就等阿里迭代

2018-03-07 20:06 GMT+08:00 licho <notifications@github.com>:
