### ISSUE TITLE
join...on...语句解析可能有BUG，请确认

### ISSUE THREAD

**Issue by dingqianlong** [alibaba/druid#2371]
druid：1.1.8
`String sql  = "select t1.teacher_id from teacher_1 t1 left join teacher_2 t2 on t1.teacher_id";`
`System.out.println(WallUtils.isValidateMySql(sql)); // true`
`System.out.println(WallUtils.isValidatePostgres(sql)); // true`

存在的问题：
sql中的on条件只写了一半，理论上是条无法执行的sql，但是被认为是正确的sql，并且用SchemaStatVisitor可以正常解析出表和字段而不会抛出异常。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.9
问题已修复，请用新版本
