### ISSUE TITLE
springboot 2.0.0 GA已发布，可将springboot依赖版本由2.0.0.RC1调整到SpringBoot 2.0.0 GA已经发布，可将springboot依赖版本由2.0.0.RC1调整到2.0.0.RELEASE了。 

### ISSUE THREAD

**Issue by aihua** [alibaba/druid#2372]
springboot 2.0.0 GA已发布，可将springboot依赖版本由2.0.0.RC1调整到SpringBoot 2.0.0 GA已经发布，可将springboot依赖版本由2.0.0.RC1调整到2.0.0.RELEASE了。 @Arbow @argan @septer @zhuzhaoyuan @coderplay

**Comment by lihengming** [comment]
1.1.9会调整为2.0.0.RELEASE

**Comment by pkaq** [comment]
1.1.9已出 这个可以close了~
