### ISSUE TITLE
如下两段代码执行结果不一致

### ISSUE THREAD

**Issue by jiangzeyin** [alibaba/druid#2373]
public static void main(String[] args) throws SQLException {
        // 代码1
        String ids = "1,2,3";
        String sql = "select count(1) from tableA where name=? and ids in(?)";
        DataSource dataSource = null;
        List<Map<String, Object>> list = JdbcUtils.executeQuery(dataSource, sql, "a", ids);

        // 代码2
        sql = "select count(1) from tableA where name=? and ids in(" + ids + ")";
        list = JdbcUtils.executeQuery(dataSource, sql, "a");

    }

代码2结果是正确的，请问这是因为什么问题呢？

**Comment by moonshy** [comment]
代码1 执行的实际sql是
select count(1) from tableA where name=‘a’ and ids in('1,2,3') //注意单引号
