### ISSUE TITLE
druid开始带广告了？是我电脑的问题还是都有？

### ISSUE THREAD

**Issue by daisenrong** [alibaba/druid#2375]
druid开始带广告了？是我电脑的问题还是都有？

**Comment by wenshao** [comment]
内置的阿里云广告，这个有什么问题么？

**Comment by YongjianLiang** [comment]
@lazydsr 自己fork一个，然后把广告干掉，druid是apache v2授权，可以自己改的。

**Comment by littlezhou** [comment]
@wenshao 可以理解，但不知温少可否考虑一下这样：广告换个类似“powered by Aliyun”之类的logo，而不是直接下面这种促销画面，毕竟这些信息客户可以从阿里云的销售页面获取。多谢！
![aliyun](https://user-images.githubusercontent.com/10972684/37188871-740376b4-238c-11e8-9e95-314b0e118c89.png)

**Comment by JackLee1993** [comment]
这种问题可以关闭了。。。

**Comment by LittleShrimp1987** [comment]
这有什么问题吗？哈哈哈哈，呵呵呵，好嗨哟。
