### ISSUE TITLE
update语句解析后获取where条件

### ISSUE THREAD

**Issue by IRoye** [alibaba/druid#2378]
windows/jar 版本1.1.8
```java
final String dbType = JdbcConstants.MYSQL; // ORACLE or POSTGRESQL or SQL_SERVER or HIVE or ODPS
//String sql = "update b set (ClientName) = (SELECT name FROM a WHERE b.id = a.id)";
String sql = "update students set name='test' where id in (select stu_id from score where s <100)";
SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, dbType);
SQLUpdateStatement stmt = (SQLUpdateStatement) parser.parseStatement();
System.out.println(stmt.getWhere());`
```
上面的代码拿到的结果是：
`SELECT stu_id
FROM score
WHERE s < 100`
而当把sql语句改为
`update students set name='test' where id in (select stu_id from score where s <100) and name = 'test2'`
代码拿到的结果变成了：
`id IN (
	SELECT stu_id
	FROM score
	WHERE s < 100
)
AND name = 'test2'`

为什么第一次获取where 条件没能拿到id 这个column和in这个operator呢？而添加一个and name = 'test2'的条件却能拿到。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.9
问题已修复，请用新版本
