### ISSUE TITLE
druid的SQLUtils.toSQLExpr只支持select吗?

### ISSUE THREAD

**Issue by scmod** [alibaba/druid#2384]
String sql = "UPDATE T SET C1 = C1 + 1 WHERE C2 = 'a'";
SQLUtils.toSQLExpr(sql);
这样也会报错...
那我是不是只有parseStatements加上指定的dbType一条路了
我只想处理些简单的sql,可不可以有什么办法不要oracle,mysql之类的VisitorAdapter一个个实现过来啊

**Comment by wenshao** [comment]
parseStatements的dbType可以指定为null

**Comment by scmod** [comment]
呀.?我之前试过指定null什么东西都没有出来,刚才试下又可以了,可能上次accept错别的visitor了所以没信息,不好意思...
