### ISSUE TITLE
请问，druid的spring监控怎么使用？

### ISSUE THREAD

**Issue by BerryWang1996** [alibaba/druid#2387]
没有找到相关文档

**Comment by IsaacGao** [comment]
有问题就去搜wiki，不要做伸手党
[druid wiki](https://github.com/alibaba/druid/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by BerryWang1996** [comment]
谢谢楼上朋友

**Comment by pkaq** [comment]
及时关闭issues 善始善终是一名合格程序猿应有的节操 ：）
