### ISSUE TITLE
字符'\'解析问题

### ISSUE THREAD

**Issue by sunsun314** [alibaba/druid#2388]
版本:1.1.8
描述：
  在字符'\\'之后一位的字符如果不能和'\\'形成转义会丢失
举例： 
  INSERT INTO SUNTEST(ID,NAME) VALUES(1,'\\_ASDFASDF')
在通过 解析器解析之后会变成
  INSERT INTO SUNTEST(ID,NAME) VALUES(1,'_ASDFASDF')

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.9
问题已修复，请用新版本
