### ISSUE TITLE
1.1.7 能不能出个特别修复版？

### ISSUE THREAD

**Issue by yihuishou** [alibaba/druid#2391]
启动报`java.lang.ClassNotFoundException: org.springframework.boot.actuate.endpoint.mvc.AbstractMvcEndpoint` 错误。

1.1.8 又依赖 springboot 2.0rc1

求 springboot 1.5.10 的解决方案

另外1.1.7 的application配置中找不到关于web页面的配置提示。

**Comment by lihengming** [comment]
等1.1.9发布吧
