### ISSUE TITLE
依赖的 springboot 版本 2.0.0.RC1 在 mavne 仓库中不存在，目前版本为 2.0.0.RELEASE

### ISSUE THREAD

**Issue by yutaoxu** [alibaba/druid#2392]
依赖的 springboot 版本 2.0.0.RC1 在 mavne 仓库中不存在，目前版本为 2.0.0.RELEASE

**Comment by bocloud** [comment]
我现在也遇到这个问题了，druid还是不错的，要是跟不上springboot的节奏，我这边就有可能转向其他的连接池组件了。希望尽快修复这个问题。

**Comment by wenshao** [comment]
争取周末发布，如果赶不及就下个周末

**Comment by lihengming** [comment]
@bocloud Spring Boot确实速度太快了，Druid Starter会尽可能的跟进Spring Boot的脚本，并兼容之前的版本，预计这几天会发布个新版本。

**Comment by pkaq** [comment]
1.1.9已出 这个可以close了~

**Comment by yutaoxu** [comment]
上述描述的问题已经在 1.1.9 中得到解决，谢谢！
