### ISSUE TITLE
方法重命名建议

### ISSUE THREAD

**Issue by liaozan** [alibaba/druid#2398]
com.alibaba.druid.spring.boot.autoconfigure.stat.DruidWebStatFilterConfiguration#filterRegistrationBean
这个方法是否可以考虑下重命名，如果用户自定义filter，可能会和druid重名，导致用户自定义filter无法注入

**Comment by lihengming** [comment]
ServletRegistrationBean也会出现这个问题，如果没有显示的使用`registrationBean.setName();`来设置名称会已方法名来定义，重复的会被覆盖，已经解决了

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.9
问题已修复，请用新版本
