### ISSUE TITLE
in...SQL语句解析问题

### ISSUE THREAD

**Issue by dingqianlong** [alibaba/druid#2407]
druid 1.1.9

SQL：
`String sql = "SELECT name FROM employee WHERE no in ('1', '2');";`
`String sql = "SELECT name FROM employee WHERE no in (1, 2);";`

解析结果：
`coditions : [employee.no IN (1, 2)]`

存在的问题：
以上两个SQL中in列表元素不一样但是解析出的coditions却一样。解析结果中in列表元素去掉了引号，导致无法辨别原SQL中的in列表元素是否使用了引号。

修改意见：
解析结果in列表元素应保留原始格式。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.10
问题修复，请用新版本
