### ISSUE TITLE
配置Oracle驱动提示error

### ISSUE THREAD

**Issue by sunrui849** [alibaba/druid#2408]
使用1.1.8版本的druid，配置了druid的Oracle驱动，提示了一个oracle.jdbc.driver.OracleDriver is deprecated.这样的错误，看了源码上对Oracle驱动做了判断如下：
`public void setDriverClassName(String driverClass) {
        if(driverClass != null && driverClass.length() > 256) {
            throw new IllegalArgumentException("driverClassName length > 256.");
        } else {
            if("oracle.jdbc.driver.OracleDriver".equalsIgnoreCase(driverClass)) {
                **LOG.error("oracle.jdbc.driver.OracleDriver is deprecated.");**
            }

            if(this.inited) {
                if(!StringUtils.equals(this.driverClass, driverClass)) {
                    throw new UnsupportedOperationException();
                }
            } else {
                this.driverClass = driverClass;
            }
        }
    }`
为什么要单独对Oracle做了处理，有什么原因么

**Comment by licardoY** [comment]
使用 `oracle.jdbc.OracleDriver`   , `oracle.jdbc.driver.OracleDriver`是老版的已经不推荐了

**Comment by sunrui849** [comment]
明白了，谢啦

**Comment by JackLee1993** [comment]
oracle.jdbc.driver.OracleDriver 为老版本oracle驱动，druid 中有判断版本，不建议使用老版本
