### ISSUE TITLE
Druid start 1.1.9 结合springboot 1.5.10 在jdk1.7下不能启动

### ISSUE THREAD

**Issue by hongliming** [alibaba/druid#2409]
由于com.alibaba.druid.spring.boot.autoconfigure.properties.DruidStatProperties在jdk1.8以上编译的

Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure]; nested exception is java.lang.ClassCastException: java.lang.UnsupportedClassVersionError cannot be cast to [Ljava.lang.Object;

**Comment by wenshao** [comment]
@lihengming

**Comment by lihengming** [comment]
@hongliming 下个版本解决哈，不过能升级JDK1.8的话还是升级一下好，Spring Boot 2.0最低要求就是JDK1.8 ，况且Java 10都快出来了。。

**Comment by hongliming** [comment]
@lihengming 谢谢土豆，明白你说的，目前还得项目编译这块得坚守一下1.7，部分老项目的Dubbo依赖需要。我负责的这块已经往1.8升级了。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.10
问题修复，请用新版本
