### ISSUE TITLE
连接关闭时未提交事务回滚

### ISSUE THREAD

**Issue by dyingfame** [alibaba/druid#2413]
有没有方法设置，使得连接关闭时不要让未提交的事务回滚。

**Comment by darren-wang** [comment]
这个很好啊，不知道Duird现在的机制是什么样的

**Comment by lizongbo** [comment]
关闭连接还回连接池时，漏提交事务的话，事务会一直存在，既没回滚也没提交，等到物理连接断开时，mysql服务端回滚了事务，我们因此已经出过严重的生产问题
该Issue需求不合理。
