### ISSUE TITLE
DB2驱动名问题

### ISSUE THREAD

**Issue by laizhiming** [alibaba/druid#2424]
com.alibaba.druid.util.JdbcConstants.DB2_DRIVER="COM.ibm.db2.jdbc.app.DB2Driver";

应该改成：com.ibm.db2.jcc.DB2Driver
谢谢！

**Comment by wenshao** [comment]
你来提交个patch？

**Comment by laizhiming** [comment]
第一次用gibhub提交代码，不知道那样提交对不对。如果不对，麻烦@wenshao 指正，谢谢。 #2447

**Comment by laizhiming** [comment]
已修复 #2447
