### ISSUE TITLE
(*) property for user to setup是配置不当引起的吗

### ISSUE THREAD

**Issue by taifenglan** [alibaba/druid#2440]
监控页面数据源下面的这个错误。尝试了很多版本，都存在这个问题，一直没有得到修复，很多博客的解决方案也没有用，找不到原因客户看了这个监控页面觉得有报错很不ok，想咨询下各位有什么好的解决方案？

**Comment by taifenglan** [comment]
都是readme里的推荐配置

**Comment by lihengming** [comment]
没关系，执行一次SQL就好了，或者使用最新版本，应该没这个问题了。

**Comment by XIAOMIOPPO** [comment]
我都用的durid spring boot starter 还是报错

**Comment by tkggft** [comment]
你们解决了吗？

**Comment by startjava** [comment]
没有解决。
