### ISSUE TITLE
SQL 解析错误

### ISSUE THREAD

**Issue by MrWhiteL** [alibaba/druid#2443]
18:22:57.610 [main] ERROR com.alibaba.druid.filter.stat.StatFilter - merge sql error, dbType clickhouse, druid-1.1.9, sql : SELECT date, transactionChannel, tranactionType FROM preComp_3All_20180322  limit 1,10
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'imit 1,10', expect LITERAL_INT, actual LITERAL_INT pos 83, line 1, column 82, token LITERAL_INT
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:284) ~[druid-1.1.9.jar:1.1.9]

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.10
问题修复，请用新版本
