### ISSUE TITLE
druid在spring  boot2.0 对postgresql数据库密码加密问题

### ISSUE THREAD

**Issue by villebo** [alibaba/druid#2445]
在spring boot2.0中采用druid-spring-boot-starter版本1.1.9对postgresql10的数据库密码进行加密处理，启动应用后出现org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"

**Comment by villebo** [comment]
已经解决了

**Comment by xmt1139057136** [comment]
怎么解决的，我也遇到了！
