### ISSUE TITLE
PostgreSQL内存表解析报错

### ISSUE THREAD

**Issue by dingqianlong** [alibaba/druid#2446]
druid 1.1.9

PostgreSQL用到内存表的SQL解析会报错，比如：
`String sql = "delete from account a using (values (1), (7)) as tmp(id) WHERE a.id = tmp.id";`

`String sql = "update student a set grade = tmp.grade from (values (1, 'A')) as tmp(id, grade) where a.id = tmp.id";`

**Comment by fengyuqian** [comment]
druid 1.1.9
这样使用也解析不了
`UPDATE mt_grade
SET NAME = tmp.NAME,
 CLASS = tmp.CLASS
FROM
    (
                 VALUES
            ('1', '111', '111'),
            ('2', '222', '222'),
            ('3', '333', '333')
    ) AS tmp (ID, NAME, CLASS)
WHERE
     mt_grade.ID = tmp.ID;`

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.10
问题修复，请用新版本
