### ISSUE TITLE
使用druid-spring-boot-starter配置多个datasource初始化卡死

### ISSUE THREAD

**Issue by arebya** [alibaba/druid#2448]
如题配置多个datasource时，@Primary的datasource正常init，其他datasource进入init之后在创建PhysicalConnection时会卡死。使用mysql客户端连接正常，同时去掉@Bean中的initMethod，在访问时出发初始化也是正常的。

spring-boot   版本1.5.7

druid-spring-boot-starter  版本1.1.6

mybatis版本   3.4.5

**Comment by xmt1139057136** [comment]
这个问题为什么关闭了呢？？我想知道关闭原因！
