### ISSUE TITLE
sql parser 对mysql字符串支持不够

### ISSUE THREAD

**Issue by fastdev163** [alibaba/druid#2452]
/com/alibaba/druid/sql/parser/Lexer.java的
1、scanString2_d()方法 1251行判断字符串结束好像有问题，感觉应该用双引号才对？
2、scanString 方法对 mysql的支持不全，mysql里面 \ 也是可以转义的。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.10
问题修复，请用新版本
