### ISSUE TITLE
表名替换异常

### ISSUE THREAD

**Issue by workTestdr** [alibaba/druid#2457]
使用Oracle数据库，在使用SQLUtils.toSQLString(statementList, dbType, parameters, option, tableMapping)这个API时出现问题。
部分代码如下：
Map<String, String> tableMapping = new HashMap<String, String>();
tableMapping.put(historyDataRoute.getOriginalTableName(), historyDataRoute.getHisTable()); List<SQLStatement> stmtList = SQLUtils.parseStatements(sql, JdbcConstants.ORACLE);
String refactorSql = SQLUtils.toSQLString(stmtList, JdbcConstants.ORACLE, null, new FormatOption(true, false), tableMapping);
代码中sql为简单的update语句，例如“UPDATE FUNDIN SET BANKTIME = ?, SENDTIME = ? WHERE TXNO = ?”
主要问题：上述代码在并发量小的时候不会出现问题，并发量大的时候会出现个别表名无法替换的情况，现在发现的情况都是Update语句。

**Comment by wenshao** [comment]
传入一个ConcurrentHashMap试试看？

**Comment by li395092734** [comment]
多谢，解决我表名替换的问题。
