### ISSUE TITLE
关于Druid初始化时对错误地址不报异常

### ISSUE THREAD

**Issue by TimeEraser** [alibaba/druid#2459]
@wenshao 我基于1.1.9进行测试发现即使是对如下url进行初始化时依然没有报错，但是1.1.2的版本却没有问题。
![image](https://user-images.githubusercontent.com/12388190/38239984-df6fafc0-3760-11e8-97b1-b3f950774c64.png)
翻阅了1.1.2初始化的代码，发现初始化时会直接用url等信息同步创建连接
![image](https://user-images.githubusercontent.com/12388190/38239853-81e0f058-3760-11e8-849b-77f9868b723f.png)
但是在1.1.9初始化的代码中，发现如果存在createScheduler时则会直接提交异步创建的任务
![image](https://user-images.githubusercontent.com/12388190/38240209-9126ef4e-3761-11e8-8118-8d9fcffd7cf4.png)

对于createScheduler的作用个人的理解是为了避免在多数据源情况下创建过多的创建线程。但是在初始化的过程中存在createScheduler就直接异步创建连接了是否有点rough，会掩盖初始化的错误。

**Comment by TimeEraser** [comment]
嗯，这个是没有问题吗，我忧人自扰了？

**Comment by lizongbo** [comment]
请使用最新版验证
