### ISSUE TITLE
关于Druid运算操作符优先级的错误

### ISSUE THREAD

**Issue by TimeEraser** [alibaba/druid#2460]
Mysql官网上对运算操作符优先级是如下定义的
![image](https://user-images.githubusercontent.com/12388190/38245342-4f563a70-3770-11e8-850f-7f9469b9bcdf.png)
我测试如下条件
![image](https://user-images.githubusercontent.com/12388190/38245383-750fe32e-3770-11e8-8922-259ad22d2094.png)
在druid解析出来之后发现
![image](https://user-images.githubusercontent.com/12388190/38245447-b171a79e-3770-11e8-9e05-56b6f7ee9221.png)
xor的优先级应该比or要高的，不知道druid是如何考虑的。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.10
问题修复，请用新版本
