### ISSUE TITLE
 active 41, maxActive 50, runningSqlCount 1   这个是什么意思？

### ISSUE THREAD

**Issue by weiboyiyou** [alibaba/druid#2468]
com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 3192, active 41, maxActive 50, runningSqlCount 1 : SELECT * FROM CLOUD_BAS.BAS_DEV_VERSION WHERE  STORE_ID=? AND DEVICE_ID=?

 active 41, maxActive 50, runningSqlCount 1   这个是什么意思？

**Comment by wenshao** [comment]
最大连接数50，已经在用41个，有一个SQL正在执行中

**Comment by weiboyiyou** [comment]
谢谢。

**Comment by hellopower** [comment]
那为什么还会超时呢？
