### ISSUE TITLE
druid+postgres，不支持窗口函数

### ISSUE THREAD

**Issue by kiddoneal** [alibaba/druid#2488]
版本: 1.1.9

sql语句：
select a.*, (a.swanav-lead(a.swanav,1,null::numeric) over w)/lead(a.swanav,1,null::numeric) over w as roe_lag 
from ffund.ffund_eval_prod_nv a 
where a.prod_id='D20171206191156525S0034R234' 
	and a.stat_date>='0000-00-00' 
	and a.stat_date<='9999-99-99' 
	and a.nav>0 and a.swanav>0 
window w as (order by a.stat_date desc)
报错信息：
syntax error: syntax error, expect LPAREN, actual IDENTIFIER pos 145, line 1, column 145, token IDENTIFIER w

**Comment by kiddoneal** [comment]
@wenshao 大神，有空帮忙看看吗？

**Comment by kiddoneal** [comment]
@wenshao 
postgres数据库: rows between这种方式也不支持，谢谢
select a.*, stddev_samp(a.idx_yield_day) over(order by a.action_date rows between 60 preceding and current row) as idx_volatility from idx_a a

**Comment by kiddoneal** [comment]
@wenshao 
postgres数据库: 如下用法不支持
(max(a.stat_date)::date-min(a.stat_date)::date + 1)::int

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.10
问题修复，请用新版本
