### ISSUE TITLE
如何进行sql改写

### ISSUE THREAD

**Issue by thank037** [alibaba/druid#2502]
通过SchemaStatVisitor可以获取AST中的Select Column, Order Column, where Column,
如果想进行某个部分的改写比如增加where条件, 该怎么做? 
SQLExpr的用法

**Comment by thank037** [comment]
@wenshao @wenshao

**Comment by lizongbo** [comment]
解析sql得到 SQLStatement对象实例，然后修改内容，再生成新sql。
