### ISSUE TITLE
SchemaStatVisitor 解析query 语句，保留 * 信息

### ISSUE THREAD

**Issue by melin** [alibaba/druid#2509]
做sql 列权限校验，需要知道所有查询的列，例如这个sql： select * from table1 a left outer join table2 b on a.id=b.id 会读取两个表的所有列，columns中能够加上table1.* , table2.*

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.10
问题修复，请用新版本
