### ISSUE TITLE
SchemaStatVisitor 解析hive 多路输出表，部分列缺失表明。

### ISSUE THREAD

**Issue by melin** [alibaba/druid#2510]
FROM sale_detail
INSERT OVERWRITE TABLE sale_detail_multi partition (sale_date='2010', region='china' )
SELECT shop_name, customer_id, total_price
INSERT OVERWRITE TABLE sale_detail_multi partition (sale_date='2010', region='china' )
SELECT shop_name, customer_id, total_price;

输出列信息：[sale_detail_multi.sale_date, sale_detail_multi.region, UNKNOWN.shop_name, UNKNOWN.customer_id, UNKNOWN.total_price]

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.10
问题修复，请用新版本
