### ISSUE TITLE
Communications link failure

### ISSUE THREAD

**Issue by funyule** [alibaba/druid#2522]
在数据库的配置中，我们已经配置了连接检测
`        <property name="validationQuery">
            <value>SELECT 1</value>
        </property>
        
        <property name="testOnBorrow" value="true"/>
        
        <property name="testOnReturn" value="false"/>
        <property name="testWhileIdle" value="true"/>`

数据库上的失效时间配的7200s

我们后台仍然爆出来 
`[TF_LOG] 10:58:15.481 [Druid-ConnectionPool-Create-397237626] ERROR c.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://{url屏蔽}?serverTimezone=GMT%2B8, errorCode 0, state 08S01
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 152,837 milliseconds ago.  The last packet sent successfully to the server was 152,836 milliseconds ago.`

请问有同行遇到过没

druid v1.1.0

**Comment by katrina2014** [comment]
遇到同样的问题，不知道怎么解决。druid v1.1.6

**Comment by dk980241** [comment]
springboot 项目 druid-spring-boot-starter 1.1.10
我们的解决方案是把 spring.datasource.url 等的配置 改成 spring.datasource.druid.url 
把配置层数改了一下。

**Comment by 1069355234** [comment]
将testOnBorrow属性设置为true以后还是会报这个问题，druid用的1.1.10版本

**Comment by stormcc** [comment]
> 将testOnBorrow属性设置为true以后还是会报这个问题，druid用的1.1.10版本

将testOnBorrow属性设置为true以后还是会报这个问题，druid version 1.1.11 版本

**Comment by yiqingchen** [comment]
> springboot 项目 druid-spring-boot-starter 1.1.10
> 我们的解决方案是把 spring.datasource.url 等的配置 改成 spring.datasource.druid.url
> 把配置层数改了一下。

这种可以吗，我现在也遇到同样的问题了

**Comment by Xanthuim** [comment]
> springboot 项目 druid-spring-boot-starter 1.1.10
> 我们的解决方案是把 spring.datasource.url 等的配置 改成 spring.datasource.druid.url
> 把配置层数改了一下。

可以吗？经过验证吗？

我发现这个开源项目也是没人维护的感觉。。。

**Comment by shuiZzz** [comment]
> springboot 项目 druid-spring-boot-starter 1.1.10
> 我们的解决方案是把 spring.datasource.url 等的配置 改成 spring.datasource.druid.url
> 把配置层数改了一下。

层级改了以后，@ConfigurationProperties(prefix = "spring.datasourcer")那里不也得改么?我打断点看着是有配置进去啊。我也用的druid-spring-boot-starte还升级到1.1.18了

**Comment by lizongbo** [comment]
请使用最新版验证
