### ISSUE TITLE
DruidPooledResultSet-->ResultSetMetaData-->getColumnName,其值为originalColumnName而不是columnName，怎么解决获取后者的值

### ISSUE THREAD

**Issue by kervin521** [alibaba/druid#2532]
DruidPooledResultSet ps = connect.prepareStatement(sql);
DruidPooledResultSet rs = ps.executeQuery();
ResultSetMetaData rsmd = rs.getMetaData();
int count = rsmd.getColumnCount();
List<String> columns = new ArrayList<String>();
for(int i=1;i<=count;i++){
				String column =   rsmd.getColumnName(i);//@1
                    columns.add(column);
}
while(rs.next()){
				JSONObject obj = new JSONObject();
				for(String column:columns){
					Object value = rs.getObject(column);//@2
					obj.put(column, value);
				}
}

在@1处getColumnName其实取的是originalColumnName的值不是数据库列字段columnName，
在@2取值使用originalColumnName获取对应字段值将为null

如何在@1取值取得columnName的值而不是originalColumnName呢？

**Comment by 992013093** [comment]
rsmd.getColumnLabe(i)
