### ISSUE TITLE
性能相差好几ms，怎么优化Druid相关配置？

### ISSUE THREAD

**Issue by ghost** [alibaba/druid#2533]
在替换dbcp为druid的shi时候，进行的本地测试；
麻烦各位专家诊断下，谢谢~感激不尽~  

相同环境，相同配置，只更换数据源连接池和依赖包；没有修改任何代码~

测试结果如下：
项目启动第一次请求：
![default](https://user-images.githubusercontent.com/30190039/39343547-06e2da7a-4a10-11e8-95ef-7ab3a625933d.jpg)

第二次请求：
![default](https://user-images.githubusercontent.com/30190039/39343388-26be9d1c-4a0f-11e8-9d53-a04f3403545e.jpg)

**Comment by yosaku01** [comment]
你看一下prepareStatement等的设置

**Comment by DoFunCloud** [comment]
@yosaku01 恩，有点提升；感谢~
ps：
[注意事项](https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_DruidDataSource%E5%8F%82%E8%80%83%E9%85%8D%E7%BD%AE#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)里面看到这个点。。估计是这个玩意误导我了~
