### ISSUE TITLE
使用SQL拦截和解析遇见的一些问题

### ISSUE THREAD

**Issue by kai23333** [alibaba/druid#2548]
SQL拦截
	配置项 : AlterTableAllow	 是否允许执行Alter Table语句   
	Mysql 语句可以过 拦截生效 
	db2 语法解析未通过TODO pos 58, line 1, column 54, token IDENTIFIER data  
	SQL语句: alter table audit.SQLHIS alter column  EXPLAINMSG set data type VARCHAR(255)

	配置项 : ReplaceAllow		 是否允许执行REPLACE语句						
	语法解析通过  拦截不生效
	SQL语句: 	select replace(name,'li','lili') from a.test;

	配置项 :   SelectWhereAlwayTrueCheck  UpdateWhereAlayTrueCheck    拦截WHERE为永真条件
        语法解析通过  拦截不生效
	SQL语句: 	select * from A where 1 = 1 ;
	update audit.USER2 SET  TEL='110' WHERE 100=100;

	配置项 :     SelectUnionCheck				检测SELECT UNION					
	语法解析通过  拦截不生效
	select name from china_employees union select name from usa_employees;

	配置项 :			SelectMinusCheck				检测SELECT MINUS				
	语法解析通过  拦截不生效
	SQL语句:SELECT Date FROM Store_Information MINUS SELECT Date FROM Internet_Sales;

	配置项 :		SelectExceptCheck				检测SELECT EXCEPT					
        语法解析通过  拦截不生效
	SQL语句:	select * from a except select * form b;

	配置项 :		SelectIntersectCheck			检测SELECT INTERSECT				
        语法解析通过  拦截不生效
	SQL语句:	SELECT Txn_Date FROM Store_Information INTERSECT SELECT Txn_Date FROM Internet_Sales;

	配置项 :	ConditionDoubleConstAllow	查询条件中是否允许连续两个常量运算表达式
        语法解析通过  拦截不生效
	SQL语句:	SELECT FID = 3 - 1，ID = 3 - 1 from A;

	(下列  疑问   具体怎么使用)
	NoneBaseStatementAllow				是否允许非以上基本语句的其他语句，缺省关闭，通过这个选项就能够屏蔽DDL。
	CommitAllow							是否允许执行commit操作
	RollbackAllow						是否允许执行roll back操作
	ConditionOpBitwseAllow				查询条件中是否允许有'&'、'~'、'|'、'^'运算符。

	SQL解析
	语句 SQL merge into		SQL解析GG
	MERGE INTO EMPLOYE AS EM   USING MANAGER AS MA  ON EM.EMPLOYEID=MA.MANAGERID  WHEN MATCHED AND EM.SALARY<MA.SALARY THEN UPDATE SET EM.SALARY=MA.SALARY  WHEN MATCHED AND EM.SALARY>MA.SALARY THEN SIGNAL SQLSTATE '70001' SET MESSAGE_TEXT = 'EM.SALARY>MA.SALARY'
	WHEN NOT MATCHED THEN INSERT VALUES (MA.MANAGERID,MA.NAME,MA.SALARY)  ELSE IGNORE;

	语句 SQL limit		SQL解析GG
	select * from Customer LIMIT 10;

**Comment by kai23333** [comment]
@wenshao 
操作步骤是先进行SQL解析,解析成功走拦截,如果失败则停止,现在主要做的是mysql和DB2的语法解析和拦截,希望可以看一下,解决一下

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.10
问题修复，请用新版本
