### ISSUE TITLE
Oracle分页查询下一页时出现语法解析错误  com.alibaba.druid.sql.parser.ParserException: syntax error, expect FIRST, actual NEXT, pos 1173, line 1, column 1169, token NEXT

### ISSUE THREAD

**Issue by napoleon-he** [alibaba/druid#2549]
运行语句是：SELECT
	specialact0_. ID AS id1_14_,
	specialact0_.gmt_create AS gmt_create2_14_,
	specialact0_.gmt_modified AS gmt_modified3_14_,
	specialact0_.issuer AS issuer4_14_,
	specialact0_.prisonarea AS prisonarea5_14_,
	specialact0_.prisonarea_code AS prisonarea_code6_14_,
	specialact0_. NAME AS name7_14_,
	specialact0_.prison AS prison8_14_,
	specialact0_.synopsis AS synopsis9_14_,
	specialact0_.sys_orgcode AS sys_orgcode10_14_,
	specialact0_.sys_orgname AS sys_orgname11_14_,
	specialact0_.sys_permname AS sys_permname12_14_,
	specialact0_.sys_perrmcode AS sys_perrmcode13_14_,
	specialact0_. TIMES AS times14_14_
FROM
	hs_special_activities specialact0_
WHERE
	1 = 1 offset ? ROWS FETCH NEXT ? ROWS ONLY

**Comment by alexpdh** [comment]
请问你解决了吗，我也遇到相同的问题

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.10
问题修复，请用新版本
