### ISSUE TITLE
Spring Boot 2.X 版本不再支持配置继承

### ISSUE THREAD

**Issue by jialechan** [alibaba/druid#2550]
"Spring Boot 2.X 版本不再支持配置继承，多数据源的话每个数据源的所有配置都需要单独配置，否则配置不会生效"

那spring boot应该怎么做，那不是很长？官方有什么替代方法？

**Comment by lihengming** [comment]
没多长啊，一般一个应用的数据源也不会很多，一个数据源配置好，其他的复制一遍改一改不就可以了，也没多麻烦。

**Comment by lihengming** [comment]
之前能继承也是取巧，Spring Boot 2.0 不支持也在情理之中。
