### ISSUE TITLE
SQLColumnDefinition属性定义的问题

### ISSUE THREAD

**Issue by scyiqie** [alibaba/druid#2576]
mysql5.7语法：
data_type [GENERATED ALWAYS] AS (expression)
      [VIRTUAL | STORED] [NOT NULL | NULL]
      [UNIQUE [KEY]] [[PRIMARY] KEY]
      [COMMENT 'string']
在SQLColumnDefinition中定义的却是sorted。

MySqlOutputVisitor的visit方法中也应新增
        if (x.isVirtual()) {
            print0(ucase ? " VIRTUAL" : " virtual");
        }

        if (x.isStored()) {
            print0(ucase ? " STORED" : " stored");
        }

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.10
问题修复，请用新版本
