### ISSUE TITLE
Spring Boot 2.0.2不能自动注入

### ISSUE THREAD

**Issue by yinjihuan** [alibaba/druid#2577]
之前用的是Spring Boot1.4.2,druid用的是1.1.2

配置方式如下：
```
spring.datasource.druid.url=xxxx
spring.datasource.druid.username=xxx
spring.datasource.druid.password=xxx
spring.datasource.druid.driver-class-name=com.mysql.jdbc.Driver
```
升级Spring Boot版本到2.0.2后报下面的错，druid用的是1.1.9
```
Caused by: org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.datasource.druid' to javax.sql.DataSource
	at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:250)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:226)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:210)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:192)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBinder.bind(ConfigurationPropertiesBinder.java:82)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:107)
	... 49 common frames omitted
```

**Comment by libindest** [comment]
我也遇到了这个问题，不知道怎么解决。不过 这样写  
@Bean
//引用一个不存在的前缀，是可以运行的
    @ConfigurationProperties(prefix = "spring.datasource.druid.one") 
    public DataSource druidDataSource() {
        return DruidDataSourceBuilder.create().build();
    }
#文件配置
spring.datasource.url=xxxx
spring.datasource.username=xxx
spring.datasource.password=xxx
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
# 连接池配置,下面配置说明请参考Druid Github Wiki，配置_DruidDataSource参考配置
# 初始化大小,最大,最小
spring.datasource.druid.initialSize=30
spring.datasource.druid.max-active=100
spring.datasource.druid.min-idle=25
# 配置获取连接等待超时的时间
spring.datasource.druid.max-wait=60000
# 其它的就不写了.....

估计这是一个bug 还请 druid 团队给与解决.

**Comment by libindest** [comment]
我也遇到了这个问题，不知道怎么解决。不过 这样写
@bean
//引用一个不存在的前缀，是可以运行的
@configurationproperties(prefix = "spring.datasource.druid.one")
public DataSource druidDataSource() {
return DruidDataSourceBuilder.create().build();
}
#文件配置
spring.datasource.url=xxxx
spring.datasource.username=xxx
spring.datasource.password=xxx
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#连接池配置,下面配置说明请参考Druid Github Wiki，配置_DruidDataSource参考配置
#初始化大小,最大,最小
spring.datasource.druid.initialSize=30
spring.datasource.druid.max-active=100
spring.datasource.druid.min-idle=25
#配置获取连接等待超时的时间
spring.datasource.druid.max-wait=60000
#其它的就不写了.....
估计这是一个bug 还请 druid 团队给与解决

**Comment by libindest** [comment]
我也遇到了这个问题，不知道怎么解决。不过 这样写
@bean
//引用一个不存在的前缀，也就是不用druid 连接池，是可以运行的。
@configurationproperties(prefix = "spring.datasource.druid.one")
public DataSource druidDataSource() {
return DruidDataSourceBuilder.create().build();
}
#文件配置
spring.datasource.url=xxxx
spring.datasource.username=xxx
spring.datasource.password=xxx
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#连接池配置,下面配置说明请参考Druid Github Wiki，配置_DruidDataSource参考配置
#初始化大小,最大,最小
spring.datasource.druid.initialSize=30
spring.datasource.druid.max-active=100
spring.datasource.druid.min-idle=25
#配置获取连接等待超时的时间
spring.datasource.druid.max-wait=60000
#其它的就不写了.....
估计这是一个bug 还请 druid 团队给与解决
除非你将spring boot 降到1.5x

**Comment by libindest** [comment]
我也遇到了这个问题，不知道怎么解决。不过 这样写
    @Bean
    public DataSource druidDataSource(Environment env) {
        return DruidDataSourceBuilder.create().build(env,"spring.datasource.druid.one");
    }
#文件配置
spring.datasource.url=xxxx
spring.datasource.username=xxx
spring.datasource.password=xxx
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#连接池配置,下面配置说明请参考Druid Github Wiki，配置_DruidDataSource参考配置
#初始化大小,最大,最小
spring.datasource.druid.one.initialSize=30
spring.datasource.druid.one.max-active=100
spring.datasource.druid.one.min-idle=25
#其它的就不写了.....
#测试运行成功
2018-05-15 23:08:58.834  INFO 20544 --- [       Thread-4] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2018-05-15 23:08:58.843  INFO 20544 --- [       Thread-4] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closed
估计这是一个bug 还请 druid 团队给与解决
除非你将spring boot 降到1.5x

**Comment by yinjihuan** [comment]
我目前用的就是1.4.2的版本，想升下级，就遇到这个问题了，不太想自己去配置数据源，看官方什么时候能解决吧，升级下改动还挺多的

**Comment by yinjihuan** [comment]
找到原因了，是filters出的问题。
是spring.datasource.druid.filters=stat,wall,log4j有问题
load com.alibaba.druid.filter.logging.Log4jFilter报错
把log4j去掉就可以了：https://github.com/alibaba/druid/issues/2507
