### ISSUE TITLE
阻塞在了DruidDataSource.getConnectionInternal?

### ISSUE THREAD

**Issue by codeloam** [alibaba/druid#2585]
版本1.0.29和1.1.9
现象：每次获取connection，都要等待很久，1s甚至更多
druid配置：maxActive 200，minIdle：100，initialSize:50
硬件配置：阿里云ECS，2核4G

请求时，每秒400多请求线程，除了获取connection时间比较长之外，sql语句都是几十毫秒就可以返回

**Comment by lizongbo** [comment]
请使用最新版验证
