### ISSUE TITLE
关于DruidPooledStatement缓存查询结果的问题

### ISSUE THREAD

**Issue by casuallc** [alibaba/druid#2598]
对于这种预编译的查询，在程序中会一直用一个对象去查询数据，如果保存了每次的查询结果就会造成使用内存持续增加。
能不能把缓存查询结果设置成可配置的？或者暴漏一个可以自己删除缓存的方法？

   `@Override
    public final ResultSet executeQuery(String sql) throws SQLException {
        checkOpen();

        incrementExecuteQueryCount();
        transactionRecord(sql);

        conn.beforeExecute();
        try {
            ResultSet rs = stmt.executeQuery(sql);

            if (rs == null) {
                return rs;
            }

            DruidPooledResultSet poolableResultSet = new DruidPooledResultSet(this, rs);
            addResultSetTrace(poolableResultSet); // 缓存查询结果

            return poolableResultSet;
        } catch (Throwable t) {
            errorCheck(t);

            throw checkException(t, sql);
        } finally {
            conn.afterExecute();
        }
    }`

**Comment by majinju** [comment]
是的我也发现了这个问题，提得很好，对于查询量较大的应用，这个缓存时很大一个问题，麻烦官方关注下
