### ISSUE TITLE
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'rder by ? ?'

### ISSUE THREAD

**Issue by syoukaihou** [alibaba/druid#2608]
druid：1.1.9
hibernate:4.2.7.Final
 
merge sql error, dbType mysql, druid-1.1.9, sql : select *  from department where (code <> '999999' or code is null ) and incId = ?  order by ? ?

com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'rder by ? ?', expect QUES, actual QUES pos 95, line 1, column 94, token QUES

为什么出现“rder by ? ?”，我的“o”呢？我的sql语句中明明有“o”。另外返回了正确的结果集。

**Comment by wenshao** [comment]
升级到1.1.10就好了
