### ISSUE TITLE
请问，DruidDataSourceStatValue里activeCount、activePeak等字段都是什么含义？

### ISSUE THREAD

**Issue by jmjyw** [alibaba/druid#2613]

**Comment by wenshao** [comment]
activeCount正在使用的连接，peak是activeCount的峰值

**Comment by jmjyw** [comment]
那activePeakTime、poolingCount、poolingPeak、poolingPeakTime、connectCount、closeCount、waitThreadCount、notEmptyWaitCount、notEmptyWaitNanos、logicConnectErrorCount、physicalConnectCount、errorCount、pstmtCacheHitCount、startTransactionCount、keepAliveCheckCount、connectionHoldTimeHistogram都是什么含义呢？非常感谢

**Comment by jmjyw** [comment]
因为要根据日志画仪表盘，所以需要知道每个字段都是什么含义

**Comment by zzhi** [comment]
我也想知道

**Comment by sky-syk** [comment]
@wenshao  大佬帮回答下呗

**Comment by fmeng** [comment]
@wenshao 可以帮忙解答一下么

**Comment by webweaver1225** [comment]
maxActive  最大活跃数
poolingCount  当前连接池数
poolingPeak 连接池峰值
activePeakTime 连接池峰值出现时间
activeCount 当前活跃连接数
activePeak 活跃数峰值
activePeakTime 活跃数峰值出现时间

**Comment by ahaha-vip** [comment]
```
"PoolingCount": 12,
"PoolingPeak": 18,
"PoolingPeakTime": "2022-02-10 09:43:32",
"ActiveCount": 31,
"ActivePeak": 47,
"ActivePeakTime": "2022-02-10 09:39:19"
```
数据连接池中连接数（PoolingCount）比 数据连接池中活跃连接数（ActiveCount）要小，这个正常吗？不是太理解

**Comment by xzs603** [comment]
> PoolingCount
代码中有这段：
```java
lock.lock();
try {
	int allCount = this.poolingCount + this.activeCount;

	if (maxActive > allCount) {
		this.connections = Arrays.copyOf(this.connections, maxActive);
		evictConnections = new DruidConnectionHolder[maxActive];
		keepAliveConnections = new DruidConnectionHolder[maxActive];
	} else {
		this.connections = Arrays.copyOf(this.connections, allCount);
		evictConnections = new DruidConnectionHolder[allCount];
		keepAliveConnections = new DruidConnectionHolder[allCount];
	}

	this.maxActive = maxActive;
} finally {
	lock.unlock();
}
```
