### ISSUE TITLE
如何把druid监控到的信息存储到数据库中

### ISSUE THREAD

**Issue by diaowenyang** [alibaba/druid#2623]
作者你好：
    druid监控到的数据现在是存储到内存中的，请问如何把这些信息（比如sql统计，慢sql等信息）存储到指定的数据库中呢？

**Comment by wiix** [comment]
第一步：
继承com.alibaba.druid.pool.DruidDataSourceStatLoggerImpl并重写public void log(DruidDataSourceStatValue statValue)方法。
注意貌似必须调用父类的构造函数和log(DruidDataSourceStatValue statValue)方法，否则监控信息会错乱。（设计不合理或是bug）
他们的原本设计意图是继承com.alibaba.druid.pool.DruidDataSourceStatLoggerAdapter，但这样更麻烦更容易出问题。

第二步：
设置statLogger为你自己写的实现。
<property name="statLogger" ref="XXXXXXXX" />

**Comment by diaowenyang** [comment]
非常感谢
