### ISSUE TITLE
为什么自定义的StatLogger类中@Autowired进来的对象为null

### ISSUE THREAD

**Issue by diaowenyang** [alibaba/druid#2629]
作者你好：
    我这边有个需求，是springboot使用druid做数据库连接池，并把它监控到的数据输出到数据库中。我从wiki上看通过自定义StatLogger来实现制定化需求的。

   https://github.com/alibaba/druid/wiki/怎么保存Druid的监控记录 

   然后我就自定义了StatLogger，并把它设置到DruidDataSource参数中

  @Configuration
public class DruidConfig {
  
    @Bean(initMethod = "init", destroyMethod = "close")
    @ConfigurationProperties(prefix = "spring.druid")
    public DruidDataSource dataSource(Filter statFilter) throws SQLException {
        DruidDataSource dataSource = new DruidDataSource();
        MyStatLogger logger = new MyStatLogger();
        dataSource.setTimeBetweenLogStatsMillis(50000);
        dataSource.setStatLogger(logger);
        dataSource.setProxyFilters(Lists.newArrayList(statFilter()));
        return dataSource;
    }
  
    @Bean
    public Filter statFilter() {
        StatFilter filter = new StatFilter();
        filter.setSlowSqlMillis(1);
        filter.setLogSlowSql(true);
        filter.setMergeSql(true);
        return filter;
    }
  
    @Bean
    public ServletRegistrationBean servletRegistrationBean() {
  
        return new ServletRegistrationBean(new StatViewServlet(),"/druid/*");
    }
  
}
上面的 MyStatLogger 就是我自定义的 StatLogger

   它的主要内容如下：
public class MyStatLogger extends DruidDataSourceStatLoggerAdapter implements
        DruidDataSourceStatLogger {
  
    private Logger logger = LoggerFactory.getLogger(MyStatLogger.class);
  
    public static List<JdbcSqlStatValue> sqlList = null;
  
    @Autowired
    private ObjectMapper objectMapper;
  
    @Autowired
    private Producer producer;
  
    @Override
    public void log(DruidDataSourceStatValue statValue) {
        sqlList = statValue.getSqlList();
        sendToMQ();
    }
  
    private void sendToMQ() {
        if (sqlList != null && sqlList.size() > 0) {
            List<DruidLogInfo> logInfos = new ArrayList<DruidLogInfo>(
                    sqlList.size());
            JdbcSqlStatValue sqlStaValue = null;
            DruidLogInfo logInfo = null;
            Throwable executeThrowable = null;
            MonitorInfo monitorInfo = new MonitorInfo();
            try {
                for (int i = 0; i < sqlList.size(); i++) {
                    sqlStaValue = sqlList.get(i);
                    logInfo = new DruidLogInfo();
                    logInfo.setSql(sqlStaValue.getSql());
                    logInfo.setSqlParam(sqlStaValue.getLastSlowParameters());
                    executeThrowable = sqlStaValue.getExecuteErrorLast();
                    if (executeThrowable != null) {
                        logInfo.setLastErrorClass(executeThrowable.getClass()
                                .getName());
                        logInfo.setLastErrorMessage(executeThrowable
                                .getMessage());
                        logInfo.setLastErrorStackTrace(Utils
                                .toString(executeThrowable.getStackTrace()));
                        logInfo.setLastErrorTime(sqlStaValue
                                .getExecuteErrorLastTime());
                    }
                    logger.info("========" + logInfo.toString());
                    logger.info("-------------------------"
                            + objectMapper.writeValueAsString(logInfo));
                    logInfos.add(logInfo);
                }
            } catch (Exception e) {
                logger.error("convert monitor log exception", e);
            }
            monitorInfo.setLogInfos(logInfos);
            sendMonitorLog(monitorInfo);
        }
    }
  
    private void sendMonitorLog(MonitorInfo monitorInfo) {
        try {
            producer.sendMsg("druid.queue",
                    objectMapper.writeValueAsString(monitorInfo));
        } catch (Exception e) {
            logger.error(e.toString());
        }
    }
}
   我经过测试验证发现，我在 MyStatLogger 里面 @Autowired 进来的两个对象，ObjectMapper 以及我自定义的队列的生产者类 Producer，全部都是 null。

   请问这个是为什么，这违反了spring的哪个原则，为什么会是 null 呢？
   希望得到大神的答复，感谢！

**Comment by sky-syk** [comment]
解决了么~同样的问题

**Comment by alei817927** [comment]
你的MyStatLogger本身并不是component或者service，怎么可能autowired到呢
