### ISSUE TITLE
druid 1.0.20和最新版的1.1.10会出现严重的连接泄露情况

### ISSUE THREAD

**Issue by slieer** [alibaba/druid#2633]
和这个有相似之外： https://github.com/alibaba/druid/issues/2423

我昨天也遇到了，采用的是如下的配置，在大量请求持续运行时，曾重启过myql， tomcat, 添加过/etc/hosts文件数据库本地域名(本地域名，可指向本地，远程db)， 瞬间在mysql 端出现过近3000 client会话， 但多数是sleep状态的！  另外，要说明一下本地域名指向的数据库ip改了，也应该连新ip上的db啊.
根据下面的配置， 怎么也想不通啊。 今天在压测环境试了重显不了。

druid 1.0.20

>   
    <bean name="dataSourceUser" class="com.alibaba.druid.pool.DruidDataSource" init-method="init" destroy-method="close">  
        <property name="url" value="${user_jdbcurl}" />  
        <property name="username" value="${user_username}" />
          
        <property name="password" value="${user_password}" />
       
         
        <property name="initialSize" value="1" />
          
        <property name="maxActive" value="20" />  
        
        <property name="minIdle" value="1"/> 
         
        <property name="maxWait" value="60000" />  
        <property name="validationQuery" value="${validationQuery}" />  
        <property name="testOnBorrow" value="false" />  
        <property name="testOnReturn" value="false" />  
        <property name="testWhileIdle" value="true" />
          
        <property name="timeBetweenEvictionRunsMillis" value="60000" />
          
        <property name="minEvictableIdleTimeMillis" value="25200000" /> 
         
        <property name="removeAbandoned" value="true" /> 
         
        <property name="removeAbandonedTimeout" value="1800" />  
        
        <property name="logAbandoned" value="true" />

**Comment by slieer** [comment]
init方法 , 就不应该搞无锁的编程方式。

**Comment by slieer** [comment]
最新版， 也会出来这个问题。

**Comment by slieer** [comment]
在初始化连接池时， 一定要校验一下当前该数据库共有多少个真实的连接。 最好提供控制某个数据库的最大连接数据的参数(一个业务模块一个连接池，而当多个业务对应一个数据库实例时， 更需要DB层面的最大连接数校验)。

**Comment by slieer** [comment]
感谢你的回复。 但是能不能在DruidDataSource， 做好校验呢？  比如发现数据库接连数， 达到一定的数量后，无论调用多少次init， 都不予分配置物理连接。 岂不更好？

**Comment by Force-King** [comment]
你好，楼主，druid 目前用哪个版本最好？
