### ISSUE TITLE
能支持一下mysql 的 load data infile导入txt文件嘛

### ISSUE THREAD

**Issue by dyq15968171048** [alibaba/druid#2640]
比如执行下面sql语句导入txt文件 “load data infile 'd:\01.txt' into TABLE code
			fields terminated by'\t'
			LINES TERMINATED by '\r\n'”报不支持load data

**Comment by wenshao** [comment]
什么版本？报错信息可以贴一下么？

**Comment by dyq15968171048** [comment]
应该是我idea缓存问题 我昨天用的是1.1.8的版本，今天在测试了一下可以了
