### ISSUE TITLE
如何避免sql合并

### ISSUE THREAD

**Issue by diaowenyang** [alibaba/druid#2648]
作者你好：
    我这边有个需求，就是通过自定义的MyStatLogger，使监控到的数据定时输出到日志或者数据库中。
    我这边希望sql不要合并，也就是不同时间执行的相同sql，不要合并在一起。这样，我就可以设计一个UI，把这些sql按照执行时间展示出来。
    我通过读api，

        @Bean
	public Filter statFilter() {
		StatFilter filter = new StatFilter();
		filter.setSlowSqlMillis(1);
		filter.setLogSlowSql(true);
		// 是否要合并日志 true表示合并
		filter.setMergeSql(false);
		return filter;
	} 

    发现 filter.setMergeSql(false); 使避免合并sql的。结果，我把它设置为false，还是不行。请问有什么解决方案？
    非常感谢！

**Comment by wenshao** [comment]
这样会对性能有较大影响，如果有这种需求，你自己做Filter采集

**Comment by diaowenyang** [comment]
多谢 @wenshao
