### ISSUE TITLE
使用Druid监控后，SQL语句占用的内存持续增长

### ISSUE THREAD

**Issue by geeksun** [alibaba/druid#2652]
Druid版本：1.0.29
使用监控配置：web.xml中配置filter---WebStatFilte和servlet---StatViewServlet
在项目中使用Druid的监控后，项目运行10天后，JVM内存溢出，对生成的hprof文件进行分析，里面提示“One instance of "com.alibaba.druid.support.http.stat.WebURIStat" loaded by "org.apache.catalina.loader.WebappClassLoader @ 0x7800c9658" occupies 784,956,096 (44.08%) bytes” 和 “One instance of "com.alibaba.druid.support.http.stat.WebAppStat" loaded by "org.apache.catalina.loader.WebappClassLoader @ 0x7800c9658" occupies 741,552,024 (41.64%) bytes”
WebURIStat和WebAppStat实例对象分别占用了748M和707M内存，查看WebURIStat中的对象信息，发现10天前的SQL语句对象都在，没有进行GC清理，请问如何避免这个问题？

**Comment by iluoxuan** [comment]
建议生产环境默认 监控是关闭的，确实有风险

**Comment by wenshao** [comment]
监控是可以在生产环境中使用的，你这个应该是特别场景。如果WebURIStat的数量很多，应该是没能正确计算RequestURI导致。比如你自己重载com.alibaba.druid.support.http.AbstractWebStatImpl#getRequestURI这个方法。

**Comment by zzbluer** [comment]
默认是开启sql合并的。
    public MergeStatFilter() {
        super.setMergeSql(true);
    }
但是如果sql没有参数的化，会很快造成内存溢出。好像没有清除几天前内存的功能，或者设置定时清除

**Comment by bigkenbird** [comment]
@zzbluer  我這邊也有遇到類似的問題，想請問說有試過從後台去 重置 SQL監控嗎

**Comment by momolela** [comment]
我是szj，邮件已经收到~

**Comment by momolela** [comment]
我是szj，邮件已经收到~
