### ISSUE TITLE
关于testWhileIdle的问题描述

### ISSUE THREAD

**Issue by yzq0428** [alibaba/druid#2663]
如果通过validationQuery 的配置检测到连接已经失效，再次调用connectionImpl.close()方法，会因为connection里isclosed()方法检测不准确 而执行rollback操作就会抛出异常 Communications link failure during rollback(). Transaction resolution unknown.

我个人认为 如果已经检测连接失效，就没有必要再去关闭连接，直接置为null即可，置为null的connection在被垃圾回收器回收后就会释放mysql服务资源
**或者也可以调用connection的abortInternal()** 来标记连接失效，避免抛出MySQLNonTransientConnectionException Communications link failure during rollback(). Transaction resolution unknown. 异常

**Comment by lizongbo** [comment]
请使用最新版验证
