### ISSUE TITLE
Springboot 2.0加密连接出错

### ISSUE THREAD

**Issue by Wang-Jun-Chao** [alibaba/druid#2673]
使用springboot2 druid进行加密连接，在创建连接时报错。不使用加密方式可以成功。
![image](https://user-images.githubusercontent.com/13402670/42080700-1dfdd91c-7bb6-11e8-8cf2-fb1a4eb4de1e.png)

**Comment by Great-Keith** [comment]
老哥请问解决了吗

**Comment by Wang-Jun-Chao** [comment]
问题已经解决了。

**Comment by 908264085** [comment]
请问是怎么解决的
