### ISSUE TITLE
druid 数据库连接断开，恢复正常后。不会重连

### ISSUE THREAD

**Issue by chenh930330** [alibaba/druid#2678]
druid 数据库连接断开，恢复正常后。不会重连

**Comment by chenh930330** [comment]
1.1.9和1.0.31都尝试过
![image](https://user-images.githubusercontent.com/40283646/42154361-2b12a3bc-7e18-11e8-81c4-c1d5318bd609.png)

**Comment by wenshao** [comment]
1.1.10试试看

**Comment by chenh930330** [comment]
1.1.10版本下了还是不行。
以下是我的配置
![image](https://user-images.githubusercontent.com/40283646/42156545-eea76984-7e1d-11e8-932a-dd342257da3e.png)
以下是报错信息，数据库连不上以后，页面就死了。即使数据库启动好了，还是连不上，不会重连。一定要重启应用，但是生产环境，就很尴尬了。
![image](https://user-images.githubusercontent.com/40283646/42156651-33ae3a3a-7e1e-11e8-81ab-8f8add7d9d1b.png)

**Comment by ljunwei** [comment]
该问题的解决方案有吗？这边也碰到了
谢谢

**Comment by shenjianeng** [comment]
get connection timeout retry : 1
at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1260)

一天warn日志出来57次

**Comment by spjich** [comment]
你好，你这个问题复现场景是什么

**Comment by chenh930330** [comment]
服务器出现问题，服务被关闭。然后在数据库服务恢复正常后，应用 未重连数据库，必须重启应用服务，才能连上数据库@spjich

**Comment by youarepppp** [comment]
有解决吗，现在也发现这个问题，数据库宕机了，重启后，连接池不会重连，生产环境太尴尬了

**Comment by chenh930330** [comment]
> 有解决吗，现在也发现这个问题，数据库宕机了，重启后，连接池不会重连，生产环境太尴尬了

用1.1.16版本就可以了

**Comment by Force-King** [comment]
同上，我也遇到这个问题了，已经使用最新版本，依然存在该问题

**Comment by ToQuery** [comment]
database url 增加配置 `&autoReconnect=true` 即可

**Comment by Jaskey** [comment]
@chenh930330 1.1.16版本的什么参数能解决？

**Comment by chenh930330** [comment]
> @chenh930330 1.1.16版本的什么参数能解决？

我当初就把版本升级了，参数和我之前的版本是一样的

**Comment by chenh930330** [comment]
我当初就是更新了版本，没有改我老版本的配置




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/druid"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月3日(星期四) 下午4:36
收件人:&nbsp;"alibaba/druid"<druid@noreply.github.com&gt;;
抄送:&nbsp;"如若初见"<846784996@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/druid] druid 数据库连接断开，恢复正常后。不会重连 (#2678)





 
@chenh930330 1.1.16版本的什么参数能解决？

**Comment by wz2cool** [comment]
我们也遇到了 一定要重启应用才可以

**Comment by mulyzhou** [comment]
现在这个问题新版本解决了吗

**Comment by chenh930330** [comment]
没有尝试过，要是你试了有结果还希望能告知一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/druid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月12日(星期五) 上午10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/druid] druid 数据库连接断开，恢复正常后。不会重连 (#2678)





 
现在这个问题新版本解决了吗

**Comment by zhangtao546** [comment]
这边用的1.1.14版本,也出现了这种,然后紧接着服务就崩了.

**Comment by wu2733** [comment]
> 服务器出现问题，服务被关闭。然后在数据库服务恢复正常后，应用 未重连数据库，必须重启应用服务，才能连上数据库@spjich

可以看一下是不是别的连接池用了druid的连接池，我们应用是因为使用了jta-atomikos做分布式事务，底层连接池druid。分布式事务使用druid时没有及时更新状态，jta的连接池默认一分钟才刷新的，有时间差，一开始没注意，生产环境就只能重启来解决

**Comment by shenjianeng** [comment]
这是来自邮箱的自动回复邮件，我已收到邮件。-------------------------------------------------

**Comment by tzszhzx** [comment]
为了防止未来的人依然不知道答案，我这里亲测有效
请配置：
break-after-acquire-failure = false，则会在数据库恢复后，自动重连

**Comment by lixiaofengCH** [comment]
自己写一个对连接池 CreateConnectionThread 的存活检测方法，每次获取连接的时候先去检测下该线程的状态，如果该线程已经死掉，则直接close连接池，然后重新创建，可以解决数据库重启后需要重启应用的问题。

CreateConnectionThread 的存活检测机制：

public static boolean checkDataSourceFailContinuousStatus(DruidDataSource dataSource) {
if (!dataSource.isBreakAfterAcquireFailure()) {
log.info("this data source does not open BreakAfterAcquireFailure");
return false;
}
boolean failContinuous = dataSource.isFailContinuous(); // fail over retry attempts
boolean createConnectionThreadIsAlive = true;
try {
CreateConnectionThread createConnectionThread = getCreateConnectionThread(dataSource);
createConnectionThreadIsAlive = createConnectionThread.isAlive();
} catch (Exception e) {
log.error("Get dataSource: " + dataSource + "'s createConnectionThread fails.");
}
return failContinuous && !createConnectionThreadIsAlive;
}

public static CreateConnectionThread getCreateConnectionThread(DruidDataSource dataSource)
throws NoSuchFieldException, IllegalAccessException {
Field createConnectionThread = dataSource.getClass().getDeclaredField("createConnectionThread");
createConnectionThread.setAccessible(true);
CreateConnectionThread createConnectionThreadInstance = (CreateConnectionThread) createConnectionThread
.get(dataSource);
log.info("Get dataSource: {}'s createConnectionThread: {}", dataSource,
createConnectionThreadInstance);
return createConnectionThreadInstance;
}
