### ISSUE TITLE
Q:请教一下SpringBoot集成Druid的配置

### ISSUE THREAD

**Issue by asurada-gsx** [alibaba/druid#2691]
#### 您好，请问使用spring-boot-starter 模块以后，在yml中配置相关参数以后，是否需要再写Config类并且调用@Configuration注解进行初始化配置呢？
- 目前使用yml进行配置
- 配置文件类似示例中的配置文件
- 不使用Config类的情况下配置是可以生效的
- Junit4进行单元测试时，不使用Config类的工程会提示Failed to determine a suitable driver class，
使用过的一切正常。
- 版本：spring boot 2.0， Druid 1.1.10

**Comment by asurada-gsx** [comment]
已解决

**Comment by baigod** [comment]
怎么解决的？

**Comment by app2smile** [comment]
> 怎么解决的？

新建的项目默认application.yml是在classpath下面的.
我的解决思路是 提高这个文件的优先级,比如classpath下面新建config文件夹,application.yml放在这个config文件夹里面即可解决
