### ISSUE TITLE
改進schemaRepository 由jdbc metadata 讀取column 定義的能力

### ISSUE THREAD

**Issue by zone1511** [alibaba/druid#2702]
原本的schemaRepository 透過.console(ddl) 來讓druid 知道每個表有甚麼column. 除了這個方式以外 我們可以利用jdbc metadata 來做到同樣的目的

**Comment by zone1511** [comment]
@wenshao 可以接受這個PR 嗎?

**Comment by lizongbo** [comment]
代码距离现在太久了，不方便合并，因此关掉。
有需要的请重新提交新的pr
