### ISSUE TITLE
使用druid-spring-boot-starter后，如果在非application.yml的文件种配置连接池信息，则报错

### ISSUE THREAD

**Issue by rdzhaoxin** [alibaba/druid#2730]
DataSourceProperties 类种使用的ConfigurationProperties注解，这个注解默认只能读取application.yml文件中的信息。如果把连接池配置写在application-druid.yml中则读取不到，导致初始化失败

**Comment by lihengming** [comment]
这是 Spring Boot 的特性，你可以导入 application-druid.yml 啊。

**Comment by 1108080** [comment]
@lihengming 嗯。我就是想问一下，有什么有什么简单的做法。

**Comment by lihengming** [comment]
1. 使用 spring.profiles.include 将该配置加入主配置中
2. 如果这个配置文件在其他位置的话，可以使用 spring.config.location 
3. 使用 @PropertySource 导入该配置文件

你可以看下 Spring Boot 文档，我知道的大概就这些了。当然，修改 Stater 的代码也是可以的，将 Druid 的配置作为配置项，但是没必要。

**Comment by 1108080** [comment]
@lihengming 感谢

**Comment by 1108080** [comment]
@lihengming 使用spring.profiles.include一定要用个类去解析吗？不能直接在主yml里直接引入其他得yml文件吗？
@
