### ISSUE TITLE
能否在监控页面中去掉页面下方广告？

### ISSUE THREAD

**Issue by pangtouyuyyf** [alibaba/druid#2731]

**Comment by hongerwei** [comment]
是啊，广告很烦人啊

**Comment by ionething** [comment]
广告是很烦人，说一下我的想法
1. 要改源码，参照这个版本的提交 [2e275a4a79f4240bebec49abbc6261467746d9e4](https://github.com/alibaba/druid/commit/2e275a4a79f4240bebec49abbc6261467746d9e4)
2. 使用1.1.4之前的版本，貌似是在这个1.1.4这个版本加的
3. 项目里用干净的common.js覆盖，路径是/druid/js/common.js
4. 静态服务器直接把这个/druid/js/common.js文件定向到干净的common.js
5. 通过过滤器或者AOP把/druid/index.html里面的标签里的common.js替换为干净的js路径，或者往html里添加一个自定义的js来处理

> 利益无关，个人建议，没有实践，仅供参考

**Comment by ionething** [comment]
> 广告是很烦人，说一下我的想法
> 
> 1. 要改源码，参照这个版本的提交 [2e275a4a79f4240bebec49abbc6261467746d9e4](https://github.com/alibaba/druid/commit/2e275a4a79f4240bebec49abbc6261467746d9e4)
> 2. 使用1.1.4之前的版本，貌似是在这个1.1.4这个版本加的
> 3. 项目里用干净的common.js覆盖，路径是/druid/js/common.js
> 4. 静态服务器直接把这个/druid/js/common.js文件定向到干净的common.js
> 5. 通过过滤器或者AOP把/druid/index.html里面的标签里的common.js替换为干净的js路径，或者往html里添加一个自定义的js来处理
> 
> > 利益无关，个人建议，没有实践，仅供参考

实践了一下 想用的可以用用 https://github.com/ionething/fuck-druid-ad
