### ISSUE TITLE
关于监控sql语句常量显示成问号的问题

### ISSUE THREAD

**Issue by yangpancode** [alibaba/druid#2780]
在使用druid monitor的过程中，sql监控出现sql语句等号后面显示成问号（“？”），如sql语句是select t.* from test t where t.id = '1' and t.value =#{value,jdbcType=VARCHAR}  执行之后会变成 select t.* from test t where t.id = ？ and t.value = ？。本来 id = '1' 是写死的常量，也显示成了问号。

**Comment by jaywongdev** [comment]
怎么回事啊？我也遇到了
