### ISSUE TITLE
druid 每次执行sql 都需要从缓存中拿连接和放回连接，影响效率

### ISSUE THREAD

**Issue by xz65669983** [alibaba/druid#2802]
比如我现在要插入一万条数据。这样每次都要从连接池中拿和还一万次。影响效率30%左右。能否有方法，只拿一条连接做完所有的插入语句后，在把连接还回给连接池呢？

**Comment by choaklin** [comment]
如果是用ORM框架实现，ORM要支持批量存储完1万条再关闭连接；
如果是自己操作数据源实现数据插入，那就自己判断吧

**Comment by RafaelGuo** [comment]
为什么不批量更新呢？

**Comment by lizongbo** [comment]
自己开启事务模式，或者自己拿到连接一直使用，然后手工close归还。
