### ISSUE TITLE
动态切换多数据源

### ISSUE THREAD

**Issue by smokedog2** [alibaba/druid#2807]
hi,我正在使用druid作为我的数据库连接池，我现在遇到了一个问题，怎么去动态切换多个数据源，我的项目服务20个城市，每个城市对应三个业务库，怎么能根据url里面的城市参数动态切换到对应城市的库。
项目采用spring boot mybatis druid

我也知道有这么个东西AbstractRoutingDataSource，但是看了网上大部分实现，都是预先创建好所有的datasource

有任何想法么，万分感谢！

**Comment by majintao** [comment]
兄弟，解决了么；求方案共享。 哈哈

**Comment by smokedog2** [comment]
@majintao  最后没有使用druid,还是使用原始的AbstractRoutingDataSource实现动态数据源切换
