### ISSUE TITLE
wall filter sql injection violation

### ISSUE THREAD

**Issue by 515445681** [alibaba/druid#2819]
sql injection violation, part alway true condition not allow : SELECT COUNT(1) FROM sys_role WHERE deleted = 0 AND 1 = 1

**Comment by Guzi219** [comment]
conditionAndAlwayTrueAllow | false | 检查查询条件(WHERE/HAVING子句)中是否包含AND永真条件
-- | -- | --

**Comment by 515445681** [comment]
好的，多谢。
