### ISSUE TITLE
密码没有解密

### ISSUE THREAD

**Issue by ywzou** [alibaba/druid#2856]
java.sql.SQLException: Access denied for user 'root'@'ywzou' (using password: YES)

application.yml

public-key:
spring:
  datasource:
    druid:
      url:“”
      username: root
      password: “”
      driver-class-name: com.mysql.cj.jdbc.Driver
      connect-properties: config.decrypt=true;config.decrypt.key=${public-key}
     filter:
        stat:
          slow-sql-millis: 5000
          log-slow-sql: true
        config:
          enabled: true

**Comment by Lanceff** [comment]
我也遇到这个问题
