### ISSUE TITLE
使用mybatis向mysql插入数据报错，druid版本1.1.9

### ISSUE THREAD

**Issue by zhb1993** [alibaba/druid#2874]
`INSERT` INTO czn_car_model_detail (
	    model_id,
	    driver_mode, 
	    displacement, 
	    power_type, 
	    maximum_power, 
	    maximum_torque, 
	    body_structure, 
	    year, 
	    maximum_speed,
	    acceleration_time, 
	    length, 
	    width, 
	    height, 
	    weight, 
	    wheel_base, 
	    minimum_gap, 
	    front_gauge, 
	    track_rear,
	    door_num, 
	    capacity, 
	    max_capacity, 
	    create_time
	 ) SELECT (
		    #{modelId},
	      	#{driverMode}, 
	      	#{displacement}, 
	      	#{powerType}, 
	      	#{maximumPower}, 
	      	#{maximumTorque}, 
	      	#{bodyStructure}, 
	      	#{year}, 
	      	#{maximumSpeed}, 
	      	#{accelerationTime}, 
	      	#{length}, 
	      	#{width}, 
	      	#{height}, 
	      	#{weight}, 
	      	#{wheelBase}, 
	      	#{minimumGap}, 
	      	#{frontGauge}, 
	      	#{trackRear}, 
	      	#{doorNum}, 
	      	#{capacity}, 
	      	#{maxCapacity}, 
	      	#{createTime}
      FROM
		DUAL
	WHERE 
		NOT EXISTS(
			SELECT 
				model_id 
			FROM 
				czn_car_model_detail 
			WHERE 
				model_id=#{modelId}
		)
执行报错  sql injection violation, syntax error: syntax error, expect RPAREN, actual FROM pos 708, line 46, column 11, token FROM : INSERT INTO czn_car_model_detail ( model_id,
	    driver_mode, 
	    displacement, 
	    power_type, 
	    maximum_power, 
	    maximum_torque, 
	    body_structure, 
	    year, 
	    maximum_speed,
	    acceleration_time, 
	    length, 
	    width, 
	    height, 
	    weight, 
	    wheel_base, 
	    minimum_gap, 
	    front_gauge, 
	    track_rear,
	    door_num, 
	    capacity, 
	    max_capacity, 
	    create_time
	 ) SELECT (
		    ?,
	      	?, 
	      	?, 
	      	?, 
	      	?, 
	      	?, 
	      	?, 
	      	?, 
	      	?, 
	      	?, 
	      	?, 
	      	?, 
	      	?, 
	      	?, 
	      	?, 
	      	?, 
	      	?, 
	      	?, 
	      	?, 
	      	?, 
	      	?, 
	      	?
      FROM
		DUAL
	WHERE 
		NOT EXISTS(
			SELECT 
				model_id 
			FROM 
				czn_car_model_detail 
			WHERE 
				model_id=?
		)

请问是什么原因呢

**Comment by zhb1993** [comment]
不好意思，我自己不仔细，写错了

**Comment by wangning08115** [comment]
#
