### ISSUE TITLE
initialSize、minIdle的区别是什么？

### ISSUE THREAD

**Issue by ChujuanXie** [alibaba/druid#2885]
https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE
参考配置中没有明确提到initialSize、minIdle的区别，字面意思是初始化大小、最小。
有没有大佬解答一下，
1、假设initialSize小于minIdle，是不是应用初始化时会拿initialSize，然后慢慢升到minIdle？如果initialSize已经够用了，连接数还会升到minIdle吗？还是一直保持在initialSize呢？
2、假设initialSize大于minIdle，是不是应用初始化时会拿initialSize，如果initialSize已经够用了，甚至有空余，连接数会慢慢降到到minIdle？

**Comment by hw-mm-payment** [comment]
同问，是否支持动态修改minIdle，实时生效呢？

**Comment by iceqing** [comment]
参考这里：
[Druid中的maxIdle为什么是没用的？](https://github.com/alibaba/druid/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#16-druid%E4%B8%AD%E7%9A%84maxidle%E4%B8%BA%E4%BB%80%E4%B9%88%E6%98%AF%E6%B2%A1%E7%94%A8%E7%9A%84)

**Comment by lizongbo** [comment]
对应以下场景： initialSize=4， minIdle=10  启动的时候会先创建4个连接，然后异步任务再创建5个。
对应以下场景： initialSize=10， minIdle=4  启动的时候会先创建10个连接，然后异步任务会回收掉6个.
