### ISSUE TITLE
SLF4j的debug日志打成了error级别

### ISSUE THREAD

**Issue by Matrix0xCC** [alibaba/druid#2889]
https://github.com/alibaba/druid/blob/475a848d6f4c93beebc8e121d7160f0b5044eba9/src/main/java/com/alibaba/druid/support/logging/SLF4JImpl.java#L84

看其他日志类的实现，应该不是有意为之。

**Comment by suyuan1980** [comment]
![image](https://user-images.githubusercontent.com/12935753/63241634-06162980-c287-11e9-9b2b-0ffb280ac5ab.png)

**Comment by lizongbo** [comment]
已经修复bug，请使用最新版验证
