### ISSUE TITLE
Spring boot版本

### ISSUE THREAD

**Issue by jifengnan** [alibaba/druid#2898]
有个疑惑，为什么1.1.10中依赖中的spring boot版本还是1.x呢。
<spring-boot.version>1.5.12.RELEASE</spring-boot.version>

**Comment by TianEnPang** [comment]
是啊，求更新！！！
现在还遇到个**“maxEvictableIdleTimeMillis must be grater than minEvictableIdleTimeMillis”**的问题
需要自己手动配置这两个属性吗？
