### ISSUE TITLE
请问有什么方式能将读取出的AST进行加工后重新生成SQL?

### ISSUE THREAD

**Issue by doukai** [alibaba/druid#2907]
我想在AST中做一些修改，比如添加查询条件，之后生成新的SQL，请问有什么方法没，感谢~

**Comment by frank-zx** [comment]
请问怎么做的？解决了吗

**Comment by doukai** [comment]
@frank-zx 通过SchemaStatExtVisitor对象可以获得SQLSelectQueryBlock SQLUpdateStatement SQLDeleteStatement这三个工具类，他们都有addCondition removeCondition addWhere等方法。可以通过这种方式实现对SQL的重新构建
