### ISSUE TITLE
maxOpenPreparedStatements与druid.maxPoolPreparedStatementPerConnectionSize

### ISSUE THREAD

**Issue by wsw0108** [alibaba/druid#2920]
druid version: 1.1.9

从代码来看，这两个配置的是一个意思，不过[配置文档](https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8)里，写的是`maxPoolPreparedStatementPerConnectionSize`，而不是`druid.maxPoolPreparedStatementPerConnectionSize`或者`maxOpenPreparedStatements`。

**Comment by gMan1990** [comment]
https://github.com/alibaba/druid/wiki/DruidDataSource配置
```<property name="maxOpenPreparedStatements" value="20" />```这样写配置不进去的

**Comment by gMan1990** [comment]
```maxPoolPreparedStatementPerConnectionSize | -1```
缺省值，代码里默认10，（不过不影响，poolPreparedStatements默认false

**Comment by wsw0108** [comment]
但是配置`poolPreparedStatements`为`true`且`maxPoolPreparedStatementPerConnectionSize`为某个指定的值的话，这个指定的值是不会生效的，因为druid期待的配置项是`druid.maxPoolPreparedStatementPerConnectionSize`(通过System Property等)或`maxOpenPreparedStatements`
