### ISSUE TITLE
【SQL 解析错误】create table customer(id int,name varchar(20), PRIMARY KEY (`id`) USING BTREE )

### ISSUE THREAD

**Issue by kaikai2000** [alibaba/druid#2941]
- create table customer(id int,name varchar(20), PRIMARY KEY (`id`)  USING BTREE） 解析错误

- create table customer(id int,name varchar(20), PRIMARY KEY USING BTREE (`id`))解析正确

**Comment by aiic03** [comment]
> * create table customer(id int,name varchar(20), PRIMARY KEY (`id`)  USING BTREE） 解析错误
> * create table customer(id int,name varchar(20), PRIMARY KEY USING BTREE (`id`))解析正确

代码中有说明。

https://github.com/alibaba/druid/blob/master/src/main/java/com/alibaba/druid/sql/dialect/mysql/parser/MySqlCreateTableParser.java#L979

** 5.5语法 USING BTREE 放在index 名字后 **

**Comment by aiic03** [comment]
关掉吧

**Comment by kaikai2000** [comment]
那个中文"**）**"是仅仅这个issue写的笔误。SQL正确的情况下，报下面错误：
![image](https://user-images.githubusercontent.com/73138/49493878-b4fd0b80-f898-11e8-8732-1f47a4401673.png)

**Comment by aiic03** [comment]
@kaikai2000 
hi 我使用druid 1.1.12 和如下测试代码，没有发现解析错误呢~
![image](https://user-images.githubusercontent.com/11695765/49494431-9dbf1d80-f89a-11e8-8b2c-d1286be9604e.png)

```java
@Test
public void test2() {
    // using druid 1.1.12
    String sql = "create table customer(id int,name varchar(20), PRIMARY KEY (id) USING BTREE)";
    List<SQLStatement> sqlStatements = SQLUtils.parseStatements(sql, "mysql");
    System.out.println(sqlStatements);
    // output
    // [CREATE TABLE customer (
    //	id int,
    //	name varchar(20),
    //	PRIMARY KEY USING BTREE (id)
    // )]
}
```

**Comment by kaikai2000** [comment]
是我版本搞错了，新版本确实没用问题，sorry!

**Comment by MrChowXavier** [comment]
这个bug是在哪个版本修复的？

**Comment by MrChowXavier** [comment]
> 这个bug是在哪个版本修复的？

1.1.10是有这个bug的
