### ISSUE TITLE
DruidDataSource关闭资源未释放

### ISSUE THREAD

**Issue by chengyulcy** [alibaba/druid#2948]
DruidDataSource 初始化成功后，代码中检测到数据源ip不同后会切换到新的数据源，但是出现切换过程中DruidDataSource 仍然使用旧的数据源，要一段时间才切换到新的数据源。

[2018-11-30 14:58:49,175]--[INFO]--[localhost-startStop-1]--[DruidDataSource.java init() 922] - {dataSource-1} inited
[2018-11-30 15:03:05,259]--[INFO]--[HDC-ThreadPool-Monitor3]--[DruidDataSource.java close() 1817] - {dataSource-1} closed
[2018-11-30 15:03:06,694]--[INFO]--[HDC-ThreadPool-36]--[DruidDataSource.java init() 922] - {dataSource-2} inited
[2018-11-30 15:03:08,200]--[ERROR]--[Druid-ConnectionPool-Create-399440805]--[DruidDataSource.java run() 2453] - create connection SQLException, url: jdbc:postgresql://8.5.46.70:5432/hdcdb, errorCode 0, state 08001 

8.5.46.70为初始化数据源，2018-11-30 15:03:05,259检测到数据源不同后把数据源close，然后重新初始化一个新的数据源（切换了一个ip地址），但是2018-11-30 15:03:08,200应用在使用过程中仍然使用老的数据源。

疑问：DruidDataSource close后数据源未释放资源，导致应用请求使用旧的数据源。

Druid配置为：
<bean id="dataSource" class="com.huawei.hdc.db.datasource.VDSDataSourceImpl" init-method="init"
		destroy-method="close">
		<property name="driverClassName" value="${driverClass}" />
		<property name="jdbcUrl" value="${jdbcUrl}" />
		<property name="username" value="${username}" />
		<property name="password" value="${password}" />
		<property name="initialSize" value="5" />
		<property name="minIdle" value="5" /> 
		<property name="maxActive" value="60" />
		<property name="maxWait" value="60000" />
		<property name="timeBetweenEvictionRunsMillis" value="60000" />
		<property name="minEvictableIdleTimeMillis" value="300000" />
		<property name="validationQuery" value="SELECT 'x'" />
		<property name="testWhileIdle" value="true" />
		<property name="testOnBorrow" value="false" />
		<property name="testOnReturn" value="false" />
		<property name="poolPreparedStatements" value="true" />
		<property name="maxPoolPreparedStatementPerConnectionSize" value="100" />
		<property name="filters" value="wall"/>
	</bean>

**Comment by chengyulcy** [comment]
java.net.SocketInputStream.socketRead0 行: 不可用 [本地方法]
   java.net.SocketInputStream.socketRead 行: 116 
   java.net.SocketInputStream.read 行: 171 
   java.net.SocketInputStream.read 行: 141 
   org.postgresql.core.VisibleBufferedInputStream.readMore 行: 143 
   org.postgresql.core.VisibleBufferedInputStream.ensureBytes 行: 112 
   org.postgresql.core.VisibleBufferedInputStream.read 行: 71 
   org.postgresql.core.PGStream.ReceiveChar 行: 272 
   org.postgresql.core.v3.QueryExecutorImpl.processResults 行: 1753 
   org.postgresql.core.v3.QueryExecutorImpl.execute 行: 348 
   org.postgresql.jdbc2.AbstractJdbc2Statement.execute 行: 545 
   org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags 行: 405 
   org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery 行: 285 
   com.alibaba.druid.pool.vendor.PGValidConnectionChecker.isValidConnection 行: 65 
   com.alibaba.druid.pool.DruidAbstractDataSource.testConnectionInternal 行: 1358 
   com.alibaba.druid.pool.DruidDataSource.getConnectionDirect 行: 1291 
   com.alibaba.druid.filter.FilterChainImpl.dataSource_connect 行: 4619 
   com.alibaba.druid.filter.FilterAdapter.dataSource_getConnection 行: 2745 
   com.alibaba.druid.filter.FilterChainImpl.dataSource_connect 行: 4615 
   com.alibaba.druid.pool.DruidDataSource.getConnection 行: 1225 
   com.alibaba.druid.pool.DruidDataSource.getConnection 行: 1217 
   com.alibaba.druid.pool.DruidDataSource.getConnection 行: 90 
原因是有业务在旧数据源未失效（ip不可达）时建立了连接并等待接收数据，数据源失效后切换到新数据源，但是原来的业务仍然等待原来的连接传输数据
设置了 druidDataSource.setConnectionProperties("socketTimeout=60000;connectTimeout=5000");也不生效

Druid适应业务中途数据源ip不可达，业务自动切换到新的ip去，如何保证旧ip创建的链路被强制清理掉，不会有业务卡在等待旧连接数据传输中，这种场景如何配置Druid。

**Comment by chengyulcy** [comment]
初始化是直接DruidDataSource druidDataSource = new DruidDataSource();创建个数据源，然后设置好配置。
然后有个定时器通过jdbc连接方式检测ip是否故障，故障切换至另外一个ip，
切换是将之前的数据源关闭druidDataSource.close()，然后重新创建一个数据源DruidDataSource druidDataSource = new DruidDataSource();

目前发现好像是切换前如果有业务请求使用了数据源连接数据库，业务不会立即切换至新数据源，新业务会使用新数据源连接，我这边是通过hibernate操作数据库的，在hiberate中配置了druid数据源。

**Comment by dandanheng** [comment]
目前也遇到这个问题,请问有解决方案了吗

**Comment by wo8335224** [comment]
@chengyulcy 你动态创建datasource ，像sessionfactory引用的datasource没有发生故障吗？我也遇到了这种需求，但是没思路。

**Comment by lizongbo** [comment]
应该是你的dao类这些持有了旧数据源。
