### ISSUE TITLE
SQL parse incorrect: SELECT * FROM a order by id,name OFFSET 10

### ISSUE THREAD

**Issue by chensongIntel** [alibaba/druid#2966]
SQLUtils.parseStatements("SELECT * FROM a order by id,name OFFSET 10", MySQL);

com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'FSET 10;', expect IDENTIFIER, actual IDENTIFIER pos 39, line 1, column 40, token IDENTIFIER OFFSET

MySQL paser prints as below,
mysql> select * from a order by name offset 12;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that
corresponds to your MySQL server version for the right syntax to use near 'offse
t 12' at line 1

**Comment by lizongbo** [comment]
这个sql语法是错的，当然用最新版druid sql解析不会报错了，但是丢弃了offset信息

```
    @Test
    public void test_offset() throws Exception {
        for (DbType dbType : new DbType[]{DbType.mysql}) {
            String sql = "select * from a order by name offset 12";
            SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, dbType);
            SQLStatement statement = parser.parseStatement();
           // OracleMultiInsertStatement multiInsertStatement = (OracleMultiInsertStatement) statement;
            System.out.println("原始的sql===" + sql);
            System.out.println("statement===" + statement.getClass());
            String newSql = statement.toString();
            System.out.println("生成的sql===" + newSql);

        }
    }
```

执行结果：
原始的sql===select * from a order by name offset 12
statement===class com.alibaba.druid.sql.ast.statement.SQLSelectStatement

生成的sql===SELECT *
FROM a
ORDER BY name
