### ISSUE TITLE
springboot2.1.1 单独配置不生效

### ISSUE THREAD

**Issue by SoberChina** [alibaba/druid#2975]
spring boot version:2.1.1.RELEASE
断点下调试:
![image](https://user-images.githubusercontent.com/10227558/50078408-deffe780-0221-11e9-9b81-49565d6d653a.png)
配置信息
![image](https://user-images.githubusercontent.com/10227558/50078482-14a4d080-0222-11e9-8695-d254d1263690.png)

**Comment by LuBan-Liu** [comment]
spring boot 2.1.1  使用的是哪个druid版本？

**Comment by SoberChina** [comment]
druid version :1.1.10  
支持2.x版本

**Comment by wangxinpier** [comment]
我试过了，好用，但是多数据源可以有问题，也许是我不太会用

**Comment by SoberChina** [comment]
@wangxinpier 手动配置的？

**Comment by lizongbo** [comment]
请使用最新版验证
