### ISSUE TITLE
sql解析INTERVAL -"5" 错误

### ISSUE THREAD

**Issue by jingshanglu** [alibaba/druid#2984]
select id,orderId,taskType,taskData,retryCount,extJson,businessId from task_0029  where taskStatus=0 and taskType='29' AND createDate < DATE_ADD(utc_date(), INTERVAL -'5' DAY) limit 0,1000;

com.alibaba.druid.sql.parser.ParserException: TODO : pos 170, line 1, column 168, token LITERAL_CHARS 5

把 -"5" 改成"-5" 才行

**Comment by jingshanglu** [comment]
这个在mysql中是可以执行的

**Comment by wenshao** [comment]
已经支持，将会在元旦期间发布新版本

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.13 问题已修复，请用新版本
