### ISSUE TITLE
DruidDataSourceStatLoggerImpl中生成日志时的bug

### ISSUE THREAD

**Issue by PengShangwen** [alibaba/druid#2985]
public void log(DruidDataSourceStatValue statValue)方法中存在如下bug：
![selection_003](https://user-images.githubusercontent.com/10007891/50321267-0baa4c80-050b-11e9-981b-018a40c94250.png)
    if (sqlStat.getFetchRowCount() > 0) {
                    sqlStatMap.put("fetchRowCount", sqlStat.getFetchRowCount());
                    sqlStatMap.put("fetchRowCount", sqlStat.getFetchRowCountMax());
                    sqlStatMap.put("fetchRowHistogram", rtrim(sqlStat.getFetchRowHistogram()));
    }
在if语句块的第二行，显然，"fetchRowCount"应为"fetchRowCountMax"

**Comment by wenshao** [comment]
感谢你发现这个问题，希望你下次直接提交Pull Request
