### ISSUE TITLE
希望在接口DruidDataSourceMBean中提供getJDBCUrl方法

### ISSUE THREAD

**Issue by PengShangwen** [alibaba/druid#2986]
我在使用JMX收集DruidDataSource数据时，希望能同时收集到其JDBCUrl，因为我配备了多个数据源。但使用JMX时只能和DruidDataSourceMBean打交道，其并没有提供getJDBCUrl方法。因而，我希望该接口能提供这个方法。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.13 问题已修复，请用新版本

**Comment by Elderry** [comment]
@PengShangwen @wenshao 我配置多数据源后，jmx 中只出现了一个数据源的数据，请问如何解决？
![image](https://user-images.githubusercontent.com/1892221/59318795-dbde4380-8cfa-11e9-8b5b-9faba35224b0.png)
