### ISSUE TITLE
插入数据之后，然后在同一个方法中更新这条数据，如果中间时间太长，会报错

### ISSUE THREAD

**Issue by patience00** [alibaba/druid#2990]
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: interrupt
试过很多次了，去掉druid就不会报错，加了druid就报错，插入和更新用的是同一个连接导致的？该如何解决这个问题啊？？下面是我的配置
![image](https://user-images.githubusercontent.com/35128024/50398338-a926aa00-07b1-11e9-8050-227a7d55bd1f.png)

**Comment by patience00** [comment]
![image](https://user-images.githubusercontent.com/35128024/50398503-0bcc7580-07b3-11e9-97cc-5c19c61b39c1.png)
更新成了这个配置，也会报错，注释掉所有druid的配置包括依赖，就没有问题！

**Comment by patience00** [comment]
下面是伪代码：
@Override
    public TaskLog getExcutedTaskLog(Long taskId, Long executeTime) {
        TaskLog taskLog = taskLogMapper.getExcutedTaskLog(taskId, executeTime - TEN_SECEONDS_MILLS, executeTime + TEN_SECEONDS_MILLS);
        if (taskLog == null) {
            taskLog = TaskLog.builder()
                    .taskId(taskId)
                    .executeTime(System.currentTimeMillis())
                    .logDetail("插入记录")
                    .status(1)
                    .build();
            taskLogMapper.insert(taskLog);
        }
        log.info("tasklog===" + taskLog);

        return taskLog;
    }

然后在别的地方调用
        TaskLog taskLog = taskLogService.getExcutedTaskLog();
        taskLog.setExecuteTime(System.currentTimeMillis());
        taskLogMapper.updateById(taskLog);
执行到最后一个更新语句就会报这个错误

**Comment by hipilee** [comment]
你好，你的问题最后解决了么？我遇见了同样的问题。感觉突然就执行不了。有些时候又可以执行通过过

**Comment by patience00** [comment]
> 你好，你的问题最后解决了么？我遇见了同样的问题。感觉突然就执行不了。有些时候又可以执行通过过

你是不是用了其他什么框架,线程中断了,关闭了数据库连接就会报这个,当时是用了xxl-job任务超时,导致的

**Comment by panchw** [comment]
我们也到了同样的问题，也是使用XXJOB，但是执行器的超时时间设置的是0（永不超时）想问下后来您那边调整哪个参数解决的这个问题还能回忆起来吗？

**Comment by patience00** [comment]
> 我们也到了同样的问题，也是使用XXJOB，但是执行器的超时时间设置的是0（永不超时）想问下后来您那边调整哪个参数解决的这个问题还能回忆起来吗？
看一下数据库的连接配置,是不是用了druid

**Comment by panchw** [comment]
是，也是XXJOB + Druid

**Comment by panchw** [comment]
> > 我们也到了同样的问题，也是使用XXJOB，但是执行器的超时时间设置的是0（永不超时）想问下后来您那边调整哪个参数解决的这个问题还能回忆起来吗？
> > 看一下数据库的连接配置,是不是用了druid
是，也是XXJOB + Druid

**Comment by yonoel** [comment]
> > > 我们也到了同样的问题，也是使用XXJOB，但是执行器的超时时间设置的是0（永不超时）想问下后来您那边调整哪个参数解决的这个问题还能回忆起来吗？
> > > 看一下数据库的连接配置,是不是用了druid
> > > 是，也是XXJOB + Druid


遇到了一样的问题，这个异常时有时无。。。

**Comment by callmeqingzhi** [comment]
确实是XXL-JOB超时设置的问题，设置为0（不超时），就没问题了

**Comment by XiaoAfei1024** [comment]
> 确实是XXL-JOB超时设置的问题，设置为0（不超时），就没问题了

XXJOB + Druid 修改XXL-JOB超时设置可以解决

**Comment by XiaoAfei1024** [comment]
> 确实是XXL-JOB超时设置的问题，设置为0（不超时），就没问题了
XXJOB + Druid 
修改XXL-JOB超时设置，设置为0
可以解决如下异常了吗？
Could not get JDBC Connection; nested exception is java.sql.SQLException: interrupt

**Comment by kangwen** [comment]
Same situation
