### ISSUE TITLE
版本1.0.28怎么配置关闭统计？

### ISSUE THREAD

**Issue by guangsheng-hu** [alibaba/druid#3008]
去掉filter的stat还是能看到druid/index.html页面，
看有同学说下面图的两个配置，但是1.0.28版本中没有这两个配置
![image](https://user-images.githubusercontent.com/13634356/50634930-278e0380-0f8b-11e9-87ad-314e22584817.png)

**Comment by lizongbo** [comment]
把以下3个配置项从配置文件中删除即可，请使用最新版验证
```

spring.datasource.druid.filter.stat.enabled=true
spring.datasource.druid.stat-view-servlet.enabled=true
spring.datasource.druid.web-stat-filter.enabled=true

```
