### ISSUE TITLE
druid-spring-boot-starter 1.1.10 配置bug

### ISSUE THREAD

**Issue by xwcxie** [alibaba/druid#3011]
druid:
    min-evictable-idle-time-millis: 60000 
    max-evictable-idle-time-millis: 300000 

在autoconfig下由于spring boot是通过反射注入属性值,class.getDeclaredMethods 获取对应的methods是随机顺序的,如果先设置max-evictable-idle-time-millis ,由于min-evictable-idle-time-millis 默认值是1800000L,所以会出现 maxEvictableIdleTimeMillis must be grater than minEvictableIdleTimeMillis

**Comment by lizongbo** [comment]
请使用最新版验证
