### ISSUE TITLE
【共享连接池】单应用连接同一mysql数据库服务器，只是要动态切换scheme，共享一个连接池，druid能够支持么？

### ISSUE THREAD

**Issue by majintao** [alibaba/druid#3012]
【共享连接池】单应用连接同一mysql数据库服务器，只是要动态切换scheme，共享一个连接池，druid能够支持么？

需求：连接同一mysql服务器，根据请求切换scheme，不想配置多个druid连接池来连接，怎么用单一TCP连接池么共享么？

**Comment by wenshao** [comment]
动态执行use

**Comment by majintao** [comment]
jdbc:mysql://<host>:<port>/<database_name>     后面的database_name只是说明sql默认的scheme，最终还是可以用use 来使用到其他数据库对吧

**Comment by lizongbo** [comment]
mysql的可以调用setSchema方法了。请使用最新版验证
