### ISSUE TITLE
Springboot 集成后使用 Gradle 打包报错

### ISSUE THREAD

**Issue by onekr-billy** [alibaba/druid#3015]
Errors occurred while build effective model from /root/.gradle/caches/modules-2/files-2.1/com.alibaba/druid/1.1.10/ac5e374df42891b0c31e2247e1cc71802f023677/druid-1.1.10.pom:
    'dependencies.dependency.systemPath' for com.alibaba:jconsole:jar must specify an absolute path but is ${env.JAVA_HOME}/lib/jconsole.jar in com.alibaba:druid:1.1.10
    'dependencies.dependency.systemPath' for com.alibaba:tools:jar must specify an absolute path but is ${env.JAVA_HOME}/lib/tools.jar in com.alibaba:druid:1.1.10

环境是：
jdk 11 + springboot 2.1.1 + gradle5

**Comment by lehug** [comment]
同样求助，我是mac环境，用的jenv，可否支持下这种场景，从jenv里面走

**Comment by lizongbo** [comment]
请使用最新版验证
