### ISSUE TITLE
基于druid生成AST树自己实现Visitor

### ISSUE THREAD

**Issue by KGfromchina** [alibaba/druid#3017]
背景是这样的,项目想在一些异构存储上封装一套统一的sql,对用户屏蔽异构存储的一些细节.目前想基于druid现有的代码基础上自己实现Visitor或者Visitor部分方法,想问下是否有相关指导文档

**Comment by wanghy0411** [comment]
去了解一下antlr吧

**Comment by lizongbo** [comment]
自己看druid源代码
