### ISSUE TITLE
解析含有复杂数据结构的hql时报错

### ISSUE THREAD

**Issue by mengya22** [alibaba/druid#3018]
麻烦请教，
含有复杂数据类型的sql解析报错，请问是目前不支持么？还是我的代码有问题
hql：
select  
	    field['id'].string_type as banner_id        
	   ,field['index'].string_type as banner_index   
	   ,field['pageName'].string_type as pageName     
from 
bdm_book.midu_xcx_web_main_log
where day = '2019-01-09'
and eventid = '151'
and cmd in ('26002','26003')
group by  field['id'].string_type 
	     ,field['index'].string_type 
	     ,field['pageName'].string_type ;

java 代码：
HiveStatementParser parser = new HiveStatementParser(hql);
 List<SQLStatement> stmtList = parser.parseStatementList();

第二行java代码抛异常：
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'	    field['id'].string_type as ban', expect LBRACKET, actual LBRACKET pos 20, line 2, column 12, token LBRACKET

**Comment by wenshao** [comment]
目前支持不完善，会补上支持

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.13 问题已修复，请用新版本
