### ISSUE TITLE
打印执行sql 括号丢失

### ISSUE THREAD

**Issue by fengyapeng** [alibaba/druid#3021]
- 你好，我使用mybaits，一下是 mybaits 的xml 查询。

`<select` id="selectDeptTree" `resultMap="sysDeptMap">`
        `   select * from sys_dept where del_flg = 0 and (`
        `<foreach collection="sysDeptEntities" item="entity" separator="or" >`
          `  ( lft &gt;= #{entity.lft} and rgt &lt;= #{entity.rgt} )`
       ` </foreach>`
       ` )`
   ` </select>`

生成的statment log 为：

`select * from sys_dept where del_flg = 0 and (
            ( lft >= ? and rgt <= ? )
         or 
            ( lft >= ? and rgt <= ? ) 
        )`
执行sql 的log 为：
`select *
from sys_dept
where del_flg = 0
	and (lft >= 18
		and rgt <= 25)
	or (lft >= 1
		and rgt <= 56)`
实际是按照statment 的log 执行的，不过打印的sql 会给错觉。

durid 版本为：1.1.12
mybatis 版本为：3.4.6

**Comment by lizongbo** [comment]
最新代码已经支持，等1.2.23版本验证
