### ISSUE TITLE
阿里的开源项目没有遵循“阿里编码规约”？

### ISSUE THREAD

**Issue by chenbo19867758** [alibaba/druid#3023]
通过“阿里编码规约”插件扫码出现很多提示。
阿里的开源项目没有遵循“阿里编码规约”？

**Comment by wenshao** [comment]
这个是历史原因，druid项目已经8年，项目比编码规约要早很多年，后续会考虑按照新的《阿里编码规约》重新格式化代码

**Comment by lizongbo** [comment]
后续来优化存量代码来尽量满足规范
