### ISSUE TITLE
Replace toArray(new T[size]) with toArray(new T[0])

### ISSUE THREAD

**Issue by hc-codersatlas** [alibaba/druid#3036]
Hi, noticed many occurrences of toArray that could be made faster with a find and replace.

Performance: replace toArray(new T[size]) with toArray(new T[0])

https://shipilev.net/blog/2016/arrays-wisdom-ancients/#_conclusion (also contains benchmarks).

Could provide some simple performance improvements thanks!

**Comment by wenshao** [comment]
for ArrayList, list.toArray(new String[list.size()]) has better performance than list.toArray(new String[0])

**Comment by hc-codersatlas** [comment]
Hi, did you read the linked article? It explicitly explains why new T[0] is faster than new T[size].
