### ISSUE TITLE
圣诞留彩蛋，Druid留广告，爱死阿里开源了！

### ISSUE THREAD

**Issue by yingwei-live** [alibaba/druid#3038]
阿里还缺这点钱？开源里面放广告,真是佩服!放广告对KPI有多大提高？

**Comment by aioair** [comment]
在哪位位置，围观一下。

**Comment by yingwei-live** [comment]
> 在哪位位置，围观一下。

配置好druid监控，就可以欣赏广告了

**Comment by it-noob** [comment]
确实有阿里云的广告

**Comment by jettyweb** [comment]
![image](https://user-images.githubusercontent.com/20220014/51722923-1c159000-2092-11e9-9983-6948df7ef9b0.png)

**Comment by yingwei-live** [comment]
> 下载jar包以后直接把它从网页中去掉好了

谢谢老兄，知道哪里去掉，不过就是觉得挺搞笑的。

**Comment by pkaq** [comment]
已投入光的怀抱~

**Comment by yosaku01** [comment]
@yingwei-live ,不能惯着它们，我现在也用hikariCP了

**Comment by codeex** [comment]
爱用不用，不用拉到，就这么牛逼！

**Comment by wenshao** [comment]
之后会提供一个去掉广告的文档，目前可以自己打包解决

**Comment by wenshao** [comment]
> 阿里还缺这点钱？开源里面放广告,真是佩服!放广告对KPI有多大提高？

这个是自己产品的广告
