### ISSUE TITLE
生产环境使用Druid内存很高,通过mat分析如下

### ISSUE THREAD

**Issue by xuzhouqqq** [alibaba/druid#3039]
mysql版本:5.6.29
mysql-connector版本:5.1.36
druid版本:1.0.15
生产环境的程序内存一直在涨，dump内存下来用mat分析发现上面提示
com.alibaba.druid.pool.DruidDataSource 这个类占用最多

![image](https://user-images.githubusercontent.com/14800016/51594636-dc369780-1f2f-11e9-99fa-abc0972a5b32.png)
![image](https://user-images.githubusercontent.com/14800016/51594646-e3f63c00-1f2f-11e9-9a6e-74029b9c98d0.png)

**Comment by 523966525** [comment]
程序里面连接都正常关闭了。仔细检查过业务代码。

**Comment by 523966525** [comment]
> 存在连接没关闭的情况？

程序里面连接都正常关闭了。仔细检查过业务代码。

**Comment by pc-fuqq** [comment]
我也存在类似的问题，暂时没找到问题所在

**Comment by Zakariy2019** [comment]
我也有这样的问题，已经在慢慢切换其他连接池了，不知道怎么解决

**Comment by lizongbo** [comment]
请使用最新版验证
