### ISSUE TITLE
对Mysql8的XA支持中有一段代码没有做空指针检查 导致跳过Mysql8  XA创建逻辑

### ISSUE THREAD

**Issue by likenamehaojie** [alibaba/druid#3045]
![image](https://user-images.githubusercontent.com/9814110/51781334-4890e100-2152-11e9-9252-9a40f9d7570c.png)
这是代码请修复
method_6_getValue 该方法没有判断是否为空

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.13 问题已修复，请用新版本
