### ISSUE TITLE
监控页面底部链接到了“澳门赌场”

### ISSUE THREAD

**Issue by wuuJiawei** [alibaba/druid#3050]
powered by AlibabaTech & sandzhang & melin & shrek.wang

其中sandzhang（http://www.sandzhang.com/）打开是澳门赌场

**Comment by NameCaosheng** [comment]
刚刚也发现了这个问题了

**Comment by NameCaosheng** [comment]
![image](https://user-images.githubusercontent.com/46740962/51823323-116d2c00-231a-11e9-90d9-96c860bb4c5e.png)

问题代码 都找到了   博主 是不是考虑下 把把广告给隐藏下啊

**Comment by wenshao** [comment]
正在跟进处理

**Comment by youuycom** [comment]
估计是域名过期了吧。。。

**Comment by wenshao** [comment]
> 1200个issues了，咋没有人回应。现在不维护了么？

一直维护，由于个人维护两个项目fastjson和druid，通常会交叉花时间维护。争取年前发布新版本。很多问题是不需要修复的，也欢迎你参与进来

**Comment by wenshao** [comment]
域名过期，正在跟进处理
