### ISSUE TITLE
监控信息是存在内存中吗

### ISSUE THREAD

**Issue by fantessti** [alibaba/druid#3057]
如果一直开启着存在内存中，后面会不会占用很大的资源，一般怎么处理

**Comment by wanglongbiao** [comment]
我感觉是在内存里，我有一个批量插入语句，字符串堆积的越来越大，到最后就崩了，正在找解决方法

**Comment by lizongbo** [comment]
是存在内存里，想要减少内容使用的话，需要开启merge sql的特性，或调低缓存上限
