### ISSUE TITLE
druid sqlparser卡住

### ISSUE THREAD

**Issue by yanshuai** [alibaba/druid#3058]
对于sql：
```
select job_names.job_name from cover_rage_job_org as org RIGHT JOIN (
 select job_names.job_name as job_name
    from (
    SELECT '1' as job_name
) job_name_all) as job_names on job_names.job_name = org.job_name
```
，sqlparser会卡住

`List<SQLStatement> sqlStatements = SQLUtils.parseStatements(sql, JdbcConstants.MYSQL);`
`for (SQLStatement sqlStatement : sqlStatements) {`
`                MySqlSchemaStatVisitor visitor = new MySqlSchemaStatVisitor();`
`                sqlStatement.accept(visitor);`
`}`

在com.alibaba.druid.sql.visitor.SchemaStatVisitor unwrapExpr 这个表达式上会卡住，
建议在825行附近增加逻辑：

`if (selectItem != null) {`
`  SQLExpr expr1 = selectItem.getExpr();`
`  if (expr1.equals(expr)) {`
`    break;`
`  }`
`  expr = expr1;`
`  continue;`
`}`

使用的是1.1.12的druid版本

**Comment by wenshao** [comment]
问题已修复，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.14
