### ISSUE TITLE
boot-druid 1.1.13不兼容boot-dubbo 0.2.0,页面无法访问,换为0.1.0的dubbo就好了

### ISSUE THREAD

**Issue by biuabiu** [alibaba/druid#3062]

**Comment by wenshao** [comment]
1.1.13缺省内置监控页面关闭

**Comment by lihengming** [comment]
看一下 Starter 文档，有说明怎么开启监控页面。

**Comment by lihengming** [comment]
# 配置下面参数用于启动监控页面，考虑安全问题，默认是关闭的，按需开启
spring.datasource.druid.stat-view-servlet.enabled=true
spring.datasource.druid.filter.stat.enabled=true
spring.datasource.druid.web-stat-filter.enabled=true

**Comment by lihengming** [comment]
# 配置下面参数用于启动监控页面，考虑安全问题，默认是关闭的，按需开启
spring.datasource.druid.stat-view-servlet.enabled=true
spring.datasource.druid.filter.stat.enabled=true
spring.datasource.druid.web-stat-filter.enabled=true

**Comment by biuabiu** [comment]
好的，有时间再看看，谢谢

**Comment by biuabiu** [comment]
@lihengming   我今天看了下 这三项我都是开启的,因为我在依赖0.1.0版本时就都是开启的,我就只是切换了版本,

**Comment by diedai** [comment]
boot-dubbo 0.2.0和0.1.0，访问监控都是404
