### ISSUE TITLE
启用心跳检测(keepAlive)，数据库重启后池里的连接有效性检测不出来

### ISSUE THREAD

**Issue by lzfvvv** [alibaba/druid#3064]
启用心跳检测(keepAlive)，数据库重启后池里的连接有效性检测不出来,跟了下代码发现检测方式用的是ping的方式，检测类是MySqlValidConnectionChecker （mysql8），产生异常后各上抛的异常是InvocationTargetException ， 但上层处理代码中会对异常做捕获，如果是SQLException就继续往上抛，如果是其它异常直接吞了，吞了之后认为检测是正常的，那些失效的连接就一直好好呆在池里。所以我觉着这可能是一个BUG，望核实，吞异常的代码片断如下：
`boolean result = true; //默认是true
Exception error = null;
try {
	result = validConnectionChecker.isValidConnection(conn, validationQuery, validationQueryTimeout);
} catch (SQLException ex) {
	throw ex; //SQLException 就会向上抛
} catch (Exception ex) {
	error = ex; 
    // 这里吞异常应该是为了如果不确定的异常就不做处理，但是也让检测失效了
}

if (!result) {
	SQLException sqlError = error != null ? //
		new SQLException("validateConnection false", error) //
		: new SQLException("validateConnection false");
	throw sqlError;
}
return;`
############################
另外说下我现在用的处理方案，将默认处理连接检测的类重置成为了ValidConnectionCheckerAdapter ：
<property name="validConnectionCheckerClassName" value="com.alibaba.druid.pool.ValidConnectionCheckerAdapter"/>

连接有问题时它抛的是 CommunicationsException ， 它的父类是 SQLException ， 所以异常不会被吞

**Comment by CHNXX** [comment]
This is a bug,
fix it:https://github.com/alibaba/druid/commit/4322f95717ea09671d8b8f08bdc2fe3fa8e77bb4
