### ISSUE TITLE
oracle转mysql语法的界面不能打开

### ISSUE THREAD

**Issue by KamTing** [alibaba/druid#3069]
URL: | https://rainbow-expert.aliyun.com:2443/sqltransform.htm
-- | --
Server: | tongyijieru-aliyun-com011192101056.cm12
Date: | 2019/02/11 18:02:57

**Comment by wenshao** [comment]
抱歉，这个已经不提供服务了

**Comment by goder037** [comment]
为啥不删除，仅仅关闭issues?
