### ISSUE TITLE
如何获取建表语句中的comment

### ISSUE THREAD

**Issue by Neo110** [alibaba/druid#3071]
CREATE TABLE `oceanus_databases` (
  `name` varchar(64) NOT NULL,
  `age` int(3) NOT NULL COMMENT '年龄',
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8  COMMENT '数据信息表'

怎么获取这个表的信息不是字段的。
COMMENT '数据信息表'

**Comment by WEIQ311** [comment]
使用以下SQL 
SELECT
table_name tableName,
ENGINE,
table_comment tableComment
FROM
information_schema.TABLES 
WHERE
table_schema = ( SELECT DATABASE () ) 
AND table_name = 'oceanus_databases';


| |
魏强
|
|
weiqiang_6@126.com
|
签名由网易邮箱大师定制
在2019年2月13日 10:15，Neo<notifications@github.com> 写道：

CREATE TABLE oceanus_databases (
name varchar(64) NOT NULL,
age int(3) NOT NULL COMMENT '年龄',
PRIMARY KEY (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '数据信息表'

怎么获取这个表的信息不是字段的。
COMMENT '数据信息表'

**Comment by Neo110** [comment]
> FROM

我的没有并没有创建。在执行前获取。

**Comment by Neo110** [comment]
自己正则解决了。
