### ISSUE TITLE
列别名中如果包含-，会被当做减号处理

### ISSUE THREAD

**Issue by ping19900226** [alibaba/druid#3077]
最近在使用druid的过程中，发现as后的别名中如果有 -(减号) 会被解析成 operator。但其实它只是一个普通字符。 比如 Select  a  as a-1...  这种如果是bug的话可以修复一下吗？

Lexer.java 对 - 的处理是从第763行开始，如果当前字符是 -，只判断两种情况，一种是 -- 注释，一种就是operator，能否增加一种  if(token == Token.AS) { // 当做普通字符处理。}

**Comment by ping19900226** [comment]
该问题是在使用SQLParserUtils 解析sql的时候发生的

**Comment by wenshao** [comment]
mysql也不支持，这个是哪个数据库的语法？

**Comment by ping19900226** [comment]
最近排查了一下，是使用的错误，谢谢关注
