### ISSUE TITLE
CAST函数与负号一起解析错误

### ISSUE THREAD

**Issue by yozen17** [alibaba/druid#3080]
SELECT CAST(10 AS decimal(10, 2)) 可以解析
SELECT -CAST(10 AS decimal(10, 2)) 报错：ParserException: TODO : pos 12, line 1, column 9, token CAST
版本 1.1.4

**Comment by yozen17** [comment]
SELECT CAST(10 AS decimal(10, 2))  可以解析
SELECT -CAST(10 AS decimal(10, 2))  报错：ParserException: TODO : pos 12, line 1, column 9, token CAST

**Comment by wenshao** [comment]
问题已修复，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.14
