### ISSUE TITLE
druid-spring-boot-starter 属性顺序问题还存在

### ISSUE THREAD

**Issue by ichavin** [alibaba/druid#3084]
问题如：https://github.com/alibaba/druid/issues/1796

**Comment by wenshao** [comment]
@lihengming

**Comment by luzhaoren** [comment]
druid-spring-boot-starter  version>1.1.13 仍然存在此问题，spring boot 2.1.3.RELEASE

**Comment by luzhaoren** [comment]
> 
> 
> druid-spring-boot-starter version>1.1.13 仍然存在此问题，spring boot 2.1.3.RELEASE

@lihengming

**Comment by lihengming** [comment]
在修复了

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.14 问题已修复，请用新版本

**Comment by wad12302** [comment]
1.1.16  存在
![image](https://user-images.githubusercontent.com/973288/56793581-eaea5e80-683e-11e9-8562-52ac2eed0716.png)

**Comment by tangguochang** [comment]
到底修复没有呢？

**Comment by TinyZzh** [comment]
![image](https://user-images.githubusercontent.com/5763397/67860048-f43ee580-fb57-11e9-8270-dcb6bb0b9ccb.png)
![image](https://user-images.githubusercontent.com/5763397/67860076-fc972080-fb57-11e9-9c9d-49c98902c050.png)

1.1.17依然无法直接new DruidDataSourceWrapper()
