### ISSUE TITLE
PagerUtil.limit 不支持 order占位符

### ISSUE THREAD

**Issue by zhouit** [alibaba/druid#3138]
druid版本 ： 1.1.4

复现语句
```java
PagerUtils.limit("select * from user order by ? ?", "mysql", 1, 20);
```

出现异常
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'rder by ? ?', expect QUES, actual QUES pos 31, line 1, column 30, token QUES

期望输出
select * from user order by ? ? limit 1, 20

**Comment by lizongbo** [comment]
这个sql语法本身就有问题，下面这样是ok的。

``` 
  String newSql = PagerUtils.limit("select * from user order by ? ", DbType.mysql, 1, 20);;
        System.out.println("mysql生成的sql===" + newSql);


```
执行结果：

```
mysql生成的sql===SELECT *
FROM user
ORDER BY ?
LIMIT 1, 20

```
