### ISSUE TITLE
请问，监控页面最底层的友链是链接了博彩网站？

### ISSUE THREAD

**Issue by JUSTZWH** [alibaba/druid#3158]
powered by AlibabaTech & sandzhang & melin & shrek.wang

**Comment by wenshao** [comment]
监控页面作者的个人网站忘记续费了，你更新到最新版本就解决此问题
https://github.com/alibaba/druid/releases/tag/1.1.14

**Comment by JUSTZWH** [comment]
> 监控页面作者的个人网站忘记续费了，你更新到最新版本就解决此问题
> https://github.com/alibaba/druid/releases/tag/1.1.14

好的
