### ISSUE TITLE
Druid初始化之后，GlassFish时区变为世界时区

### ISSUE THREAD

**Issue by YuFulu** [alibaba/druid#3174]
GlassFish启动之后，时区为东八区，但是一旦Druid初始化，GlassFish时区立刻变为世界时区，导致时间错误。

**Comment by YuFulu** [comment]
有人提到Druid默认使用世界时区，是不是因为这个导致的？Druid能否修改时区设置？

**Comment by ston1992** [comment]
请问解决了吗，如何解决的

**Comment by YuFulu** [comment]
我的那个是业务原因，找到问题了
