### ISSUE TITLE
使用connectTimeout不生效？

### ISSUE THREAD

**Issue by itrickzhang** [alibaba/druid#3182]
![image](https://user-images.githubusercontent.com/23379828/56104206-7c1d2380-5f69-11e9-88b1-4fca457ba09e.png)
使用版本1.1.10，数据库连接超时后，设置连接超时时间不生效

**Comment by itrickzhang** [comment]
使用：jdbc:mysql://10.22.0.162:3306/test?connectTimeout=5000

**Comment by lizongbo** [comment]
请使用最新版验证
