### ISSUE TITLE
打印出的可执行SQL未能格式化

### ISSUE THREAD

**Issue by yl-yue** [alibaba/druid#3208]
**环境**
- druid 1.1.16
- jdk 11
- springboot 2.1.3

**问题**
升级版本后，发现打印出来的可执行SQL不在格式化了，不论怎么配置格式化设置都没反应。
![image](https://user-images.githubusercontent.com/39790401/56953641-98c37900-6b6f-11e9-8023-bd45422719c5.png)
控制台打印出来的未格式化SQL
![image](https://user-images.githubusercontent.com/39790401/56953808-ee982100-6b6f-11e9-871a-3d277745d712.png)

**Comment by xusheng1987** [comment]
以前用的什么版本

**Comment by yl-yue** [comment]
时间已久，问题模糊了。升级版本应该就OK了。所以暂时关闭此问题。
