### ISSUE TITLE
PG创建临时表不能解析？

### ISSUE THREAD

**Issue by todd5167** [alibaba/druid#3212]
CREATE  TEMPORARY TABLE  films_recent AS SELECT * FROM films 。

解析失败 PG

**Comment by todd5167** [comment]
create schema schema01;
com.alibaba.druid.sql.parser.ParserException: TODO SCHEMA

**Comment by rlncepu** [comment]
这个问题有更新或者解决方法吗？

**Comment by jxsllzy** [comment]
这个问题目前还没有解决
