### ISSUE TITLE
mysql sql解析两个以上or的 时候丢失括号

### ISSUE THREAD

**Issue by blackchoc** [alibaba/druid#3213]
问题和#2167 一样，但是我的版本是1.1.13，更新至最新的版本1.1.16仍然有这个问题
https://github.com/alibaba/druid/issues/2167
使用1.1.3 和1.1.2版本未出现该问题。但测试1.1.4，1.1.6，1.17 均无法通过

   @Test
    public void testBracket() {
        String sql = null;
//        sql = "select * from table1 where a=1 and (b=1 or c=2)";//可以通过
        sql = "select * from table1 where a=1 and (b=1 or c=2 or d=3)";//pretty format 后丢失括号
        String prettySql = null;
        prettySql = com.alibaba.druid.sql.SQLUtils.formatMySql(sql);
//        prettySql = com.alibaba.druid.sql.SQLUtils.formatSQLServer(sql);//使用sqlserver 也没有问题
        System.out.println(prettySql);
    }

**Comment by blackchoc** [comment]
发现是开启SQLBinaryOpExprGroup 支持后，格式化输出的问题。不知道这个SQLBinaryOpExprGroup 是做什么用的。目前重新写了个format方法，关闭SQLBinaryOpExprGroup 就好了。但是不知道sql解析会不会一样有问题。

**Comment by TheP0wer** [comment]
> 

https://github.com/alibaba/druid/issues/1542
