### ISSUE TITLE
能否提供一个阀值来限制查询一次最多返回多少行数据

### ISSUE THREAD

**Issue by smile2014** [alibaba/druid#3214]
这样可以避免开发人员写一个不分页查询也不带条件一次返回十万行数据导致应用服务器挂机

**Comment by tnngo** [comment]
我想，也许您需要的是一个触发器。这不是druid应该有的功能，请仔细理解JDBC驱动。

**Comment by smile2014** [comment]
查询触发器怎么控制???,我觉得很有必要再连接池这一层加这种阀值，来控制单次查询返回行数

**Comment by smile2014** [comment]
@wenshao

**Comment by smile2014** [comment]
@wenshao
