### ISSUE TITLE
创建物理连接时，所有连接都只连接到domain中其中一个ip

### ISSUE THREAD

**Issue by ShoweNi** [alibaba/druid#3260]
在创建物理连接时，创建socket连接，使用InetAddress[] possibleAddresses = InetAddress.getAllByName(this.host)获取ip列表，然后一次连接这些ip，这样的话容易导致连接池的所有连接都是一致连接到同一个ip上面

**Comment by lizongbo** [comment]
这个是 jdbc驱动控制的，不是druid控制的
