### ISSUE TITLE
druid脚部power链接问题

### ISSUE THREAD

**Issue by Sadboy007** [alibaba/druid#3266]
在使用druid的时候，下面存在power链接，文字为：powered by AlibabaTech & sandzhang & melin & shrek.wang ，其中第二个 sandzhang跳转地址为http://www.sandzhang.com/ ，打开是赌博网站，不知道以前的版本是否能删除，或者后续的版本是否还会存在此问题。

**Comment by gelibo** [comment]
The new version has solved the problem

**Comment by Sadboy007** [comment]
Thanks for your reply.
