### ISSUE TITLE
支持自定义filter吗

### ISSUE THREAD

**Issue by dankes** [alibaba/druid#3278]
如果默认的filter不够用，如何加入自定义的filter？

**Comment by dankes** [comment]
如果要实现接入xxx-Filter，在yml文件应该如何配置？
<bean id="xxx-filter" class="xxx.xxx.xxx.xxxFilter">
</bean>

<bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource" init-method="init" destroy-method="close">
    ...
    <property name="proxyFilters">
        <list>
            <ref bean="xxx-filter"/>
        </list>
    </property>
</bean>

**Comment by dankes** [comment]
```
<bean id="xxx-filter" class="xxx.xxx.xxx.xxxFilter">
    <property name="resultSetLogEnabled" value="false" />
</bean>

<bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource" init-method="init" destroy-method="close">
    ...
    <property name="proxyFilters">
        <list>
            <ref bean="xxx-filter"/>
        </list>
    </property>
</bean>
```

**Comment by liubingsmile** [comment]
只是需要在应用META-INF 增加druid-filter.properties 配置文件，比如配置为 
druid.filters.sqlmonitor=com.yonghui.datasource.filter.MonitorSQLPerformanceStatFilter
然后在配置中增加过滤配置
<bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource" init-method="init" destroy-method="close">
    ...
    <property name="proxyFilters">
        <list>
            <ref bean="sqlmonitor"/>
        </list>
    </property>
</bean>
