### ISSUE TITLE
JdbcDataSourceStat 持有太多的对象,并且不进行释放,最终导致OOM

### ISSUE THREAD

**Issue by raydl007** [alibaba/druid#3288]
![image](https://user-images.githubusercontent.com/10443318/59563038-44b11d00-9067-11e9-9ead-0884d290ee31.png)
如上图所示,并且已经关闭了状态监控,依然内存疯涨

**Comment by raydl007** [comment]
![image](https://user-images.githubusercontent.com/10443318/59563582-842f3780-906e-11e9-850a-651983468e4a.png)
是否配置正确

**Comment by YourXin** [comment]
> ![image](https://user-images.githubusercontent.com/10443318/59563038-44b11d00-9067-11e9-9ead-0884d290ee31.png)
> 如上图所示,并且已经关闭了状态监控,依然内存疯涨

请问最后如何解决这个问题的呢?

**Comment by raydl007** [comment]
#关闭druid的监控,该监控会耗尽内存
spring.datasource.druid.stat-view-servlet.enabled=false
spring.datasource.druid.web-stat-filter.enabled=false
spring.datasource.druid.filter.stat.enabled=false

这样改就可以了

**Comment by YourXin** [comment]
好的，多谢

**Comment by raydl007** [comment]
> 好的，多谢

客气了,这是某个版本的代码错误,文档里面虽然写的是默认关闭,但是实际上开启的,更新到新版的也可以解决这个问题

**Comment by YourXin** [comment]
> > 好的，多谢
> 
> 客气了,这是某个版本的代码错误,文档里面虽然写的是默认关闭,但是实际上开启的,更新到新版的也可以解决这个问题

确实，我们现在使用的1.1.10的版本。默认打开了。
