### ISSUE TITLE
使用druid SQL parser解析SQL，有什么SQL合法性的验证方案么？

### ISSUE THREAD

**Issue by UCSBGauchos** [alibaba/druid#3293]
最近使用SQL parser解析SQL，那些不合法的SQL比如"select *"好像解析起来也不会报错。想确认下，sql parser组件在验证合法性SQL方面有什么办法么？

**Comment by lizongbo** [comment]
这个只能自己判断，druid目前的能力主要是做到能解析成语法树，没法想db那样对语法的合法性做到完全准确的判断，不可能穷举各种异常场景。
