### ISSUE TITLE
如何看待druid支持古老的proxool和商业广告植入

### ISSUE THREAD

**Issue by hkzkx** [alibaba/druid#3295]
阿里，你开源，还要植入商业广告，脸红不？
引用了proxool，那么古老，maven依赖都拉不到，你们怎么干活的？

**Comment by hkzkx** [comment]
包呢，包呢，我日，温少，你能不能把老代码删除？

**Comment by hkzkx** [comment]
tbdatasource-2.0,2，包呢？

**Comment by hkzkx** [comment]
好好做你的连接池和监控不行吗，搞这么多乱七八ZAO的东西

**Comment by hkzkx** [comment]
花了好大力气说服众人，结果被光光的打脸，疼啊，相比Hikari，你们还是嫩。。。。。

**Comment by wenshao** [comment]
dependency的scope是test，这个没问题啊，你用错了？

**Comment by hkzkx** [comment]
@wenshao，重新编译打包有问题的，找不到依赖包，特别是tbdatasource，另外，建议把proxool依赖移除，这么陈旧的连接池，原作者早就不维护了，druid为啥还要支持？

**Comment by wenshao** [comment]
在项目的lib目录下有啊

**Comment by WangChangJuan** [comment]
说话好难听啊，开源也需要资金支持。
光是很强，但是说不定那天就被人超越了。
