### ISSUE TITLE
简介数据库报错的时候，如何能捕获exception

### ISSUE THREAD

**Issue by ut777** [alibaba/druid#3298]
当连接池无法连接到数据库(用户名密码错误)的时候，连接池会反复的尝试连接。这个时候连接池并不会抛出exception。这样导致调用的程序hang死。有没有什么办法，能让调用的函数（应用程序）知道，连接出了问题？

**Comment by wenshao** [comment]
可以通过配置maxWait参数解决

**Comment by ut777** [comment]
> 可以通过配置maxWait参数解决

感谢回答。
