### ISSUE TITLE
druid和mybatis-plus整合会出现SQLFeatureNotSupportedException?

### ISSUE THREAD

**Issue by cielswift** [alibaba/druid#3300]
mybatis-plu代码生成器,会把数据库的 date类型生成为 Java 的LocalDate类型,而进行查询会报SQLFeatureNotSupportedException 错误; 但是把mybatis-plu转换策略换成DateType.ONLY_DATE,生成 java的 Date类型就没问题;

mybatis-plu代码的维护者认为是druid的问题.

![2](https://user-images.githubusercontent.com/42295829/59828901-9f4fbf00-936e-11e9-92b8-39269b665ad9.PNG)
![3](https://user-images.githubusercontent.com/42295829/59828903-a1198280-936e-11e9-802b-0b0b154cbb4f.PNG)

**Comment by kakaluote444** [comment]
那是旧版本（比如1.1.16）中`getObject(String columnLabel, Class<T> type) `是直接抛出异常的，在最新版本里面有实现逻辑，可以更换版本解决。 
```xml
<dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid</artifactId>
                <version>1.1.19</version>
</dependency>
```

**Comment by lizongbo** [comment]
已经支持，请使用最新版验证
