### ISSUE TITLE
defaultAutoCommit的问题

### ISSUE THREAD

**Issue by lmzhizhe** [alibaba/druid#3306]
我 把 defaultAutoCommit 设置为false，正常的sql执行，事务提交后，数据库没数据的，我跟了整个事务的日志 和 代码，事务缺失是正常提交了，而且调用了 druid的datasource进行commit，但数据库就是没数据。

我把 defaultAutoCommit 设置为true，事务执行得方法里面 我直接throw runtimeExceptiion 竟然也没回滚，所以我就很好奇 这个 连接池到底是怎么回事。

我把datasource换成c3p0，提交和回滚都正常了，能否解答下，是你们的bug，还是你们没维护了？

**Comment by lizongbo** [comment]
请使用 1.2.20版本验证。
