### ISSUE TITLE
druid连接池确定泄漏?

### ISSUE THREAD

**Issue by maguanggit** [alibaba/druid#3324]
我们项目是springboot2.0.4, druid是1.0.10, 
![image](https://user-images.githubusercontent.com/25919386/60584092-dc7c6e00-9dbe-11e9-8fe6-c863c61cc2e8.png)
逻辑打开和逻辑关闭连接数相差很大, 但是每一个weburi的详情中JdbcPoolConnectionCloseCount和JdbcPoolConnectionOpenCount数量一致,请问这是怎么回事啊?
打开druid遗弃功能后, activeConnectionStackTrace中会有信息, 但是我看了方法了, 都是jpa原生查询, 没有手动创建连接的情况. 我remove-abandoned-timeout设置的300, activeConnectionStackTrace应该在5分钟之后才会出现信息, 可是我项目启动后, 大量访问某个接口, 2分钟后就会出现信息, 这怎么解释呢?

**Comment by maguanggit** [comment]
出现很长时间了, 我们项目偶尔会挂掉, 重启就会解决

**Comment by lizongbo** [comment]
请使用最新版验证
