### ISSUE TITLE
druid-spring-boot-starter支持springboot2.0吗

### ISSUE THREAD

**Issue by LaneMa** [alibaba/druid#3338]
springboot版本2.1.4.RELEASE
druid-spring-boot-starter版本试过1.1.7、1.1.4、1.1.2，但是启动的时候都是报错Caused by: java.lang.ClassNotFoundException: org.springframework.boot.autoconfigure.jdbc.metadata.DataSourcePoolMetadataProvider，但是 org.springframework.boot.autoconfigure.jdbc.metadata这个目录下已经没有这个类了啊。不用
druid-spring-boot-starter 直接用druid是没有问题的。是不是暂时还不支持springboot2.0啊？

**Comment by sparkcai** [comment]
支持的， 应该是你配置有问题。

**Comment by lizongbo** [comment]
已经支持，请使用最新版验证
