### ISSUE TITLE
SLF4JImpl类debug方法，日志级别使用错误

### ISSUE THREAD

**Issue by kch820** [alibaba/druid#3360]
com.alibaba.druid.support.logging.SLF4JImpl
public void debug(String msg, Throwable e) {
        debugCount++;
        log.log(null, callerFQCN, LocationAwareLogger.ERROR_INT, msg, null, e);
    }
日志级别是否应该为LocationAwareLogger.DEBUG_INT

**Comment by lizongbo** [comment]
请使用最新版验证
