### ISSUE TITLE
坐等温少修复druid最新版不支持mybatis 3.5.1+LocalDateTime等jdk8的时间问题

### ISSUE THREAD

**Issue by liaomengge** [alibaba/druid#3387]

**Comment by zhanjunfeng** [comment]
帮顶一下，这个问题拖了好久了

**Comment by WangChangJuan** [comment]
阿里的专家，一般都非常忙，相应不会那么及时，你本人要是有时间的话，可以阅读一下代码，自己动手看能否解决。

**Comment by NeverMind2014** [comment]
把

**Comment by NeverMind2014** [comment]
把com.alibaba.druid.proxy.jdbc.ResultSetProxyImpl的方法
public <T> T getObject(String columnLabel, Class<T> type) throws SQLException {
        throw new SQLFeatureNotSupportedException();
}
改为    
public <T> T getObject(String columnLabel, Class<T> type) throws SQLException {
        FilterChainImpl chain = createChain();
        Object value = chain.resultSet_getObject(this, columnLabel, type);
        recycleFilterChain(chain);
        return (T) value;
    }
就可以了，但是没做过严格测试，也不知道为啥这个方法官方jar包没有实现

**Comment by liaomengge** [comment]
> 把com.alibaba.druid.proxy.jdbc.ResultSetProxyImpl的方法
> public T getObject(String columnLabel, Class type) throws SQLException {
> throw new SQLFeatureNotSupportedException();
> }
> 改为
> public T getObject(String columnLabel, Class type) throws SQLException {
> FilterChainImpl chain = createChain();
> Object value = chain.resultSet_getObject(this, columnLabel, type);
> recycleFilterChain(chain);
> return (T) value;
> }
> 就可以了，但是没做过严格测试，也不知道为啥这个方法官方jar包没有实现

这个问题，温少已经修了（基于1.1.20），只是一直没有发布新版本，估计1.1.21就可以了，见：https://github.com/alibaba/druid/commit/4486ef9f205dd3b17295b5d8475e911ab022b14e~

**Comment by lizhuangs** [comment]
这个问题并没有修复，虽然运行不报错，但是druid的日志里面显示为null

**Comment by lizongbo** [comment]
请使用最新版验证
