### ISSUE TITLE
该项目还在维护吗？

### ISSUE THREAD

**Issue by liangyuanpeng** [alibaba/druid#3401]

**Comment by liaomengge** [comment]
修复问题太慢了

**Comment by zgqq** [comment]
看起来是放弃了，java 9现在都没支持

**Comment by WangChangJuan** [comment]
辛苦温少与团队无偿为社区服务这么多年了。
为了促进项目的继续维护,大家是否需要进行项目捐助？
一个项目发展离不开大家的支持，相信温少不会抛弃我们大家的。

个人最近发现另外一款国产连接池（小蜜蜂），性能也还可以
有兴趣的朋友可以看看，地址：Http://www.github.com/Chris2018998/BeeCP

**Comment by LuVx21** [comment]
估计一部分转hikaricp了

**Comment by WangChangJuan** [comment]
hikaricp也有段时间不没有回帖了。。。。

**Comment by WangChangJuan** [comment]
上次无意看到一个中国人的Github项目，看到上面上面的测试成绩，光居然不是最快的，Vibur才是最快的，感觉不可思议。 有兴趣的朋友可以去帮它验明一下真伪。。地址：https://github.com/Chris2018998/BeeCP
