### ISSUE TITLE
1.1.19版本处理不了postgresql的delete returning语句

### ISSUE THREAD

**Issue by bingo-chou** [alibaba/druid#3410]
类似于这样的`delete from t1 using t2 where t1.t2_id = t2.id and t2.id = 90 returning t1.name`

**Comment by 13567436138** [comment]
我调试了源代码是支持的，不过只支持returning *  的情况

**Comment by 13567436138** [comment]
`@Test
    public void demo2(){
        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try{
            Properties properties = new Properties();
            properties.load(this.getClass().getResourceAsStream("/druid.properties"));
            DataSource dataSource = DruidDataSourceFactory.createDataSource(properties);
            // 获得连接:
            conn = dataSource.getConnection();
            // 编写SQL：
            String sql = "delete from student where id=3 returning *";
            pstmt = conn.prepareStatement(sql);
            // 执行sql:
           rs= pstmt.executeQuery();
            while(rs.next()){
                System.out.println(rs.getString("name"));
            }
        }catch(Exception e){
            e.printStackTrace();
        }finally{
            if(rs!=null){
                try {
                    rs.close();

                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            if(pstmt!=null){
                try {
                    pstmt.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            if(conn!=null){
                try {
                    conn.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }

        }
    }`

**Comment by bingo-chou** [comment]
确实是只支持returning *, 不支持特定字段
