### ISSUE TITLE
【bug】grant create session语法不支持

### ISSUE THREAD

**Issue by ssxlulu** [alibaba/druid#3421]
如下图所示，grant create session语法不支持。

![image](https://user-images.githubusercontent.com/14773179/63675788-2d876c00-c81c-11e9-9d70-153386d0e32f.png)

![image](https://user-images.githubusercontent.com/14773179/63675240-f49ac780-c81a-11e9-9c5a-4e2b5c2b6901.png)

**Comment by 13567436138** [comment]
我试了下，没问题啊，可以执行，最新的代码

**Comment by 13567436138** [comment]
你用的是oracle数据库么

**Comment by ssxlulu** [comment]
> 你用的是oracle数据库么

搞错了，mysql没有此语法。

**Comment by ssxlulu** [comment]
此单关闭。
