### ISSUE TITLE
SQLFeatureNotSupportedException

### ISSUE THREAD

**Issue by Alenfitz** [alibaba/druid#3425]
version:1.1.9
com/alibaba/druid/pool/DruidPooledConnection类中的get/setSchema() 方法还未实现，请问有计划在近期版本实现吗？谢谢!

**Comment by wenshao** [comment]
getSchema()会支持，但setSchema需要考虑一下

**Comment by Alenfitz** [comment]
好的，期待新的版本，谢谢你的回复！
