### ISSUE TITLE
缺少java.sql.Time类型适配。

### ISSUE THREAD

**Issue by gMan1990** [alibaba/druid#3428]
https://github.com/alibaba/druid/blob/6df3c39b420867f45c8f4b531488e3bfadb372fb/src/main/java/com/alibaba/druid/sql/visitor/SQLASTOutputVisitor.java#L371
```text
java.sql.Timestamp 而且MySQL支持到微妙
java.sql.Date
java.sql.Time
```

测试代码
```java
Timestamp ts = new Timestamp(System.currentTimeMillis());
ts.setNanos(999888777);
String format = SQLUtils.format("INSERT INTO `test`(`_timestamp`, `_date`, `_time`) VALUES (?,?,?);",
    JdbcConstants.MYSQL,
    Arrays.asList(ts, new java.sql.Date(ts.getTime()), new java.sql.Time(ts.getTime())));
System.out.println(format);
```
预期结果（如果输出至微妙的话
```text
INSERT INTO `test` (`_timestamp`, `_date`, `_time`)
VALUES ('2019-08-29 13:54:29.999888', '2019-08-29', '13:54:29');
```

**Comment by 13567436138** [comment]
能把你的sql语句贴一下么，断点进不去

**Comment by gMan1990** [comment]
@13567436138 贴了测试代码。

**Comment by 13567436138** [comment]
https://github.com/alibaba/druid/pull/3419/commits
代码已提交

**Comment by 13567436138** [comment]
'2019-08-29 13:54:29.999888'这个为啥是6位，不是3位么

**Comment by gMan1990** [comment]
https://dev.mysql.com/doc/refman/5.7/en/fractional-seconds.html
`MySQL 5.7 has fractional seconds support for TIME, DATETIME, and TIMESTAMP values, with up to microseconds (6 digits) precision`

所以按理java.sql.Time，java.sql.Timestamp可以格式化到微妙。不过就先这样吧。。
因为这里的sql仅仅是用来看看的，不能拿去数据库执行，如果要执行的话还得考虑`mysql时区`与`程序时区`的问题
