### ISSUE TITLE
sql监控里面的时间单位是什么啊？

### ISSUE THREAD

**Issue by fridayhoho** [alibaba/druid#3431]
druid/sql.html

sql监控里面的单位是什么啊？

MaxTimespan 如何看出来是什么时间单位啊

**Comment by 13567436138** [comment]
应该是ms

**Comment by fridayhoho** [comment]
我感觉是s，一个sql 不可能只有几ms吧？

也没给个确定的单位，全靠猜

**Comment by zhhaojie** [comment]
> 我感觉是s，一个sql 不可能只有几ms吧？
> 
> 也没给个确定的单位，全靠猜

当然是ms. 一个SQL跑3~4ms正常得很
