### ISSUE TITLE
1.1.19  版本发布太随意了吧？ 什么说明都不写，偷偷改很不好

### ISSUE THREAD

**Issue by chenkline** [alibaba/druid#3434]
首先感谢阿里开源druid组件，但是小小的吐槽一下
1.1.19  版本发布太随意了吧？ 什么说明都不写？既然1.1.18升级有问题就勇敢的说出来，其实没什么，大家能接受，但是偷偷地改不作任何说明，我们使用者升级前也是需要宣导的，有时候就因此经常自己打脸。

**Comment by yangyining** [comment]
看了下提交历史，1.1.19貌似只是增加了对jdbc4.1的支持。 
提交id：39ac64c32ede4d1a7e015922fa8552f784726044
