### ISSUE TITLE
> 我也遇到了同样问题，搞了好几天，心累。。。

### ISSUE THREAD

**Issue by ioandy** [alibaba/druid#3438]
> 我也遇到了同样问题，搞了好几天，心累。。。
> 请教下楼上说更新mysql-connector-java，哪个版本会正常啊？ 还有设置setMinPoolSize(0), 没有起作用..

你搞出来了么？spring-boot-starter-jta-atomikos升级了么？我也是各种方法都试了…心好累

_Originally posted by @shuiZzz in https://github.com/alibaba/druid/issues/2299#issuecomment-526463669_

好了，查了好多资料，后来又跟了源码，应该是配置问题，后来一通瞎改竟然不报错了，现在暂时还正常。

**Comment by shuiZzz** [comment]
> > 我也遇到了同样问题，搞了好几天，心累。。。
> > 请教下楼上说更新mysql-connector-java，哪个版本会正常啊？ 还有设置setMinPoolSize(0), 没有起作用..
> 
> 你搞出来了么？spring-boot-starter-jta-atomikos升级了么？我也是各种方法都试了…心好累
> 
> _Originally posted by @shuiZzz in [#2299 (comment)](https://github.com/alibaba/druid/issues/2299#issuecomment-526463669)_
> 
> 好了，查了好多资料，后来又跟了源码，应该是配置问题，后来一通瞎改竟然不报错了，现在暂时还正常。

你的配置改了些啥啊？能发出来参考一下么？

**Comment by ioandy** [comment]
@shuiZzz  加Q截图给你 757455159
