### ISSUE TITLE
java.sql.SQLFeatureNotSupportedException

### ISSUE THREAD

**Issue by V1ncentzzZ** [alibaba/druid#3452]
最新版druid1.1.20，com.alibaba.druid.proxy.jdbc.ResultSetProxyImpl#getObject(java.lang.String, java.lang.Class<T>)，这个方法什么时候能实现啊~~~

**Comment by 13567436138** [comment]
```
public <T> T getObject(String columnLabel, Class<T> type) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }
```
是这个么

**Comment by 13567436138** [comment]
使用场景能贴一下么

**Comment by V1ncentzzZ** [comment]
emmmm，没问题了，我考虑了下，返回指定Class或者Object没多大区别，com.alibaba.druid.proxy.jdbc.ResultSetProxyImpl#getObject(java.lang.String)这个接口就能满足使用，后续如果有必须使用到上述接口的时候我再来回复，谢谢你的回答~

**Comment by junshao1986** [comment]
这个问题在使用JDK8的日期类型的时候就会出现该问题

**Comment by lizongbo** [comment]
请使用最新版验证
