### ISSUE TITLE
Druid1.1.10必现discard connection

### ISSUE THREAD

**Issue by taotao0325** [alibaba/druid#3486]
Spring boot项目，druid为1.1.10版本。单台服务器必现discard connection

配置项：
spring.datasource.druid.time-between-eviction-runs-millis=60000
#配置一个连接在池中最小生存的时间，单位是毫秒
spring.datasource.druid.min-evictable-idle-time-millis=300000
spring.datasource.druid.validation-query=SELECT 1 FROM DUAL
#申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。建议配置为true，不影响性能，并且保证安全性
spring.datasource.druid.test-while-idle=true
#申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
spring.datasource.druid.test-on-borrow=false
#归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
spring.datasource.druid.test-on-return=false

系统异常：
2019-09-24 07:26:40.729 [http-nio-8080-exec-5] ERROR com.alibaba.druid.pool.DruidDataSource - discard connection
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 8 milliseconds ago.  The last packet sent successfully to the server was 8 milliseconds ago.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:974)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:391)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3409)

求问题解决思路或者方案。谢谢！！！

**Comment by taotao0325** [comment]
@wenshao

**Comment by beiwangnull** [comment]
1.1.18也出现了，然后看打出来的日志：

testWhileIdle true, idle millis 181896, minIdle 2, poolingCount 3, timeBetweenEvictionRunsMillis 60000, lastValidIdleMillis 181896, driver com.mysql.cj.jdbc.Driver, exceptionSorter com.alibaba.druid.pool.vendor.MySqlExceptionSorter

看日志就是testWhileIdle没有生效

**Comment by taotao0325** [comment]
@beiwangnull 你这个日志是怎么出来的，需要配置什么吗。我这里没有看到这个日志

testWhileIdle true, idle millis 181896, minIdle 2, poolingCount 3, timeBetweenEvictionRunsMillis 60000, lastValidIdleMillis 181896, driver com.mysql.cj.jdbc.Driver, exceptionSorter

**Comment by beiwangnull** [comment]
@taotao0325 这个是报错了，自动打出来的error.log

**Comment by taotao0325** [comment]
好的，谢谢。之前没看error log，看的是info log

**Comment by taotao0325** [comment]
@zhangdewen9999 没解决，换了一台服务器

**Comment by dingxy3** [comment]
> @zhangdewen9999 没解决，换了一台服务器

换服务器后解决了？

**Comment by yangzt23** [comment]
1.0.27 也有此问题, 升级到1.1.20就好了

**Comment by westCastle** [comment]
1.1.22也有这个问题，还没有解决

**Comment by sail-y** [comment]
我也有啊，这个问题到底是怎么出现的，又是怎么解决的，是数据库的问题吗

**Comment by dingxy3** [comment]
jdbc连接串后加 connectTimeout和sockttimeout解决。

**Comment by git10135405** [comment]
楼主解决了吗

**Comment by westCastle** [comment]
已解决
测试环境中在数据库链接url后面添加的：
&amp;allowMultiQueries=true&amp;rewriteBatchedStatements=true&amp;failOverReadOnly=false&amp;serverTimezone=UTC


生产环境使用的DRDS未发生该问题


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/druid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月12日(星期五) 下午4:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/druid] Druid1.1.10必现discard connection (#3486)





 
楼主解决了吗
