### ISSUE TITLE
用的小众数据库。。xa not support dbType 。有什么办法可以配置驱动么

### ISSUE THREAD

**Issue by tanghf0403** [alibaba/druid#3489]
使用DruidXADataSource，项目使用的是JdbcUtils里面没有配置的数据库。怎么办。一直提示"xa not support dbType : "

**Comment by derekzone** [comment]
可以指定driver的

**Comment by tanghf0403** [comment]
谢谢。是dbType 不能为空。但是又没有我使用的数据库的类型

**Comment by yfdxzy2010** [comment]
去掉wall

**Comment by wyfsxs** [comment]
大佬，怎么去掉wall，filter中吗，这个dbtype可恶心了
