### ISSUE TITLE
Communications link failure

### ISSUE THREAD

**Issue by WellaceZ** [alibaba/druid#3491]
mysql驱动：5.1.42
druid：1.1.9
druid配置项：
datasource.pool.default.initialSize=0
datasource.pool.default.minIdle=0
datasource.pool.default.maxActive=200
datasource.pool.default.maxWait=60000
datasource.pool.default.timeBetweenConnectErrorMillis=1000
datasource.pool.default.notFullTimeoutRetryCount=-1
datasource.pool.default.connectionErrorRetryAttempts=3
datasource.pool.default.failFast=true
datasource.pool.default.timeBetweenEvictionRunsMillis=60000
datasource.pool.default.minEvictableIdleTimeMillis=300000
datasource.pool.default.testOnBorrow=false
datasource.pool.default.testOnReturn=false
datasource.pool.default.testWhileIdle=true
datasource.pool.default.validationQuery=
datasource.pool.default.validationQueryTimeout=60
datasource.pool.default.logAbandoned=false
datasource.pool.default.removeAbandoned=false
datasource.pool.default.removeAbandonedTimeout=600

数据库的设置为：
connect_timeout=10;
interactive_time=1800;
wait_timeout=1800;

后台日志会时不时的报com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure。The last packet successfully received from the server was 43,694 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.

这个错误是数据库端主动断开连接，但是数据库的时间为1800秒，testWhileIdle=true，如果超过60秒在获取connection的时候就会校验connection的有效性，没想明白哪里出的问题导致“脏连接”

**Comment by tangzengke** [comment]
使用druid连接池时数据库连接长时间未使用被数据库服务器主动关闭后使用连接报错（Error querying database.  Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 9,103 milliseconds ago.  The last packet sent successfully to the server was 9,110 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.），解决方案如下：
1、druid组件升级至1.1.16及以上版本
<dependency>
	<groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
            <version>1.1.16</version>
</dependency>
2、数据库连接URL加入keepAlive=true参数，注意要删除连接URL中的autoReconnect=true参数
3、连接属性中的timeBetweenEvictionRunsMillis+minEvictableIdleTimeMillis要小于数据库服务器的wait_timeout值（可通过show global variables like 'wait_timeout'查看）

**Comment by liusn0329** [comment]
@tangzengke  题主满足wait_timeout>timeBetweenEvictionRunsMillis+minEvictableIdleTimeMillis,这个问题是1.1.9版本的已知bug么，我也遇到了，偶现问题，真是头疼

**Comment by lizongbo** [comment]
请使用最新版验证
