### ISSUE TITLE
SQLUtils.toSQLString能否获得原始的输入

### ISSUE THREAD

**Issue by ZevveZ** [alibaba/druid#3497]
- 先说一个bug
```
String sql = "SELECT any(time), sum(field) FROM table group by type";
List<SQLStatement> stmtList = SQLUtils.parseStatements(sql, JdbcConstants.CLICKHOUSE);
System.out.println(SQLUtils.toSQLString(stmtList.get(0), JdbcConstants.CLICKHOUSE, new SQLUtils.FormatOption(false, false)));
```
期望输出: `select any(time), sum(field) from table group by type`
实际输出: `select ANY(time), sum(field) from table group by type`

- 有没有办法获得原始输入的字符串(关注大小写)，比如`SELECT any(time), SUM(field) FROM table group by type` 输出的结果保留原来的大小写

**Comment by chuyuanlinzi** [comment]
> * 先说一个bug
> 
> ```
> String sql = "SELECT any(time), sum(field) FROM table group by type";
> List<SQLStatement> stmtList = SQLUtils.parseStatements(sql, JdbcConstants.CLICKHOUSE);
> System.out.println(SQLUtils.toSQLString(stmtList.get(0), JdbcConstants.CLICKHOUSE, new SQLUtils.FormatOption(false, false)));
> ```
> 
> 期望输出: `select any(time), sum(field) from table group by type`
> 实际输出: `select ANY(time), sum(field) from table group by type`
> 
> * 有没有办法获得原始输入的字符串(关注大小写)，比如`SELECT any(time), SUM(field) FROM table group by type` 输出的结果保留原来的大小写

我也遇到类似问题，在Clickhouse中，会自动转换查询项中匹配到的Token，导致自动转换了大小写，期望不做处理，这个该如何实现呢，翻源码也没找到合适的方法，请大神。

**Comment by ZevveZ** [comment]
自己搞得，看起来druid没有这样的设置

**Comment by chuyuanlinzi** [comment]
> 自己搞得，看起来druid没有这样的设置

有好办法吗，愿闻其详

**Comment by QinAndroid** [comment]
> 自己搞得，看起来druid没有这样的设置

请问这个问题是怎么解决的？
