### ISSUE TITLE
mybatisplus整合druid一起使用LocalDateTime等新日期会报错

### ISSUE THREAD

**Issue by 1725636955** [alibaba/druid#3501]
现象： 集成druid数据源，使用3.1.0之前版本没问题，升级mp到3.1.1+后，运行时报错:java.sql.SQLFeatureNotSupportedException

原因： mp3.1.1+使用了新版jdbc，LocalDateTime等新日期类型处理方式升级，但druid不支持，参考:https://github.com/baomidou/mybatis-plus/issues/1245

**Comment by ylh23y** [comment]
https://github.com/alibaba/druid/issues/3276

**Comment by 1725636955** [comment]
现象： 集成druid数据源，使用3.1.0之前版本没问题，升级mp到3.1.1+后，运行时报错:java.sql.SQLFeatureNotSupportedException

原因： mp3.1.1+使用了新版jdbc，LocalDateTime等新日期类型处理方式升级，但druid不支持，参考:baomidou/mybatis-plus#1245

**Comment by 1725636955** [comment]
现象：集成druid数据源，使用3.1.0之前版本没问题，升级mp到3.1.1+后，运行时报错：java.sql.SQLFeatureNotSupportedException

原因：mp3.1.1 +使用了新版jdbc，LocalDateTime等新日期类型处理方式升级，但druid不支持，参考：baomidou / mybatis-plus＃1245

**Comment by wuwj-cn** [comment]
实际问题代码是已经fixed，但是看了一下是commit没有合并到1.1.20中，具体看#3517 ，看看官方什么时候再给个版本修复

**Comment by wuwj-cn** [comment]
在代码生成器的全局配置中配置DateType可解决这个问题
gc.setDateType(DateType.SQL_PACK);

**Comment by 1725636955** [comment]
> 在代码生成器的分布式配置中配置DateType可解决这个问题
> gc.setDateType（DateType.SQL_PACK）;
666

**Comment by 1725636955** [comment]
> 在代码生成器的分布式配置中配置DateType可解决这个问题
> gc.setDateType（DateType.SQL_PACK）;

那这样就是使用date类了吧

**Comment by wuwj-cn** [comment]
> > 在代码生成器的分布式配置中配置DateType可解决这个问题
> > gc.setDateType（DateType.SQL_PACK）;
> 
> 那这样就是使用date类了吧

默认Timestamp
![image](https://user-images.githubusercontent.com/1322188/67081479-d1144d80-f1c9-11e9-9ac9-48da0c2e29ce.png)

**Comment by 1725636955** [comment]
好

**Comment by 1725636955** [comment]
> > > 在代码生成器的分布式配置中配置DateType可解决这个问题
> > > gc.setDateType（DateType.SQL_PACK）;
> > 
> > 
> > 那这样就是使用date类了吧
> 
> 默认Timestamp
> ![image](https://user-images.githubusercontent.com/1322188/67081479-d1144d80-f1c9-11e9-9ac9-48da0c2e29ce.png)

好

**Comment by yuhua1987113** [comment]
+1

**Comment by liuximeng** [comment]
+1

**Comment by chaochunshu** [comment]
> 升级22 后正常了

目前最新的还是20，什么时候发22呢

**Comment by cuihj** [comment]
> > 升级22 后正常了
> 
> 目前最新的还是20，什么时候发22呢

wait.....

**Comment by lizhuangs** [comment]
+1。运行不报错，druid日志显示为null，用原生的没有这个问题。坐等修复。

**Comment by YiuTerran** [comment]
目前还是：Parameters : [NULL, null, null]，打印日志有问题
