### ISSUE TITLE
不能解析全文检索语法WITH QUERY EXPANSION

### ISSUE THREAD

**Issue by ConnorLH** [alibaba/druid#3520]
``` sql
SELECT SysNo,MATCH(Name)AGAINST('张三' WITH QUERY EXPANSION) AS score
FROM `test_table`
WHERE MATCH(Name)AGAINST('张三' WITH QUERY EXPANSION)
```
解析sql报错
`com.alibaba.druid.sql.parser.ParserException: TODO. pos 221, line 2, column 100, token WITH`

**Comment by super3one** [comment]
> ```sql
> SELECT SysNo,MATCH(Name)AGAINST('张三' WITH QUERY EXPANSION) AS score
> FROM `test_table`
> WHERE MATCH(Name)AGAINST('张三' WITH QUERY EXPANSION)
> ```
> 
> 解析sql报错 `com.alibaba.druid.sql.parser.ParserException: TODO. pos 221, line 2, column 100, token WITH`

所以最后是怎么解决的呢？我也遇到了这个问题
