### ISSUE TITLE
使用Gbase时会报slowSqlMillis 和 mergeSql这两个连接属性的错误，请问怎么解决

### ISSUE THREAD

**Issue by rainrcn** [alibaba/druid#3525]
11:45:45.487 ERROR com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread
 2572 run - create connection SQLException, url: jdbc:gbase://10.77.10.10:5258/
test, errorCode 0, state null java.sql.SQLException: driver not support property
 druid.stat.slowSqlMillis.
        at com.gbase.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java
:378) ~[gbase-connector-java-8.3.81.jar!/:?]
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnecti
on(DruidAbstractDataSource.java:1578) ~[druid-1.1.14.jar!/:1.1.14]
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnecti
on(DruidAbstractDataSource.java:1644) ~[druid-1.1.14.jar!/:1.1.14]
        at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(Dru
idDataSource.java:2570) [druid-1.1.14.jar!/:1.1.14]

------------------------------------------------------------------------------

12:00:28.595 ERROR com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread
 2572 run - create connection SQLException, url: jdbc:gbase://10.77.10.10:5258/
test, errorCode 0, state null java.sql.SQLException: driver not support property
 druid.stat.mergeSql.
        at com.gbase.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java
:378) ~[gbase-connector-java-8.3.81.jar!/:?]
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnecti
on(DruidAbstractDataSource.java:1578) ~[druid-1.1.14.jar!/:1.1.14]
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnecti
on(DruidAbstractDataSource.java:1644) ~[druid-1.1.14.jar!/:1.1.14]
        at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(Dru
idDataSource.java:2570) [druid-1.1.14.jar!/:1.1.14]

------------------------------下面是配置-----------------------------

gbasetest:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:gbase://10.77.10.10:5258/test
      username: gbase
      password: 'gbase20110531'
      driverClassName: com.gbase.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      # exceptionSorter: true
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true

---------------------------依赖组件--------------------------------------
`<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>druid-spring-boot-starter</artifactId>
    <version>1.1.14</version>
</dependency>`

请问怎么解决？？十分感谢

**Comment by chenqi723** [comment]
配置中改为
connectionProperties: isCheckProperty=false
就可以禁用属性检查
