### ISSUE TITLE
数据库服务切换导致2分钟获取不到连接错误-版本1.1.14 / 1.1.20

### ISSUE THREAD

**Issue by whosharp** [alibaba/druid#3527]
在生产环境上，由于数据库服务器升级，需要将数据服务切换至新的数据库服务，发现在切换过程中，存在2分钟获取不到连接的情况，导致这2分钟的数据库操作全部失败。线下也多次测试，问题必现。
使用的腾讯云服务，整个切换过程大概是3~4秒，但是业务应用持续了2分钟sql报错，

切换主要步骤如下（腾讯云提供）：
> HA切换分为两种逻辑，分别是Master OK状态下的切换和Master Down状态下的切换。
>     MasterOK：
>     1. 置空VIP
>     2. kill老主库上的连接，客户端收到mysql返回的reset包；同时在TGW网关处标记访问老主库的五元组失效
>     3. VIP指向新主库
>     4.1 用户新连接指向新主库
>     4.2 没kill掉的老连接访问到TGW时，返回reset包，重新发起新连接访问新主库
>     MasterDown:
>     1. 置空VIP
>     2. 在TGW网关处标记访问老主库的五元组失效
>     3. VIP指向新主库
>     4.1 用户新连接指向新主库
>     4.2 老连接访问到TGW时，返回reset包，重新发起新连接访问新主库

一类是错误信息，持续时间与切换时间差不多，持续几秒
> org.springframework.dao.RecoverableDataAccessException: 
> ### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

另一类错误信息，持续2分钟
> org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
> ### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 2000, active 0, maxActive 20, creating 1, createElapseMillis 124212

配置如下
```xml
<bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource" init-method="init" destroy-method="close">
        <!-- 基本属性 url、user、password -->
        <property name="driverClassName" value="${jdbc.driverClassName}" />
        <property name="url" value="${jdbc.url}"/>
        <property name="username" value="${jdbc.username}"/>
        <property name="password" value="${jdbc.password}"/>
        <!-- 初始连接数,缺省为0,建议值实例总连接数/服务数量*0.2 -->
        <property name="initialSize" value="10"/>
        <!-- 最小空闲连接,缺省为0,建议和initialSize一致 -->
        <property name="minIdle" value="10"/>
        <!-- 最大连接数,缺省为8,建议值实例总连接数/服务数量 -->
        <property name="maxActive" value="20"/>
        <!-- 获取连接的最大等待时间,缺省为-1 -->
        <property name="maxWait" value="2000"/>
        <!-- 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x',缺省为null -->
        <property name="validationQuery" value="SELECT 1"/>
        <property name="minEvictableIdleTimeMillis" value="300000"/>
        <property name="keepAlive" value="true" />
        <!-- removeAbandoned 配置与否都存在2分钟获取不到连接的情况 -->
        <property name="removeAbandoned" value="true" />
        <property name="removeAbandonedTimeoutMillis" value="1800000" />
        <property name="validationQueryTimeout" value="1000" />
    </bean>
```

**Comment by wenshao** [comment]
这个和socketTimeout配置有关系吧，创建连接是单线程的，这时候创建连接在置空的VIP上，堵住了

**Comment by whosharp** [comment]
> 这个和socketTimeout配置有关系吧，创建连接是单线程的，这时候创建连接在置空的VIP上，堵住了

谢谢大佬的回复，问题已经解决了。
由于在日志中没有“Connection timed out”的相关错误信息，一直没往这个方面想。
经过大佬提醒，通过在jdbc.url中增加了connectTimeout=5000配置后，错误持续了4点几秒后就正常了，如果没有配置的这个参数，linux下默认建立连接的超时时间为127秒（与错误日志显示的持续时间一致，大约124秒多），参考这篇文章：https://blog.csdn.net/qq_22054285/article/details/79189146
另参见[mysql相关配置文档](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-configuration-properties.html)
