### ISSUE TITLE
maven仓库下载的1.1.20版本的druid包与github上ResultSetProxyImpl这个类的代码不一致？

### ISSUE THREAD

**Issue by wangzhedong** [alibaba/druid#3530]
maven仓库下载下来的jar包ResultSetProxyImpl的第1559行代码与github上的代码不符合
github上： @Override
    public <T> T getObject(String columnLabel, Class<T> type) throws SQLException {
        FilterChainImpl chain = createChain();
        T value = chain.resultSet_getObject(this, columnLabel, type);
        recycleFilterChain(chain);
        return value;
    }
1.1.20jar包中：
public <T> T getObject(String columnLabel, Class<T> type) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }
然后就导致localdateTime还是报错，这个问题难道还没有修复嘛？

**Comment by lizongbo** [comment]
请使用最新版本验证
