### ISSUE TITLE
Communications link failure

### ISSUE THREAD

**Issue by Ahrievil** [alibaba/druid#3532]
每天固定的时间就会在日志里面反馈出来，不知道是mysql的配置问题还是druid的配置问题，还是druid的版本问题
我用的是druid-starter 版本是  1.1.18
druid的版本号是 1.1.18(很奇怪，错误代码里面指明的是1.1.17)
mysql的版本是5.7.20
mysql-connector-java的版本是5.1.40
1.日志报错截图：（我们用了mycat做数据库中间件）

![image](https://user-images.githubusercontent.com/23119719/67748941-02f99f80-fa67-11e9-9a2a-9382130d5f0c.png)

![image](https://user-images.githubusercontent.com/23119719/67748978-1573d900-fa67-11e9-92f7-980be6203bc9.png)

2.druid的​配置：
#datasource
spring.datasource.driver-class-name = com.mysql.jdbc.Driver
spring.datasource.druid.filter.stat.enabled = true
spring.datasource.druid.filter.stat.log-slow-sql = true
spring.datasource.druid.filter.stat.merge-sql = true
spring.datasource.druid.filter.stat.slow-sql-millis = 1000
spring.datasource.druid.filters = stat,wall,log4j
spring.datasource.druid.keep-alive = true
spring.datasource.druid.remove-abandoned = true
spring.datasource.druid.remove-abandoned-timeout = 1800
spring.datasource.druid.initialSize = 5
spring.datasource.druid.maxActive = 30
spring.datasource.druid.maxWait = 60000
spring.datasource.druid.minEvictableIdleTimeMillis = 300000
spring.datasource.druid.timeBetweenEvictionRunsMillis = 60001
spring.datasource.druid.minIdle = 5
spring.datasource.druid.stat-view-servlet.enabled = true
spring.datasource.druid.stat-view-servlet.login-username = tezign
spring.datasource.druid.stat-view-servlet.login-password = tezign0818
spring.datasource.druid.testOnBorrow = false
spring.datasource.druid.testOnReturn = false
spring.datasource.druid.testWhileIdle = true
spring.datasource.druid.useGlobalDataSourceStat = true
spring.datasource.druid.validationQuery = SELECT 1 FROM DUAL
spring.datasource.druid.validationQueryTimeout = 10
spring.datasource.druid.web-stat-filter.enabled = true
spring.datasource.type = com.alibaba.druid.pool.DruidDataSource

#mysql
spring.datasource.druid.my-cat.url = jdbc:mysql://mycat:xxxx/xx?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
spring.datasource.druid.my-cat.username = xxxx
spring.datasource.druid.my-cat.password = xxxx

3.mysql的关键配置

wait_timeout, 86400
connect_timeout, 10
interactive_timeout, 7200

**Comment by hanshisan** [comment]
老哥解决了嘛 我也遇到了这个问题

**Comment by hanshisan** [comment]
看你那个 validationQuery配置应该不对 连接mysql用的应该是select 1

**Comment by Ahrievil** [comment]
谢谢提醒，我试试

> 老哥解决了嘛 我也遇到了这个问题

**Comment by Ahrievil** [comment]
> 看你那个 validationQuery配置应该不对 连接mysql用的应该是select 1

谢谢提醒，我试试

**Comment by Ahrievil** [comment]
结案了，问题出在我们用的是mycat来作为数据库分表的工具，mycat重启会导致链接丢失，经查证，每次重启和报错的时间完全吻合，所以这个issues我关了

**Comment by Ahrievil** [comment]
结案了，问题出在我们用的是mycat来作为数据库分表的工具，mycat重启会导致链接丢失，经查证，每次重启和报错的时间完全吻合，所以这个issues我关了
