### ISSUE TITLE
postgresql 执行 begin end语句块报错 

### ISSUE THREAD

**Issue by liuheiniu** [alibaba/druid#3538]
postgresql 执行 begin end语句块报错 

库 : druid-spring-boot-starter
版本: 1.1.20

想实现的功能 
begin;
update table set name='a', sn='a' where id=1;
update table set name='b', sn='b' where id=2;
update table set name='c', sn='c' where id=3;
end;

配置文件中已配置 multi-statement-allow: true 
也试过@Bean的方式配置同样无效

报错：
com.alibaba.druid.wall.WallFilter        : sql injection violation, not terminal sql, token END : begin;

经过反复试验。虽然报错。但数据库的值却已经被修改。
如果去掉wall 相关配置 后成功执行且无报错。

**Comment by ipanocloud** [comment]
我也遇到了类似的问题

**Comment by lizongbo** [comment]
加上语法支持了，等1.2.21版本验证即可
