### ISSUE TITLE
升级druid到1.1.21

### ISSUE THREAD

**Issue by mastcer** [alibaba/druid#3544]
[WARNING] The POM for com.alibaba:druid:jar:1.1.21 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

**Comment by mastcer** [comment]
<dependency>
            <groupId>com.sun</groupId>
            <artifactId>tools</artifactId>
            <version>1.8</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/lib/openjdk-1.8-tools.jar</systemPath>
        </dependency>

        <dependency>
            <groupId>com.sun</groupId>
            <artifactId>jconsole</artifactId>
            <version>1.8</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/lib/openjdk-1.8-jconsole.jar</systemPath>
        </dependency>

**Comment by imEzreal** [comment]
+1
