### ISSUE TITLE
TestWhileIdle=true的情况下空闲连接失效

### ISSUE THREAD

**Issue by zhangever** [alibaba/druid#3545]
配置:
```
testWhileIdle=true
testOnBorrow=false
testOnReturn=false
keepAlive=true
```
mysql服务端wait_timeout=60分钟。
默认情况下， 每60秒通过"select 1‘’检测一次空闲连接。
然而， 部分空闲连接依然给mysql杀掉。

从mysql看空闲的连接的情况，
`select * from infomation_schema.processlist order by time desc limit 10;`
发现大量的连接空闲时间超过10几分钟(Command=Sleep)。(理论上空闲时间不超过1分钟)

开启mysql的日志， 没发现保活查询语句`select 1`
在客户端抓包， 也常时间没发现有tcp包发往mysql。

查询代码`MySqlValidConnectionChecker.isValidConnection`, 发现即使配置了`validationQuery`， 保活机制依然默认采用mysql_ping。

这个设置很不合理且没有文档说明。 这个机制只能用于检测连接是否有效，对于`testOnBorrow`来说可能比较合适。
但对于`testWhileIdle`来说， 并不起作用，因为它不会重置连接的空闲时间。

而且， 禁用`usePingMethod`这个参数，并没有在wiki上说明。

**Comment by chensk0601** [comment]
想问下你这个是哪个版本？

**Comment by zhangever** [comment]
1.1.14？
看代码最新版本也是一样的



---原始邮件---
发件人: "凯凯"<notifications@github.com&gt;
发送时间: 2019年11月5日(星期二) 晚上11:30
收件人: "alibaba/druid"<druid@noreply.github.com&gt;;
抄送: "zhangever"<439674061@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [alibaba/druid] TestWhileIdle=true的情况下空闲连接失效 (#3545)



想问下你这个是哪个版本？

**Comment by zhangever** [comment]
禁用usePingMethod后，经过调试发现，客户端30分钟才会发一次SELECT 1， 预期是1分钟(默认配置)
![image](https://user-images.githubusercontent.com/2963615/68267254-c5ab9800-008c-11ea-8395-df672bd423b6.png)

**Comment by zhangever** [comment]
最终结论:
心跳方式不管是mysql_ping还是SELECT 1， 都可以重置连接的空闲时间。
然后，保活线程是1分钟执行一次，但只对空闲时间超过minEvictableIdleTimeMillis的连接发心跳。

我们之前minEvictableIdleTimeMillis设置是30分钟， 所以30分钟才会看到一次心跳。 而mysql服务端不知道为何， 对于超过30分钟的连接会直接kill掉。

**Comment by wzgy** [comment]
> 最终结论:
> 心跳方式不管是mysql_ping还是SELECT 1， 都可以重置连接的空闲时间。
> 然后，保活线程是1分钟执行一次，但只对空闲时间超过minEvictableIdleTimeMillis的连接发心跳。
> 
> 我们之前minEvictableIdleTimeMillis设置是30分钟， 所以30分钟才会看到一次心跳。 而mysql服务端不知道为何， 对于超过30分钟的连接会直接kill掉。

30分钟说不定是硬件防火墙拆的连接🤭
