### ISSUE TITLE
Druid 1.1.21 gradle compile error

### ISSUE THREAD

**Issue by liaomengge** [alibaba/druid#3552]
![image](https://user-images.githubusercontent.com/12670328/68266427-0bb32c80-008a-11ea-833f-5c2795f147fd.png)
![image](https://user-images.githubusercontent.com/12670328/68266447-21c0ed00-008a-11ea-9e3a-33eca69b79c9.png)
在1.1.21中，pom强制引入了绝对路径，故在编译中报错了，在1.1.20中是没有这个的~

**Comment by gxzqaz** [comment]
maven 下也会有报错 +1

**Comment by houseme** [comment]
see https://github.com/alibaba/druid/pull/1006

**Comment by lizongbo** [comment]
请使用最新版验证
