### ISSUE TITLE
最新版1.1.21在maven无法打包

### ISSUE THREAD

**Issue by xcocean** [alibaba/druid#3557]
The POM for com.alibaba:druid:jar:1.1.21 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

**Comment by lzysuqianqiu** [comment]
same

**Comment by duhongle** [comment]
make

**Comment by trows** [comment]
+1

**Comment by tiger8888** [comment]
+1

**Comment by mastcer** [comment]
+1

**Comment by happyycm** [comment]
+1

**Comment by imEzreal** [comment]
+1

**Comment by cloud13th** [comment]
+10086

**Comment by Mirrormiss** [comment]
+1

**Comment by MstString** [comment]
+1

**Comment by MartinForReal** [comment]
'dependencies.dependency.systemPath' for com.alibaba:jconsole:jar must specify an absolute path but is ${env.JAVA_HOME}/lib/jconsole.jar @ 
'dependencies.dependency.systemPath' for com.alibaba:tools:jar must specify an absolute path but is ${env.JAVA_HOME}/lib/tools.jar @ 

after I set log level of maven to debug , I've got above messages. 

It's a good idea to check if JAVA_HOME is set.  FYI

**Comment by YiuTerran** [comment]
为啥至今还没有解决…这不是个小问题么

**Comment by folochina** [comment]
+1

**Comment by lizongbo** [comment]
请使用最新版验证
