### ISSUE TITLE
impala和mongo获取驱动类错误

### ISSUE THREAD

**Issue by smark-d** [alibaba/druid#3559]
**com.alibaba.druid.util.JdbcUtils**类，getDriverClassName(String rawUrl)方法，建议新增对impala和mongo的支持

**Comment by yx91490** [comment]
> **com.alibaba.druid.util.JdbcUtils**类，getDriverClassName(String rawUrl)方法，建议新增对impala和mongo的支持

参考 https://github.com/alibaba/druid/issues/3423#issuecomment-526152631
