### ISSUE TITLE
1.1.21 pom错误, mavenCentral

### ISSUE THREAD

**Issue by monkeylite** [alibaba/druid#3564]
'dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${project.basedir}/lib/openjdk-1.8-tools.jar in com.alibaba:druid:1.1.21
    'dependencies.dependency.systemPath' for com.sun:jconsole:jar must specify an absolute path but is ${project.basedir}/lib/openjdk-1.8-jconsole.jar in com.alibaba:druid:1.1.21

**Comment by moonfruit** [comment]
嗯嗯，遇到了同样的问题

**Comment by houseme** [comment]
see https://github.com/alibaba/druid/pull/3565

**Comment by toutzhang** [comment]
Gradle 6.0.1 构建依赖时，报同样的错。

**Comment by softboy99** [comment]
遇到同样的问题

**Comment by wangzhongwen** [comment]
还是有这个问题

**Comment by app2smile** [comment]
同样的问题

**Comment by HancockY** [comment]
console

**Comment by HancockY** [comment]
加1

**Comment by jdzgd** [comment]
同样的问题

**Comment by dictionaryshi** [comment]
同样的问题+1

**Comment by shapled** [comment]
pom.xml 的 build plugins 中添加

```xml
<plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-surefire-plugin</artifactId>
   <configuration>
      <useSystemClassLoader>false</useSystemClassLoader>
   </configuration>
</plugin>
```

**Comment by yusiwen** [comment]
+1 same problem here

**Comment by LiJunYi2** [comment]
加1

**Comment by coodex2016** [comment]
+1

**Comment by coodex2016** [comment]
The POM for com.alibaba:druid:jar:1.1.22 is invalid, transitive dependencies (if any) will not be available: 2 problems were encountered while building the effective model for com.alibaba:druid:1.1.22

**Comment by DoneSpeak** [comment]
+1

**Comment by GreenHandWu** [comment]
啥时候修复呀

**Comment by tiegangli** [comment]
惊呆了，原来这是一个19年就存在的问题吗？

**Comment by zhangpeng16488** [comment]
+1,22年了，这个问题依然存在

**Comment by lizongbo** [comment]
这个报错信息并不影响使用，不过最新版也优化了，请使用最新版验证
