### ISSUE TITLE
Lexer对UTF-8的BOM缺乏支持

### ISSUE THREAD

**Issue by snoopyhzy** [alibaba/druid#3576]
解析用户上传脚本时，将输入流转为String后。
发现如果是带BOM的UTF-8文件，会出现词法解析失败。

词法解析器是否有条件处理这个？以前用ANLTR好像是不会有问题的。

目前在用户上传后发现如果文件是StartWith \uFEFF的，则str.substring(1)。

**Comment by lizongbo** [comment]
这种在自己读取文件发现由bom信息开头的，自行截取即可。
