### ISSUE TITLE
sql监控合并sql出错

### ISSUE THREAD

**Issue by wenbochang888** [alibaba/druid#3579]
spring.datasource.druid.filter.stat.merge-sql=true  已经设置为true了，参考了文档的第四点

但sql几分钟达到了几千条，页面直接卡死了，看了看之前的issus，感觉会出oom的问题。

是否解决下这个bug？？？

![微信图片_20191123182231](https://user-images.githubusercontent.com/26178822/69477250-d85cf580-0e1e-11ea-8cfc-d31d5698163d.jpg)

**Comment by wenbochang888** [comment]
仅仅limit不同，其他全部相似。sql不能merge，页面直接卡死

**Comment by wenbochang888** [comment]
@wenshao 谢谢。期待在后续版本可以把监控这块做好点，别烂尾了。

**Comment by lizongbo** [comment]
请使用最新版验证
