### ISSUE TITLE
no support explain analyze 

### ISSUE THREAD

**Issue by Sreaper** [alibaba/druid#3587]
i see mysql 8.0 support explain analyze syntax
i use druid(1.1.20) to execute 'explain analyze select count(*) from baker02' cause error
sql parse error: syntax error, error in :'lyze select count(*) from baker02'

**Comment by lizongbo** [comment]
出错的这个sql语法就是错的

explain select count(*) from baker02 正确
    
analyze select count(*) from baker02 正确

explain analyze select count(*) from user 错误 出错信息如下：

[Code: 1064, SQL State: 42000]  (conn=849) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'analyze select count(*) from baker02 ' at line 1  [Script position: 535 - 576]
