### ISSUE TITLE
druid是否支持设置加密套件

### ISSUE THREAD

**Issue by Fang57** [alibaba/druid#3590]

**Comment by Fang57** [comment]
在Url中直接设置&enabledSslProtocolSuites=TLSv1.2&enabledSslCipherSuites=TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 这种会报错

**Comment by lizongbo** [comment]
druid不控制不干预ssl连接相关的配置，按照各个数据的jdbc设置进行即可。
