### ISSUE TITLE
SQLUtils.toSQLString oracle, format关键字为小写时输出了错误的sql语句

### ISSUE THREAD

**Issue by xuesong123** [alibaba/druid#3593]
// 测试用例
            String dbType = JdbcConstants.ORACLE;
            String sql = "alter table my_test rename to my_test2";
            SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, dbType);
            List<SQLStatement> statements = parser.parseStatementList();
            FormatOption DEFAULT_FORMAT_OPTION = new FormatOption(false, true, false);

            for(SQLStatement statement : statements) {
                System.out.println("sql: " + statement.getClass().getName());
                String result = SQLUtils.toSQLString(statement, dbType, DEFAULT_FORMAT_OPTION);
                System.out.println(result); // rename my_testto my_test2
            }

只要 FormatOption 参数的第一个参数为小写，输出就会出错，表名和关键字中间少了个空格

**Comment by lizongbo** [comment]
最新版验证是ok的
```
 public void test_rename() {
        String sql = "alter table my_test rename to my_test2";
        SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, DbType.oracle);
        List<SQLStatement> statements = parser.parseStatementList();
        FormatOption DEFAULT_FORMAT_OPTION = new FormatOption(false, true, false);
        com.alibaba.druid.sql.ast.statement.SQLAlterTableStatement hh;
        for(SQLStatement statement : statements) {
            System.out.println("sql: " + statement.getClass().getName() + " " + statement.toString());
            String result = SQLUtils.toSQLString(statement, DbType.oracle, DEFAULT_FORMAT_OPTION);
            System.out.println(result); // rename my_testto my_test2
        }
    }


```
执行结果：

rename my_test to my_test2
