### ISSUE TITLE
这个可以连接Apache Druid嘛

### ISSUE THREAD

**Issue by Doslin** [alibaba/druid#3595]
` String url = "jdbc:avatica:remote:url=http://172.16.16.152:8888/druid/v2/sql/avatica/";`
url如上，但是不知道选择哪个驱动

**Comment by BadLemon67** [comment]
![image](https://github.com/alibaba/druid/assets/78586518/6e76fbb1-b23d-42f9-aca6-84de39224362)
源码中没有找到avatica相关驱动
运行效果如图，应该是没有支持

**Comment by lizongbo** [comment]
有jdbc驱动就可以， 自己明确指定Driver class即可。
