### ISSUE TITLE
Errors occurred in java11 for tools.jar and jconsole.jar

### ISSUE THREAD

**Issue by cy503328434** [alibaba/druid#3601]
Errors occurred while build effective model from E:\dev\gradle\repository\caches\modules-2\files-2.1\com.alibaba\druid\1.1.21\d0972638d4f2620717ad3adc1524f65dd3eb9fc\druid-1.1.21.pom:
    'dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${project.basedir}/lib/openjdk-1.8-tools.jar in com.alibaba:druid:1.1.21
    'dependencies.dependency.systemPath' for com.sun:jconsole:jar must specify an absolute path but is ${project.basedir}/lib/openjdk-1.8-jconsole.jar in com.alibaba:druid:1.1.21
    'dependencies.dependency.systemPath' for com.alibaba:jconsole:jar must specify an absolute path but is ${env.JAVA_HOME}/lib/jconsole.jar in com.alibaba:druid:1.1.21
    'dependencies.dependency.systemPath' for com.alibaba:tools:jar must specify an absolute path but is ${env.JAVA_HOME}/lib/tools.jar in com.alibaba:druid:1.1.21

I adding     "implementation ('com.alibaba:druid:1.1.21'){
        exclude group: 'com.alibaba', module: 'jconsole'
        exclude group: 'com.alibaba', module: 'tools'
    }" in my project, but still invalid.

**Comment by HancockY** [comment]
我也这个问题

**Comment by libertyall** [comment]
参见https://github.com/alibaba/druid/pull/3565。
找到druid-1.1.21.pom，将里面的openjdk-1.8-tools.jar和openjdk-1.8-jconsole.jar依赖删掉。

**Comment by lizongbo** [comment]
请使用最新版验证
