### ISSUE TITLE
配置keepAlive无法生效

### ISSUE THREAD

**Issue by Zhang-xudong** [alibaba/druid#3607]
以下是我的部分配置信息，打开druid的监控页面观察其他的都生效了，只有这个keepAlive始终都不生效，一直都是false：
`dataSourcePropertis.put("keepAlive","true");
dataSourcePropertis.put("maxWait", "60000"); 
dataSourcePropertis.put("removeAbandonedTimeout", "3600");  
dataSourcePropertis.put("removeAbandoned", "true");        
dataSourcePropertis.put("logAbandoned", "true");          `
我用的druid版本是1.1.17.

**Comment by qiaolugithub** [comment]
https://github.com/alibaba/druid/wiki/KeepAlive_cn

**Comment by qiaolugithub** [comment]
试试启动参数的，我就这么用了，但是你可以启动时候调试下看看应该有参数打入druid数据源的set方法

**Comment by lizongbo** [comment]
请使用最新版验证
