### ISSUE TITLE
SQLUtils.parseStatements 不支持 DB2 的 limit 关键字

### ISSUE THREAD

**Issue by MiluDeer** [alibaba/druid#3622]
DB2 已经支持用 limit 关键字，但用 SQLUtils.parseStatements 解析时仍然出错， 报 ParserException 异常

**Comment by Mosys** [comment]
将 Druid 1.1.21 版本已经修复这个问题，升级一下就好。

**Comment by MiluDeer** [comment]
> Druid 1.1.21 版本已经修复这个问题，升级一下就好。

好的， 谢谢

**Comment by tubesummer** [comment]
请问使用SQLUtils.parseStatements 后，如何添加上limit条件，DB2数据库
