### ISSUE TITLE
 使用mybatis 3.5.2 cursor 会造成Error querying database.  Cause: java.sql.SQLFeatureNotSupportedException

### ISSUE THREAD

**Issue by wu191287278** [alibaba/druid#3625]
使用mybatis 3.5.2 cursor 会造成Error querying database.  Cause: java.sql.SQLFeatureNotSupportedException  
希望支持 Statement.closeOnCompletion

**Comment by wu191287278** [comment]
![image](https://user-images.githubusercontent.com/5573184/70884321-b23b0780-2010-11ea-83b9-0c9942ceb3e7.png)
![image](https://user-images.githubusercontent.com/5573184/70884344-bff08d00-2010-11ea-9aba-47688dcd0810.png)

**Comment by always-busy** [comment]
+1

**Comment by wanglforever** [comment]
+1

**Comment by lizongbo** [comment]
请使用最新版本验证
