### ISSUE TITLE
偶尔出现   Reason: maxEvictableIdleTimeMillis must be grater than 

### ISSUE THREAD

**Issue by 1725636955** [alibaba/druid#3636]
spring.datasource.admin.min-evictable-idle-time-millis=600000
spring.datasource.admin.max-evictable-idle-time-millis=900000
我配置的max明显比min大,但是偶尔会出现
Reason: maxEvictableIdleTimeMillis must be grater than 
bug,不常见,10次大概有2次,重启就没有了,不影响运行

**Comment by DreamUFO** [comment]
我的也是 同样的问题 
暂时这样解决的
@Bean(name = "dataSource")
    @ConfigurationProperties(prefix = "xx.xx.druid")
    public DataSource getOrderDataSource() {
 
        DruidDataSource dataSource = new DruidDataSource();
 
        /**setMinEvictableIdleTimeMillis需要先设置*/
        dataSource.setMinEvictableIdleTimeMillis(druidConfig.getMinEvictableIdleTimeMillis());
        dataSource.setMaxEvictableIdleTimeMillis(druidConfig.getMaxEvictableIdleTimeMillis());
 
        return dataSource;
    }

**Comment by 1725636955** [comment]
> 我的也是 同样的问题
> 暂时这样解决的
> @bean(name = "dataSource")
> @ConfigurationProperties(prefix = "xx.xx.druid")
> public DataSource getOrderDataSource() {
> 
> ```
>     DruidDataSource dataSource = new DruidDataSource();
> 
>     /**setMinEvictableIdleTimeMillis需要先设置*/
>     dataSource.setMinEvictableIdleTimeMillis(druidConfig.getMinEvictableIdleTimeMillis());
>     dataSource.setMaxEvictableIdleTimeMillis(druidConfig.getMaxEvictableIdleTimeMillis());
> 
>     return dataSource;
> }
> ```

后来发现用法错误,return DruidDataSourceBuilder.create().build();这样就行了
