### ISSUE TITLE
数据库连接失效

### ISSUE THREAD

**Issue by shanyuhzz** [alibaba/druid#3651]
目前公司采用的是微服务架构，有个商品服务由于需要定时从供应商那边缓存数据，频率2小时一次，每次两条线程，每个线程批量写入2000条，采用的是jdbc的方式进行数据存储，直接使用数据库连接池进行操作
@Autowired
private DataSource druidDataSource;
目前连接池配置是
druid.initialSize=1
druid.maxActive=8
druid.minIdle=4
druid.maxWait=60000
druid.testWhileIdle=true
druid.validationQuery=select 1 from dual
druid.timeBetweenEvictionRunsMillis=60000
druid.minEvictableIdleTimeMillis=1800000
druid.keepAlive=true

每60s的销毁线程执行，最小空闲时间是半个小时，有保活的操作

数据库的wait_timeout和interactive_timeout都是8个小时，用的是阿里云的mysql数据库，配置是单核2G内存

问题：不规律的出现数据库连接不上的问题，每次都会有几个微服务挂掉，报的异常信息都一致，异常信息如下：
 DruidPooledStatement             CommunicationsException, druid version 1.1.21, jdbcUrl : jdbc:mysql:localhost:3306/service_user?useUnicode=true&useSSL=true, testWhileIdle true, idle millis 1, minIdle 4, poolingCount 3, timeBetweenEvictionRunsMillis 60000, lastValidIdleMillis 1, driver com.mysql.jdbc.Driver, exceptionSorter com.alibaba.druid.pool.vendor.MySqlExceptionSorter
2019-12-26 14:25:25.154 ERROR 6 [icator-0] DruidDataSource                  discard connection

com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 7,538 milliseconds ago.  The last packet sent successfully to the server was 1 milliseconds ago.

Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.

我不知道是我的配置有问题，还是数据库的配置不支持4000的同时写入，所以想请教下，希望能在这里解决掉这个问题，谢谢

**Comment by lemontree8801** [comment]
MySQL的 druid.validationQuery=select 1

**Comment by wudanjun** [comment]
同问，此处的last packet received是7秒之前，按理不会产生任何超时中断。此处应该也不会触发testWhileIdle，那这个中断为何发生？

**Comment by ckh101** [comment]
什么原因

**Comment by git10135405** [comment]
这么多人有这个问题

**Comment by dayAndnight2018** [comment]
@wenshao 大佬，这个问题有解吗？

**Comment by yamiowen** [comment]
怀疑这个问题是druid底层的一个bug，也没有官方的一个解释
