### ISSUE TITLE
SQLUtils.formatOracle格式化的sql如果带有order by和union all会有问题

### ISSUE THREAD

**Issue by jevislee** [alibaba/druid#3656]
druid版本为1.1.21.jar

比如
select * from (
  select * from tbl order by id
)
union all
select * from tbl

使用SQLUtils.formatOracle格式化后为
select *
from (
  select *
  from tbl
  order by id
  union all
  select *
  from tbl
)
执行格式化后的sql报错,有order by的语句必须在外面包一层select才能union all

**Comment by snoopyhzy** [comment]
这其实不是格式化问题是语法分析器parser的问题 他解析认为下面那个union all是同级的所以出这个问题 源码里有个中文注释xxx必须放上面什么的 。。反正也没看懂这快

**Comment by fanfanAlice** [comment]
你这个问题解决了吗？ 我也碰到一样的问题。
