### ISSUE TITLE
postgrsql on conflict (id) do update set报错

### ISSUE THREAD

**Issue by yfdxzy2010** [alibaba/druid#3661]
16:22:53.535 [schedule-pool-2] ERROR c.a.d.f.s.StatFilter - [mergeSql,149] - merge sql error, dbType postgres, druid-1.1.21, sql : 
			insert into sys_user_online(sessionId,login_name) values (?, ?)  on conflict (sessionId) do update set login_name=excluded.login_name
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'     on conflict (sessionId) do upd', expect ON, actual ON pos 215, line 2, column 50, token ON
应该是对postgresql的解析问题

**Comment by yfdxzy2010** [comment]
db type 至少需要加两个地方

**Comment by YourXin** [comment]
> db type 至少需要加两个地方

请问怎么个处理方式呢？

**Comment by TalentSSS** [comment]
> db type 至少需要加两个地方

加哪两个地方？
```Java
List<SQLStatement> sqlStatements = SQLUtils.parseStatements(sql, DbType.postgresql);
```
