### ISSUE TITLE
能否开放JdbcParameter 扩展的能力，目前不支持LocalDateTime

### ISSUE THREAD

**Issue by jackphang** [alibaba/druid#3664]
![image](https://user-images.githubusercontent.com/26587479/71669757-c6209080-2da8-11ea-859c-c5f574dfb079.png)

![image](https://user-images.githubusercontent.com/26587479/71669787-dc2e5100-2da8-11ea-8a93-05e597b19da2.png)

**Comment by JieJo** [comment]
druid 1.1.20, Oracle 驱动 升级到jdbc8解决了这个问题

**Comment by lizongbo** [comment]
请使用最新版验证
