### ISSUE TITLE
ClickHouse的Visitor

### ISSUE THREAD

**Issue by RaulGuo** [alibaba/druid#3666]
对clickhouse的sql解析时需要使用SchemaStatVisitor来获取sql中的visitor信息，但没有ClickHouse专用的SchemaStatVisitor。

**Comment by RaulGuo** [comment]
对clickhouse的sql解析时需要使用SchemaStatVisitor来获取sql中的visitor信息，但没有ClickHouse专用的SchemaStatVisitor。

**Comment by viokuma** [comment]
同求，希望durid可以实现这个功能，我们想用在数据血缘分析上

**Comment by LeeMouRen** [comment]
> SchemaStatVisitor

请问之后有进展吗？现在有同样的需求，求指路

**Comment by lizongbo** [comment]
已经增加了 ClickSchemaStatVisitor
