### ISSUE TITLE
The POM for com.alibaba:druid:jar:1.1.21 is invalid

### ISSUE THREAD

**Issue by dictionaryshi** [alibaba/druid#3675]
1.1.21 maven 打包时会报The POM for com.alibaba:druid:jar:1.1.21 is invalid 这个错，1.1.20没有这个问题。请解决一下吧

**Comment by asdf913** [comment]
The below log is the warning message raised by Maven for **com.alibaba:druid:jar:1.1.21** dependency.
The log could be retrieve by **mvn clean package -X**
> [WARNING] The POM for com.alibaba:druid:jar:1.1.21 is invalid, transitive dependencies (if any) will not be available: 2 problems were encountered while building the effective model for com.alibaba:druid:1.1.21
[ERROR] 'dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${project.basedir}/lib/openjdk-1.8-tools.jar @ 
[ERROR] 'dependencies.dependency.systemPath' for com.sun:jconsole:jar must specify an absolute path but is ${project.basedir}/lib/openjdk-1.8-jconsole.jar @

**Comment by feidegenggao** [comment]
回到上一个版本，继续搬砖。

**Comment by asdf913** [comment]
So, do you mean this issue will be still investigating, or just close this issue?

**Comment by gaofengbj** [comment]
还是没有解决这个问题

**Comment by shuohao** [comment]
1.1.22解决了

**Comment by asdf913** [comment]
The warning is gone in 1.1.22 version.
Thanks you for your work.

**Comment by yujiaao** [comment]
https://blog.csdn.net/cockroach02/article/details/102734426
Use JDK but JRE resolve this problem, wild!

**Comment by lizongbo** [comment]
请使用最新版验证
