### ISSUE TITLE
The POM for com.alibaba:druid:jar:1.1.21 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

### ISSUE THREAD

**Issue by zuihou** [alibaba/druid#3681]
maven 在install 时，会报这个警告，但不影响运行。

The POM for com.alibaba:druid:jar:1.1.21 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

**Comment by zuihou** [comment]
1.1.21 之前的版本没问题

**Comment by shuohao** [comment]
+1

**Comment by imoling** [comment]
同样问题，目前哪个版本最好用呢？

**Comment by fjalimama** [comment]
同样问题，目前哪个版本最好用呢？

**Comment by fjalimama** [comment]
难道说跟idea的版本还有关系?  用2019.3的都没问题,用2020.1的就有问题了

**Comment by zuihou** [comment]
亲测1.1.22版本已修复

**Comment by beijixing1745** [comment]
jdk11, idea 2019.3.5, idea 2020.1.2环境，还有警告。

The POM for com.alibaba:druid:jar:1.1.22 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

**Comment by zykaka** [comment]
1.1.24 still has this issue.  Problem:  pom file in central repository doesn't has the header line to indicate it is a xml file. 
https://repo1.maven.org/maven2/com/alibaba/druid/1.1.24/druid-1.1.24.pom

Add  <?xml version="1.0" encoding="UTF-8"?> will resolve this issue.
