### ISSUE TITLE
druid-spring 1.1.20一直报Caused by: java.sql.SQLException: Operation not allowed after ResultSet closed

### ISSUE THREAD

**Issue by TsukasaHwan** [alibaba/druid#3691]
是我配置有问题吗？

>       initial-size: 10
>       min-idle: 10
>       max-active: 100
>       max-wait: 60000
>       time-between-eviction-runs-millis: 60000
>       min-evictable-idle-time-millis: 30000
>       test-on-borrow: false
>       test-while-idle: true
>       test-on-return: false
>       keep-alive: true
>       remove-abandoned: true
>       remove-abandoned-timeout: 1800
>       log-abandoned: true
>       default-auto-commit: false

sql语句是没有问题的

**Comment by jolinery** [comment]
把这个关掉就ok了
keep-alive: false

**Comment by yangmengmeng01** [comment]
怎么解决的啊？把keep-alive: false也没用
