### ISSUE TITLE
还是中文问题

### ISSUE THREAD

**Issue by yangjiandong** [alibaba/druid#370]
druid 0.2.19
jdbc.url=jdbc:wrap-jdbc:filters=encoding:jdbc:oracle:thin:...
<property name="connectionProperties">
        
        <value>clientEncoding=GBK;serverEncoding=ISO-8859-1;</value>
</property>
现在运行hibernate，一般sql(只要不含中文信息的语句或者采用占位符的sql)都可以，碰到select \* from table where col='中文'，select col as "中文" from tablez 这样的sql还是有问题

**Comment by Wow-Chen** [comment]
相同情况，目前druid版本1.1.23,sql 语句有中文就会乱码，导致查询无数据，请问有解决办法吗

**Comment by shixued** [comment]
这个问题根源在jdbc thin驱动，默认是把sql getBytes(字符集)提交给oracle执行的
