### ISSUE TITLE
Support PolarDB  Compatible with Oracle Syntax

### ISSUE THREAD

**Issue by ldming** [alibaba/druid#3703]
Now, druid does not support PolarDB driver, I will support it.

**Comment by cdh-dev** [comment]
请问druid是否支持POLARDB(oracle)数据库？到底是用poardb驱动还是用postgresql驱动？

**Comment by cdh-dev** [comment]
用poardb驱动时，JDBC的URL用jdbc:polardb://开头的URL，启动后，会报testWhileIdle is true, validationQuery not set，而用postgres的驱动，JDBC的URL用jdbc:postgresql:开头的地址，则不会报这个错；当然这个参数validationQuery都是有配的

**Comment by ldming** [comment]
> 请问druid是否支持POLARDB(oracle)数据库？到底是用poardb驱动还是用postgresql驱动？

目前还不支持。但可以使用 pollardb 的驱动，正确配置驱动名就可以，dbType可以指定为 postgresql。

**Comment by cdh-dev** [comment]
感谢回复；我们现在用polardb驱动，jdbc的url也是要jdbc:polardb开头，但是没指定dbtype,是否需要指定？目前也是关了wall和stat的filter;没关的话，对于oracle的merger into语法会报错。这样使用是否稳定，目前处于测试阶段中，没有大并发使用。
