### ISSUE TITLE
merge sql error, dbType postgresql

### ISSUE THREAD

**Issue by YourXin** [alibaba/druid#3711]
`create table if not exists ip_20200302 partition of ip for values from (20200302) to (20200303);`

com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'0302 partition of ip', expect IDENTIFIER, actual IDENTIFIER pos 72, line 1, column 63, token IDENTIFIER partition

merge sql error, dbType postgresql, druid-1.1.10
merge=true.  不支持partition字段？

**Comment by lizongbo** [comment]
请使用最新版验证。
