### ISSUE TITLE
是否支持 log4j2 Asynchronous Loggers

### ISSUE THREAD

**Issue by norangit** [alibaba/druid#3716]
hi, 请问，druid pool 是否支持  log4j2 Asynchronous Loggers？如果支持的话是否需要做什么特别的配置？我按照 log4j2 官方的推荐添加了系统属性，全局启用了异步特性：

```System.setProperty("log4j2.contextSelector", "org.apache.logging.log4j.core.async.AsyncLoggerContextSelector");```

启动 SpringBoot 后，发现 druid 打印出来的日志，找不到打印日志的类，显示 ？号，如下：

```
[18:56:26.457] DEBUG ?   - {conn-10002, pstmt-20008} Parameters : []
[18:56:26.457] DEBUG ?   - {conn-10002, pstmt-20008} Types : []
```

**Comment by webweaver1225** [comment]
> hi, 请问，druid pool 是否支持 log4j2 Asynchronous Loggers？如果支持的话是否需要做什么特别的配置？我按照 log4j2 官方的推荐添加了系统属性，全局启用了异步特性：
> 
> `System.setProperty("log4j2.contextSelector", "org.apache.logging.log4j.core.async.AsyncLoggerContextSelector");`
> 
> 启动 SpringBoot 后，发现 druid 打印出来的日志，找不到打印日志的类，显示 ？号，如下：
> 
> ```
> [18:56:26.457] DEBUG ?   - {conn-10002, pstmt-20008} Parameters : []
> [18:56:26.457] DEBUG ?   - {conn-10002, pstmt-20008} Types : []
> ```

异步日志为了性能 默认是不打印的，你可以通过includeLocation参数开启

**Comment by lizongbo** [comment]
druid不依赖具体的log组件，自己配置即可。我们在项目中都正常使用。
