### ISSUE TITLE
连接似乎未释放,无法获取连接

### ISSUE THREAD

**Issue by tuwq** [alibaba/druid#3720]
配置:
spring.druid.filters=stat
spring.druid.initialSize=1
spring.druid.testWhileIdle=true
spring.druid.testOnBorrow=false
spring.druid.testOnReturn=false
spring.druid.poolPreparedStatements=true
spring.druid.maxOpenPreparedStatements=20
spring.druid.timeBetweenLogStatsMillis=300000

spring.druid.maxActive=600
spring.druid.minIdle=1
spring.druid.maxWait=6000
spring.druid.validationQuery=select 1 from dual
spring.druid.timeBetweenEvictionRunsMillis=60000
spring.druid.minEvictableIdleTimeMillis=300000
        
spring.druid.removeAbandoned=false
#超时时间；单位为秒。180秒=3分钟
spring.druid.removeAbandonedTimeout=1800
#关闭abanded连接时输出错误日志
spring.druid.logAbandoned=true 

错误信息:
Caused by: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 6000, active 14, maxActive 600, creating 1, createElapseMillis 4162
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 6017, active 14, maxActive 600, creating 1, createElapseMillis 4180
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by tuwq** [comment]
![QQ截图20200310115159](https://user-images.githubusercontent.com/33643926/76278217-0713b480-62c6-11ea-88e4-07e1268c0ba1.png)

**Comment by tuwq** [comment]
![QQ截图20200310115754](https://user-images.githubusercontent.com/33643926/76278339-670a5b00-62c6-11ea-838e-4d54a49c6a39.png)
![QQ截图20200310120418](https://user-images.githubusercontent.com/33643926/76278729-48f12a80-62c7-11ea-84c2-118fe716d1c6.png)
![QQ截图20200310120929](https://user-images.githubusercontent.com/33643926/76278989-02e89680-62c8-11ea-84cd-8a0761f830b8.png)

java.sql.SQLNonTransientConnectionException: Data source rejected establishment of connection,  message from server: "Too many connections"

**Comment by tuwq** [comment]
![QQ截图20200310121810](https://user-images.githubusercontent.com/33643926/76279337-3a0b7780-62c9-11ea-81b2-b8a15da44adc.png)
代码中没有手动获取过connection,所以不存在业务逻辑未关闭connection

**Comment by wsbhacker** [comment]
你好,问题解决了吗

**Comment by tuwq** [comment]
我换hikari没问题了
# hikari
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
# 连接池名字
spring.datasource.hikari.pool-name=DatebookHikariCP
# 自动提交
spring.datasource.hikari.auto-commit=true
# 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
spring.datasource.hikari.connection-timeout=20000
# 最小连接数
spring.datasource.hikari.minimum-idle=5
# 最大连接数
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=31000
spring.datasource.hikari.connection-test-query=SELECT 1

**Comment by tuwq** [comment]
> 你好,问题解决了吗

我换hikari后没问题了,druid找不到原因
