### ISSUE TITLE
spring boot集成直接404

### ISSUE THREAD

**Issue by objectboy2016** [alibaba/druid#3722]
springboot版本2.2.5.RELEASE
mysql版本 8.0.19
durid在1.1.10版本之后/druid/sql.html页面全部都是404 ,

**Comment by Zlatanlong** [comment]
配置
**druid.stat-view-serlvet.enabled: true**
可能默认是false了

**Comment by objectboy2016** [comment]
> 配置
> **druid.stat-view-serlvet.enabled: true**
> 可能默认是false了

试过了 不行, 不知道哪里还需要配置
