### ISSUE TITLE
【跪求】springsecurity5+springboot+druid1.1.22集成后druid/login.html空白

### ISSUE THREAD

**Issue by arraycto** [alibaba/druid#3771]
![image](https://user-images.githubusercontent.com/37463247/78889630-9c0cf780-7a96-11ea-8c56-70263781bc9c.png)
springsecurity5+springboot+druid1.1.22集成后druid/login.html空白

http://127.0.0.1:7101/druid/sql.html访问跳转到：http://127.0.0.1:7101/druid/slogin.html，该页面是空白，已经做了springsecurity5的config过滤，搞了一天啊。求大神指点

**Comment by ekoz** [comment]
@arraycto 用排除法试试，springboot + druid 的干净工程能否正常显示 login.html ，如果能，那么你自己就要分析下是否是 spring security 影响了

**Comment by arraycto** [comment]
感谢感谢
