### ISSUE TITLE
执行SQLUtils.parseStatements后，SQL中的()被移出了

### ISSUE THREAD

**Issue by qabin** [alibaba/druid#3775]
原始SQL：SELECT ((700055789 % (64*4))%64); 
执行SQLUtils.parseStatements后，获取到的SQL变成了：SELECT 700055789 % 64 * 4 % 64;
请教一下这个问题怎么解决？

**Comment by WennaDu** [comment]
遇到同样的问题，where 条件用有（） 被 去掉了，sql 解析有问题

**Comment by yl-zhang** [comment]
druid版本不能太高  我之前用的1.2.16有问题  降到1.2.8就不会丢失括号了。
