### ISSUE TITLE
在超级高并发情况下.德鲁伊在takeLast时候会死锁,进而引发应用线程堆积

### ISSUE THREAD

**Issue by Forest10** [alibaba/druid#3797]
重现步骤:

1.使用最简单的db url.不要设置任何额外参数(尤其是socketTimeOut)
类似 jdbc:mysql://localhost:3306/db  jdbc:sqlserver://127.0.0.1:3307;DatabaseName=db

2.不要设置任何参数包括但不限于testOnReturn 和 onBorrow 以及MaxWait以及TestWhileIdle,保持db url的纯粹性

![image](https://user-images.githubusercontent.com/20788885/81501326-6152e500-930a-11ea-8cef-9a9d5dd90f63.png)
maxActive在超级高并发的时候设置1000和1实际是一样的 .我设置1是为了及时复现

3.锁住一张表abc(SELECT * FROM abc WITH(TABLOCKX);). 写一个service,逻辑是,发出一个针对这张表abc的简单查询SQL(SELECT * FROM abc),接下来马上跟着一个查询未锁表的SQL(def表---SELECT * FROM def).触发此service逻辑.此时 abc SQL会hang住(因为此时的abc表已经被表锁锁住了).然后去数据库查询processList直接杀掉应用发出的abc sql.(手动查杀SQL是为了模拟大部分公司的慢查询SQL的job发出的行为). 这时候针对def的查询逻辑会直接报错.(org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: SQL Server did not return a response. The connection has been closed.)这个错误是意料之中的.很OK

4.再次请求. 此次请求hang住, tomcat线程不释放.等到200时候.game over

结论:

一般大部分公司都有外界的慢查询查杀job来强行杀死各种应用发出的SQL. 所以可以利用超级高并发(为了耗尽应用的DS con,还得在最后一个con的时候请求到一个耗时非常长的SQL)触发其公司内部的job,然后损坏他们的ds.等到应用请求下一个正常用户请求时候引发大规模应用线程hang死.最后应用不能处理正常用户请求.

**conf:**

**sqlServer version:**
Microsoft SQL Server 2008 R2 (RTM) - 10.50.1600.1 (X64) 

**sqlServer driver version:**
6.2.2.jre8

**Java version:**
1.8.0_144

**druid version:**
1.1.22和1.1.11.理论上1.1.22以前版本应该都有这个问题.

**Comment by Forest10** [comment]
takeLast()中的 notEmpty.await()// signal by recycle or creator; 会一直hang住.猜测是慢SQL查杀job主动杀死SQL未正确出发recycle操作.造成maxActiveCount未能正确进行++或--

**Comment by Forest10** [comment]
上述测试所用的abc和def表数据都超级少.不会引发OOM

**Comment by wenshao** [comment]
什么版本？

**Comment by Forest10** [comment]
> 什么版本？

现在测试了1.1.22和1.1.11.理论上1.1.22以前版本应该都有这个问题.
我这个属于超级极端测试了. 只要在下一个正常请求到来时候. ds pool里面有多于一个conn的时候.这个请求就OK.然后配合testWhileIdle.也能把那个坏掉的con及时清除出去.

**Comment by Forest10** [comment]
1.版本1.1.22和1.1.11
2.本地Mac Pro. 在我本地笔记本使用上述方式实现了定向爆破应用的测试.还未进行服务器级别测试.
