### ISSUE TITLE
XA mysql-connector-java-8+支持

### ISSUE THREAD

**Issue by lion000** [alibaba/druid#3810]
啥也不说了 直接上代码
![image](https://user-images.githubusercontent.com/16664111/82517843-981dcc00-9b50-11ea-876e-3be14fe324ab.png)

最新的1.1.22里面对mysql的驱动可能在编写的时候有时间差吧，getBooleanReadableProperty这个方法只有8.0.11才有，8.0.12之后貌似就被删除了
![image](https://user-images.githubusercontent.com/16664111/82517940-cf8c7880-9b50-11ea-8281-130e3e6ee2a1.png)
![image](https://user-images.githubusercontent.com/16664111/82517955-d4512c80-9b50-11ea-9bbb-0d046539485a.png)
希望尽快支持跟进一下

**Comment by chenrenfei** [comment]
刚要报这个问题，有人也报了！

**Comment by biticcf** [comment]
在1.1.23同样遇到这个问题，导致mysql-connector-j只能使用8.0.11，无法更新。希望尽快支持跟进一下。
