### ISSUE TITLE
druid可以修改sql的查询字段和条件吗

### ISSUE THREAD

**Issue by chenpengGH** [alibaba/druid#3812]
比如原sql是 "select a.user_id, a.user_name from table_a a where 1=1 and a.filter_Id='111' and a.filter_type='0'" 修改为 "select  a.user_name from table_a a where 1=1 and a.filter_Id='111'" 。
可以去掉某个查询字段和条件

**Comment by poorguy-tech** [comment]
I don't  know if druid can do this, but you can. If you are using Mybatis, you can add a interceptor to get the sql statement to run. Modify this sql with some sql parser framework (like jsqlparser). Then you will get the new sql. 

For example, PageHelper use this technique to  page

**Comment by KANLON** [comment]
可以的，你要自己不过你要自己解析出`SQLSelectQueryBlock`，然后想下面的代码这样替换，应该条件的替换或去除也有类似这样的方法。你可以解析出原来的查询项，然后去掉你不要的重新设置查询项

```java
            SQLSelectQuery tempSelectQuery = (((SQLSelectStatement) parseStatements("select " + express + " as " + alias + " from temp1", JdbcConstants.MYSQL).iterator().next()).getSelect()).getQuery();
            SQLSelectQueryBlock tempDistinctColumnQuery = (SQLSelectQueryBlock) tempSelectQuery;
            SQLSelectItem distinctSelectItem = tempDistinctColumnQuery.getSelectList().iterator().next();
            sqlSelectQueryBlock.getSelectList().clear();
            sqlSelectQueryBlock.getSelectList().add(distinctSelectItem);

```

**Comment by lmikoto** [comment]
有没有visitor的例子可以参考。上述直接解析的话会有很多嵌套sql的场景考虑不到

**Comment by zemochen** [comment]
https://github.com/alibaba/druid/wiki/Druid_SQL_AST

**Comment by lizongbo** [comment]
j解析sql然后修改SQLSelectStatement，再生成新sql即可
