### ISSUE TITLE
SQLUtils.format 格式化sql语句时（）括号 消失 

### ISSUE THREAD

**Issue by WennaDu** [alibaba/druid#3816]
SQLUtils.format 格式化sql语句时（）括号 消失 ，当括号内大于两个条件时，解析后括号没有了 。

解析前语句 ：
select * from test
where role = 'User'
and (username = 'aaa' or name = 'bbb' or role = 'Admin')

格式化后语句：
select * from test
where role = 'User'
and  username = 'aaa' or name = 'bbb' or role = 'Admin'

但是如果 括号中只有两个条件，则可以正常解析 ：
解析前语句 ：
select * from test
where role = 'User'
and (username = 'aaa' or name = 'bbb')

格式化后语句：
select * from test
where role = 'User'
and  （username = 'aaa' or name = 'bbb' ）

**Comment by spafka** [comment]
so am i

**Comment by lizongbo** [comment]
最新代码已经支持，等1.2.23版本验证
