### ISSUE TITLE
空闲连接间隔检测实现存在bug

### ISSUE THREAD

**Issue by waylink** [alibaba/druid#3847]
经分析druid1.1.10源码，确认druid的query test存在bug；

druid的空闲连接检测时间即lastIdleTime，是在获取connection对象时刷新。当connection对象仅仅被get，未发起任何实际query时，仅connection对象的lastIdleTime会被更新，但此连接在数据库server的lastIdleTime并未更新。

当一个connection对象被不停的get、release时，conection的lastIdleTime被不停的刷新，无法触发query test动作。此时连接可能已不可用，但无法正确test。

**Comment by lizongbo** [comment]
请使用最新版验证
