### ISSUE TITLE
添加监控是否对服务内存有消耗，长时间未重启是否导致服务压力过大？

### ISSUE THREAD

**Issue by huazi009** [alibaba/druid#3851]
![微信截图_20200628102518](https://user-images.githubusercontent.com/23333160/85936072-b46c1000-b929-11ea-92b8-8a5a299e4002.png)

**Comment by lizongbo** [comment]
默认的监控模式没有merge sql，会存最近1000条sql，内存消耗是很大，请开启merge特性或者将上限1000调小。
可同时进行。
