### ISSUE TITLE
druid-spring-boot-starter 1.1.23  discard long time none received connection

### ISSUE THREAD

**Issue by micheal0792** [alibaba/druid#3873]
When I use druid-spring-boot-starter and version is 1.1.23  in my project ,there are some errors in my log file as below:

> 2020-07-20 09:01:18.859 [http-nio-0.0.0.0-8081-exec-5] ERROR c.a.d.pool.DruidAbstractDataSource- discard long time none received connection. , jdbcUrl : jdbc:mysql://xxxxxx.mysql.zhangbei.rds.aliyuncs.com:3306/xxxx_prd?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8, jdbcUrl : jdbc:mysql://rxxxx.mysql.zhangbei.rds.aliyuncs.com:3306/xxxx_prd?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8, lastPacketReceivedIdleMillis : 369797

,but if I change the starter version to 1.1.22, this error dispear.some one can help me?

**Comment by CSNight** [comment]
> When I use druid-spring-boot-starter and version is 1.1.23 in my project ,there are some errors in my log file as below:
> 
> > 2020-07-20 09:01:18.859 [http-nio-0.0.0.0-8081-exec-5] ERROR c.a.d.pool.DruidAbstractDataSource- discard long time none received connection. , jdbcUrl : jdbc:mysql://xxxxxx.mysql.zhangbei.rds.aliyuncs.com:3306/xxxx_prd?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8, jdbcUrl : jdbc:mysql://rxxxx.mysql.zhangbei.rds.aliyuncs.com:3306/xxxx_prd?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8, lastPacketReceivedIdleMillis : 369797
> 
> ,but if I change the starter version to 1.1.22, this error dispear.some one can help me?

I have the same problem too!

**Comment by micheal0792** [comment]
> > When I use druid-spring-boot-starter and version is 1.1.23 in my project ,there are some errors in my log file as below:
> > > 2020-07-20 09:01:18.859 [http-nio-0.0.0.0-8081-exec-5] ERROR c.a.d.pool.DruidAbstractDataSource- discard long time none received connection. , jdbcUrl : jdbc:mysql://xxxxxx.mysql.zhangbei.rds.aliyuncs.com:3306/xxxx_prd?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8, jdbcUrl : jdbc:mysql://rxxxx.mysql.zhangbei.rds.aliyuncs.com:3306/xxxx_prd?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8, lastPacketReceivedIdleMillis : 369797
> > 
> > 
> > ,but if I change the starter version to 1.1.22, this error dispear.some one can help me?
> 
> I have the same problem too!

have you resolved this problem yet? I have changed it to the old version in my product env.

**Comment by CSNight** [comment]
@micheal0792  No! I just go back and use the old version. I think there may some side effect in recent commit of  version 1.1.23, but i don't find a solution yet

**Comment by micheal0792** [comment]
someone else meet this issue？just us two？ my god...

**Comment by droid-Q** [comment]
I have the same problem too!

**Comment by 1120247833** [comment]
`spring.datasource.druid.test-while-idle: false`

I set this and it work

**Comment by droid-Q** [comment]
Or set time-between-eviction-runs-millis = min-evictable-idle-time-millis ,it work

**Comment by janecms** [comment]
> someone else meet this issue？just us two？ my god...

me to! recently  upgrade to spring cloud 2.

**Comment by mostcool** [comment]
I have the same problem too!

**Comment by fosin** [comment]
me too

**Comment by LayJustDoIt** [comment]
me too.  i also use this version.

**Comment by 1725636955** [comment]
![image](https://user-images.githubusercontent.com/43667484/88754830-4d44b400-d192-11ea-9b2b-bb6a178bda75.png)
当前时间戳 减去 获取最后一个数据包的接收时间Ms大于timeBetweenEvictionRunsMillis属性时，就会报错，但是不知道为何老版本不报错 @wenshao

**Comment by chenweibo** [comment]
一样这个问题 如果解决了 @我   发现会提示连接  discard long time none received connection.

**Comment by xulingfeng931027** [comment]
我也碰到了,先回退版本解决吧

**Comment by itfsw** [comment]
我也遇到同样问题，回退版本正常

**Comment by 1725636955** [comment]
同上，网络是没有问题的情况下升级版本出现这个问题

**Comment by xudc0521** [comment]
I have the same problem too.

**Comment by fu1744** [comment]
mark

**Comment by etaqi** [comment]
I have the same problem too.

**Comment by lizhuangs** [comment]
+1

**Comment by zhangyongbo** [comment]
+1

**Comment by CoolProgramme** [comment]
+2

**Comment by cliod** [comment]
+3

**Comment by skyjilygao** [comment]
+4

**Comment by abadfox233** [comment]
+5

**Comment by lqmxiaogang** [comment]
I have the same problem too.

**Comment by wys18** [comment]
any body solved this?

**Comment by flyinke** [comment]
+= 1

**Comment by asi6611622** [comment]
+6

**Comment by MickeyWZC** [comment]
### 只是打印这个异常，但是对程序没有影响
看了源码，调试了一下，我的是Mysql。看下来Druid源码大概意思是获取连接的时候会判断该连接是否空闲时间超过配置的时间（默认60秒），如果有超过，再去验证连接是否可用，验证是否可用的时候会调用MySqlUtils.getLastPacketReceivedTimeMs（conn）获取一个上次活跃时间，1.1.23有更新这个方法的实现，1.1.22调用结果是-1。所以1.1.22没有错误日志，1.1.23有错误日志，但是因为获取连接是循环，会一直获取到一个可用的连接。所以只是打印这个异常，但是对程序没有影响。

**Comment by wangbin117241030** [comment]
+1

**Comment by micheal0792** [comment]
> ### 只是打印这个异常，但是对程序没有影响, JDBC为mysql-connector-java 8.x
> ##看了源码，调试了一下。看下来Druid源码大概意思是获取连接的时候会判断该连接的空闲时间是否超过配置的时间（默认60秒），如果有超过，再去验证连接是否可用，验证是否可用的时候会调用MySqlUtils.getLastPacketReceivedTimeMs（conn）获取一个上次活跃时间，1.1.23有更新这个方法的实现，1.1.22调用结果因为找不到实现类所以返回-1。更新请看 #3829 。
> 所以1.1.22没有错误日志，1.1.23有错误日志，但是因为获取连接是循环，会一直获取到一个可用的连接。所以只是打印这个异常，但是对程序没有影响。
> 
> 简单来说就是超过60秒空闲则丢弃连接顺带打印异常日志，给你个新链接，对程序应该是没影响的。
> 
> 回退到1.1.22或者在启动的时候加上参数-Ddruid.mysql.usePingMethod=false 这样会在验证空闲连接时选择SQL `select 1` 而不是ping的方式, 也就刷新了上次查询的时间，也不会出现这个异常日志了

thanks a lot

**Comment by nodejh** [comment]
Druid 默认每 60s 运行一次空闲连接回收器，所以超过 60s 没有使用的连接会被释放，并打印 WARN 日志 `discard long time none received connection` 。 出现这个警告可能是业务中执行 SQL 操作的间隔时间比较长。

解决办法是，将连接空闲时间 timeBetweenEvictionRunsMillis 设置大一些，比如设置为 5 分钟：

```
 spring.datasource.druid.time-between-eviction-runs-millis=300000
```

**Comment by zero1995zyq** [comment]
> Druid 默认每 60s 运行一次空闲连接回收器，所以超过 60s 没有使用的连接会被释放，并打印 WARN 日志 `discard long time none received connection` 。 出现这个警告可能是业务中执行 SQL 操作的间隔时间比较长。
> 
> 解决办法是，将连接空闲时间 timeBetweenEvictionRunsMillis 设置大一些，比如设置为 5 分钟：
> 
> ```
>  spring.datasource.druid.time-between-eviction-runs-millis=300000
> ```

**Comment by zero1995zyq** [comment]
> Druid 默认每 60s 运行一次空闲连接回收器，所以超过 60s 没有使用的连接会被释放，并打印 WARN 日志 `discard long time none received connection` 。 出现这个警告可能是业务中执行 SQL 操作的间隔时间比较长。
> 
> 解决办法是，将连接空闲时间 timeBetweenEvictionRunsMillis 设置大一些，比如设置为 5 分钟：
> 
> ```
>  spring.datasource.druid.time-between-eviction-runs-millis=300000
> ```

it's bad

**Comment by ahgaoyong** [comment]
升级到1.2.9好像就没有了
