### ISSUE TITLE
在每隔一段时间之后获取数据库连接会耗时2-3秒

### ISSUE THREAD

**Issue by Hey-stone** [alibaba/druid#3896]
![image](https://user-images.githubusercontent.com/10703836/89368454-2cd6a580-d70e-11ea-9eac-f80ecd88e81f.png)
![image](https://user-images.githubusercontent.com/10703836/89368498-44ae2980-d70e-11ea-9bbf-f76f216091e9.png)

**Comment by Hey-stone** [comment]
跟驱动有关吗？我用的driverClassName: com.mysql.cj.jdbc.Driver
改成driverClassName: com.mysql.jdbc.Driver 之后好像没有复现了。

**Comment by Hey-stone** [comment]
mysql版本低于6.0

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.1
问题已修复，请用新版本
