### ISSUE TITLE
因为配置了WebMvcConfigurationSupport监控页面登录的时候获取username和password为null

### ISSUE THREAD

**Issue by 1725636955** [alibaba/druid#3906]
配置了以下代码后登录监控页面获取参数为null
@Configuration
public class WebConfigurer extends WebMvcConfigurationSupport {

    /**
     * reources that do not pass the interceptor
     * 设置全局变量
     *
     * @param registry
     */
    @Override
    protected void addResourceHandlers(ResourceHandlerRegistry registry) {
        // 静态文件
        registry.addResourceHandler("/static/**").addResourceLocations("classpath:/static/");
        // swagger2页面
        registry.addResourceHandler("/swagger-ui.html").addResourceLocations("classpath:/META-INF/resources/");
        registry.addResourceHandler("/webjars/**").addResourceLocations("classpath:/META-INF/resources/webjars/");
        super.addResourceHandlers(registry);
    }

}
![image](https://user-images.githubusercontent.com/43667484/90115477-bf1e1f80-dd86-11ea-95bf-a40fc93bf9ca.png)

请求为：
![image](https://user-images.githubusercontent.com/43667484/90115532-ce04d200-dd86-11ea-979a-10fe9ecb84e3.png)

建议将登录参数修改为json形式，放入body体内。

**Comment by 1725636955** [comment]
删除配置类WebMvcConfigurationSupport一切正常

**Comment by 1205747671** [comment]
我没有配置也是null 奇怪

**Comment by 1725636955** [comment]
> 我没有配置也是null 奇怪

后来发现原因在filter，将HttpServletrRquest替换的原因，

**Comment by 1205747671** [comment]
> > 我没有配置也是null 奇怪
> 
> 后来发现原因在filter，将HttpServletrRquest替换的原因，

找到原因了，是引了一个自定义的filter，重写了HttpServletRequest导致getParameter获取的值是null。
