### ISSUE TITLE
空闲连接检测已经打开，为什么还是出错呢？

### ISSUE THREAD

**Issue by jackding79** [alibaba/druid#3916]
![image](https://user-images.githubusercontent.com/55568065/91148461-41de9d00-e6ec-11ea-833c-9181fd78399a.png)
![image](https://user-images.githubusercontent.com/55568065/91148505-558a0380-e6ec-11ea-8dbe-a9d891820c11.png)
配置文件是我们平台包装了一层。
有大佬知道问题吗。生产出现好几次了。

**Comment by Zakariy2019** [comment]
以前用1.1.4没这个问题，自从换了新的版本，就有这个问题了，你可以试试

**Comment by jackding79** [comment]
@Zakariy2019 1.1.4我快吐了，有的项目地生产环境用的用的这个版本，最近一直出现connection holder is null的问题。已经让关闭removeAbond了，程序中也没排查出多个线程绑定一个connection的情况，郁闷。

**Comment by Zakariy2019** [comment]
我的生产环境还有内存高占用问题，也没法解决，一直以为是代码问题，专门写了很简单的功能去测试，内存依然高涨不下；现在慢慢切换到别的连接池了

**Comment by lizongbo** [comment]
请使用最新版本验证。
