### ISSUE TITLE
SQLite简单的增删改查报错

### ISSUE THREAD

**Issue by zhaohuihua** [alibaba/druid#3917]
SQLite简单的增删改查报错，版本1.1.23

```
>>DEBUG 23:40:34.127 | main | Executing SQL query:
    SELECT COUNT(*) FROM TEST_USER_CORE_INFO
    WHERE DATA_STATE=1 | SqlBufferJdbcTemplate.queryForObject(SqlBufferJdbcTemplate.java:265)
>>ERROR 23:40:34.129 | main | getFetchDirection error | com.alibaba.druid.pool.DruidPooledPreparedStatement.<init>(DruidPooledPreparedStatement.java:100)
java.sql.SQLException: ResultSet closed
	at org.sqlite.core.CoreResultSet.checkOpen(CoreResultSet.java:76)
	at org.sqlite.jdbc3.JDBC3ResultSet.getFetchDirection(JDBC3ResultSet.java:117)
	at org.sqlite.jdbc3.JDBC3Statement.getFetchDirection(JDBC3Statement.java:319)
	at com.alibaba.druid.filter.FilterChainImpl.statement_getFetchDirection(FilterChainImpl.java:3059)
	at com.alibaba.druid.filter.FilterAdapter.statement_getFetchDirection(FilterAdapter.java:2547)
	at com.alibaba.druid.filter.FilterChainImpl.statement_getFetchDirection(FilterChainImpl.java:3057)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.getFetchDirection(StatementProxyImpl.java:293)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.<init>(DruidPooledPreparedStatement.java:98)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:359)
	at org.springframework.jdbc.core.PreparedStatementCreatorFactory$PreparedStatementCreatorImpl.createPreparedStatement(PreparedStatementCreatorFactory.java:238)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:690)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:717)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:767)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:211)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:219)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:233)
	at SqlBufferJdbcTemplate.queryForObject(SqlBufferJdbcTemplate.java:270)
```

**Comment by guoyi8** [comment]
> SQLite简单的增删改查报错，版本1.1.23
> 
> ```
> >>DEBUG 23:40:34.127 | main | Executing SQL query:
>     SELECT COUNT(*) FROM TEST_USER_CORE_INFO
>     WHERE DATA_STATE=1 | SqlBufferJdbcTemplate.queryForObject(SqlBufferJdbcTemplate.java:265)
> >>ERROR 23:40:34.129 | main | getFetchDirection error | com.alibaba.druid.pool.DruidPooledPreparedStatement.<init>(DruidPooledPreparedStatement.java:100)
> java.sql.SQLException: ResultSet closed
> 	at org.sqlite.core.CoreResultSet.checkOpen(CoreResultSet.java:76)
> 	at org.sqlite.jdbc3.JDBC3ResultSet.getFetchDirection(JDBC3ResultSet.java:117)
> 	at org.sqlite.jdbc3.JDBC3Statement.getFetchDirection(JDBC3Statement.java:319)
> 	at com.alibaba.druid.filter.FilterChainImpl.statement_getFetchDirection(FilterChainImpl.java:3059)
> 	at com.alibaba.druid.filter.FilterAdapter.statement_getFetchDirection(FilterAdapter.java:2547)
> 	at com.alibaba.druid.filter.FilterChainImpl.statement_getFetchDirection(FilterChainImpl.java:3057)
> 	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.getFetchDirection(StatementProxyImpl.java:293)
> 	at com.alibaba.druid.pool.DruidPooledPreparedStatement.<init>(DruidPooledPreparedStatement.java:98)
> 	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:359)
> 	at org.springframework.jdbc.core.PreparedStatementCreatorFactory$PreparedStatementCreatorImpl.createPreparedStatement(PreparedStatementCreatorFactory.java:238)
> 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
> 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:690)
> 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:717)
> 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:767)
> 	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:211)
> 	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:219)
> 	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:233)
> 	at SqlBufferJdbcTemplate.queryForObject(SqlBufferJdbcTemplate.java:270)
> ```

请问解决了么，我也遇到类似问题

**Comment by guoyi8** [comment]
> > SQLite简单的增删改查报错，版本1.1.23
> > ```
> > >>DEBUG 23:40:34.127 | main | Executing SQL query:
> >     SELECT COUNT(*) FROM TEST_USER_CORE_INFO
> >     WHERE DATA_STATE=1 | SqlBufferJdbcTemplate.queryForObject(SqlBufferJdbcTemplate.java:265)
> > >>ERROR 23:40:34.129 | main | getFetchDirection error | com.alibaba.druid.pool.DruidPooledPreparedStatement.<init>(DruidPooledPreparedStatement.java:100)
> > java.sql.SQLException: ResultSet closed
> > 	at org.sqlite.core.CoreResultSet.checkOpen(CoreResultSet.java:76)
> > 	at org.sqlite.jdbc3.JDBC3ResultSet.getFetchDirection(JDBC3ResultSet.java:117)
> > 	at org.sqlite.jdbc3.JDBC3Statement.getFetchDirection(JDBC3Statement.java:319)
> > 	at com.alibaba.druid.filter.FilterChainImpl.statement_getFetchDirection(FilterChainImpl.java:3059)
> > 	at com.alibaba.druid.filter.FilterAdapter.statement_getFetchDirection(FilterAdapter.java:2547)
> > 	at com.alibaba.druid.filter.FilterChainImpl.statement_getFetchDirection(FilterChainImpl.java:3057)
> > 	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.getFetchDirection(StatementProxyImpl.java:293)
> > 	at com.alibaba.druid.pool.DruidPooledPreparedStatement.<init>(DruidPooledPreparedStatement.java:98)
> > 	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:359)
> > 	at org.springframework.jdbc.core.PreparedStatementCreatorFactory$PreparedStatementCreatorImpl.createPreparedStatement(PreparedStatementCreatorFactory.java:238)
> > 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
> > 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:690)
> > 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:717)
> > 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:767)
> > 	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:211)
> > 	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:219)
> > 	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:233)
> > 	at SqlBufferJdbcTemplate.queryForObject(SqlBufferJdbcTemplate.java:270)
> > ```
> 
> 请问解决了么，我也遇到类似问题

把dataSource的属性poolPreparedStatements设置成false，就可以了。如果设置了maxPoolPreparedStatementPerConnectionSize，最好同步设置-1关闭，或者直接不给
