### ISSUE TITLE
maxActive和配置文件的不对应,每过30秒会报错

### ISSUE THREAD

**Issue by AttackingCat** [alibaba/druid#3918]
# 我们用zookeeper注册了两个后台链接数据库的节点,一台服务器是好的,但是另一台服务器每隔30s会报50次错.报错内容如下:
Caused by: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, active 50, maxActive 50, creating 0,
.........
# 使用web页面进行监控,查看数据源跟我们配置文件的是一样的,先后用springboot的方式和tomcat的方式启动,都会有这个错误,数据库连接归还都是自动归还,druid版本1.1.10

# 配置文件如下
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.druid.initial-size=5
spring.datasource.druid.min-idle=5
spring.datasource.druid.maxActive=25
spring.datasource.druid.maxWait=60000
spring.datasource.druid.timeBetweenEvictionRunsMillis=60000
spring.datasource.druid.minEvictableIdleTimeMillis=90000
spring.datasource.druid.keep-alive=true
spring.datasource.druid.remove-abandoned-timeout=90
spring.datasource.druid.remove-abandoned=true
spring.datasource.druid.log-abandoned=true
spring.datasource.druid.validationQuery=SELECT 1 FROM DUAL
spring.datasource.druid.testWhileIdle=true
spring.datasource.druid.testOnBorrow=false
spring.datasource.druid.testOnReturn=false
spring.datasource.druid.poolPreparedStatements=true
spring.datasource.druid.maxPoolPreparedStatementPerConnectionSize=100
spring.datasource.druid.filter.stat.merge-sql=false
spring.datasource.druid.web-stat-filter.enabled=true
spring.datasource.druid.web-stat-filter.url-pattern=/*
spring.datasource.druid.web-stat-filter.exclusions=*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
spring.datasource.druid.stat-view-servlet.url-pattern=/druid/*
spring.datasource.druid.stat-view-servlet.allow=
spring.datasource.druid.stat-view-servlet.deny=
spring.datasource.druid.stat-view-servlet.reset-enable=true
spring.datasource.druid.stat-view-servlet.login-username=admin
spring.datasource.druid.stat-view-servlet.login-password=123456
spring.datasource.druid.filter.wall.config.strict-syntax-check=false

**Comment by AttackingCat** [comment]
期待您的开发团队能帮我们解决这个问题

**Comment by diaodiaofly** [comment]
> 期待您的开发团队能帮我们解决这个问题

建议你尝试1.1.23版本  是否存在该问题，如果存在 错误日志贴个附件看看

**Comment by AttackingCat** [comment]
> > 期待您的开发团队能帮我们解决这个问题
> 
> 建议你尝试1.1.23版本 是否存在该问题，如果存在 错误日志贴个附件看看

感谢
![image](https://user-images.githubusercontent.com/49849912/92489934-edc2d500-f222-11ea-8b96-138556b9e563.png)

**Comment by AttackingCat** [comment]
> > 期待您的开发团队能帮我们解决这个问题
> 
> 建议你尝试1.1.23版本 是否存在该问题，如果存在 错误日志贴个附件看看

感谢您的回复,我们的开发组在尝试其他方式以后选择了更换服务器,现在已经不再出现这个错误了,如果后续再次出现该问题,我们会尝试您的建议的

**Comment by Qianlu5110** [comment]
1.1.23版本，在连接池有什么特殊优化吗？
