### ISSUE TITLE
druid1.1.24版本：discard long time none received connection

### ISSUE THREAD

**Issue by diaodiaofly** [alibaba/druid#3954]
使用最新版，程序刚启动第一次jdbc会出现该异常，该异常在上一个版本也存在1.1.23

**Comment by wenshao** [comment]
可以提供异常堆栈信息么？

**Comment by 1725636955** [comment]
> 可以提供异常异常信息么？

您请看：[#3908 ] 这个问题从1.1.23开始出现的，

**Comment by 1725636955** [comment]
> 使用最新版，程序刚启动第一次jdbc会出现该异常，该异常在上一个版本也存在1.1.23

[#3873 ]你看一下这个的解决方式

**Comment by wenshao** [comment]
这只是一个错误信息，不影响使用，后续会优化掉

**Comment by 1725636955** [comment]
> 这只是一个错误信息，不影响使用，后续会优化掉

麻烦您了

**Comment by zhangran2616** [comment]
> 这只是一个错误信息，不影响使用，后续会优化掉

新发布的1.2.2还是存在这个问题。是后续版本在修复是吗？

**Comment by 1725636955** [comment]
> > 这只是一个错误信息，不影响使用，后续会优化掉
> 
> 新发布的1.2.2还是存在这个问题。是后续版本在修复是吗？

这个估计需要我们找出原因，看看究竟是怎么回事然后反馈了，新版做的修改为将error日志改为了warn日志

**Comment by 1522140840** [comment]
> 这只是一个错误信息，不影响使用，后续会优化掉

大佬 后续优化了吗？？？
