### ISSUE TITLE
create table 语句 table_option解析问题

### ISSUE THREAD

**Issue by ljq132008** [alibaba/druid#3975]
create database user default charset=utf8 collate=utf8_general_ci;
如果collate不加default好像解析有问题，与前面的options一起解析成SQLBinaryOpExpr了
druid-1.1.23版本
https://dev.mysql.com/doc/refman/8.0/en/create-table.html

**Comment by wenshao** [comment]
问题已修复，请用新版本 https://github.com/alibaba/druid/releases/tag/1.2.1

**Comment by ljq132008** [comment]
![image](https://user-images.githubusercontent.com/8446458/95649717-775f0e80-0b11-11eb-9449-8709cf13d916.png)
升级到1.2.1版本解析还是不正确
