### ISSUE TITLE
支持一下 clickhouse的 BalancedClickhouseDataSource

### ISSUE THREAD

**Issue by kiwimg** [alibaba/druid#3984]
支持一下 clickhouse的 BalancedClickhouseDataSource

**Comment by kiwimg** [comment]
这个什么时候能支持呢

**Comment by marvelcaton** [comment]
+1，求支持 clickhouse的 BalancedClickhouseDataSource

**Comment by wenshao** [comment]
没想好怎么支持呢

**Comment by wenshao** [comment]
在1.2.5中配置driverClassName=com.alibaba.druid.support.clickhouse.BalancedClickhouseDriver试试看

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.5
问题已修复，请用新版本

**Comment by kiwimg** [comment]
感谢 支持，大赞，请问怎么配置呢

**Comment by dqccoding** [comment]
> 感谢 支持，大赞，请问怎么配置呢

直接看源码就可以理解了
![image](https://user-images.githubusercontent.com/19896518/118953682-a256ee00-b98f-11eb-8b95-c95055efa90b.png)

**Comment by kiwimg** [comment]
clickhouse jdbc版本升级了，怎么支持一下新版本呢
