### ISSUE TITLE
druid-admin 无法编译运行，部分引用包名错误

### ISSUE THREAD

**Issue by lltx** [alibaba/druid#3992]
https://github.com/alibaba/druid/blob/b236a85bbc3cdccaad615ebaf0a385fa6314f3e8/druid-admin/src/main/java/com/alibaba/druid/admin/service/MonitorStatService.java#L12-L19

emmm

**Comment by wenshao** [comment]
@patience00 看下

**Comment by patience00** [comment]
@lltx 这是之前初始化的时候,包名错了,请使用最新版
