### ISSUE TITLE
无法登录监控页，登陆判断获取的参数是null

### ISSUE THREAD

**Issue by 1205747671** [alibaba/druid#3998]
druid-spring-boot-starter版本：1.1.22
springboot版本：2.2.8.RELEASE

![image](https://user-images.githubusercontent.com/38599758/97078806-4a3a5200-1621-11eb-8d1f-408d4ce6fb3c.png)

![image](https://user-images.githubusercontent.com/38599758/97078809-51f9f680-1621-11eb-8b6b-376b1bb60317.png)

获取的参数是null

**Comment by devlhl** [comment]
druid的会话依赖于cookie，看看你的应用的会话是不是header或者其他方式维护的（关注submitLogin的请求，看response header有没有Set-Cookie:）

**Comment by 1205747671** [comment]
找到原因了，是引了一个自定义的filter，重写了HttpServletRequest导致getParameter获取的值是null。
