### ISSUE TITLE
 syntax error, expect RPAREN, actual COLONCOLON pos 61, line 1, column 60, token COLONCOLON

### ISSUE THREAD

**Issue by cn-wwl** [alibaba/druid#4010]
## SQL语句包含`::`,使用 `PagerUtils` 时,抛出下面的异常

Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual COLONCOLON pos 61, line 1, column 60, token COLONCOLON
	at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:2856)
	at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:1419)
	at com.alibaba.druid.sql.parser.SQLExprParser.dotRest(SQLExprParser.java:1356)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerExprParser.dotRest(SQLServerExprParser.java:131)
	at com.alibaba.druid.sql.parser.SQLExprParser.primaryRest(SQLExprParser.java:1008)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerExprParser.primaryRest(SQLServerExprParser.java:120)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseWhere(SQLSelectParser.java:624)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerSelectParser.query(SQLServerSelectParser.java:172)
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:358)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerSelectParser.select(SQLServerSelectParser.java:57)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseSelect(SQLStatementParser.java:2562)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:248)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:171)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:492)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:487)
	at com.alibaba.druid.sql.PagerUtils.limit(PagerUtils.java:81)
	at com.example.test.utils.AlibabaDruid.main(AlibabaDruid.java:17)

### SQL
```mssql
select * from test where shape.STIntersects(geometry::STGeomFromText('POLYGON ((86610.054 86610.054,112372.95799999963 88785.5940000005,112372.91199999955 88675.996999999508,86610.054 86610.054))',0))=1;
```

**Comment by wenshao** [comment]
能提供重现问题的SQL么？

**Comment by cn-wwl** [comment]
select * from test where shape.STIntersects(geometry::TGeomFromText('POLYGON ((86610.054 86610.054,112372.95799999963 88785.5940000005,112372.91199999955 88675.996999999508,86610.054 86610.054))',0))=1;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/druid"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 中午11:31
收件人:&nbsp;"alibaba/druid"<druid@noreply.github.com&gt;;
抄送:&nbsp;"回归现实"<373624472@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/druid]  syntax error, expect RPAREN, actual COLONCOLON pos 61, line 1, column 60, token COLONCOLON (#4010)





 
能提供重现问题的SQL么？

**Comment by cn-wwl** [comment]
目前的解决方案是 采取替换特殊字符的形式，将`::`替换成`COLONCOLON `,接着使用`PagerUtils.limit()`，生成好分页sql，再将`COLONCOLON `替换成`::`，最后再去执行。

**Comment by wenshao** [comment]
升级到1.2.1版本试试看

**Comment by cn-wwl** [comment]
我这边升级到`1.2.1`版本后，执行依然报错：
```java
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, expect ), actual :: pos 61, line 1, column 60, token ::
	at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:3960)
	at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:1807)
	at com.alibaba.druid.sql.parser.SQLExprParser.dotRest(SQLExprParser.java:1737)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerExprParser.dotRest(SQLServerExprParser.java:127)
	at com.alibaba.druid.sql.parser.SQLExprParser.primaryRest(SQLExprParser.java:1306)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerExprParser.primaryRest(SQLServerExprParser.java:116)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseWhere(SQLSelectParser.java:634)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerSelectParser.query(SQLServerSelectParser.java:163)
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:368)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerSelectParser.select(SQLServerSelectParser.java:48)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseSelect(SQLStatementParser.java:4112)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:204)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:558)
	at com.alibaba.druid.sql.PagerUtils.limit(PagerUtils.java:55)
	at com.example.test.utils.AlibabaDruid.main(AlibabaDruid.java:21)
```

**相关代码：**
```java

public static void main(String[] args) { 
        String sql = PagerUtils.limit(getSql(), DbType.sqlserver,11,20);//deconvert(PagerUtils.limit(convert(getSql()),dbtype,11,20));
        System.out.println(sql); 
 }
public static String getSql()  {
        return "select * from L_FlowPipe  where shape.STIntersects(geometry::STGeomFromText('POLYGON ((86610.054 86610.054,112372.95799999963 88785.5940000005,112372.91199999955 88675.996999999508,86610.054 86610.054))',0))=1 order by createtime desc;";
 }
```

**Comment by c0526** [comment]
怎么解决的

**Comment by xiaoyugong** [comment]
请问这个问题怎么解决的呢 @wenshao @cn-wwl

**Comment by cn-wwl** [comment]
你把问题看完整，就知道了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xiaoyugong"<notifications@github.com&gt;; 
发送时间: 2020年12月25日(星期五) 晚上6:13
收件人: "alibaba/druid"<druid@noreply.github.com&gt;; 
抄送: "回归现实"<373624472@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [alibaba/druid]  syntax error, expect RPAREN, actual COLONCOLON pos 61, line 1, column 60, token COLONCOLON (#4010)





 
请问这个问题怎么解决的呢 @wenshao @cn-wwl

**Comment by xiaoyugong** [comment]
> 你把问题看完整，就知道了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xiaoyugong"<notifications@github.com&gt;; 发送时间: 2020年12月25日(星期五) 晚上6:13 收件人: "alibaba/druid"<druid@noreply.github.com&gt;; 抄送: "回归现实"<373624472@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [alibaba/druid] syntax error, expect RPAREN, actual COLONCOLON pos 61, line 1, column 60, token COLONCOLON (#4010) 请问这个问题怎么解决的呢 @wenshao @cn-wwl — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

没看明白，::替换成COLONCOLON，也不行

**Comment by cn-wwl** [comment]
1.定义好字符集枚举
```java

/**
 * @author wwl
 * @date 2020/10/29 16:11
 * @desc 约定枚举字符定义方式：
 *  在定义枚举字符时，字符长度越短，则越往下放，字符长度越长，则越往上放
 *
 */
public enum DruidEnum {


    COLONCOLON("::"),

    COLON(":"),


    ;

    public final String name;

    DruidEnum(){
        this(null);
    }

    DruidEnum(String name){
        this.name = name;
    }

    public static String getEnumNameForValue(Object value){
        DruidEnum[] values = DruidEnum.values();
        String enumValue = null;
        for(DruidEnum eachValue : values) {
            enumValue = eachValue.toString();

            if (enumValue.equalsIgnoreCase((String) value)) {
                return eachValue.name();
            }
        }
        return enumValue;
    }
}
```
2.定义字符替换帮助类
```java
/**
 * @author wwl
 * @date 2020/10/29 16:12
 * @desc 用于com.alibaba.druid的PageUtils对象，
 *       此对象对特殊字符不能处理，因此通过 DruidEnum 定义特殊字符及其值
 */ 
public class DruidConvertUtil {

    public String encode(String str)
    {
        String result="";
        for (DruidEnum en:DruidEnum.values())
        {
            result=str.replace(en.name,DruidEnum.valueOf(en.toString()).toString());
        }
        return result;
    }

    public String decode(String str)
    {
        String result="";
        for (DruidEnum en:DruidEnum.values())
        {
            result=str.replace(DruidEnum.valueOf(en.toString()).toString(),en.name);
        }
        return result;
    }
}

```

3.使用
```java
public static void main(String[] args) { 
        String sql =DruidConvertUtil.decode(PagerUtils.limit(DruidConvertUtil.encode(getSql()),dbtype,11,20));
        System.out.println(sql); 
 }
public static String getSql()  {
        return "select * from L_FlowPipe  where shape.STIntersects(geometry::STGeomFromText('POLYGON ((86610.054 86610.054,112372.95799999963 88785.5940000005,112372.91199999955 88675.996999999508,86610.054 86610.054))',0))=1 order by createtime desc;";
 }

```

**Comment by cn-wwl** [comment]
已经贴代码了，去看吧






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xiaoyugong"<notifications@github.com&gt;; 
发送时间: 2020年12月25日(星期五) 晚上6:33
收件人: "alibaba/druid"<druid@noreply.github.com&gt;; 
抄送: "回归现实"<373624472@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [alibaba/druid]  syntax error, expect RPAREN, actual COLONCOLON pos 61, line 1, column 60, token COLONCOLON (#4010)





  
你把问题看完整，就知道了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xiaoyugong"<notifications@github.com&gt;; 发送时间: 2020年12月25日(星期五) 晚上6:13 收件人: "alibaba/druid"<druid@noreply.github.com&gt;; 抄送: "回归现实"<373624472@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [alibaba/druid] syntax error, expect RPAREN, actual COLONCOLON pos 61, line 1, column 60, token COLONCOLON (#4010) 请问这个问题怎么解决的呢 @wenshao @cn-wwl — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
  
没看明白，::替换成COLONCOLON，也不行

**Comment by xiaoyugong** [comment]
ok,谢谢分享




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/druid"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月25日(星期五) 晚上6:46
收件人:&nbsp;"alibaba/druid"<druid@noreply.github.com&gt;;
抄送:&nbsp;"擱浅"<270187133@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/druid]  syntax error, expect RPAREN, actual COLONCOLON pos 61, line 1, column 60, token COLONCOLON (#4010)





 已经贴代码了，去看吧 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "xiaoyugong"<notifications@github.com&amp;gt;;  
 发送时间: 2020年12月25日(星期五) 晚上6:33 
 收件人: "alibaba/druid"<druid@noreply.github.com&amp;gt;;  
 抄送: "回归现实"<373624472@qq.com&amp;gt;; "Mention"<mention@noreply.github.com&amp;gt;;  
 主题: Re: [alibaba/druid]  syntax error, expect RPAREN, actual COLONCOLON pos 61, line 1, column 60, token COLONCOLON (#4010) 
 
 
 
 
 
    
 你把问题看完整，就知道了 
  … 
  ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人: "xiaoyugong"<notifications@github.com&amp;gt;; 发送时间: 2020年12月25日(星期五) 晚上6:13 收件人: "alibaba/druid"<druid@noreply.github.com&amp;gt;; 抄送: "回归现实"<373624472@qq.com&amp;gt;; "Mention"<mention@noreply.github.com&amp;gt;; 主题: Re: [alibaba/druid] syntax error, expect RPAREN, actual COLONCOLON pos 61, line 1, column 60, token COLONCOLON (#4010) 请问这个问题怎么解决的呢 @wenshao @cn-wwl — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. 
    
 没看明白，::替换成COLONCOLON，也不行

**Comment by xiaoyugong** [comment]
> 1.定义好字符集枚举
> 
> ```java
> /**
>  * @author wwl
>  * @date 2020/10/29 16:11
>  * @desc 约定枚举字符定义方式：
>  *  在定义枚举字符时，字符长度越短，则越往下放，字符长度越长，则越往上放
>  *
>  */
> public enum DruidEnum {
> 
> 
>     COLONCOLON("::"),
> 
>     COLON(":"),
> 
> 
>     ;
> 
>     public final String name;
> 
>     DruidEnum(){
>         this(null);
>     }
> 
>     DruidEnum(String name){
>         this.name = name;
>     }
> 
>     public static String getEnumNameForValue(Object value){
>         DruidEnum[] values = DruidEnum.values();
>         String enumValue = null;
>         for(DruidEnum eachValue : values) {
>             enumValue = eachValue.toString();
> 
>             if (enumValue.equalsIgnoreCase((String) value)) {
>                 return eachValue.name();
>             }
>         }
>         return enumValue;
>     }
> }
> ```
> 
> 2.定义字符替换帮助类
> 
> ```java
> /**
>  * @author wwl
>  * @date 2020/10/29 16:12
>  * @desc 用于com.alibaba.druid的PageUtils对象，
>  *       此对象对特殊字符不能处理，因此通过 DruidEnum 定义特殊字符及其值
>  */ 
> public class DruidConvertUtil {
> 
>     public String encode(String str)
>     {
>         String result="";
>         for (DruidEnum en:DruidEnum.values())
>         {
>             result=str.replace(en.name,DruidEnum.valueOf(en.toString()).toString());
>         }
>         return result;
>     }
> 
>     public String decode(String str)
>     {
>         String result="";
>         for (DruidEnum en:DruidEnum.values())
>         {
>             result=str.replace(DruidEnum.valueOf(en.toString()).toString(),en.name);
>         }
>         return result;
>     }
> }
> ```
> 
> 3.使用
> 
> ```java
> public static void main(String[] args) { 
>         String sql =DruidConvertUtil.decode(PagerUtils.limit(DruidConvertUtil.encode(getSql()),dbtype,11,20));
>         System.out.println(sql); 
>  }
> public static String getSql()  {
>         return "select * from L_FlowPipe  where shape.STIntersects(geometry::STGeomFromText('POLYGON ((86610.054 86610.054,112372.95799999963 88785.5940000005,112372.91199999955 88675.996999999508,86610.054 86610.054))',0))=1 order by createtime desc;";
>  }
> ```

请问你用的druid是哪个版本，数据库是pg吗？ 我改了还是不行

**Comment by cn-wwl** [comment]
1.druid版本为1.1.23，数据库是sqlserver的2.你先保证原始的sql是正确的，在数据库可执行成功的，
3.目前的解决方案是 采取替换特殊字符的形式，将sql中的::替换成COLONCOLON&nbsp;,接着使用PagerUtils.limit()，生成好分页sql，再将sql中的COLONCOLON&nbsp;替换成::，最后再去执行。
4.如果你要替换的字符不是::,那需要去enum中定义好，才能使用，
5.再去看encode()和decode()做了什么样的事情，






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xiaoyugong"<notifications@github.com&gt;; 
发送时间: 2020年12月25日(星期五) 晚上7:10
收件人: "alibaba/druid"<druid@noreply.github.com&gt;; 
抄送: "回归现实"<373624472@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [alibaba/druid]  syntax error, expect RPAREN, actual COLONCOLON pos 61, line 1, column 60, token COLONCOLON (#4010)





  
1.定义好字符集枚举
 /**  * @author wwl  * @date 2020/10/29 16:11  * @desc 约定枚举字符定义方式：  *  在定义枚举字符时，字符长度越短，则越往下放，字符长度越长，则越往上放  *  */ public enum DruidEnum {     COLONCOLON("::"),     COLON(":"),     ;     public final String name;     DruidEnum(){         this(null);     }     DruidEnum(String name){         this.name = name;     }     public static String getEnumNameForValue(Object value){         DruidEnum[] values = DruidEnum.values();         String enumValue = null;         for(DruidEnum eachValue : values) {             enumValue = eachValue.toString();             if (enumValue.equalsIgnoreCase((String) value)) {                 return eachValue.name();             }         }         return enumValue;     } }
 
2.定义字符替换帮助类
 /**  * @author wwl  * @date 2020/10/29 16:12  * @desc 用于com.alibaba.druid的PageUtils对象，  *       此对象对特殊字符不能处理，因此通过 DruidEnum 定义特殊字符及其值  */  public class DruidConvertUtil {     public String encode(String str)     {         String result="";         for (DruidEnum en:DruidEnum.values())         {             result=str.replace(en.name,DruidEnum.valueOf(en.toString()).toString());         }         return result;     }     public String decode(String str)     {         String result="";         for (DruidEnum en:DruidEnum.values())         {             result=str.replace(DruidEnum.valueOf(en.toString()).toString(),en.name);         }         return result;     } }
 
3.使用
 public static void main(String[] args) {          String sql =DruidConvertUtil.decode(PagerUtils.limit(DruidConvertUtil.encode(getSql()),dbtype,11,20));         System.out.println(sql);   } public static String getSql()  {         return "select * from L_FlowPipe  where shape.STIntersects(geometry::STGeomFromText('POLYGON ((86610.054 86610.054,112372.95799999963 88785.5940000005,112372.91199999955 88675.996999999508,86610.054 86610.054))',0))=1 order by createtime desc;";  }
  
请问你用的druid是哪个版本，数据库是pg吗？ 我改了还是不行
