### ISSUE TITLE
Communications link failure

### ISSUE THREAD

**Issue by pengweizhong** [alibaba/druid#4016]
环境 
druid starter版本 1.1.9
mysql版本 8.0.13
错误堆栈：
`### Error querying database.  Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 2,230,340 milliseconds ago. The last packet sent successfully to the server was 2,230,348 milliseconds ago.
### Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 2,230,340 milliseconds ago. The last packet sent successfully to the server was 2,230,348 milliseconds ago.
; Communications link failure

The last packet successfully received from the server was 2,230,340 milliseconds ago. The last packet sent successfully to the server was 2,230,348 milliseconds ago.; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 2,230,340 milliseconds ago. The last packet sent successfully to the server was 2,230,348 milliseconds ago.`

**Comment by pengweizhong** [comment]
这个是什么原因导致的？看了那么多的issue，并不能解决我的问题，请问如何解决它？

**Comment by pengweizhong** [comment]
没有人维护的open issue，开着也没必要了。

**Comment by garrickjubiao** [comment]
出现这个问题一般两个原因：
第一种，从连接池里拿到的是一个失效链接， 可以通过配置testWhileIdle、validationQuery等参数来检测链接的有效性；
第二种，执行了一条慢SQL或者数据库服务器当前负载过高，导致响应很慢，连接数直接超最大限制，可以通过DB相关监控基础设施查看接口报错时的数据库健康情况；
