### ISSUE TITLE
能支持一下LocalDateTime吗？

### ISSUE THREAD

**Issue by lqzxpp** [alibaba/druid#4023]
我用druid + slf4j + mybatis 进行sql打印。
因为我用的日期属性是LocalDateTime类型，然后sql打印出来的参数是 null，
我跟踪到PreparedStatementProxyImpl类中的private void setObjectParameter(int parameterIndex, Object x)函数，
才发现这里不支持LocalDateTime类型，这样到最后只能调用 
 setParameter(parameterIndex, createParameter(Types.OTHER, null))

所以打印出来的参数就变为 null

希望可以改进支持LocalDateTime，或者提供一个配置接口解决。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.3
问题已修复，请用新版本
