### ISSUE TITLE
多并发环境下多次获取和关闭Connection导致Connection数组内部连接重复

### ISSUE THREAD

**Issue by chenyangcun** [alibaba/druid#4037]
1.开启多个线程同时获取Connection和关闭Connection(10-30个线程）
2.重复多次后，有机率出现Connection数组内部连接重复情况
3.出现问题后DataSource的ActiveCount数也会有异常，连接都断开了，ActiveCount还会有值，重复跑下去ActiveCount都会超过MaxActive, 但createCount和poolingCount值就没有增加。
4.使用的durid版本是1.1.22版本
5.以下是dump下来的connections数组情况
![connections](https://github.com/chenyangcun/temp/blob/main/durid-connection.png?raw=true)

**Comment by BruceZhangXL** [comment]
有查出来原因吗 @chenyangcun

**Comment by tain198127** [comment]
在minEvictableIdleTimeMillis小于keepAliveBetweenTimeMillis时，连接池中可能会保留多个相同的连接，导致获取连接时拿到同一个连接。 可以参考    [https://github.com/alibaba/druid/issues/4316](url)

**Comment by BruceZhangXL** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by chenyangcun** [comment]
应该是这个原因，minEvictableIdleTimeMillis改大后就没有出现了
