### ISSUE TITLE
where条件里，等号（或其他符号）右边如果有cast，则无法解析

### ISSUE THREAD

**Issue by axzhcode** [alibaba/druid#4061]
where条件里，等号（或其他符号）右边如果有cast，则无法解析
比如：
`
select id,name from bi.aaa where stat_date <= cast(current_date as varchar(10))
`
获取条件信息：
`System.out.println(statVisitor.getConditions());`
[bi.aaa.stat_date <= null]

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.4
请用新版本
