### ISSUE TITLE
可以对ConnectionPool 里面的每一个Connection 执行一个命令

### ISSUE THREAD

**Issue by zhihuiFan** [alibaba/druid#4062]
大致的接口类似：
```
connectionPool.forEach( Function (Connection conn)); 
```

这样用户可以在connection pool 初始化以后， 对里面的每一个连接运行一个查询。 
```
void warmup_conn(Connection conn)
{
  conn.queryForList(...); 
}
```

这个功能对我们当前的用户来说是非常有用的。 

另外不清楚当前是否已经存在了这样的接口，实际上我想执行warmup_conn 的时机在于： `connectionPool 已经创建了 initialSize 或者 minIdle 个连接之后,  并且在开始服务业务之前执行的`

比如 
```
connectionPool.initilize();
connectionPool.forEach(...);
```

同时forEach 里面的函数最好能够并行执行 （我们目前的需求是一个query 可能要执行40s,  connection size 会在10 左右， 如果串行执行400s 有点太长了）

**Comment by lizongbo** [comment]
使用connection-init-sqls的机制吧
