### ISSUE TITLE
在并发条件下 大量 连接sleep 提示 Could not open JDBC Connection for transaction

### ISSUE THREAD

**Issue by yihuiyu** [alibaba/druid#4064]
Could not get JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 8000, active 300, maxActive 300, creating 0
用的是druid + mybatis 在并发条件下 数据库报错 查询数据库 300个连接有200多sleep的 但是还是会拿新的连接 不知道 这个应该怎么配置

**Comment by 13127929676** [comment]
扩大一下最大连接数试试呢

**Comment by weixing1204** [comment]
存在连接泄漏的风险，removeAbandoned设置成true试试

**Comment by yihuiyu** [comment]
问题已解决 发现是自己写的队列满了之后再请求就会报上面的错，最后加大了队列
