### ISSUE TITLE
insert all 在1.2.x中出现问题OracleMultiInsertStatement$InsertIntoClause not allow

### ISSUE THREAD

**Issue by 6LWa6ZKx** [alibaba/druid#4065]
具体异常如下:
`Cause: java.sql.SQLException: sql injection violation, dbType oracle, druid-version 1.2.3, class com.alibaba.druid.sql.dialect.oracle.ast.stmt.OracleMultiInsertStatement$InsertIntoClause not allow : INSERT ALL  INTO xxxx`

我使用1.1.x的版本没有任何问题，如果升级到1.2.x就出现这个异常，我尝试配置wall.enabled=true，wall.config.comment-allow:true，问题依然存在。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.4
请用新版本
