### ISSUE TITLE
new SQLSelectStatement().toString();会报NullPointException错误

### ISSUE THREAD

**Issue by lipengjiegithub** [alibaba/druid#4071]
调试变量的时候发现new SQLSelectStatement()得到的变量会报错，虽然本身并不会影响程序的运行，但是会导致调试无法查看变量。
这个创建过程是在创建SQLSelectBuilderImpl的时候创建的，这个时候SQLSelect还没有被创建，所以toString的时候报了Null。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.4
请用新版本
