### ISSUE TITLE
文档有错别字

### ISSUE THREAD

**Issue by fjrmiao** [alibaba/druid#4072]
https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE-wallfilter 里面
“有时候，一些应用框架做了自己的JDBC Proxy Driver，是的DruidDataSource无法正确识别数据库的类型，则需要特别指定，如下：”
这句话中的“是的”应该是“使得”的笔误。

**Comment by lizongbo** [comment]
已经更新
