### ISSUE TITLE
Oracle：SQLUNionQuery中的SYSDATE消失

### ISSUE THREAD

**Issue by schneidyang** [alibaba/druid#4084]
-----unionQuery-----

SELECT COUNT(ID) AS count, '已完成' AS event
FROM EVENT_RECEIVE_ENTITY
WHERE tenant_id = 'ff8080817592c76a017592d380f00081'
	AND account_id = 'ff8080817592c76a017592d380f10082'
	AND (EVENT_STATUS IN ('14', '15')
		AND ACCOUNT_ID = ?
		AND system_id IN (?))
UNION ALL
SELECT COUNT(ID) AS count, '处理中' AS event
FROM EVENT_RECEIVE_ENTITY
WHERE tenant_id = 'ff8080817592c76a017592d380f00081'
	AND account_id = 'ff8080817592c76a017592d380f10082'
	AND (EVENT_STATUS NOT IN ('1', '14', '15', '17')
		AND ACCOUNT_ID = ?
		AND system_id IN (?))
UNION ALL
SELECT COUNT(ID) AS count, '预警故障' AS event
FROM EVENT_RECEIVE_ENTITY
WHERE tenant_id = 'ff8080817592c76a017592d380f00081'
	AND account_id = 'ff8080817592c76a017592d380f10082'
	AND (event_status NOT IN (
			'1', 
			'2', 
			'3', 
			'14', 
			'15', 
			'17'
		)
		AND system_id IN (?)
		AND ACCOUNT_ID = ?
		AND  >= CREATED + 0 + (WARNING_TIME - 5) / 24 / 60)

---
-----left-----

SELECT COUNT(ID) AS count, '已完成' AS event
FROM EVENT_RECEIVE_ENTITY
WHERE tenant_id = 'ff8080817592c76a017592d380f00081'
	AND account_id = 'ff8080817592c76a017592d380f10082'
	AND (EVENT_STATUS IN ('14', '15')
		AND ACCOUNT_ID = ?
		AND system_id IN (?))
UNION ALL
SELECT COUNT(ID) AS count, '处理中' AS event
FROM EVENT_RECEIVE_ENTITY
WHERE tenant_id = 'ff8080817592c76a017592d380f00081'
	AND account_id = 'ff8080817592c76a017592d380f10082'
	AND (EVENT_STATUS NOT IN ('1', '14', '15', '17')
		AND ACCOUNT_ID = ?
		AND system_id IN (?))

---
-----right-----

SELECT COUNT(ID) AS count, '预警故障' AS event
FROM EVENT_RECEIVE_ENTITY
WHERE tenant_id = 'ff8080817592c76a017592d380f00081'
	AND account_id = 'ff8080817592c76a017592d380f10082'
	AND (event_status NOT IN (
			'1', 
			'2', 
			'3', 
			'14', 
			'15', 
			'17'
		)
		AND system_id IN (?)
		AND ACCOUNT_ID = ?
		AND SYSDATE >= CREATED + 0 + (WARNING_TIME - 5) / 24 / 60)

---
为什么在unionQuery.toString()后，right中最后一个过滤条件中的SYSDATE消失了？

**Comment by wenshao** [comment]
怎么用的？

**Comment by schneidyang** [comment]
```
SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, TenantProperties.getInstance().getDbType());

        SQLStatement statement = parser.parseStatement();

        if (statement instanceof SQLSelectStatement) {
            SQLSelect sqlSelect = ((SQLSelectStatement) statement).getSelect();
            if (sqlSelect.getQuery() instanceof SQLUnionQuery) {
                SQLUnionQuery unionQuery = (SQLUnionQuery) sqlSelect.getQuery();
                sql = doUnionSelect(unionQuery);
            } else {
                sql = doSelectSql(sql, sqlSelect.getQueryBlock());
            }
        }
```
```
private String doUnionSelect(SQLUnionQuery unionQuery) {
        SQLSelectQuery left = unionQuery.getLeft();
        SQLSelectQuery right = unionQuery.getRight();
        if (left instanceof SQLUnionQuery) {
            doUnionSelect((SQLUnionQuery) left);
        } else {
            doSelectSql(String.valueOf(left), (SQLSelectQueryBlock) left);
        }
        if (right instanceof SQLUnionQuery) {
            doUnionSelect((SQLUnionQuery) right);
        } else {
            doSelectSql(String.valueOf(right), (SQLSelectQueryBlock) right);
        }
        return String.valueOf(unionQuery);
    }
```

**Comment by schneidyang** [comment]
> 怎么用的？



> ```
> SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, TenantProperties.getInstance().getDbType());
> 
>         SQLStatement statement = parser.parseStatement();
> 
>         if (statement instanceof SQLSelectStatement) {
>             SQLSelect sqlSelect = ((SQLSelectStatement) statement).getSelect();
>             if (sqlSelect.getQuery() instanceof SQLUnionQuery) {
>                 SQLUnionQuery unionQuery = (SQLUnionQuery) sqlSelect.getQuery();
>                 sql = doUnionSelect(unionQuery);
>             } else {
>                 sql = doSelectSql(sql, sqlSelect.getQueryBlock());
>             }
>         }
> ```
> 
> ```
> private String doUnionSelect(SQLUnionQuery unionQuery) {
>         SQLSelectQuery left = unionQuery.getLeft();
>         SQLSelectQuery right = unionQuery.getRight();
>         if (left instanceof SQLUnionQuery) {
>             doUnionSelect((SQLUnionQuery) left);
>         } else {
>             doSelectSql(String.valueOf(left), (SQLSelectQueryBlock) left);
>         }
>         if (right instanceof SQLUnionQuery) {
>             doUnionSelect((SQLUnionQuery) right);
>         } else {
>             doSelectSql(String.valueOf(right), (SQLSelectQueryBlock) right);
>         }
>         return String.valueOf(unionQuery);
>     }
> ```


```

**Comment by wenshao** [comment]
SQLUtils.toOracleString(unionQuery) 这样试试看
