### ISSUE TITLE
WallConfig属性selelctAllow命名单词错误-）

### ISSUE THREAD

**Issue by vinartis** [alibaba/druid#4085]
![图片](https://user-images.githubusercontent.com/4651907/101872118-b0723880-3bbf-11eb-8b46-bed6a6b65871.png)

`public class WallConfig implements WallConfigMBean {

    private boolean             noneBaseStatementAllow      = false;

    private boolean             callAllow                   = true;
    private boolean             selelctAllow                = true;
    private boolean             selectIntoAllow             = true;`

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.4
请用新版本
