### ISSUE TITLE
设置了连接池初始化数量，还需要手动init()

### ISSUE THREAD

**Issue by icecrea** [alibaba/druid#4105]
@Bean
    public DruidDataSource master() throws SQLException {
        DruidDataSource dataSource = new DruidDataSource();
        ...
        dataSource.setUrl(masterUrl);
        dataSource.setDriverClassName(JDBC_DRIVER);
        dataSource.setUsername(entry.getUser());
        dataSource.setPassword(entry.getPassword());
        dataSource.setInitialSize(5);//初始化时建立物理连接的个数
        dataSource.setMinIdle(5);//池中维护的最小空闲连接数
        dataSource.setMaxActive(20);//池中最大连接数，包括闲置和使用中的连接
        dataSource.init();
        return dataSource;
    }

设置了initsize，但是测试发现还需要调用init方法才会启动的时候初始化

**Comment by lizongbo** [comment]
init动作是必须的
