### ISSUE TITLE
clickhouse的createTable语句报错

### ISSUE THREAD

**Issue by wangjxian** [alibaba/druid#4106]
可以支持clickhouse的建表语句吗。
看代码发现parseCreate的实现只有mysql的
这样一句clickhouse的建表语句。
create table topic_ch_list_2(timestamp UInt64,level String,message String) engine = MergeTree() ORDER BY timestamp SETTINGS index_granularity = 8192

Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'String) engine = MergeTree() ORDER BY , pos 81, line 1, column 76, token IDENTIFIER engine

用的是最新的1.2.4

**Comment by wenshao** [comment]
在什么场景使用，可以说下么？

**Comment by wangjxian** [comment]
> 在什么场景使用，可以说下么？

你好，我们公司有个产品。有点类似sql的可视化管理工具。需要在界面上输入sql。后台根据输入的sql的类型，做不同的策略。因此需要解析sql。但是目前的版本的parseCreate 不支持clickhouse的create 语句。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.5
问题已修复，请用新版本
