### ISSUE TITLE
ClickHouse LIMIT BY 语句报错

### ISSUE THREAD

**Issue by xieziqiang** [alibaba/druid#4110]
druid版本：1.2.4

错误日志：
### Cause: java.sql.SQLException: sql injection violation, dbType clickhouse, , druid-version 1.2.4, syntax error: syntax error, error in :'IT ? BY a, pos 297, line 11, column 18, token BY : SELECT
        a,
        b,
        sum(c) as c
        FROM table
        WHERE
        timestamp BETWEEN toDateTime(?) AND toDateTime(?)
          
        GROUP BY a, b
        ORDER BY c
        LIMIT ? BY a

clickhouse limit by 说明文档：https://clickhouse.tech/docs/en/sql-reference/statements/select/limit-by/

@wenshao 大佬，可以支持下 clickhouse 的 limit by 语法吗？谢谢

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.5
问题已修复，请用新版本
