### ISSUE TITLE
国产数据库kingbase8驱动支持

### ISSUE THREAD

**Issue by bosscloud** [alibaba/druid#4117]
jdbc:kingbase驱动是com.kingbase.Driver  
jdbc:kingbase8驱动是com.kingbase8.Driver  

工具类中JdbcUtils

```
else if (rawUrl.startsWith("jdbc:kingbase:") || rawUrl.startsWith("jdbc:kingbase8:")) {
			//return JdbcConstants.KINGBASE_DRIVER;
			return "com.kingbase8.Driver";
		} 
```
建议调整
```
else if (rawUrl.startsWith("jdbc:kingbase:") {
			return JdbcConstants.KINGBASE_DRIVER;
		} 
else if (rawUrl.startsWith("jdbc:kingbase8:")) {
			//return JdbcConstants.KINGBASE_DRIVER_8;
			return "com.kingbase8.Driver";
		} 
```

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.5
问题已修复，请用新版本

**Comment by bosscloud** [comment]
![image](https://user-images.githubusercontent.com/17606795/113096508-e21f1600-9227-11eb-9ce7-7b1132eb0a0a.png)
源码查看时候，是否落了字母呢？`不应该是om.kingbase8.Driver`，而是`com.kingbase8.Driver`
