### ISSUE TITLE
国产瀚高数据库支持

### ISSUE THREAD

**Issue by highgo-driver** [alibaba/druid#4118]
您好，
  我是国产瀚高数据库的开发者，随着国产化的快速进行，瀚高数据库的用户量也在快速增加，需要在druid中增加对瀚高数据库 
  配置的支持，希望可以得到大佬的支持。下边是瀚高数据库jdbc的配置方式：
  driver：com.highgo.jdbc.Driver
  url: jdbc:highgo://hostname:port/dbname

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.5
问题已修复，请用新版本
