### ISSUE TITLE
请问连接池的缓存机制

### ISSUE THREAD

**Issue by viking714** [alibaba/druid#4119]
最近在研究这个项目，但有个问题困惑我，如果同时到连接池的请求比较多，超过了Druid设置的同时连接的session的上限，是否Druid会把这些暂时没能处理的请求缓冲下来，然后排队等待有处理完的连接再重用给后面的请求，如果有这种这种缓冲的队列一类的东西，请问是具体在源码的哪个部分，如果我想监控当前缓冲了多少个任务，是否有什么办法？万分感谢。

**Comment by onewe** [comment]
如果当前的连接池没有足够的连接,线程会被await,变量 notEmptyWaitThreadCount 会 +1 你可以根据这个来统计等待的线程数，如果我没理解错的话。
