### ISSUE TITLE
看起来是一个bug，MySqlExprParser，minRows设到了maxRows

### ISSUE THREAD

**Issue by Adrninistrator** [alibaba/druid#4147]
https://github.com/alibaba/druid/blob/master/src/main/java/com/alibaba/druid/sql/dialect/mysql/parser/MySqlExprParser.java
在这个文件里，有两处“setMaxRows(minRows);”
没有看到调用setMinRows()方法

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.5
问题已修复，请用新版本
