### ISSUE TITLE
1.2.4不支持hive？

### ISSUE THREAD

**Issue by zombietramp** [alibaba/druid#4166]
1.2.4配置hive数据源
提示出错
![image](https://user-images.githubusercontent.com/1066758/107335162-8d4a0380-6af2-11eb-8ffc-816e94805a19.png)

![image](https://user-images.githubusercontent.com/1066758/107335307-bcf90b80-6af2-11eb-8be1-0463ffc762be.png)

![image](https://user-images.githubusercontent.com/1066758/107335383-d601bc80-6af2-11eb-8514-ca1aadd60cec.png)

**Comment by wenshao** [comment]
把WallFilter去掉就好了，wallfilter是不支持hive的
