### ISSUE TITLE
使用druid-admin监控，根据README.md文件配置后，监控页面是空白

### ISSUE THREAD

**Issue by xiaofan-wang-cd** [alibaba/druid#4167]
使用druid-admin监控，根据README.md文件配置后，使用eureka，监控页面是空白，请问客户端如何配置？

**Comment by 1725636955** [comment]
你看源码，其实就是admin请求客户端的接口获取信息，客户端的解决由druid暴露，很简单的

**Comment by 1725636955** [comment]
> 使用druid-admin监控，根据README.md文件配置后，使用eureka，监控页面是空白，请问客户端如何配置？

你看源码，其实就是admin请求客户端的接口获取信息，客户端的接口由druid暴露，很简单的

**Comment by wenshao** [comment]
@patience00 帮看下

**Comment by patience00** [comment]
@xiaofan-wang-cd  发一下你的配置

**Comment by xiaofan-wang-cd** [comment]
![Uploading image.png…]()
使用eureka配置

**Comment by xiaofan-wang-cd** [comment]
server:
  port: 19999
spring:
  application:
    name: druid-admin
  main:
    allow-bean-definition-overriding: true
  cloud:
    consul:
      enabled: false
      host: localhost
      port: 8500
      discovery:
        enable: true
        hostname: ${spring.cloud.client.ip-address}
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        instance-zone: zone1
    nacos:
      discovery:
        enabled: false
        server-addr: localhost:8848
eureka:
  instance:
    preferIpAddress: true
    ipAddress: localhost
    instance-id: ${eureka.instance.ipAddress}:${server.port}:${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
    enabled: true

monitor:
  applications: wg-service
  login-username: admin #监控页面的登录用户名和密码
  login-password: 123

**Comment by patience00** [comment]
@xiaofan-wang-cd  图片糊了,注册中心只需启用一种即可

**Comment by patience00** [comment]
@xiaofan-wang-cd  问题解决了吗?

**Comment by patience00** [comment]
@xiaofan-wang-cd  ？

**Comment by xiaofan-wang-cd** [comment]
只启用一个注册中心
server:
  port: 19999
spring:
  application:
    name: druid-admin
  main:
    allow-bean-definition-overriding: true
  cloud:
    consul:
      enabled: false
      host: localhost
      port: 8500
      discovery:
        enable: false
        hostname: ${spring.cloud.client.ip-address}
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        instance-zone: zone1
    nacos:
      discovery:
        enabled: false
        server-addr: localhost:8848
eureka:
  instance:
    preferIpAddress: true
    ipAddress: localhost
    instance-id: ${eureka.instance.ipAddress}:${server.port}:${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
    enabled: true

monitor:
  applications: wg-service
  login-username: admin #监控页面的登录用户名和密码
  login-password: 123
监控数据还是没有
![image](https://user-images.githubusercontent.com/23634459/114337642-124da980-9b84-11eb-8417-19a966ea8939.png)
同一个注册中心
![image](https://user-images.githubusercontent.com/23634459/114337662-1b3e7b00-9b84-11eb-82f6-1c2a82d8555c.png)
服务本身的监控数据有：
![image](https://user-images.githubusercontent.com/23634459/114337750-4923bf80-9b84-11eb-8ad7-733c1ebd746e.png)

**Comment by patience00** [comment]
@xiaofan-wang-cd   eureka-client没有获取到正确的serviceId已经解决，另外如果你在本地测试的话，试一下eureka控制台的WG-SERVICE的ip或域名能不能访问

**Comment by xiaofan-wang-cd** [comment]
好的，谢谢，监控页面出来了，请问一下，现在这些监控指标支持持久化么？

**Comment by patience00** [comment]
暂不支持,druid-admin只做数据的聚合
