### ISSUE TITLE
1.2.0开始com.alibaba.druid.sql.PagerUtils.limit函数删除了部分方法,导致无法兼容旧的程序

### ISSUE THREAD

**Issue by ifangta** [alibaba/druid#4176]
1.2.0开始com.alibaba.druid.sql.PagerUtils.limit函数删除了部分方法,导致无法兼容旧的程序，目前发现少了以下函数定义：
    com.alibaba.druid.sql.PagerUtils.limit(String sql, String dbType, int offset, int count)
期望能够能够提供兼容。

**Comment by lizongbo** [comment]
修改自己的组件来使用  public static String limit(String sql, DbType dbType, int offset, int count) 吧。
