### ISSUE TITLE
SQLUtils.format转换带括号的公式时丢失括号

### ISSUE THREAD

**Issue by hongchq** [alibaba/druid#4187]
sql中有公式如下：
![image](https://user-images.githubusercontent.com/13551684/109618120-23150380-7b72-11eb-9b16-1d2ebd015686.png)
格式化后括号没了，导致计算错误：

![image](https://user-images.githubusercontent.com/13551684/109618065-14c6e780-7b72-11eb-91f4-faf05be0bc68.png)

**Comment by Willam2004** [comment]
想了解下，是怎么使用了，我用master代码跑下，没有问题。 
```@Test
    public void testFormat() {
        String sql = "select t1.dim_201_org_5mmf_id, (gzss1002tb * 100) / (gzss1003mc * 1000) / 30 FROM tb1" ;
        String format = SQLUtils.format(sql, DbType.mysql);
        assertEquals("SELECT t1.dim_201_org_5mmf_id\n"
            + "\t, gzss1002tb * 100 / (gzss1003mc * 1000) / 30\n"
            + "FROM tb1", format);
    }

**Comment by hongchq** [comment]
return SQLUtils.formatMySql(sql);
版本是：druid-1.1.21.jar



hongcq@emrubik.com
 
发件人： 潘冠敬
发送时间： 2021-03-07 22:32
收件人： alibaba/druid
抄送： hongchq; Author
主题： Re: [alibaba/druid] SQLUtils.format转换带括号的公式时丢失括号 (#4187)
想了解下，是怎么使用了，我用master代码跑下，没有问题。
    public void testFormat() {
        String sql = "select t1.dim_201_org_5mmf_id, (gzss1002tb * 100) / (gzss1003mc * 1000) / 30 FROM tb1" ;
        String format = SQLUtils.format(sql, DbType.mysql);
        assertEquals("SELECT t1.dim_201_org_5mmf_id\n"
            + "\t, gzss1002tb * 100 / (gzss1003mc * 1000) / 30\n"
            + "FROM tb1", format);
    }
