### ISSUE TITLE
Oracle VPN 断开后 重建连接，数据库无法恢复连接

### ISSUE THREAD

**Issue by liuhuiyu2004** [alibaba/druid#4205]
`
spring:
  # ==========================
  #             datasource数据库设定
  # ==========================
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.19.0.17:1521:MoOne
    username: user001
    password: passworduser01
    #   数据源其他配置
    druid:
      #     配置初始化大小、最小、最大线程数
      initialSize: 5
      minIdle: 5
      #     CPU核数+1，也可以大些但不要超过20，数据库加锁时连接过多性能下降
      maxActive: 20
      #     最大等待时间，内网：800，外网：1200（三次握手1s）
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      #     配置一个连接在池中最大空间时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      #     设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
      testOnBorrow: true
      #     设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
      testOnReturn: true
      #     可以支持PSCache（提升写入、查询效率）
      poolPreparedStatements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      #     保持长连接
      keepAlive: true
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      break-after-acquire-failure: true
      connection-error-retry-attempts: 3
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
  data:
    cassandra:
      ssl: false
`
//断开恢复后依然显示错误信息。
{
  "timestamp": "2021-03-20T07:06:26.629+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "could not prepare statement; nested exception is org.hibernate.exception.GenericJDBCException: could not prepare statement",
  "path": "/home"
}

**Comment by zrlw** [comment]
break-after-acquire-failure为true时不自动重连接，这个搞成true，数据库异常时负责建立连接的线程就直接退出了，只能重启应用才行

**Comment by zrlw** [comment]
break-after-acquire-failure这个选项不要搞成true，搞成为true时不会自动重新建立连接，当数据库异常时负责建立连接的线程直接退出，数据库就算恢复正常了也只能重启应用

**Comment by liuhuiyu2004** [comment]
多谢
