### ISSUE TITLE
oracle ddl解析references出错

### ISSUE THREAD

**Issue by aTuYang** [alibaba/druid#4210]
当解析以下语法时，sqlparser的SQLExprParser类中parseReference方法运行到accept(Token.LPAREN);时，此时系统希望匹配到左括号"("，但是oracle语法中不是一定会出现左括号的"("导致在accept的函数中直接抛出异常，终止解析。

Oracle DDL
create table tableA
(
    col_ NVARCHAR2(64) not null
        constraint col_A
            unique
        constraint col_B
            references tableB,
...

**Comment by wenshao** [comment]
能否提供完整SQL
