### ISSUE TITLE
postgresql解析失败：select max(tmp1)::varchar from test01;

### ISSUE THREAD

**Issue by Galthen** [alibaba/druid#4223]
select max(tmp1)::varchar from test01;

com.alibaba.druid.sql.parser.ParserException: syntax error, error in :' max(tmp1)::varchar from test01;, pos 18, line 1, column 17, token ::

**Comment by wenshao** [comment]
问题已修复，请用新版本
https://github.com/alibaba/druid/releases/tag/1.2.6
