### ISSUE TITLE
Mysql主动断开或者有路由器主动断开Connection，导致KeepAlive Ping失效，从而造成keepAlive机制完全失效，版本是1.1.24，最新版本1.2.5也有类似问题

### ISSUE THREAD

**Issue by chen1220502052** [alibaba/druid#4227]
Mysql-5.6.46-log 主动kill connection
MySqlValidConnectionChecker isValidConnection 报错
![image](https://user-images.githubusercontent.com/7092757/113699667-75fd5000-9708-11eb-87cb-dbd319519ab2.png)
Druid-Destory线程会认为改connection正常，主要由于以下代码
![image](https://user-images.githubusercontent.com/7092757/113700401-64687800-9709-11eb-9a64-922e54781fbd.png)
随后以后正常的数据库连接的Ping检查都会抛异常InvocationTargetException，导致keepAlive失效

请问您们这块的逻辑是出于什么原因，这样设计的呢，我应该如何避免这类问题呢，谢谢浏览的我的问题

**Comment by chen1220502052** [comment]
druid 配置：
![image](https://user-images.githubusercontent.com/7092757/113701087-44858400-970a-11eb-920a-f6d57eb18d5e.png)

**Comment by Chris2018998** [comment]
推荐试试这个
https://github.com/Chris2018998/BeeCP
