### ISSUE TITLE
sql parser打印小写alter view 语句会变成 atler view

### ISSUE THREAD

**Issue by lawenyuan** [alibaba/druid#4228]
```
 druid : 1.2.4 1.2.5
```
问题：SQLUtils.toSQLString  在设置小写的情况下，alter view 会变成 atler view。

问题代码：com/alibaba/druid/sql/visitor/SQLASTOutputVisitor.java ： visit(SQLAlterViewStatement x) 函数
![image](https://user-images.githubusercontent.com/15192513/113700230-2a977180-9709-11eb-9578-d9f828581192.png)

**Comment by lawenyuan** [comment]
@wenshao

**Comment by wenshao** [comment]
问题已修复，请用新版本
https://github.com/alibaba/druid/releases/tag/1.2.6
