### ISSUE TITLE
PostgreSql库TIMESTAMPTZ字段转LocalDateTime报错

### ISSUE THREAD

**Issue by yaodaqing402** [alibaba/druid#4232]
Caused by: org.postgresql.util.PSQLException: Cannot convert the column of type TIMESTAMPTZ to requested type timestamp.

版本信息
PostgreSQL 9.4.24 (Greenplum Database 6.1.0 build dev) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.5.1 20190307 (Alibaba 6.5.1-1 2.17), 64-bit compiled on May  7 2020 06:30:38
mybatis-spring：2.0.4
mybatis：3.5.4
mybatis-plus-core:3.3.2
druid:1.2.5

**Comment by lizongbo** [comment]
这个应该是你的postgresql 版本太低导致的，升级druid和psotgresql jdbc到最新版再验证。
