### ISSUE TITLE
[] Parsing error

### ISSUE THREAD

**Issue by c-myth** [alibaba/druid#4237]
#### Postgresql
When SQL contains `[]`, the method `com.alibaba.druid.sql.SQLUtils#parseStatements(java.lang.String, com.alibaba.druid.DbType)` parse error.
For example, `cast(xx as varchar(12)[]) as mm`

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.6
问题已修复，请用新版本
