### ISSUE TITLE
resultSetTrace导致内存持续增长问题

### ISSUE THREAD

**Issue by majinju** [alibaba/druid#4254]
List<ResultSet> com.alibaba.druid.pool.DruidPooledStatement.resultSetTrace与DruidPooledStatement com.alibaba.druid.pool.DruidPooledResultSet.stmt相互持有导致内存持续增长。
List<ResultSet> com.alibaba.druid.pool.DruidPooledStatement.resultSetTrace列表持续增长但没有很好的释放和控制大小。

**Comment by Aitozi** [comment]
+1 同遇到这个问题
