### ISSUE TITLE
多个druid数据源, 可以共享一个createScheduler和destroyScheduler吗?

### ISSUE THREAD

**Issue by bthulu** [alibaba/druid#4270]
因业务需求, 可能会创建几十个数据源, 如果每个数据源都用默认的createScheduler和destroyScheduler, 那产生的线程数就太多了, 可不可以共享一个scheduler呢?

**Comment by wenshao** [comment]
可以共享的，支持单独配置createScheduler和destroyScheduler就是为了数万个超大规模的连接池场景
