### ISSUE TITLE
1.2.6 MSSQL 在不设置validationQuery会抛出异常的问题。

### ISSUE THREAD

**Issue by Fourcks** [alibaba/druid#4284]
1.2.5之前MSSQL在不设置validationQuery可以正常使用，1.2.6之后会不断抛出 java.sql.SQLException: validateConnection false。

主要原因在于 com.alibaba.druid.pool.DruidAbstractDataSource  约 13xx+行的 public void validateConnection(Connection conn) 方法发生了变更。相较上一个版本在第二个异常catch中添加了一句`result = false;`，导致进入了`if (!result)`的代码块后抛出异常。

这是希望用户以后强制填写validationQuery吗？
但是Oracle和Mysql的ValidConnectionChecker子类的isValidConnection方法提供了默认的validationQuery而MSSQL的却没有。
1.2.5以及之前版本MSSQL的ValidConnectionChecker子类的isValidConnection方法也会抛出异常，但是会因为result是true而不会抛出异常。
希望可以为MSSQL也添加一个默认validationQuery

**Comment by lizongbo** [comment]
已经加上默认validationQuery,请升级最新版验证
