### ISSUE TITLE
sqlparse模块的orderby解析模块针对复杂sql无法正确解析

### ISSUE THREAD

**Issue by penggan666** [alibaba/druid#4297]
针对于sql：
with customer_total_return as\n" +
                "(select sr_customer_sk as ctr_customer_sk\n" +
                ",sr_store_sk as ctr_store_sk\n" +
                ",sum(SR_FEE) as ctr_total_return\n" +
                "from store_returns\n" +
                ",date_dim\n" +
                "where sr_returned_date_sk = d_date_sk\n" +
                "and d_year =2000\n" +
                "group by sr_customer_sk\n" +
                ",sr_store_sk)\n" +
                " select  c_customer_id\n" +
                "from customer_total_return ctr1\n" +
                ",store\n" +
                ",customer\n" +
                "where ctr1.ctr_total_return > (select avg(ctr_total_return)*1.2\n" +
                "from customer_total_return ctr2\n" +
                "where ctr1.ctr_store_sk = ctr2.ctr_store_sk)\n" +
                "and s_store_sk = ctr1.ctr_store_sk\n" +
                "and s_state = 'NM'\n" +
                "and ctr1.ctr_customer_sk = c_customer_sk\n" +
                "order by c_customer_id\n" +
                "limit 100;
sqlParse1.1.22模块可以正确解析出：
-------------orderby-----------------
[UNKOWN.c_customer_id]
sqlParse1.2.6模块无法正确解析：
-------------orderby-----------------
[]

另外，对于更加复杂的sql，1.1.X版本和1.2.X版本均会出现无法正确解析出order by字段的情况，比如说如下sql：
with year_total as (
 select c_customer_id customer_id
       ,c_first_name customer_first_name
       ,c_last_name customer_last_name
       ,c_preferred_cust_flag customer_preferred_cust_flag
       ,c_birth_country customer_birth_country
       ,c_login customer_login
       ,c_email_address customer_email_address
       ,d_year dyear
       ,sum(ss_ext_list_price-ss_ext_discount_amt) year_total
       ,'s' sale_type
 from customer
     ,store_sales
     ,date_dim
 where c_customer_sk = ss_customer_sk
   and ss_sold_date_sk = d_date_sk
 group by c_customer_id
         ,c_first_name
         ,c_last_name
         ,c_preferred_cust_flag 
         ,c_birth_country
         ,c_login
         ,c_email_address
         ,d_year 
 union all
 select c_customer_id customer_id
       ,c_first_name customer_first_name
       ,c_last_name customer_last_name
       ,c_preferred_cust_flag customer_preferred_cust_flag
       ,c_birth_country customer_birth_country
       ,c_login customer_login
       ,c_email_address customer_email_address
       ,d_year dyear
       ,sum(ws_ext_list_price-ws_ext_discount_amt) year_total
       ,'w' sale_type
 from customer
     ,web_sales
     ,date_dim
 where c_customer_sk = ws_bill_customer_sk
   and ws_sold_date_sk = d_date_sk
 group by c_customer_id
         ,c_first_name
         ,c_last_name
         ,c_preferred_cust_flag 
         ,c_birth_country
         ,c_login
         ,c_email_address
         ,d_year
         )
  select  
                  t_s_secyear.customer_id
                 ,t_s_secyear.customer_first_name
                 ,t_s_secyear.customer_last_name
                 ,t_s_secyear.customer_preferred_cust_flag
 from year_total t_s_firstyear
     ,year_total t_s_secyear
     ,year_total t_w_firstyear
     ,year_total t_w_secyear
 where t_s_secyear.customer_id = t_s_firstyear.customer_id
         and t_s_firstyear.customer_id = t_w_secyear.customer_id
         and t_s_firstyear.customer_id = t_w_firstyear.customer_id
         and t_s_firstyear.sale_type = 's'
         and t_w_firstyear.sale_type = 'w'
         and t_s_secyear.sale_type = 's'
         and t_w_secyear.sale_type = 'w'
         and t_s_firstyear.dyear = 1999
         and t_s_secyear.dyear = 1999+1
         and t_w_firstyear.dyear = 1999
         and t_w_secyear.dyear = 1999+1
         and t_s_firstyear.year_total > 0
         and t_w_firstyear.year_total > 0
         and case when t_w_firstyear.year_total > 0 then t_w_secyear.year_total / t_w_firstyear.year_total else 0.0 end
             > case when t_s_firstyear.year_total > 0 then t_s_secyear.year_total / t_s_firstyear.year_total else 0.0 end
 order by t_s_secyear.customer_id
         ,t_s_secyear.customer_first_name
         ,t_s_secyear.customer_last_name
         ,t_s_secyear.customer_preferred_cust_flag
limit 100;

**Comment by wenshao** [comment]
这种情况，如果不提供DDL信息，是无法准确解析的

**Comment by penggan666** [comment]
请问如何提供那？
