### ISSUE TITLE
sql解析 结果不正确,ast括号匹配出错

### ISSUE THREAD

**Issue by Nanrer** [alibaba/druid#4299]
String sql = "select 1-(2+3)-(4-5)";
解析的结果是:
SELECT 1 - 2 + 3 - (4 - 5)

**Comment by tianlianyeyue123** [comment]
请问一下这个问题是如何修复的？

**Comment by Nanrer** [comment]
新版本修复了

**Comment by tianlianyeyue123** [comment]
修复的版本和相关修改能帮忙发下吗？

**Comment by tianlianyeyue123** [comment]
你好，请问一下这个问题是哪个版本修复的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月21日(周一) 下午3:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/druid] sql解析 结果不正确,ast括号匹配出错 (#4299)




 
新版本修复了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Nanrer** [comment]
看下官方最新版本吧



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月25日 10:51 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [alibaba/druid] sql解析 结果不正确,ast括号匹配出错 (#4299) |

你好，请问一下这个问题是哪个版本修复的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月21日(周一) 下午3:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/druid] sql解析 结果不正确,ast括号匹配出错 (#4299)





新版本修复了

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
