### ISSUE TITLE
国产数据库神舟OSCAR数据库驱动支持

### ISSUE THREAD

**Issue by bosscloud** [alibaba/druid#4317]
现在最新 druid版本是 1.2.6里面判断发现缺少对于新数据库支持

驱动：com.oscar.Driver  

连接：jdbc:oscar://IP:2003/OSRDB  

![image](https://user-images.githubusercontent.com/17606795/121003551-3f06f180-c7c0-11eb-98ae-46949c9328ae.png)
```
else if (rawUrl.startsWith("jdbc:oscar")) {
            return JdbcConstants.OSCAR_DRIVER;
        } 
```
![image](https://user-images.githubusercontent.com/17606795/121003587-4a5a1d00-c7c0-11eb-80de-2ed1f84bcc1e.png)
```
oscar          (1 << 36),
```
![image](https://user-images.githubusercontent.com/17606795/121003642-55ad4880-c7c0-11eb-8cda-c7ff9065a94c.png)
```
    DbType OSCAR                      = DbType.oscar;
    String OSCAR_DRIVER               = "com.oscar.Driver";
```

**Comment by wenshao** [comment]
提交PR吧，请参与进来

**Comment by lizongbo** [comment]
最新版本已经支持jdbc:oscar，请升级验证
