### ISSUE TITLE
SQLServer的链接检查MSSQLValidConnectionChecker类缺少默认的查询语句

### ISSUE THREAD

**Issue by bigtree123321** [alibaba/druid#4324]
1.2.6版本，sqlserver的isvaildConnection方法，缺少默认的查询语句。mysql及oracle的都有
![image](https://user-images.githubusercontent.com/20411027/121760520-d9b75580-cb5d-11eb-9f8b-b41bb8078c89.png)
![image](https://user-images.githubusercontent.com/20411027/121760549-f2277000-cb5d-11eb-82fa-9dfde2578703.png)
![image](https://user-images.githubusercontent.com/20411027/121760559-fe133200-cb5d-11eb-8a46-1a47ac7b75fd.png)

**Comment by DemoCap** [comment]
@wenshao
