### ISSUE TITLE
数据源监控名称问题

### ISSUE THREAD

**Issue by icode** [alibaba/druid#434]
数据源监控的时候应该可以给ds设置一个name，这样看起来比较清楚，生成那个ID可读性太差了

DataSourceStat List 

如果配置了就用我的，没有就生成原来的ID

http://110.76.43.235:8080/mini-web/druid/datasource.html

这里，第一个选项卡的名字,如果我多数据源我还是要看链接字符串我才知道是那个DS

**Comment by DuanXiaoJun** [comment]
@wenshao 请问这个名字的问题是怎么解决的呢？
