### ISSUE TITLE
Springboot项目jar包运行报错： init datasource error

### ISSUE THREAD

**Issue by hubfineall** [alibaba/druid#4345]
从gitee clone下来renren-fast项目 ，在IDEA运行正常，将其打成jar包运行报错，显示，see the followings

![image](https://user-images.githubusercontent.com/86762604/124070836-0aa9ec80-da71-11eb-81b5-71a8b80b0a0b.png)

项目yml配置文件 application-dev.yml
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://101.34.34.15:3306/jiu_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
            username: root
            password: root
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            #Oracle需要打开注释
            #validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true
有哪位靓仔知道是什么问题吗？急。在线等。。。。

**Comment by LiveAlone** [comment]
db 本身有问题吧

**Comment by lizongbo** [comment]
检查自己的网络问题。
