### ISSUE TITLE
源码编译不过

### ISSUE THREAD

**Issue by Cultivators** [alibaba/druid#4348]
maven:3.6.3
jdk:1.8.0_271
win10
版本：1.1.24、1.2.3、1.2.4 编译的时候都找不到对应的类。。是我漏加了什么还是编译的方式有问题，我是直接mvn install
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project druid: Compilation failure
: Compilation failure:
[ERROR] /D:/self_project/druid/src/main/java/com/alibaba/druid/sql/visitor/SQLASTVisitor.java:[281,27] 找不到符号
[ERROR]   符号:   类 SQLZOrderBy
[ERROR]   位置: 接口 com.alibaba.druid.sql.visitor.SQLASTVisitor
[ERROR] /D:/self_project/druid/src/main/java/com/alibaba/druid/sql/visitor/SQLASTVisitor.java:[285,27] 找不到符号
[ERROR]   符号:   类 SQLZOrderBy
[ERROR]   位置: 接口 com.alibaba.druid.sql.visitor.SQLASTVisitor
[ERROR] /D:/self_project/druid/src/main/java/com/alibaba/druid/sql/dialect/odps/ast/OdpsSelectQueryBlock.java:[30,13] 找不到符号
[ERROR]   符号:   类 SQLZOrderBy
[ERROR]   位置: 类 com.alibaba.druid.sql.dialect.odps.ast.OdpsSelectQueryBlock
[ERROR] /D:/self_project/druid/src/main/java/com/alibaba/druid/sql/dialect/odps/ast/OdpsSelectQueryBlock.java:[87,12] 找不到符号
[ERROR]   符号:   类 SQLZOrderBy
[ERROR]   位置: 类 com.alibaba.druid.sql.dialect.odps.ast.OdpsSelectQueryBlock
[ERROR] /D:/self_project/druid/src/main/java/com/alibaba/druid/sql/dialect/odps/ast/OdpsSelectQueryBlock.java:[91,29] 找不到符号
[ERROR]   符号:   类 SQLZOrderBy
[ERROR]   位置: 类 com.alibaba.druid.sql.dialect.odps.ast.OdpsSelectQueryBlock
[ERROR] /D:/self_project/druid/src/main/java/com/alibaba/druid/sql/parser/SQLExprParser.java:[2414,12] 找不到符号
[ERROR]   符号:   类 SQLZOrderBy
[ERROR]   位置: 类 com.alibaba.druid.sql.parser.SQLExprParser
[ERROR] /D:/self_project/druid/src/main/java/com/alibaba/druid/sql/dialect/odps/visitor/OdpsOutputVisitor.java:[526,26] 找不到符号
[ERROR]   符号:   类 SQLZOrderBy
[ERROR]   位置: 类 com.alibaba.druid.sql.dialect.odps.visitor.OdpsOutputVisitor
[ERROR] -> [Help 1]

**Comment by lizongbo** [comment]
请拉取最新代码进行构建编译
