### ISSUE TITLE
消费者线程获取连接失败重试次数与预期不符

### ISSUE THREAD

**Issue by code4wt** [alibaba/druid#4381]
https://github.com/alibaba/druid/blob/056645ef88735137f2d063a643304501cb02fba3/src/main/java/com/alibaba/druid/pool/DruidDataSource.java#L1429
这个判断会导致多重试一次，与预期不相符。尤其是在排错的时候，预期得到一个异常，可以日志里找不到异常。

**Comment by qixiaobo** [comment]
[notFullTimeoutRetryCount](https://github.com/alibaba/druid/pull/4594)
