### ISSUE TITLE
cross join unnest

### ISSUE THREAD

**Issue by lguohao** [alibaba/druid#4434]
是否支持cross join unnest呢，dbtype为presto时 解析格式化sql语句时候报错
![image](https://user-images.githubusercontent.com/89823910/131435721-990d89ab-bf6f-4fda-a2c7-ac7f7a324d46.png)
sqi语句为：
![image](https://user-images.githubusercontent.com/89823910/131435811-6b043be7-3873-4359-aa06-674e5db0b3ad.png)

**Comment by wenshao** [comment]
请提供SQL文本
