### ISSUE TITLE
SQLBinaryOperator能否支持AND NOT逻辑操作？

### ISSUE THREAD

**Issue by xgpxg** [alibaba/druid#4436]
目前看只支持这3种：
BooleanAnd("AND", 140), 
BooleanXor("XOR", 150), 
BooleanOr("OR", 160),

因项目需求，通过SQLBinaryOperator构建SQL时，需要构建出AND NOT,能否通过扩展支持BooleanNot("AND NOT", 140)呢？
如果可以，需要修改那些地方呢？

**Comment by wenshao** [comment]
```SQL
a AND b (NOT c)
```
其中NOT是SQLUnaryOperator.NOT
