### ISSUE TITLE
Spring 监控 (Spring Stat)  无数据

### ISSUE THREAD

**Issue by ydl00** [alibaba/druid#4455]
1.1.22 以及 以上版本 , 即使 设置 spring.datasource.druid.aop-patterns  属性, Spring Stat 默认 也不会生效,  

我们需要 手动 配置 spring.aop.auto= false

druid-spring-boot-starter/src/main/java/com/alibaba/druid/spring/boot/autoconfigure/stat/DruidSpringAopConfiguration.java

AOP二次代理问题  的提交 是否可以优化

@eryanwcp

**Comment by kaitezhan** [comment]
这个问题解决了吗？
 stat-view-servlet:
          enabled: true
          url-pattern: /monitor/druid/*
        web-stat-filter:
          enabled: true

这样配置了还是没数据
