### ISSUE TITLE
1.1.21版本通过maven下载时，未自动下载lib文件夹部分依赖

### ISSUE THREAD

**Issue by chen462488588** [alibaba/druid#4482]
我的环境：
```
$ mvn -v
Apache Maven 3.8.2 (NON_CANONICAL)
Maven home: /opt/maven
Java version: 1.8.0_292, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-openjdk/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "linux", version: "5.10.68-1-manjaro", arch: "amd64", family: "unix"
```
无法自动下载lib包下的openjdk-1.8-jconsole.jar和openjdk-1.8-tools，导致报错```The following artifacts could not be resolved: com.sun:tools:jar:1.8, com.sun:jconsole:jar:1.8: Could not find artifact com.sun:tools:jar:1.8 at specified path /home/data/MavenRepo/com/alibaba/druid/1.1.21/lib/openjdk-1.8-tools.jar```，手动下载这两个jar,并放到com/alibaba/druid/1.1.21/lib才行。

**Comment by akuma** [comment]
我也遇到了这个问题，切换会 maven 3.8.1 或者更早版本就没有这个问题。

**Comment by chen462488588** [comment]
> 我也遇到了这个问题，回退到 maven 3.8.1 或者更早版本就没有这个问题。

哦好的谢谢，又是manjaro滚动更新的锅。
