### ISSUE TITLE
第二次insert 报Caused by: java.sql.SQLException: 索引中丢失  IN 或 OUT 参数

### ISSUE THREAD

**Issue by ddatsh** [alibaba/druid#453]
非常容易重现,只要配个 NamedParameterJdbcTemplate 
oracle 数据库

<pre>
public static void main(String[] args) throws Exception {
        ApplicationContext ctx = new ClassPathXmlApplicationContext(
                "application-context.xml");
        NamedParameterJdbcTemplate jt = (NamedParameterJdbcTemplate) ctx
                .getBean("jdbcTemplate");

        KeyHolder keyHolder = new GeneratedKeyHolder();
        Map paramMap = new HashMap();
        paramMap.put("moduleName", "moduleName");
        paramMap.put("description", "description");
        paramMap.put("status", "status");
        paramMap.put("env", "env");
        SqlParameterSource ss = new MapSqlParameterSource(paramMap);
        String sql = "insert into module (id,moduleName,description,status,env) values (seq_module_id.nextval,:moduleName,:description,:status,:env)";
        jt.update(sql, ss, keyHolder, new String[] { "id" });
        jt.update(sql, ss, keyHolder, new String[] { "id" });
}
</pre>

**Comment by owenlmg** [comment]
都两年多了这个问题还没解决啊？

**Comment by vcsupser** [comment]
都三年了这个问题还没解决啊？

**Comment by lizongbo** [comment]
请使用最新版本验证,复现的话重新提Issue
