### ISSUE TITLE
监控页面的sql监控，事务中是什么状态

### ISSUE THREAD

**Issue by ddatsh** [alibaba/druid#457]
配好了可用正确的，spring annotation 事务，可被正确提交，回滚
service 执行的db操作已经完事了
sql监控页面里的事务中计数一直累加？
这个事物中，是指的语句是属于事务的而已吧？而非还在事务里，没被提交吧？

如果是这样，那WEB应用、session监控，spring监控  TAB里
事务提交数、事务回滚数 还是显示的0

**Comment by srctar** [comment]
@wenshao  真的是这样的么？ 我的数据库设置为自动提交事务。 隔离级别RR， 我已经看到事务的结果生效了。 为何页面显示还是“事务中”
