### ISSUE TITLE
Apache Log4j2远程代码执行漏洞有对应更新么？

### ISSUE THREAD

**Issue by david5515** [alibaba/druid#4606]
https://help.aliyun.com/noticelist/articleid/1060971232.html
漏洞描述
Apache Log4j2是一款优秀的Java日志框架。2021年11月24日，阿里云安全团队向Apache官方报告了Apache Log4j2远程代码执行漏洞。由于Apache Log4j2某些功能存在递归解析功能，攻击者可直接构造恶意请求，触发远程代码执行漏洞。漏洞利用无需特殊配置，经阿里云安全团队验证，Apache Struts2、Apache Solr、Apache Druid、Apache Flink等均受影响。阿里云应急响应中心提醒 Apache Log4j2 用户尽快采取安全措施阻止漏洞攻击。

**Comment by wy0682109523** [comment]
同问，顶一下

**Comment by wenshao** [comment]
Aliyun Druid不是Apache Druid，Driud没有直接依赖log4j2，只是通过反射判断当前环境有什么log库就用什么库

**Comment by david5515** [comment]
收到，谢谢
