### ISSUE TITLE
StatementSqlFormatOption 日志输出LocalDateTime类型的问题

### ISSUE THREAD

**Issue by FeiLong2014** [alibaba/druid#4610]
CsfLogFilter csfLogFilter = new CsfLogFilter();
        csfLogFilter.setStatementCloseAfterLogEnabled(false);
        csfLogFilter.setStatementCreateAfterLogEnabled(false);
        csfLogFilter.setStatementPrepareCallAfterLogEnabled(false);
        csfLogFilter.setStatementPrepareAfterLogEnabled(false);
        csfLogFilter.setResultSetLogEnabled(false);
        csfLogFilter.setStatementParameterSetLogEnabled(false);
        csfLogFilter.setStatementParameterClearLogEnable(false);
        csfLogFilter.setStatementSqlFormatOption(SQLUtils.DEFAULT_FORMAT_OPTION);
        csfLogFilter.setStatementExecutableSqlLogEnable(true);
        csfLogFilter.setStatementSqlPrettyFormat(true);

输出日志：UPDATE xxx
SET TIME = 2021-12-13T13:44:54.951
WHERE 1=1

原始问题所在位置：
SQLASTOutputVisitor -》 printParameter

我的临时解决办法：
LogFilter logExecutableSql ：
List<Object> parameters = new ArrayList<Object>(parametersSize);
        for (int i = 0; i < parametersSize; ++i) {
            JdbcParameter jdbcParam = statement.getParameter(i);
            Object value = jdbcParam.getValue();
            if (value instanceof TemporalAccessor) {
                String strDate = dtf2.format((TemporalAccessor)value);
                value = strDate;
            }
            parameters.add(jdbcParam != null ? value : null);
        }

希望底层修复一下

**Comment by lizongbo** [comment]
加上处理逻辑，等构建新包后可以验证。
