### ISSUE TITLE
当方法使用ExecutorService在线程池中运行时，jdbc exectime统计不正确

### ISSUE THREAD

**Issue by peream** [alibaba/druid#462]
日志：
2013-10-11 09:01:26 [SEND_TOPIC-1](StatFilter.java:465)
ERROR: slow sql 1860001 millis. 
select \* from ( select topicqueue0_.id as id1_31_, topicqueue0_.add_time as add_time2_31_, topicqueue0_.failed_count as failed_c3_31_, topicqueue0_.json_str as json_str4_31_, topicqueue0_.topic_bus_id as topic_bu5_31_ from comm_topic_queue topicqueue0_ order by topicqueue0_.add_time desc ) where rownum <= ?
[1000]

comm_topic_queue是个空表，从执行到打印出日志的时间没超过1s，但是日志记录了1860001 millis

ExecutorService 是随spring启动的
executor.execute(new Runnable() {
            @Override
            public void run()
            {
                busMethod();
            }
        });

```
private void busMethod()
{
    //logic ....
}
```

**Comment by lizongbo** [comment]
请使用最新版本验证
