### ISSUE TITLE
有计划支持 StarRocks 的语法解析吗

### ISSUE THREAD

**Issue by chachae** [alibaba/druid#4628]
有计划支持 StarRocks 的语法解析吗，现在使用 MySQL 的 DbType 解析 StarRocks 的部分函数语法会报错

**Comment by huangyu2021** [comment]
有找到starrocks的语法解析办法吗？我现在也需要。

**Comment by chachae** [comment]
> 有找到starrocks的语法解析办法吗？我现在也需要。

没有，只做了简单的dml / ddl区分，至于sr 其它函数和一些特有的sql 就当普通sql 去做得了，真要做解析光靠druid 还是远远不够的
