### ISSUE TITLE
原始并列的union all字句，调用SQLUtils.toSQLExpr(sql)方法后会报缺失括号（解析后括号放错了位置）。附上原始sql

### ISSUE THREAD

**Issue by xf12341** [alibaba/druid#4647]
SELECT
	*
FROM
	(
	SELECT
		C_IDEN
	FROM
		(
		SELECT
			E.c_iden
		FROM
			(
			SELECT
				a.c_iden
			FROM
				A_P_CO a
			LEFT JOIN (
				SELECT
					b.c_group_code
				FROM
					A_P_AB b
				LEFT JOIN A_P_AB_G c ON
					b.c_g = c.c_g
				WHERE
					b.n_c = 1
					AND c.n_c = 1) d ON
				d.c_g = a.c_p) E
		WHERE
			E.C_P IS NOT NULL
			AND NOT EXISTS (
			SELECT
				1
			FROM
				A_P_CO sett
			WHERE
				sett.C_P = E.C_P
				AND sett.C_M = E.C_M
				AND sett.c_b = e.c_b
				AND NVL(sett.c_t, ' ') = NVL(e.c_t, ' ')
				AND sett.c_s = e.c_s
				AND sett.c_d = e.c_d
				AND sett.n_s = e.n_s
				AND sett.C_D = e.C_D
				AND sett.C_DV = e.C_DV
				AND NVL(sett.C_E, ' ') = NVL(e.C_E, ' ')
				AND sett.c_ds = e.c_ds
				AND sett.n_c = E.n_c )
	UNION ALL
		SELECT
			a.c_iden
		FROM
			A_P_CO a
		WHERE
			NOT EXISTS (
			SELECT
				1
			FROM
				A_P_AB b
			WHERE
				a.c_p = b.c_g
				AND b.n_c = 1)) ) A
WHERE
	A.C_P = '111100'
	AND TO_DATE('2018-07-04', 'yyyy-MM-dd') BETWEEN A.D_BEGIN AND A.D_END
	AND A.N_C = 1
	AND c_b = 'test1'
	AND c_H = 'test2'
UNION ALL
SELECT
	*
FROM
	(
	SELECT
		*
	FROM
		(
		SELECT
			C_IDEN
		FROM
			(
			SELECT
				E.c_iden
			FROM
				(
				SELECT
					a.c_iden
				FROM
					A_P_CO a
				LEFT JOIN (
					SELECT
						b.c_g,
						c.c_p
					FROM
						A_P_AB b
					LEFT JOIN AP_AB c ON
						b.c_g = c.c_g
					WHERE
						b.n_c = 1
						AND c.n_c = 1) d ON
					d.c_g = a.c_p) E
			WHERE
				E.C_P IS NOT NULL
				AND NOT EXISTS (
				SELECT
					1
				FROM
					A_P_CO sett
				WHERE
					sett.C_P = E.C_P
					AND sett.C_M = E.C_M
					AND sett.c_b = e.c_b
					AND NVL(sett.c_t, ' ') = NVL(e.c_t, ' ')
					AND sett.c_s = e.c_s
					AND sett.c_d = e.c_d
					AND sett.n_s = e.n_s
					AND sett.C_D = e.C_D
					AND sett.C_DV = e.C_DV
					AND NVL(sett.C_E, ' ') = NVL(e.C_E, ' ')
					AND sett.c_d = e.c_d
					AND sett.n_c = E.n_c )
		UNION ALL
			SELECT
				a.c_iden
			FROM
				A_P_CO a
			WHERE
				NOT EXISTS (
				SELECT
					1
				FROM
					A_P_AB b
				WHERE
					a.c_p = b.c_g
					AND b.n_c = 1)) ) A
	WHERE
		A.C_P = '111100'
		AND TO_DATE('2018-07-04', 'yyyy-MM-dd') BETWEEN A.D_BEGIN AND A.D_END
		AND A.N_C = 1
		AND c_b <> 'test1'
		AND c_busi_type <> 'test2'
		AND c_b <> 'test3'
	ORDER BY
		C_S ASC)
UNION ALL
SELECT
	*
FROM
	(
	SELECT
		C_IDEN
	FROM
		(
		SELECT
			E.c_iden
		FROM
			(
			SELECT
				a.c_iden
			FROM
				A_P_CO a
			LEFT JOIN (
				SELECT
					b.c_g,
					c.c_p
				FROM
					A_P_AB b
				LEFT JOIN A_P_AB c ON
					b.c_g = c.c_g
				WHERE
					b.n_c = 1
					AND c.n_c = 1) d ON
				d.c_g = a.c_p) E
		WHERE
			E.C_P IS NOT NULL
			AND NOT EXISTS (
			SELECT
				1
			FROM
				A_P_CO sett
			WHERE
				sett.C_P = E.C_P
				AND sett.C_M = E.C_M
				AND sett.c_b = e.c_b
				AND NVL(sett.c_t, ' ') = NVL(e.c_t, ' ')
				AND sett.c_s = e.c_s
				AND sett.c_d = e.c_d
				AND sett.n_s = e.n_s
				AND sett.C_D = e.C_D
				AND sett.C_DV = e.C_DV
				AND NVL(sett.C_E, ' ') = NVL(e.C_E, ' ')
				AND sett.c_d = e.c_d
				AND sett.n_c = E.n_c )
	UNION ALL
		SELECT
			a.c_iden
		FROM
			A_P_CO a
		WHERE
			NOT EXISTS (
			SELECT
				1
			FROM
				A_P_AB b
			WHERE
				a.c_p = b.c_g
				AND b.n_c = 1)) ) A
WHERE
	A.C_P = '111100'
	AND TO_DATE('2018-07-04', 'yyyy-MM-dd') BETWEEN A.D_BEGIN AND A.D_END
	AND A.N_CHECK_STATE = 1
	AND c_b = 'tet1'
UNION ALL
SELECT
	*
FROM
	(
	SELECT
		C_IDEN
	FROM
		(
		SELECT
			E.c_iden
		FROM
			(
			SELECT
				a.c_iden
			FROM
				A_P_CO a
			LEFT JOIN (
				SELECT
					b.c_g,
					c.c_p
				FROM
					A_P_AB b
				LEFT JOIN A_P_AB_G c ON
					b.c_g = c.c_g
				WHERE
					b.n_c = 1
					AND c.n = 1) d ON
				d.c_g = a.c_p) E
		WHERE
			E.C_P IS NOT NULL
			AND NOT EXISTS (
			SELECT
				1
			FROM
				A_P_CO sett
			WHERE
				sett.C_P = E.C_P
				AND sett.C_M = E.C_M
				AND sett.c_b = e.c_b
				AND NVL(sett.c_t, ' ') = NVL(e.c_t, ' ')
				AND sett.c_s = e.c_s
				AND sett.c_d = e.c_d
				AND sett.n_s = e.n_s
				AND sett.C_D = e.C_D
				AND sett.C_DV = e.C_DV
				AND NVL(sett.C_E, ' ') = NVL(e.C_E, ' ')
				AND sett.c_d = e.c_d
				AND sett.n_c = E.n_c )
	UNION ALL
		SELECT
			a.c_iden
		FROM
			A_P_CO a
		WHERE
			NOT EXISTS (
			SELECT
				1
			FROM
				A_P_AB b
			WHERE
				a.c_p = b.c_g
				AND b.n_c = 1)) ) A
WHERE
	A.C_P = '111100'
	AND TO_DATE('2018-07-04', 'yyyy-MM-dd') BETWEEN A.D_BEGIN AND A.D_END
	AND A.N_C = 1
	AND c_b = 'test1'
UNION ALL
SELECT
	*
FROM
	(
	SELECT
		C_IDEN
	FROM
		(
		SELECT
			E.c_iden
		FROM
			(
			SELECT
				a.c_iden
			FROM
				A_P_CO a
			LEFT JOIN (
				SELECT
					b.c_g,
					c.c_p
				FROM
					A_P_AB b
				LEFT JOIN A_P_AB_G c ON
					b.c_g = c.c_g
				WHERE
					b.n_c = 1
					AND c.n_c = 1) d ON
				d.c_g = a.c_p) E
		WHERE
			E.C_P IS NOT NULL
			AND NOT EXISTS (
			SELECT
				1
			FROM
				A_P_CO sett
			WHERE
				sett.C_P = E.C_P
				AND sett.C_M = E.C_M
				AND sett.c_b = e.c_b
				AND NVL(sett.c_t, ' ') = NVL(e.c_t, ' ')
				AND sett.c_s = e.c_s
				AND sett.c_dv = e.c_dv
				AND sett.n_s = e.n_s
				AND sett.C_D = e.C_D
				AND sett.C_DV = e.C_DV
				AND NVL(sett.C_E, ' ') = NVL(e.C_E, ' ')
				AND sett.c_d = e.c_d
				AND sett.n_c = E.n_c )
	UNION ALL
		SELECT
			a.c_iden
		FROM
			A_P_CO a
		WHERE
			NOT EXISTS (
			SELECT
				1
			FROM
				A_P_AB b
			WHERE
				a.c_p = b.c_g
				AND b.n_c = 1)) ) A
WHERE
	A.C_P = '111100'
	AND TO_DATE('2018-07-04', 'yyyy-MM-dd') BETWEEN A.D_BEGIN AND A.D_END
	AND A.N_C = 1
	AND c_b = 'test1'
	AND c_HBTIME = 'test2'

**Comment by lizongbo** [comment]
最新代码优化了括号解析和生成逻辑，等1.2.23版本验证
