### ISSUE TITLE
web监控无法登录,servlet无法获取到用户名和密码

### ISSUE THREAD

**Issue by ken-alx** [alibaba/druid#4653]
![image](https://user-images.githubusercontent.com/19256972/148520386-5e724ad4-f38f-44f1-8bc6-4dd9a934da91.png)

官方使用的是form-data提交的数据, 到后端 servlet 时无法获取到数据。

![image](https://user-images.githubusercontent.com/19256972/148520591-46ed5683-8091-43fa-b3a2-42460fa9d37c.png)

![image](https://user-images.githubusercontent.com/19256972/148520669-0aabc275-9e8f-4b68-be7d-fe88da06828a.png)

**Comment by github-liuzhongkun** [comment]
是不是在servlet执行过程中获取了请求体的数据

**Comment by ken-alx** [comment]
@github-liuzhongkun 是的，这个找到问题了，忘记关了。因为重写了request的问题
