### ISSUE TITLE
Auto-Configuration should expose explicit datasource type, not interface

### ISSUE THREAD

**Issue by snicoll** [alibaba/druid#4673]
The following auto-configuration exposes a bean of type `javax.sql.DataSource` and provide an explicit initialization method on it:

https://github.com/alibaba/druid/blob/f937ecd43363b2df61afdc120858097cb2510580/druid-spring-boot-starter/src/main/java/com/alibaba/druid/spring/boot/autoconfigure/DruidDataSourceAutoConfigure.java#L53-L58

`javax.sql.DataSource` does not have an method named `init` so introspecting the bean definition at build time is failing. Please expose the actual type rather than the interface.

**Comment by linghengqian** [comment]
@wenshao Is it possible to deal with it? This affects additional applications.

**Comment by zrlw** [comment]
it might be better that removing initMethod from ```@Bean``` and calling init() at the end of DruidDataSourceWrapper#afterPropertiesSet

**Comment by zrlw** [comment]
refer to org.springframework.beans.factory.BeanFactory javadocs:
```
The full set of initialization methods and their standard order is: 
1.BeanNameAware's setBeanName 
2.BeanClassLoaderAware's setBeanClassLoader 
3.BeanFactoryAware's setBeanFactory 
4.EnvironmentAware's setEnvironment 
5.EmbeddedValueResolverAware's setEmbeddedValueResolver 
6.ResourceLoaderAware's setResourceLoader(only applicable when running in an application context) 
7.ApplicationEventPublisherAware's setApplicationEventPublisher(only applicable when running in an application context) 
8.MessageSourceAware's setMessageSource(only applicable when running in an application context) 
9.ApplicationContextAware's setApplicationContext(only applicable when running in an application context) 
10.ServletContextAware's setServletContext(only applicable when running in a web application context) 
11.postProcessBeforeInitialization methods of BeanPostProcessors 
12.InitializingBean's afterPropertiesSet 
13.a custom init-method definition 
14.postProcessAfterInitialization methods of BeanPostProcessors 
```
