### ISSUE TITLE
DruidDataSource restart()时，activeCount not zero

### ISSUE THREAD

**Issue by Championkid** [alibaba/druid#4707]
你好， 有个业务我需要去重新设置DruidDataSource 的链接，这无法避免的要先使用 restart() 更新this.inited参数，但是在我restart时发现activeCount > 0，来请教下，怎么清除连接池，或者是用什么方式能够使 restart 成功？

谢谢！
![image](https://user-images.githubusercontent.com/33680380/157874285-cb492713-2e3c-4b8c-8c21-9b01ec707698.png)

**Comment by Championkid** [comment]
@

**Comment by Championkid** [comment]
我调用 restart 之前，是清空了 activeConnections 集合的，但我发现activeConnections总是为空，经过读代码我发现，要设置开启 removeAbandoned，这样创建的链接才会被加入到activeConnections中。

**Comment by gltncx11** [comment]
你好 这里我activeCount不是0，但是activeConnections也是为空，是必须要开启removeAbandoned吗
