### ISSUE TITLE
mysql数据库，druid 0.2.26版本，只使用statwall时，空的sql语句，会报异常。

### ISSUE THREAD

**Issue by lifw555** [alibaba/druid#473]
比如语句：
/ \* !40101 SET NAMES utf8 \* /;
/ \* !40101 SET SQL_MODE=''\* /;

/ \* !40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 \* /;
/ \*  !40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' \* /;

**Comment by lizongbo** [comment]
请使用最新版验证
