### ISSUE TITLE
druid-0.2.25 数据库连接统计信息错误

### ISSUE THREAD

**Issue by michealpwanted** [alibaba/druid#479]
运行一段时间, 有时会发现, 以下两个数据错误
ds.getActiveCount();
ds.getPoolingCount();

当无连接使用的情况下getPoolingCount会小于连接池配置的minIdle 数量。
getActiveCount有时会成为负数。

一旦这两个值错误，错误会一直保持。除非重启

**Comment by starlight36** [comment]
遇到了这个问题。统计到的ActiveCount值出现了负数，使用的版本是1.1.11

**Comment by lizongbo** [comment]
请使用最新版验证
