### ISSUE TITLE
【疑问】为什么2.8以后连更新日志都没了？

### ISSUE THREAD

**Issue by TechAilurus** [alibaba/druid#4799]
目前刚2.10了，但是2.9开始都找不到更新日志，changelog，wiki change等等。
我觉得这有点不符合软件工程的精神，尤其是一个start达到25K的开源软件，让人对框架的未来有一丝隐忧。

**Comment by wenshao** [comment]
一直要补上，但在忙fastjson相关的事情，1.2.9 & 1.2.10都是内部需求直接发的，所以也没发release notes。预计6月份会补上并且恢复更新。
