### ISSUE TITLE
The POM for com.alibaba:druid:jar:1.2.11 is invalid

### ISSUE THREAD

**Issue by lzysuqianqiu** [alibaba/druid#4822]
The POM for com.alibaba:druid:jar:1.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

**Comment by martin7569** [comment]
同样得问题，解决了么

**Comment by moonmm** [comment]
同样问题

**Comment by mofee** [comment]
the saem problem:
[WARNING] The POM for com.alibaba:druid:jar:1.2.11 is invalid, transitive dependencies (if any) will not be available: 2 problems were encountered while building the effective model for com.alibaba:druid:1.2.11
[ERROR] 'dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${project.basedir}/lib/openjdk-1.8-tools.jar @
[ERROR] 'dependencies.dependency.systemPath' for com.sun:jconsole:jar must specify an absolute path but is ${project.basedir}/lib/openjdk-1.8-jconsole.jar @

**Comment by lzysuqianqiu** [comment]
https://github.com/alibaba/druid/commit/7e4778b7563258b1b8ec5e64a0775da31f580a63   已经在移除了

**Comment by XM2510136957** [comment]
![image](https://user-images.githubusercontent.com/18229485/179931309-6ca03d51-9094-4b2f-ba43-776acb1a0a3e.png)

**Comment by XM2510136957** [comment]
![image](https://user-images.githubusercontent.com/18229485/179931398-5379b60e-4cfd-43f1-bb84-968a60d85d8c.png)

**Comment by RandyZ** [comment]
同样的问题，jdk17

**Comment by XM2510136957** [comment]
> ![image](https://user-images.githubusercontent.com/18229485/179931398-5379b60e-4cfd-43f1-bb84-968a60d85d8c.png)

解决办法：
<exclusions>
    <exclusion>
        <groupId>com.sun</groupId>
        <artifactId>jconsole</artifactId>
    </exclusion>
    <exclusion>
        <groupId>com.sun</groupId>
        <artifactId>tools</artifactId>
    </exclusion>
</exclusions>

**Comment by jiataoliu** [comment]
mvn install 警告：

```tex
The POM for com.alibaba:druid:jar:1.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
```



升到 1.2.20 打包不报警告：

```xml

<!-- Druid 数据库连接池 -->
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>druid-spring-boot-starter</artifactId>
    <!-- <version>1.2.11</version> -->
    <version>1.2.20</version>
</dependency>
```
