### ISSUE TITLE
sql解析如果获取建表语句的注释

### ISSUE THREAD

**Issue by liqiang134619** [alibaba/druid#4829]
create table public.company_contacts(
company_id int8 not null --tgest
)
              
我想获取对应列的 列注释
可以提供对应的api吗

**Comment by li395092734** [comment]
你找到解决办法了吗？我想获取整个表的注释，

**Comment by liqiang134619** [comment]
抱歉，最后我也没有找到办法。

**Comment by li395092734** [comment]
一不小心找到你的问题的答案了。
https://github.com/alibaba/druid/issues/2426

**Comment by li395092734** [comment]
我再继续研究我的。唉。😌

**Comment by lizongbo** [comment]
这是要获取sql的纯注释内容？
