### ISSUE TITLE
MySqlShowStatement 无法识别show语句

### ISSUE THREAD

**Issue by Caiyinwei** [alibaba/druid#4861]
sqlStatement instanceof MySqlShowStatement 为false，语句为show tables

**Comment by Caiyinwei** [comment]
MySqlShowStatement识别语句错误

**Comment by Caiyinwei** [comment]
1.2.11版本

**Comment by lizongbo** [comment]
因为其它db也支持这个语法，所以类型是 com.alibaba.druid.sql.ast.statement.SQLShowTablesStatement
并不是Mysql专属，因此没有实现MySqlShowStatement。
