### ISSUE TITLE
mysql下limit 0报错

### ISSUE THREAD

**Issue by bluesx** [alibaba/druid#4866]
limit 0在mysql数据实际是允许存在的，但是在druid下执行就会报语法错误，希望尽快修复！
我目前的应用场景：解析表或视图或子查询的所有输出字段，但是避免扫描表，避免返回数据。
版本：1.2.6

**Comment by bluesx** [comment]
版本:1.2.6

**Comment by ShepherdZFJ** [comment]
换成limit 1，本身你只是解析sql，并不是去执行sql，不存在扫表和返回数据

**Comment by ShepherdZFJ** [comment]
> limit 1 也会返回数据，我不要返回数据。
哦哦，我看错了，你是用druid执行SQL，不是解析SQL

**Comment by kimmking** [comment]
替换为：1 = 2不就得了。
或者直接用connection.getMetadata
