### ISSUE TITLE
druid1.0.31版本Druid-ConnectionPool-Destroy线程不销毁持续增长

### ISSUE THREAD

**Issue by lit2430** [alibaba/druid#4890]
druid版本：1.0.31
问题：部署服务之后，一天时间，服务的线程数量达到500多，看线程堆栈，发现Druid-ConnectionPool-Destroy线程数达到了354个，且一直都是TIMED_WAITING状态，现在怀疑是不是线程没有释放导致的？
线程堆栈图：
<img width="918" alt="image" src="https://user-images.githubusercontent.com/91309604/183394762-2c52f39e-2abd-4ae3-8141-a172afeb2b3f.png">

初始化连接池代码：
    private Connection getPoolConnection() throws Exception {
        long start = System.currentTimeMillis();
        Connection conn = null;
        String key = Hashing.md5().newHasher().putString(JSONObject.toJSON(dataSource).toString(), Charsets.UTF_8).hash().toString();
            DataSource ds = datasourceMap.get(key);
            if (ds == null) {
                synchronized (key.intern()) {
                    ds = datasourceMap.get(key);
                    if (ds == null) {
                        Map<String, String> conf = new HashedMap();
                        Properties properties = new Properties();
                        if(dataSource.containsKey(PROPERTIES)){
                            Map<String, String> props = JSONObject.parseObject(JSON.toJSONString(dataSource.get(PROPERTIES)),new TypeReference<Map<String, String>>(){});
                            properties.putAll(props);
                        }
                        conf.put(DruidDataSourceFactory.PROP_DRIVERCLASSNAME, dataSource.get(DRIVER));
                        conf.put(DruidDataSourceFactory.PROP_URL, dataSource.get(JDBC_URL));
                        conf.put(DruidDataSourceFactory.PROP_USERNAME, dataSource.get(USERNAME));
                        if (StringUtils.isNotBlank(dataSource.get(PASSWORD))) {
                            conf.put(DruidDataSourceFactory.PROP_PASSWORD, dataSource.get(PASSWORD));
                        }
                        conf.put(DruidDataSourceFactory.PROP_INITIALSIZE, "5");
                        conf.put(DruidDataSourceFactory.PROP_MINIDLE, "5");
                        conf.put(DruidDataSourceFactory.PROP_MAXACTIVE, "20");
                        conf.put(DruidDataSourceFactory.PROP_MAXWAIT, "30000");
                        conf.put(DruidDataSourceFactory.PROP_TIMEBETWEENEVICTIONRUNSMILLIS, "600000");
                        conf.put(DruidDataSourceFactory.PROP_TESTWHILEIDLE, "true");
                        conf.put(DruidDataSourceFactory.PROP_VALIDATIONQUERY, VALIDATIONQUERY);
                        conf.put(DruidDataSourceFactory.PROP_FILTERS,"stat");
                        conf.put(DruidDataSourceFactory.PROP_REMOVEABANDONED, "true");
                        conf.put(DruidDataSourceFactory.PROP_REMOVEABANDONEDTIMEOUT, "1800");
                        conf.put(DruidDataSourceFactory.PROP_LOGABANDONED, "true");
                        DruidDataSourceBuilder.create().build();
                        DruidDataSource druidDS = (DruidDataSource) DruidDataSourceFactory.createDataSource(conf);
                        druidDS.setConnectProperties(properties);
                        druidDS.setBreakAfterAcquireFailure(true);
                        druidDS.setConnectionErrorRetryAttempts(5);
                        datasourceMap.put(key, druidDS);
                        ds = datasourceMap.get(key);
                    }
                }
            }
            try {
                conn = ds.getConnection();
            } catch (SQLException e) {
                datasourceMap.remove(key);
                throw e;
            }
            return conn;
    }

**Comment by libra146** [comment]
请问这个问题如何解决的，我也遇到了这个问题
