### ISSUE TITLE
为什么连接池里有5个核心线程连接，但每次总是获取同一个连接？

### ISSUE THREAD

**Issue by lit2430** [alibaba/druid#4892]
对同一个接口调用50次，发现druidDatasource获取的连接是同一个，这个是什么问题？
<img width="686" alt="5FBB645E-018E-4ee4-A211-C54A73A93344" src="https://user-images.githubusercontent.com/91309604/183871611-980423c8-150e-4636-95dc-70834d906c1a.png">
下面是配置：
![image](https://user-images.githubusercontent.com/91309604/183871808-d909363e-4b6a-40d8-b2f7-68010e1eb7bd.png)

**Comment by fengzhizi2022** [comment]
连接池初始化好了之后，会放在一个DruidConnectionHolder[] connections数组里面，每个getConnection的时候，都是取这个数组的最后一个元素。所以你测试的场景，每次都是同一个连接。

**Comment by lit2430** [comment]
感谢，看源码找到原因了
