### ISSUE TITLE
mysql 解析 sql 报错

### ISSUE THREAD

**Issue by 2259289435** [alibaba/druid#4904]
版本：1.2.6

### SQL: select             a.region_id region,             a.org_id organizeId,             a.meal_type_id mealTypeId         from (                          select                 b.region_id,                 b.org_id,                 a.meal_type_id             from (                                  select                     a.customer_id,                     a.meal_type_id                 from cai_dining_calendar a                  WHERE a.eat_flag = 1 and a.dining_date = ? and a.tenant_code = ?              ) a inner join (select * from json_table (                                          ?,                     '$[*]' COLUMNS (                         `region_id` bigint PATH '$.a' ERROR ON ERROR,                         `org_id` bigint PATH '$.b' ERROR ON ERROR,                         `customer_id` bigint PATH '$.c' ERROR ON ERROR                     )             ) b) b on a.customer_id = b.customer_id             group by b.region_id,b.org_id,a.meal_type_id         ) a         order by a.region_id,a.org_id,a.meal_type_id

Cause: java.sql.SQLSyntaxErrorException: com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual IDENTIFIER COLUMNS
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual IDENTIFIER COLUMNS
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:235)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:88)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy169.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:223)

**Comment by lizongbo** [comment]
1.2.20已经能正常解析，只是生成的sql里会多上 "as "和"default "字样：

`` ` 

mysql生成的sql===SELECT a.region_id AS region, a.org_id AS organizeId, a.meal_type_id AS mealTypeId
FROM (
	SELECT b.region_id, b.org_id, a.meal_type_id
	FROM (
		SELECT a.customer_id, a.meal_type_id
		FROM cai_dining_calendar a
		WHERE a.eat_flag = 1
			AND a.dining_date = ?
			AND a.tenant_code = ?
	) a
		INNER JOIN (
			SELECT *
			FROM JSON_TABLE(?,'$[*]'
				COLUMNS (
					region_id bigint PATH '$.a' DEFAULT ERROR ON ERROR,
					org_id bigint PATH '$.b' DEFAULT ERROR ON ERROR,
					customer_id bigint PATH '$.c' DEFAULT ERROR ON ERROR
				)
			) b
		) b
		ON a.customer_id = b.customer_id
	GROUP BY b.region_id, b.org_id, a.meal_type_id
) a
ORDER BY a.region_id, a.org_id, a.meal_type_id

` ` `
