### ISSUE TITLE
druid 解析sql，如果sql中含有JSON_TABLE函数，会导致解析出来的sql错误

### ISSUE THREAD

**Issue by ocean-wll** [alibaba/druid#4916]
druid版本：1.2.11
原始sql：SELECT people.* 
FROM t1, 
     JSON_TABLE(json_col, '$.people[*]' COLUMNS (
                name VARCHAR(40)  PATH '$.name',
                address VARCHAR(100) PATH '$.address')
     ) people;
问题代码：com.alibaba.druid.sql.dialect.mysql.ast.expr.MySqlJSONTableExpr 的 toString()

<img width="877" alt="image" src="https://user-images.githubusercontent.com/38898167/187826263-68547d2a-3489-427b-803a-b21bebd1cc81.png">

问题描述：想通过druid解析sql代码实例如下：
`SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, dbType);
        final List<SQLStatement> sqlStatements = parser.parseStatementList();`

发现当sql中含有 JSON_TABLE 会导致解析后的sql缺少一个逗号，执行时直接抛异常。

**Comment by ocean-wll** [comment]
怀疑问题出现在 com.alibaba.druid.sql.dialect.mysql.visitor.MySqlOutputVisitor#visit(com.alibaba.druid.sql.dialect.mysql.ast.expr.MySqlJSONTableExpr)
<img width="619" alt="image" src="https://user-images.githubusercontent.com/38898167/187827890-e0a703be-5743-4e1e-9cf1-0288713e7b74.png">

**Comment by ocean-wll** [comment]
修改代码以后输出正确
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/38898167/187829904-c6b40ce8-9a89-4c57-9e97-b33353eff90d.png">

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.12
druid-1.2.12版本已发布，请帮忙用新版本验证
