### ISSUE TITLE
当使用Statement不同sql执行多次execute方法，sql监控只会有一条sql记录

### ISSUE THREAD

**Issue by huangguangshan** [alibaba/druid#4921]
问题说明：当使用Statement不同sql执行多次execute方法，sql监控只会有一条sql记录。伪代码如下：
Connection connection = dataSource.getConnection();
Statement stmt= connection.createStatement();
stmt.execute("create table account0(accno varchar(20),customer varchar(30),balance int)");
stmt.execute("insert into account0 values('20','user1',9)");
stmt.close();
connection.close();
此时sql监控只有create语句的sql。但是执行数、执行时间等都会进行相应的累加。

**Comment by huangguangshan** [comment]
附上该问题修复pr链接 https://github.com/alibaba/druid/pull/4922

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.12
druid-1.2.12版本已发布，请帮忙用新版本验证
