### ISSUE TITLE
com.alibaba.druid.util.JdbcUtils中能否增加openGauss驱动？

### ISSUE THREAD

**Issue by nullMoneyException** [alibaba/druid#4923]
com.alibaba.druid.util.JdbcUtils类中getDriverClassName方法能否增加 jdbc:opengauss 驱动？
如不能，能否在433行中 rawUrl.startsWith("jdbc:postgresql:") 后加 ‘’‘ || rawUrl.startsWith("jdbc:opengauss:") ’‘’？

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.12
druid-1.2.12版本已发布，请帮忙用新版本验证
