### ISSUE TITLE
druid是否有参数控制连接的最大生存时间

### ISSUE THREAD

**Issue by ruanyg** [alibaba/druid#4924]
如题，请问druid是否有参数控制连接的最大生存时间，类似hikariCP的maxLifetime参数（https://github.com/brettwooldridge/HikariCP/blob/HikariCP-3.4.5/README.md）。

找了下druid有个类似参数 maxEvictableIdleTimeMillis ，但是该参数以idle时间为依据，也就是说如果某条连接存活了很久但是最近有访问过就不会被从连接池中移除，这种情况下如果连接的是数据库代理（无状态集群），则在数据库代理做升配等运维操作时会有残留连接导致运维操作不平滑。

**Comment by kimmking** [comment]
phyTimeoutMillis
