### ISSUE TITLE
用druid连接Postgresql刷新物化视图，刷新不了

### ISSUE THREAD

**Issue by shenQQQ** [alibaba/druid#4931]
Caused by: java.sql.SQLException: sql injection violation, dbType postgresql, druid-version 1.2.4, class com.alibaba.druid.sql.ast.statement.SQLRefreshMaterializedViewStatement not allow : refresh materialized view <table_name>

如图，我该怎么做？

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.13
问题已修复，请用新版本

**Comment by shenQQQ** [comment]
> https://github.com/alibaba/druid/releases/tag/1.2.13 问题已修复，请用新版本

换了版本还是提示有注入风险。我是配合mybatis使用的druid，把物化视图刷新语句作为update语句来使用的。请问我是需要额外进行一些配置么？

org.springframework.jdbc.UncategorizedSQLException: 
### Error updating database.  Cause: java.sql.SQLException: sql injection violation, dbType postgresql, druid-version 1.2.13, class com.alibaba.druid.sql.ast.statement.SQLRefreshMaterializedViewStatement not allow : REFRESH MATERIALIZED VIEW <table_name>


@Mapper
public interface XXXMapper {

    @Update("REFRESH MATERIALIZED VIEW <table_name>")
    void refreshMaterialzedView();
}
