### ISSUE TITLE
整合ShardingSphere-jdbc-5.2.0读写分离报错，用默认的hikari就ok

### ISSUE THREAD

**Issue by Ryoui** [alibaba/druid#4935]
demo版本依赖：
`    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <spring-boot.version>2.4.13</spring-boot.version>
        <mybatis-spring-boot-starter.version>2.2.2</mybatis-spring-boot-starter.version>
        <shardingsphere.version>5.2.0</shardingsphere.version>
        <mapper-spring-boot-starter.version>4.2.1</mapper-spring-boot-starter.version>
        <druid-spring-boot-starter.version>1.2.12</druid-spring-boot-starter.version>
    </properties>`
错误信息：
`2022-09-15 16:27:38.828  INFO 19320 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2022-09-15 16:27:38.861  INFO 19320 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-09-15 16:27:38.880 ERROR 19320 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field xxxMapper in com.example.rws.impl.xxxServiceImpl required a bean of type
 'com.example.rws.mybatis.mapper.xxxMapper' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'com.example.rws.mybatis.mapper.xxxMapper' in your configuration.

Disconnected from the target VM, address: '127.0.0.1:50089', transport: 'socket'

Process finished with exit code 1`
上面错误就只是变更了数据源配置，其他配置都没变更。
demo读写分离配置：

> `# 模式配置
spring.shardingsphere.mode.type=Standalone

# 配置真实数据源
spring.shardingsphere.datasource.names=write_ds,read_ds_01

# 配置写库数据源
spring.shardingsphere.datasource.write_ds.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.write_ds.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.write_ds.url=jdbc:mysql://localhost:3306/rws?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useOldAliasMetadataBehavior=true
spring.shardingsphere.datasource.write_ds.username=root
spring.shardingsphere.datasource.write_ds.password=skaPG12MXHxn08Il5Rihfresn5eEFR3YYl8QHJkQcVv5PjWo8W6A29CisQj05SpKGQIcyZjjGnl7x373JCQ1vQ==
spring.shardingsphere.datasource.write_ds.filters=config
spring.shardingsphere.datasource.write_ds.connection-properties=config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALQ2TLFIdjackJNuP8XT+pZYSzZ39W4uXC66pinoK2tT0cQQysWyEJI2CtBQoeLDn2V/J1TmvyaXJcvLlhMm9O8CAwEAAQ==
# 配置读库数据源
spring.shardingsphere.datasource.read_ds_01.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.read_ds_01.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.read_ds_01.url=jdbc:mysql://localhost:3306/rws1?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useOldAliasMetadataBehavior=true
spring.shardingsphere.datasource.read_ds_01.username=root
spring.shardingsphere.datasource.read_ds_01.password=GqC7Q+9XpM3jKpEUoGTGNvUpTDsGBzGbDXLxsAu/7laiLhyZsuvlgZLfq6HdRhHGrKzLVWBEq9OBAiikgGDVeg==
spring.shardingsphere.datasource.read_ds_01.filters=config
spring.shardingsphere.datasource.read_ds_01.connection-properties=config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIqFxA41/oBimJuWZEFidePQMcGlCKI1GM+ibL/xtqlWkY1hDS+iJvc7YzR3O4/i9xZQ+yeTm7qb3N0YWSoTOdkCAwEAAQ==

# 读写分离
spring.shardingsphere.rules.readwrite-splitting.data-sources.readwrite_ds.static-strategy.write-data-source-name=write_ds
spring.shardingsphere.rules.readwrite-splitting.data-sources.readwrite_ds.static-strategy.read-data-source-names=read_ds_01
spring.shardingsphere.rules.readwrite-splitting.data-sources.readwrite_ds.load-balancer-name=round_robin
spring.shardingsphere.rules.readwrite-splitting.load-balancers.round_robin.type=ROUND_ROBIN`

**Comment by wenshao** [comment]
没用过shardingsphere，无法判断报错原因

**Comment by linghengqian** [comment]
- The reason is at https://github.com/apache/shardingsphere/issues/21211#issuecomment-1268667396 .  

- I don't think there is anything that can be done on the Druid side, this issue can be closed.
