### ISSUE TITLE
ClickHouseDriver

### ISSUE THREAD

**Issue by airywangym** [alibaba/druid#4943]
String CLICKHOUSE_DRIVER = "ru.yandex.clickhouse.ClickHouseDriver";
是否考虑更换为 clickHouse官方会在以后的版本中 将ru.yandex.clickhouse.ClickHouseDriver移除
String CLICKHOUSE_DRIVER = "com.clickhouse.jdbc.ClickHouseDriver";

**Comment by alexzhuustc** [comment]
同呼唤，辛苦考虑改一下
