### ISSUE TITLE
咨询：Oracle的socketTimeout和connectTimeout怎么设置？

### ISSUE THREAD

**Issue by reixuemin** [alibaba/druid#4952]
好像Oracle的没法通过url去设置socketTimeout和connectTimeout，是能在配置文件里面设置吗？

**Comment by mingyang66** [comment]
可以的，你可以看最新版本已经支持了

**Comment by reixuemin** [comment]
> 可以的，你可以看最新版本已经支持了

没看到怎么配，能教下我吗？

**Comment by mingyang66** [comment]
#建立连接时连接超时时间，默认：10000ms
spring.datasource.druid.connect-timeout=10000
#数据库操作超时时间，默认：10000ms
spring.datasource.druid.socket-timeout=10000

**Comment by reixuemin** [comment]
> #建立连接时连接超时时间，默认：10000ms spring.datasource.druid.connect-timeout=10000 #数据库操作超时时间，默认：10000ms spring.datasource.druid.socket-timeout=10000

我这么改过了，没效果，不知道是不是跟多数据源有关系，我当时的情况是升级到1.2.13后，如果sql查询时间超过60秒就提示socket time out，改了这个配置和
spring.datasource.dynamic.datasource.master.druid.connect-timeout=10000
spring.datasource.dynamic.datasource.master.druid.socket-timeout=10000
还是不行，回退到1.2.11就可以了

**Comment by mingyang66** [comment]
你看下你用的多数据源属性是不是直接关联到了DruidDataSource上，如果不是可能就是多数据源的问题

**Comment by kimmking** [comment]
跳过1.2.12版本即可。
