### ISSUE TITLE
Communications link failure 2 millisecords ago

### ISSUE THREAD

**Issue by vainhope** [alibaba/druid#4957]
![image](https://user-images.githubusercontent.com/18212930/195235047-6271b059-ac71-4ea8-8575-0d44855ab167.png)

数据库超时时间 正常设置
![image](https://user-images.githubusercontent.com/18212930/195235400-da3d074a-9c63-435f-9aec-3c04bc8c584d.png)

会偶现几秒connect不可用的情况

监控mysql的processlist 发现 processlist 的time是正常更新的

druid的版本1.2.6

**Comment by kenshin614** [comment]
你的问题最后解决了吗？怎么解决的？
