### ISSUE TITLE
1.2.12加的 connectTimeout和socketTimeout无法通过配置文件配置么

### ISSUE THREAD

**Issue by muyiluop** [alibaba/druid#4973]
通过配置 druid.connectTimeout 和 druid.socketTimeout 发现没有生效

**Comment by ahgaoyong** [comment]
同问

**Comment by sunney2010** [comment]
是无法配置了。
反而之前能生效的，
1、URL配置，如：url: jdbc:mysql://127.0.0.1:3306/xxx?connectTimeout=3000&socketTimeout=6000
2、 在connectionProperties配置:如：connectionProperties： connectTimeout=3009;socketTimeout=6009
被默认值为10秒覆盖了。这是什么设计思路呢？

**Comment by ztzheng** [comment]
确实没生效，现在只能降到1.2.11，这样很难再支持。。

**Comment by lizongbo** [comment]
请使用最新版
