### ISSUE TITLE
腾讯 APIJSON 已支持 Druid 并提供 Demo 🎉

### ISSUE THREAD

**Issue by TommyLemon** [alibaba/druid#4975]
https://github.com/Tencent/APIJSON

Demo：
https://github.com/APIJSON/APIJSON-Demo/tree/master/APIJSON-Java-Server/APIJSONDemo-Druid

![](https://camo.githubusercontent.com/18a2e4aa3dde917ddf15cfc32768790b79ea9f332d3912a810fc77379cf3ed1a/68747470733a2f2f6f7363696d672e6f736368696e612e6e65742f6f73636e65742f75702d62626265633466633565646334373262653132376330326134663363643866346563322e4a504547)

![](https://raw.githubusercontent.com/TommyLemon/StaticResources/master/APIJSON/APIJSON_query_associate.gif)

![image](https://user-images.githubusercontent.com/5738175/197548793-43c68d81-0ef3-49d6-8beb-83be88f4971b.png)

![image](https://raw.githubusercontent.com/TommyLemon/StaticResources/master/APIJSON/APIJSON_query_summary.gif)

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/5738175/197549231-d6042022-c360-4462-b3a2-0c5a805cd1a4.png">

![image](https://user-images.githubusercontent.com/5738175/197549465-0c092f7d-6060-4f45-9ae5-042aaa3650e9.png)

**Comment by wenshao** [comment]
👍🏻

**Comment by TommyLemon** [comment]
另外 APIJSON 也是基于温绍另一个著名开源项目 FASTJSON 序列化和反序列化 JSON 实现的，感谢温绍辛苦开源和多年维护的项目~

**Comment by kimmking** [comment]
1+1 > 2
