### ISSUE TITLE
WallFilter配置支持国产化数据库-示例：达梦

### ISSUE THREAD

**Issue by yxd179** [alibaba/druid#4977]

**Comment by kimmking** [comment]
see https://github.com/alibaba/druid/issues/2150

**Comment by yxd179** [comment]
spring:
    druid:
    filters: stat,wall,sfl4j
温馨提示* 可将wall不做配置，或者拓展DbType.class中init方法，将DbType中dm做为switch中case项......

**Comment by yxd179** [comment]
DbType.class

**Comment by yxd179** [comment]
DbType.class
other(1L),
    jtds(2L),
    hsql(4L),
    db2(8L),
    postgresql(16L),
    sqlserver(32L),
    oracle(64L),
    mysql(128L),
    mariadb(256L),
    derby(512L),
    hive(1024L),
    h2(2048L),
    dm(4096L),
    kingbase(8192L),
    gbase(16384L),
    oceanbase(32768L),
    informix(65536L),
    odps(131072L),
    teradata(262144L),
    phoenix(524288L),
    edb(1048576L),
    kylin(2097152L),
    sqlite(4194304L),
    ads(8388608L),
    presto(16777216L),
    elastic_search(33554432L),
    hbase(67108864L),
    drds(134217728L),
    clickhouse(268435456L),
    blink(536870912L),
    antspark(1073741824L),
    oceanbase_oracle(-2147483648L),
    polardb(1L),
    ali_oracle(2L),
    mock(4L),
    sybase(8L),
    ingres(0L),
    cloudscape(0L),
    timesten(0L),
    as400(0L),
    sapdb(0L),
    kdb(0L),
    log4jdbc(0L),
    xugu(0L),
    firebirdsql(0L),
    JSQLConnect(0L),
    JTurbo(0L),
    interbase(0L),
    pointbase(0L),
    edbc(0L),
    mimer(0L);

WallFilter.class
public synchronized void init(DataSourceProxy dataSource) {
        if (dataSource == null) {
            LOG.error("dataSource should not be null");
        } else {
            if (this.dbTypeName == null || this.dbTypeName.trim().length() == 0) {
                if (dataSource.getDbType() != null) {
                    this.dbTypeName = dataSource.getDbType();
                } else {
                    this.dbTypeName = JdbcUtils.getDbType(dataSource.getRawJdbcUrl(), "");
                }
            }

            if (this.dbTypeName == null) {
                this.dbTypeName = JdbcUtils.getDbType(dataSource.getUrl(), (String)null);
            }

            DbType dbType = DbType.of(this.dbTypeName);
            switch(dbType) {
            case mysql:
            case oceanbase:
            case dm:
            case drds:
            case mariadb:
            case h2:
            case presto:
                if (this.config == null) {
                    this.config = new WallConfig("META-INF/druid/wall/mysql");
                }

                this.provider = new MySqlWallProvider(this.config);
                break;
            case oracle:
            case ali_oracle:
            case oceanbase_oracle:
                if (this.config == null) {
                    this.config = new WallConfig("META-INF/druid/wall/oracle");
                }

                this.provider = new OracleWallProvider(this.config);
                break;
            case sqlserver:
            case jtds:
                if (this.config == null) {
                    this.config = new WallConfig("META-INF/druid/wall/sqlserver");
                }

                this.provider = new SQLServerWallProvider(this.config);
                break;
            case postgresql:
            case edb:
            case polardb:
                if (this.config == null) {
                    this.config = new WallConfig("META-INF/druid/wall/postgres");
                }

                this.provider = new PGWallProvider(this.config);
                break;
            case db2:
                if (this.config == null) {
                    this.config = new WallConfig("META-INF/druid/wall/db2");
                }

                this.provider = new DB2WallProvider(this.config);
                break;
            case sqlite:
                if (this.config == null) {
                    this.config = new WallConfig("META-INF/druid/wall/sqlite");
                }

                this.provider = new SQLiteWallProvider(this.config);
                break;
            default:
                throw new IllegalStateException("dbType not support : " + dbType + ", url " + dataSource.getUrl());
            }

            this.provider.setName(dataSource.getName());
            this.inited = true;
        }
    }

**Comment by yxd179** [comment]
DbType.class
    dm(4096L);

WallFilter.class
public synchronized void init(DataSourceProxy dataSource) {
            ......
            switch(dbType) {
            case dm:
            ......
    }
}

**Comment by kimmking** [comment]
can you submit a PR for it?

**Comment by x403368945** [comment]
看 com.alibaba.druid.wall.WallFilter 源码中有SPI扩展

```
static WallProvider initWallProviderInternal(DataSourceProxy dataSource, String dbTypeName, WallConfig config) {
    // ....
    switch (dbType) {
        case oracle:
        case ali_oracle:
        case oceanbase_oracle:
            //case dm:
            if (config == null) {
                config = new WallConfig(OracleWallProvider.DEFAULT_CONFIG_DIR);
            }
            provider = new OracleWallProvider(config);
            break;
        // ....
        default:
            provider = initWallProviderWithSPI(dataSource, config, dbType);
            if (provider == null) {
                throw new IllegalStateException("dbType not support : " + dbType + ", url " + dataSource.getUrl());
            }
    }
    return provider;
}

static WallProvider initWallProviderWithSPI(DataSourceProxy dataSource, WallConfig config, DbType dbType) {
    List<WallProviderCreator> wallProviderCreatorList = new ArrayList<>();
    ServiceLoader<WallProviderCreator> providerCreators = ServiceLoader.load(WallProviderCreator.class);
    providerCreators.forEach((wallProviderCreator) -> {
        wallProviderCreatorList.add(wallProviderCreator);
    });
    //sort wallProviderCreatorList
    Collections.sort(wallProviderCreatorList, (o1, o2) -> {
        return Integer.compare(o1.getOrder(), o2.getOrder());
    });
    for (WallProviderCreator providerCreator : providerCreators) {
        WallProvider wallProvider = providerCreator.createWallConfig(dataSource, config, dbType);
        if (wallProvider != null) {
            LOG.debug("use wallProvider " + wallProvider.getClass().getName() + " from " + providerCreator.getClass().getName());
            return wallProvider;
        }
    }
    return null;
}
```

SPI文件：src/main/resources/META-INF/services/com.alibaba.druid.wall.WallProviderCreator  内容，指向自定义扩展：
`druid.wall.DmWallProviderCreator`

druid.wall.DmWallProviderCreator.java 代码：
```
package druid.wall;

import com.alibaba.druid.DbType;
import com.alibaba.druid.proxy.jdbc.DataSourceProxy;
import com.alibaba.druid.wall.WallConfig;
import com.alibaba.druid.wall.WallProvider;
import com.alibaba.druid.wall.WallProviderCreator;
import com.alibaba.druid.wall.spi.OracleWallProvider;

import java.util.Objects;

/**
 * 达梦SQL防火墙
 */
public class DmWallProviderCreator implements WallProviderCreator {

    @Override
    public int getOrder() {
        return 100;
    }

    @Override
    public WallProvider createWallConfig(DataSourceProxy dataSource, WallConfig config, DbType dbType) {
        if (Objects.equals(DbType.dm, dbType)) {
            if (config == null) {
                config = new WallConfig(OracleWallProvider.DEFAULT_CONFIG_DIR);
            }
            return new OracleWallProvider(config);
        }
        return null;
    }
}
```
