### ISSUE TITLE
druid1.2.6+ojdbc19.14.0.0循环执行同一条sql报java.sql.SQLException: 关闭的语句

### ISSUE THREAD

**Issue by sixlei** [alibaba/druid#4980]
测试用例：
`@Test
public void testQuery() throws SQLException, InterruptedException {
DruidDataSource ds = new DruidDataSource();
ds.setDriverClassName("oracle.jdbc.driver.OracleDriver");
ds.setUrl("jdbc:oracle:thin:@127.0.0.1:1521/orcl");
ds.setUsername("test");
ds.setPassword("test");

    ds.setDriverClassLoader(ClassLoader.getSystemClassLoader());
    ds.setInitialSize(5);
    ds.setMaxActive(30);
    ds.setMinIdle(5);
    ds.setMaxWait(5000);
    ds.setTimeBetweenEvictionRunsMillis(120000);
    ds.setMinEvictableIdleTimeMillis(300000);
    ds.setTestWhileIdle(true);
    ds.setTestOnBorrow(false);
    ds.setPoolPreparedStatements(true);
    ds.setMaxPoolPreparedStatementPerConnectionSize(20);
    ds.setValidationQuery("select sysdate from dual");
    ds.setDefaultAutoCommit(true);

    while (true) {
        DruidPooledConnection connection = null;
        boolean originalAutoCommit = false;
        try {
            connection = ds.getConnection();
            originalAutoCommit = connection.getAutoCommit();
            connection.setAutoCommit(false);
            String sql = "SELECT lock_key,lock_value,expire FROM distributed_lock WHERE lock_key = ? FOR UPDATE";
            try (PreparedStatement pst = connection.prepareStatement(sql)) {
                pst.setString(1, "AsyncCommitting");
                ResultSet resultSet = pst.executeQuery();
                if (resultSet.next()) {
                    DistributedLockDO distributedLock = new DistributedLockDO();
                    distributedLock.setExpireTime(resultSet.getLong(ServerTableColumnsName.DISTRIBUTED_LOCK_EXPIRE));
                    distributedLock.setLockValue(resultSet.getString(ServerTableColumnsName.DISTRIBUTED_LOCK_VALUE));
                    distributedLock.setLockKey("AsyncCommitting");
                    System.out.println(distributedLock);
                }
            }
            connection.commit();
        } catch (Exception e) {
            LOGGER.error("execute acquire lock failure, key is: {}", "AsyncCommitting", e);
            try {
                if (connection != null) {
                    connection.rollback();
                }
            } catch (SQLException ex) {
                LOGGER.warn("rollback fail because of {}", ex.getMessage(), ex);
            }
        } finally {
            try {
                if (originalAutoCommit) {
                    connection.setAutoCommit(true);
                }
                IOUtil.close(connection);
            } catch (SQLException ignore) {
            }
        }

        Thread.sleep(1000);
    }

}`
报错：
java.sql.SQLException: 关闭的语句
	at oracle.jdbc.driver.OracleClosedStatement.exitImplicitCacheToActive(OracleClosedStatement.java:2957)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.exitImplicitCacheToActive(OraclePreparedStatementWrapper.java:1249)
	at com.alibaba.druid.util.OracleUtils.exitImplicitCacheToActive(OracleUtils.java:94)
	at com.alibaba.druid.pool.PreparedStatementPool.get(PreparedStatementPool.java:66)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:361)

给数据源配置useOracleImplicitCache为false是可以跳过statement的缓存的，但是不知道这个参数有没有什么其他影响，文档里也没找到。

**Comment by kimmking** [comment]
你分析的对，缓存的pstmt，导致之前的已经关闭了。
