### ISSUE TITLE
1.2.12加的 connectTimeout和socketTimeout配置无效

### ISSUE THREAD

**Issue by sunney2010** [alibaba/druid#4982]
自从1.2.12加的 connectTimeout和socketTimeout配置两个参数后。
connectTimeout和socketTimeout两个参数配置已无效了。之前 的配置方式有两种：
1、URL配置，如：url: jdbc:mysql://127.0.0.1:3306/xxx?connectTimeout=3000&socketTimeout=6000
2、 在connectionProperties配置:如：connectionProperties： connectTimeout=3009;socketTimeout=6009

现在配置都被：connectTimeout和socketTimeout默认值为10秒覆盖了。
![druid](https://user-images.githubusercontent.com/3646000/199062762-a5b61494-ebc1-419a-b784-5f447eac8688.png)

connectionProperties配置被默认值为10秒覆盖了。
![druid1](https://user-images.githubusercontent.com/3646000/199063704-02cde597-37ce-431e-9273-9df9cd6ef1a8.png)

URL配置也没有生效。

这样设计也太不合理了？

**Comment by wenshao** [comment]
确实是不对，会在下个版本中修复

**Comment by sunney2010** [comment]
建议connectTimeout和socketTimeout配置生效的优先级为：
connectionProperties>URL>默认值10秒。
