### ISSUE TITLE
打印的可执行SQL, 时间格式等字段缺少",无法直接在数据库的命令行直接执行

### ISSUE THREAD

**Issue by fengdh23** [alibaba/druid#4985]
select * from t where create_time >= 2022-03-15T13:15:30 and create_time <= 2022-04-02T13:15:30)
期望的输出是：
select * from t where create_time >= '2022-03-15T13:15:30' and 'create_time <= 2022-04-02T13:15:30')

**Comment by hhive** [comment]
> select * from t where create_time >= 2022-03-15T13:15:30 and create_time <= 2022-04-02T13:15:30) 期望的输出是： select * from t where create_time >= '2022-03-15T13:15:30' and 'create_time <= 2022-04-02T13:15:30')

你好，我找了很多资料都只能把sql和参数分开打印，可以请问下这样合并打印要怎么样配置吗

**Comment by wenshao** [comment]
参数类型是什么？

**Comment by llddy** [comment]
> select * from t where create_time >= 2022-03-15T13:15:30 and create_time <= 2022-04-02T13:15:30) 期望的输出是： select * from t where create_time >= '2022-03-15T13:15:30' and 'create_time <= 2022-04-02T13:15:30')

不应该是这个吗？
select * from t where create_time >= '2022-03-15T13:15:30' and **create_time <= '2022-04-02T13:15:30'**)

**Comment by lizongbo** [comment]
示例sql和期望效果都是错的

测试sql
``
 String sql="select * from t where create_time >= '2022-03-15T13:15:30' and create_time <= '2022-04-02T13:15:30' ";
``

测试结果：
```
mysql生成的sql===SELECT *
FROM t
WHERE create_time >= '2022-03-15T13:15:30'
	AND create_time <= '2022-04-02T13:15:30'
```
