### ISSUE TITLE
参数socketTimeout在postgresql和oracle表现不一致

### ISSUE THREAD

**Issue by aolaog** [alibaba/druid#4989]
在设置connectTimeout参数为10000ms的情况下，socketTimeout在postgresql上单位是秒:
       if (connectTimeout > 0) {
            if (isMySql) {
                if (connectTimeoutStr == null) {
                    connectTimeoutStr = Integer.toString(connectTimeout);
                }

                physicalConnectProperties.put("connectTimeout", connectTimeoutStr);
            } else if (isOracle) {
                if (connectTimeoutStr == null) {
                    connectTimeoutStr = Integer.toString(connectTimeout);
                }

                physicalConnectProperties.put("oracle.net.CONNECT_TIMEOUT", connectTimeoutStr);  //这里是毫秒
            } else if (driver != null && "org.postgresql.Driver".equals(driver.getClass().getName())) {
                if (connectTimeoutStr == null) {
                    connectTimeoutStr = Integer.toString(connectTimeout);
                }
                physicalConnectProperties.put("loginTimeout", connectTimeoutStr);

                if (socketTimeoutSr == null) {
                    socketTimeoutSr = Integer.toString(socketTimeout);
                }
                physicalConnectProperties.put("socketTimeout", socketTimeoutSr);  //这里单位是秒
            }
        }
    而这里设置Connection的超时时间时，这里是毫秒，但用的都是socketTimeout
    if (socketTimeout > 0 && !netTimeoutError) {
                try {
                    conn.setNetworkTimeout(netTimeoutExecutor, socketTimeout);
                } catch (SQLFeatureNotSupportedException | AbstractMethodError e) {
                    netTimeoutError = true;
                } catch (Exception ignored) {
                    // ignored
                }
            }
    这样的话在postgresql上其参数含义就会有问题，导致设置超时时间为3600秒时，postgresql上会报错。

**Comment by kimmking** [comment]
fixed now: https://github.com/alibaba/druid/commit/06b8ac173a10ce4ff9b12824de4165ae4afe4947
