### ISSUE TITLE
springboot3.0已知bug

### ISSUE THREAD

**Issue by jiangqiang1996** [alibaba/druid#5000]
1. 之前有人提过的，druid的监控页面不支持jakarta。[https://github.com/alibaba/druid/issues/4839](https://github.com/alibaba/druid/issues/4839) 我之前在fastjson2的时候也提过这个问题，高版本的javaee接口包名改了。javax都改成了jakarta。
2. 最近springboot发布的3.0.0-SNAPSHOT版本，密码加密后没有解密。
我前不久一直使用的是springboot的3.0.0-M4版本，不开启监控页面是可以正常使用的。但是我今天升级到3.0.0-SNAPSHOT之后，发现启动项目一直报错数据库认证错误。因为我开启了druid的数据库密码加密功能，所以我猜想并没有解密，然后我通过使用不同的springboot版本进行断点，发现password确实并没有解密。

**Comment by liangyuanpeng** [comment]
any update here?
