### ISSUE TITLE
SQLBinaryOperator 不支持IN 和NOT IN语法

### ISSUE THREAD

**Issue by ddna1021** [alibaba/druid#5016]
在解析SQL发现，NOT IN 语法无法被识别为二元操作符，查找源码：
https://github.com/alibaba/druid/blob/master/core/src/main/java/com/alibaba/druid/sql/ast/expr/SQLBinaryOperator.java

发现确实没有支持改语法。

@wenshao ，请大佬看看

**Comment by TalentSSS** [comment]
Hi，这边构造了下面的例子看了下，使用 **`IN`和`NOT IN`操作符的表达式是作为 `SQLInListExpr` 来进行解析的**
```SQL
SELECT id, name, age WHERE age > 18 AND name NOT IN ('Alan', 'Bob', 'Cindy')
```
我们解析该语句，打开解析后的结构可以看到
![image](https://user-images.githubusercontent.com/13519606/206428117-34536d1f-7773-4d89-91d7-2f23e3d2e461.png)
这里的`name NOT IN ('Alan', 'Bob', 'Cindy')`构成了一个 `SQLInListExpr` 表达式，所以没必要把它们添加到`SQLBinaryOperator`中

**Comment by ddna1021** [comment]
收到 感谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月08日 18:58 |
| 收件人 | ***@***.***> |
| 抄送至 | Fan ***@***.***>***@***.***> |
| 主题 | Re: [alibaba/druid] SQLBinaryOperator 不支持IN 和NOT IN语法 (Issue #5016) |

Hi，这边构造了下面的例子看了下，使用 IN和NOT IN操作符的表达式是作为 SQLInListExpr 来进行解析的

SELECT id, name, age WHERE age >18AND name NOT IN ('Alan', 'Bob', 'Cindy')

我们解析该语句，打开解析后的结构可以看到

这里的name NOT IN ('Alan', 'Bob', 'Cindy')构成了一个 SQLInListExpr 表达式，所以没必要把它们添加到SQLBinaryOperator中
