### ISSUE TITLE
Throw exception 'failed to unregister' when tomcat shutdown.

### ISSUE THREAD

**Issue by qiuxiaoj** [alibaba/druid#502]
registered the JDBC driver [com.alibaba.druid.proxy.DruidDriver] but failed to unregister it when the web application was stopped. 
To prevent a memory leak, the JDBC Driver has been forcibly unregistered.

**Comment by asd1245dss** [comment]
实现ServletContextListener,然后再contextDestroyed()方法中添加如下代码：
Enumeration drivers = DriverManager.getDrivers();
while (drivers.hasMoreElements()) {
Driver driver = drivers.nextElement();
try {
DriverManager.deregisterDriver(driver);
logger.info(String.format("deregistering jdbc driver: %s", driver));
} catch (SQLException e) {
e.printStackTrace();
logger.error(String.format("deregistering jdbc driver: %s", driver));
}
}
最后在web.xml中注册自己的监听器，问题解决。
