### ISSUE TITLE
Druid Spring Boot Starter 在SpringBoot3.0.0中无法使用

### ISSUE THREAD

**Issue by elonehoo** [alibaba/druid#5022]
好像是因为SpringBoot切换了一些版本依赖，将**javax**切换到了**jakarta**

**Comment by jboonb77** [comment]
需要多久修复，现在急用学习

**Comment by elonehoo** [comment]
这是一个开源项目，如果你非常着急可以自己去修复，提一个PR，我想 druid 的团队成员也会非常高兴的

**Comment by wenshao** [comment]
12月底或者1月份处理spring 3.x的问题，最近在忙fastjson2，这个要晚些才处理

**Comment by Deathef** [comment]
@wenshao 这个是打算新开一个分支弄吗，还是说在现在的分支上Spring Boot 2和Spring Boot 3同时兼容？

**Comment by Deathef** [comment]
Spring Boot 3 主要的三个点就是

+ 使用 Jakarta EE 10， 这个比较好处理的，替换下包引入的路径就好了

+ 修改了自动装配的SPI结构，这个改起来也不麻烦，修改下`Druid Spring Boot Starter`这个模块就好了

+ GraalVM，这个是一个比较麻烦的改动，我用Druid没有跑通，应该是要参考做一些处理[GraalVM Native Image Support](https://docs.spring.io/spring-boot/docs/3.0.0/reference/html/native-image.html#native-image.advanced)

**Comment by wenshao** [comment]
@Deathef 做不到兼容的，增加一个新的module，元旦后看吧

**Comment by vanlin** [comment]
> Spring Boot 3 主要的三个点就是
> 
> * 使用 Jakarta EE 10， 这个比较好处理的，替换下包引入的路径就好了
> * 修改了自动装配的SPI结构，这个改起来也不麻烦，修改下`Druid Spring Boot Starter`这个模块就好了
> * GraalVM，这个是一个比较麻烦的改动，我用Druid没有跑通，应该是要参考做一些处理[GraalVM Native Image Support](https://docs.spring.io/spring-boot/docs/3.0.0/reference/html/native-image.html#native-image.advanced)

个人目前也是手动处理了前两步，先打个私有包用着，建议开个分支先支持起来

**Comment by AmbitionLover** [comment]
1.2.18 druid-spring-boot-3-starter
