### ISSUE TITLE
durid not suppoet jdk17

### ISSUE THREAD

**Issue by chansanya** [alibaba/druid#5046]
i want use jdk17 ,will druid have a support plan in the follow-up?

**Comment by chansanya** [comment]
![fe334b37f6a0fa1ba847fb535dc90f8](https://user-images.githubusercontent.com/47585031/207483953-ff452cb9-11ea-4a5c-a5c4-c28fece2b2c6.png)

**Comment by Deathef** [comment]
Java 17 can also use the `javax.servlet` package, you just need to add the 'javax.servlet:javax.servlet-api' dependency package. If you want to use Spring Boot 3, that won't work. You can use it on Spring Boot 2.6.x.

**Comment by ahgaoyong** [comment]
中国人讲中国话, 我看你是中文的注释?

你这个包是servlet相关的吧, 跟druid没有任何关系啊, 人家是数据库连接池啊

**Comment by Deathef** [comment]
@ahgaoyong 他这个注释应该是Druid自己的注释，他指的是Druid的那几个监控页面的包。
Spring Boot 3 主要的改动之一就是升级到Jakarta EE 10，如果他想在Spring Boot 3上面使用的话确实会存在包找不到的问题。

**Comment by elonehoo** [comment]
#5022
