### ISSUE TITLE
Is there any plan to support Spring Boot 3 ?

### ISSUE THREAD

**Issue by Deathef** [alibaba/druid#5048]
Spring Boot 3 has been GA, is there a plan to support it?

**Comment by Deathef** [comment]
Major Spring Boot 3 change: Support  for Jakarta EE 10 with an EE 9 baseline. 
+ There are a lot of packages that need to be replaced from `javax.servlet.*` to `jakarta.servlet.*`.
+ The SpringBoot auto configuration needs to be modified.

**Comment by elonehoo** [comment]
#5022
