### ISSUE TITLE
Socket read timed out

### ISSUE THREAD

**Issue by pizriw** [alibaba/druid#5050]
升级1.2.14后  oracle 经常报{conn-310006} discard java.sql.SQLRecoverableException: IO Error: Socket read timed out  怎么回事呢  
是需要设置什么么 

环境 ：springboot 2.7.1  + jdk17

**Comment by HSHunterR** [comment]
问下怎么解决的

**Comment by hellozhaoxudong** [comment]
druid.setSocketTimeout(18000000);
druid.setConnectTimeout(18000000);
