### ISSUE TITLE
druid一直加载不到MysqlConnection，导致CPU 100%

### ISSUE THREAD

**Issue by BugCui** [alibaba/druid#5060]
druid版本：1.2.8
mysql-connector-java：6.0.3
OS: linux

我的项目每次运行，都会调用druid的com.alibaba.druid.util.MySqlUtils#getLastPacketReceivedTimeMs
方法，然而由于我用的JDBC驱动为6.0.3，找不到
"com.mysql.jdbc.MySQLConnection"
"com.mysql.cj.MysqlConnection"
这两个类，导致每次类加载都失败，最终造成CPU 100%
（6.0.3中类路径为：com.mysql.cj.api.MysqlConnection，带有api）

我专门写了一篇文章记录整个事件的排查过程：
https://blog.csdn.net/csp_6666/article/details/128279538?spm=1001.2014.3001.5501

 ```
<dependency>
          <groupId>mysql</groupId>
          <artifactId>mysql-connector-java</artifactId>
          <version>6.0.3</version>
  </dependency>
  <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid</artifactId>
            <version>1.2.8</version>
   </dependency>
```

**Comment by wenshao** [comment]
升级下驱动吧，比如最新版本的8.0.31，坚持用6.0.3版本的原因？

**Comment by BugCui** [comment]
> 升级下驱动吧，比如最新版本的8.0.31，坚持用6.0.3版本的原因？

是的，我们是靠升级驱动解决的。
但我认为这块druid最好能做下兼容，以防其他人像我这种情况遇到同样的问题。

**Comment by newboy2004** [comment]
please assign to me   and    create new branch to  fix bug on the tag 1.2.15 ?

**Comment by kimmking** [comment]
@newboy2004 it is your change now
