### ISSUE TITLE
使用SQLUtils.parseStatements时，不能识别多条create trigger 语句

### ISSUE THREAD

**Issue by zhangmx97** [alibaba/druid#5065]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/29156288/210777905-95b2f422-928b-47b2-8f09-743c34b72d36.png">

结果：
<img width="963" alt="image" src="https://user-images.githubusercontent.com/29156288/210778060-5321adc7-9cc3-4117-913d-6c48918479f8.png">

测试代码
`List<SQLStatement> sqlStatements =  SQLUtils.parseStatements(`
               ` "CREATE TRIGGER `tidff` BEFORE UPDATE ON `test` FOR EACH ROW update test set _time = '3333';\n" +`
                      `  "CREATE TRIGGER `triger1` AFTER INSERT ON `test` FOR EACH ROW update test set _time = '2222';\n",`
               ` JdbcUtils.MYSQL);`

**Comment by lizongbo** [comment]
根据 https://github.com/alibaba/druid/pull/5354/
已经优化解析逻辑
