### ISSUE TITLE
testConnectionInternal method Bug

### ISSUE THREAD

**Issue by ylq5126** [alibaba/druid#5074]
druid version: 1.2.15
![image](https://user-images.githubusercontent.com/9344601/211774141-6db6bfe0-0d82-4a05-8e24-9e20a76dffcb.png)
此处的校验空闲链接时长是不是应该取
minEvictableIdleTimeMillis 而不是 timeBetweenEvictionRunsMillis

**Comment by kimmking** [comment]
先说结论，这里没问题。

- [x ] timeBetweenEvictionRunsMillis 是 60s
- [x] minEvictableIdleTimeMillis 是 半小时
- [x] maxEvictableIdleTimeMillis  是7小时

常规情况下，判断的idle是 60s（比如testWhileIdle也是这个值）。
minEvictableIdleTimeMillis过长，现在很多云环境，默认idle 15分钟的tcp连接会被SLB干掉。
7小时明显是为了mysql默认的那个8小时inactive设置的。

连接是数据库最宝贵的资源，我们尽量用保守的策略去处理连接。所以60s没有活跃的，可以去掉重建了。

实际上，我们有时候也会用phyTimeoutMillis和phyMaxUseCount控制一定时间或使用次数强制回收连接，以保证所有连接的可用性，以及数据库的内存有机会回收。

**Comment by ylq5126** [comment]
> 先说结论，这里没问题。
> 
> * [x]  timeBetweenEvictionRunsMillis 是 60s
> * [x]  minEvictableIdleTimeMillis 是 半小时
> * [x]  maxEvictableIdleTimeMillis  是7小时
> 
> 常规情况下，判断的idle是 60s（比如testWhileIdle也是这个值）。 minEvictableIdleTimeMillis过长，现在很多云环境，默认idle 15分钟的tcp连接会被SLB干掉。 7小时明显是为了mysql默认的那个8小时inactive设置的。
> 
> 连接是数据库最宝贵的资源，我们尽量用保守的策略去处理连接。所以60s没有活跃的，可以去掉重建了。
> 
> 实际上，我们有时候也会用phyTimeoutMillis和phyMaxUseCount控制一定时间或使用次数强制回收连接，以保证所有连接的可用性，以及数据库的内存有机会回收。

好的，如果我要保证链接可用性的话，minEvictableIdleTimeMillis 这个值要适当调低对吧
