### ISSUE TITLE
是否支持时序数据库比如 influxDB

### ISSUE THREAD

**Issue by ZhenChen008** [alibaba/druid#5075]
请问 Druid连接池是否支持时序数据库比如 influxDB，如果可以还请指明一下链接，谢谢！
I would like to ask whether Druid connection pool supports Time Series database(TSDB) , such as influxDB. 
If so, please give a link. Thank you!

**Comment by kimmking** [comment]
@ZhenChen008 thanks for your suggestion, and now we have no plan to integration with influxDB or other TSDB. If you are insterested in this feature, can you submit some codes to implement it. When you start this wonderful job, any question will be to discuss here.
