### ISSUE TITLE
Druid是否支持SpringBoot3.0?

### ISSUE THREAD

**Issue by kervin521** [alibaba/druid#5076]
WebStatFilter还是实现javax.servlet下的Filter接口，支持SpringBoot3.0需要支持jakarta.servlet下的Filter

**Comment by ChinaFLTV** [comment]
+1我也遇到了

**Comment by wenshao** [comment]
计划在2月底前发布版本支持

**Comment by 14772** [comment]
> 

请问现在支持了吗

**Comment by kervin521** [comment]
@ivancxj @14772 已经支持了

```pom
<dependency>
			<groupId>com.alibaba.fastjson2</groupId>
		 	<artifactId>fastjson2-extension-spring6</artifactId>
</dependency>
```

**Comment by lizongbo** [comment]
请升级使用 1.2.20

// https://mvnrepository.com/artifact/com.alibaba/druid-spring-boot-3-starter
implementation 'com.alibaba:druid-spring-boot-3-starter:1.2.20'
