### ISSUE TITLE
SQLServer不支持socketTimeout

### ISSUE THREAD

**Issue by ztzheng** [alibaba/druid#5079]
查询超过10s超时，这个配置从1.2.12开始设置为默认值，源码没有SQLServer的判断

![image](https://user-images.githubusercontent.com/8120919/213860178-c4c4bda3-60b0-4e64-af0f-770d740776bd.png)

**Comment by kimmking** [comment]
I will process it later.

**Comment by Wincher** [comment]
I'd like to fix this, please assign it to me @kimmking

**Comment by kimmking** [comment]
it for you now. @Wincher

**Comment by kimmking** [comment]
fixed now: https://github.com/alibaba/druid/commit/a9d9803dc86bdd32bc3634ceab948e2380e1acd9
