### ISSUE TITLE
Druid何时支持springboot3.0版本

### ISSUE THREAD

**Issue by 461796280** [alibaba/druid#5082]

**Comment by wenshao** [comment]
计划在2月底

**Comment by Deathef** [comment]
#5022

**Comment by lizongbo** [comment]
请升级使用 1.2.20

// https://mvnrepository.com/artifact/com.alibaba/druid-spring-boot-3-starter
implementation 'com.alibaba:druid-spring-boot-3-starter:1.2.20'
