### ISSUE TITLE
MySqlStatementParser 无法识别BEGIN开启事务的语法 

### ISSUE THREAD

**Issue by today-isaniceday** [alibaba/druid#5091]
begin和start transaction等价可以用于开启一个事务。官方语法说明：
https://dev.mysql.com/doc/refman/5.6/en/commit.html

当前最新版本的druid将begin解析为【begin...end】语法的一部分，而【begin...end】是存储过程中的语法和开启事务是两回事：
![image](https://user-images.githubusercontent.com/79831340/215981532-734c3fe9-3709-4ed7-b9ab-f49f631222a4.png)

复现代码

```
SQLStatementParser parser = new MySqlStatementParser("BEGIN");
List<SQLStatement> stmts = parser.parseStatementList();
```

期待修复

**Comment by zhanghuajieHIT** [comment]
这个问题，现在有什么方法规避吗？

**Comment by lizongbo** [comment]
```
@Test
    public void testBegin(){
        SQLStatementParser parser = new MySqlStatementParser("BEGIN");
        List<SQLStatement> stmts = parser.parseStatementList();
        System.out.println(stmts);
    }
```
执行结果：
[BEGIN ]

该问题已经解决。
