### ISSUE TITLE
1.2.4 ConcurrentModifyException

### ISSUE THREAD

**Issue by Eatin** [alibaba/druid#5093]
使用了druid1.2.4 版本，日志报错，ConcurrentModifyException 提示的是

 if (requireDiscard) {
            if (holder.statementTrace != null) {
                holder.lock.lock();
                try {
                    //报错代码ConcurrentModifyException 
                    for (Statement stmt : holder.statementTrace) {
                        JdbcUtils.close(stmt);
                    }
                } finally {
                    holder.lock.unlock();
                }
            }

            this.discardConnection(holder);
        }

以下是测试用的配置
maxWait=60000
timeBetweenEvictionRunsMillis=60000
minEvictableIdleTimeMillis=300000
validationQuery=SELECT 1 FROM DUAL
testWhileIdle=true
testOnBorrow=true
initialSize=1
maxActive=2

**Comment by kimmking** [comment]
麻烦发一下异常堆栈。
看了一下这里的代码，没发现有会并发修改的地方。

btw：testOnBorrow打开的时候，testWhileIdle为true无效。

**Comment by kimmking** [comment]
请升级最新版本，statementTrace的所有操作都加了锁。
