### ISSUE TITLE
ConnectTimeout 默认值不生效

### ISSUE THREAD

**Issue by xlofhappy** [alibaba/druid#5095]
在 DruidDataSource 的 init 方法中 ，
 if (connectTimeout == 0) {
       socketTimeout = DEFAULT_TIME_CONNECT_TIMEOUT_MILLIS;
}
当不设置 connectTimeout 属性时，是否有错误？

**Comment by kimmking** [comment]
https://github.com/alibaba/druid/blob/596e572d235ce678338775a81258927f8b9d49c5/core/src/main/java/com/alibaba/druid/pool/DruidAbstractDataSource.java#L126

If not set, the default value of 'int' type will be 0.

**Comment by scdhao** [comment]
得自己设置connectTimeout =-1避开bug了

**Comment by kimmking** [comment]
-1 means NEVER timeout. @scdhao
