### ISSUE TITLE
对于PostgreSQL，传递了错误的connectTimeout

### ISSUE THREAD

**Issue by xlofhappy** [alibaba/druid#5096]
在DruidAbstractDataSource中 的 createPhysicalConnection 方法中，
if (driver != null && "org.postgresql.Driver".equals(driver.getClass().getName())) {
                if (connectTimeoutStr == null) {
                    connectTimeoutStr = Integer.toString(connectTimeout);
                }
                physicalConnectProperties.put("loginTimeout", connectTimeoutStr);

                if (socketTimeoutSr == null) {
                    socketTimeoutSr = Integer.toString(socketTimeout);
                }
                physicalConnectProperties.put("socketTimeout", socketTimeoutSr);
            }
当数据库时 postgresql时，使用connectTimeout的值传递 loginTimeout 属性至 postgresql的Driver中，用以创建物理连接，但org.postgresql.Driver 中会将 loginTimeout认为是以秒单位，详见方法 Driver中的 private static long timeout(Properties props) 方法

**Comment by kimmking** [comment]
![image](https://user-images.githubusercontent.com/807508/219900397-c6b791b7-e31f-4951-8c36-e466055fee35.png)
You are right, from the README.md, loginTimeout/connectTimeout/socketTimeout are three different options of pg driver in seconds.

**Comment by kimmking** [comment]
there will be corrected by two steps:

- [ ] config three options with seconds in your application, and correct comments/docs in druid codes
- [ ] add a loginTimeout to set it and not use connectTimeout option

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.16
问题已修复，请用新版本

**Comment by kuguobing** [comment]
DruidDataSource::init()

 if (connectTimeout == 0) {
                socketTimeout = DEFAULT_TIME_CONNECT_TIMEOUT_MILLIS;
 }

这个怎么还没改？

**Comment by kimmking** [comment]
“Connection Timeout” is the correct option for SQLServer.

**Comment by lizongbo** [comment]
请使用 1.2.21验证

**Comment by DerrickRoseCode** [comment]
1.2.21 我的报错也还在

**Comment by kimmking** [comment]
pg的什么版本驱动，我记得之前修复过这个问题。

DerrickRoseCode ***@***.***> 于2024年10月23日周三 11:43写道：
