### ISSUE TITLE
版本1.2.15 能否加一个参数用于配置sql格式化后输出换行，不然第一行离得太远了

### ISSUE THREAD

**Issue by ahxClouds** [alibaba/druid#5097]
![image](https://user-images.githubusercontent.com/30315260/216780760-644eb121-c786-4f23-b6f0-44ef20408a40.png)
![image](https://user-images.githubusercontent.com/30315260/216780791-873952d9-248d-4d6f-b9bc-7ce1508d2316.png)

**Comment by kimmking** [comment]
you can resolve it by configuring your own layout with a crlf.
