### ISSUE TITLE
spring boot3.0自动配置方式变更，连接池无法自动导入

### ISSUE THREAD

**Issue by gstsgy** [alibaba/druid#5100]

**Comment by daenmax** [comment]
没明白您是什么意思，目前我测试，druid在springboot3上除了web监控页面无法使用外，其他均正常

**Comment by gstsgy** [comment]
> 没明白您是什么意思，目前我测试，druid在springboot3上除了web监控页面无法使用外，其他均正常
spring boot start 不能自动导入datasource，spring自动配置spi方式改变了

**Comment by gstsgy** [comment]
![image](https://user-images.githubusercontent.com/42596329/217249307-4fea733b-f54d-4fcf-9d39-a6a62374cc17.png)

**Comment by leifengyang** [comment]
是的。赶紧修补下吧。
1.  javax.servlet 全部迁移到  jakarta.servlet.http
2.  spring.factories 文件废弃了。请把 DruidDataSourceAutoConfigure 移到 META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports 中

**Comment by cnclsg** [comment]
为什么durid montior除数据源外的事务提交数都为0，在SpringBoot2.7.8平台

**Comment by Deathef** [comment]
#5022

**Comment by ShenFeng312** [comment]
> 是的。赶紧修补下吧。
> 
> 1. javax.servlet 全部迁移到  jakarta.servlet.http
> 2. spring.factories 文件废弃了。请把 DruidDataSourceAutoConfigure 移到 META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports 中

这个文件是向下兼容的

**Comment by kimmking** [comment]
Duplicated with #5022
