### ISSUE TITLE
请教一个问题，同一方法中，查询语句数量大于druid连接池最大连接数时，会出现连接泄露，有相应说明吗？

### ISSUE THREAD

**Issue by fate-stay-night** [alibaba/druid#5122]
请教一个问题，同一方法中，查询语句数量大于druid连接池最大连接数时，会出现连接泄露，有相应说明吗？

**Comment by kimmking** [comment]
如果存在这个问题，说明有bug。
建议：
1、把复现的情况做一个test case，这里共享一下。
2、或者，通过logAbandoned, removeAbandoned 进行排查。
