### ISSUE TITLE
sql解析create view语法问题

### ISSUE THREAD

**Issue by fizz-stack** [alibaba/druid#5124]
**druid版本：1.2.16**

### 测试代码：
```
String sql2="CREATE ALGORITHM=UNDEFINED " +
                "DEFINER=`root`@`%` " +
                "SQL SECURITY DEFINER VIEW `test_view` AS \n" +
                "select  `t1`.`US_USERID` AS `US_USERID`,  `t1`.`US_USERNAME` AS `US_USERNAME` from `test_userinfo` `t1`";
        SQLCreateViewStatement createViewStatement=(SQLCreateViewStatement) SQLUtils.parseSingleMysqlStatement(sql2);
        System.out.println(createViewStatement);
```

### 输出结果：
```
CREATE ALGORITHM = UNDEFINED
	DEFINER = '`root`'@'`%`'
	SQL SECURITY = DEFINER
	VIEW `test_view`
AS
SELECT `t1`.`US_USERID` AS `US_USERID`, `t1`.`US_USERNAME` AS `US_USERNAME`
FROM `test_userinfo` `t1`
```

### 问题：

- sql解析的结果是`sql security =`，但mysql中的 `sql security` 没有等号

### 其他发现：

- 这个[问题](https://github.com/alibaba/druid/issues/4229#issuecomment-864920969)似乎很早之前就存在了
- `com.alibaba.druid.sql.visitor.SQLASTOutputVisitor`下的`visit(SQLCreateViewStatement x)`方法存在`this.print0(this.ucase ? "SQL SECURITY = " : "sql security = ");`语句

**Comment by misszhangss** [comment]
@lizongbo 您好，我们目前也遇到了这个问题，  想问一下这个问题  咱们有规划在哪个版本解决吗

**Comment by lizongbo** [comment]
看了下mysql 官方语法，确实不应该是等号。
参考： https://dev.mysql.com/doc/refman/8.0/en/create-view.html

这个改动很小，我来提交个pr，然后找温少合并一下。
