### ISSUE TITLE
错误语法解析通过：mysql中select多个一个逗号竟可以解析通过

### ISSUE THREAD

**Issue by zhuwenda** [alibaba/druid#5140]
版本1.2.14，以下SQL的select多了一个逗号，可以解析通过，但在mysql8数据库中无法执行
```sql
select col1, from table1
```

执行结果如下图：

<img width="896" alt="image" src="https://user-images.githubusercontent.com/5311170/221763787-ede802b1-6fd9-4bb3-b7a5-e09e96899042.png">

这是正常的吗？

**Comment by kimmking** [comment]
it's a bug.
Can you submit a PR to fix it?

**Comment by newboy2004** [comment]
please assign it to me thanks
