### ISSUE TITLE
配置慢sql不生效

### ISSUE THREAD

**Issue by belindacpp** [alibaba/druid#5142]
我的properties添加的配置是：
spring.datasource.druid.filters=stat
spring.datasource.druid.filter.stat.enabled=true
spring.datasource.druid.filter.stat.log-slow-sql=true
spring.datasource.druid.filter.stat.db-type=mysql
spring.datasource.druid.filter.stat.slow-sql-millis=200

我的logback-spring.xml添加的配置是：
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/45474309/221802176-56a024e5-9c50-4f51-8dd4-03a959a27931.png">

启动项目后，sqlinfo.log没有相关的慢sql日志，请问大家还需要做什么配置吗，或者如何排查？感谢

**Comment by kimmking** [comment]
`spring.datasource.druid.filters=stat,log4j`
