### ISSUE TITLE
1.2.X版本，PG数据库url配置socketTimeout不起效

### ISSUE THREAD

**Issue by KelvinChung18** [alibaba/druid#5145]
配置信息：jdbc:postgresql://xxx/postgres?currentSchema=tyzk_tsk&stringtype=unspecified&reWriteBatchedInserts=true&connectTimeout=30&socketTimeout=600
，查询超过10s就会出现I/O报错，并提示 socket read time out

**Comment by kimmking** [comment]
明天我验证一下。

**Comment by kimmking** [comment]
connectTimeout=30&socketTimeout=600
这两个参数，你应该配置到连接池参数里，而不是jdbcUrl里。
