### ISSUE TITLE
17年bug fixed for testWhileIdle提交针对mysql抛弃链接的修改造成接口不断出现毛刺

### ISSUE THREAD

**Issue by yangcom01** [alibaba/druid#5148]
![image](https://user-images.githubusercontent.com/11738213/222426103-09648820-58f6-43f2-b32d-225c5a15c8d9.png)
![image](https://user-images.githubusercontent.com/11738213/222426213-e0fb5175-3768-4987-9fad-f91efb9fa7b0.png)
您好在17年的时候， 因testWhileIdle提交了两次代码， 增加了对mysql单独判断
（1） 有效（ping方法）且驱动为mysql, 如果当前时间距上次connection执行完sql的时间大于阈值时则discard

想咨询下：
（1）为什么要增加这段逻辑， 如果有效直接使用不就好了吗？
（2）对于平时链接活跃度低时， 存在大量链接消亡和创建，接口不断出现毛刺

**Comment by wenshao** [comment]
这个代码记得是为了诊断一个异常场景增加的代码，这个应该是不需要了。 @kimmking 也帮看下。

@yangcom01 你提个PR吧？

**Comment by yangcom01** [comment]
好滴， 非常感谢您~

**Comment by yangcom01** [comment]
好的，非常感谢百忙之中的快速回复，公司电脑不允许提交，下班后我用自己电脑提交下
再次感谢~&nbsp; 祝好~



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月3日(周五) 凌晨3:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/druid] 17年bug fixed for testWhileIdle提交针对mysql抛弃链接的修改造成接口不断出现毛刺 (Issue #5148)




 
这个代码记得是为了诊断一个异常场景增加的代码，这个应该是不需要了。 @kimmking 也帮看下。
 
@yangcom01 你提个PR吧？

**Comment by kimmking** [comment]
> 这个代码记得是为了诊断一个异常场景增加的代码，这个应该是不需要了。 @kimmking 也帮看下。
> 
> @yangcom01 你提个PR吧？

roger

**Comment by kimmking** [comment]
> 好的，非常感谢百忙之中的快速回复，公司电脑不允许提交，下班后我用自己电脑提交下 再次感谢~&nbsp; 祝好~
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年3月3日(周五) 凌晨3:55 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [alibaba/druid] 17年bug fixed for testWhileIdle提交针对mysql抛弃链接的修改造成接口不断出现毛刺 (Issue #5148) 这个代码记得是为了诊断一个异常场景增加的代码，这个应该是不需要了。 @kimmking 也帮看下。 @yangcom01 你提个PR吧？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

欢迎提交PR，然后关联这个issue id就可以了。比如 PR标题是 fix #5148

**Comment by yangcom01** [comment]
好滴，还有点收尾的事情。考虑了下，待我们理论论证充分，验证充分后就提，避免引入新问题或改的不合适给您们带来不必要麻烦~&nbsp; &nbsp;预计下周提，再次感谢哈~



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月4日(周六) 凌晨0:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/druid] 17年bug fixed for testWhileIdle提交针对mysql抛弃链接的修改造成接口不断出现毛刺 (Issue #5148)




  
好的，非常感谢百忙之中的快速回复，公司电脑不允许提交，下班后我用自己电脑提交下 再次感谢~&nbsp; 祝好~
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年3月3日(周五) 凌晨3:55 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [alibaba/druid] 17年bug fixed for testWhileIdle提交针对mysql抛弃链接的修改造成接口不断出现毛刺 (Issue #5148) 这个代码记得是为了诊断一个异常场景增加的代码，这个应该是不需要了。 @kimmking 也帮看下。 @yangcom01 你提个PR吧？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
欢迎提交PR，然后关联这个issue id就可以了。比如 PR标题是 fix #5148

**Comment by yangcom01** [comment]
您好，我们已论证并验证完， PR已提交， 麻烦空闲的时候帮忙审核下， 有问题随时沟通， 再次感谢哈~




------------------ Original ------------------
From:                                                                                                                        "棉花糖"                                                                                    ***@***.***&gt;;
Date:&nbsp;Sat, Mar 4, 2023 07:40 PM
***@***.******@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;回复：[alibaba/druid] 17年bug fixed for testWhileIdle提交针对mysql抛弃链接的修改造成接口不断出现毛刺 (Issue #5148)



好滴，还有点收尾的事情。考虑了下，待我们理论论证充分，验证充分后就提，避免引入新问题或改的不合适给您们带来不必要麻烦~&nbsp; &nbsp;预计下周提，再次感谢哈~



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月4日(周六) 凌晨0:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/druid] 17年bug fixed for testWhileIdle提交针对mysql抛弃链接的修改造成接口不断出现毛刺 (Issue #5148)




  
好的，非常感谢百忙之中的快速回复，公司电脑不允许提交，下班后我用自己电脑提交下 再次感谢~&nbsp; 祝好~
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年3月3日(周五) 凌晨3:55 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [alibaba/druid] 17年bug fixed for testWhileIdle提交针对mysql抛弃链接的修改造成接口不断出现毛刺 (Issue #5148) 这个代码记得是为了诊断一个异常场景增加的代码，这个应该是不需要了。 @kimmking 也帮看下。 @yangcom01 你提个PR吧？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
欢迎提交PR，然后关联这个issue id就可以了。比如 PR标题是 fix #5148

**Comment by lizongbo** [comment]
ping模式不太靠谱，为啥用ping模式而不是用validatequery？

**Comment by lizongbo** [comment]
请使用 1.2.21 进行验证。
