### ISSUE TITLE
SpringBoot3.0.0+Mybatis3.5.1+Druid1.2.16报错，提示登录失败

### ISSUE THREAD

**Issue by wangyunpeng0319** [alibaba/druid#5155]

**Comment by wangyunpeng0319** [comment]
报错：提示登录失败
密码修改为明文可以正常使用或者springboot降级到2也可以使用，请问Druid不支持springboot3吗？

**Comment by FengLingxuan** [comment]
如果你使用的是druid-spring-boot-starter,它目前在SpringBoot3上无法正常工作的, 你可以尝试自己创建连接池对象并将它注册为Bean。
或许你可能遇到其他问题,请参考#5022

**Comment by daenmax** [comment]
druid-spring-boot-starter 在springboot3是正常工作的，只不过一些特性功能无法使用，例如**监控页面、密码加密功能**

**Comment by FengLingxuan** [comment]
> druid-spring-boot-starter 在springboot3是正常工作的，只不过一些特性功能无法使用，例如**监控页面、密码加密功能**

当前版本的druid-spring-boot-starter在SpringBoot3.0.x中确实是无法生效的，原因是SpringBoot3.0起修改了自动装配的SPI结构，[](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files)，基于此结果下，DruidDataSourceAutoConfigure未完成自动装配工作，而通过spring.datasource.type指定的连接池无法对部分配置进行读取。
如果你依旧想使用druid-spring-boot-starter，可以尝试自行指定org.springframework.boot.autoconfigure.AutoConfiguration.imports
而监控页面不生效是因为SpringBoot3使用了Jakarta EE 10。

**Comment by lizongbo** [comment]
请使用 12.20

https://mvnrepository.com/artifact/com.alibaba/druid-spring-boot-3-starter/1.2.20
