### ISSUE TITLE
什么时候支持SpringBoot3？

### ISSUE THREAD

**Issue by jianliangWang** [alibaba/druid#5160]
为什么还不支持SpringBoot3？都出来这么久了，该支持了呀

**Comment by pizriw** [comment]
同问

**Comment by wang-xiaowu** [comment]
别催了各位，看git contribution，温少他们是一直在开发这部分的代码的
咱给点时间，给点空闲

**Comment by lizongbo** [comment]
请升级使用 1.2.20

// https://mvnrepository.com/artifact/com.alibaba/druid-spring-boot-3-starter
implementation 'com.alibaba:druid-spring-boot-3-starter:1.2.20'

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.20
请用新版本
