### ISSUE TITLE
druid 与clickhouse兼容性问题

### ISSUE THREAD

**Issue by sondertara** [alibaba/druid#5166]
版本: 1.2.16
问题: clickhouse不支持setCatalog，使用的是setSchema，但是调用connection.setSchema时，
对应`DruidPooledConnection#setSchema`中，只有mysql家族的数据库才会生效，调用报`SQLFeatureNotSupportedException`

**Comment by lizongbo** [comment]
看了下cluckhouse是支持
```
 public void setSchema(String schema) throws SQLException {
        properties.setDatabase(schema);
    }

    public String getSchema() throws SQLException {
        return properties.getDatabase();
    }

```
我看下这里优化成调用jdbc驱动的setSchema
