### ISSUE TITLE
当前master分支依旧没有解决连接泄露问题

### ISSUE THREAD

**Issue by zrlw** [alibaba/druid#5176]
shrink方法下面两处代码：
https://github.com/alibaba/druid/blob/dac1f48b207e75a55d98d761d034d96c45475d98/core/src/main/java/com/alibaba/druid/pool/DruidDataSource.java#L3204

https://github.com/alibaba/druid/blob/dac1f48b207e75a55d98d761d034d96c45475d98/core/src/main/java/com/alibaba/druid/pool/DruidDataSource.java#L3210

都会最终导致System.arraycopy前移：
https://github.com/alibaba/druid/blob/dac1f48b207e75a55d98d761d034d96c45475d98/core/src/main/java/com/alibaba/druid/pool/DruidDataSource.java#L3250

但如果connections里的连接从头到尾的种类依次是：
1.  空闲时间超过minEvictableIdleTimeMillis待清理的A条连接
phyConnectTimeMillis < phyTimeoutMillis &&  idleMillis  > minEvictableIdleTimeMillis &&  i < checkCount
2.  空闲时间超过minEvictableIdleTimeMillis但应该继续存活（i超过checkCount）的B条连接
phyConnectTimeMillis < phyTimeoutMillis &&  idleMillis  > minEvictableIdleTimeMillis &&  i >=  checkCount && idleMillis < maxEvictableIdleTimeMillis
3. 物理连接时间超时待清理的C条连接
phyConnectTimeMillis >= phyTimeoutMillis 
4. 其他D条连接
shrink操作的System.arraycopy(connections, A+C, connections, 0, poolingCount - A - C)会将第2部分应继续存活的连接覆盖掉，第2部分的DruidConnectionHolder只能等待gc才会释放。

**Comment by lizongbo** [comment]
请升级到 1.2.20再验证

**Comment by zrlw** [comment]
> 请升级到 1.2.20再验证

看了1.2.20的shrink代码，每次shrink只检查判定前checkCount个连接，检查确定保留的连接和没有做检查的连接复制到可用连接数组connections，所以连接偶发泄露的缺陷应该得到修复了。
其中部分代码还可以考虑做一下优化，比如：
```
                Arrays.fill(connections, 0, poolingCount, null);
                System.arraycopy(shrinkBuffer, 0, connections, 0, remaining);
```
可以先执行arraycopy复制，再将connections剩下的位置填充fill为null
