### ISSUE TITLE
偶发连接失效java.sql.SQLException: connection disabled

### ISSUE THREAD

**Issue by cdming405003** [alibaba/druid#5177]
访问mysql过程中会突然出现
异常日志一：
DruidPooledStatement errorCheck：CommunicationsException,druid version 1.1.23
然后报出异常日志二：
discard connection com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure The last packet successfully received from the server was 5,538,582 milliseconds ago. The last packet sent successfully to the server was 5,538,582 milliseconds ago. 
……
Caused by: java.net.SocketException: Connection reset at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115) 

后续有请求还偶尔报出
Cause: java.sql.SQLException: connection disabled ; uncategorized SQLException; SQL state [null]; error code [0]; connection disabled; nested exception is java.sql.SQLException: connection disabled at
……
Caused by: java.sql.SQLException: connection disabled at com.alibaba.druid.pool.DruidPooledConnection.checkStateInternal(DruidPooledConnection.java:1169) at
……
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure The last packet successfully received from the server was 5,538,582 milliseconds ago. The last packet sent successfully to the server was 5,538,582 milliseconds ago.
……
Caused by: java.net.SocketException: Connection reset at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115) at
……

配置：
spring:
  datasource:
    druid:
      max-active: 10
      min-idle: 0
      max-wait: 5000
      validation-query: select 1
      testOn-borrow: true

**Comment by cdming405003** [comment]
... received from the server was 5,538,582 milliseconds ago.这个时间为什么不同时间点的5,538,582 这个数值是不变的，mysql服务端的空闲超时时间是24小时。

**Comment by zrlw** [comment]
https://github.com/alibaba/druid/pull/4726

**Comment by cdming405003** [comment]
> druid的shrink清理连接处理逻辑有问题，我们自己打了个补丁，可以参考一下： #4726 建议你们先升一下druid版本，新版本修复了很多issue。
> 
> 你们应该检查一下应用和数据库之间的网络设备配置，这种30分钟就断开连接的现象多是防火墙自动reset了空闲tcp连接超过30分钟导致的，要保活druid需要设置keepAlive=true

**Comment by cdming405003** [comment]
已经升级到druid 1.2.6版本，keep-alive也打开了，但还是出现Cause: java.sql.SQLException: connection disabled ... Communications link failure The last packet successfully received from the server was 11,700,370 milliseconds ago.这类的错误，每天能有几例错误，并且每次错误都是11,700,370 这个值，请问下这个是什么原因
max-active: 10
min-idle: 0
max-wait: 2000
validation-query: select 1
min-evictable-idle-time-millis: 600000
max-evictable-idle-time-millis: 1800000
keep-alive: true

**Comment by cdming405003** [comment]
公司内部很多服务都是使用druid，只有一个服务会产生这样的错误

**Comment by JJimmy01** [comment]
我也遇到了相同的问题，目前版本1.2.16，后面有修复吗

**Comment by cdming405003** [comment]
> 

没有解决，使用了推荐的补丁版本依旧会报错

**Comment by JJimmy01** [comment]
得了，咱也没时间看源码去了，切回到Hikari连接池了

**Comment by liugddx** [comment]
>

Thanks for your hard work.

**Comment by liugddx** [comment]
> 收到，我计划在5.1期间处理这个问题


Thanks for your hard work.

**Comment by zrlw** [comment]
> @zrlw 已经升级到druid 1.2.6版本，keep-alive也打开了，但还是出现Cause: java.sql.SQLException: connection disabled ... Communications link failure The last packet successfully received from the server was 11,700,370 milliseconds ago.这类的错误，每天能有几例错误，并且每次错误都是11,700,370 这个值，请问下这个是什么原因 max-active: 10 min-idle: 0 max-wait: 2000 validation-query: select 1 min-evictable-idle-time-millis: 600000 max-evictable-idle-time-millis: 1800000 keep-alive: true

11,700,370ms是3小时15分钟，之前你写的5,538,582ms是30分钟， 用的是mysql驱动么？如果是，druid发送的保活探测报文并不是你们配置的select 1，而是自动改为mysql的ping探活包，有开源或商业数据库（客户端用的mysql驱动）收到这种探活包不会更新服务端的连接状态，连接的空闲时间依然会增长，空闲超过阈值后还会主动拆连，建议你们的应用启动参数增加这个选项试试看（关掉druid默认的ping探活方法，采用普通的select语句探活）：
-Ddruid.mysql.usepingmethod=false

你们说的情况应该是探活机制失效的问题，我们自己打的那个补丁 https://github.com/alibaba/druid/pull/4726 只是修补druid连接池shrink清理逻辑，避免出现应用正在使用中的连接被错误清掉、已失效连接没有清理直接进入老年代的问题，并不能解决连接被数据库服务端或中间的网络设备直接干掉的情况。

@cdming405003  @JJimmy01

**Comment by zrlw** [comment]
另外如果配置了timeBetweenEvictionRunsMillis（druid执行清理连接、探活连接的destroy任务的时间间隔，默认1分钟）、keepAliveBetweenTimeMillis（空闲超过此配置的连接才会做探活处理，默认2分钟）这两个参数，也要确认一下不能配大了。

**Comment by JJimmy01** [comment]
使用的是mysql的驱动，timeBetweenEvictionRunsMillis配置的是2秒，keepAliveBetweenTimeMillis没有配置，使用的应该是默认的时间，在druid提供监控的页面能看到有配置的探活sql在执行，我试过将mysql的主动关闭空闲连接的时间设置为30s进行测试，没有复现出这个问题

**Comment by cdming405003** [comment]
> 另外如果配置了timeBetweenEvictionRunsMillis（druid执行清理连接、探活连接的destroy任务的时间间隔，默认1分钟）、keepAliveBetweenTimeMillis（空闲超过此配置的连接才会做探活处理，默认2分钟）这两个参数，也要确认一下不能配大了。

以下是设置的druid配置：
spring:
  datasource:
    druid:
      max-active: 10
      min-idle: 0
      max-wait: 2000
      validation-query: select 1
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 1800000
      keep-alive: true
并且在启动类中设置了 System.setProperty("druid.mysql.usePingMethod", "false");使用select 1进行探活

使用的mysql驱动是：com.mysql.jdbc.Driver

**Comment by cdming405003** [comment]
> druid

我们所使用的云厂商提供的k8s到mysql的连接确实经常会不稳定，造成连接失效，但是已经配置了通过select 1探活

**Comment by zrlw** [comment]
> 使用的是mysql的驱动，timeBetweenEvictionRunsMillis配置的是2秒，keepAliveBetweenTimeMillis没有配置，使用的应该是默认的时间，在druid提供监控的页面能看到有配置的探活sql在执行，我试过将mysql的主动关闭空闲连接的时间设置为30s进行测试，没有复现出这个问题

你说的30秒是mysql数据库服务器的wait_timeout连接最大空闲时间么？如果keepAliveBetweenTimeMillis超过wait_timeout，那么druid的keepAlive探活机制应该是没有效果的，因为等不到druid发送探活包，服务端就已经判定连接空闲超过wait_timeout关闭连接了。

**Comment by zrlw** [comment]
> 我们所使用的云厂商提供的k8s到mysql的连接确实经常会不稳定，造成连接失效，但是已经配置了通过select 1探活

如果网络不稳定，探活也不一定保证池子里的连接都是可用的。探活检测默认的间隔时间是2分钟，两次检测中的时间窗可能就有连接被干掉了，此时如果从池子取到这种连接还是会报错的。
你说的只有一个服务存在这个问题，可以试试把那个服务的Druid选项testOnBorrow设为true看看能否减少这种问题（但并不能杜绝，如果网络很差，即使testOnBorrow检测成功，但下一秒也可能因网络中断而异常，还是会提示通信故障）。
另外testOnBorrow设为true也很影响性能，对于性能要求比较高的应用而言，不应该采用这种方式。

你说用了推荐的补丁版本依旧会报错，如果是我说的补丁 https://github.com/alibaba/druid/pull/4726 ，那主要原因就不是druid清理连接shrink方法里的arraycopy问题了。

**Comment by zrlw** [comment]
> 我们所使用的云厂商提供的k8s到mysql的连接确实经常会不稳定，造成连接失效，但是已经配置了通过select 1探活

如果网络不稳定，探活也不一定保证池子里的连接都是可用的。探活检测默认的间隔时间是2分钟，两次检测中的时间窗可能就有连接被干掉了，此时如果从池子取到这种连接还是会报错的。
你说的只有一个服务存在这个问题，可以试试把那个服务的Druid选项testOnBorrow设为true看看能否减少这种问题（但并不能杜绝，如果网络很差，即使testOnBorrow检测成功，但下一秒也可能因网络中断而异常，还是会提示通信故障）。
另外testOnBorrow设为true也很影响性能，对于性能要求比较高的应用而言，不应该采用这种方式。

你说用了推荐的补丁版本依旧会报错，如果指的是 https://github.com/alibaba/druid/pull/4726 ，那主要原因就不是druid清理连接shrink方法里的arraycopy的问题了。

**Comment by cdming405003** [comment]
我们的原因找到了，是由于在事物内没有回滚导致的，麻烦了

**Comment by lifejoyforpy** [comment]
问一个问题，版本是1.22.事务导致的死锁后，后续会偶发出现链接disable。链接上次使用看时间是死锁事务占用的链接，这个连接池原理是什么，只要死锁了。这个链接后续呗其他请求占用就会报上面错误.这样的话，感觉不合理。麻烦解释下

**Comment by zrlw** [comment]
死锁后数据库抛fatal异常，就会触发druid执行handleFatalError操作disable掉抛异常的连接。

**Comment by lifejoyforpy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lifejoyforpy** [comment]
> 死锁后数据库抛fatal异常，就会触发druid执行handleFatalError操作disable掉抛异常的连接。

那为啥，后续的请求，sql还会跑这个异常，

**Comment by zrlw** [comment]
把你的异常堆栈打印出来看看吧，否则不清楚你说的什么问题，正常情况下disable的连接会被close掉，不会继续使用。

**Comment by lifejoyforpy** [comment]
> 把你的异常堆栈打印出来看看吧，否则不清楚你说的什么问题，正常情况下disable的连接会被close掉，不会继续使用。

我的错误和上面一样，都是链接disabled。但是后面请求，就会偶尔触发的，看描述就是使用了disable链接，druid 是1.22

**Comment by zrlw** [comment]
找你的dba看看吧，数据库服务端主动关闭了连接也是disable，没有堆栈信息无法确认你这种情况是服务端还是客户端的问题，druid是开源软件，你自己搜一下代码看看有没有相符的错误日志输出，下一次再出问题就能确定什么原因了。

**Comment by lifejoyforpy** [comment]
> 找你的dba看看吧，数据库服务端主动关闭了连接也是disable，没有堆栈信息无法确认你这种情况是服务端还是客户端的问题，druid是开源软件，你自己搜一下代码看看有没有相符的错误日志输出，下一次再出问题就能确定什么原因了。

还服务端。我重启就pod就好了，明显druid连接池在处理异常错误情况下，有bug。堆栈和上面一样，就是死锁时候的链接，后面被重新使用，那个链接是disable。要不然为啥会出现上一次成功是很久以前。

**Comment by zrlw** [comment]
druid只是个开源的东西，并不是商业软件，是否使用主要要看自己的维护能力，基本上都是自己用自己改，开源连接池也有很多，如果怀疑是druid连接池问题你可以换其他连接池看看能否解决问题吧。

**Comment by lifejoyforpy** [comment]
> druid只是个开源的东西，并不是商业软件，是否使用主要要看自己的维护能力，基本上都是自己用自己改，开源连接池也有很多，如果怀疑是druid连接池问题你可以换其他连接池看看能否解决问题吧。

主要是现在换改动大，这个问题原因应该就是死锁导致的，正常不会有的。错误堆栈就是上述类似。链接disable。现象是接口查询，会频繁disable堆栈，重启就好了。因此才搜到了这里

**Comment by zrlw** [comment]
可以试试master分支。
druid社区近期来了一个维护者 @lizongbo 把近几年的PR陆续做了逐个检查和合并，或许你的问题能在master分支解决，和已发布的1.2.20版本相比，master已经做了很多修订了。

**Comment by zrlw** [comment]
pod下用druid，min-idle最好配为0，确保连接池及时清除有问题的连接

**Comment by lifejoyforpy** [comment]
> pod下用druid，min-idle最好配为0，确保连接池及时清除有问题的连接
不配置情况下，默认值就是这个。

**Comment by lifejoyforpy** [comment]
> 可以试试master分支。 druid社区近期来了一个维护者 @lizongbo 把近几年的PR陆续做了逐个检查和合并，或许你的问题能在master分支解决，和已发布的1.2.20版本相比，master已经做了很多修订了。

这个升级，不依赖外部条件吧，我试试

**Comment by zrlw** [comment]
master可能依赖的组件比如spring版本有升级，大概率不会有版本冲突。

**Comment by zrlw** [comment]
另外你是不是开启了事务，同一个事务使用的连接都是同一个（ThreadLocal，这个和连接池无关，是保存在事务上下文的），死锁发生时如果应用代码catch吞掉了异常继续运行（事务没有回滚），本事务后续的sql仍然会使用数据库服务已主动disable掉的连接（数据库服务器会主动干掉出现死锁的连接）。

**Comment by lifejoyforpy** [comment]
> > 另外你是不是开启了事务，同一个事务使用的连接都是同一个（ThreadLocal，这个和连接池无关，是保存在事务上下文的），死锁发生时如果应用代码catch吞掉了异常继续运行（事务没有回滚），本事务后续的sql仍然会使用数据库服务已主动disable掉的连接（数据库服务器会主动干掉出现死锁的连接）。
> > 我的写法就是用的spring 事务。没有设置超时，我理解不会进catch，我的catch里是有rollback。

现在我修改了，设置了超时时间，如果超时我也会rollback。不存在catch里没有rollback

**Comment by zrlw** [comment]
@lifejoyforpy 建议先从应用层面排除死锁条件，数据库事务出现死锁时应用程序主动rollback也未必能够回滚，捕获异常的处理过程如果继续使用数据库连接也可能会出现连接已经被服务端主动disable的情况。

**Comment by liuyandeng** [comment]
我也有相同问题,使用1.2.23,请问最后是什么问题呢

**Comment by lifejoyforpy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by liuyandeng** [comment]
能否加个微信聊一聊

**Comment by mroldx** [comment]
> 还服务端。我重启就pod就好了，明显druid连接池在处理异常错误情况下，有bug。堆栈和上面一样，就是死锁时候的链接，后面被重新使用，那个链接是disable。要不然为啥会出现上一次成功是很久以前。

是这样的，我死锁出现后也变这样了，重启就好了

**Comment by lifejoyforpy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
