### ISSUE TITLE
经过多层代理，获取ip失败，报空指针

### ISSUE THREAD

**Issue by yydznzd** [alibaba/druid#5180]
由于经过了多次代理，request.getHeader("x-forwarded-for")获取到的ip为多个，中间用“,”隔开，DruidWebUtils.getRemoteAddr(HttpServletRequest request)获取ip的时候对于这种会直接返回null，此时在调用WebSessionStat.addRemoteAddress(String ip)时ip为null，导致报空指针异常!
![1](https://user-images.githubusercontent.com/61178778/227176314-5a9c39e1-3782-410d-a224-720399dd111d.png)
![2](https://user-images.githubusercontent.com/61178778/227176455-b5ae3922-fd48-4eb8-8e0f-ebfeedd35c12.png)
![3](https://user-images.githubusercontent.com/61178778/227176476-4c5cf7e1-a519-48ad-8f5b-a0d70f0b1715.png)
![4](https://user-images.githubusercontent.com/61178778/227176488-bf2196e0-84ff-4cec-8e33-b017a5b1a128.png)

**Comment by lizongbo** [comment]
我来看下
