### ISSUE TITLE
啥时候适配springboot 3.0啊？

### ISSUE THREAD

**Issue by Bin1993** [alibaba/druid#5187]
年前说的元旦左右会适配，然后又说一月底适配，然后又说二月底适配，直到今天三月底了还没适配。这个就不能给个准信么，3.0升级有这么难么

**Comment by 14772** [comment]
附议

**Comment by PieceOfFall** [comment]
gkd啊，真的

**Comment by handsomelins** [comment]
GKD

**Comment by daenmax** [comment]
附议

**Comment by wenshao** [comment]
正在做匹配

**Comment by ChangZou** [comment]
加油啊，快发一版3.0

**Comment by PieceOfFall** [comment]
> 正在做匹配，争取这几天发一个版本

加油

**Comment by getliuxinyu** [comment]
加油

**Comment by Bin1993** [comment]
催更啊

**Comment by lizongbo** [comment]
请升级使用 1.2.20

// https://mvnrepository.com/artifact/com.alibaba/druid-spring-boot-3-starter
implementation 'com.alibaba:druid-spring-boot-3-starter:1.2.20'

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.20
请用新版本
