### ISSUE TITLE
DruidDataSource类829行是不是有点问题啊

### ISSUE THREAD

**Issue by xdm649365504** [alibaba/druid#5188]
if (connectTimeout == 0) {
                socketTimeout = DEFAULT_TIME_CONNECT_TIMEOUT_MILLIS;
            }

            if (socketTimeout == 0) {
                socketTimeout = DEFAULT_TIME_SOCKET_TIMEOUT_MILLIS;
            }

这里造成不配置connectTimeOut的话 socketTimeout一直会变更为默认的10000ms 造成单独配置socketTimeout失败 难道就是要这样配置么

**Comment by blankbq** [comment]
真搞不懂为啥要加这个默认配置

**Comment by lizongbo** [comment]
这个赋值bug已经修复

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.20
请用新版本
