### ISSUE TITLE
是否可以支持jdbc:mariadb配置connectTimeout和socketTimeout

### ISSUE THREAD

**Issue by cuixiushuai** [alibaba/druid#5192]
DruidDataSource类中的init方法，从配置中读取参数设置socketTimeout和connectTimeout的逻辑，限制了url的前缀为jdbc:wrap-jdbc或者jdbc:mysql，是否可以支持mariadb的前缀jdbc:mariadb

**Comment by lizongbo** [comment]
这里说的配置是指mariadb的 jdbc url吗？
https://mariadb.com/kb/en/about-mariadb-connector-j/
