### ISSUE TITLE
关于druid sql parser 和 说明文档的一点问题

### ISSUE THREAD

**Issue by IAMSZG** [alibaba/druid#5193]
1.不能解析DDL语句中的using btree这种索引数据结构设置。
2.说明文档标题错误：
![image](https://user-images.githubusercontent.com/57979308/229033433-1bf0c776-12f7-413f-b1df-dfbf3cd45730.png)

**Comment by lizongbo** [comment]
反馈问题请发 触发异常的 sql原始文本
