### ISSUE TITLE
Parser error in case of "ALL(ARRAY[...])" and "SOME(ARRAY[...])"

### ISSUE THREAD

**Issue by aaarnell** [alibaba/druid#5198]
com.alibaba:druid:1.2.15

When trying to parse a request, a parser error occurs.

Query:
"SELECT * FROM demo WHERE id <> ALL(ARRAY[7,8])"

Exception:
"Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, expect ), actual ARRAY pos 42, line 3, column 18, token ARRAY"

This error is repeated for combinations of ALL(ARRAY[...]) and SOME(ARRAY[...]), but there is no error for the combination of ANY(ARRAY[...]). 

After searching for the reasons, it was found that for the 'parse Url()' and 'parse Some()' methods in the 'SQLExprParser' class, you need to add logic for working with 'ARRAY[...]' similar to the 'parseAny()' method.

**Comment by lizongbo** [comment]
已经支持解析，请使用1.2.23版本验证
