### ISSUE TITLE
snakeyaml兼容问题

### ISSUE THREAD

**Issue by tiancaipei** [alibaba/druid#5206]
版本
<snakeyaml.version>1.33</snakeyaml.version>
<druid.version>1.1.18</druid.version>（升级到高版本的druid也是同样）
问题描述
将snakeyaml版本升级到1.33，但是升级后出现报错
org.yaml.snakeyaml.error.YAMLException: Unable to find getter for property 'tenantColumn' on object com.alibaba.druid.wall.WallFilter@52aa7742:java.lang.reflect.InvocationTargetException
请问该如何处理

**Comment by nikbobo** [comment]
解决了吗？楼主。
我也遇到了同样的问题。

**Comment by lizongbo** [comment]
请使用最新版验证
