### ISSUE TITLE
spring boot 3自动注入失效

### ISSUE THREAD

**Issue by AndyT0** [alibaba/druid#5209]
Spring Boot 3.x版本注入自动失效 ，已经移除了对spring.factories支持，改为META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports支持

**Comment by FengLingxuan** [comment]
#5022

**Comment by waitwind-fly** [comment]
是这样的哥 我今天试了下还是不行（ps:不知道是不是我打开方式不对）  不知道你那边解决掉没有

**Comment by lizongbo** [comment]
请升级使用 1.2.20

// https://mvnrepository.com/artifact/com.alibaba/druid-spring-boot-3-starter
implementation 'com.alibaba:druid-spring-boot-3-starter:1.2.20'
