### ISSUE TITLE
Boot  2.3.2.RELEASE + Druid-boot-stater  1.1.20  监控页面无法访问

### ISSUE THREAD

**Issue by yandingrui** [alibaba/druid#5212]
Boot  2.3.2.RELEASE + Druid-boot-stater  1.1.20  ，本地localhost可以访问监控页面，但是发到服务器上却无法访问监控页面显示
<img width="613" alt="image" src="https://user-images.githubusercontent.com/86654066/231135448-bc548c3e-beca-4918-8c63-230349c84e7c.png">
，对应的yml也配置了 
spring.druid.datasource.stat-view-servlet.enable=true
spring.druid.datasource.stat-view-servlet.allow="测试服务器的ip"
但是却不能访问，请问是版本问题吗还是什么

**Comment by lizongbo** [comment]
allow的ip应该是你浏览器所在的ip
