### ISSUE TITLE
1.2.16升级到1.2.17方法变更产生兼容问题

### ISSUE THREAD

**Issue by looly** [alibaba/druid#5216]
@kimmking 

见：https://github.com/alibaba/druid/commit/cfb1ec095a5cbba105bb1dcaad6d783ae13123bd#diff-607f3e6b95004336d0b44bf13934c27efcac5ba101094d89a9524095f351ee30L189

这里的修改中，直接将`configFromPropety`修改为`configFromPropeties`，这么改是否考虑兼容性呢？是否可以标记deprecated然后再修改呢？

这样会造成1.2.16版本和1.2.17无法兼容。

**Comment by daenmax** [comment]
确实，1.2.16升级到1.2.17启动直接报错了，小版本升级出现这样的问题，属实不应该，况且是这么大用户体量的产品

**Comment by kimmking** [comment]
在master主干处理了：https://github.com/alibaba/druid/pull/5229

**Comment by looly** [comment]
@kimmking 是滴。感谢~~辛苦了。
