### ISSUE TITLE
shrink方法 keepAlive bug导致连接泄露

### ISSUE THREAD

**Issue by stheart** [alibaba/druid#5220]
问题现象：后端有一个定时任务一分钟跑一次，该任务会查询一次数据库，一晚上后发现数据库连接被打满了

问题原因：[DruidDataSource.java]中的shrink方法中，触发keeplive逻辑后，从connections移除的连接，和添加到keepAliveConnections的连接不一致，导致连接丢失以及不停创建新连接

经过本地复现以及调试，发现出错的逻辑流程如下，以下10001,10003,10003均为连接号id：
1. 初始化连接池connections，connections状态为【10001,10002,10003】
2. 业务使用了10003连接后归还，连接池状态为【10001,10002,10003】，此连接由于被使用过，后续不需要保活
3. shrink函数触发对10001,10002连接进行keeplive操作（这次操作是正确的）

-  执行流程：先将10001,10002连接放到keepalive数组，再将connections中10001和10002移除，此时connections状态为【10003】，在10001,10002保活成功之后，再次放入connections，此时connections状态为【10003,10002,10001】

4. shrink函数再次触发对10001,10002连接进行keeplive操作（**这次操作出现异常**）

-   执行流程：先将10001,10002连接放到keepalive数组，再将connections中10002和10003移除（**问题就在这里，连接移除错了，应该移除10001和10002**），此时连接池状态为【10001】而不是【10003】，这导致后续保活流程报错以及会创建新连接，导致连接泄露。
5. 此时10001连接既出现在keepAliveConnections数组，又出现在connections数组，在10001保活成功之后，归还到connections数组中去，由于有重复连接校验的逻辑，导致后续直接将10001连接关闭，但是该连接还是在connections数组数组，在下次对10001连接保活的时候，就会出现连接已关闭的错误日志
![image](https://user-images.githubusercontent.com/49032936/232202920-2e90d72b-565d-4302-bedf-0a9179ea97f2.png)

#5221 

druid版本：1.2.15
druid配置文件：
![image](https://user-images.githubusercontent.com/49032936/232006220-7a088a9d-c599-49b0-b7c2-418174445fc8.png)

**Comment by stheart** [comment]
将保活连接从connections数组中移除的代码主要是这两行，
System.arraycopy(connections, removeCount, connections, 0, poolingCount - removeCount);
Arrays.fill(connections, poolingCount - removeCount, poolingCount, null);
我在pr中将这块逻辑修正了，在将连接添加到keepalive数组的同时，将connections中的连接置为null，最后再将connections的null元素处理下排序往后放即可

**Comment by dcy10000** [comment]
看起来最新版已经修复了使用connectionsFlag
