### ISSUE TITLE
增加TiDB的BEGIN开启事务的语法解析支持

### ISSUE THREAD

**Issue by lizongbo** [alibaba/druid#5224]
版本： 1.2.17

TiDB的sql示例1： BEGIN;
示例2：BEGIN PESSIMISTIC;
示例3: BEGIN /*T! PESSIMISTIC */;

TiDB的官方介绍： https://docs.pingcap.com/zh/tidb/stable/sql-statement-begin
目前解析这些sql会视为是begin end的语法，直接抛异常。

**Comment by kimmking** [comment]
pending it.
我试了一下，单测里的写法，对正常的mysql是错误语法。
能否专门针对tidb做这个语法处理？
