### ISSUE TITLE
如何对格式化后表名进行替换？

### ISSUE THREAD

**Issue by li395092734** [alibaba/druid#5230]
使用Druid进行格式化以后，有没有相应的API，能够实现对表名和其它字段的更新操作呢？

**Comment by kimmking** [comment]
啥意思，修改sql，换掉表名和列名？
这是直接操作sql parser干的活儿。

**Comment by li395092734** [comment]
是对现有SQL进行修改表名和备注。
这个是有相应的API可以实现吗？

**Comment by li395092734** [comment]
https://github.com/alibaba/druid/issues/2457

**Comment by li395092734** [comment]
从另一个里面找到了，表明替换的。#2457
