### ISSUE TITLE
看到有“druid-spring-boot-starter”。是不是也可以加个 "solon" 框架的适配："druid-solon-plugin"？

### ISSUE THREAD

**Issue by noear** [alibaba/druid#5238]
Solon 框架的项目仓库：https://github.com/noear/solon

希望也能有对应的适配：）

**Comment by lizongbo** [comment]
你自己封装适配一个即可。

**Comment by xcocean** [comment]
并不困难，可以参考这篇文章：
* [https://lingkang.top/archives/solon2druid](https://lingkang.top/archives/solon2druid)
* [https://blog.csdn.net/weixin_44480167/article/details/149146402](https://blog.csdn.net/weixin_44480167/article/details/149146402)

**Comment by xcocean** [comment]
> Solon 框架的项目仓库：https://github.com/noear/solon
> 
> 希望也能有对应的适配：）

并不困难，可以参考这篇文章：
* [https://lingkang.top/archives/solon2druid](https://lingkang.top/archives/solon2druid)
* [https://blog.csdn.net/weixin_44480167/article/details/149146402](https://blog.csdn.net/weixin_44480167/article/details/149146402)
