### ISSUE TITLE
有些配置能不能给点默认值，比如连接失败就一直打印错误日志？这很合理吗？连接最大等待时间也是，给个默认的时间不好，就这么让请求一直等着？

### ISSUE THREAD

**Issue by AHangC** [alibaba/druid#5247]

**Comment by AHangC** [comment]
还有一些配置，我在你们文档里也看不到说明，源码类上也没有属性说明，只能跟进源码调用来看，这不能补全一下？

**Comment by lizongbo** [comment]
最新的属性配置请参考：

https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8
