### ISSUE TITLE
请问FilterEventAdapter 如何配置 监听某一张表, 而不是通过解析每一条sql语句, 来判断是那一张表

### ISSUE THREAD

**Issue by cloudAndMonkey** [alibaba/druid#5257]
<img width="923" alt="image" src="https://user-images.githubusercontent.com/12228225/236607855-71277d40-3ebe-457b-9952-45ce06f1bcbd.png">

**Comment by lizongbo** [comment]
不解析sql就不可能知道这个sql语句涉及哪些表。
