### ISSUE TITLE
The last packet successfully received from the server was XXXXmilliseconds ago. The last packet sent successfully to the server was XXXX milliseconds ago

### ISSUE THREAD

**Issue by xb12369** [alibaba/druid#5262]
mysql8.0 druid1.2.17下项目运行一段时间后报了解超时（默认超时时间是10s）
这是出现错误的时候具体的报错信息：
```
ERROR druid.sql.Statement(Slf4jLogFilter.java:148) - {conn-10006, pstmt-21952} execute error
###Error updating database.  Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 10,012 milliseconds ago. The last packet sent successfully to the server was 10,012 milliseconds ago.
### The error may exist in class path resource [mapper/medical/DoctorMapper.xml]
### The error may involve com.boao.backend.dao.medical.DoctorDao.updateDynamicById-Inline
### The error occurred while setting parameters
### SQL: UPDATE table SET license_status = ?,                                                             updated_on = now(),      updated_by_id = ?,      updated_by = ?    WHERE    id = ?
### Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 10,012 milliseconds ago. The last packet sent successfully to the server was 10,012 milliseconds ago.
; Communications link failure

The last packet successfully received from the server was 10,012 milliseconds ago. The last packet sent successfully to the server was 10,012 milliseconds ago.; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

```

请求接口的时间：2023-05-08 11:10:21.536
响应的时间：2023-05-08 11:10:31.575

配置的数据超时时间：
| Variable_name| Value|
| --- | --- |
| connect_timeout |10  |

```
?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
# 空闲时验证，防止连接断开
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true

# 连接池的配置信息:初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 100

```

表面上看确实是超过了10s导致连接超时，但是这个仅仅根据主键做的update，导致我甚至想加个索引都没法再加！

困扰了我好多天~~~~~~~先标记在这，那天我给处理好了再回来更新

要是有好心的大佬有类似的案例，求分享，好人一生平安！！！

**Comment by lizongbo** [comment]
这个异常CommunicationsException是mysql jdbc抛出来的，问题出在mysql jdbc层的可能性大一些(当然也可能是连接保活有问题)
性能要求不是非常高的话，把testOnBorrow设置为true来避免问题，我们的绝大部分项目都是开启了testOnBorrow的，单次db操作的平均耗时最多只增加了1毫秒。

**Comment by ChinaJeckXu** [comment]
> 这个异常CommunicationsException是mysql jdbc抛出来的，问题出在mysql jdbc层的可能性大一些(当然也可能是连接保活有问题)
> 性能要求不是非常高的话，把testOnBorrow设置为true来避免问题，我们的绝大部分项目都是开启了testOnBorrow的，单次db操作的平均耗时最多只增加了1毫秒。

1.2.18版本 把testOnBorrow设置为true 实测依旧存在这个问题

**Comment by xiaoyuwang1987** [comment]
> > 这个异常CommunicationsException是mysql jdbc抛出来的，问题出在mysql jdbc层的可能性大一些(当然也可能是连接保活有问题)
> > 性能要求不是非常高的话，把testOnBorrow设置为true来避免问题，我们的绝大部分项目都是开启了testOnBorrow的，单次db操作的平均耗时最多只增加了1毫秒。
> 
> 1.2.18版本 把testOnBorrow设置为true 实测依旧存在这个问题

希望赶紧修复一下，我们只要大表做操作 就会这样

**Comment by lnexin** [comment]
分库分表或者大表都有这个问题，怀疑是链接失活以后，连接池不知道，还去执行检测语句导致的。

cp30官方有解决方案，https://blog.csdn.net/frankcheng5143/article/details/50589264，但druid 的配置里面似乎不支持这个

**Comment by lnexin** [comment]
1. 使用数据查询数据的wait_timeout,   [show global variables like '%timeout%'; ] 查询出来的wait_timeout=600
2. druid 中配置的 datasource.setMaxWait(700);
3. 只要实际程序的值大于数据库里面的，而程序会使用 datasource.setValidationQuery(select 1); 设置的查询语句去查询链接是否可用，但是一旦超时，就会导致查不了，报错；

临时解决方案：
把程序里面连接池的时间设置小一点，比如上面小宇600 s 就好

**Comment by lizongbo** [comment]
> 1. 查询数据库里面 [show global variables like '%timeout%'; ] 查询出来的wait_timeout=600

你这个是dba瞎配置了啊，这种dba可以开掉了。

默认十分钟断开连接，执行个事务或大表操作超过10分钟就就死定了。
默认值是28800表示8小时，dba再小气，配个3600秒一小时，也够严格了，我们的配置是172800，是48小时才断开。

**Comment by brantroy** [comment]
实质上这个10,012应该是socketTimeout的时间，属于jdbc层面的默认10秒配置，可以通过在jdbcUrl中增加&socketTimeout=xxx来修改该配置项。
我这边一个大表操作出现了类似问题，解决方案是做了sql的优化，将单次操作时间缩短（之前偶尔需要10多秒，导致socket超时了）。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.20
请用新版本

**Comment by a364514921** [comment]
> 实质上这个10,012应该是socketTimeout的时间，属于jdbc层面的默认10秒配置，可以通过在jdbcUrl中增加&socketTimeout=xxx来修改该配置项。 我这边一个大表操作出现了类似问题，解决方案是做了sql的优化，将单次操作时间缩短（之前偶尔需要10多秒，导致socket超时了）。

可行，感谢 👍

**Comment by sai129198** [comment]
> https://github.com/alibaba/druid/releases/tag/1.2.20 请用新版本


<dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-starter</artifactId>
                <version>1.2.20</version>
</dependency>

用的1.2.20版本一样出现这个问题
