### ISSUE TITLE
MySql 解析Where子句中包含变量的小于表达式出错

### ISSUE THREAD

**Issue by xuesong123** [alibaba/druid#5272]
描述：小于表达式后如果是变量，小于符号会被解析为 <@
示例: 
set @end_date = '2023-05-01';
select * from mytest where mydate < @end_date;

解析之后的 where 子句变为：
select * from mytest where mydate <@ end_date;
小于符号后如果跟两个及以上空格则无此问题

对应的源码：
版本： 1.2.16
类: com.alibaba.druid.sql.parser.Lexer 
行号：1637

` `

                    if (ch == ' ') {
                        char c1 = charAt(pos + 1);
                        if (c1 == '=') {
                            scanChar();
                            scanChar();
                            if (ch == '>') {
                                token = Token.LTEQGT;
                                scanChar();
                            } else {
                                token = Token.LTEQ;
                            }
                        } else if (c1 == '>') {
                            scanChar();
                            scanChar();
                            token = Token.LTGT;
                        } else if (c1 == '<') {
                            scanChar();
                            scanChar();
                            token = Token.LTLT;
                        } else if (c1 == '@') {
                            scanChar();
                            scanChar();
                            token = Token.LT_MONKEYS_AT;
                        } else if (c1 == '-' && charAt(pos + 2) == '>') {
                            scanChar();
                            scanChar();
                            scanChar();
                            token = Token.LT_SUB_GT;
                        } else {
                            token = Token.LT;
                        }

` `

重现：

` `

           Lexer lexer = new Lexer("a < @end_date", null, DbType.mysql);

            while(true) {
                lexer.nextToken();
                com.alibaba.druid.sql.parser.Token token = lexer.token();
                System.out.println(lexer.token() + ": " + lexer.stringVal());

                if(token == Token.EOF) {
                    break;
                }
            }

``

**Comment by MinAAAAAAAA** [comment]
同样也遇到了这个问题，重写了一遍

**Comment by lizongbo** [comment]
请发能复现问题的完整sql

**Comment by lizongbo** [comment]
看了下命中 postgresql的语法了 https://github.com/alibaba/druid/issues/1391

**Comment by ren1151576** [comment]
同样的问题在1.2.24版本中仍未解决。
数据库：mysql
建表语句：
```
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    age INT NOT NULL
);
BEGIN;
```
测试代码
```
@Test
void testSplitSql() {
    String sql = "SELECT*FROM users WHERE age<@target_age;";
    List<SQLStatement> sqlStatements = SQLUtils.parseStatements(sql, "mysql");
    String resultSQL = sqlStatements.get(0).toString();
    System.out.println(resultSQL);
    assert resultSQL.equals("SELECT *\n" +
            "FROM users\n" +
            "WHERE age <@target_age;");
}
```
实际得到的sql为：
```
SELECT *
FROM users
WHERE age <@ target_age;
```
错误的将参数`@target_age`分割为`@ target_age`了
