### ISSUE TITLE
压力测试下，sql执行时间过长

### ISSUE THREAD

**Issue by chengqian117** [alibaba/druid#5278]
# 版本
```
<dependency>
   <groupId>com.alibaba</groupId>
   <artifactId>druid-spring-boot-starter</artifactId>
   <version>1.2.17</version>
</dependency>
<dependency>
   <groupId>mysql</groupId>
   <artifactId>mysql-connector-java</artifactId>
   <version>8.0.25</version>
</dependency>
```
数据库版本 mysql:5.7.25
# 问题
压力测试下，500个请求sql查询时间高达6秒。
压测过程中在mysql客户端执行sql，时间依旧很短。
怀疑sql在排队执行。
# 测试内容
![2b1bb273b8f9b14f099541dc21421d6](https://github.com/alibaba/druid/assets/55426483/7ee1ec71-35b1-46b9-8f64-578d8d8c5b8b)
![4564b5108277ed622ecdf63469824da](https://github.com/alibaba/druid/assets/55426483/d99979ed-528f-4c12-b39f-042bf0a19c0e)

**Comment by zrlw** [comment]
druid只是管理连接池的，sql执行慢还是去查服务端靠谱一些。

**Comment by chengqian117** [comment]
@zrlw 
感谢，已经解决了。
是因为接口里有mysql存储过程，他不受事务级别影响，执行是同步的。所以才有sql排队的现象。感谢
