### ISSUE TITLE
不运行mssql  的OFFSET FETCH分页方法吗

### ISSUE THREAD

**Issue by wskidtren** [alibaba/druid#5290]
当有sql语然中有 offset 1 row fetch next 20 rows only分页时，

提示syntax error: syntax error, expect ONLY, actual STAR, pos 989, line 33, column 36, token *

**Comment by wskidtren** [comment]
Error querying database.  Cause: java.sql.SQLException: sql injection violation, dbType sqlserver, , druid-version 1.2.18, syntax error: syntax error, expect ONLY, actual STAR, pos 989, line 33, column 36, token *

**Comment by lizongbo** [comment]
发个完整的可复现bug的sql来。

**Comment by lizongbo** [comment]
没有收到出错示例sql，且 actual STAR 更像是拼错了单词是STAR。
