### ISSUE TITLE
druid 链接oracle 数据库首次查询非常慢

### ISSUE THREAD

**Issue by kyh16000771** [alibaba/druid#5293]
我使用的druid  版本是 1.2.8 ，oracle数据库使用的版本 
  <dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc6</artifactId>
            <version>11.2.0.4</version>
        </dependency>
在首次创建查询的时候，接口执行消耗超出正常20倍，根据druid的sql监控可以看到sql 执行的时间都在个位数，接口没有任何其他逻辑，使用的是mysql plus 版本3.3.0 分析原因产生在数据库首次创建链接的位置，
# 初始连接数
      initialSize: 10
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 50
      # 配置获取连接等待超时的时间
      maxWait: 500
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 6000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 90000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      # 应用向连接池申请连接，并且testOnBorrow为false时，连接池将会判断连接是否处于空闲状态，如果是，则验证这条连接是否可用
      testWhileIdle: true
      # 如果为true，默认是false，应用向连接池申请连接时，连接池会判断这条连接是否是可用的
      testOnBorrow: false
      # 如果为true（默认false），当应用使用完连接，连接池回收连接的时候会判断该连接是否还可用
      testOnReturn: false 
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      keepAlive: true
      相关配置，请问有什么解决办法吗

**Comment by zrlw** [comment]
应该去找oracle问问，druid只是管理连接池，连接创建用的是oracle的驱动，连接建立慢通常和连接池无关。
类似的问题网上有很多，比如“Oracle RAC 模式下客户端建立JDBC初始连接时因ONS造成应用启动时卡顿30秒问题”
