### ISSUE TITLE
项目引用的三方包用了这个方法，但最新版druid去掉了

### ISSUE THREAD

**Issue by oday-xiexin** [alibaba/druid#5298]
三方包内部依赖的druid使用了1.1的版本，我项目使用的是1.2.16。1.2.16没这个方法 
   public static boolean isEmpty(String value) {
        return isEmpty((CharSequence)value);
    }
 Exception: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: com.alibaba.druid.util.StringUtils.isEmpty(Ljava/lang/String;)Z
能不能在下个版本增加下保持下兼容性

**Comment by oday-xiexin** [comment]
@wenshao

**Comment by DreamFerry** [comment]
自己找替代方法，或者用旧版本，不应让druid承担历史包袱

**Comment by oday-xiexin** [comment]
> 重构项目 OR 用旧版本，不应让druid承担历史包袱
三方包==

**Comment by lizongbo** [comment]
请找第三方包修改调用方法
