### ISSUE TITLE
GetConnectionTimeoutException

### ISSUE THREAD

**Issue by liuymxlxfyzs** [alibaba/druid#5299]
项目突然间报错（druid 当前版本1.1.22）

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, active 0, maxActive 100, creating 0, createErrorCount 4479

**Comment by howieqdd** [comment]
解决了吗

**Comment by lizongbo** [comment]
请使用最新版进行验证
