### ISSUE TITLE
xml注入多数据源，如何指定其中一个为主数据源

### ISSUE THREAD

**Issue by chosenZ** [alibaba/druid#5308]
背景是项目中本来只有一个老数据源，最近新增了一个数据源后，getBean(DataSource.class)的地方就会报【期待一个匹配但找到两个数据源】的错误。有类似@Primary的XML property可以实现指定老数据源为默认数据源的方法吗，如果把老的地方全都改了，风险比较大。

**Comment by lizongbo** [comment]
spring的话，在bean定义上加primary属性就可以了。

`   <bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource" init-method="init" destroy-method="close" primary="true">
`
