### ISSUE TITLE
druid1.2.16 格式化mysql select语句时TIMESTAMPDIFF函数转换错误

### ISSUE THREAD

**Issue by AdolphLv** [alibaba/druid#5309]
程序代码:
![20230606134733](https://github.com/alibaba/druid/assets/35337924/46fad478-6cfe-4f64-9fac-50b980dc38b6)

运行结果:
![image](https://github.com/alibaba/druid/assets/35337924/87b3ee1c-4c78-474d-9c0a-d963372844b2)

问题点:
TIMESTAMPDIFF函数第一个参数DAY为单位,不是字段,加上``后sql异常

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.20
请用新版本
