### ISSUE TITLE
1.2.16版本，连接PG数据库在url上设置socketTimeout失效问题

### ISSUE THREAD

**Issue by Ewang17** [alibaba/druid#5310]
社区上已经有类似issue：https://github.com/alibaba/druid/issues/5145

今天看了下源码，感觉实现方式有点问题，看下官方要不要改下。

之前1.2.5版本使用url方式设置是没问题的，升级到1.2.16以后失效。配套postgresql版本是42.5.1。

看代码，postgresql在org.postgresql.Driver#parseURL方法中，是会解析url中的参数放进 connection properties的。

然后在创建连接时，ConnectionFactoryImpl#tryConnect又会从properties里取出来设置到Socket上。
![image](https://github.com/alibaba/druid/assets/26238688/c57ee421-d84c-4e41-81c2-b8524416bc76)

而druid由于只对mysql的url进行了解析，对于pg数据库只能取到默认值。
![image](https://github.com/alibaba/druid/assets/26238688/4bf40903-6a48-46c0-9510-cdbb53413f45)

![image](https://github.com/alibaba/druid/assets/26238688/f5be89e9-42df-46ed-9fbe-03823e8fea09)

且会在postgresql的Driver创建完连接之后，重新设置一遍socketTimeout，导致默认值覆盖了原有配置，原有配置失效
![image](https://github.com/alibaba/druid/assets/26238688/3fbf4b0a-8929-464b-8fec-980bdcda8b7b)

**Comment by zrlw** [comment]
自己改一下DruidDataSource#initFromUrlOrProperties，增加pg支持吧，此类issue不止一个，迄今为止还没有人出来奉献。
或者换成xml配置方式：
https://www.alibabacloud.com/help/zh/analyticdb-for-mysql/user-guide/druid-connection-pool-1

**Comment by dingxy3** [comment]
> 社区上已经有类似issue：#5145
> 
> 今天看了下源码，感觉实现方式有点问题，看下官方要不要改下。
> 
> 之前1.2.5版本使用url方式设置是没问题的，升级到1.2.16以后失效。配套postgresql版本是42.5.1。
> 
> 看代码，postgresql在org.postgresql.Driver#parseURL方法中，是会解析url中的参数放进 connection properties的。
> 
> 然后在创建连接时，ConnectionFactoryImpl#tryConnect又会从properties里取出来设置到Socket上。 ![image](https://private-user-images.githubusercontent.com/26238688/244586401-c57ee421-d84c-4e41-81c2-b8524416bc76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MzAzNTcsIm5iZiI6MTcwNTczMDA1NywicGF0aCI6Ii8yNjIzODY4OC8yNDQ1ODY0MDEtYzU3ZWU0MjEtZDg0Yy00ZTQxLTgxYzItYjg1MjQ0MTZiYzc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDA1NTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MDkwYTY1OGJiNTM5NjFmNjg3ODQ2YmQ1ZjlmODgyNWI1NGIzODM1OWMzOGM4M2U3ZmZiMDgwMTI0YjliZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s4pWmN9yrYmZj4lmp_hipP11-yp0NkLpQzKkBkE8Vtg)
> 
> 而druid由于只对mysql的url进行了解析，对于pg数据库只能取到默认值。 ![image](https://private-user-images.githubusercontent.com/26238688/244016233-4bf40903-6a48-46c0-9510-cdbb53413f45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MzAzNTcsIm5iZiI6MTcwNTczMDA1NywicGF0aCI6Ii8yNjIzODY4OC8yNDQwMTYyMzMtNGJmNDA5MDMtNmE0OC00NmMwLTk1MTAtY2RiYjUzNDEzZjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDA1NTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYWUxMzM0MDk2OTJlYWZmY2M0NGFkZjA0MDNkZWEyYjM3MTE5YmI0MDQzNTRkZGNlMzBjYTI5Nzk2OWI1M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q8pRFnoR067GtZj2bBtuCLanIQWkKHyNIWYvYFVePh0)
> 
> ![image](https://private-user-images.githubusercontent.com/26238688/244586196-f5be89e9-42df-46ed-9fbe-03823e8fea09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MzAzNTcsIm5iZiI6MTcwNTczMDA1NywicGF0aCI6Ii8yNjIzODY4OC8yNDQ1ODYxOTYtZjViZTg5ZTktNDJkZi00NmVkLTlmYmUtMDM4MjNlOGZlYTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDA1NTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZjkwZTJkMzdhNzExNjQyNDE2YjQwZmZjYzRlYmZjZTEyYmM0NmY3Nzk1MmFlNWUzNmUwYTQwYTgzMTMxMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.psBM0btLOOsV2DhlcrbWsZixjXRfvTTMn1Y1gGGJLFM)
> 
> 且会在postgresql的Driver创建完连接之后，重新设置一遍socketTimeout，导致默认值覆盖了原有配置，原有配置失效 ![image](https://private-user-images.githubusercontent.com/26238688/244586031-3fbf4b0a-8929-464b-8fec-980bdcda8b7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MzAzNTcsIm5iZiI6MTcwNTczMDA1NywicGF0aCI6Ii8yNjIzODY4OC8yNDQ1ODYwMzEtM2ZiZjRiMGEtODkyOS00NjRiLThmZWMtOTgwYmRjZGE4YjdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDA1NTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYTI5M2M3YzE4ODg0ZDI3MmY1MzM2NDFiYTQyYjk5ZjBlOGUxZmEzMDJjMDhlNjRhZDUzNzBjYmNmYTEzOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OeLc_mMiy4ps3LZOY6soT4U1A3Xif4sGSXqQWbVDD7w)

默认10s没有错，但是最起码留个口子比如connectionProperties=connectTimeout=10000;socketTimeout=30000这个优先级最高，能代替默认10s，但是现在通过connectionProperties这个还是被覆盖。配置connectionProperties和socketTimeout属性不同源呢。

**Comment by zrlw** [comment]
看代码修订过程，感觉是druid要和数据库具体驱动解耦了，数据库类型太多了，每个都去适配代码越来越臃肿。
只是mysql面子可能比较大，就只给它保留了url参数解析，其他类型的数据库砍掉了url特定参数解析，相关参数都要遵循druid自己的方式去搞：具体可以看看DruidDataSourceWrapper和相关测试类，测试类通过application.properties设置spring.datasource.druid.xxx参数，其中xxx就包括你需要的socket-timeout。

**Comment by dingxy3** [comment]
> 看代码修订过程，感觉是druid要和数据库具体驱动解耦了，数据库类型太多了，每个都去适配代码越来越臃肿。 只是mysql面子可能比较大，就只给它保留了url参数解析，其他类型的数据库砍掉了url特定参数解析，相关参数都要遵循druid自己的方式去搞：具体可以看看DruidDataSourceWrapper和相关测试类，测试类通过application.properties设置spring.datasource.druid.xxx参数，其中xxx就包括你需要的socket-timeout。

spring.datasource.druid.socket-timeout 没用哦

**Comment by zrlw** [comment]
并不需要druid-spring，DruidDataSourceWrapper这个类是配置druid参数的demo，配置的参数名称前缀xxx和配置文件的参数名称前缀一致就行，比如xxx.socket-timeout。
配置类：
@ConfigurationProperties("spring.datasource.druid")
...
配置文件:
xxx.socket-timeout=nnn

当然最省事的方式是构建ds对象直接调用ds的setConnectTimeout（设置socketTimeout参数的前提条件）和setSocketTimeout方法。

**Comment by dingxy3** [comment]
> 并不需要druid-spring，DruidDataSourceWrapper这个类是配置druid参数的demo，配置的参数名称前缀xxx和配置文件的参数名称前缀一致就行，比如xxx.socket-timeout。 配置类： @ConfigurationProperties("spring.datasource.druid") ... 配置文件: xxx.socket-timeout=nnn
> 
> 当然最省事的方式是构建ds对象直接调用ds的setConnectTimeout（设置socketTimeout参数的前提条件）和setSocketTimeout方法。

目前就是ds set解决的，我们自己封装的和druid-spring一样的sdk。没有像DruidDataSourceWrapper类似的封装导致一些属性无法配置（比如这个socketTimeout）。
另外connectionProperties=connectTimeout=10000;socketTimeout=30000这样设置进去也会被druid给改成10秒默认值。druid这个封装导致socketTimeout属性数据没有保持一致，属性不同源（它在判断coonnecttimeout是否大于0的时候然后设置socketTimeout为什么不判断connectProperties里有没有用户设置coonnecttimeout属性，没有再设置scocketTimeout是不是更好点）。

**Comment by zrlw** [comment]
目前设置druid全部参数只能参照DruidDataSourceWrapper的方式，要么你们就要自己定制修改代码了。
druid社区的惯例貌似一直是提issue的负责提PR，等着审核合并进master，除非是功能缺陷，只提issue没有PR的绝大多数都会一直凉在那里，你可以翻翻看，有的issue已经凉了N年了。

**Comment by zrlw** [comment]
这个问题本质是connectTimeout，socketTimeout设置方式优先级问题，目前druid以wrapper封装优先于connectionProperties，只是默认设置和wrapper封装没有标识区分，所以在connectionProperties设置这两个参数都没有用。

**Comment by zrlw** [comment]
如果提PR，可以修改setConnectionProperties，对于name为connectTimeout、socketTimeout的参数，同时调用一下对应的set方法。

**Comment by dingxy3** [comment]
> 这个问题本质是connectTimeout，socketTimeout设置方式优先级问题，目前druid以wrapper封装优先于connectionProperties，只是默认设置和wrapper封装没有标识区分，所以在connectionProperties设置这两个参数都没有用。

是的，先定优先级在，再保持数据同源。
