### ISSUE TITLE
1.2.15版本插入数据时抛 NullpointException

### ISSUE THREAD

**Issue by david-wudw** [alibaba/druid#5311]
![image](https://github.com/alibaba/druid/assets/43885357/b9981446-452d-4265-939b-164ce55e67c5)

**Comment by david-wudw** [comment]
version is 1.2.15, when  insert data , got this exception.

**Comment by david-wudw** [comment]
![image](https://github.com/alibaba/druid/assets/43885357/33f33947-474e-4ff4-9328-1d9fbdec7066)

**Comment by lizongbo** [comment]
请使用最新版验证。
