### ISSUE TITLE
spring-boot-3配置运行后， http://网站:8080/druid/ 无法访问404

### ISSUE THREAD

**Issue by elwin942** [alibaba/druid#5314]
用了官方的测试代码也不行，我只是改了下配置参数
![image](https://github.com/alibaba/druid/assets/57627757/e5c4770d-e2d5-4f63-829b-11574f5b9866)

数据库驱动为：
<dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.30</version>
        </dependency>
spring-boot-3.X  + java 17
![image](https://github.com/alibaba/druid/assets/57627757/02d8a2ce-52c9-40a2-901e-5e559b4810cb)
**当我改为spring-boot-2.X + java8时又是可以的。**

**Comment by WilliamJustin** [comment]
druid的监控页面基于javax.servlet，Springboot3用jakarta.servlet替换掉了javax.servlet，应该是这个原因

**Comment by xintingcui** [comment]
https://blog.csdn.net/friendlytkyj/article/details/131032426 参考这个，我试过之后是可以访问的，没问题

**Comment by elwin942** [comment]
> https://blog.csdn.net/friendlytkyj/article/details/131032426 参考这个，我试过之后是可以访问的，没问题

试过加org.springframework.boot.autoconfigure.AutoConfiguration.imports文件是可以的，谢谢！

**Comment by youapple** [comment]
可参考示例：https://github.com/youapple/hexadecimal-demo/tree/master/springboot3-druid

**Comment by zhaobo-98** [comment]
> > [https://blog.csdn.net/Friendlytkyj/article/details/131032426](https://blog.csdn.net/friendlytkyj/article/details/131032426)参考这个，我试过之后是可以访问的，没问题
> 
> 试过加org.springframework.boot.autoconfigure.AutoConfiguration.imports文件是可以的，谢谢！
加完上述配置后，报错了，请问有解决方式吗？
<img width="1692" alt="image" src="https://github.com/alibaba/druid/assets/49614720/8d2f56e1-e79a-4bf2-aef1-2bee162ed88f">

**Comment by rikkely** [comment]
> 

这个文件是加在jar包下面吗 还是启动类的resources下面

**Comment by lizongbo** [comment]
请升级使用 1.2.20 

// https://mvnrepository.com/artifact/com.alibaba/druid-spring-boot-3-starter
implementation 'com.alibaba:druid-spring-boot-3-starter:1.2.20'
