### ISSUE TITLE
使用hutool DB,配置文件时db.setting,希望用druid加密数据库密码该怎么操作

### ISSUE THREAD

**Issue by JZ-MEI** [alibaba/druid#5323]
我的项目使用的hutool的db.setting,我应该用怎么写配置文件，这是[数据源配置db.setting样例](https://hutool.cn/docs/#/db/%E6%95%B0%E6%8D%AE%E6%BA%90%E9%85%8D%E7%BD%AEdb.setting%E6%A0%B7%E4%BE%8B),

**Comment by lizongbo** [comment]
找hutool加支持能力
