### ISSUE TITLE
druid+mybatis+clickhouse 首次查询或间隔很久后首次查询 很慢

### ISSUE THREAD

**Issue by yongjie-huang** [alibaba/druid#5328]
druid 1.2.4
clickhouse-jdbc 0.4.0版本

如题，首次查询或间隔很久后首次查询 耗时扩大近10倍。sql耗时监控并无明显增大（表数据量小也是一样的情况）

直观感觉是druid连接池创建新的连接耗时很久，开启keepalive也未解决。

**Comment by zrlw** [comment]
tcpdump抓包分析一下过程吧，确认连接请求是不是及时发出去了，数据库服务器是不是及时应答结果了，客户端什么时候收到的结果，这样才能确定问题出在哪里。
druid只是管理连接的，创建连接用的jar包又不是druid自己写的，连接建立耗时长短通常和连接池没有关系。
