### ISSUE TITLE
由于网络变化导致tls握手长时间卡住，导致创建连接的线程长时间卡死

### ISSUE THREAD

**Issue by polaris-phecda** [alibaba/druid#5338]
问题现象：
创建链接的线程卡住15分钟，整个链接池不可用。

![2](https://github.com/alibaba/druid/assets/92513748/4cea2262-0975-4f39-b751-15283945d300)

我的配置（连接oracle数据库）：
`gam.datasource.params=useSSL=true&requireSSL=true&verifyServerCertificate=true&socketTimeout=900&loginTimeout=300`

问题原因：
创建连接的过程中，在tcp握手后tls握手时，网络发生异常，导致创建连接的线程长时间卡在socketread0，无法创建新连接。导致整个连接池不可用。

请求：
由于sockettimeout通常受限于业务场景无法缩短，希望可以参考postgresql的设计，在创建连接时增加保底的超时时间，控制故障范围，保证整个连接池不会长时间不可用。[https://github.com/alibaba/druid/pull/5337](https://github.com/alibaba/druid/pull/5337)

**Comment by kimmking** [comment]
socketTimeout设置了15分钟，那么connection timeout就应该大于15分钟（=connect+login）。

**Comment by zrlw** [comment]
这个问题属于网络故障触发tcp重传机制引发的深层次网络问题，问题的本质是操作系统tcp_retries2默认值15偏大，当数据库服务器物理宕机后，客户端要等大约924秒才拆除已建立的连接。
https://www.163.com/dy/article/HNV8K6JD0552RMA4.html

重现这个问题的方式比较简单，只是有点粗暴，要把数据库服务器直接物理宕机（不是执行reboot，是要直接关电源那种的效果），如果运行在虚机上，用虚机管理软件将其宕机。

如果应用有耗时长事务，socketTimeout就不容易设置了，设小了，数据库服务端正常运行的长事务会被截断，设长了，数据库服务器宕机时，客户端不能及时感知故障。
我看过一篇oracle的文档，网络环境好的内网数据库服务器场景下，可以将客户端操作系统的tcp_retries2设为3，当数据库服务节点宕机时，客户端只需等待2秒左右就能感知做故障切换了，socketTimeout这个参数依据业务设置，设得再大也不影响客户端及时感知服务端宕机。
我们遇到过这个问题，也和相关大厂做过技术沟通，他们系的银行把tcp_retries2这个参数统一调整为6，客户端大概等12秒就能感知服务端宕机。
![image](https://github.com/alibaba/druid/assets/40652892/c05429f4-2d94-42e4-8baf-23d5f13c0ebf)
