### ISSUE TITLE
多数据源失效，恢复后的重连

### ISSUE THREAD

**Issue by facedark** [alibaba/druid#5342]
遇到个目前业务场景的问题。部署项目时6个连接都是正常  由于网络原因断电原因会导致连接失败 正常情况是无限重连 但是会导致线程阻塞 所以设置了重连次数为1  。这样的设置又会导致 当恢复网络恢复供电时候 重连也失败了。 这样的场景不管怎么设置 都有弊端  能否有较完善的解决方案望告知

**Comment by gyl6666** [comment]
类似问题，设置了如下参数后，当网络断开时会重连。但重连一定次数后，就算后续网络恢复，在申请新的连接时，连接池不会再去尝试建立连接，在阻塞一定时间后，返回Connection refused。
druid.setConnectionErrorRetryAttempts(5);//失败重连5次
druid.setBreakAfterAcquireFailure(true);//请求失败后中断

**Comment by facedark** [comment]
> 类似问题，设置了如下参数后，当网络断开时会重连。但重连一定次数后，就算后续网络恢复，在申请新的连接时，连接池不会再去尝试建立连接，在阻塞一定时间后，返回Connection refused。 druid.setConnectionErrorRetryAttempts(5);//失败重连5次 druid.setBreakAfterAcquireFailure(true);//请求失败后中断

这个问题 后续我看了下源码  发现有一个方法是用来初始化链接的   某种程度上解决了我们遇到的问题  但是这个初始化的前提是必须是你的所有连接在部署项目启动的最开始要保证都是健康可以连接的状态  否则由于不会加入到连接池 也就不会初始化的时候重连这个连接    写上此方法名  希望对你有帮助   dynamicRoutingDataSource.afterPropertiesSet();

**Comment by lizongbo** [comment]
要么一直重连，要么超过重试次数停止重连，没有两全其美的方法
