### ISSUE TITLE
springboot3.x druid-spring-boot-3-starter 访问druid页面 404

### ISSUE THREAD

**Issue by fangweilong** [alibaba/druid#5346]
#5345 
参照这个issue。
如果出现java.lang.ClassNotFoundException: org.h2.Driver异常
请检查是否配置：driver-class-name。发现无法通过url自动识别，必须强制指定

**Comment by fangweilong** [comment]
这里还有个问题，必须要配置

**Comment by XinLau1996** [comment]
2023年7月12日 08:23:47  同样遇到问题，解决了踢我一下 我的配置文件：https://gitee.com/xinlau/agile/blob/master/src/main/resources/config/application.yml

**Comment by xiaoyuwang1987** [comment]
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
配了上面情况，还是启动报：java.lang.ClassNotFoundException: org.h2.Driver异常

**Comment by xiaoyuwang1987** [comment]
我有一个项目也是这个错，最后只能把账号密码 驱动都放在druid节点下配置，才能启动

**Comment by fangweilong** [comment]
> 2023年7月12日 08:23:47 同样遇到问题，解决了踢我一下 我的配置文件：https://gitee.com/xinlau/agile/blob/master/src/main/resources/config/application.yml

尝试配置一下org.springframework.boot.autoconfigure.AutoConfiguration.imports

**Comment by youapple** [comment]
可参考示例：https://github.com/youapple/hexadecimal-demo/tree/master/springboot3-druid

**Comment by dolphin-w** [comment]
```java
    @Bean
    @ConfigurationProperties(prefix = "spring.datasource",ignoreUnknownFields = true) // 读取配置文件中的数据源信息。Druid会以此建立数据库连接
    public DataSource dataSource() throws SQLException {
        DruidDataSource druidDataSource = new DruidDataSource();
        return druidDataSource;
    }
```
需要配置这个

**Comment by Waylon-Firework** [comment]
我是结合shardingsphere后404.如果不使用shardingsphere的话没有问题。

**Comment by li-fcb1899** [comment]
> 我有一个项目也是这个错，最后只能把账号密码 驱动都放在druid节点下配置，才能启动

我放在druid节点下也启动不了

**Comment by hellostronger** [comment]
<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
            <version>1.2.6</version>
</dependency>

   
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.4.3.4</version>
        </dependency>


<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.2.1</version>
 </dependency>

spring：
shardingsphere:
    props:
      sql:
        show: true
    datasource:                         # 合并多个连接池的监控数据，默认false
      common:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        # 初始连接数
        initial-size: 7
        # 最小连接池数量
        min-idle: 7
        # 最大连接池数量
        maxActive: 27
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        # 配置一个连接在池中最大生存的时间，单位是毫秒
        maxEvictableIdleTimeMillis: 900000
        #Oracle需要打开注释
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=1
        wall:
          multi-statement-allow: true
      names: db0
#      db1
      db0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/xxx?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
        username: root
        password: 123456
        min-idle: 10                                          # 最小连接数
        max-active: 20                                        # 最大连接数
        initial-size: 10                                       # 初始化大小
        max-wait: 60000                                       # 获取连接时的最大等待时间
        async-init: true                                      # 异步初始化加载
        min-evictable-idle-time-millis: 300000                # 一个连接在池中最小生存的时间，单位是毫秒
        time-between-eviction-runs-millis: 600000             # 多久才进行一次检测需要关闭的空闲连接，单位是毫秒
#        filters: stat,wall,log4j2                                 # 配置扩展插件：stat-监控统计，log4j-日志，wall-防火墙（防止SQL注入），去掉后，监控界面的sql无法统计
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=1
        validation-query: SELECT 1                            # 检测连接是否有效的 SQL语句，为空时以下三个配置均无效
        test-on-borrow: true                                  # 申请连接时执行validationQuery检测连接是否有效，默认true，开启后会降低性能
        test-on-return: true                                  # 归还连接时执行validationQuery检测连接是否有效，默认false，开启后会降低性能
        test-while-idle: true                                 # 申请连接时如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效，默认false，建议开启，不影响性能


这样能进druid页面，配置看着也是yml自己写的，但是有个问题是filter这个注释一打开就会报 tennatColumn缺失

**Comment by lizongbo** [comment]
等构建 1.2.20版本就ok了。
