### ISSUE TITLE
为什么缺省为3000，还会报慢sql日志

### ISSUE THREAD

**Issue by xiaoyuwang1987** [alibaba/druid#5356]
slow sql 2747 millis. delete from  .......,，看这个应该2747也没有大于3000的值，怎么也报这个慢sql的提示

**Comment by lizongbo** [comment]
应该是你的项目配置中有人自定义了slowSqlMillis的值。

**Comment by xiaoyuwang1987** [comment]
> 应该是你的项目配置中有人自定义了slowSqlMillis的值。
spring:
  datasource:
    url: jdbc:mysql://xxx.xxx.x.xx:3306/xxx?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: xxx
    password: xxx
    druid:
      max-active: 20
      max-open-prepared-statements: 5

我就定义了这些，还有这个我感觉是不是不影响 虽然日志级别是error,我可以改配置对吧， 还有我是不是可以把slowSqlMillis调大
