### ISSUE TITLE
JdbcUtils.getDriverClassName(String rawUrl)方法希望可以添加impala支持

### ISSUE THREAD

**Issue by luguangdong** [alibaba/druid#5358]
项目使用多数据源，其中有impala，在使用seata-xa模式下初始化数据源时，druid不支持impala报错
![image](https://github.com/alibaba/druid/assets/41789844/1ea22da6-6c85-4979-aa1d-a63e62da838f)

**Comment by lizongbo** [comment]
升级到最新版本，已经支持。
