### ISSUE TITLE
数据库TCP实际连接数超过maxActive

### ISSUE THREAD

**Issue by lizhengbin** [alibaba/druid#5359]
使用while(true)暴力压测发现数据库的TCP实际连接数大于maxActive，但此时poolingCount+aciveCount是小于maxActive的。实际会无限创建新连接最后导致达到数据库的最大连接数而创建连接失败。
druid版本1.2.16

![image](https://github.com/alibaba/druid/assets/8109610/bdeeb784-4fa7-4e08-94a6-efe3f58b159a)

![image](https://github.com/alibaba/druid/assets/8109610/f72c1ef5-6fb0-46d7-8335-afed48d6e3c7)

![image](https://github.com/alibaba/druid/assets/8109610/ba9a0e59-36c6-40f9-9643-2198d96ffc1f)

**Comment by WaitRainbow** [comment]
请问最终是怎么解决该问题的
