### ISSUE TITLE
mybatis下解析动态表名报错 druid版本1.2.19-SNAPSHOT

### ISSUE THREAD

**Issue by ashinewu** [alibaba/druid#5360]
当表名中含有动态参数时，解析是有问题的。
例如select c_id from t_a_file_? order by c_id desc limit 1 
![image](https://github.com/alibaba/druid/assets/49027834/258c0e1a-4208-472a-a4ca-fc8ea3d018d0)

也搜到了其他issues，发现大佬已经回复，但是仍然无效。
https://github.com/alibaba/druid/issues/3542
<img width="574" alt="image" src="https://github.com/alibaba/druid/assets/49027834/65f5b5a6-1b23-4310-ac03-bfdd307de93b">

这里还有个类似的问题 https://github.com/alibaba/druid/issues/5271

麻烦大佬们解决一下！

**Comment by lizongbo** [comment]
啥场景会有这种问号拼在一起的表名？

**Comment by ashinewu** [comment]
> 啥场景会有这种问号拼在一起的表名？

分表时

**Comment by lizongbo** [comment]
表名应该整个是问好，而不是一半表名一半问号。
