### ISSUE TITLE
druid-spring-boot-3-starter不支持jakarta 

### ISSUE THREAD

**Issue by OneFAnn** [alibaba/druid#5367]
native-image编译成功，但运行exe文件报错

```
Caused by: java.lang.NullPointerException: null
        at com.alibaba.druid.spring.boot3.autoconfigure.DruidDataSourceWrapper.afterPropertiesSet(DruidDataSourceWrapper.java:39)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1816)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
        ... 92 common frames omitted
```

**Comment by OneFAnn** [comment]
spring boot 3.1.1
druid-spring-boot-3-starter  1.2.18

**Comment by OneFAnn** [comment]
原因可能是使用@ConfigurationProperties注解的配置类里有嵌套的类，需要使用@NestedConfigurationProperty。
例如：
@ConfigurationProperties(prefix = "my.properties")
public class MyProperties {

    private String name;

    @NestedConfigurationProperty
    private Nested nested = new Nested();

    // getters / setters...

}

**Comment by Lambdua** [comment]
我打包成native-image启动后也报这个错，请问如何解决
```java
Caused by: java.lang.NullPointerException: null
        at com.alibaba.druid.spring.boot3.autoconfigure.DruidDataSourceWrapper.afterPropertiesSet(DruidDataSourceWrapper.java:39) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1817) ~[com.bdip.ai.AiChatApplication:6.0.11]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766) ~[com.bdip.ai.AiChatApplication:6.0.11]
        ... 16 common frames omitted

```

**Comment by Tokzchen** [comment]
想看看springboot3是怎么集成druid的，不知为何配置一直失效

**Comment by OneFAnn** [comment]
> 我打包成native-image启动后也报这个错，请问如何解决
> 
> ```java
> Caused by: java.lang.NullPointerException: null
>         at com.alibaba.druid.spring.boot3.autoconfigure.DruidDataSourceWrapper.afterPropertiesSet(DruidDataSourceWrapper.java:39) ~[na:na]
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1817) ~[com.bdip.ai.AiChatApplication:6.0.11]
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766) ~[com.bdip.ai.AiChatApplication:6.0.11]
>         ... 16 common frames omitted
> ```

没解决，怀疑是StatViewServlet 和 WebStatFilter 自动配置失效的问题
@ConfigurationProperties("spring.datasource.druid")
public class DruidStatProperties {
    private String[] aopPatterns;
    private StatViewServlet statViewServlet = new StatViewServlet();   
    private WebStatFilter webStatFilter = new WebStatFilter();

**Comment by OneFAnn** [comment]
> 想看看springboot3是怎么集成druid的，不知为何配置一直失效

如果是单纯想在springboot3用，依赖换成下面这个
            
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-3-starter</artifactId>
                <version>${druid.version}</version>
            </dependency>

**Comment by liao-can-jie** [comment]
配置文件是怎么配置的，我提供下自己配置的
```batchfile
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
      db-type: mysql
      filter:
        config:
          enabled: true
        stat:
          enabled: true
      filters: stat,wall,slf4j
      initial-size: 5
      max-active: 20
      max-pool-prepared-statement-per-connection-size: -1
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      min-idle: 5
      pool-prepared-statements: false
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1
      validation-query-timeout: 1
      stat-view-servlet:
        allow: 127.0.0.1
        enabled: true
        login-password: 123456
        login-username: root
        reset-enable: true
        url-pattern: /druid/*
      web-stat-filter:
        enabled: true
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
        session-stat-enable: true
        session-stat-max-count: 100
        url-pattern: /*
```

**Comment by lizongbo** [comment]
最新代码已经支持springboot3，待构建 1.2.20版本
