### ISSUE TITLE
PG Select语法For子句bug

### ISSUE THREAD

**Issue by Icarus124** [alibaba/druid#5368]
语法格式：SELECT ... 
[ FOR { UPDATE | NO KEY UPDATE | SHARE | KEY SHARE } [ OF table_name [, ...] ] [ NOWAIT | SKIP LOCKED ] [...] ]
在master分支PGSelectParser类第217行：

> if (lexer.token() == Token.OF) {
>                 for (; ; ) {
>                     SQLExpr expr = this.createExprParser().expr();

if判断后解析table_name，需要先执行一次lexer.nextToken();

**Comment by lizongbo** [comment]
反馈问题请发完整示例SQL
