### ISSUE TITLE
1.2.5版本 JdbcConstants 中 KINGBASE8_DRIVER常量错误

### ISSUE THREAD

**Issue by wangyuhao12138** [alibaba/druid#5370]
![image](https://github.com/alibaba/druid/assets/140132230/ca7ed8cb-cafc-4789-b2fa-99f5c5d46d9d)

**Comment by lizongbo** [comment]
新版本早已修复这个bug，请升级使用最新版。

![image](https://github.com/alibaba/druid/assets/1670666/aabc10cb-22f1-4a5c-9a8b-2ff7b2591027)
