### ISSUE TITLE
native-image编译和运行exe都成功，但请求一直阻塞

### ISSUE THREAD

**Issue by liao-can-jie** [alibaba/druid#5371]
window10
graalvm-ce-java17-22.3.0
spring boot 3.1.1
druid-spring-boot-3-starter 1.2.18
native-image编译和运行exe都成功，但请求一直阻塞
![image](https://github.com/alibaba/druid/assets/70512659/828f8c85-00a1-43af-9b97-9d33f4f801b0)

**Comment by kimmking** [comment]
native image以后，druid 配置没有加载上。

**Comment by liao-can-jie** [comment]
本地配置文件和maven都加上了druid

**Comment by lizongbo** [comment]
> > 本地配置文件和maven都加上了druid
> 
> 我的运行也失败了，是因为现在 druid 还不支持 graalvm 吗 错误信息：
> 
> ```
> 2023-12-20 06:50:46.782 [main] WARN  o.s.b.w.s.c.ServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'shiroFilter': Unsatisfied dependency expressed through method 'shiroFilter' parameter 0: Error creating bean with name 'dataSourceConfig': Unsatisfied dependency expressed through field 'druidConfig': Error creating bean with name 'dataSourceConfig.DruidProperties': Could not bind properties to 'DataSourceConfig.DruidProperties' : prefix=spring.datasource, ignoreInvalidFields=false, ignoreUnknownFields=true
> 2023-12-20 06:50:46.783 [main] ERROR o.s.b.diagnostics.LoggingFailureAnalysisReporter - 
> 
> ***************************
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> Failed to bind properties under 'spring.datasource.druid' to java.util.Properties:
> 
>     Property: spring.datasource.druid.test-on-return
>     Value: "false"
>     Origin: class path resource [application.yml] - 74:23
>     Reason: failed to convert java.util.LinkedHashMap<?, ?> to java.util.Properties (caused by java.lang.NoSuchMethodException: java.util.Properties.<init>())
> 
> Action:
> 
> Update your application's configuration
> ```
> 
> 配置：
> 
> ```
>   datasource:
>     type: com.alibaba.druid.pool.DruidDataSource
>     druid:
>       driver-class-name: org.mariadb.jdbc.Driver
>       initial-size: 5
>       max-active: 100
>       min-idle: 5
>       max-wait: 60000
>       keep-alive: true
>       pool-prepared-statements: true
>       max-pool-prepared-statement-per-connection-size: 20
>       min-evictable-idle-time-millis: 600000 # 配置一个连接在连接池中的最小生存时间，单位毫秒
>       max-evictable-idle-time-millis: 900000 
>       validation-query: select 1 # 用来检测连接是否有效的sql
>       validation-query-timeout: 1 # 单位：秒，检测连接是否有效的超时时间
>       test-while-idle: true # 如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
>       time-between-eviction-runs-millis: 5000 # 配置间隔多久进行一次检测，检测需要关闭的空闲连接，单位毫秒
>       test-on-borrow: false # 配置从连接池获取连接时，是否检查连接有效性，true每次都检查；false不检查
>       test-on-return: false # 配置向连接池归还连接时，是否检查连接有效性，true每次都检查；false不检查
> ```

近期我来研究一下。

**Comment by zcw159357** [comment]
https://blog.zcw159357.com/article/1/2023-01-27-2301.html
我之前搞过druid的native-image 打了本地包 能成功运行 可以参考下看

**Comment by lizongbo** [comment]
等1.2.22构建出来之后再验证吧

https://github.com/alibaba/druid/pull/5671
