### ISSUE TITLE
1.2.18版本，其它类型的db初始化报错。

### ISSUE THREAD

**Issue by Angle-bo** [alibaba/druid#5373]
使用1.2.18版本，数据源初始化报错。报错代码DruidAbstractDataSource.createPhysicalConnection
![image](https://github.com/alibaba/druid/assets/16486675/c616b3e1-2f38-4829-adec-2ddfea83c340)

获取不到dbTypeName时，这里是不是可以改为:
`if (dbTypeName!=null && dbTypeName.equals(DbType.sqlserver.name())) `

**Comment by Angle-bo** [comment]
项目使用了tdengine，不是com.alibaba.druid.DbType中兼容的类型。
之前使用的durid-1.2.8版本是，可以正常初始化数据源。1.2.18版本，dbTypeName为空的情况，强制equals导致报错。

**Comment by 450925854** [comment]
相同的问题， 连impala之后就挂了。。
只能先回滚了。。

**Comment by zjwon** [comment]
遇到相同的问题，升级到1.2.18时发现不兼容lindorm，智能回退到1.2.16，但是1.2.16版本connectTimeout、socketTimeout两个参数又有bug

**Comment by Angle-bo** [comment]
使用1.2.18版本，临时解决办法，项目中重写com.alibaba.druid.pool.DruidAbstractDataSource。1764行替换为：
`if (dbTypeName!=null && dbTypeName.equals(DbType.sqlserver.name()))`
项目正常使用，先测试，等遇到新问题在看。

**Comment by kimmking** [comment]
Druid use a whitelist to ensure the db type MUST BE in supported list.
The UNKNOWN db type and its JDBC driver maybe cause something invalid, so If you want to add a new db type, make a PR to support it explicitly.
