### ISSUE TITLE
请更新一下DruidDataSource配置属性列表

### ISSUE THREAD

**Issue by CoderFreeMan** [alibaba/druid#5375]
https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8

**Comment by lizongbo** [comment]
近期我来更新一下

**Comment by lizongbo** [comment]
https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8

更新了一版，看下有没有什么不清楚的地方，我继续优化说明
