### ISSUE TITLE
1.2.x中MySQL语法收敛问题

### ISSUE THREAD

**Issue by Joey777210** [alibaba/druid#5381]
原始SQL：`select * from table where id in (+100, 200, 300, 400, 500)`
期望结果：`select * from table where id in (?)`
druid1.1.x：`select * from table where id in (?)`
druid1.2.x:`select * from table where id in (+?, ?, ?, ?, ?)`

**Comment by lizongbo** [comment]
试了一下bug复现了，我看下好不好适配修复
