### ISSUE TITLE
如何過濾特定內容

### ISSUE THREAD

**Issue by vt167098** [alibaba/druid#5382]
如何可以在druid設定攔截特定的資料內容, 比方從資料庫讀取的資料, 過濾符合特定條件的內容, 進一步修改內容後再送出結果, 或在回寫到資料庫前, 修改符合條件的內容後, 再送回資料庫.

**Comment by lizongbo** [comment]
描述有点抽象，不确定你具体要修改什么样的内容。
正常来讲，利用filter机制，继承FilterEventAdapter，然后在statementExecuteQueryAfter或resultSetOpenAfter等方法中加入自己的定制逻辑，修改返回的结果集即可。在写入之前，则是在statementExecuteBefore等方法中加入定制逻辑。
