### ISSUE TITLE
执行日志不打印

### ISSUE THREAD

**Issue by XuJincai** [alibaba/druid#5388]
spring-boot
![微信截图_20230803113617](https://github.com/alibaba/druid/assets/16322049/afe98c5d-cde1-4363-89c1-4449f065f923)
druid
![微信截图_20230803113629](https://github.com/alibaba/druid/assets/16322049/0bc04de2-5818-4321-ab4f-36a630153d57)
配置文件
![微信截图_20230803113541](https://github.com/alibaba/druid/assets/16322049/68aca2b8-91bb-403e-953c-e5a3ed9e23e1)
![微信截图_20230803113550](https://github.com/alibaba/druid/assets/16322049/e73c311b-ead3-4919-907c-b33dcd60bc7a)

**Comment by lizongbo** [comment]
自己核实配置和log组件依赖
