### ISSUE TITLE
springboot3 , jdk17环境下

### ISSUE THREAD

**Issue by Tokzchen** [alibaba/druid#5393]
因为缺失自动装配，我，在resource目录下添加了META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports文件后项目启动没有问题，但
发现对jakarta.activation.DataSource这个类的数据源Autowired失败，只能注入com.alibaba.druid.spring.boot3.autoconfigure.DruidDataSourceWrapper

报错信息:
Bean named 'dataSource' is expected to be of type 'jakarta.activation.DataSource' but was actually of type 'com.alibaba.druid.spring.boot3.autoconfigure.DruidDataSourceWrapper'

**Comment by Tokzchen** [comment]
补充一下，引入的依赖是 druid-spring-boot-3-starter,1.2.18

**Comment by OneFAnn** [comment]
![image](https://github.com/alibaba/druid/assets/26647611/fc24bddf-3cc4-48da-aac1-897df1c963e6)
不支持jakarta

**Comment by OakHoo** [comment]
druid-spring-boot-3-starter  1.2.19版本解决这个问题了吗

**Comment by lizongbo** [comment]
数据源class是 java.sql.DataSource，而不是jakarta.activation.DataSource。
等1.2.20版本构建出来，就可以正常使用druid-spring-boot-3-starter了。

**Comment by VanmathiMuthusamy** [comment]
Will 1.2.20 version support for spring boot 3?

**Comment by lizongbo** [comment]
> Will 1.2.20 version support for spring boot 3?
yes, 1.2.20 released:

https://repo1.maven.org/maven2/com/alibaba/druid/1.2.20/

**Comment by shook2012** [comment]
> > Will 1.2.20 version support for spring boot 3?
> > yes, 1.2.20 released:
> 
> https://repo1.maven.org/maven2/com/alibaba/druid/1.2.20/

1.2.20也不支持 stat-view-servlet呀~

**Comment by lizongbo** [comment]
> > > Will 1.2.20 version support for spring boot 3?
> > > yes, 1.2.20 released:
> > 
> > 
> > https://repo1.maven.org/maven2/com/alibaba/druid/1.2.20/
> 
> 1.2.20也不支持 stat-view-servlet呀~


spring.datasource.druid.stat-view-servlet.enabled=true

这样启用配置是ok的。

有问题再重新反馈。
