### ISSUE TITLE
使用mysql的情况下，启动报异常：java.lang.ClassNotFoundException: org.h2.Driver

### ISSUE THREAD

**Issue by li-fcb1899** [alibaba/druid#5397]
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
     driver-class-name: com.mysql.cj.jdbc.Driver

如上配置，启动报异常：java.lang.ClassNotFoundException: org.h2.Driver

**Comment by li-fcb1899** [comment]
spring boot 3.12
druid-spring-boot-3-starter 1.2.18

**Comment by zmx198768** [comment]
![image](https://github.com/alibaba/druid/assets/20762941/27f6013e-998b-469a-80a4-80787d11ab4d)
强啊，druid开发人员

**Comment by leideqin** [comment]
我也遇到这个问题了，根本没法用。

**Comment by lizongbo** [comment]
等构建出最新的druid版本 1.2.20就可以了。
