### ISSUE TITLE
1.2.8 开启testOnBorrow不断重试数据库连接

### ISSUE THREAD

**Issue by yangBin666** [alibaba/druid#5398]
druid1.2.8版本，通过pgbouncer连接池连接pgsql数据库(9.2.24版本)

开启了testOnBorrow参数，在服务oom之后一段时间后，以300/s左右的频率不断请求/关闭数据库连接
pgbouncer端日志：
![image](https://github.com/alibaba/druid/assets/18570574/cb1b155c-49ad-4381-8393-70ba1825cd1e)
服务后端无大量请求日志：相关报错只有
```
15:43:14 create connection SQLException,url:xxxx.xx.xx.xx errorCode 0， state 08P01 ，PSQLException：ERROR：client_login_timeout
```
备注：不能稳定复现

**Comment by kimmking** [comment]
08P01 是协议错误，是否存在客户端驱动，pgbouncer跟pg sql server的版本不兼容？

**Comment by yangBin666** [comment]
> 08P01 是协议错误，是否存在客户端驱动，pgbouncer跟pg sql server的版本不兼容？
正常情况下是可以正常连接的，应该不存在版本不兼容的情况
