### ISSUE TITLE
StatFilter 定位慢sql的时候有个痛点，就是只能看到慢sql语句无法看到程序调用堆栈，能否提个pr进行增强一下

### ISSUE THREAD

**Issue by jackyyyyyssss** [alibaba/druid#5399]

**Comment by lizongbo** [comment]
自己继承StatFilter 实现该效果即可，框架默认开启探测堆栈会增大性能开销。

我就是继承StatFilter 定制了增强特性，把mybatis的mapper方法放到threadlocal里，然后在慢sql，慢事务等场景下，输出对应的方法名到日志，定位sql触发来源很方便。

**Comment by jackyyyyyssss** [comment]
已经实现了 ，主要看看是不是能贡献一下，搞个开关即可
