### ISSUE TITLE
dbTypeName 为空时，equals判断会报NullPoint

### ISSUE THREAD

**Issue by PerrySeven** [alibaba/druid#5403]
1.2.18版本中 DruidAbstractDataSource 1764 行 
使用dbTypeName 判断，若是dbtypename 获取失败，这里会报空对象
else if (dbTypeName.equals(DbType.sqlserver.name())) {

else if (DbType.sqlserver.name().equals(dbTypeName)) {

**Comment by lizongbo** [comment]
升级 到1.2.19版本，这个bug已经修复了。
