### ISSUE TITLE
druid: 1.2.6，jdk：1.8 oracle jdk

### ISSUE THREAD

**Issue by jieli-cqwl** [alibaba/druid#5410]
警告：The POM for com.alibaba:druid:jar:1.2.6 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

问题：忽略警告会有实际影响吗？

**Comment by lizongbo** [comment]
请使用  1.2.20 
https://github.com/alibaba/druid/releases/tag/1.2.20
