### ISSUE TITLE
1.2.18版本SQLUtils.parseStatements解析GP时报错

### ISSUE THREAD

**Issue by lindasunren** [alibaba/druid#5413]
不支持update ... set ... from ... where ...
`String sql = "update  WORK.TABLE1 t\n" +
                    "set open_date = cast(to_char(a.d_opentimestamp, 'yyyMMdd') as int4)\n" +
                    "from WORK.TABLE2 a\n" +
                    "where t.acco=a.acco\n" +
                    "\tand t.sys='KEY';";`
`List<SQLStatement> sqlStatements = SQLUtils.parseStatements(sql,JdbcConstants.GREENPLUM);`

解析报错：
com.alibaba.druid.sql.parser.ParserException: not supported.pos 93, line 3, column 2, token IDENTIFIER FROM
at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:615)
at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:599)
at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:620)

替换成`String sql = "update  WORK.TABLE1 t\n" +
                    "set open_date=19000101\n" +
                    "where sys='KEY';";` 执行成功
或者替换成`List<SQLStatement> sqlStatements = SQLUtils.parseStatements(sql,JdbcConstants.POSTGRESQL);` 执行成功

**Comment by lizongbo** [comment]
是createSQLStatementParser的时候，没有将GREENPLUM适配进去，修复代码很简单，我加一下
```
           case postgresql:
            case greenplum:
            case edb:
                return new PGSQLStatementParser(sql, features);

```
