### ISSUE TITLE
在并发高的时候，连接获取失败，但是连接数量远远没有达到配置的最大数量

### ISSUE THREAD

**Issue by GSY1** [alibaba/druid#5418]
使用oceanBase 数据库，配置了maxActive为500，但是在并发高的时候，每次active 为8，runningsqlCount 为8的时候，就会报获取数据库连接失败，druid:1.0.13

**Comment by zhangxiaozhang** [comment]
我使用1.2.1版本时正常。升级到1.2.18时 。报同样的问题。

**Comment by kimmking** [comment]
> 使用oceanBase 数据库，配置了maxActive为500，但是在并发高的时候，每次active 为8，runningsqlCount 为8的时候，就会报获取数据库连接失败，druid:1.0.13

版本很老了。试试新版本。

**Comment by GSY1** [comment]
> > 使用oceanBase数据库，配置了maxActive为500，但是在并发高的时候，每次active为8，runningsqlCount为8的时候，报获取数据库连接失败，druid:1.0.13
> 
> 版本很老了。尝试新版本。

能分析一下可能产生这个问题的原因吗，查了好久没有任何头绪
