### ISSUE TITLE
SQL解析错误: CREATE TABLE AS WITH SELECT 语法 | durid 1.2.18 ｜db.mysql

### ISSUE THREAD

**Issue by wfy-belief** [alibaba/druid#5421]
## 原始SQL
```sql
create table if not exists t2 as
with X as ( select * from t1)
select * from X;
```

![image](https://github.com/alibaba/druid/assets/58450591/126843c4-53d7-4def-ac43-801b378043d7)

![image](https://github.com/alibaba/druid/assets/58450591/1992c2c3-4e53-48f5-83df-a4e382915144)

被解析为了两个语句

## 额外信息

mysql8.0版本

**Comment by lizongbo** [comment]
bug复现了，我加下解析逻辑来支持
