### ISSUE TITLE
求交流的地方，有么有微信群？

### ISSUE THREAD

**Issue by ywy2090** [alibaba/druid#5424]

**Comment by lizongbo** [comment]
目前没有微信群，我也是因为要反馈bug提交代码，才找人联系到了温少，有啥问题就在这里issue里提出来，我如果能搞定的，我可以搞定一部分，搞不定的，就等温少来处理。

**Comment by ywy2090** [comment]
> 目前没有微信群，我也是因为要反馈bug提交代码，才找人联系到了温少，有啥问题就在这里issue里提出来，我如果能搞定的，我可以搞定一部分，搞不定的，就等温少来处理。
> 
> 

好的 感谢
