### ISSUE TITLE
为什么PGSQLStatementParser不重写parseCreateFunction方法

### ISSUE THREAD

**Issue by LHCBYT** [alibaba/druid#5429]
我希望通过Druid来创建pg的function，但是发现开启wall后，PGSQLStatementParser不重写parseCreateFunction方法，导致语法分析错误，无法创建pg的function，只能关闭wall才能创建
请问为什么PGSQLStatementParser不重写parseCreateFunction方法，是有什么特殊理由吗

**Comment by kimmking** [comment]
暂不支持这个功能。你如果感兴趣可以提交一个PR。
