### ISSUE TITLE
Hive 解析时建表语句不支持 NULL  DEFIND AS 和STORED AS语句

### ISSUE THREAD

**Issue by Jespncheng** [alibaba/druid#5430]

**Comment by lizongbo** [comment]
发详细的触sql样本来

**Comment by Jespncheng** [comment]
> 发详细的触发异常的sql样本来

Create table if not exists data01.test_20230830(a string ,b string) PARTITIONED BY (load_date date, org string) ROW FORMAT DELIMITED NULL DEFINED AS '' STORD AS ORC;

报错信息com.alibaba.Druid.sql.parse.parserException:syntax error,expect FIELDS,actual NULL,pod 155,line 1,column 151,token NULL

at com.alibaba.Druid.sql.parse.SQLParser.HiveCreateTableParser.parseCreateTabke(HiveCreateTableParser.java:197)

**Comment by lizongbo** [comment]
单测验证了下最新包代码是不会报错的，能解析，但是缺少后面一部分 定义信息：

```

    @Test
    public void test_createTable() throws Exception {
        DbType dbType = DbType.hive;
        String sql="Create table if not exists data01.test_20230830(a string ,b string) "
            + "PARTITIONED BY (load_date date, org string) ROW FORMAT DELIMITED NULL DEFINED AS '' STORD AS ORC;";
        SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, dbType);
        SQLStatement statement = parser.parseStatement();
        System.out.println("原始的sql===" + sql);
        String newSql=statement.toString().replace("\n","").replace('\'','"')+";";
        System.out.println("生成的sql===" + newSql);
        System.out.println("生成的statement===" + statement.getClass());
        assertTrue(newSql.equalsIgnoreCase(sql));
        SchemaStatVisitor visitor = SQLUtils.createSchemaStatVisitor(dbType);
        statement.accept(visitor);
        System.out.println("getTables==" + visitor.getTables());
        Map<Name, TableStat> tableMap = visitor.getTables();
        assertFalse(tableMap.isEmpty());

    }

```

执行结果：
原始的sql===Create table if not exists data01.test_20230830(a string ,b string) PARTITIONED BY (load_date date, org string) ROW FORMAT DELIMITED NULL DEFINED AS '' STORD AS ORC;

生成的sql===CREATE TABLE IF NOT EXISTS data01.test_20230830 (	a string,	b string)PARTITIONED BY (	load_date date,	org string)ROW FORMAT DELIMITED;

我看下好加解析的话，我就加一下

**Comment by lizongbo** [comment]
另外这个语句本身就有错吧？ 不是 STORD AS ORC ,应该是 STORED AS ORC
https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL
