### ISSUE TITLE
应用重启后出现dataSource already closed

### ISSUE THREAD

**Issue by WiseSheep1** [alibaba/druid#5435]
应用重启后出现dataSource already closed，再重新启动后恢复正常

**Comment by WiseSheep1** [comment]
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: ### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is com.alibaba.druid.pool.DataSourceClosedException: dataSource already closed at Sat Sep 09 01:08:19 CST 2023

**Comment by kimmking** [comment]
偶发的还是必现的？出现问题时所有的连接都close掉了，还是只有个别连接？
是否开了testOnXXX之类的参数。这个问题出现的原因是 从连接池获取到一个连接，但是这个链接已经不可用了。按道理不会出现的，感觉就是两个情况：
1、应用和数据库之间的网络出了问题，或者数据库自己出了问题，导致中间的连接断开了。同时没开保活。
2、应用的关闭或者没有成功启动的时候，连接池执行了close，这个时候还有业务在操作。
两个情况都不太正常。你可以按这个思路排查。
