### ISSUE TITLE
druid-spring-boot-3-starter中的src/main/resources目录中的properties文件

### ISSUE THREAD

**Issue by dingzhaojun2046** [alibaba/druid#5437]
druid-spring-boot-3-starter中的src/main/resources目录中放入这么多properties文件，是怎么考虑的呢？

**Comment by yinyuncan** [comment]
同问，引入后直接报错，我得想个办法屏蔽他

**Comment by zmx198768** [comment]
> druid-spring-boot-3-starter中的src/main/resources目录中放入这么多properties文件，是怎么考虑的呢？

新手开发，代码无人审核，才会犯的低级错误。。。他们写的配置项太多，命令行覆盖不太靠谱，建议删掉重新打包。
