### ISSUE TITLE
Postgresql 无法解析 alter database 语句

### ISSUE THREAD

**Issue by Aaron3S** [alibaba/druid#5444]
如图 缺少 PGAlterDatabaseStmt 类

![image](https://github.com/alibaba/druid/assets/34506289/2098181d-55ec-4cb3-89aa-8116d4c82525)

**Comment by lizongbo** [comment]
发个完整的验证的sql样本来。

**Comment by Aaron3S** [comment]
比如 alter database 'aaa' rename to ccc
