### ISSUE TITLE
对于mysql语法的UPDATE语句解析错误

### ISSUE THREAD

**Issue by hrb-yanght** [alibaba/druid#5445]
对于mysql语法的UPDATE语句解析错误

例如 update a set b=c and df=as and cs=fs 这种语句会将 and df=as and cs=fs  解析为条件(CONDITION)

**Comment by lizongbo** [comment]
这种写法虽然mysql是支持，但是实际容易导致生产问题，我们已经在生产被别的同事写这样的sql坑过了，建议调整sql写法。
