### ISSUE TITLE
executeBatch无法获取更新条目数，无法进行判断乐观锁相关

### ISSUE THREAD

**Issue by Wilson-Lai-Zzz** [alibaba/druid#5448]
com.alibaba.druid.proxy.jdbc.StatementProxyImpl#executeBatch
这里的代码没理解意义，但是会覆盖掉jdbc的更新条目数，而且拿第一行意义好像不大
![image](https://github.com/alibaba/druid/assets/32032164/6860d413-2809-4c62-8e8e-c888793022cc)

**Comment by kimmking** [comment]
这段代码返回的updateCount不就是更新数吗？

**Comment by Wilson-Lai-Zzz** [comment]
其实不是的，JDBC.executeBatch返回的是-2表示的是sql没有问题，不管数据的更新行数
updateCounts = 1的时候就会有问题
![image](https://github.com/alibaba/druid/assets/32032164/94212f27-d34e-4564-b479-8e50c48f1953)
如果updateCounts != 1还是可以获得正确的数据
把这个判断去掉好像就可以

**Comment by lizongbo** [comment]
发个完整的测试用例代码吧
