### ISSUE TITLE
Bug:socketTimeout参数不支持mysql jdbcurl里设置socketTimeout=0的场景

### ISSUE THREAD

**Issue by lizongbo** [alibaba/druid#5451]
参考：
https://github.com/alibaba/druid/issues/5419
https://dev.mysql.com/doc/connector-j/8.1/en/connector-j-connp-props-networking.html

mysql的jdbc url里，connectTimeout和socketTimeout，在不指定的情况下，默认是0表示永不超时，我们的项目中一直没设置这个值，可以配置的值范围是 0 - 2147483647

而druid现在的初始化过程中，在按url识别参数后，针对等于0的，强制设置成了默认值10秒。

![image](https://github.com/alibaba/druid/assets/1670666/8a366a8e-e861-439c-b922-d0d1d9a1ae5e)

导致即使想通过只修改jdbc url来实现继续保持永久超时，也是没办法做到了。

![image](https://github.com/alibaba/druid/assets/1670666/f2c23d8b-bd54-4cf4-ad86-3f35cf3ff2da)

修复方式，把设置默认值的逻辑放到前面即可

![image](https://github.com/alibaba/druid/assets/1670666/0d002f09-5331-435b-b89d-85138bad518b)

**Comment by qq592304796** [comment]
@wenshao 现在升级之后，默认是10s，之前默认是0不超时，现在是必须要指定socketTimeout参数吗？

**Comment by lizongbo** [comment]
> @wenshao 现在升级之后（1.2.20），默认是10s，之前默认是0不超时，现在是必须要指定socketTimeout参数吗？

目前的版本是这样，这个对从低版本升级上来的项目很不友好，我在纠结要不要把设置默认10s的逻辑去掉。
