### ISSUE TITLE
使用druid1.2.11之后不能自动释放数据库连接

### ISSUE THREAD

**Issue by shiyuesky** [alibaba/druid#5461]
请教大师,我一直使用DruidDataSource: 
<bean id="dataSource"
class="com.alibaba.druid.pool.DruidDataSource" init-method="init"
destroy-method="close">
但是在1.2.11后就发现一个问题:使用这个连接数据库连接池的,打包war包到tomcat的webapp目录下使用没有问题,但是删除war包的时候(tomcat依旧运行,热部署war包).此时的该war包对应项目生成的数据库连接不被释放,除非关闭tomcat,但是1.2.11版本就可以正常释放,数据库是oracle11.2
druid1.2.11之后的版本都有这个问题

**Comment by zrlw** [comment]
如果用的是mysql而且配置了keepAlive=true，可以试试配置druid.mysql.usePingMethod=false
1.2.11修改了mysql的默认探活方式，之前默认调用mysql驱动的pingInternal，从1.2.11开始默认改成执行select 1了。
