### ISSUE TITLE
springboot3 + tomcat10 + druid1.2.20 IllegalStateException

### ISSUE THREAD

**Issue by Lehyu** [alibaba/druid#5469]
Failed to bind properties under 'spring.datasource.password-callback' to javax.security.auth.callback.PasswordCallback:

    Reason: java.lang.IllegalStateException: Failed to extract parameter names for public javax.security.auth.callback.PasswordCallback(java.lang.String,boolean)

<img width="1370" alt="image" src="https://github.com/alibaba/druid/assets/14256558/9555022b-bad6-40db-bde8-d188ad92b683">

**Comment by Lehyu** [comment]
JVM Version:           17.0.8.1+1
JVM Vendor:            Eclipse Adoptium
TOMCAT Version:    10.1.15

**Comment by lizongbo** [comment]
贴一下完整的application.properties里的ddruid相关配置

**Comment by Lehyu** [comment]
> 贴一下完整的application.properties里的ddruid相关配置

![image](https://github.com/alibaba/druid/assets/14256558/996ad49a-4087-422a-9682-ac2061ca3760)

**Comment by lizongbo** [comment]
配置应该是 spring.datasource.druid.password-callback
而不是spring.datasource.password-callback
