### ISSUE TITLE
druid-boot3 1.2.20版本无法打开监控

### ISSUE THREAD

**Issue by TangFangrun** [alibaba/druid#5473]
当配置      stat-view-servlet:
        enabled: true
启动项目会报错：This is because there is more than one mappable servlet in your servlet context: {org.springframework.web.servlet.DispatcherServlet=[/], com.alibaba.druid.support.jakarta.StatViewServlet=[/druid/*]}.改为false就可以正常启动

**Comment by aibozeng** [comment]
我昨天也发现了这个问题。环境是 springboot3.1.3, springwebsecurity, druid-boot3 1.2.20 。

**Comment by aibozeng** [comment]
误诊了， springboot3.1.3 和  druid-boot3 1.2.20  没有问题，能出来监控页面。问题发现是出在 spring web security 身上，当要配置具体的匿名可访问页面时，就会出现楼上说的问题，当你不指定具体页面，全部可匿名访问，例如： auth.anyRequest().permitAll()，就OK了。 要解决：再搞搞spring web security , 解决 MvcRequestMatcher 和 request mapping 分流 DispatcherServlet  StatViewServlet ；

**Comment by TangFangrun** [comment]
> 误诊了， springboot3.1.3 和 druid-boot3 1.2.20 没有问题，能出来监控页面。问题发现是出在 spring web security 身上，当要配置具体的匿名可访问页面时，就会出现楼上说的问题，当你不指定具体页面，全部可匿名访问，例如： auth.anyRequest().permitAll()，就OK了。 要解决：再搞搞spring web security , 解决 MvcRequestMatcher 和 request mapping 分流 DispatcherServlet StatViewServlet ；

老哥说的对，给过滤链加上一句    .requestMatchers(new MvcRequestMatcher(handlerMappingIntrospector, "/druid/**")).permitAll()  就ok了

**Comment by Wang-Yumin** [comment]
@aibozeng 具体怎么搞？请教一下，老师！

**Comment by OneFAnn** [comment]
> @aibozeng 具体怎么搞？请教一下，老师！

springboot3.1.4开始才有这个问题
在spring security的配置中 requestMatchers配置的资源路径需要指明AntPathRequestMatcher还是MvcRequestMatcher；
在我的场景中我需要的是AntPathRequestMatcher：
import static org.springframework.security.web.util.matcher.AntPathRequestMatcher.antMatcher;
资源路径都用antMatcher包起来了，如：antMatcher("/druid/**")

**Comment by aibozeng** [comment]
handlerMappingIntrospector 是用于查找可用的Servlet对象，可以直接 new HandlerMappingIntrospector() 一个来使用吗？我没有继续研究了，期望你们在 使用手册中，增加对 spring security web 的支持的 描述。
----- 原始邮件 -----
发件人：TangFangrun ***@***.***>
收件人：alibaba/druid ***@***.***>
抄送人：zeng ***@***.***>,  Comment ***@***.***>
主题：Re:_[alibaba/druid]_druid-boot3_1.2.20版本无法打开监控_(Issue_#5473)
日期：2023年11月08日 11点08分



误诊了， springboot3.1.3 和 druid-boot3 1.2.20 没有问题，能出来监控页面。问题发现是出在 spring web security 身上，当要配置具体的匿名可访问页面时，就会出现楼上说的问题，当你不指定具体页面，全部可匿名访问，例如： auth.anyRequest().permitAll()，就OK了。 要解决：再搞搞spring web security , 解决 MvcRequestMatcher 和 request mapping 分流 DispatcherServlet StatViewServlet ；

老哥说的对，给过滤链加上一句    .requestMatchers(new MvcRequestMatcher(handlerMappingIntrospector, "/druid/**")).permitAll()  就ok了
