### ISSUE TITLE
50并发压30秒，druid的testConnectionInternal()耗时300ms

### ISSUE THREAD

**Issue by FangJYun** [alibaba/druid#5476]
![image](https://github.com/alibaba/druid/assets/25579255/5c2aa799-63b9-46d8-80f3-df4e6247cea4)

**Comment by lizongbo** [comment]
你这明显是你的数据库性能不行啊。

**Comment by zrlw** [comment]
可以试试最新的master分支，这段反射获取lastPacketReceivedTimeMs的代码已经删除了。
