### ISSUE TITLE
why `replace` sql built-in function does’t work ?

### ISSUE THREAD

**Issue by sunxien** [alibaba/druid#5477]
# Dependency in pom.xml

`<dependency>`
`    <groupId>com.alibaba</groupId>`
`    <artifactId>druid</artifactId>`
`    <version>1.2.20</version>`
`</dependency>`

# Java example code

`{`
`      String sql = "upper('abc')";`
`      Object val = SQLEvalVisitorUtils.evalExpr(DbType.mysql, sql);`
`      System.out.println(sql + ": " + val);`
`  }`
`  {`
`      String sql = "concat('abc','b')";`
`      Object val = SQLEvalVisitorUtils.evalExpr(DbType.mysql, sql);`
`      System.out.println(sql + ": " + val);`
`  }`
` {`
`      // SQL: select replace('abc','b','B') from dual;`
`      // FIXME: Found a bug when eval replace function like below:`
`      String sql = "replace('abc','b','B')";`
`      Object val = SQLEvalVisitorUtils.evalExpr(DbType.mysql, sql);`
`      System.out.println(sql + ": " + val);`
`  }`

# Run example code
![image](https://github.com/alibaba/druid/assets/81640257/4f6b73f9-8b9a-40a8-bd21-7e08f03ec032)

**Comment by lizongbo** [comment]
加上支持了，等1.2.21版本出来之后验证。
