### ISSUE TITLE
如何能够在SQL执行之前统一添加注释信息？

### ISSUE THREAD

**Issue by SpireCat** [alibaba/druid#5480]
项目上有对此能力的诉求，希望能够在SQL注释中体现traceId等易于定位的信息，基于Druid如何实现？

**Comment by lizongbo** [comment]
继承 FilterEventAdapter，实现自己的Filter,注册进去即可。
重载以下几个方法，把sql修改拼上注释之后，再调用super.statementExecuteUpdateBefore等对应方法即可。

```
  @Override
    protected void statementExecuteUpdateBefore(StatementProxy statement, String sql) {
    }
 @Override
    protected void statementExecuteQueryBefore(StatementProxy statement, String sql) {
    }
  @Override
    protected void statementExecuteBefore(StatementProxy statement, String sql) {
    }
   @Override
    protected void statementExecuteBatchBefore(StatementProxy statement) {
}
```

**Comment by lizongbo** [comment]
不过合理的trace做法，建议应该是基于filter的这些方法，旁路采集sql生成trace即可。
我最近刚刚做了这样的实现，基于opentelemetry的sdk封装，然后通过slf4j生成trce日志即可。

**Comment by SpireCat** [comment]
> 不过合理的trace做法，建议应该是基于filter的这些方法，旁路采集sql生成trace即可。 我最近刚刚做了这样的实现，基于opentelemetry的sdk封装，然后通过slf4j生成trce日志即可。

感谢你的回答，当前诉求的场景是通过数据库SHOW PROCESSLIST命令就可以直接看到当前数据库慢SQL以及对应的链路信息。

**Comment by lizongbo** [comment]
> > 不过合理的trace做法，建议应该是基于filter的这些方法，旁路采集sql生成trace即可。 我最近刚刚做了这样的实现，基于opentelemetry的sdk封装，然后通过slf4j生成trce日志即可。
> 
> 感谢你的回答，当前诉求的场景是通过数据库SHOW PROCESSLIST命令就可以直接看到当前数据库慢SQL以及对应的链路信息。

那你按照我前面的方案再sql前面拼上 带traceid的注释，然后调用super方法即可。

**Comment by newyur** [comment]
我参照着上面给的方案增加了FilterEventAdapter，为什么我的info还是原先的info呢

**Comment by lizongbo** [comment]
> 我参照着上面给的方案增加了FilterEventAdapter，为什么我的info还是原先的info呢
你要把修改后的sql作为参数去调用super里的对应方法。

**Comment by newyur** [comment]
@Override
    protected void statementExecuteUpdateBefore(StatementProxy statement, String sql) {
        sql = "/*wwwww*/" + sql;
        super.statementExecuteUpdateBefore(statement, sql);
    }

我覆写了这个方法，确定filter已经生效，但是我的info里的信息依然是形如update userdo set age=3,email='1111111',name='kk' where id=2

**Comment by lizongbo** [comment]
> ```
> @Override
> protected void statementExecuteUpdateBefore(StatementProxy statement, String sql) {
>     sql = "/*wwwww*/" + sql;
>     super.statementExecuteUpdateBefore(statement, sql);
> }
> ```
> 
> 我覆写了这个方法，确定filter已经生效，但是我的info里的信息依然是形如update userdo set age=3,email='1111111',name='kk' where id=2

你的info是说数据库里的info的话，需要找dba核实。

**Comment by newyur** [comment]
@Override
    public PreparedStatementProxy connection_prepareStatement(FilterChain chain, ConnectionProxy connection, String sql)
        throws SQLException {
        try {
            sql = generateTraceInfoToSql(sql);

            PreparedStatementProxy statement = super.connection_prepareStatement(chain, connection, sql);
            statementPrepareAfter(statement);
            return statement;
        } catch (Exception e) {
            LOGGER.error("An error occurred when generating traceInfo to Sql");
        }

        return super.connection_prepareStatement(chain, connection, sql);
    }

    @Override
    public PreparedStatementProxy connection_prepareStatement(FilterChain chain, ConnectionProxy connection, String sql,
        int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        try {
            sql = generateTraceInfoToSql(sql);

            PreparedStatementProxy statement = super.connection_prepareStatement(chain, connection, sql,
                resultSetType, resultSetConcurrency,
                resultSetHoldability);
            statementPrepareAfter(statement);
            return statement;
        } catch (Exception e) {
            LOGGER.error("An error occurred when generating traceInfo to Sql");
        }
        return super.connection_prepareStatement(chain, connection, sql,
            resultSetType, resultSetConcurrency,
            resultSetHoldability);
    }

使用这种方式可以解决，这些processlist的info有注释了
