### ISSUE TITLE
1.1.18 close无法清除所有连接，存在activeCount>0,导致restart失败

### ISSUE THREAD

**Issue by hzxcaq** [alibaba/druid#5481]
请教大佬们
想在项目中刷新一下数据库连接配置，执行如下代码
```
try {
        if (druidDataSource.isInited()) {
                int n=druidDataSource.removeAbandoned();
                log.info("removeAbandoned result:"+n);
                druidDataSource.close();
                createDataSource();
        }
        druidDataSource.restart();
        druidDataSource.setUsername(SpringDBConfig.getDBLoginInfo()[0]);
        druidDataSource.setPassword(SpringDBConfig.getDBLoginInfo()[1]);
        druidDataSource.setUrl(SpringDBConfig.getDBLoginInfo()[2]);
        druidDataSource.init();
        log.info("druidDataSource refreshed.");
} catch (Exception e) {
        log.warn("diskDBPropertyMonitor refresh database error:" + e);
}
```
removeAbandoned是为了解决restart时候总是抛以下异常而增加的；但发现无效
`2023-11-13 15:36:22.660[WARN ][Thread-DiskDBPropertyMonitor][][]com.virtual.vdi.service.DiskDBPropertyMonitor.monitor [73] - diskDBPropertyMonitor refresh database error:java.sql.SQLException: can not restart, activeCount not zero. 1`
查看restart代码会有activeCount的验证；
但是为什么close无法清除所有连接
```
public void restart() throws SQLException {
        lock.lock();
        try {
                if (activeCount > 0) {
                        throw new SQLException("can not restart, activeCount not zero. " + activeCount);
                }
                if (LOG.isInfoEnabled()) {
                        LOG.info("{dataSource-" + this.getID() + "} restart");
                }

                this.close();
                this.resetStat();
                this.inited = false;
                this.enable = true;
                this.closed = false;
        } finally {
                lock.unlock();
        }
}
```

**Comment by zrlw** [comment]
activeCount大于0就等待一下吧，说明有sql还在执行，close并不会干掉正在执行sql的连接

**Comment by hzxcaq** [comment]
> activeCount大于0就等待一下吧，说明有sql还在执行，close并不会干掉正在执行sql的连接

有什么办法强行干掉所有连接吗，我要实现不停服务更新数据库连接，好像只有这个办法

**Comment by lizongbo** [comment]
> > activeCount大于0就等待一下吧，说明有sql还在执行，close并不会干掉正在执行sql的连接
> 
> 有什么办法强行干掉所有连接吗，我要实现不停服务更新数据库连接，好像只有这个办法

更新账号密码和url这些，把minIdle设置为0，等待连接被回收重建使用新信息。

**Comment by hzxcaq** [comment]
> > > activeCount大于0就等待一下吧，说明有sql还在执行，close并不会干掉正在执行sql的连接
> > 
> > 
> > 有什么办法强行干掉所有连接吗，我要实现不停服务更新数据库连接，好像只有这个办法
> 
> 更新账号密码和url这些，把minIdle设置为0，等待连接被回收重建使用新信息。

那还需要手动close再restart吗？还需要在初始化datasource bean的时候，设置setRemoveAbandoned吗

**Comment by lizongbo** [comment]
合理的做法是自己在外层包装一层数据源，持有具体数据源的引用，自己执行重启动作的时候，分为3步
1.创建新数据源
2.引用切换到新数据源
3.旧数据源执行关闭动作。
