### ISSUE TITLE
当activeCount>=maxActive 时候会出现死循环

### ISSUE THREAD

**Issue by Rorchal** [alibaba/druid#5522]
![image](https://github.com/alibaba/druid/assets/105156970/09ec0d0e-2799-40bb-8548-f427baa6a754)  
![image](https://github.com/alibaba/druid/assets/105156970/d8d71879-4003-4cca-a3e1-6fee7a1be5d5)

**Comment by zrlw** [comment]
pull一下代码，当前master分支已修复
