### ISSUE TITLE
druid 1.2.20  wallFilter不支持达梦数据库

### ISSUE THREAD

**Issue by healw** [alibaba/druid#5554]
请问1.2.20版本druid的wallFilter依旧不支持达梦数据库吗，如果想手动支持的话有什么思路吗？
<img width="752" alt="4" src="https://github.com/alibaba/druid/assets/87115521/b3410f14-9b25-477f-9b05-633165f121c4">

**Comment by lizongbo** [comment]
自己先手工指定dbtype为oracle吧。
