### ISSUE TITLE
采用SQL查询方式检测连接时应该跳过所有filter

### ISSUE THREAD

**Issue by zrlw** [alibaba/druid#5564]
连接检测SQL（通常是SELECT 1）最核心的目标是尽快感知连接是否可用，此类SQL去执行filter只是增加耗时和占用资源。

**Comment by lizongbo** [comment]
是的，之前的版本是没有经过filter的，最近版本经过了filter，导致我通过filter采集opentelemetry的trace信息的时候就会多一个sql查询的span。
