### ISSUE TITLE
每次创建物理连接后，为什么要进行连接的可用性校验？

### ISSUE THREAD

**Issue by xuziyang** [alibaba/druid#5566]
在`com.alibaba.druid.pool.DruidAbstractDataSource#createPhysicalConnection()`方法中，每次创建成功物理连接后，随后都会执行`validateConnection(conn);` 对连接进行可用性校验，

是否可以去掉这个校验，或者默认关闭，添加一个参数来开启，因为刚创建出来的连接就不可用的概率很低

**Comment by zrlw** [comment]
对刚建立的连接做连接有效性验证，我能想到的场景就是有proxy代理的数据库，客户端建立的连接只是客户端到proxy之间的连接，对刚建立的连接执行一次sql确认一下proxy到后端数据库的连接是否有效。
我觉得可以加个配置参数，默认关闭。
