### ISSUE TITLE
有无大佬帮忙看看, 万分感谢!!! linux系统上初始化建立连接很慢, 一个连接大概10S

### ISSUE THREAD

**Issue by ji-xiao-jian** [alibaba/druid#5574]
Druid数据源,   oracle数据库,  windows和linux连接地址, 配置参数都一样.
![image](https://github.com/alibaba/druid/assets/74283018/5f389857-da2e-4f88-b5b6-4dce8102f71f)

windows服务器启动初始化数据连接:
![image](https://github.com/alibaba/druid/assets/74283018/db0facae-14f1-47ef-b25e-c3d887cc4847)

**Comment by ji-xiao-jian** [comment]
![image](https://github.com/alibaba/druid/assets/74283018/4101a8c3-ca92-4f24-be4b-1e771ef87a4a)

**Comment by lizongbo** [comment]
这种情况得自己抓包看连接数据库的网络情况，跟druid没有关系。
大概率是你的这个虚拟机里网络参数配置有问题。
我们前段时间出了个生产大问题，就是调整试点的openeuler的一个网络参数，然后就跪了。
换其它linux操作系统验证一下吧。

**Comment by ji-xiao-jian** [comment]
好的, 谢谢, 感谢回复, 我排查下再试试. 










在 2023-12-11 08:38:07，"LiZongbo" ***@***.***> 写道：

这种情况得自己抓包看连接数据库的网络情况，跟druid没有关系。
大概率是你的这个虚拟机里网络参数配置有问题。
我们前段时间出了个生产大问题，就是调整试点的openeuler的一个网络参数，然后就跪了。
换其它linux操作系统验证一下吧。

**Comment by zrlw** [comment]
把maxActive设置为1看看快不快。
1. 如果快，那就是循环建立的连接数太多了，maxActive有必要调小一些；
2. 如果也不快，那就需要抓包排查网络和数据库服务器了。

**Comment by ji-xiao-jian** [comment]
试了下都设置为1, 也是慢, 大概还是10s, 正在研究抓包排查网络, 感谢大佬.

**Comment by sleyxn** [comment]
我想请教一下 这个问题最后是什么原因导致的 因为 我最近也有这样的问题
![1ee0589bcde9591cb8b30aa9f28ccd9d](https://github.com/alibaba/druid/assets/103576254/fc2b8869-8daf-4bc8-b673-304a2e391fd0)

**Comment by ji-xiao-jian** [comment]
没找到原因, 应该跟服务器有关系,  最后用keepalived解决的. 
















在 2024-05-13 19:48:33，"sleyxn" ***@***.***> 写道：

我想请教一下 这个问题最后是什么原因导致的 因为 我最近也有这样的问题
1ee0589bcde9591cb8b30aa9f28ccd9d.png (view on web)
