### ISSUE TITLE
项目的单测有问题

### ISSUE THREAD

**Issue by xuziyang** [alibaba/druid#5580]
提交了一个PR [针对shrink方法进行锁优化 #557](https://github.com/alibaba/druid/pull/5579) ， 一直测试不通过，把pr的内容改为只添加一个空行，测试也不通过。 目前项目的测试有问题。

**Comment by zrlw** [comment]
构建工作流加了Checkstyle强制验证，需要下载构建详细日志，把涉及的代码或注解（注意，和你提交的pr多半并没有直接关联关系）订正再提交，类似强制摊派任务。
