### ISSUE TITLE
druid 1.2.18版本，clickhouse sql语法check问题

### ISSUE THREAD

**Issue by CorleoneZ** [alibaba/druid#5581]
SELECT pip as Ip, count(*) as Platform
FROM database.table as origin
JOIN (
          SELECT arrayJoin(['127.0.0.1','127.0.0.1']) AS pip
) AS subquery
ON origin.pip_hex = toString(hex(IPv4StringToNum(subquery.pip)))
GROUP BY Ip
HAVING Platform >= 1;

这是我想要执行的sql，本地直接运行是正常的，但是在使用druid连接池时，始终在 [ 中括号这里检测错误。
追踪代码发现就是在checkInternal方法中抛出的异常
![image](https://github.com/alibaba/druid/assets/52928730/5bb73d79-5d36-4f14-aaef-a1c97f6869c7)
![image](https://github.com/alibaba/druid/assets/52928730/e2c85cd7-24ee-458a-9c8d-6ce96ce780ff)

**Comment by lizongbo** [comment]
中括号解析暂时不支持，近期来研究一下先

**Comment by lizongbo** [comment]
最新代码已经支持解析这个sql，等1.2.23版本验证
