### ISSUE TITLE
1.2.16版本，sql报错ParserException: syntax error，但是执行成功。db2

### ISSUE THREAD

**Issue by SteedTamer** [alibaba/druid#5589]
sql没有问题，数据库中可以执行
原始sql
`select KEYID, KEYVALUE from KEYIDS where KEYID = ? for read only with rs use and keep update locks`
druid执行报错
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'h rs use and keep update locks', expect AS, actual USE, pos 103, line 7, column 44, token USE

请问是什么原因，如果暂时无法处理应该怎么屏蔽此错误，我尝试捕获该异常没有效果

**Comment by zrlw** [comment]
https://www.ibm.com/docs/en/db2/9.7?topic=q-select-statement
lock-request-clause子句目前还都不支持。
```
>>-USE AND KEEP--+-SHARE-----+--LOCKS--------------------------><
                 +-UPDATE----+          
                 '-EXCLUSIVE-'      
```

**Comment by zrlw** [comment]
你可以提交个PR做一下支持：
1. 改一下DB2SelectParser.java，参照里面的WITH子句加上lock-request-clause子句支持：
```
if (lexer.token() == Token.WITH) {
...
```
2. 参照com.alibaba.druid.bvt.sql.db2.DB2SelectTest_*加个验证测试类。
不复杂，可以练练手。

**Comment by SteedTamer** [comment]
@zrlw  谢谢，我尝试下看看
