### ISSUE TITLE
springboot下数据库的用户名加密

### ISSUE THREAD

**Issue by a05222236** [alibaba/druid#5608]
已经在springboot下实现了密码加密
（java -cp druid-1.0.16.jar com.alibaba.druid.filter.config.ConfigTools you_password）
现在需要对用户名username也进行加密，也想使用java -cp druid.jar ....的方式，要如何实现？

**Comment by shenjianeng** [comment]
我理解一下，你是想对 username 也进行加密处理吗？

我看了下代码：`com.alibaba.druid.filter.config.ConfigFilter#decrypt` 从源码来看只会处理 password，不会处理 username。

因此即便对 username 进行了加密，druid 在使用的时候也不会解密。

另外，提醒一下，不建议使用 druid 自带的秘钥对，作为开源软件，这就是公开的，很容易被解密。

**Comment by zrlw** [comment]
可以参考一下
https://blog.csdn.net/wangshuai6707/article/details/132469462
