### ISSUE TITLE
com.alibaba.druid.TestIdel3 本机执行测试失败

### ISSUE THREAD

**Issue by xuziyang** [alibaba/druid#5624]
![image](https://github.com/alibaba/druid/assets/8465969/b24bc9a6-6df1-41c6-b9fc-4ff0e8137186)

**Comment by xuziyang** [comment]
为什么我本地这个测试不能通过，github的测试就可以通过。
当我把这个测试的代码改了，本地可以通过了，github测测试还是可以通过，挺奇怪的。
@lizongbo

**Comment by shenjianeng** [comment]
你改的不对吧，
<img width="741" alt="image" src="https://github.com/alibaba/druid/assets/30279020/d73d5a92-f77d-4cbd-9fd8-95c68d3df870">

这里就应该是 1 ，创建了一个，然后又 close 还回去了，怎么会是 2 呢？

**Comment by xuziyang** [comment]
> 你改的不对吧， <img alt="image" width="741" src="https://private-user-images.githubusercontent.com/30279020/291491494-d73d5a92-f77d-4cbd-9fd8-95c68d3df870.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NjgzMDEsIm5iZiI6MTcwMjk2ODAwMSwicGF0aCI6Ii8zMDI3OTAyMC8yOTE0OTE0OTQtZDczZDVhOTItZjc3ZC00Y2JkLTlmZDgtOTVjNjhkM2RmODcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA2NDAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZDVmNTQ4ODdiNDg5NjczNTA2MDkzNmRiNmY3ZTkxZGRlZDQ5ZDEzM2QyMjQxZGVjMGJiNzZjNjQ2Y2NiNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6ZYXOTB00B_Z1Wu2L6lM1af9WWOPTlknWA1NugqqDNY">
> 
> 这里就应该是 1 ，创建了一个，然后又 close 还回去了，怎么会是 2 呢？

https://github.com/alibaba/druid/issues/5624 你看错了，我是把2改成1了，不是把1改成2

**Comment by shenjianeng** [comment]
抱歉，看错了。我本地只跑这个类的话，1 是能通过的

**Comment by shenjianeng** [comment]
具体原因 pr 里已经回复你了。

**Comment by xuziyang** [comment]
> 具体原因 pr 里已经回复你了。

那我的pr是不是可以合进了
