### ISSUE TITLE
SQLMergeStatement, Matched and Not Matched clause顺序不固定可造成binding错误

### ISSUE THREAD

**Issue by ZhengguanLi** [alibaba/druid#5631]
Oracle Merge Statement 我们可以有如下query:
```sql
MERGE INTO /* NUSQL.TEST */ target_table
USING source_table ON (target_table.id = source_table.id)
WHEN NOT MATCHED THEN INSERT (id, column1) VALUES (source_table.id, source_table.column1)
WHEN MATCHED THEN UPDATE SET target_table.column1 = source_table.column1
```
在这个query里面, `WHEN NOT MATCHED THEN INSERT` 在 `WHEN MATCHED THEN UPDATE SET`之前，但是format之后，这两个clause的顺序发生改变，WHEN MATCHED THEN UPDATE SET会始终在前。语法上没有问题，但是因为这个的改变，假如query是parameterized，那么因为binding对应的位置变了，会失败。

是否可以在parse的时候就记录这两个clause的位置关系，输出保持跟原有的sql相同的顺序？

**Comment by lizongbo** [comment]
加上支持了，等1.2.21的新包来验证
