### ISSUE TITLE
获取不到设置的max-wait

### ISSUE THREAD

**Issue by zxl-codehub** [alibaba/druid#5645]
我在springboot3项目引入了druid启动器，在application.yml文件中配置spring.datasource.druid.max-wait=30000ms，但在测试程序中通过getMaxWait方法获取到的max-wait是-1，这是怎么回事？

**Comment by zrlw** [comment]
这个参数配置时不要带ms单位，另外30000你确定获取连接要等30秒么

**Comment by lizongbo** [comment]
druid的数值配置值只支持纯数字方式配置
