### ISSUE TITLE
OceanBase-oracle模式下，致命异常错误码扩展不生效问题

### ISSUE THREAD

**Issue by ray-lsr** [alibaba/druid#5646]
问题描述：因sorter使用成员变量访问修饰符问题，会使用户自定义的致命错误码失效，导致抛出的异常类型是非致命错误，未进行连接销毁，没有达到预期效果。
druid1.2.8，包含master分支
关系：OceanBaseOracleExceptionSorter extends OracleExceptionSorter
初始化数据源同时会初始化错误码sorter，因为访问修饰符使用不当，首先初始化OracleExceptionSorter构造器，此时子类OceanBaseOracleExceptionSorter成员变量并没有初始化，因为子类重写了configFromProperties，导致，父类直接掉了子类的实现，导致fatalErrorCodes为null，
<img width="884" alt="image" src="https://github.com/alibaba/druid/assets/45811620/335c1969-e4fd-4fcf-b470-78e4c43fb3e4">

<img width="863" alt="image" src="https://github.com/alibaba/druid/assets/45811620/758a89b0-f61f-4261-a246-07b443431506">

**Comment by zrlw** [comment]
把父类的fatalErrorCodes改成protected，子类删除重复定义吧
你提交个pr？

**Comment by ray-lsr** [comment]
ok @zrlw , 提上去，合并到master么

**Comment by zrlw** [comment]
构造方法里直接调用configFromProperties这个方式也有问题，如果子类覆写了这个方法就会出同样的问题，pmd代码质量检查会警告这种写法，最好是剥离出去。
@lizongbo

**Comment by zrlw** [comment]
https://blog.csdn.net/kiba_zwei/article/details/104176295
构造方法内不应调用可被覆写的方法

**Comment by zrlw** [comment]
configFromProperties方法如果要支持覆写，那还是尽早剥离出去好一些

**Comment by lizongbo** [comment]
https://github.com/alibaba/druid/pull/5647 已经合并
