### ISSUE TITLE
Postgre sql At Time Zone 不支持

### ISSUE THREAD

**Issue by OldKing-lion** [alibaba/druid#5648]
在postgre sql里使用at time zone执行时区转换，Navicat正常，代码报错：
java.sql.SQLException: sql injection violation, dbType postgresql, , druid-version 1.2.2, syntax error: syntax error, expect ), actual IDENTIFIER pos 477, line 12, column 59, token IDENTIFIER at

sql:
SELECT your_timestamp AT TIME ZONE 'UTC' AS your_timestamp_with_timezone;

**Comment by lizongbo** [comment]
目前暂时不支持这种语法解析
看官方介绍应该是可以先写成 timezone函数的形式：

https://www.postgresql.org/docs/current/functions-datetime.html

`
The function timezone(zone, timestamp) is equivalent to the SQL-conforming construct timestamp AT TIME ZONE zone.
`
后面研究一下怎么加是语法解析支持。

**Comment by OldKing-lion** [comment]
> 目前暂时不支持这种语法解析 看官方介绍应该是可以先写成 timezone函数的形式：
> 
> https://www.postgresql.org/docs/current/functions-datetime.html
> 
> `The function timezone(zone, timestamp) is equivalent to the SQL-conforming construct timestamp AT TIME ZONE zone.` 后面研究一下怎么加是语法解析支持。

ok thx ,timezone is good
