### ISSUE TITLE
不支持MySQL8.0 ALTER TABLE t1 ALTER INDEX i_idx INVISIBLE语法

### ISSUE THREAD

**Issue by GPF199541** [alibaba/druid#5650]
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'_idx INVISIBLE;', expect SET, actual null, pos 42, line 1, column 34, token IDENTIFIER INVISIBLE

**Comment by lizongbo** [comment]
发完整的测试sql来。

**Comment by GPF199541** [comment]
public class indexvisTest {
    public static void main(String[] args) {
        String sql = "ALTER TABLE t1 ALTER INDEX i_idx INVISIBLE;";
        SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, JdbcUtils.MYSQL);
        List<SQLStatement> sqlStatements = parser.parseStatementList();
        System.out.println(sqlStatements.size());
//        for(SQLStatement sqlStatement:sqlStatements){
//            System.out.println(sqlStatement);
//        }
    }
}
SQL是：
ALTER TABLE t1 ALTER INDEX i_idx INVISIBLE;
ALTER TABLE t1 ALTER INDEX i_idx VISIBLE;
