### ISSUE TITLE
升级到1.2.20版本后，提示：java: 无法访问jakarta.servlet.ServletContext   找不到jakarta.servlet.ServletContext的类文件

### ISSUE THREAD

**Issue by xianyum** [alibaba/druid#5652]
`implements javax.servlet.Filter其中 
public void init(FilterConfig config){
        String exclusions = config.getInitParameter("exclusions");
        if (exclusions != null && exclusions.trim().length() != 0) {
            this.excludesPattern = new HashSet(Arrays.asList(exclusions.split("\\s*,\\s*")));
        }
        this.contextPath = DruidWebUtils.getContextPath(config.getServletContext());
    }`
使用的jdk11版本

**Comment by zrlw** [comment]
druid的pom依赖的jakarta.servlet.ServletContext组件只是编译时刻使用，所以scope只是provided，不会打到jar包里，这个东西需要运行容器提供，或者你自己的应用去添加依赖，jdk11可能要用版本6。
```
<dependency>
    <groupId>jakarta.servlet</groupId>
    <artifactId>jakarta.servlet-api</artifactId>
    <version>6.0.0</version>
</dependency>
```
