### ISSUE TITLE
我现在用的是1.1.10版本，但检测出路径遍历的安全漏洞，给出的方案是升级至1.2.4，请问路径遍历路径在1.2.4分支上修改的源码是那些

### ISSUE THREAD

**Issue by pwj126** [alibaba/druid#5653]
![image](https://github.com/alibaba/druid/assets/8382753/708abcc1-a2b8-479a-819c-031fb68e9d57)

官网给出的建议 https://security.alibaba.com/announcement/announcement?id=214

**Comment by zrlw** [comment]
用git diff版本比较差异吧，这个并不是商业软件，反馈也是个人行为，没有什么官方。

**Comment by lizongbo** [comment]
直接升级到最新稳定版吧，或者等这几天发布了1.2.21之后再升级。
