### ISSUE TITLE
dbtype null

### ISSUE THREAD

**Issue by RyanWang945** [alibaba/druid#5654]
我在用阿里云的tablestore和druid，然后会报merge sql error, dbType null, sql .ParserException: syntax error, error in :'desc LIMIT ?, ?     ',expect IDENTIFIER, actual IDENTIFIER LIMIT
这个如何解决？
我看网上有建议关闭merge sql功能，这个可以这么做吗？但网上的都是spring properties，然后我的项目中没有这个文件。
我如何在创建druid对象时关闭merge sql呢
DruidDataSource dataSource = new DruidDataSource();
然后如何设置

**Comment by lizongbo** [comment]
是否mergeSql，主要是看你是不是启用了statfilter，是的话再这里面去改设置。

对应的是StatFilter的mergeSql变量，如果是MergeStatFilter，则默认启用

![image](https://github.com/alibaba/druid/assets/1670666/41bdce24-4ba1-46aa-b3cb-d2b8f559d825)

也检查一下你的druid组件版本，看下你的jdbc驱动用的是啥，正常来讲，是能自动识别出dbType的，除非是冷门数据库，否则不太可能是dbType null。
