### ISSUE TITLE
连接池数据结构采用线程对象做key的map，实测能够有效提升连接池处理性能

### ISSUE THREAD

**Issue by zrlw** [alibaba/druid#5667]
druid连接池目前采用数组加锁方式存在高并发锁竞争的性能问题，高配置环境下配置大连接池（大小超过50）时问题尤为突出。
实际应用环境下，每个线程连接同一个数据库只使用一个数据库连接就足够了，将连接池改造为应用线程id为key的ConcurrentHashMap减少加锁处理范围，能够显著提升连接池的容量及性能。
先测一段时间确定一下稳定性。

**Comment by zrlw** [comment]
采用3种方式对连接池管理机制进行了重构：
1. requestByMpscQueue  应用通过Mpsc队列申请和返还连接 https://github.com/zrlw/druid/tree/requestByMpscQueue  
2. usingMpmc 连接池改为Mpmc无锁队列 https://github.com/zrlw/druid/tree/usingMpmc
3. usingThreadMap  连接池改为线程key的ConcurrentHashMap https://github.com/zrlw/druid/tree/usingThreadMap 
三种重构方式均借鉴了netty单线程、nginx单进程支撑海量并发处理的思想，采用单线程维护核心资源消除资源互斥锁的使用范围，其中usingThreadMap还借鉴了brpc的resource_pool的理念：每个线程尽量使用自己的资源，每个线程访问同一个数据库时重复使用一个连接应该就可以满足要求，所以将连接池设计成了线程对象作key、连接做value的ConcurrentHashMap。
用于JMH基准测试的主要代码如下（上面3个分支均单独新增了了一个jmh测试模块）：
```
@BenchmarkMode(Mode.AverageTime)
@Warmup(iterations = 1, time = 1)
@Measurement(iterations = 3, time = 10)
// Threads.MAX means using Runtime.getRuntime().availableProcessors().
@Threads(Threads.MAX)
@Fork(1)
@OutputTimeUnit(TimeUnit.SECONDS)
@State(Scope.Benchmark)
public class MyBenchmark {
    private DruidDataSource dataSource;

    @Setup(Level.Trial)
    public void setUp() throws Exception {
        DruidDataSourceStatManager.clear();

        dataSource = new DruidDataSource();
        dataSource.setRemoveAbandoned(true);
        dataSource.setRemoveAbandonedTimeoutMillis(100);
        dataSource.setLogAbandoned(true);
        dataSource.setTimeBetweenEvictionRunsMillis(10);
        dataSource.setMinEvictableIdleTimeMillis(300 * 1000);
        dataSource.setUrl("jdbc:mock:xxx");
        // 测试连接池资源充足场景：poolSize取Runtime.getRuntime().availableProcessors(); 测试连接池资源竞争场景poolSize取availableProcessors的二分之一
        int poolSize = X;
        dataSource.setMaxActive(poolSize);
        dataSource.setInitialSize(poolSize);
        // 仅当测试连接池资源竞争场景时设置maxWait
        dataSource.setMaxWait(200);
        dataSource.init();
    }

    @TearDown(Level.Trial)
    public void tearDown() throws Exception {
        dataSource.close();
        Assert.assertEquals(0, DruidDataSourceStatManager.getInstance().getDataSourceList().size());
    }

    @Benchmark
    public void test_activeTrace() throws Exception {
        int count = 1000_00;
        int i = 0;
        try {
            for (; i < count; ++i) {
                Connection conn = dataSource.getConnection();
                Assert.assertNotNull(conn);
                // sleep 0 to trigger thread scheduling.
                Thread.sleep(0);
                conn.close();
                Assert.assertTrue(conn.isClosed());
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            Assert.assertEquals(count, i);
        }
    }

    public static void main(String[] args) throws RunnerException {
        Options options = new OptionsBuilder()
                .include(MyBenchmark.class.getSimpleName())
                .build();
        new Runner(options).run();
    }
}
```
master作为上面3种方式测试对比的基准分支，commit id为39cde02 - 调整原本有误的测试用例。
JMH测试环境：Thinkpad T14 Gen2i Win10  i7-1165G7 @ 2.80GHz 4c(8逻辑cpu) / 32G内存
JMH版本及测试选项：
```
# JMH version: 1.37
# VM version: JDK 1.8.0_242, OpenJDK 64-Bit Server VM, 25.242-b08
# VM invoker: C:\Program Files\ojdkbuild\java-1.8.0-openjdk-1.8.0.242-1\jre\bin\java.exe
# VM options: <none>
# Blackhole mode: full + dont-inline hint (auto-detected, use -Djmh.blackhole.autoDetect=false to disable)
# Warmup: 1 iterations, 1 s each
# Measurement: 3 iterations, 10 s each
# Timeout: 10 min per iteration
# Threads: 8 threads, will synchronize iterations
# Benchmark mode: Average time, time/op
# Benchmark: com.alibaba.druid.MyBenchmark.test_activeTrace
```
测试结果：
一、连接池资源充足场景：连接池MaxActive等于并发测试线程数，测试结果如下所示（测试若干次，各分支测试结果基本无变化）：usingMpmc、usingThreadMap不分伯仲，但性能仅比master略有提升，requestByMpscQueue反而不及master。
1. requestByMpscQueue  
```
Benchmark                     Mode  Cnt  Score   Error  Units
MyBenchmark.test_activeTrace  avgt    3  2.735 ± 0.504   s/op
```
2.usingMpmc
```
Benchmark                     Mode  Cnt  Score   Error  Units
MyBenchmark.test_activeTrace  avgt    3  2.101 ± 1.019   s/op
``` 
3. usingThreadMap
```
Benchmark                     Mode  Cnt  Score   Error  Units
MyBenchmark.test_activeTrace  avgt    3  2.114 ± 0.646   s/op
```
5. master (39cde02 - 调整原本有误的测试用例)
```
Benchmark                     Mode  Cnt  Score   Error  Units
MyBenchmark.test_activeTrace  avgt    3  2.284 ± 1.153   s/op
```
二、连接池资源存在竞争的场景：连接池MaxActive为并发测试线程数的二分之一，获取连接等待时间均为200ms，测试结果如下所示（测试若干次，各分支测试结果基本无变化）：usingThreadMap性能提升最为显著，耗时不到master的二分之一，usingMpmc耗时约为master的二分之一，requestByMpscQueue耗时略高于master的二分之一。
1. requestByMpscQueue  
```
Benchmark                     Mode  Cnt  Score   Error  Units
MyBenchmark.test_activeTrace  avgt    3  4.323 ± 1.293   s/op
```
2.usingMpmc
```
Benchmark                     Mode  Cnt  Score   Error  Units
MyBenchmark.test_activeTrace  avgt    3  4.228 ± 1.482   s/op
```
3. usingThreadMap
```
Benchmark                     Mode  Cnt  Score   Error  Units
MyBenchmark.test_activeTrace  avgt    3  3.673 ± 2.346   s/op
```
4. master(39cde02 - 调整原本有误的测试用例)
```
Benchmark                     Mode  Cnt  Score   Error  Units
MyBenchmark.test_activeTrace  avgt    3  8.488 ± 2.610   s/op
```

小结：
usingThreadMap最有潜力，或许能够满足高并发场景下的性能需求。

**Comment by zrlw** [comment]
采用threapMap结构，无论是active还是空闲状态的连接，都保存在同一个map里面，附加的好处就是连接再也不会泄露了。
当前master从连接池取出连接后，如果持有连接的应用线程挂了，就会导致activeCount不减少但连接已不能回收的情况。

**Comment by zrlw** [comment]
测试连接池资源存在竞争时，资源配置越高，usingThreadMap相对master分支的优势越明显，在ThinkCentre M730S i7-10700 2.90GHz 8c(16逻辑cpu）、16G内存上跑连接池MaxActive为并发测试线程数的二分之一，获取连接等待时间均为200ms结果对比如下：
1. usingThreadMap
```
Benchmark                     Mode  Cnt  Score   Error  Units
MyBenchmark.test_activeTrace  avgt    3  3.510 ± 1.188   s/op
```
2. master(https://github.com/alibaba/druid/commit/39cde02442d0b27fa54b2a2b858c6a140416b59a - 调整原本有误的测试用例)
```
Benchmark                     Mode  Cnt  Score   Error  Units
MyBenchmark.test_activeTrace  avgt    3  14.828 ± 0.911   s/op
```

**Comment by zrlw** [comment]
连接池资源充足场景下，如果设置maxWait，usingThreadMap与master分支相比也有明显优势，在ThinkCentre M730S i7-10700 2.90GHz 8c(16逻辑cpu）、16G内存上跑连接池大小等于并发线程数16，maxWait为200ms时的测试结果对比：
1. usingThreadMap
```
Benchmark                     Mode  Cnt  Score   Error  Units
MyBenchmark.test_activeTrace  avgt    3  2.280 ± 2.853   s/op
```
2. master(https://github.com/alibaba/druid/commit/39cde02442d0b27fa54b2a2b858c6a140416b59a - 调整原本有误的测试用例)
```
Benchmark                     Mode  Cnt  Score   Error  Units
MyBenchmark.test_activeTrace  avgt    3  9.812 ± 3.095   s/op
```

**Comment by zrlw** [comment]
连接池资源充足场景，即使不设置maxWait，usingThreadMap测试结果也略优于master分支。ThinkCentre M730S i7-10700 2.90GHz 8c(16逻辑cpu）、16G内存上跑连接池大小等于并发线程数16，maxWait不设置（takeLast获取连接无限期等待）：
1. usingThreadMap
```
Benchmark                     Mode  Cnt  Score   Error  Units
MyBenchmark.test_activeTrace  avgt    3  2.266 ± 3.282   s/op
```
3. master(https://github.com/alibaba/druid/commit/39cde02442d0b27fa54b2a2b858c6a140416b59a - 调整原本有误的测试用例)
```
Benchmark                     Mode  Cnt  Score   Error  Units
MyBenchmark.test_activeTrace  avgt    3  2.439 ± 3.103   s/op
```

**Comment by zrlw** [comment]
ThinkCentre M730S i7-10700 2.90GHz 8c(16逻辑cpu）、16G内存跑其他两种重构方式的测试结果均不如usingThreadMap。
1. 16并发线程，8连接池，maxWait200ms
usingMpmc: ``` 9.784 ± 4.882 s/op``` （比master快三分之一）
requestByMpscQueue(返还连接放入返还队列后不等待守护线程处理结果，下同）: ```4.305 ± 2.902 s/op``` (比master快三分之二）
2. 16并发线程，16连接池，maxWait200ms
usingMpmc: ```9.406 ± 6.471 s/op```  (与master同一级别）
requestByMpscQueue: ```3.134 ± 3.748 s/op``` (比master快三分之二）
3. 16并发线程，16连接池，不设置maxWait（takeLast获取连接无限期等待） 
usingMpmc: ```2.296 ± 3.095 s/op``` (与master同一级别）
requestByMpscQueue: ```3.081 ± 3.900``` (还比master慢五分之一！）

**Comment by zrlw** [comment]
做这个测试并没有考虑网络通信延时、sql预编译等因素，所以测试结果并不能和实际场景等同，实际的意义主要是确认一下master分支有没有优化空间。
目前看，master分支设置maxWait时数据源改用公平锁的处理方式对线程数较多的应用有实质影响，对于cpu核数较多、应用线程池配置大需要大数据库连接池（比如maxActive=512）的应用，可能更适合采用非公平锁，这类应用可以通过dataSource#setUseUnfairLock或设置druid.useUnfairLock强制使用非公平锁，减少获取锁的cas操作，提高druid连接池的吞吐能力。

**Comment by zrlw** [comment]
模拟连接创建需要1s的测试结果也是非公平锁优于公平锁，无论连接池是否存在竞争关系，公平锁平均耗时均在非公平锁两倍以上，而且随应用线程数线性增长（测试线程数采用cpu可用总核数）。
我提交个PR，大家可以自己测试一下:
https://github.com/alibaba/druid/pull/5688

**Comment by lingyangcj** [comment]
@zrlw 您好，耽误您一些时间，我司使用druid时出现了一个比较诡异的问题，我现在把具体的场景和配置给您，诚恳的希望您能替我分析一下，若能得到您的解答，非常感谢。
基础逻辑：闸机扫到车牌，根据车牌查询数据库，若车牌已经录入系统，则抬杆并插入数据库一条出场数据，另外再更新一条该闸机的最后一台车辆的出场时间。所以总共涉及到3个表，查询一次，更新一次，新增一次。单挑SQL的执行时间都很短。  
问题出现场景：1.我司公司门口有汽车闸机3个，在某些时候会突然出现无法抬杆的情况。比如A车和B车和C车，A是第一个出厂的车，在被闸机扫描到但无法抬杆后，门卫将手动抬杠放走该车辆A，此时应用系统是正常服务的但是无法收到闸机传送过来的信息，同时门户将B和C车辆手动抬杆放出。在5分钟后，ABC车辆的数据在同一时间进行了处理，我该怎么修改durid的配置，或者是参考您的这个修改提高druid的性能。
