### ISSUE TITLE
druid parser support clickhouse dialect

### ISSUE THREAD

**Issue by imgawei** [alibaba/druid#5677]
请问parser是否支持clickhouse 的方言，或者是否支持自定义解析规则？在试图解析ClickHouse建视图语句时，发现解析带Final、Any Join、All Join、Asof join会报错。麻烦知道的大佬们解答一下，谢谢

**Comment by lizongbo** [comment]
parser解析逻辑是手写的，解析报错的话，就是还不支持相关逻辑。
欢迎贡献解析逻辑代码的pr。
