### ISSUE TITLE
shrink方法中某个条件前后不一致

### ISSUE THREAD

**Issue by Rorchal** [alibaba/druid#5684]
<img width="674" alt="2ec6f7aba88cbb525096ff8464cb451" src="https://github.com/alibaba/druid/assets/105156970/408c6b68-71ec-407a-90e1-e095642113a3">

**Comment by Rorchal** [comment]
如果有问题请让提交下

**Comment by zrlw** [comment]
keepAlive即使不配，keepAliveBetweenTimeMillis默认是120s，这个代码就是检测到空闲小于120s的就结束检测（minEvictableIdleTimeMillis默认是30分钟）。
我觉得没有必要改，现在优先使用排在后面的连接，当前位置的连接的空闲时间都小于2分钟了，后面的连接空闲时间肯定更小，没有必要继续检测后面的连接。
