### ISSUE TITLE
在Insert语句中columns添加注释不生效

### ISSUE THREAD

**Issue by nyoungo** [alibaba/druid#5686]
在Insert语句中columns添加注释不生效

测试程序如下：
`    public static void main(String[] args) {
        String sql = "INSERT INTO TABLE_TEST_1(\n" +
                "\tDATE_ID,\n" +
                "\tCUS_NO,\n" +
                "\tCUS_NAME\n" +
                ")\n" +
                "SELECT A.DATE_ID,\n" +
                "\tA.CUS_NO,\n" +
                "\tA.CUS_NAME\n" +
                "FROM TABLE_TEST_2 \n" +
                "WHERE COL1='1';";
        MySqlInsertStatement sqlStatement = (MySqlInsertStatement)SQLUtils.parseSingleMysqlStatement(sql);
        for (SQLExpr column : sqlStatement.getColumns()) {
            column.addAfterComment("-- comment");
        }
        System.out.println(sqlStatement.toString());
    }`

输出结果：
`INSERT INTO TABLE_TEST_1 (DATE_ID, CUS_NO, CUS_NAME)
SELECT A.DATE_ID, A.CUS_NO, A.CUS_NAME
FROM TABLE_TEST_2
WHERE COL1 = '1';`

**Comment by lizongbo** [comment]
针对这个场景加上了注释的解析和输出支持，但是可能其它场景还会缺注释，等收到反馈再来补逻辑。
