### ISSUE TITLE
spring3.0.2以上版本+nacos +druid，配置nacos动态刷新后刷新任意一个无关的key都会导致druid连接断开并无法重连。

### ISSUE THREAD

**Issue by whq4123** [alibaba/druid#5687]
配置nacos动态刷新后，更新nacos上任意key值，会导致使用druid的服务连接不上数据库报错，大致信息如下：

`org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'dataSource': Could not bind properties to 'DataSource' : prefix=spring.datasource.druid, ignoreInvalidFields=false, ignoreUnknownFields=true
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:99)
      .
      .
      .
Caused by: com.alibaba.druid.pool.DataSourceClosedException: dataSource already closed at Sat Jan 13 16:55:12 CST 2024
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1676)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1504)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1484)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1469)
	... 61 common frames omitted`

初步排查是因为springboot重新绑定是调用调用bean的destroy方法之后重新初始化 bean，

> appContext.getAutowireCapableBeanFactory().destroyBean(bean);
				appContext.getAutowireCapableBeanFactory().initializeBean(bean, name);

对于druid，destroy后，druid连接池关闭（closed= true）然后进行初始化，包括bean的属性bind；
对于复杂属性，[spirngboot3.0.2版本修改了构造器绑定的逻辑](https://github.com/spring-projects/spring-boot/commit/84b13f07488ed220ce1ab8c5148306f72dde727e)，新逻辑会先调用bean的get方法判断属性是否已经存在来确定是否使用构造器绑定来初始化属性，在判断DruidDataSourceWrapper的connection属性时，由于closed = true ，getConnection()方法抛出异常，导致问题出现。

**Comment by zrlw** [comment]
如果不想那么麻烦，getConnection()判断closed为true时直接返回null，加上一行error日志输出能解决这个问题。
但是理论上要解决这个问题，DruidDataSource需要实现BeanPostProcessor接口且使用@Order注解确保在spring的ConfigurationPropertiesBindingPostProcessor前执行，DruidDataSource在postProcessBeforeInitialization方法设置druidDatasource开始初始化状态、在postProcessAfterInitialization方法设置完成初始化状态，然后在getConnection方法判断这个标识，如果是开始初始化的状态，直接返回null。
我觉得你可以提交个PR。

**Comment by whq4123** [comment]
发现有个不常用的属性 spring.cloud.refresh.never-refreshable 可以配置为 com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceWrapper 禁止 DruidDataSource 的动态属性刷新临时解决这个问题。
`spring.cloud.refresh.never-refreshable = com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceWrapper`

@zrlw assign 给我吧，尝试修复下

**Comment by zrlw** [comment]
@whq4123  我和你一样没有权限，不过PR并不需要指派，你可以直接提交的

**Comment by whq4123** [comment]
今天仔细看了下，我们用的1.2.21，这个版本有个新增的逻辑是 DruidDataSourceWrapper，实现了DisposableBean 接口，我认为这个改动有问题，也是问题出现的主要原因之一：
spring在rebind的时候（不光是nacos更新配置）都会调用DisposableBean的destroy方法，如果按照现在的改动，rebind会导致close连接池，那所有的链接都会断开，cache都会清空，任务线程会中断，这显然是不合适的。所以这个地方应该还原为之前的代码。
