### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by anyanyna** [alibaba/druid#5690]

**Comment by anyanyna** [comment]
SQL Server数据库设置testOnBorrow为true导致获取连接一直卡住. 将参数值修改为false, 其他任何东西不动,  数据库连接获取正常

**Comment by lizongbo** [comment]
检查validate的sql语句是不是写得不对

**Comment by zrlw** [comment]
设置testOnBorrow通常还要同时设置validationQueryTimeout，否则默认是无限期等待服务端响应。

**Comment by zrlw** [comment]
标题建议改成具体的问题内容，方便查找

**Comment by anyanyna** [comment]
> 检查validate的sql语句是不是写得不对

是的, 没有设置validationQuery参数的原因.
