### ISSUE TITLE
获取连接失败

### ISSUE THREAD

**Issue by wjj96239** [alibaba/druid#5693]
最近频繁报获取不到连接的问题，版本为1.2.8，下面是我们的连接池配置：

![企业微信截图_1705480376187](https://github.com/alibaba/druid/assets/135202522/f89bdb45-e2b4-4c9d-b0a0-c8fad7927ff0)
报错信息如下：

![image](https://github.com/alibaba/druid/assets/135202522/d5a73b17-b7c3-4fa8-a284-1e049565e9d2)

事发当时，通过 SELECT * FROM pg_stat_activity 查询当前连接，也都正常，查看druid监控也没发现异常

**Comment by lizongbo** [comment]
升级到最新版本1.2.21来验证

**Comment by zrlw** [comment]
查一下error日志有没有discard关键词：druid遇到严重异常（比如事务死锁）会主动关掉连接的错误日志，事务内的所有sql使用同一连接（同一个ThreadLocal），如果sql严重异常后继续执行后续sql会有此类异常。
另外异常堆栈信息要定位到cause最下面几行，至少要有druid的代码行信息。

**Comment by lizongbo** [comment]
请使用1.2.22进行验证
