### ISSUE TITLE
这个问题很多年了springboot+druid+atomikos 长时间不使用数据库连接无法使用，多请求几次又可以使用了 

### ISSUE THREAD

**Issue by cloudlessa** [alibaba/druid#5696]
这个问题很多年前就有了一直没有好的解决办法么？
环境：
druid1.2.21
atomikos4.0.6
mysql8 mysql-connector8.0.11
差不多的相关问题:
2018年 #2299
2019年 #3187 
2023年 #5153
其他相关链接：https://www.jb51.net/article/236653.htm  https://www.jianshu.com/p/8af07f1319f8
druid主要配置：
>    
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 30
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false

atomikos配置:
>     
      ds.setMaxPoolSize(30);
      ds.setMinPoolSize(10);
      ds.setBorrowConnectionTimeout(60);
      ds.setTestQuery(prop.getProperty("validationQuery"));
      ds.setUniqueResourceName(dataSourceName);

<img width="1337" alt="image" src="https://github.com/alibaba/druid/assets/20315613/e6164f21-afd9-489d-bc7a-c6be00ef5511">

**Comment by zrlw** [comment]
此类话题出现过很多次了，空闲连接检测需要配置keepAlive=true才生效，否则没有用。
```
shrink方法：
                    if (keepAlive && idleMillis >= keepAliveBetweenTimeMillis   《== 空闲连接探活
```
keepAlive说明：
https://www.jianshu.com/p/d7ca2617b692
druid的wiki应该把这个加到FAQ里面，否则此类问题以后还会出现。
@wenshao

**Comment by cloudlessa** [comment]
> 此类话题出现过很多次了，空闲连接检测需要配置keepAlive=true才生效，否则没有用。
> 
> ```
> shrink方法：
>                     if (keepAlive && idleMillis >= keepAliveBetweenTimeMillis   《== 空闲连接探活
> ```
> 
> keepAlive说明： https://www.jianshu.com/p/d7ca2617b692 druid的wiki应该把这个加到FAQ里面，否则此类问题以后还会出现。 @wenshao

这个配置已经试过了并没有用,可能是我配置方式有问题
<img width="782" alt="image" src="https://github.com/alibaba/druid/assets/20315613/587efc60-93f7-4bfb-baf4-8ad7b975f3b8">
<img width="1272" alt="image" src="https://github.com/alibaba/druid/assets/20315613/4892484c-a880-4427-9aee-1e472a798d11">

我估计会是这个问题：https://www.jb51.net/article/236653.htm https://www.jianshu.com/p/8af07f1319f8
本身druid是没问题 就是集成atomikos的出的问题。
方式一、
参考链接 https://github.com/alibaba/druid/issues/2299
设置: ds.setMinPoolSize(0);//这个貌似可以解决。但是最小连接池设置为0了。
方式二、
参考链接https://blog.csdn.net/zhoufei3813/article/details/126725329 
只设置了:  ds.setMaxLifetime(300);//minEvictableIdleTimeMillis: 300000
自己测试没啥问题，但其他人使用有问题。

我想问题应该就是druid和atomikos的链接池的时间不一致导致了。如何统一设置 有没有具体的方法的。

**Comment by cloudlessa** [comment]
基本上确定是这个原因了https://www.jb51.net/article/236653.htm
<img width="841" alt="image" src="https://github.com/alibaba/druid/assets/20315613/0f54ab54-ea26-4780-8fcd-2cd076a7adfb">
方式一、
参考链接 https://github.com/alibaba/druid/issues/2299
设置: ds.setMinPoolSize(0);
但是会出现其他问题
<img width="1506" alt="image" src="https://github.com/alibaba/druid/assets/20315613/e49b71dc-773d-4cf6-a146-b0da557a2f09">
方式二、
配置druid的testOnBorrow: true
设置ds.setMaxLifetime(300000);//跟minEvictableIdleTimeMillis: 300000配置一样
这个方式的话，就是druid相关文档说是

`testOnBorrow | true | 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
`
目前采用了这个方式二，想看看有没有更好的方式解决。

**Comment by zrlw** [comment]
设置可以自己写ds.setKeepAlive(true)也可以参考DruidDataSourceWrapper在配置文件里配置。
用开源软件需要自己debug跟踪一下，通常情况下只靠社区是指望不上的。
你还是debug跟踪一下shrink方法，看看里面的keepAlive是否为true吧。

**Comment by lizongbo** [comment]
看上去是atomikos的问题，testOnBorrow的性能影响并不大，每次db操作仅增加1到3毫秒的耗时开销，
setMinPoolSize(0)也没啥影响，只要创建的连接不快速回收即可。

大部分的业务的性能瓶颈都不在这里，有很大调用量在意的性能的话，也就不会触发这种空闲连接的场景了。
