### ISSUE TITLE
SQLDataType的isInt（）接口中没有对MEDIUMINT 类型放回

### ISSUE THREAD

**Issue by Barry04** [alibaba/druid#5722]
SQLDataType的isInt（）接口中没有对MEDIUMINT 类型放回
![image](https://github.com/alibaba/druid/assets/61132615/4c51083d-867f-48aa-a11d-fb879c0bee87)

**Comment by Barry04** [comment]
![image](https://github.com/alibaba/druid/assets/61132615/e9908dcf-fa72-42e5-bf88-6423d9fc0ff2)
还有个问题就是为什么这些Clob和Blob类型的也会有长度的说法

**Comment by lizongbo** [comment]
发下能重现bug的测试代码。

**Comment by Barry04** [comment]
isInt()方法就没有对mediumInt进行处理，还需要测试代码干啥？

**Comment by lizongbo** [comment]
FnvHash. Constants 没有定义 MEDIUMINT，如果认为有问题，请发不符合预期的相关测试代码。

**Comment by Barry04** [comment]
![image](https://github.com/alibaba/druid/assets/61132615/83fa0594-9ca7-44ec-a7a5-f8d015010b6f)
测试代码写完了。看看吧

**Comment by Barry04** [comment]
List<SQLStatement> stmtList =  SQLUtils.parseStatements("CREATE TABLE `test` (\n" +
                "  `small` smallint(255) NOT NULL COMMENT '',\n" +
                "  `ID` varchar(32) NOT NULL COMMENT '唯一值',\n" +
                "  `medium` mediumint(20) DEFAULT NULL,\n" +
                "  `big` bigint(20) DEFAULT NULL,\n" +
                "  PRIMARY KEY (`ID`)\n" +
                ") ENGINE=InnoDB DEFAULT CHARSET=utf8;", "mysql");
        SQLCreateTableStatement createTableStatement = (SQLCreateTableStatement) stmtList.get(0);
        for (SQLTableElement element : createTableStatement.getTableElementList()) {
            if (element instanceof SQLColumnDefinition) {
                SQLColumnDefinition columnDefinition = (SQLColumnDefinition) element;
                System.out.print(columnDefinition.getName());
                boolean isInt = columnDefinition.getDataType().isInt();
                System.out.println(" isInt = " + isInt);
            }
        }
