### ISSUE TITLE
version: 1.2.20 db: sqlserver  无法通过配置参数设置sqlserver的connectionTimeout(loginTimeout) 和 socketTimeout

### ISSUE THREAD

**Issue by VeeNeenGoo** [alibaba/druid#5729]
如题

试过3种方法配置：
1: 直接配置
druid:
  connectionTimeout: 300000
  socketTimeout: 300000

2：jdbcurl中加参数
url: jdbc:sqlserver://****;loginTimeout=300000;socketTimeout=300000

3：配置connectionProperties属性
druid
  connectionProperties: loginTimeout=300000;socketTimeout=300000

3种方式配置，最终通过druid创建出来的SqlServerConnection中，loginTimeout都是10，socketTimeout都是10000

**Comment by VeeNeenGoo** [comment]
目前临时通过手动另外写一个配置DataSource的java类来设置



``` java
import com.alibaba.druid.pool.DruidDataSource;
import com.alibaba.druid.pool.DruidDataSourceFactory;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import javax.sql.DataSource;

@Configuration
public class DruidDatasourceConfig {
    @Bean("dataSource")
    public DataSource dataSource() throws Exception {
       // :
       // :
       // :
        DruidDataSource dataSource = (DruidDataSource) DruidDataSourceFactory.createDataSource(properties);
        dataSource.setConnectTimeout(300000);
        dataSource.setSocketTimeout(300000);

        return dataSource;
    }
}
```

**Comment by psyuhen** [comment]
这两个参数已经埋了好多坑了。。JNDI，JDBC等。

**Comment by lizongbo** [comment]
> 这两个参数已经埋了好多坑了。。JNDI，JDBC等。

根源是指定了默认值为10秒导致的坑，二实际场景中大家之前很少设置jdbc相关的timeout。
我来把这个默认值逻辑去掉吧。

**Comment by xhal** [comment]
从 1.2.12 ~ 目前最新1.2.21 版本都有这问题， 只能退回 1.2.11 版本

**Comment by Vinke2** [comment]
> 从 1.2.12 ~ 目前最新1.2.21 版本都有这问题， 只能退回 1.2.11 版本

所以我一直停留在1.2.11
