### ISSUE TITLE
druid1.1.10版本，设置maxactive为80，大并发使用情况下，实测数据库连接数为300，请问是什么情况导致的？

### ISSUE THREAD

**Issue by deyent** [alibaba/druid#5741]
各位大佬不知道有没有遇到我这个情况。
druid1.1.10版本，设置maxactive为80，大并发使用情况下，实测数据库连接数为300，请问是什么情况导致的？

**Comment by guodzh1** [comment]
不应该吧，这个参数很核心，应该不至于有这样大的bug，建议排查下是不是还有其他客户端连接到这个数据库上，或者你这个应用是不是集群部署的？

**Comment by lizongbo** [comment]
请使用1.2.21进行验证
