### ISSUE TITLE
Druid1.2.11执行SQL报错MySqlResolveVisitor cannot be cast to OracleASTVisito

### ISSUE THREAD

**Issue by DongcidaCi-Didadi** [alibaba/druid#5747]
报错com.alibaba.druid.sql.repository.SchemaResolveVisitorFactory$MySqlResolveVisitor cannot be cast to com.alibaba.druid.sql.dialect.oracle.visitor.OracleASTVisitor，Oracle版本为19.7

**Comment by lizongbo** [comment]
发下完整的出错sql和重现bug的测试代码吧
