### ISSUE TITLE
从1.2.3开始不支持clickhouse的array join

### ISSUE THREAD

**Issue by zoro000** [alibaba/druid#5756]
测试如下：
#创建表 mr_tbl
CREATE TABLE mr_tbl
(
    `id` UInt8,
    `name` String,
    `age` Int,
    `local` Array(String)
)
ENGINE = MergeTree()
ORDER BY id
#向表mr_tbl中插入数据
insert into table mr_tbl values (1,'zs',18,['beijing','shanghai']),(2,'ls',19,['guangzhou','hangzhou']),(3,'ww',20,[]);
#查询
SELECT id,name,age,local FROM mr_tbl ARRAY JOIN local
#报错
Cause: java.sql.SQLException: sql injection violation, dbType clickhouse, , druid-version 1.2.8, syntax error: not supported.pos 382, line 15, column 50, token IDENTIFIER ARRAY

**Comment by lizongbo** [comment]
最新代码已经支持解析，等1.2.24版本验证
