### ISSUE TITLE
Communications link failure

### ISSUE THREAD

**Issue by jeffyding** [alibaba/druid#5757]
**最近升级jdk17，druid版本从1.2.5升级到1.2.20后，数据库连接经常报错，信息如下：**

[http-nio-10000-exec-88] ERROR [DruidDataSource.java:1988] [4.610420b2-327d-4807-9a18-451d5298cedb.21a64d90-8fb3-4080-8d27-cce2a2474c2e.1709696602.12345678] [  ] - {conn-10020} discard
com.mysql.cj.jdbc.exceptions.CommunicationsException: **Communications link failure**

The last packet successfully received from the server was 60,092 milliseconds ago. The last packet sent successfully to the server was 60,115 milliseconds ago.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)

useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&autoReconnect=true&connectTimeout=30000&socketTimeout=60000

**Comment by VsterLong** [comment]
俺也一样，也没看到解决办法

**Comment by guodzh1** [comment]
异常是不是没截全？

**Comment by lizongbo** [comment]
因为解析了你的url里的connectTimeout=30000&socketTimeout=60000，超时设置受这个控制的，把这个值配大一些，
比如 connectTimeout=300000&socketTimeout=1800000

**Comment by jeffyding** [comment]
1.2.12增加了2个参数，默认10s，对于一些报表查询就不够用了，可以自行调整参数值大小解决
![druid1212](https://github.com/alibaba/druid/assets/11002841/1f7902df-bb76-4a46-be9d-ee075cbf569e)

**Comment by Kang-Yang** [comment]
@jeffyding 大佬
connectTimeout 这个参数的单位现在是s还是ms呢
