### ISSUE TITLE
没有1.2.21版本的tag

### ISSUE THREAD

**Issue by kylincode** [alibaba/druid#5758]
Maven中有1.2.21版本的jar包了，但是没有1.2.21版本的tag，能打一个1.2.21版本的tag吗？想看看1.2.21版本的代码

**Comment by wangweicugw** [comment]
+1

**Comment by lizongbo** [comment]
温少没有创建tag，你拉初始化 1.2.22的那个commit的代码即可。

**Comment by lizongbo** [comment]
请以1.2.22的代码为准吧
