### ISSUE TITLE
1.2.20 tag的代码无法运行单测，运行单测时一直卡住

### ISSUE THREAD

**Issue by kylincode** [alibaba/druid#5759]
**运行命令**：mvn test
**tag:** 1.2.20
**jdk版本:** azul-17
**现象：**
一直卡在 {dataSource-298} inited
<img width="1205" alt="image" src="https://github.com/alibaba/druid/assets/15274994/7702f0f7-38ba-46cf-a731-5ea181eb7629">

**Comment by lizongbo** [comment]
1.2.20单测有问题，请使用最新master的代码
