### ISSUE TITLE
Druid version 1.2.20 +  Parsing PG SQL leads to an endless loop | 解析PGSQL进入死循环

### ISSUE THREAD

**Issue by Chenzihe1895** [alibaba/druid#5760]
SQLUtils.parseStatements("Vacuum verbose;", DbType.postgresql);
in version 1.2.20+ will lead to an endless lool.
Howerver in other version will throw exception.

**Comment by Chenzihe1895** [comment]
version : 1.2.16

**Comment by Chenzihe1895** [comment]
For example:
Vacuum verbose;
vacuum full;
etc...
com.alibaba.druid.sql.dialect.postgresql.parser.PGSQLStatementParser#parseVacuumTable

**Comment by Chenzihe1895** [comment]
机翻，可能描述不大准确

**Comment by lizongbo** [comment]
已经重现bug并修复，等1.2.22版验证
