### ISSUE TITLE
请求回退连接池创建线程逻辑，使用1.2.21遇到连接池关闭问题的都过来

### ISSUE THREAD

**Issue by codedad1983** [alibaba/druid#5771]
>执行单元测试MySqlHexTest就能看到死循环效果：
>```
>Caused by: java.net.UnknownHostException: hbase-01
>	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
>	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
>	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
>	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:130)
>	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
>	... 9 more
>```
>原因是MySqlHexTest测试类配置的jdbcUrl是```jdbc:mysql://hbase-01:3306/sonar```，而测试环境并没有配置hbase-01的ip地址。
>建议借鉴这个PR的做法，把RunTime异常和SQL异常处理合并，如果一次连接都没有创建成功过，就break中止，否则按原来SQL异常处理分支处理。

_Originally posted by @zrlw in https://github.com/alibaba/druid/issues/4885#issuecomment-1859739400_
            
@zrlw 你提出的场景与 @shilei1987 描述的问题完全不是一码事。测试环境并没有配置hbase-01的ip地址并不会导致真实物理连接被创建，也不存在消耗数据库连接的问题。如此修改这个创建过程逻辑导致我们应用在启动刚开始的故障自恢复能力完全失效。

建议恢复原始逻辑！！！

**Comment by codedad1983** [comment]
UnknownHostException之类的网络配置问题，完全可以由连接池自动重试，当网络接通应用就能自动恢复了，搞什么关闭连接池！

关闭之后在并发使用过程又没有处理好并发情况下的restart和init操作，真会添乱。

**Comment by codedad1983** [comment]
退一万步讲，@zrlw 你这么改顶多算是只解决第一次创建连接的问题，往后的RuntimeException同样存在 #4885 的问题。

**Comment by lizongbo** [comment]
> UnknownHostException之类的网络配置问题，完全可以由连接池自动重试，当网络接通应用就能自动恢复了，搞什么关闭连接池！
> 
> 关闭之后在并发使用过程又没有处理好并发情况下的restart和init操作，真会添乱。

请详细描述一下你们复现问题的步骤
看上去是启动的时候数据库连不上的也要先创建好连接池，然后这段实际访问异常，但是db恢复之后，系统的db操作再自动恢复正常？

**Comment by codedad1983** [comment]
1.2.20的逻辑就是启动的时候初始化好连接池的各项参数，创建线程就会在后台自动维护链接，出现异常就会自动重试直到满足连接池的预期设定。上层应用无论何时都只要getConnection()即可，无需关心连接池中的异常，只需处理对connection的操作异常。这样的设计隔离性很好，各自的职责也很明确。

1.2.21中在完成init()后通过isInit()得到true的状态下自动关闭连接池的逻辑是否合理？这要让上层应用如何处理？相关代码的修改与 #4885 根本不是一回事，并没有解决问题，还把那个问题关闭了。

基于1.2.21之前的版本，我们应用如果连不上数据库（无论何时，包括启动的时候），那么getConnection()就会阻塞，等待一个超时时间，然后报错，是否重试是否退出就由我们应用来决定（大部分应用都会选择自动重试）。当数据库恢复，连接池的CreateConnectionThread就是会自动把连接重新建起来，配合应用上的重试就自动恢复了。

**Comment by codedad1983** [comment]
目前看1.2.21版本的逻辑就奇葩了。首次创建连接异常就把连接池关了，而且应用没有任何感知，然后要实现自恢复，我就只能尝试在每次getConnection()之前先判断isClosed()，然后restart()和init()，但是这样在多线程并发的情况下会反复restart()和init()。

**Comment by lizongbo** [comment]
我来恢复一下， 这个fastfail的触发时机确实应该交给应用层，连接池在这种情况下不应该fastfail

**Comment by genvyday** [comment]
1.2.21这个发布真的可能把druid的名声毁了

**Comment by genvyday** [comment]
#4885 的问题明显是因为在Connection DruidAbstractDataSource::createPhysicalConnection(String url, Properties info)第一时间处理异常关闭数据库连接导致的连接泄露导致的。
在public DruidAbstractDataSource::PhysicalConnectionInfo createPhysicalConnection()才去处理异常关闭连接明显会导致连接泄露。
druid的代码质量堪忧。

> 退一万步讲，@zrlw 你这么改顶多算是只解决第一次创建连接的问题，往后的RuntimeException同样存在 #4885 的问题。

**Comment by genvyday** [comment]
#4885  问题明显是因为在DruidAbstractDataSource::createPhysicalConnection(String url, Properties info)和FilterChainImpl::connection_connect没有在出现异常时关闭数据库连接，导致连接泄露的问题。

> 退一万步讲，@zrlw 你这么改顶多算是只解决第一次创建连接的问题，往后的RuntimeException同样存在 #4885 的问题。

**Comment by zrlw** [comment]
连接参数配置错误时，Druid自动重试机制导致错误日志会将磁盘空间占满，有docker用户提出了druid主动关闭的需求。
可以考虑加一个选项，兼顾一下这些用户的需求。
@lizongbo

**Comment by zrlw** [comment]
之前提交的那个PR的背景是一直有用户反馈当配错数据库连接参数时，应用程序启动时druid不间断输出错误日志，直接把他们的磁盘空间耗尽了，这些用户希望应用启动过程首次创建druid连接池的时候，如果有问题就直接终止。
这些用户配置的timeBetweenConnectErrorMillis参数和connect timeout参数很小，这个或许可以作为平衡两种需求的判断条件。

**Comment by codedad1983** [comment]
> 连接参数配置错误时，Druid自动重试机制导致错误日志会将磁盘空间占满，有docker用户提出了druid主动关闭的需求。 可以考虑加一个选项，兼顾一下这些用户的需求。 @lizongbo 

这个问题是他们应用上没设计好。需要应用设计上先想好连不上数据库要怎么办，很久都连不上数据库又怎么办。即便druid主动关闭了，上层应用又不知道，仍然可能会在其他地方打印错误日志导致磁盘空间占满的。这不是druid要解决的问题。

**Comment by codedad1983** [comment]
> 之前提交的那个PR的背景是一直有用户反馈当配错数据库连接参数时，应用程序启动时druid不间断输出错误日志，直接把他们的磁盘空间耗尽了，这些用户希望应用启动过程首次创建druid连接池的时候，如果有问题就直接终止。 这些用户配置的timeBetweenConnectErrorMillis参数和connect timeout参数很小，这个或许可以作为平衡两种需求的判断条件。

（1）这个需求不应该在druid的职责范围内吧。应该应用自己实现啊：启动后自己getConnection()一下，然后Connection.close()出错的话应用退出不就好了。
（2）druid走到今天更应该关注一下企业级场景，国家级核心机构的场景。上线后才发现配置上的错误，测试过程都没有？这种小作坊团队是你们的主要用户吗？启动后也不检查？监控都哪里去了？那你给他关了，他们也依然不知道。

**Comment by codedad1983** [comment]
> 我来恢复一下， 这个fastfail的触发时机确实应该交给应用层，连接池在这种情况下不应该fastfail

感谢采纳建议！

**Comment by zrlw** [comment]
@codedad1983 不是上线时出现的问题，是异地中心灾备切换演练时出现了操作事故，数据库配置员把某中心应急数据库域名配错了（正常情况下该中心使用的数据库配置都是正确的，所以一直没有发现灾备数据库地址错误的问题），灾备切换时这个中心的各个应用自动切换到应急数据库，使用了错误的数据库参数导致应用磁盘空间被不间断输出的druid错误日志撑满了。
特别需要指出的是Druid是个开源软件，可能很多地方和你想像的或期待的不一样，只是去年lizongbo他们自己也需要定制druid，他愿意个人出面接手维护这个社区，处理了很多积压了多年的issue和PR。
druid虽然还标着alibaba的名，但只是个开源版而已，不没有任何组织和人员出面承担运行责任，如果你们要拿它做核心应用而且你们的规模比较大，建议组建自己的二次开发和运维团队，直接使用社区版的风险并不可控。
我在这里提交PR也是纯个人行为，社区有人提出来我们曾遇过的issue时，就把我们自己的修订方式提一个PR过来，但这些修改内容只是基于我们自己异地多中心多库多分区的应用场景，不一定适合于各个客户，采纳与否还是要由lizongbo评估的。

**Comment by codedad1983** [comment]
>灾备切换时这个中心的各个应用自动切换到应急数据库，使用了错误的数据库参数导致应用磁盘空间被不间断输出的druid错误日志撑满了。

监控呢？你还是搞不清楚，你自己写个简单的getConnection()应用试一试嘛，看看把druid把连接池关了是什么结果。druid不打印这个日志就不会撑满磁盘了？druid还打算做exit把进程关了？磁盘空间管理也是druid要去实现的功能吗？

**Comment by lizongbo** [comment]
作为公共组件，封装实现主要特性的工作量不算大，大部分的工作量都是在针对不同情况的尽可能兼容适配加固。
我自己在工作中封装框架的时候原以为两年开发完就稳定了，结果一直在持续丰富新特性，并加固旧特性，在不影响正常逻辑的情况适配兼容各种奇葩场景。

有时候则会出现对责任边界理解有偏差而考虑不周的情况，欢迎大家在使用druid的过程中发现问题及时反馈,
我会结合我踩过的各种坑的经验来评估后持续优化，比如最近几个版本加的默认10秒超时逻辑，也给大家带来了很多困扰，我是在项目中踩坑之后利用Filter强制修正成了0，近期收到大家的反馈之后，也在最近的commit里去掉了这个逻辑，这几天温少 应该会构建出1.2.22版本来，1.2.22会支持graalvm，超时默认逻辑恢复以前版本，也支持wallfilter的回调口子便于项目自行扩展逻辑。

目前sql语法解析里，还有个难点是针对中括号的的数组等语法还没支持，也欢迎大家一起贡献代码，让druid越来越稳定，越来越强大。

**Comment by codedad1983** [comment]
感谢大家为druid的付出，目前阶段我在druid上还只是一个使用者，惭愧惭愧。我只是基于研究了druid连接池功能的核心源码而纯纯的表达一下我的建议：
我认为druid发展到这个阶段来说应该算个成熟度很高的国产公共组件了，能受到大家的青睐和大规模的使用是有它的原因的，至少说明现有的解决方案在一般情况下并不会出现太大的问题。新的版本就尽量不要在核心逻辑和关键参数上有太大变化（新增功能除外）（1.2.21在这个问题上的变化是有点大的），不是所有需求都要去满足，先看看以目前的设计，应用自己能不能有解决方法。至少zrlw提到的几个场景在我看来都有应用层面的解决方案，没有必要纳入某个公共组件的开发需求。

**Comment by zrlw** [comment]
提那个PR的时候我的确没有考虑到应用单点部署的情况。我们部分核心应用需要同时连几十个数据库，一旦出现不可恢复的异常时（包括连接池关闭），监控系统就会介入，自动将相关应用的接入流量切到其他中心。

**Comment by zrlw** [comment]
如果是刚开始了解druid，建议先看一遍wiki https://github.com/alibaba/druid/wiki （虽然有的内容可能已经过时或与当前代码不符，但绝大多数都没有问题）。
另外，druid的定位如首页强调的“为监控而生”那样，核心框架基于监控需求而设计，监控相关的代码行数远超过连接池自身的代码行数，监控功能虽然很丰富，但把握这些东西都是有代价的，如果开发能力相对薄弱，自定义filter设计不合理，最终效果可能还不如直接使用springboot自带的连接池。
对于监控没有那么要求、不需要设计filter的用户，可以考虑一下其他监控功能简单但性能优化能力相对突出的连接池，当然最好是能针对自己的应用场景设计一套测试对比方案，通过测试结果进行选择，网上虽然有很多的对比结果，但未必适合。
