### ISSUE TITLE
druid有潜在连接泄露问题

### ISSUE THREAD

**Issue by genvyday** [alibaba/druid#5776]
DruidAbstractDataSource::createPhysicalConnection(String url, Properties info)和
FilterChainImpl::connection_connect有潜在链接泄露问题。
------------------------------------------------------------------------------------------------------------------
 #4885  明显是DruidAbstractDataSource::createPhysicalConnection(String url, Properties info)和
FilterChainImpl::connection_connect没有在出现异常时关闭数据库连接导致连接泄露的问题。

> 退一万步讲，@zrlw 你这么改顶多算是只解决第一次创建连接的问题，往后的RuntimeException同样存在 #4885 的问题。

_Originally posted by @genvyday in https://github.com/alibaba/druid/issues/5771#issuecomment-1996504147_

**Comment by zrlw** [comment]
提供一个能够重现连接泄露的缺陷验证代码？或者直接提交一个缺陷修订PR（如果包含缺陷修复测试代码就更好了）

**Comment by codedad1983** [comment]
>直接提交一个缺陷修订PR（如果包含缺陷修复测试代码就更好了）

哈哈，这个情况的触发几率实在太低太低了，还可能与jdbc驱动实现质量相关，所以一直都没人修正。
