### ISSUE TITLE
1.2.22版本的StatViewServlet，WebStatFilter包名还没有修改jakarta.servlet

### ISSUE THREAD

**Issue by yzun** [alibaba/druid#5782]
1.2.22版本的StatViewServlet，WebStatFilter等包名还没有修改，导致在集成springboot 3.2.0版本时报错。因为新版springboot中ServletRegistrationBean，FilterRegistrationBean全部要求jakarta.servlet.* 
<img width="901" alt="image" src="https://github.com/alibaba/druid/assets/3615557/9b07f760-91b8-4187-90f0-4544bb3feb68">

**Comment by lizongbo** [comment]
你自己引用错class了。
springbot 3.x的快速集成是用 druid-spring-boot-3-starter
`
// https://mvnrepository.com/artifact/com.alibaba/druid-spring-boot-3-starter
implementation 'com.alibaba:druid-spring-boot-3-starter:1.2.22'

`
![image](https://github.com/alibaba/druid/assets/1670666/9954901f-b16e-488b-8fd4-0153ce472d62)
