### ISSUE TITLE
druid 不兼容配置jdbc-url

### ISSUE THREAD

**Issue by cqsuper** [alibaba/druid#5784]
之前dataSource用的是Springboot默认的DataSourceBuilder构建出来的，他兼容spring的配置：spring.datasource.jdbc-url=xxxx
而切换到druid后，会有不兼容的错误：DataSourceBeanCreationException: Failed to determine suitable jdbc url，改成spring.datasource.url就ok，能否考虑一下兼容。
另外：
![image](https://github.com/alibaba/druid/assets/568555/dab636a0-27e4-4835-a49e-d9e0fc0c8e17)
所以还是直接兼容好了

**Comment by lizongbo** [comment]
应该是原来一直写得有问题，jdbcUrl没有生成get和set方法，导致没法使用jdbc-url进行注入配置。

像#5785 这样  发下能触发异常的 详细的配置示例，以及出错堆栈吧，我验证一下加上get set方法是否ok

**Comment by lizongbo** [comment]
看了下代码，springboot的DataSourceProperties 是不支持 jdbcUrl属性的，应该是以前的druid实现有问题才误打误撞支持了 jdbcUrl属性

这种兼容不了，除非改DataSourceProperties的代码，也没有必要再兼容了，统一使用url属性。

相关属性参考org.springframework.boot.autoconfigure.jdbc.DataSourceProperties 的代码：

```
@ConfigurationProperties(prefix = "spring.datasource")
public class DataSourceProperties implements BeanClassLoaderAware, InitializingBean {

```

**Comment by riyun1989** [comment]
> 看了下代码，springboot的DataSourceProperties 是不支持 jdbcUrl属性的，应该是以前的druid实现有问题才误打误撞支持了 jdbcUrl属性
> 
> 这种兼容不了，除非改DataSourceProperties的代码，也没有必要再兼容了，统一使用url属性。
> 
> 相关属性参考org.springframework.boot.autoconfigure.jdbc.DataSourceProperties 的代码：
> 
> ```
> @ConfigurationProperties(prefix = "spring.datasource")
> public class DataSourceProperties implements BeanClassLoaderAware, InitializingBean {
> ```
![image](https://github.com/user-attachments/assets/eed21294-9b30-4730-9d7b-1229985aac60)

能否把警告信息删除掉，不然启动的时候一直有这么个警告信息
