### ISSUE TITLE
ConfigTools里面的Main方法为什么去除啊？我们很多项目还在用啊，大佬们。

### ISSUE THREAD

**Issue by Zero5269** [alibaba/druid#5786]
ConfigTools里面的Main方法1.2.20版本还有，1.2.22版本就删除了。删除了干啥啊。我们很多项目还在用这个加密啊。这删除了也没提供个新的，我们咋搞啊。有没有哪位大佬指导1.2.22怎么做密码加密？

**Comment by lizongbo** [comment]
合并回来了，后面升级用1.2.23吧

**Comment by Zero5269** [comment]
大佬，1.2.23啥时候会发布呢？我看现在druid每个版本都差了半年。我们本来是因为安全漏洞所以要升级到1.2.20，结果发现这个版本里面sockettimeout默认值不兼容之前版本。然后升级的1.2.22，结果发现加密方法没了。如果短时间不发布1.2.23那我们可能还需要回退版本，现在这个升级的版本我们计划下周就投产了。1.2.23的预计发布时间可以告知下吗？非常感谢。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月20日(周三) 晚上10:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/druid] ConfigTools里面的Main方法为什么去除啊？我们很多项目还在用啊，大佬们。 (Issue #5786)


合并回来了，后面升级用1.2.23吧


—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.



---原始邮件---
***@***.***&gt;
发送时间:&nbsp;2024年3月20日(周三) 晚上10:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/druid] ConfigTools里面的Main方法为什么去除啊？我们很多项目还在用啊，大佬们。 (Issue #5786)





合并回来了，后面升级用1.2.23吧

—
Reply to this email directly,&nbsp;view it on GitHub, or&nbsp;unsubscribe.
You are receiving this because you authored the thread.





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月20日(周三) 晚上10:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/druid] ConfigTools里面的Main方法为什么去除啊？我们很多项目还在用啊，大佬们。 (Issue #5786)




 
合并回来了，后面升级用1.2.23吧

**Comment by lizongbo** [comment]
版本没那么快，你先回退依赖吧
