### ISSUE TITLE
There are many issues with parsing SQL. 

### ISSUE THREAD

**Issue by via-red** [alibaba/druid#5788]
It seems like the Durid parser could benefit from a refactoring. Currently, it appears to be a tangled mess with various database type syntaxes mixed together. However, it falls short of covering all aspects comprehensively.

**Comment by lizongbo** [comment]
有发现问题就反馈具体问题的详细情况，druid是积累起来的手工解析逻辑，有不少地方是重复或冗余的，只能以后逐渐优化。
