### ISSUE TITLE
还是注释保留问题

### ISSUE THREAD

**Issue by solidco2** [alibaba/druid#5791]
看前面很多人提到了注释丢失，我这里用最新版本（1.2.22）测试了odps解析器，发现SELECT段、Where段的注释都能保留，但是FROM段的都丢失了，可否请大佬帮忙看下能否解决。因为涉及到IMPALA HINT，丢失了性能优化就无效了。
附截图
![QQ截图20240321145748](https://github.com/alibaba/druid/assets/570284/c03230da-ff8f-4402-b3e6-c2122c03a197)

**Comment by lizongbo** [comment]
发可以直接复现问题的文本sql来，你这样根本不方便写用例验证。

**Comment by solidco2** [comment]
抱歉，是我的问题，测试SQL如下：
```
select a -- C1
from  -- C2
  t -- C3
  join s on t.n = s.n -- C4
where -- C5
  t.x = 1  -- C6
```
在上述SQL中，为了让对比清楚，我把多个节点分别写上了6个注释（C1-C6），运行结果中，C2、C4的位置的注释丢失

附：结果截图
![image](https://github.com/alibaba/druid/assets/570284/aa7fc05d-8956-4d4b-adda-68cd1cd70033)

**Comment by lizongbo** [comment]
目前注释的解析和输出写法有点乱，暂时加了下支持逻辑，等1.2.23版本来验证

**Comment by solidco2** [comment]
我试过了 1.2.23 版本，仍然没有解决这个问题
