### ISSUE TITLE
`druid.connectionProperties` vs `druid.connectProperties`

### ISSUE THREAD

**Issue by jiajunsu** [alibaba/druid#5793]
If we want to set properties for database connection, we could use either `druid.connectionProperties` or `druid.connectProperties`。

I didn't find any docs explain the difference between them. Could we use just one word to set connection properties.

https://github.com/alibaba/druid/blob/4a48c1a52ca68a4244803f4b9e3b452480111a96/core/src/main/java/com/alibaba/druid/pool/DruidDataSourceFactory.java#L67

https://github.com/alibaba/druid/blob/4a48c1a52ca68a4244803f4b9e3b452480111a96/core/src/main/java/com/alibaba/druid/pool/DruidDataSourceFactory.java#L377

https://github.com/alibaba/druid/blob/4a48c1a52ca68a4244803f4b9e3b452480111a96/core/src/main/java/com/alibaba/druid/pool/DruidDataSource.java#L485

**Comment by lizongbo** [comment]
DruidDataSourceFactory is use for create jndi  name bind obecjt.
