### ISSUE TITLE
无法解析alter column if [not] exist...

### ISSUE THREAD

**Issue by FatCatNorth** [alibaba/druid#5797]
**dbtype:** mariadb  
**dbversion:** 11.2.3  
**druid verion:** 1.2.20  
**error sql:** `alter table info_course drop column if exists course_type_id`
**testcase code:**  
**stacktrace info:**  

```
21:53:17.933 [main] ERROR c.a.d.f.s.StatFilter - [mergeSql,150] - merge sql error, dbType mariadb, druid-1.2.20, sql : -- 给课程表增加类型字段
alter table info_course drop column if exists course_type_id
com.alibaba.druid.sql.parser.ParserException: illegal name, pos 53, line 2, column 38, token IF
	at com.alibaba.druid.sql.parser.SQLExprParser.name(SQLExprParser.java:2385)
```

**error info:** `illegal name, pos 53, line 2, column 38, token IF`
---

**Comment by lizongbo** [comment]
加上了解析，等1.2.23版验证
