### ISSUE TITLE
1.2.22起springboot配置文件提示失效

### ISSUE THREAD

**Issue by dreamkaylee** [alibaba/druid#5801]
![2024-03-25_104631](https://github.com/alibaba/druid/assets/26585787/cd93412a-a52b-4cc8-80a0-e9ce918f87ae)

**Comment by dreamkaylee** [comment]
你好，我会第一时间回复您的邮件，祝您有个好心情！……利己者生，利人者恒。……

**Comment by meiMingle** [comment]
遇到了同样的问题

**Comment by 157677678** [comment]
不是配置整体失效 我的配置只有driver url username  password 1.2.21能正常连接 22就不行 springboot比较老 2.1.9 不过还是对这种小版本号升级造成这么大区别表示奇怪

**Comment by mingyang66** [comment]
1.2.22版本问题挺大，我这边升级是直接报数据库Mapper对应的bean不存在

**Comment by Aunixtoyou** [comment]
同问。没提示挺不方便的

**Comment by zrlw** [comment]
可能和 #5783 是同类问题，原因是1.2.22规范了配置参数名，可以试试 @lizongbo  的建议：
```
调整一下配置，使用springboot的DataSourceProperties对应的这些变量名进行配置即可
```

**Comment by lizongbo** [comment]
#5944 修复了spring-configuration-metadata.json没有生成的问题， 等1.2.24版本验证

**Comment by lizongbo** [comment]
#5944 修复了spring-configuration-metadata.json没有生成的问题， 等1.2.24版本验证
