### ISSUE TITLE
druid连接池有autoCommit功能，是否能再加上autoClose功能，防止拿到连接执行sql自动提交后忘记关闭，导致资源无法回收

### ISSUE THREAD

**Issue by qiguisen** [alibaba/druid#5809]
RT
druid连接池有autoCommit功能，针对DruidPooledConnection,是否能再加上autoClose功能，防止拿到连接执行sql自动提交后忘记关闭，导致资源无法回收。

**Comment by lizongbo** [comment]
自己忘了关闭连接的愚蠢行为，应该自己负责，而不是druid去承担责任。

removeAbandoned 开启这个特性，已经可以连接长时间未关闭的连接并移除掉了在，只是明确提示了不能在生产开启这个特性。
