### ISSUE TITLE
带条件的insert报错

### ISSUE THREAD

**Issue by lilanlong** [alibaba/druid#5810]
dbtype: SqlServer
dbversion: 2019
duird version: 1.2.17

sql injection violation, dbType sqlserver, druid-version 1.2.17, class com.alibaba.druid.sql.ast.statement.SQLIfStatement not allow : if not exists (select 1 from account a  where id = '2') insert into account(id,name) values('1', '站三')

**Comment by lizongbo** [comment]
根据提示“SQLIfStatement not allow”,请检查自己的wallfilter配置。
