### ISSUE TITLE
druid 1.2.22 是否支持瀚高数据库？

### ISSUE THREAD

**Issue by ruralqiu** [alibaba/druid#5815]
druid 1.2.22 是否支持瀚高数据库？

**Comment by lizongbo** [comment]
druid适用各种支持 jdbc驱动的数据，只是在sql语法解析相关的的方言适配可能不全，这种将数据源的dbtype手工指定成sql语法相同或接近的类型即可。

详细配置参考： 



https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8
