### ISSUE TITLE
druid连接池可以在springboot 3.2中开启虚拟线程使用吗

### ISSUE THREAD

**Issue by mzjdy** [alibaba/druid#5819]
版本：druid-spring-boot-3-starter  1.2.22
连接驱动：mariadb-java-client 3.3.3
jdk 21
springboot 3.2.3 开启虚拟线程

各位大佬，这种搭配，可以用druid连接池吗？

**Comment by mzjdy** [comment]
目前项目跑起来正常，就是不知道是否有性能问题

**Comment by lizongbo** [comment]
SpringBoot是否用虚拟线程池，跟druid没有任何关系。

Springboot通过枚举org.springframework.boot.autoconfigure.thread.Threading.VIRTUAL来控制启用虚拟线程池的地方，
都是springboot自己创建tomcat线程池，定时任务线程池等地方使用该特性。

**Comment by mzjdy** [comment]
> SpringBoot是否用虚拟线程池，跟druid没有任何关系。
> 
> Springboot通过枚举org.springframework.boot.autoconfigure.thread.Threading.VIRTUAL来控制启用虚拟线程池的地方， 都是springboot自己创建tomcat线程池，定时任务线程池等地方使用该特性。

好的，谢谢

**Comment by ethankowal** [comment]
@mzjdy 我感觉他回答的有问题，他只回答了SpringBoot能否开启虚拟线程与druid没有关系，没有回答SpringBoot开启虚拟线程会不会影响druid,  只要开启了虚拟线程，原有代码里边有使用ThreadLocal的，大部分都会出问题，druid代码是有一些ThreadLocal的
