### ISSUE TITLE
Druid 1.1.23 版本是restart时显示空指针问题

### ISSUE THREAD

**Issue by QyLp** [alibaba/druid#5820]
在进行restart的方法中，关闭链接时显示空指针的错误，打印出连接池的信息是提示发现 PoolingCount和Connections数据不一致
	CreateTime:"2024-04-01 10:49:02",
	ActiveCount:0,
	**PoolingCount:1,**
	CreateCount:1,
	DestroyCount:0,
	CloseCount:47,
	ConnectCount:48,
	**Connections:[
	]**

数据库连接池的配置信息为：            
             druidDataSource.setMaxWait(10000L); 
            druidDataSource.setMinEvictableIdleTimeMillis(120000); 
            druidDataSource.setMaxEvictableIdleTimeMillis(1000L * 60L * 30L); 
            druidDataSource.setTimeBetweenEvictionRunsMillis(60000); 
            druidDataSource.setPhyTimeoutMillis(1000L * 60L * 60L); 
            druidDataSource.setMaxActive(4); //最大连接池数量
            druidDataSource.setInitialSize(2); //启动程序时，在连接池中初始化多少个连接
            druidDataSource.setMinIdle(2); //回收空闲连接时，将保证至少有minIdle个连接
            druidDataSource.setValidationQuery("SELECT 'x'");
            druidDataSource.setTestWhileIdle(true);
            druidDataSource.setTestOnBorrow(false);
            druidDataSource.setTestOnReturn(false);
            druidDataSource.setDefaultAutoCommit(true);
            druidDataSource.setValidationQueryTimeout(10);
            druidDataSource.setRemoveAbandoned(true);
            druidDataSource.setRemoveAbandonedTimeout(600);
            druidDataSource.setQueryTimeout(30);
            druidDataSource.init();
            instance

**Comment by lizongbo** [comment]
用 1.2.22 验证看是否复现吧
