### ISSUE TITLE
请更新Wiki文档

### ISSUE THREAD

**Issue by meiMingle** [alibaba/druid#5821]
已经甲辰龙年了,wiki文档部分内容已经严重滞后或缺失或有错误，比如 [配置 wallfilter](https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE-wallfilter) 这里缺少blockAllow的描述。
比如[Druid-Change-Log](https://github.com/alibaba/druid/wiki/Druid-Change-Log)还停留在2017年
还有若干个相关issue 
#3316 
#5375 
#5228 
#4984 
#4072 
#3799 
#2127 
#1765 
#571

**Comment by lizongbo** [comment]
https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8

更新了一版，看下有没有什么不清楚的地方，我继续优化说明

**Comment by lizongbo** [comment]
https://github.com/alibaba/druid/issues/3316 已经修改
https://github.com/alibaba/druid/issues/5375 已经更新
https://github.com/alibaba/druid/issues/5228 已经修改
https://github.com/alibaba/druid/issues/4984 待处理
https://github.com/alibaba/druid/issues/4072 已经修改
https://github.com/alibaba/druid/issues/3799 已经修改
https://github.com/alibaba/druid/issues/2127 待处理
https://github.com/alibaba/druid/issues/1765 待处理
https://github.com/alibaba/druid/issues/571 待处理
