### ISSUE TITLE
在进行压测时activePeak记录的数据始终没有超过64，大量获取连接进行锁等待

### ISSUE THREAD

**Issue by ztgoto** [alibaba/druid#5825]
druid 版本1.1.16
数据库版本 mysql 5.7
我将maxActive设置到了500进行压测，发现大量的数据请求获取连接都在等待锁（com.alibaba.druid.pool.DruidDataSource#getConnectionInternal    lock.lockInterruptibly()）导致延时非常的高，
后来看到activePeak记录的数据始终没有超过64，压测过程中数据库的连接也就是六十多，我觉得有点奇怪。
不知道是配置问题还是怎么回事

**Comment by lizongbo** [comment]
使用 1.2.22 版本来压测验证，没有精力去分析定位低版本的代码问题
