### ISSUE TITLE
conditionAndAlwayTrueAllow参数没了吗？有什么替换方案

### ISSUE THREAD

**Issue by zhangdaiscott** [alibaba/druid#5827]
dbtype: mysql
dbversion: 5.7
duird version: 1.2.22
error sql: SELECT COUNT(*) AS total FROM sys_role WHERE 1 = 1
error info: 
```
Caused by: java.sql.SQLException: sql injection violation, dbType mysql, druid-version 1.2.22, select alway true condition not allow : SELECT COUNT(*) AS total FROM sys_role WHERE 1 = 1
```

![image](https://github.com/alibaba/druid/assets/3162115/d8c2001c-c7c5-42e2-af2d-c379b331e00f)

**Comment by lizongbo** [comment]
conditionAndAlwayTrueAllow 参数在的，以前逻辑实现反了，你把配置调换一下即可。

![image](https://github.com/alibaba/druid/assets/1670666/9fa13e7c-18bf-4dfc-bbf8-45b0cc409625)

**Comment by zhangdaiscott** [comment]
ok

**Comment by austinuMyaccount** [comment]
你好，这个参数要配置在哪儿呢，conditionAndAlwayTrueAllow 参数在的，以前逻辑实现反了，你把配置调换一下即可。

**Comment by ixubin** [comment]
楼主出现的select alway true condition not allow这个问题，并不是conditionAndAlwayTrueAllow这个参数在起作用，而是selectWhereAlwayTrueCheck这个参数。核心代码如下：
WallConfig wallConfig = new WallConfig();
wallConfig.setSelectWhereAlwayTrueCheck(false);
