### ISSUE TITLE
druid 1.2.22 的 DruidDataSourceAutoConfigure 改动导致与 dynamic-datasource 不兼容

### ISSUE THREAD

**Issue by ldcsaa** [alibaba/druid#5831]
duird 1.2.22 之前的版本，DruidDataSourceAutoConfigure 定义了 DataSource Bean，该Bean定义会被 [dynamic-datasource](https://github.com/baomidou/dynamic-datasource/) 的 DataSource Bean覆盖，所以没有问题。
```
public class DruidDataSourceAutoConfigure {
    private static final Logger LOGGER = LoggerFactory.getLogger(DruidDataSourceAutoConfigure.class);

    /**
     * Not setting initMethod of annotation {@code @Bean} is to avoid failure when inspecting
     * the bean definition at the build time. The {@link DruidDataSource#init()} will be called
     * at the end of {@link DruidDataSourceWrapper#afterPropertiesSet()}.
     *
     * @return druid data source wrapper
     */
    @Bean
    @ConditionalOnMissingBean
    public DataSource dataSource() {
        LOGGER.info("Init DruidDataSource");
        return new DruidDataSourceWrapper();
    }
}
```

但 duird 1.2.22 的 DruidDataSourceAutoConfigure 把 Bean 类型改为了 DruidDataSourceWrapper，[dynamic-datasource](https://github.com/baomidou/dynamic-datasource/) 不能覆盖这个Bean定义。所以，由于没有相应的druid配置，导致加载 DruidDataSourceWrapper Bean 失败。
```
public class DruidDataSourceAutoConfigure {
    private static final Logger LOGGER = LoggerFactory.getLogger(DruidDataSourceAutoConfigure.class);

    /**
     * Not setting initMethod of annotation {@code @Bean} is to avoid failure when inspecting
     * the bean definition at the build time. The {@link DruidDataSource#init()} will be called
     * at the end of {@link DruidDataSourceWrapper#afterPropertiesSet()}.
     *
     * @return druid data source wrapper
     */
    @Bean
    @ConditionalOnMissingBean
    public DruidDataSourceWrapper dataSource() {
        LOGGER.info("Init DruidDataSource");
        return new DruidDataSourceWrapper();
    }
}
```

**Comment by EricCeng** [comment]
我也碰到这个问题了 QAQ

**Comment by lizongbo** [comment]
这个改动是为了支持graal vm上运行，我再研究看下如何两边都兼容。

**Comment by lizongbo** [comment]
发个完整的可以复现问题的demo来吧，我没用过[dynamic-datasource](https://github.com/baomidou/dynamic-datasource/) 这些组件。

**Comment by xiangyunup** [comment]
我只看到了url错误，你们却看到了如此多～

**Comment by Lmx1220** [comment]
> 发个完整的可以复现问题的demo来吧，我没用过[dynamic-datasource](https://github.com/baomidou/dynamic-datasource/) 这些组件。

Description:

The bean 'dataSource', defined in class path resource [com/alibaba/druid/spring/boot3/autoconfigure/DruidDataSourceAutoConfigure.class], could not be registered. A bean with that name has already been defined in class path resource [com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAutoConfiguration.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true
就算开启bean 最后走的还是DruidDataSourceAutoConfigure的bean

**Comment by lizongbo** [comment]
看上去是ConditionalOnMissingBean必须指定具体的class，近期我优化一下，然后来验证看下

**Comment by blankhang** [comment]
我也遇到这个问题

**Comment by diaodiaofly** [comment]
mark

**Comment by lizongbo** [comment]
现在加了类型匹配

```
  @ConditionalOnMissingBean({DruidDataSourceWrapper.class,
        DruidDataSource.class,
        DataSource.class})

```

等1.2.23出来再验证

**Comment by Lmx1220** [comment]
> 现在加了类型匹配
> 
> ```
>   @ConditionalOnMissingBean({DruidDataSourceWrapper.class,
>         DruidDataSource.class,
>         DataSource.class})
> ```
> 
> 等1.2.23出来再验证

可以了直接覆盖代码测试启动不报错了

**Comment by IMJacky** [comment]
mark 同样遇到这个问题

**Comment by Lmx1220** [comment]
> mark 同样遇到这个问题

等新版出来就行了

**Comment by Umenezumi** [comment]
> > mark 同样遇到这个问题
> 
> 等新版出来就行了

您好 请问合并此 pr 的版本大概什么时间发布呢？

**Comment by Lmx1220** [comment]
实在等不急就覆盖底代码就行
