### ISSUE TITLE
经SQLStatementParser转化后sql中的转义字符前后不一致

### ISSUE THREAD

**Issue by xiehaopeng** [alibaba/druid#5832]
**dbtype:**  
mysql

**dbversion:**  
5.7

**druid verion:** 
1.2.14

**error sql:** 
SELECT 'abc"\"';

**testcase code:**
<img width="1246" alt="image" src="https://github.com/alibaba/druid/assets/46118966/868cb1d3-e8e5-4bbe-b33f-815eb44a5f00">

**stacktrace info:**
<img width="154" alt="image" src="https://github.com/alibaba/druid/assets/46118966/45f0ec8e-ff17-4161-ac7e-b18c6b4ee2ea">

**error info:** 
经过SQLStatementParser转化后的sql前后不一致

**Comment by lizongbo** [comment]
用1.2.22版本验证

**Comment by xiehaopeng** [comment]
我这边尝试用1.2.22版本验证，遇到了相同的问题
