### ISSUE TITLE
OracleCreateTableParser解析oracle建表语句获取不到注释

### ISSUE THREAD

**Issue by bubb1eP** [alibaba/druid#5833]
<img width="571" alt="image" src="https://github.com/alibaba/druid/assets/160395537/f8dc2f99-b7f0-4321-aa0b-9736a00a18d0">
sql语句
<img width="886" alt="image" src="https://github.com/alibaba/druid/assets/160395537/2573d6e1-d0f3-48cb-a903-b921e45da60f">
代码示例
<img width="882" alt="image" src="https://github.com/alibaba/druid/assets/160395537/dcce654d-2dd9-4396-a3d0-d1749e049ec9">
解析结果
解析结果没有获取到注释

**Comment by bubb1eP** [comment]
druid版本是1.2.5

**Comment by lizongbo** [comment]
用1.2.22验证，如果还是复现，请发纯文本的信息，和能重现问题的测试代码，图片根本不方便制造测试用例。

**Comment by bubb1eP** [comment]
`        String sql="create table APP_USER (     USERID         VARCHAR2(16)            not null         primary key,     UPDATEDATE     DATE          default null,     FIRSTLOGIN     VARCHAR2(2)   default '0' ) comment on table APP_USER is '用戶表（內勤）' comment on column APP_USER.USERID is '用户ID' comment on column APP_USER.UPDATEDATE is '更新时间' comment on column APP_USER.FIRSTLOGIN is '首次登录";
OracleCreateTableParser parser = new OracleCreateTableParser(sql);
        SQLCreateTableStatement sqlCreateTableStatement = parser.parseCreateTable();
        String tableName = sqlCreateTableStatement.getTableName();
        System.out.println(tableName);
        for (SQLTableElement sqlTableElement : sqlCreateTableStatement.getTableElementList()) {
            if (sqlTableElement instanceof SQLPrimaryKey) {
                SQLPrimaryKey sqlPrimaryKey = (SQLPrimaryKey) sqlTableElement;
            }else if (sqlTableElement instanceof SQLColumnDefinition){
                SQLColumnDefinition sqlColumnDefinition = (SQLColumnDefinition) sqlTableElement;
                System.out.println("字段名："+sqlColumnDefinition.getNameAsString()+" 注释："+sqlColumnDefinition.getComment());
            }
        }
`
如上述oracle的sql语句，解析的时候是拿不到注释的也不能识别主键字段

**Comment by bubb1eP** [comment]
> 用1.2.22验证，如果还是复现，请发纯文本的信息，和能重现问题的测试代码，图片根本不方便制造测试用例。

       String sql="create table APP_USER (     USERID         VARCHAR2(16)            not null         primary key,     UPDATEDATE     DATE          default null,     FIRSTLOGIN     VARCHAR2(2)   default '0' ) comment on table APP_USER is '用戶表（內勤）' comment on column APP_USER.USERID is '用户ID' comment on column APP_USER.UPDATEDATE is '更新时间' comment on column APP_USER.FIRSTLOGIN is '首次登录"; OracleCreateTableParser parser = new OracleCreateTableParser(sql); SQLCreateTableStatement sqlCreateTableStatement = parser.parseCreateTable(); String tableName = sqlCreateTableStatement.getTableName(); System.out.println(tableName); for (SQLTableElement sqlTableElement : sqlCreateTableStatement.getTableElementList()) { if (sqlTableElement instanceof SQLPrimaryKey) { SQLPrimaryKey sqlPrimaryKey = (SQLPrimaryKey) sqlTableElement; }else if (sqlTableElement instanceof SQLColumnDefinition){ SQLColumnDefinition sqlColumnDefinition = (SQLColumnDefinition) sqlTableElement; System.out.println("字段名："+sqlColumnDefinition.getNameAsString()+" 注释："+sqlColumnDefinition.getComment()); } }
如上述oracle的sql语句，解析的时候是拿不到注释的也不能识别主键字段

**Comment by lizongbo** [comment]
确认这个sql是合法语句？
https://deepinout.com/oracle/oracle-questions/319_oracle_oracle_create_table_with_column_comments.html
看网上的最多是表注释跟着建表语句一起写成一个sql，没见到把字段注释合并成一个sql来写的。

**Comment by bubb1eP** [comment]
> 确认这个sql是合法语句？ https://deepinout.com/oracle/oracle-questions/319_oracle_oracle_create_table_with_column_comments.html 看网上的最多是表注释跟着建表语句一起写成一个sql，没见到把字段注释合并成一个sql来写的。

而且你发的这个链接注释也是分开的呀

**Comment by lizongbo** [comment]
> > 确认这个sql是合法语句？ https://deepinout.com/oracle/oracle-questions/319_oracle_oracle_create_table_with_column_comments.html 看网上的最多是表注释跟着建表语句一起写成一个sql，没见到把字段注释合并成一个sql来写的。
> 
> 而且你发的这个链接注释也是分开的呀

仔细看人家的是分号分开的多条sql语句，你的是一条，你自己先在oracle数据验证清楚sql的合法性再来反馈问题。

**Comment by bubb1eP** [comment]
> > > 确认这个sql是合法语句？ https://deepinout.com/oracle/oracle-questions/319_oracle_oracle_create_table_with_column_comments.html 看网上的最多是表注释跟着建表语句一起写成一个sql，没见到把字段注释合并成一个sql来写的。
> > 
> > 
> > 而且你发的这个链接注释也是分开的呀
> 
> 仔细看人家的是分号分开的多条sql语句，你的是一条，你自己先在oracle数据验证清楚sql的合法性再来反馈问题。

验证过了亲，不行，我一开始是直接复制的ddl建完表后的语句，而且不合法的话，sql解析就出错了喔，我这个是复制的示例试了一下，你不信可以自己测试一下喔，是无法获取注释的。

**Comment by bubb1eP** [comment]
> > > 确认这个sql是合法语句？ https://deepinout.com/oracle/oracle-questions/319_oracle_oracle_create_table_with_column_comments.html 看网上的最多是表注释跟着建表语句一起写成一个sql，没见到把字段注释合并成一个sql来写的。
> > 
> > 
> > 而且你发的这个链接注释也是分开的呀
> 
> 仔细看人家的是分号分开的多条sql语句，你的是一条，你自己先在oracle数据验证清楚sql的合法性再来反馈问题。

你都懒得自己试一下就关闭issues，确实是存在这个bug ！
