### ISSUE TITLE
Druid configures Error

### ISSUE THREAD

**Issue by JunSilckTar** [alibaba/druid#5834]
druid-spring-boot-starter version: 1.2.22
Springboot version: 2.6.13

Ktorm version: 3.6.0
dbType: mysql
dbVersion: 8.0

Hi, I got a error when I run application with not set url for spring.database, like this

```
spring:
  datasource:
   # url: jdbc:mysql://localhost:3306
```

I set excuse for @SpringBootApplication(exclude = {DataSourceAutoConfiguration.class})
kotlin: @SpringBootApplication(exclude = [DataSourceAutoConfiguration.class])

the error is " Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured. "

But it is working  if I set  url, like this, and there is a connection on web! like this

```
spring:
  datasource:
    url: jdbc:mysql://localhost:3306
```
<img width="694" alt="截屏2024-04-09 13 37 38" src="https://github.com/alibaba/druid/assets/103525955/1bef72a0-b8a7-4ad7-ae45-a6c64fcebe46">

I use that way to configure DruidDataSource, other connection is correct 
<img width="512" alt="截屏2024-04-09 13 37 59" src="https://github.com/alibaba/druid/assets/103525955/03c8f6a8-554d-4911-804d-550532a09c59">

I must set url for springboot.database else class org.springframework.boot.autoconfigure.jdbc.DataSourceBeanCreationException Failed to determine a suitable driver class. if I don't use druid, the error not come out

I wondering not put any configuration on application.properties or yaml, Is there a problem with my operation or a bug? I can't test

Thank you for your working!!!
Regards.

**Comment by JunSilckTar** [comment]
sorry,
I use that way to configure DruidDataSource, other connection is correct
```kotlin
        val druidDataSource = DruidDataSource()
        druidDataSource.url = url
```

**Comment by lizongbo** [comment]
```

spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    type: com.alibaba.druid.pool.DruidDataSource

```
