### ISSUE TITLE
1.1.9 如何关闭监控

### ISSUE THREAD

**Issue by parashorea** [alibaba/druid#5842]

**Comment by parashorea** [comment]
web-stat-filter:
        enabled: false
      filter:
        stat:
          enabled: false
      WebStatFilter:
        enabled: false
      StatViewServlet:
        enabled: false
      stat-view-servlet:
        enabled: false 都不生效

**Comment by lizongbo** [comment]
升级使用1.2.22，基于新版本进行配置验证。低版本不再维护
