### ISSUE TITLE
StatFilter没有适配gaussdb导致sql打印异常

### ISSUE THREAD

**Issue by zhang1001san** [alibaba/druid#5845]
你好。

1问题：StatFilter没有适配gaussdb导致sql打印异常
2. 异常sql  ：  delete from xx表  t where t.id=1 
3.异常代码处(StatFilter.java)：
` public String mergeSql(String sql, DbType dbType) {
      
        try {
            sql = ParameterizedOutputVisitorUtils.parameterize(sql, dbType, null, null, null);
        } catch (Exception e) {
            LOG.error("merge sql error, dbType " + dbType + ", druid-" + VERSION.getVersionNumber() + ", sql : " + sql, e);
        }

        return sql;
    }`

4.错误原因：
SQLParserUtils.createSQLStatementParser方法并没有适配gaussdb。
  gaussdb 应该也是使用PGSQLStatementParser把？（如下）      
`        
case postgresql:
case greenplum:
case edb:
eturn new PGSQLStatementParser(sql, features);
`

**Comment by lizongbo** [comment]
加上适配了
