### ISSUE TITLE
解析 出错 DELETE FROM aa_tmp  t WHERE (t.batch_no = ?) 

### ISSUE THREAD

**Issue by mubaili126** [alibaba/druid#5846]
SQL：
DELETE FROM ia_tmp  
t
 
   
 
 WHERE 
 (t.batch_no = ?)
使用SQLUtils.format 解析出错
出错信息： not supported.pos 47, line 2, column 2, token IDENTIFIER t

**Comment by lizongbo** [comment]
信息不详，连基本数据库类型信息都没有。补充信息后再反馈。
