### ISSUE TITLE
SpringBoot3使用druid 1.2.22存在问题

### ISSUE THREAD

**Issue by isiit** [alibaba/druid#5849]
Springboot3已经将javax.xx.xx升级到了jakrata.x.x；但是druid还是引用了javax.x.x;导致适配性问题，不知道什么时间可以修复此适配性bug？

**Comment by lizongbo** [comment]
我的 SpringBoot3.2.4 使用druid-spring-boot-3-starter功能一切正常。或者直接依赖druid 1.2.22也是没有问题的，且druid对servlet包没有强制依赖，只是druid jar包里多一些用不到的class而已，哪里来的适配性问题，哪里有适配性bug？

自己先核实自己的配置问题，然后确实确认是ddruid有问题就请贴出错详情来。


`
	implementation 'com.alibaba:druid-spring-boot-3-starter:1.2.22'

`

**Comment by isiit** [comment]
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
