### ISSUE TITLE
url配置成 “123” 会触发Druid死循环，一直去重复尝试连接

### ISSUE THREAD

**Issue by zhangdaiscott** [alibaba/druid#5850]
dbtype: mysql
dbversion: 5.7
duird version: 1.2.22

问题：url配置成 “123” 会触发Druid死循环，一直去重复尝试连接
配置：  
![image](https://github.com/alibaba/druid/assets/3162115/8d6b8a09-fb26-4737-b462-a892d9c739f4)

错误截图：
![image](https://github.com/alibaba/druid/assets/3162115/4b2fa8d5-3d2f-463b-9679-ecec1be679e6)

**Comment by lizongbo** [comment]
这种低级错误需要自己避免，组件做不了什么事情，没啥能兼容的。

**Comment by DoubleSong123** [comment]
> 这种低级错误需要自己避免，组件做不了什么事情，没啥能兼容的。

你好，请问下在不修改代码逻辑的情况下，出了这种情况有没有好的办法解决？我这有个工程，在占位符未完成替换的时候，要是去连接，会偶现这个死循环，有没有配置项可以去kill掉此连接池的呢
