### ISSUE TITLE
使用druid的1.1.9版本适配国产瀚高数据库，com.alibaba.druid.sql.parser.ParserException

### ISSUE THREAD

**Issue by ruralqiu** [alibaba/druid#5851]
spring.datasource druid filters=stat,log4j
如上去掉druid wall不起作用
详细见图示：
![1](https://github.com/alibaba/druid/assets/100115904/74f890ca-5278-4a06-a836-0a262e8301ca)
![2](https://github.com/alibaba/druid/assets/100115904/d47d3993-e116-458a-b34d-6107cdddebd9)
是否是druid SQL解析不支持瀚高数据库的start with ....connect by的oracle递归兼容语法？？？

**Comment by lizongbo** [comment]
暂时可以通过指定dbtype的方式来规避，相关属性配置请参考： 
https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8

**Comment by lizongbo** [comment]
另外请升级到1.2.22来验证功能，老的版本不再维护。

**Comment by ruralqiu** [comment]
> 另外请升级到1.2.22来验证功能，老的版本不再维护。

您好，我本地已经测试1.2.22版本，验证也是出现同样的报错

**Comment by ruralqiu** [comment]
> 暂时可以通过指定dbtype的方式来规避，相关属性配置请参考： https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8

已制定druid的db-type是postgresql，还是出现同样的错误，我理解的是指定db-type为某种数据库类型后，druid会强制校验分析该种数据库的SQL语法，比如PG，若在PG的基础上做了oracle SQL语法的兼容 ，那druid开启wall的情况相下，就无法进行SQL解析
