### ISSUE TITLE
clickhouse update 有问题

### ISSUE THREAD

**Issue by jinxiaoyi** [alibaba/druid#5852]
druid版本1.2.22
现在接入clickhouse。 在运行sql的时候报错了

报错信息如下
 class com.alibaba.druid.sql.dialect.clickhouse.ast.ClickhouseAlterTableUpdateStatement not allow : ALTER TABLE data_customer UPDATE    nick_name=?   WHERE  (id = ?)
 
断点发现 WallVisitorUtils：：preVisitCheck（） 发现了异常爆出点
![image](https://github.com/alibaba/druid/assets/34831856/a0c4a2c1-f83d-40ac-a996-9ddd0887a773)
请问是不支持clickhouse的update操作吗

**Comment by lizongbo** [comment]
这是你开了wallfilter防火墙拦截的，自己先调整wallconfig里的配置试一下。
