### ISSUE TITLE
为什么使用公钥直接解密？非对称加密中并不常见，因为通常情况下公钥是用来加密数据，而私钥用来解密数据

### ISSUE THREAD

**Issue by wangyunpeng0319** [alibaba/druid#5856]
public static String decrypt(PublicKey publicKey, String cipherText) throws Exception {
        Cipher cipher = Cipher.getInstance("RSA/ECB/PKCS1Padding");

        try {
            cipher.init(2, publicKey);
        } catch (InvalidKeyException var7) {
            RSAPublicKey rsaPublicKey = (RSAPublicKey)publicKey;
            RSAPrivateKeySpec spec = new RSAPrivateKeySpec(rsaPublicKey.getModulus(), rsaPublicKey.getPublicExponent());
            Key fakePrivateKey = KeyFactory.getInstance("RSA").generatePrivate(spec);
            cipher = Cipher.getInstance("RSA");
            cipher.init(2, fakePrivateKey);
        }

        if (cipherText != null && cipherText.length() != 0) {
            byte[] cipherBytes = Base64.base64ToByteArray(cipherText);
            byte[] plainBytes = cipher.doFinal(cipherBytes);
            return new String(plainBytes);
        } else {
            return cipherText;
        }
    }

这段代码中的异常处理逻辑显示，如果用公钥直接解密失败（抛出 InvalidKeyException 异常），它会尝试创建一个伪造的私钥（fakePrivateKey），并使用它来解密。这个伪造的私钥是根据公钥的模数（modulus）和公开指数（publicExponent）创建的。这种方法是基于 RSA 算法的数学属性，允许使用公钥的参数来形成一个能够解密数据的密钥。

这个实现确实是不标准的，也可能引起安全上的疑虑。在标准的非对称加密实践中，私钥应该是唯一能够解密由公钥加密数据的密钥。如果这段代码允许公钥解密数据，那么这意味着数据实际上并没有被安全加密，因为任何拥有公钥的人（在这种情况下是任何人）都能解密数据。

请问这样的设计是出于什么原因？ 公钥用于解密，这样明文密码就有泄露的风险

**Comment by lizongbo** [comment]
我从来没这样用过，然后看了下网上资料说的原因是：

`
 // 因为 IBM JDK 不支持私钥加密, 公钥解密, 所以要反转公私钥
           // 也就是说对于解密, 可以通过公钥的参数伪造一个私钥对象欺骗 IBM JDK
           RSAPublicKey rsaPublicKey = (RSAPublicKey) publicKey;
           RSAPrivateKeySpec spec = new RSAPrivateKeySpec(rsaPublicKey.getModulus(), rsaPublicKey.getPublicExponent());

`

感觉是以前远古时代留下的适配逻辑。
