### ISSUE TITLE
pgsql解析SET SCHEMA语法时出错

### ISSUE THREAD

**Issue by kang2086** [alibaba/druid#5870]
pgsql语法：
SET SCHEMA 'platform_base';

drop table if exists JC_FUND_ACCOUNT_TEST cascade;
.....

多余的解析值
![企业微信截图_20240426173711](https://github.com/alibaba/druid/assets/36265554/df5ce3a3-cb01-4829-b433-a716ad37d3ed)

**Comment by lizongbo** [comment]
你根本没提供使用的druid的版本，我用1.2..22验证了解析是正常的，只是生成的sql存在问题，多了个to，导致再次解析会失败，我优化一下。
请使用最新版本的进行验证

**Comment by kang2086** [comment]
druid使用的1.2.22版本

**Comment by kang2086** [comment]
> 你根本没提供使用的druid的版本，我用1.2..22验证了解析是正常的，只是生成的sql存在问题，多了个to，导致再次解析会失败，我优化一下。 请使用最新版本的进行验证
druid使用的1.2.22版本
