### ISSUE TITLE
Hardcoded secret key and RSA key size of 512 bits may lead to potential risks

### ISSUE THREAD

**Issue by Gax-c** [alibaba/druid#5875]
## Why you need it?
We've identified that in the file `ConfigTools.java` the secret key is hardcoded [here](https://github.com/alibaba/druid/blob/master/core/src/main/java/com/alibaba/druid/filter/config/ConfigTools.java#L36). 
```java
    private static final String DEFAULT_PRIVATE_KEY_STRING = "MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAocbCrurZGbC5GArEHKlAfDSZi7gFBnd4yxOt0rwTqKBFzGyhtQLu5PRKjEiOXVa95aeIIBJ6OhC2f8FjqFUpawIDAQABAkAPejKaBYHrwUqUEEOe8lpnB6lBAsQIUFnQI/vXU4MV+MhIzW0BLVZCiarIQqUXeOhThVWXKFt8GxCykrrUsQ6BAiEA4vMVxEHBovz1di3aozzFvSMdsjTcYRRo82hS5Ru2/OECIQC2fAPoXixVTVY7bNMeuxCP4954ZkXp7fEPDINCjcQDywIgcc8XLkkPcs3Jxk7uYofaXaPbg39wuJpEmzPIxi3k0OECIGubmdpOnin3HuCP/bbjbJLNNoUdGiEmFL5hDI4UdwAdAiEAtcAwbm08bKN7pwwvyqaCBC//VnEWaq39DCzxr+Z2EIk=";
    public static final String DEFAULT_PUBLIC_KEY_STRING = "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKHGwq7q2RmwuRgKxBypQHw0mYu4BQZ3eMsTrdK8E6igRcxsobUC7uT0SoxIjl1WveWniCASejoQtn/BY6hVKWsCAwEAAQ==";

```
Additionally, in the same file, the RSA key is generated with a key size of only 512 [here](https://github.com/alibaba/druid/blob/master/core/src/main/java/com/alibaba/druid/filter/config/ConfigTools.java#L41). 
```java
    public static void main(String[] args) throws Exception {
        String password = args[0];
        String[] arr = genKeyPair(512);
        System.out.println("privateKey:" + arr[0]);
        System.out.println("publicKey:" + arr[1]);
        System.out.println("password:" + encrypt(arr[0], password));
    }
```
## How it could be?
The default hardcoded secret key can be dangerous. If the user do not have the knowledge to set up a new key, the default key will be easily exposed to the attacker. 
The RSA key size of 512 bits is considered weak and can be broken with sufficient computing resources. Modern standards recommend a minimum key size of 2048 bits.
## Reference
[https://www.javamex.com/tutorials/cryptography/rsa_key_length.shtml](https://www.javamex.com/tutorials/cryptography/rsa_key_length.shtml)

**Comment by lizongbo** [comment]
历史遗留代码，本来移除了但是有人还是依赖，只能继续保留，使用者责任自负。
