### ISSUE TITLE
spring boot 3.0.2整合druid 1.2.20和dynamic后web页面一直404

### ISSUE THREAD

**Issue by jonycw** [alibaba/druid#5892]
**dbtype:** mysql
**dbversion:**  8.0.33
**druid verion:** 1.2.20
**error sql:**
**testcase code:**
**stacktrace info:**
**error info:** Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed May 08 15:35:42 GMT+08:00 2024
There was an unexpected error (type=Not Found, status=404).
---

**Comment by jonycw** [comment]
主要配置如下：
spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    #动态数据源配置
    dynamic:
      druid:
        #     配置初始化大小、最小、最大线程数
        initialSize: 5
        minIdle: 5
        #     CPU核数+1，也可以大些但不要超过20，数据库加锁时连接过多性能下降
        maxActive: 20
        #     最大等待时间，内网：800，外网：1200（三次握手1s）
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        #     配置一个连接在池中最大空间时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1
        testWhileIdle: true
        #     设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
        testOnBorrow: true
        #     设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
        testOnReturn: true
        #     可以支持PSCache（提升写入、查询效率）
        poolPreparedStatements: true
        #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        #     保持长连接
        keepAlive: true
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

        web-stat-filter:
          # 是否启用StatFilter默认值true
          enabled: true
          # 添加过滤规则
          url-pattern: /*
          # 忽略过滤的格式
          exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico

        stat-view-servlet:
          # 是否启用StatViewServlet默认值true
          enabled: true
          # 访问路径为/druid时，跳转到StatViewServlet
          url-pattern: /druid/*
          # 是否能够重置数据
          reset-enable: false
          # 需要账号密码才能访问控制台，默认为root
          login-username: druid
          login-password: druid
          # IP白名单
          allow: 127.0.0.1
          # IP黑名单（共同存在时，deny优先于allow）
          deny:
      datasource:
        one:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://xxxx/one?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: xx
          password: xxxxx
          type: com.alibaba.druid.pool.DruidDataSource
        two:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://xxxx/two?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: xx
          password: xxx
          type: com.alibaba.druid.pool.DruidDataSource
      primary: one

**Comment by jonycw** [comment]
main config：
```
spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    #动态数据源配置
    dynamic:
      druid:
        #     配置初始化大小、最小、最大线程数
        initialSize: 5
        minIdle: 5
        #     CPU核数+1，也可以大些但不要超过20，数据库加锁时连接过多性能下降
        maxActive: 20
        #     最大等待时间，内网：800，外网：1200（三次握手1s）
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        #     配置一个连接在池中最大空间时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1
        testWhileIdle: true
        #     设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
        testOnBorrow: true
        #     设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
        testOnReturn: true
        #     可以支持PSCache（提升写入、查询效率）
        poolPreparedStatements: true
        #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        #     保持长连接
        keepAlive: true
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

        web-stat-filter:
          # 是否启用StatFilter默认值true
          enabled: true
          # 添加过滤规则
          url-pattern: /*
          # 忽略过滤的格式
          exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico

        stat-view-servlet:
          # 是否启用StatViewServlet默认值true
          enabled: true
          # 访问路径为/druid时，跳转到StatViewServlet
          url-pattern: /druid/*
          # 是否能够重置数据
          reset-enable: false
          # 需要账号密码才能访问控制台，默认为root
          login-username: druid
          login-password: druid
          # IP白名单
          allow: 127.0.0.1
          # IP黑名单（共同存在时，deny优先于allow）
          deny:
      datasource:
        one:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://xxxx/one?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: xx
          password: xxx
          type: com.alibaba.druid.pool.DruidDataSource
        two:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://xxxx/two?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: xx
          password: xxx
          type: com.alibaba.druid.pool.DruidDataSource
      primary: one

**Comment by jonycw** [comment]
已解决

**Comment by itluck** [comment]
> 已解决

您好，请问后面您是怎么解决的呢？可以分享一下不？谢谢

**Comment by itluck** [comment]
> > 已解决
> 
> 您好，请问后面您是怎么解决的呢？可以分享一下不？谢谢

已处理，依赖要用对正确是：druid-spring-boot-3-starter。
附一下我的配置：
`spring:
  application:
    name: xxxx
  profiles:
    active: ${PRO_ACTIVE:dev}
  datasource:
    druid:
      filters: stat,wall,slf4j
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      stat-view-servlet:
        enabled: true
        allow:
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: true #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      grace-destroy: false #是否优雅关闭数据源，默认为false，设置为true时，关闭数据源时如果数据源中还存在活跃连接，至多等待10s后强制关闭
      druid:
        initial-size: 10
        # 初始化大小，最小，最大
        min-idle: 20
        maxActive: 500
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        testWhileIdle: true
        testOnBorrow: true
        validation-query: SELECT 1
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,slf4j
        filter:
          wall:
            config:
              multi-statement-allow: true
              none-base-statement-allow: true
            enabled: true
      datasource:
        master:
          druid:
            validation-query: SELECT 1
        xxx:
          druid:
            validation-query: SELECT 1
        xxx:
          druid:
            validation-query: SELECT 1`
