### ISSUE TITLE
druid1.2.22 解析建表语句 默认值(curdate()) 错误

### ISSUE THREAD

**Issue by GPF199541** [alibaba/druid#5899]
String sql = "CREATE TABLE `t2` (\n" +
                "  `id` int NOT NULL AUTO_INCREMENT,\n" +
                "  `a` varchar(60) DEFAULT NULL,\n" +
                "  `dd` json DEFAULT NULL,\n" +
                "\t`create_date` date NOT NULL DEFAULT (curdate()) COMMENT '创建日期',  \n" +
                "  `b` varchar(30) DEFAULT NULL,\n" +
                "  PRIMARY KEY (`id`)\n" +
                ") ENGINE=InnoDB";
        SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, DbType.mysql);
        List<SQLStatement> sqlStatements = parser.parseStatementList();
        for(SQLStatement sqlStatement:sqlStatements){
            System.out.println(sqlStatement);
        }
CREATE TABLE `t2` (
	`id` int NOT NULL AUTO_INCREMENT,
	`a` varchar(60) DEFAULT NULL,
	`dd` json DEFAULT NULL,
	`create_date` date NOT NULL DEFAULT curdate() COMMENT '创建日期',
	`b` varchar(30) DEFAULT NULL,
	PRIMARY KEY (`id`)
) ENGINE = InnoDB

SQL解析前：CREATE TABLE `t2` (
  `id` int NOT NULL AUTO_INCREMENT,
  `a` varchar(60) DEFAULT NULL,
  `dd` json DEFAULT NULL,
	`create_date` date NOT NULL DEFAULT (curdate()) COMMENT '创建日期',  
  `b` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;
SQL解析后：CREATE TABLE `t2` (
	`id` int NOT NULL AUTO_INCREMENT,
	`a` varchar(60) DEFAULT NULL,
	`dd` json DEFAULT NULL,
	`create_date` date NOT NULL DEFAULT curdate() COMMENT '创建日期',
	`b` varchar(30) DEFAULT NULL,
	PRIMARY KEY (`id`)
) ENGINE = InnoDB
后者SQL到MySQL无法执行提示语法错误
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'curdate() COMMENT '创建日期',
	`b` varchar(30) DEFAULT NULL,
	PRIMARY KEY (`' at line 5

**Comment by lizongbo** [comment]
前几天优化括号解析和生成逻辑的时候，已经优化支持这种情况了，等1.2.23版本出来即可。

```

    @Test
    public void test_parse_curdate() {
        for (DbType dbType : new DbType[]{DbType.mysql}) {
            for (String sql : new String[]{
                "CREATE TABLE t2 (\n" +
                    " id int NOT NULL AUTO_INCREMENT,\n" +
                    " a varchar(60) DEFAULT NULL,\n" +
                    " dd json DEFAULT NULL,\n" +
                    "\tcreate_date date NOT NULL DEFAULT (curdate()) COMMENT '创建日期', \n" +
                    " b varchar(30) DEFAULT NULL,\n" +
                    " PRIMARY KEY (id)\n" +
                    ") ENGINE=InnoDB",
            }) {
                SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, dbType);
                List<SQLStatement> statementList = parser.parseStatementList();
                System.out.println(statementList);
                //assertEquals(1, statementList.size());
                SQLParseAssertUtil.assertParseSql(sql, dbType);
            }
        }
    }

```

执行结果：

```
[CREATE TABLE t2 (
	id int NOT NULL AUTO_INCREMENT,
	a varchar(60) DEFAULT NULL,
	dd json DEFAULT NULL,
	create_date date NOT NULL DEFAULT (curdate()) COMMENT '创建日期',
	b varchar(30) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE = InnoDB]
mysql原始的sql===CREATE TABLE t2 (
 id int NOT NULL AUTO_INCREMENT,
 a varchar(60) DEFAULT NULL,
 dd json DEFAULT NULL,
	create_date date NOT NULL DEFAULT (curdate()) COMMENT '创建日期', 
 b varchar(30) DEFAULT NULL,
 PRIMARY KEY (id)
) ENGINE=InnoDB
mysql首次解析生成的sql===[CREATE TABLE t2 (
	id int NOT NULL AUTO_INCREMENT,
	a varchar(60) DEFAULT NULL,
	dd json DEFAULT NULL,
	create_date date NOT NULL DEFAULT (curdate()) COMMENT '创建日期',
	b varchar(30) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE = InnoDB]
mysql再次解析生成的sql===[CREATE TABLE t2 (
	id int NOT NULL AUTO_INCREMENT,
	a varchar(60) DEFAULT NULL,
	dd json DEFAULT NULL,
	create_date date NOT NULL DEFAULT (curdate()) COMMENT '创建日期',
	b varchar(30) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE = InnoDB]

进程已结束，退出代码为 0


```

**Comment by GPF199541** [comment]
1.2.23预计什么时候发布

**Comment by lizongbo** [comment]
> 1.2.23预计什么时候发布

近期我问下温少，没啥问题的话看月底前能不能发个版本吧
