### ISSUE TITLE
Postgresql修改表字段语句格式化有问题

### ISSUE THREAD

**Issue by huangyao229328404** [alibaba/druid#5909]
**dbtype:**  Postgresql
**dbversion:**  12
**druid verion:** 1.2.22
**error sql:**  ALTER TABLE mobino.alarm_count_day ALTER COLUMN warn_day TYPE character varying(100)
**testcase code:**
String sql = "ALTER TABLE mobino.alarm_count_day ALTER COLUMN warn_day TYPE character varying(100)";
String formatSql = SQLUtils.format(sql, DbType.postgresql);
System.out.println(formatSql);
**stacktrace info:**
输出结果为:  
ALTER TABLE mobino.alarm_count_day
	ALTER COLUMN warn_day character varying(100)
**error info:**
sql语句中的TYPE 解析之后不见了

**Comment by lizongbo** [comment]
最新代码已经支持，等1.2.23版本验证
