### ISSUE TITLE
DruidDataSource.getConnectionDirect优化建议

### ISSUE THREAD

**Issue by maxid** [alibaba/druid#591]
该方法中调用了discardConnection，而discardConnection调用了JdbcUtils.close(readConnect)，似乎没有考虑到数据库主动断开连接的情况，导致日志经常输出java.sql.SQLRecoverableException: IO Error: Broken pipe

实际上，discardConnection在一个无限循环中，其后紧随的是continue; 并不影响getConnection，所以是否不要生硬的输出以上Exception误导用户呢？

**Comment by zpa3x60** [comment]
这种问题很耗时，为什么在主动检测时候不保活？
