### ISSUE TITLE
sql监控为什么只能显示1000条

### ISSUE THREAD

**Issue by sunshio** [alibaba/druid#5911]
**dbtype:** 
**dbversion:** 
**druid verion:**
**error sql:**
**testcase code:**
**stacktrace info:**
**error info:**
---

**Comment by lizongbo** [comment]
因为默认值是1000

`
    private int maxSqlSize = 1000;

`
想要调整，则通过jvm启动参数指定 -Ddruid.stat.sql.MaxSize=1234 这样来调整，因为sql作为key占用了内存，注意别把内存撑爆了.

或者执行连接池的属性配置：

`
        dataSource.setConnectionProperties("druid.stat.sql.MaxSize=2000");
`
