### ISSUE TITLE
求大佬帮忙看看, 万分感谢!!! linux系统上初始化建立连接很慢, 一个连接大概10S

### ISSUE THREAD

**Issue by sleyxn** [alibaba/druid#5912]
<!--
please follow the issue template below for bug reports and feature requests
for example, if you are reporting a bug, please provide the following information:
dbtype: Oracle
dbversion: 19
duird version: 1.2.8
![1ee0589bcde9591cb8b30aa9f28ccd9d](https://github.com/alibaba/druid/assets/103576254/64a03187-7796-4689-b7a4-6b46f665c364

**Comment by sleyxn** [comment]
![Uploading 1ee0589bcde9591cb8b30aa9f28ccd9d.png…]()

**Comment by sleyxn** [comment]
![bb5e7fd0e562f94e27738fe80eb537ec](https://github.com/alibaba/druid/assets/103576254/052813ec-eaef-45fe-a4eb-a8d087cc4353)

**Comment by sleyxn** [comment]
![1ee0589bcde9591cb8b30aa9f28ccd9d](https://github.com/alibaba/druid/assets/103576254/fbd109c8-763a-4167-a9e0-754dbde66337)

**Comment by lizongbo** [comment]
你这个十秒卡点太准了，看下操作系统设置之类的地方吧，这种只能从自己的实际场景来查，看下你们是不是有用到域名解析。

**Comment by 4fool** [comment]
需要定位出慢在哪里了，可以尝试使用arthas trace命令分析一下
