### ISSUE TITLE
连接池连接泄漏，大量空闲连接不释放

### ISSUE THREAD

**Issue by SoulFerry-1** [alibaba/druid#5918]
druid连接池核心配置如下：（用于pg内核的vastbase数据库）
minIdle：5
maxActive：20
testWhileIdle：true
timeBetweenEvictionRunsMillis：60000
minEvictableIdleTimeMillis：60000

问题：
对应连接池版本为1.2.15，实际使用过程中，存在大量的空闲连接不释放，不知道是因为配置不合理还是当前源码存在连接泄漏的情况。
从代码来看，确实存在一部分连接既没有放到回收池，也没有放到保活池。哪位大哥帮忙看看，这个未处理的连接是否会导致连接泄漏。
![连接池泄漏](https://github.com/alibaba/druid/assets/50396520/3d71d46d-12c2-4aba-8441-500a322fed7d)

**Comment by liuyandeng** [comment]
有报错connection holder is null吗

**Comment by 4fool** [comment]
1.2.15版本存在连接泄露的bug （#5422 中有连接泄露复现的示例），可以升级到最新版本1.2.22试试

**Comment by liuyandeng** [comment]
> 1.2.15版本存在连接泄露的bug （#5422 中有连接泄露复现的示例），可以升级到最新版本1.2.22试试

@4fool 请帮忙看下#5920 问题,是否是和此类问题相同

**Comment by SoulFerry-1** [comment]
已经升级到最新1.2.22版本了，大致就是销毁线程过程中产生的，我将timeBetweenEvictionRunsMillis，改成了2分钟，空闲连接就每2分钟生成一次，之前是1分钟生成一次，也并不是所有的都不回收，会有大部分空闲连接不回收。pg_stat_activity表中，诸如commit，select 1，show transaction isloation，都不回收。应该是连接泄露未解决的，最新版本的那一段逻辑中，还是存在这个问题的

**Comment by SoulFerry-1** [comment]
> 有报错connection holder is null吗

没有噢

**Comment by SoulFerry-1** [comment]
> 1.2.15版本存在连接泄露的bug （#5422 中有连接泄露复现的示例），可以升级到最新版本1.2.22试试

已经升级到最新版本，仍然存在大量连接泄露的问题

**Comment by lizongbo** [comment]
使用最新的1.2.22验证，并检查代码中存在连接未关闭的场景，我们在项目中通过自定义filter监控了每个连接的借用和归还，将可能没有及时归还的连接监控告警出来。

**Comment by SoulFerry-1** [comment]
> 使用最新的1.2.22验证，并检查代码中存在连接未关闭的场景，我们在项目中通过自定义filter监控了每个连接的借用和归还，将可能没有及时归还的连接监控告警出来。
今天排查出来原因了，设置了socketTimeout参数为10分钟，将此参数去掉后，问题解决。默认为10秒，是不是当连接查询超过10秒钟，会出现报错的情况，我暂时还没测试

**Comment by lizongbo** [comment]
1.2.22之前的版本使用了不合理的10秒默认值，升级到1.2.22来。
