### ISSUE TITLE
DruidConnectionProvider不适用Hibernate4.3

### ISSUE THREAD

**Issue by guocw998** [alibaba/druid#592]
Druid通过实现Hibernate接口ConnectionProvider提供对hibernate的支持：
public class DruidConnectionProvider implements ConnectionProvider, Configurable,Stoppable {
在最新版中Druid1.0.6中，继承的是org.hibernate.service.jdbc.connections.spi.ConnectionProvider,
Hibernate4.3的ConnectionProvider接口声明已经被修改为：
org.hibernate.engine.jdbc.connections.spi.ConnectionProvider

**Comment by ljluestc** [comment]
import org.hibernate.engine.jdbc.connections.spi.ConnectionProvider;
import org.hibernate.service.spi.Configurable;
import org.hibernate.service.spi.Stoppable;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Properties;

public class DruidConnectionProvider implements ConnectionProvider, Configurable, Stoppable {

    @Override
    public Connection getConnection() throws SQLException {
        // Implement the getConnection method using Druid's connection pool
        // Return the Connection from the pool
        return null;
    }

    @Override
    public void closeConnection(Connection connection) throws SQLException {
        // Close the provided connection using Druid's connection pool handling
    }

    @Override
    public boolean supportsAggressiveRelease() {
        return false;
    }

    @Override
    public boolean isUnwrappableAs(Class unwrapType) {
        return false;
    }

    @Override
    public <T> T unwrap(Class<T> unwrapType) {
        return null;
    }

    @Override
    public void configure(Properties properties) {
        // Initialize and configure Druid connection pool
        // Use properties to set up the connection pool settings
    }

    @Override
    public void stop() {
        // Stop the Druid connection pool
    }
}
