### ISSUE TITLE
During the runtime of a Spring Boot project, if an exception occurs with the data source connection, how can the data source automatically recover its connection after it has been restored?

### ISSUE THREAD

**Issue by 303470934** [alibaba/druid#5921]
**dbtype: mysql
**dbversion: 8.0.35
**druid verion: 1.2.1
**error sql:**
**testcase code:**
**stacktrace info:**
**error info: mysql connection error

At project startup, the database is functioning normally.  During project operation, an abnormality with the database server leads to exceptions in database connections.  This results in the Spring Boot project continuously reporting errors, causing exception requests to exhaust the resources of the database connection pool and thereby rendering the Spring Boot project unresponsive.

Question 1: How can we prevent exception requests from depleting the database connection pool resources and causing the project to hang?
Question 2: Without restarting the Spring Boot project, how can we enable the database connection pool to automatically restore connections to the异常database service, thereby restoring normal operation to the entire project?

**Comment by lizongbo** [comment]
请使用最新的1.2.22验证。
