### ISSUE TITLE
statement closed

### ISSUE THREAD

**Issue by liujunbo233** [alibaba/druid#5925]
辛苦看下，当服务运行一段时间以后就会报这个错误

配置：
![image](https://github.com/alibaba/druid/assets/49676771/39de5acb-d7d0-4c2b-9c65-744b2fabb01b)
查询sql
![image](https://github.com/alibaba/druid/assets/49676771/ef390439-7c77-4530-86e5-5e2ce4c0869e)

**Comment by liujunbo233** [comment]
我这是是开启了pscache

**Comment by lizongbo** [comment]
把pscache禁用再看下，一般的场景不需要靠这个提升性能
