### ISSUE TITLE
druid1.2.22解析Clickhouse array join有误

### ISSUE THREAD

**Issue by GPF199541** [alibaba/druid#5933]
sql = "SELECT * FROM base_customized_cost ARRAY JOIN split.service AS `service` WHERE capture_time >= DATE('2024-04-01') AND capture_time < DATE('2024-05-01') LIMIT 100;";
SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, DbType.clickhouse);
List<SQLStatement> sqlStatements = parser.parseStatementList();
for(SQLStatement sqlStatement:sqlStatements){
     if(sqlStatement instanceof SQLSelectStatement){
                SQLSelectStatement sqlSelectStatement = (SQLSelectStatement) sqlStatement;
                System.out.println(sqlSelectStatement);
            }
}

解析 clickhouse SQL，array join解析为别名了

**Comment by lizongbo** [comment]
是解析成表名“base_customized_cost ARRAY”了，等这几天1.2.23发布之后，再来优化识别逻辑
