### ISSUE TITLE
plsql 这个为啥还能复现 我看之前好像已经处理过了 

### ISSUE THREAD

**Issue by qiurunze123** [alibaba/druid#5934]
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'desc nulls last
                
',expect IDENTIFIER, actual IDENTIFIER nulls

 <postgresql.version>42.3.2</postgresql.version>
        <druid.version>1.2.21</druid.version>
好像不影响查询 但是一直报错 不支持这个desc nulls last

**Comment by lizongbo** [comment]
发完整的sql语句来

**Comment by qiurunze123** [comment]
SELECT
    gmt_create,
    gmt_modified,
    id,
    portrait_id,
    title,
    status,
    main_pict,
    cluster_id,
    cluster_ord,
    main_sku_title,
    main_sku_buy_price,
    main_sku_buy_pict,
    threshold_price,
    cate_level1_id,
    cate_level1_name,
    cate_level2_id,
    cate_level2_name,
    cate_leaf_name,
    cate_leaf_id,
    cate_level3_id,
    cate_level3_name,
    match_score,
    hyperlink_id,
    competition_id,
    portrait_reporter,
    seed_item_url,
    seed_item_Id,
    create_type,
    hot_item_prove,
    specification_sku,
    audit_reason,
    audit_note,
    environment,
    plan_id,
    cate_priority,
    is_win_product_bid,
    min_bid_price,
    max_bid_price,
    item_source_type,
    big_explosive_items,
    small_explosive_items,
    seller_id,
    order_score,
    platform_type,
    item_slave_num,
    item_evaluate_num,
    item_top_info,
    sku_id,
    sku_title,
    sku_price,
    sku_threshold_price,
    sku_threshold_price_penny,
    sku_pict,
    sku_type,
    extend_json,
    CASE WHEN b.cate_id IS NOT NULL THEN
        'yes'
    ELSE
        'no'
    END AS is_match_available_cate,
    trd_level_sn,
    brand_authorized_sn,
    CASE WHEN a.cate_priority = 'P3' THEN
        8
    WHEN a.cate_priority = 'P2' THEN
        9
    WHEN a.cate_priority = 'P1' THEN
        10
    ELSE
        7
    END AS cate_priority_order,
    CASE WHEN c.item_cnt IS NOT NULL THEN
        1
    ELSE
        0
    END AS item_cnt_order,
    is_open
FROM
    c2m_plan_paid_portrait AS a
    LEFT JOIN (
        SELECT
            supplier_id,
            cate_id,
            cate_name,
            trd_level,
            trd_level_sn,
            trd_ord,
            item_count,
            brand_authorized,
            brand_authorized_sn,
            season_type,
            season_type_sn,
            order_30d,
            order_90d_future,
            seasonal_rank_score,
            seasonal_label
        FROM
            dwd_tgc_opp_hot_query_seller_basic_info_holo
        WHERE
            dshh = max_pt('dwd_tgc_opp_hot_query_seller_basic_info_holo')
            AND supplier_id = 0) AS b ON a.cate_leaf_id = b.cate_id
    LEFT JOIN (
        SELECT
            supplier_id,
            portrait_id AS portrait_id_same_supplier_item,
            compete_item_id,
            cluster_id AS cluster_id_same_supplier_item,
            item_cnt
        FROM
            c2m_price_portrait_compete_same_supplier_item
        WHERE
            ds = max_pt('c2m_price_portrait_compete_same_supplier_item')
            AND supplier_id = 0) AS c ON a.portrait_id = c.portrait_id_same_supplier_item
    LEFT JOIN (
        SELECT
            portrait_id AS portrait_id_group,
            string_agg(sku_id, ',') AS sku_id,
            string_agg(sku_title, ',') AS sku_title,
            string_agg(sku_price, ',') AS sku_price,
            string_agg(sku_threshold_price, ',') AS sku_threshold_price,
            string_agg(sku_threshold_price_penny, ',') AS sku_threshold_price_penny,
            string_agg(sku_pict, ',') AS sku_pict,
            string_agg(sku_type, '#') AS sku_type
        FROM (
            SELECT
                sku_id,
                CASE WHEN sku_title IS NOT NULL THEN
                    sku_title
                ELSE
                    'no'
                END AS sku_title,
                CASE WHEN sku_price IS NOT NULL THEN
                    sku_price
                ELSE
                    'no'
                END AS sku_price,
                CASE WHEN sku_threshold_price IS NOT NULL THEN
                    sku_threshold_price
                ELSE
                    'no'
                END AS sku_threshold_price,
                portrait_id,
                CASE WHEN sku_threshold_price_penny IS NOT NULL THEN
                    cast(sku_threshold_price_penny AS varchar)
                ELSE
                    'no'
                END AS sku_threshold_price_penny,
                CASE WHEN sku_pict IS NOT NULL THEN
                    sku_pict
                ELSE
                    'no'
                END AS sku_pict,
                CASE WHEN sku_type IS NOT NULL THEN
                    sku_type
                ELSE
                    'no'
                END AS sku_type
            FROM
                public.c2m_t_portrait_sku_rel
            WHERE
                status = ?) AS relgroup
        GROUP BY
            portrait_id) AS d ON a.portrait_id = d.portrait_id_group
    LEFT JOIN (
        SELECT
            portrait_id AS portrait_id_e,
            source_type,
            is_open
        FROM
            portrait_scene_pool) AS e ON a.portrait_id = e.portrait_id_e
ORDER BY
    order_score DESC nulls LAST,
    trd_level_sn DESC nulls LAST,
    item_cnt_order DESC nulls LAST,
    portrait_id DESC nulls LAST
LIMIT ? offset ?

**Comment by qiurunze123** [comment]
ORDER BY
order_score DESC nulls LAST,
trd_level_sn DESC nulls LAST,
item_cnt_order DESC nulls LAST,
portrait_id DESC nulls LAST

**Comment by lizongbo** [comment]
我验证了解析是正常的，相关解析代码最后一次的修改，也是2020的时候优化的，一直解析正常。
仔细检查你的依赖包版本应该是没有真正更新到最新。


![image](https://github.com/alibaba/druid/assets/1670666/2835830e-be5a-475d-8298-777e1303b556)


```
public class Issue5934 {


    @Test
    public void test_parse_nullslast() {
        for (DbType dbType : new DbType[]{DbType.mysql,DbType.oracle,DbType.postgresql}) {
            for (String sql : new String[]{
                "SELECT\n"
                    + "gmt_create,\n"
                    + "is_open\n"
                    + "FROM\n"
                    + "portrait_scene_pool \n"
                    + "ORDER BY\n"
                    + "aaa ASC nulls FIRST,\n"
                    + "order_score DESC nulls FIRST,\n"
                    + "trd_level_sn DESC nulls FIRST,\n"
                    + "item_cnt_order DESC nulls LAST,\n"
                    + "portrait_id DESC nulls LAST\n"
                    + "LIMIT ? offset ?;",
            }) {
                SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, dbType);
                List<SQLStatement> statementList = parser.parseStatementList();
                System.out.println(statementList);
                assertEquals(1, statementList.size());
                SQLParseAssertUtil.assertParseSql(sql, dbType);
            }
        }
    }
}


```
