### ISSUE TITLE
druid starter从1.2.22版本开始，配置属性没有提示

### ISSUE THREAD

**Issue by GodLiang** [alibaba/druid#5952]
![微信截图_20240530160703](https://github.com/alibaba/druid/assets/16900397/e77b526f-dd2d-4aaf-9289-b90423396a26)
1.2.21版本正常。看了下jar，1.2.22版本开始spring-configuration-metadata.json没有了。

**Comment by lizongbo** [comment]
等1.2.24版本，已经优化，
