### ISSUE TITLE
druid最新代码解析clickhouse array join 有误

### ISSUE THREAD

**Issue by GPF199541** [alibaba/druid#5954]
druid 最新代码 1.2.24 snap

SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, DbType.clickhouse);
List sqlStatements = parser.parseStatementList();
for(SQLStatement sqlStatement:sqlStatements){
if(sqlStatement instanceof SQLSelectStatement){
SQLSelectStatement sqlSelectStatement = (SQLSelectStatement) sqlStatement;
System.out.println(sqlSelectStatement);
}
}

解析前：
SELECT 
	capture_time,
	resource_uid,
	service_uid,
	s_cost, 
	cost
FROM base_customized_cost
LEFT ARRAY JOIN
	split.service_uid AS service_uid,split.cost AS s_cost
WHERE
	capture_time >= DATE('2024-03-19')
	AND capture_time < DATE('2024-04-01')
	AND `ler_3` = '1'
    AND `middleware_type` = ''
    AND resource_uid = 'b3b1f4a7a7ce4c7ab9ff7619c9f0eac0'
    AND service_uid = 'f874cc2a3e934e488769eb9e2d82479e'
ORDER BY capture_time ASC

解析后：
SELECT capture_time, resource_uid, service_uid, s_cost, cost
FROM base_customized_cost
	LEFT ARRAY JOIN split.service_uid service_uid, split.cost s_cost
WHERE capture_time >= DATE('2024-03-19')
	AND capture_time < DATE('2024-04-01')
	AND `ler_3` = '1'
	AND `middleware_type` = ''
	AND resource_uid = 'b3b1f4a7a7ce4c7ab9ff7619c9f0eac0'
	AND service_uid = 'f874cc2a3e934e488769eb9e2d82479e'
ORDER BY capture_time ASC

去除了 array join 的 as 导致sql执行报错
报错信息：
Syntax error: failed at position 122 ('service_uid') (line 3, col 35):

SELECT capture_time, resource_uid, service_uid, s_cost, cost
FROM base_customized_cost
LEFT ARRAY JOIN split.service_uid service_uid, split.cost s_cost
WHERE capture_time >= DATE('2024-03-19')
AND capture_time < DATE('2024-04-01')
AND `ler_3` = '1'
AND `middleware_type` = ''
AND resource_uid = 'b3b1f4a7a7ce4c7ab9ff7619c9f0eac0'
AND service_uid = 'f874cc2a3e934e488769eb9e2d82479e'
ORDER BY capture_time ASC;

Expected one of: UNION, LIMIT, WHERE, WINDOW, DoubleColon, INNER, LIKE, GLOBAL NOT IN, end of query, HAVING, AS, DIV, IS, UUID, GROUP BY, INTO OUTFILE, OR, QuestionMark, BETWEEN, OFFSET, NOT LIKE, MOD, LEFT ARRAY JOIN, PREWHERE, AND, JOIN, Comma, alias, ORDER BY, array join, SETTINGS, IN, ARRAY JOIN, ILIKE, FORMAT, Dot, NOT ILIKE, WITH, NOT, table, table function, subquery or list of joined tables, token, NOT IN, GLOBAL IN

**Comment by lizongbo** [comment]
优化逻辑增强了解析。 #5955
