### ISSUE TITLE
druid最新代码解析json建立索引有误

### ISSUE THREAD

**Issue by GPF199541** [alibaba/druid#5958]
druid1.2.24 snap
alter TABLE test.rs_urge_pickup_config ADD KEY idx_site_id_list2 ((cast(site_id_list as char(10) array))),
ADD KEY idx_site_from_list2 ((cast(site_from_list as char(30) array))),
ADD KEY idx_shipping_channel_list2 ((cast(shipping_channel_list as char(50) array)));

这个SQL解析括号有问题，我拉最新的代码测试，发现少了个括号
现在解析出来是这样的：
ALTER TABLE test.rs_urge_pickup_config
ADD KEY idx_site_id_list2 (CAST(site_id_list AS char(10) ARRAY)),
ADD KEY idx_site_from_list2 (CAST(site_from_list AS char(30) ARRAY)),
ADD KEY idx_shipping_channel_list2 (CAST(shipping_channel_list AS char(50) ARRAY));

1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CAST(site_id_list AS char(10) ARRAY)),
ADD KEY idx_site_from_list2 (CAST(`s' at line 2

缺括号

要解析成
ALTER TABLE test.rs_urge_pickup_config
ADD KEY idx_site_id_list2 ((CAST(site_id_list AS char(10) ARRAY))),
ADD KEY idx_site_from_list2 ((CAST(site_from_list AS char(30) ARRAY))),
ADD KEY idx_shipping_channel_list2 ((CAST(shipping_channel_list AS char(50) ARRAY)));

这样才对

**Comment by lizongbo** [comment]
mysql版本是多少？发一下完整的建表语句，我验证一下语法，目前这种多重括号的情况，druid解析是归一化成了一层，要改的难度非常大，我要验证下mysql是不是强依赖这个多重括号。
