### ISSUE TITLE
使用MySqlWallProvider对sql执行check方法，发现无法识别rlike关键词

### ISSUE THREAD

**Issue by k4n5ha0** [alibaba/druid#5960]
dbtype: mysql
dbversion: 5.7.41
duird version: 1.2.23
error sql: select id from x where id = 'dato2' RLIKE SLEEP(5) AND 'XArD'='XArD'
error info: com.alibaba.druid.sql.parser.ParserException: not supported.pos 41, line 1, column 36, token RLIKE
![image](https://github.com/alibaba/druid/assets/22064977/a5b107d6-f99a-4af7-8cb1-436467402dfa)

期望：
增加rlike关键词的识别，避免sql注入

**Comment by lizongbo** [comment]
这个sql语句本身就是语法错误的，不可能解析成语法树

**Comment by k4n5ha0** [comment]
![image](https://github.com/alibaba/druid/assets/22064977/ba72ccdc-7936-403d-b973-1e3f67663183)
@lizongbo
