### ISSUE TITLE
springboot2.7.8 + mysql 8.4.0 + druid-springboot-starter 不能用withRecursive递归查询，一使用就报语法错误,sql本身是没问题

### ISSUE THREAD

**Issue by lesionlinlin** [alibaba/druid#5965]
springboot2.7.8 + mysql 8.4.0 + druid-springboot-starter 不能用withRecursive递归查询，一使用就报语法错误,sql本身是没问题

**Comment by lizongbo** [comment]
发完整的sql语句来，这个语法是加了支持的
