### ISSUE TITLE
解析hive创建表时不能识别STORED BY

### ISSUE THREAD

**Issue by HandSomeMan111111** [alibaba/druid#5968]
解析hive创建表时不能识别STORED BY

报错为

语句是
CREATE TABLE IF NOT EXISTS `test.tests`(\n  `id` bigint COMMENT 'from deserializer', \n  `job_group` bigint COMMENT 'from deserializer', \n  `job_id` bigint COMMENT 'from deserializer', \n  `ums_ts_` bigint COMMENT 'from deserializer') comment 'test'\nROW FORMAT SERDE \n  'org.apache.paimon.hive.PaimonSerDe' \nSTORED BY \n  'org.apache.paimon.hive.PaimonStorageHandler'

我在issue列表里面看到这个问题已经被closed，
issue 列表为https://github.com/alibaba/druid/issues/4622
但是即使我升级到最新的1.2.3版本也还是有问题

**Comment by lizongbo** [comment]
看了下官方有两种语法,，目前只支持STORED AS，近期我加一下适配。

  [STORED AS file_format]
     | STORED BY 'storage.handler.class.name' [WITH SERDEPROPERTIES (...)] 

https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL

**Comment by HandSomeMan111111** [comment]
我看这个问题之前有人提交过，然后代码已经被merge了，但是我在新的版本里面没发现
ps 预计哪个版本可以使用呢

**Comment by lizongbo** [comment]
> 我看这个问题之前有人提交过，然后代码已经被merge了，但是我在新的版本里面没发现 ps 预计哪个版本可以使用呢

等 1.2.24
