### ISSUE TITLE
Druid Startrt 1.2.21+ && SpringBoot 3.2.3+ && JDK21/17 starter配置文件参数无法识别

### ISSUE THREAD

**Issue by CxMYu** [alibaba/druid#5972]
Druid Startrt 1.2.21+ && SpringBoot 3.2.3+ && OPENJDK21/17 starter参数无法识别
SpringBoot 3.2.3、OPENJDK17 Druid 1.2.21 可以识别
![image](https://github.com/alibaba/druid/assets/80197535/61d78dc2-71f2-4877-bc3f-dd2b26eaabea)

SpringBoot 3.2.5、OPENJDK21 Druid Startrt 1.2.22/1.2.23都无法识别 降级1.2.21可以识别
![image](https://github.com/alibaba/druid/assets/80197535/58575f79-ed17-4fc0-9c1c-9f00562cd6e9)

**Comment by lizongbo** [comment]
是说idea没有提示么？是的话，等1.2.24， 22和23的 maven插件构建没有生成meta文件

**Comment by CxMYu** [comment]
yes 中间这俩版本上述参数配置 暂时只能通过手动bean注入来吗

**Comment by CxMYu** [comment]
> 是说idea没有提示么？是的话，等1.2.24， 22和23的 maven插件构建没有生成meta文件

yes 中间这俩版本上述参数配置 暂时只能通过声明式bean注册吗

**Comment by lizongbo** [comment]
> > 是说idea没有提示么？是的话，等1.2.24， 22和23的 maven插件构建没有生成meta文件
> 
> yes 中间这俩版本上述参数配置 暂时只能通过声明式bean注册吗

这个只是没有idea的语法提示，不影响功能。

**Comment by johnnyee** [comment]
我也遇到了这个问题
