### ISSUE TITLE
含有 rename 的 alert table 语句被解析为单纯 rename， alter table 其余信息丢失

### ISSUE THREAD

**Issue by zycgit** [alibaba/druid#5976]
dbtype: mysql
dbversion: 5.7
duird version: 1.2.23
error sql: alter table test.abc comment 'abc' engine MyISAM, rename abc_test
error info: 

<img width="1057" alt="image" src="https://github.com/alibaba/druid/assets/4951471/55658cda-cdfc-49c1-824b-2b8383a46748">

解析丢失语句

**Comment by lizongbo** [comment]
等1.2.24版验证即可
