### ISSUE TITLE
新版本starter不支持module-info.java

### ISSUE THREAD

**Issue by mingyang66** [alibaba/druid#5979]
新版本不支持module-info.java模式引入指定的类，如果在个人项目中引入会报如下：
`ackage 'com.alibaba.druid.spring.boot3.autoconfigure.stat' is declared in module with an invalid name ('druid.spring.boot.3.starter')`
应该是根据包名默认解析的module名称，带了数字不符合规范，看看能不能支持下 @lizongbo @wenshao

**Comment by mingyang66** [comment]
建议把springboot3版本的druid-spring-boot-3-starter包名修改为druid-spring-boot3-starter

**Comment by lizongbo** [comment]
等1.2.24版本验证
