### ISSUE TITLE
打印日志的时候，Double类型转BigDecimal不对

### ISSUE THREAD

**Issue by strivezsh** [alibaba/druid#5990]
com/alibaba/druid/sql/visitor/SQLASTOutputVisitor.java
line:3106
        if (param instanceof Double) {
            param = new BigDecimal((double) param);
        }

应该是
            param = new BigDecimal(param.toString());

**Comment by strivezsh** [comment]
```
        Object d = 2.6D;
        BigDecimal bd1 = new BigDecimal((double) d);
        BigDecimal bd2 = new BigDecimal(d.toString());

        System.out.println(bd1.toString());
        System.out.println(bd2.toString());
```

2.600000000000000088817841970012523233890533447265625
2.6

**Comment by lizongbo** [comment]
#5994 这个pr做了修复
