### ISSUE TITLE
基于springboot需要配置login-username和login-password，请问可以不配置（免密）直接登录的参数

### ISSUE THREAD

**Issue by he0xff** [alibaba/druid#5995]
**dbtype:** 
**dbversion:** 
**druid verion: 1.26.1
**error sql:**
**testcase code:**
**stacktrace info:**
**error info:**
---

**Comment by lizongbo** [comment]
druid组件没有1.26.1这个版本，没有什么login-username和login-password配置。
apache druid 也没有1.26.1版本

问错东西了
