### ISSUE TITLE
多线程使用同一链接且开启事务时，事务sql日志会缺失部分sql

### ISSUE THREAD

**Issue by RichardSong-dev** [alibaba/druid#5999]
**dbtype:mysql/oceanbase**
**dbversion:5.7/4.3**
**druid verion:1.2.20**
**error info:
在多线程使用druid创建的同一数据库连接且开启事务时，在事务提交时用时超过transactionThresholdMillis的情况下，打印的事务sql日志信息会遗漏部分sql。
问题的原因是TransactionInfo.getSqlList()方法未进行并发控制，且sqlList成员变量使用的不是线程安全的list，导致在并发向sqlList中写入数据时会产生数据丢失的问题。**

**Comment by lizongbo** [comment]
多线程使用同一连接的做法就是错误的。
