### ISSUE TITLE
ajax请求收到302，就死循环了

### ISSUE THREAD

**Issue by zhhzhfya** [alibaba/druid#606]
项目组你们好：
## 我用ajax post请求后台一个请求获取数据，用了 DruidWebStatFilter，过滤是“/*”，收到的是一个302 found，然后ie就跳转，又收到302，然后ie就跳转，这个ajax请求就死循环了。

请求头：
请求  POST /com.hd.DoServlet HTTP/1.1
Accept  _/_
Accept-Language zh-cn
Referer http://localhost:8080/com.hd.DoServlet?func=SY_FORM_DEF
Content-Type    application/x-www-form-urlencoded;charset=utf-8
Accept-Encoding gzip, deflate
User-Agent  Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/6.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; MALCJS)
Host    localhost:8080
Content-Length  310
DNT 1
Connection  Keep-Alive
Cache-Control   no-cache
## Cookie  JSESSIONID=abcLDX402xQcqaevH7FEu; cookie_lang=1; SY_FUNC_search=inline

响应标头：
响应  HTTP/1.1 302 Found
Server  Resin/3.2.0
Location    http://localhost:8080/com.hd.DoServlet?func=SY_FORM_DEF&sessionFlag=1&actParam=&isPageReadOnly=null&parentFuncCode=&FORM_CONF_CODE=&isInTab=false&isMain=false&parentFunc=&parentKeyCode=&topMainFuncCode=&topSelectedCodes=&topWfProcInstCode=&topWfActInstCode=&isAjaxRequest=true&isSub=false&parentFuncCode=&FORM_CONF_CODE=
Content-Type    text/html; charset=GBK
Content-Length  358
Date    Mon, 04 Aug 2014 07:41:35 GMT

**Comment by lizongbo** [comment]
请使用最新版验证
