### ISSUE TITLE
SQL监控页面的执行时间分布是啥意思呢？

### ISSUE THREAD

**Issue by monkeychen** [alibaba/druid#626]
您好！
       初次使用Druid的监控页面，想问下：SQL监控页面的【[1,0,0,0,0,0,0,0]】是什么意思呢？括号的数值为执行的行数，每个逗号间隔时间为多少呢？
       期待您的回复，谢谢！

**Comment by wzdark** [comment]
我也不知道 同问

**Comment by DevilMayCrySamsara** [comment]
同问

**Comment by yufeng217** [comment]
列的头部有提示。
比如鼠标放在「执行时间分布」的「-」处，会提示「0-1毫秒次数」

**Comment by kevin-wang001** [comment]
是有提示，比较隐蔽。“-”太小了，放大了才定位
