### ISSUE TITLE
大神，oracle11g 上开启testOnBorrow时，申请链接时疯狂地开启线程导致服务器崩溃

### ISSUE THREAD

**Issue by yin-bp** [alibaba/druid#656]
oracle11g 上开启testOnBorrow时，申请链接时疯狂地开启线程，导致服务器崩溃
使用druid版本：druid-0.2.23-20130715.145141-15.jar

**Comment by ChetWang** [comment]
@wenshao
是1.0.12版实现还是1.1.12啊？1.1版本都还没出现呢
