### ISSUE TITLE
restart的逻辑好像没有实现完善？有部分计数器未清理导致restart后依然无法申请链接。

### ISSUE THREAD

**Issue by jinxfei** [alibaba/druid#661]
使用的测试代码很简单，创建一个连接池，设置maxActive为5，然后连续申请五个链接，都不关闭。

这时候重启

> dsInst.setResetStatEnable(true);
> dsInst.restart();

之后
dsInst.getConnection(5000)
依然报TimeoutException。

跟踪了一下，好像是activeCount这个统计数字在restart的时候，没有被清零。

**Comment by gyk001** [comment]
请问怎么restart数据源，ActiveCount>0的时候restart会失败啊，我现在想强制所有连接重连应该怎么操作
