### ISSUE TITLE
如何将监控数据保存到数据库里？

### ISSUE THREAD

**Issue by wzdfr** [alibaba/druid#670]
请教如何将监控数据保存到数据库里？
我看都提供了创建对应存储的SQL DDL了，应该是可以把监控数据对应的保存至数据库表中的吧。
我该如何做？
麻烦大神们给给回复！谢谢！

**Comment by ydq** [comment]
@wenshao 挖个坟，话说监控数据写数据库功能完成了吗？看官方wiki都没提到这个，貌似都只有输出到日志文件的。
