### ISSUE TITLE
建议在log4j输出格式化sql前面添加一个换行符。

### ISSUE THREAD

**Issue by cgz1211** [alibaba/druid#673]
现在的输出：
[DEBUG]-[Thread: main]-[com.alibaba.druid.filter.logging.Log4jFilter.statementLog()]: {conn-10010, pstmt-20022} executed. SELECT g.*, c.Name AS ParentName
FROM Tb_Group g
    LEFT JOIN Tb_Group c ON g.parentid = c.grid
WHERE g.Grid = '540753f6e886469abda8b0f39938f6ea'

希望的输出：
[DEBUG]-[Thread: main]-[com.alibaba.druid.filter.logging.Log4jFilter.statementLog()]: {conn-10010, pstmt-20022} executed. 
SELECT g.*, c.Name AS ParentName
FROM Tb_Group g
    LEFT JOIN Tb_Group c ON g.parentid = c.grid
WHERE g.Grid = '540753f6e886469abda8b0f39938f6ea'

**Comment by mtdp** [comment]
可以格式话sql语句成一行显示吗？多行日志会很大。
