### ISSUE TITLE
后台输出syntax error提示

### ISSUE THREAD

**Issue by it2911** [alibaba/druid#724]
开发环境是
DB ： postgreSQL + Mybatis + SpringMVC
druid的版本号是1.0.8

删除表的时候会在后台输出如下错误
DROP TABLE IF EXISTS t_report_1_19

com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'E IF EXISTS t_report_1_19',expect EXISTS, actual EXISTS EXISTS

生成表的时候会在后台输出如下错误
CREATE TABLE t_history_1_19(
    		id SERIAL NOT NULL,
			modify_history TEXT,
			modify_user INTEGER,
			modify_style INTEGER,
			modify_date TIMESTAMP WITHOUT TIME ZONE,
			report_id INTEGER,
			CONSTRAINT t_history_1_19_pkey PRIMARY KEY (id))
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'TAMP WITHOUT TIME ZONE,
			report_i',expect RPAREN, actual IDENTIFIER WITHOUT

虽然后台报错，但是实际上是执行成功的，请问如何让拼写错误提示消失

**Comment by donaldjohn** [comment]
select count(*)
from shop_inquiry
WHERE 1 = 1
      and (date_add(from_unixtime(create_time/1000), INTERVAL CONVERT(fbyxq, UNSIGNED INTEGER) MONTH) < now());
;
我的语法是这样的， Mysql， 亲测 1.1.9 问题依旧 @wenshao
