### ISSUE TITLE
ConstArithmeticAllow 无法正常拦截

### ISSUE THREAD

**Issue by wangyu4882** [alibaba/druid#728]
select * from city_list where city_id = 3-1
setConstArithmeticAllow(false)

SELECT * from city_list where 2 = case when 2=1 then 1 else 2 END
setCaseConditionConstAllow(false)

SELECT * from city_list where city_id = 1 & 2
setConditionOpBitwseAllow(false)

上述sql 在1.0.9时可以被拦截， 但在1.0.11中不行 
数据库类型Mysql

**Comment by yakolee** [comment]
已修复
