### ISSUE TITLE
大神，select * from table查询数据时，如果table是一个视图，当视图的定义发生变化时，通过字段名称获取字段值不正确

### ISSUE THREAD

**Issue by yin-bp** [alibaba/druid#734]
bboss持久层框架集成了druid连接池时，通过类似语句select \* from table查询数据时，如果table是一个视图，当视图的定义发生变化时，通过字段名称获取字段值时发生取到值是错误的。重启tomcat后，就恢复正常了。

**Comment by xuse** [comment]
MySQL么？JDBC驱动问题吧。

**Comment by yin-bp** [comment]
驱动应该是没有问题的，apache dbcp和druid用的mysql驱动是一样的，dbcp没有问题，而druid就存在问题，邪门啊

**Comment by jacking124** [comment]
版本贴一下的！

**Comment by lizongbo** [comment]
应该是看起来什么缓存参数导致的，请使用最新版验证
