### ISSUE TITLE
您好，升级了1.0.12版本后，发现/druid/下几个SQL相关的页面无内容显示；

### ISSUE THREAD

**Issue by tanqimin** [alibaba/druid#756]
具体的页面有：
/druid/datasource.html
/druid/sql.html
/druid/wall.html

使用的数据库是SQL SERVER 2014，filter已设置为stat，上一个版本（1.0.9）正常

**Comment by CodeSummer** [comment]
非常的奇怪，害的我查了半天的代码

**Comment by yakolee** [comment]
抱歉，1.0.12版本的修改引入了bug，下个版本1.0.13中修复
