### ISSUE TITLE
clob 问题

### ISSUE THREAD

**Issue by ElenaDomi** [alibaba/druid#757]
当配置了filters=stat,log4j 之后 会出现以下问题 去掉filters没有问题
com.alibaba.druid.proxy.jdbc.ClobProxyImpl cannot be cast to oracle.sql.CLOB
求教

**Comment by FightSCJP** [comment]
同求，这个问题怎么处理

**Comment by FightSCJP** [comment]
@wenshao

**Comment by lizongbo** [comment]
请使用最新版验证

**Comment by hutdonrun** [comment]
有解决吗
