### ISSUE TITLE
sql查询中的逻辑条件包围的括号丢失导致逻辑错误

### ISSUE THREAD

**Issue by xerobuffer** [alibaba/druid#761]
版本1.0.11

SELECT CIM_M_FUN_LOC.ID AS X_COL0, CIM_M_FUN_LOC.PARENT_ID AS X_COL1, CIM_M_FUN_LOC.FL_STAND_ID AS X_COL2, CIM_M_FUN_LOC.FL_CODE AS X_COL3, CIM_M_FUN_LOC.FL_NAME AS X_COL4
	, CIM_M_FUN_LOC.GRADE AS X_COL5, CIM_M_FUN_LOC.SORT_NUM AS X_COL6, CIM_M_FUN_LOC.SEQ AS X_COL7, CIM_M_FUN_LOC.LEAF AS X_COL8
FROM CIM_M_FUN_LOC
WHERE (CIM_M_FUN_LOC.ID IN ('2110239349', '2110239445')
	AND 'NA' = 'NA')
	OR (CIM_M_FUN_LOC.PARENT_ID = 'NA'
	AND 'NA' != 'NA');

经过解析后，where里面的括号全部没了，这样逻辑就发生了错误，望确认

**Comment by yakolee** [comment]
and 比 or 运算符优先级要高，没有括号，逻辑不会发生改变吧

**Comment by xerobuffer** [comment]
Sorry，确实我弄错！。
