### ISSUE TITLE
sql 解析错误

### ISSUE THREAD

**Issue by wangyu4882** [alibaba/druid#762]
select * from t_user where email = 'adf' RLIKE (SELECT (CASE WHEN (ORD(MID((SELECT DISTINCT(IFNULL(CAST(schema_name AS CHAR),0x20)) FROM INFORMATION_SCHEMA.SCHEMATA LIMIT 3,1),13,1))>64) THEN 0x616466 ELSE 0x28 END)) AND 'piKu'='piKu' and password ='912ec803b2ce49e4a541068d495ab570'
------------------------------------------
select * from t_user where email = 'adf' LIKE (SELECT (CASE WHEN (ORD(MID((SELECT DISTINCT(IFNULL(CAST(schema_name AS CHAR),0x20)) FROM INFORMATION_SCHEMA.SCHEMATA LIMIT 3,1),13,1))>64) THEN 0x616466 ELSE 0x28 END)) AND 'piKu'='piKu' and password ='912ec803b2ce49e4a541068d495ab570'
------------------------------------------
select * from t_blog where title = 'Title 1' RLIKE (SELECT (CASE WHEN (8225=8225) THEN 0x5469746c652031 ELSE 0x28 END)) AND 'WQuF'='WQuF'

上述SQL由sqlmap产生。 在1.0.12中解析错误，  Mysql数据库

**Comment by yakolee** [comment]
select * from t_blog where title = 'Title 1' RLIKE .... 类似这些SQL语句符合mysql语法规范吗？没找到相关的语法说明，麻烦提供一下

**Comment by wangyu4882** [comment]
该sql是否符合mysql规范没有找到资料，
但是该sql等价于 
select * from t_blog where title = ('Title 1' RLIKE 'a'） 
类似于 1+3-2 看哪个运算优先级高了，

类似的还有select * from t_blog where title = 'Title 1' > 'a'   
都需要判断运算符优先级

**Comment by wenshao** [comment]
不想支持这种语法！
