### ISSUE TITLE
druid1.0.12 mysql解析错误：delete * from orders where id=1

### ISSUE THREAD

**Issue by wdw1206** [alibaba/druid#769]
mysql的这个语句delete \* from orders where id=1应该报ParserException才对，但现在解析不报错。

**Comment by yakolee** [comment]
会报错的啊，贴一下你的测试代码

**Comment by wdw1206** [comment]
String sql = "delete * from orders where id=1";
		MySqlStatementParser parser = new MySqlStatementParser(sql);
		
		SQLStatement statement = parser.parseStatement();
		System.out.println(statement);
		System.out.println("test");

应该parser.parseStatement();这一句就要抛异常的。
