### ISSUE TITLE
no exception thrown when parse oracle sql "select aa bb cc" which is in bad syntax

### ISSUE THREAD

**Issue by bingoohuang** [alibaba/druid#773]
new OracleStatementParser("select aa bb cc").parseStatementList();
1) "from xxx" is required in oracle
2) in "select aa bb cc " , there is no meaning of cc

**Comment by lizongbo** [comment]
现在也不会抛异常
解析后生成的sql为 
`
SELECT aa AS bb
FROM DUAL, cc
`
