### ISSUE TITLE
我写了块关于SQL explain plan的工具，druid看看需不需要

### ISSUE THREAD

**Issue by magixsource** [alibaba/druid#776]
https://github.com/magixsource/epdog
  目的是收集那种执行慢的SQL，把计划过程找一下，方便DBA也好，开发人员也好，去分析去解决问题。

**Comment by xuse** [comment]
好像只能支持MySQL和Maria？

**Comment by magixsource** [comment]
现在暂时是在Oracle上用，其他数据库没支持。
