### ISSUE TITLE
一直报这个错误，但是又不影响结果，是怎么回事呢？com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'desc limit ?',expect IDENTIFIER, actual IDENTIFIER limit

### ISSUE THREAD

**Issue by xuminwlt** [alibaba/druid#778]
19:52:04.863 [qtp16094384-49] ERROR c.a.druid.filter.stat.StatFilter - merge sql error, dbType log4jdbc, sql : 
select this_.id as id1_28_2_, this_.createDate as createDa2_28_2_, this_.modifyDate as modifyDa3_28_2_, this_.timestamp as timestam4_28_2_, this_.company_id as company50_28_2_, this_.creater_id as creater51_28_2_, this_.state as state5_28_2_, this_.a1 as a6_28_2_, this_.a2 as a7_28_2_, this_.a3 as a8_28_2_, this_.a4 as a9_28_2_, this_.a5 as a10_28_2_, this_.b01 as b11_28_2_, this_.b02 as b12_28_2_, this_.b1 as b13_28_2_, this_.b2 as b14_28_2_, this_.b3 as b15_28_2_, this_.b4 as b16_28_2_, this_.c1 as c17_28_2_, this_.c2 as c18_28_2_, this_.c3 as c19_28_2_, this_.c4 as c20_28_2_, this_.c5 as c21_28_2_, this_.c6 as c22_28_2_, this_.c7 as c23_28_2_, this_.department as departm24_28_2_, this_.name as name25_28_2_, this_.no as no26_28_2_, this_.pinYin as pinYin27_28_2_, this_.pinYinHead as pinYinH28_28_2_, this_.snapshot_id as snapsho52_28_2_, this_.sortNo as sortNo29_28_2_, this_.sumScore as sumScor30_28_2_, this_.used as used31_28_2_, this_.users_id as users_i53_28_2_, this_.weight_Avgcycle as weight_32_28_2_, this_.weight_Avgnegotiation as weight_33_28_2_, this_.weight_BusiConversionrate as weight_34_28_2_, this_.weight_Client as weight_35_28_2_, this_.weight_Collectionrate as weight_36_28_2_, this_.weight_Completionreate as weight_37_28_2_, this_.weight_ContConversionrate as weight_38_28_2_, this_.weight_ContractMoney as weight_39_28_2_, this_.weight_Door as weight_40_28_2_, this_.weight_Grossmargin as weight_41_28_2_, this_.weight_IM as weight_42_28_2_, this_.weight_Invoice as weight_43_28_2_, this_.weight_Linkman as weight_44_28_2_, this_.weight_NewReceivables as weight_45_28_2_, this_.weight_Phone as weight_46_28_2_, this_.weight_Receipt as weight_47_28_2_, this_.weight_SumReceivables as weight_48_28_2_, this_.weight_eMail as weight_49_28_2_, company2_.id as id1_15_0_, company2_.createDate as createDa2_15_0_, company2_.modifyDate as modifyDa3_15_0_, company2_.timestamp as timestam4_15_0_, company2_.company_id as company30_15_0_, company2_.creater_id as creater31_15_0_, company2_.state as state5_15_0_, company2_.apino as apino6_15_0_, company2_.name as name7_15_0_, company2_.no as no8_15_0_, company2_.pinYin as pinYin9_15_0_, company2_.pinYinHead as pinYinH10_15_0_, company2_.address as address11_15_0_, company2_.adminId as adminId12_15_0_, company2_.apiEnable as apiEnab13_15_0_, company2_.apiSecret as apiSecr14_15_0_, company2_.apiToken as apiToke15_15_0_, company2_.apiUrl as apiUrl16_15_0_, company2_.apiWsEnable as apiWsEn17_15_0_, company2_.area as area18_15_0_, company2_.city as city19_15_0_, company2_.county as county20_15_0_, company2_.departmentShare as departm21_15_0_, company2_.description as descrip22_15_0_, company2_.headImage as headIma23_15_0_, company2_.help as help24_15_0_, company2_.ifApprove as ifAppro25_15_0_, company2_.isBestselling as isBests26_15_0_, company2_.province as provinc27_15_0_, company2_.subname as subname28_15_0_, company2_.subscription as subscri29_15_0_, users1_.id as id1_60_1_, users1_.createDate as createDa2_60_1_, users1_.modifyDate as modifyDa3_60_1_, users1_.timestamp as timestam4_60_1_, users1_.company_id as company27_60_1_, users1_.creater_id as creater28_60_1_, users1_.state as state5_60_1_, users1_.apino as apino6_60_1_, users1_.name as name7_60_1_, users1_.no as no8_60_1_, users1_.pinYin as pinYin9_60_1_, users1_.pinYinHead as pinYinH10_60_1_, users1_.address as address11_60_1_, users1_.adminId as adminId12_60_1_, users1_.birthday as birthda13_60_1_, users1_.city as city14_60_1_, users1_.county as county15_60_1_, users1_.email as email16_60_1_, users1_.focusMapLat as focusMa17_60_1_, users1_.focusMapLng as focusMa18_60_1_, users1_.headImage_id as headIma29_60_1_, users1_.idCard as idCard19_60_1_, users1_.ifEvaluate as ifEvalu20_60_1_, users1_.mobile as mobile21_60_1_, users1_.phone as phone22_60_1_, users1_.province as provinc23_60_1_, users1_.sex as sex24_60_1_, users1_.theme as theme25_60_1_, users1_.userPoint as userPoi26_60_1_ from ss_evaluateresult this_ inner join ss_company company2_ on this_.company_id=company2_.id inner join ss_users users1_ on this_.users_id=users1_.id where (this_.users_id=? or users1_.id=?) and (this_.company_id=? or company2_.id=?) and (this_.state=?) and this_.snapshot_id=? order by this_.createDate asc, this_.createDate desc limit ?
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'desc limit ?',expect IDENTIFIER, actual IDENTIFIER limit
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:229) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:325) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:121) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:116) ~[druid-1.0.12.jar:1.0.12]

**Comment by xiaozhuangzi** [comment]
@xuminwlt 

参考
issues #560 
https://github.com/alibaba/druid/issues/560

**Comment by yakolee** [comment]
数据库类型是什么？

**Comment by jacking124** [comment]
是mysql数据库的，它这个是SQL的错误order by this_.createDate asc, this_.createDate desc limit ?，到底是ase了，还是desc了！！！！

**Comment by xuminwlt** [comment]
这个错误是配了log4jdbc的url 数据库类型是 dbType log4jdbc，直接使用mysql就不报错了。@jacking124，这个我还真没注意到，谢谢。

**Comment by xunianchong** [comment]
可能是druid版本太老，建议升级一下druid版本

**Comment by yanmgingli123** [comment]
具体如何配置解决的，楼主可以分享下吗？
