### ISSUE TITLE
请问，如何

### ISSUE THREAD

**Issue by 253379672** [alibaba/druid#781]
比如执行SQL：SELECT T1.ID FROM USER T1
1.我首先将要执行的SQL拦截下来。
2.然后系统有一个配置规则，如：是把USER表的ID替换成UID。
3.使用SchemaStatVisitor来统计SQL中使用的表、字段、过滤条件、排序表达式、分组表达式。
4.我该如何替换，并重新生成新的SQL。

例子中只有看到解析SQL，没有看到生成SQL的。如何生成SQL，求助！

**Comment by lizongbo** [comment]
解析得到statment对象实例之后，修改变量，然后toString就可以生成新的sql了。
