### ISSUE TITLE
1.0.12，1.0.13内置监控页面DruidStatView，数据源只显示(*) property for user to setup, SQL监控页面为空

### ISSUE THREAD

**Issue by p0xiao** [alibaba/druid#788]
1.0.12，1.0.13内置监控页面DruidStatView，数据源只显示(*) property for user to setup, SQL监控页面为空，换回1.0.11无此问题。这是为何？

**Comment by yakolee** [comment]
会在1.0.13中修复发布

**Comment by zjhzxhz** [comment]
原来是Bug~! 让我纠结很久~!

**Comment by XIAOMIOPPO** [comment]
这个问题1.1.10还有
