### ISSUE TITLE
升级到1.0.13，总是提示“not support oracle driver 1.0”

### ISSUE THREAD

**Issue by ContyChen** [alibaba/druid#798]
升级到1.0.13，总是提示“not support oracle driver 1.0”。
在1.0.12版本没有问题。

**Comment by jacking124** [comment]
你的oracle驱动是那个版本的！！

**Comment by ContyChen** [comment]
Implementation-Vendor: Oracle Corporation
Implementation-Title: JDBC
Implementation-Version: 11.2.0.1.0
Specification-Vendor: Sun Microsystems Inc.
Specification-Title: JDBC
Specification-Version: 4.0
Main-Class: oracle.jdbc.OracleDriver
-------------------------------------------------
JDK_1.7.0_72   
spring 4.1.5
TOMCAT 7.0.57

**Comment by cuiken** [comment]
开发环境用没用log4jdbc，有可能是这个原因。我开发环境用了这个以后升级也报这个错，拿不到版本

**Comment by lizongbo** [comment]
请使用最新版验证
