### ISSUE TITLE
I/O Error: Software caused connection abort: recv failed

### ISSUE THREAD

**Issue by blokwap** [alibaba/druid#799]
请问哪里有druid的release note
现在项目用的是1.0.1版本
时不时报I/O Error: Software caused connection abort: recv failed，请问是版本问题吗，如何解决

**Comment by blokwap** [comment]
[ERROR][2015-03-10 15:36:20,505][org.hibernate.engine.jdbc.spi.SqlExceptionHelper]wait millis 60000, active 20, runningCount 6 这个问题具体指什么

**Comment by jacking124** [comment]
你换新版本！

**Comment by wenshao** [comment]
链接不够用，20个链接已经被申请，其中6个链接正在执行SQL

**Comment by blokwap** [comment]
连接不够用--我不想单纯的增加数据库的连接个数，这样解决不了问题，
现在调试这个问题的话是不是应该从
![image](https://cloud.githubusercontent.com/assets/4651247/6591441/e0c7109e-c7fa-11e4-9212-70a66207e6d0.png)这里着手进行调试

**Comment by blokwap** [comment]
在SQL监控栏目中所有操作都是“事务中”，“事务提交”为0，请问这是正常现象吗，何时事务会结束，hibernate已配置自动提交

**Comment by lizongbo** [comment]
请使用最新版验证
