### ISSUE TITLE
升级到1.0.13后，sql injection violation, part alway true condition not allow 异常

### ISSUE THREAD

**Issue by taolive** [alibaba/druid#801]
之前版本是正常的，升级到1.0.13后，原有模板抛以下异常：
java.sql.SQLException: sql injection violation, part alway true condition not allow : select count(personalin0_.i_id) as col_0_0_ from t_hr_personal_info personalin0_ cross join t_hr_staff staff1_ where personalin0_.i_staff_id=staff1_.i_id and 1=1 and staff1_.sstaffaccount=?
    at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:714)
    at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:240)

**Comment by takeseem** [comment]
因为1=1导致触发了wall规则来自我的华为手机-------- 原始邮件 --------主题：[druid] 升级到1.0.13后，sql injection violation, part alway true condition not allow 异常 (#801)发件人：taolive 收件人：alibaba/druid 抄送：之前版本是正常的，升级到1.0.13后，原有模板抛以下异常：
java.sql.SQLException: sql injection violation, part alway true condition not allow : select count(personalin0_.i_id) as col_0_0_ from t_hr_personal_info personalin0_ cross join t_hr_staff staff1_ where personalin0_.i_staff_id=staff1_.i_id and 1=1 and staff1_.sstaffaccount=?
    at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:714)
    at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:240)

**Comment by taolive** [comment]
但是这sql中的1=1是JPA自动生成的，我没有添加这个条件

**Comment by taolive** [comment]
我使用的上一个版本：1.0.4 是正常运行的

**Comment by taolive** [comment]
同时我配置了这些属性：
 <bean id="wall-filter-config" class="com.alibaba.druid.wall.WallConfig" init-method="init">
        
        <property name="dir" value="META-INF/druid/wall/mysql"/>
        <property name="selectWhereAlwayTrueCheck" value="false"></property>
        <property name="conditionAndAlwayTrueAllow" value="false"></property>
    </bean>

**Comment by taolive** [comment]
同时我针对com.alibaba.druid.wall.WallConfig配置selectWhereAlwayTrueCheck = false，conditionAndAlwayTrueAllow=false

如果where 1=1 是正常的，但是where name = ‘aaa' and 1=1 有问题

**Comment by yakolee** [comment]
where后面第一个条件基本不会是注入点，不做检查，所以where 1=1 是正常的，where name = ‘aaa' and 1=1 有问题；
如果不想抛这个异常，请设置 conditionAndAlwayTrueAllow=true

**Comment by lizongbo** [comment]
请使用最新版验证
