### ISSUE TITLE
web应用一段时间后空指针异常

### ISSUE THREAD

**Issue by bblaiye** [alibaba/druid#802]
druid-1.0.12，tomcat 7，spring3.2，mybatis3.2，oracle10g。 应用开始正常，一段时间后（半天或一天）报500错误。求解，谢谢！！
java.lang.NullPointerException  com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:196)   org.sitemesh.webapp.contentfilter.ContentBufferingFilter.bufferAndPostProcess(ContentBufferingFilter.java:169)  org.sitemesh.webapp.contentfilter.ContentBufferingFilter.doFilter(ContentBufferingFilter.java:126)  org.sitemesh.config.ConfigurableSiteMeshFilter.doFilter(ConfigurableSiteMeshFilter.java:163)    org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)    org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

查看了源码 WebStatFilter.java
在此处
if (contextPath != null && requestURI.startsWith(contextPath)) {
            requestURI = requestURI.substring(contextPath.length());
            if (!requestURI.startsWith("/")) {
                requestURI = "/" + requestURI;
            }
        }
不知为何就是空指针了。

**Comment by bblaiye** [comment]
没人回复吗？ 实在找不出原因了。 再不行只能换c3p0了。

**Comment by wenshao** [comment]
行数不对啊

**Comment by bblaiye** [comment]
问题似乎找到了，运行服务器上放了2个druid，还有个druid-0.2.15的，估计是运维人员粗心忘记删除了。
删掉后已经运行了2天了，没有再现500。 不过这2天并发量不大， 原来总出500时，系统并发量也正好很大。 具体情况再观察。  谢谢温少！！

**Comment by niexiaolong** [comment]
问一下，正常情况下，生产环境都不应该是单机吧。
应该都是集群环境啊
集群环境，druid的监控数据都保存找内存表中，看监控的时候，没发现有问题吗。。。。
上一秒A接口访问量800次，下一秒应该是801,802才对，然后下一秒跳到另一台机器上，变成700次了。

不可能就我一个人遇到吧，这也是很常见也很好解释的问题
