### ISSUE TITLE
DDL解析不支持ADD KEY

### ISSUE THREAD

**Issue by bucketli** [alibaba/druid#804]
ALTER TABLE `t_area`  ADD KEY `parent_id` (`parent_id`);

提交建表任务出错DDL不合法[DDL ERROR!]sql解析出错,出错信息：TODO KEY KEY 

改成ALTER TABLE `t_area`  ADD INDEX `parent_id` (`parent_id`); 可以

后面我提个pull request解决，这里issue记录下

**Comment by wenshao** [comment]
欢迎！
