### ISSUE TITLE
1.0.12版本，在spring中配置数据源，引用外部属性文件，得到的username为${db_datacenter_url}，而不是对应的值。

### ISSUE THREAD

**Issue by xiaohui886688** [alibaba/druid#807]
<bean id="propertyConfigurer"
        class="org.springframework.beans.factory.config.PropertyPlaceholderConfigurer">
        <property name="locations">
            <list>
                <value>classpath:db.properties</value>
            </list>
        </property>
    </bean>

bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource" destroy-method="close">
		<property name="url" value="${db_datacenter_url}" />
		<property name="username" value="${db_datacenter_username}" />
		<property name="password" value="${db_datacenter_password}" />

**Comment by wizwjw** [comment]
这个和 druid 有什么关系？

**Comment by xiaohui886688** [comment]
同样的spring版本，用其他数据源或者其他bean对象，${db_datacenter_url}可以注入变量的值，唯独druid拿不到变量值，得到的是'db_datacenter_url'@'本地的主机名'。怀疑druid内部是不是对$符号处理过了？




xiaohui12719@163.com
 发件人： semparatus发送时间： 2015-04-03 18:52收件人： alibaba/druid抄送： xiaohui886688主题： Re: [druid] 1.0.12版本，在spring中配置数据源，引用外部属性文件，得到的username为${db_datacenter_url}，而不是对应的值。 (#807)这个和 druid 有什么关系？

**Comment by Martin404** [comment]
这跟druid没关系，跟mybatis整合会出现这种问题，如果配置文件如下：
	<bean class="org.mybatis.spring.mapper.MapperScannerConfigurer">
		<property name="basePackage" value="com.supuy.sps.dao" />
		<property name="sqlSessionFactoryBeanName" value="sqlSessionFactory" />
	</bean>
引入了sqlSessionFactoryBeanName或者sqlSessionFactory会导致在加载的时候数据源配置文件被覆盖，你可以删掉 ，当然此方案还是失败，如果配置项中有default-autowire="byName" default-lazy-init="false"，删掉

**Comment by xiaohui886688** [comment]
谢谢。
