### ISSUE TITLE
skip not validate connection

### ISSUE THREAD

**Issue by lzf715** [alibaba/druid#810]
一段时间以后，取报到连接，报skip not validate connection，系统是spring+mybatis

**Comment by wenshao** [comment]
能够提供更详细一点的堆栈信息么？

**Comment by lzf715** [comment]
您好，首先谢谢你。

ID	UseCount	LastActiveTime	ConnectTime	Holdability	TranIsolation	AutoCommit	ReadoOnly	 Pscache
sql	defaultRowPrefetch	rowPrefetch	hitCount
2059194266	1	2015-04-03 00:31:01	2015-04-03 00:15:36	1	2	true	false	
SELECT * FROM SAM_USER_BATCH WHERE GROUPID like '%SAM%' AND STATUS='01'	undefined	-1	0
1701423197	0	2015-04-03 00:31:01	2015-04-03 00:31:01	1	2	true	false	

这是从监控里看的连接池中连接信息，活跃连接没有。

		<property name="removeAbandoned" value="true" />
		
		<property name="removeAbandonedTimeout" value="1800" />
		
		<property name="logAbandoned" value="true" />
这是设置我理解是空闲30分就强制关闭了，但是到现都没有
您说的具体的能够提供更详细一点的堆栈信息么是从哪里看？

**Comment by lizongbo** [comment]
请使用最新版本验证
