### ISSUE TITLE
1.0.13 版本解析器 mysql解析不支持DESC tableName column1语句

### ISSUE THREAD

**Issue by abirdman** [alibaba/druid#818]
例如新建一个表create table student (id int ,sname varchar(44));
然后使用如下测试代码测试：
public static void main(String[] args) {
		String sql = "desc student sname";
		MySqlStatementParser parser = new MySqlStatementParser(sql);
		SQLStatement statement;

		//解析出现问题统一抛SQL语法错误
		try {
			statement = parser.parseStatement();
			Assert.assertEquals(sql.toUpperCase(),statement.toString());
		} catch (Throwable t) {
			t.printStackTrace();
		}
	}

**Comment by wenshao** [comment]
提交个pull request？

**Comment by yakolee** [comment]
1.0.15中会支持
