### ISSUE TITLE
druid的sql的dialect为什么删掉对HIVE的支持了？

### ISSUE THREAD

**Issue by sdboy206207** [alibaba/druid#825]
druid的sql的dialect为什么删掉对HIVE的支持了？

**Comment by wenshao** [comment]
没人用啊

**Comment by sdboy206207** [comment]
我想用 (⊙﹏⊙)b。
我想用druid的sql parse模块。不知道druid-0.2.8中那些hive parse代码是否ok？

**Comment by wenshao** [comment]
没人用过的代码，怎么知道是否OK呢，唉。。。

**Comment by sdboy206207** [comment]
想解析hive中的sql，获取到对应的表名或者列名，有什么办法么？

**Comment by lizongbo** [comment]
请使用最新版验证
