### ISSUE TITLE
为sql添加查询条件

### ISSUE THREAD

**Issue by mizhiwu** [alibaba/druid#833]
我目前使用PagerUtils获得sql语句的分页查询语句。
那么有没有一个Utils可以通过我给的sql，添加一个查询条件，然后返回最终sql呢？
例如:sql = "select * from users where 1 =1" --> "select * from users where 1 =1 and username='a'"

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/wiki/%E5%A6%82%E6%9E%9C%E4%BF%AE%E6%94%B9SQL%E6%B7%BB%E5%8A%A0%E6%9D%A1%E4%BB%B6

SQLUtils增加了相应方法
