### ISSUE TITLE
druid慢sql监控希望能够提供自定义处理器扩展

### ISSUE THREAD

**Issue by JerryFang** [alibaba/druid#835]
druid自带的StatFilter中慢sql监控，只提供了简单的日志打印。
大集群环境下，不利于问题排查。
希望能够提供自定义处理器接口，便于扩展

目前的代码：
long millis = nanos / (1000 \* 1000);
if (millis >= slowSqlMillis) {
    String slowParameters = buildSlowParameters(statement);
    sqlStat.setLastSlowParameters(slowParameters);
    if (logSlowSql) {
        LOG.error("slow sql " + millis + " millis. \n" + statement.getLastExecuteSql() + "\n"
                  + slowParameters);
    }
}

**Comment by lizongbo** [comment]
自己继承 StatFilter增加相关的自定义逻辑即可
