### ISSUE TITLE
mysql数据库密码写错了，启动的时候会hold住，没反应，没有连接失败的提示

### ISSUE THREAD

**Issue by wanggj** [alibaba/druid#836]
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>druid</artifactId>
    <version>0.2.23</version>
</dependency>

**Comment by janwen** [comment]
这个比较坑爹。刚碰到更诡异的。Oralce密码过期,tomcat启动不了，也看不到错误。直接导致linux server  挂掉,fork:can not allocate memory .可以把druid的log打开，能看到错误。

**Comment by wendal** [comment]
一直不fix,哎

**Comment by lizongbo** [comment]
请使用最新版验证
