### ISSUE TITLE
 对mybaties(3.2.3)语法支持不太好

### ISSUE THREAD

**Issue by igool** [alibaba/druid#867]
<select id="*******************" parameterType="map" resultMap="**************">
        SELECT 
            b.id,
            b.appid,
            b.appname,
            b.appkey,
            b.createtime,
            b.status,
            b.iplimit,
            b.appdesc,
            b.redirect_url,
            b.memo,b.uid,
            b.mid 
        FROM business b 
        where 1=1
        <choose>
            <otherwise>
                <foreach item="item" collection="columnDefs" index="index">
                    <choose>
                        <when
                            test="index > -1 and (item.getSearch() != '' and item.getSearch() != null)  ">
                            <choose>
                                <when test="item.getName() == 'appname'">
                                    AND b.appname LIKE "%"#{item.search}"%"
                                </when>
                                <when test="item.getName() == 'status'">
                                    AND b.status=#{item.search} 
                                </when>
                            </choose>
                        </when>
                    </choose>
                </foreach>

```
            <if test="!listbids.isEmpty()">
            AND b.id IN
            <foreach item="did" collection="listbids" index="index"
                open="(" separator="," close=")">
                #{did}
            </foreach>
            </if>
            ORDER BY createtime desc
        </otherwise>
    </choose>

</select>
```

这是一个部分匹配的一个SQL片断
AND b.appname LIKE "%"#{item.search}"%"
实际上我的SQL是执行没有问题的。

**Comment by igool** [comment]
![druid](https://cloud.githubusercontent.com/assets/3281260/8032766/57e43138-0e0b-11e5-95f5-9534a1767f18.png)

**Comment by wenshao** [comment]
这个符合mysql语法规范？？
