### ISSUE TITLE
phyTimeout mysql数据库8小时超时问题

### ISSUE THREAD

**Issue by blackshadowwalker** [alibaba/druid#870]
增加一个参数：phyTimeoutMillis = 7 * 3600 * 1000  物理连接的超时时间，
如果池中的一个物理连接超过指定的时间（默认7小时）则关闭物理连接，以避免mysql数据库8小时超时的限制而报异常，在DestroyTask线程中处理
````java
int phytimeoutms = currentTimeMillis - com.alibaba.druid.proxy.jdbc.ConnectionProxy.getConnectedTime();
if( phytimeoutms  >= phyTimeoutMillis  ){
   JdbcUtils.close(connection);
}
````

**Comment by wenshao** [comment]
不错的建议，你提交一个pull request？

**Comment by blackshadowwalker** [comment]
> 不错的建议，你提交一个pull request？

好啊， 我写一下  @wenshao

**Comment by blackshadowwalker** [comment]
虽然druid会在进行逻辑打开连接时如果空闲达到一定的时间就检查连接的有效性，如果存在以下这种情况就会达到mysql默认8小时空闲超时：
1. 连接池minIdle >=1 , 这某个连接一直未被逻辑打开，这些被保留的连接一直未被使用
2. (testOnBorrow=false， testWhileIdle=true, testOnReturn=false)连接池中的连接很活跃（空闲时间小于timeBetweenEvictionRunsMillis），但是池中获取连接后并未进行任何的数据库操作，从而未进行与数据库的真实通讯，这样会导致大量的连接空闲超时

**Comment by blokwap** [comment]
请问现在这个8小时问题还有其他的解决方案吗

**Comment by niexiaolong** [comment]
配置一个 testOnBorrow=true就够了 其他都不用配  不然会出现重复检查的效率影响
并且 配置这个 在生产环境跑了 效率影响确实不是想象中的大

**Comment by blokwap** [comment]
文档中说了testWhileIdle作用是申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis， 
执行validationQuery检测连接是否有效。

但是配置了testWhileIdle为什么不起作用呢

**Comment by wenshao** [comment]
什么版本？

**Comment by yakolee** [comment]
@blokwap 什么版本？连接池是怎么配置的？配validationQuery了吗？

**Comment by blokwap** [comment]
@wenshao @yakolee 换了1.0.13版本以后还没重现过这个问题。谢谢

**Comment by blackshadowwalker** [comment]
https://github.com/alibaba/druid/pull/939
