### ISSUE TITLE
1.0.15 版本 SQL监控事务已经提交但监控页面中的监控sql的事务状态还为事务中

### ISSUE THREAD

**Issue by wangjuneng** [alibaba/druid#892]
org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:365) [15-07-07 15:02:31] Creating new transaction with name [org.firefly.biz.service.AccountService.queryAccountList]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT,readOnly
[DEBUG] org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:204) [15-07-07 15:02:31] Acquired Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@1c390af] for JDBC transaction
[DEBUG] org.springframework.jdbc.datasource.DataSourceUtils.prepareConnectionForTransaction(DataSourceUtils.java:153) [15-07-07 15:02:31] Setting JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@1c390af] read-only
[DEBUG] org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:221) [15-07-07 15:02:31] Switching JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@1c390af] to manual commit
[INFO] org.firefly.framework.core.Application.getFireflyJdbcDaoSupport(Application.java:190) [15-07-07 15:02:31] 从ThreadLocal变量中获得JdbcDaoSupport对象实例:{default=org.firefly.framework.dao.JdbcDaoSupport@1fb084a}
[DEBUG] org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:635) [15-07-07 15:02:31] Executing prepared SQL query
[DEBUG] org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:570) [15-07-07 15:02:31] Executing prepared SQL statement [ SELECT count(*) ]
[DEBUG] org.firefly.framework.dao.dialect.PageDialectOracle.getSqlConstruct(PageDialectOracle.java:45) [15-07-07 15:02:31] page sql: 
[DEBUG] org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:635) [15-07-07 15:02:32] Executing prepared SQL query
[DEBUG] org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:570) [15-07-07 15:02:32] Executing prepared SQL statement [ 
[DEBUG] org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:752) [15-07-07 15:02:32] Initiating transaction commit
[DEBUG] org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:264) [15-07-07 15:02:32] Committing JDBC transaction on Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@1c390af]
[DEBUG] org.springframework.jdbc.datasource.DataSourceUtils.resetConnectionAfterTransaction(DataSourceUtils.java:222) [15-07-07 15:02:32] Resetting read-only flag of JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@1c390af]
[DEBUG] org.springframework.jdbc.datasource.DataSourceTransactionManager.doCleanupAfterCompletion(DataSourceTransactionManager.java:322) [15-07-07 15:02:32] Releasing JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@1c390af] after transaction
[DEBUG] org.springframework.jdbc.datasource.DataSourceUtils.doReleaseConnection(DataSourceUtils.java:332) [15-07-07 15:02:32] Returning JDBC Connection to DataSource

N   SQL▼  执行数   执行时间    最慢  事务中   错误数   更新行数    读取行数    执行中  
1   SELECT \* FROM ( SELECT ...  2   23  11  2           6       2

**Comment by niexiaolong** [comment]
同问，我这边，也是这样

**Comment by niexiaolong** [comment]
是的，给别人演示的时候，别人问这个，我都不知道怎么回答他。。。。

**Comment by ptzhuf** [comment]
@niexiaolong 你就回答他, 恭喜你, 你看到的是一个真实的软件运行在一个真实的环境中, 他不是我们伪造出来给你看的, 演示的时候有bug是好事, 有bug就可以让那些程序员解决了啊~hahaha, 来, 我们继续 go on (从我们的前IBM CTO 毛总那里偷来的句子~)

**Comment by lizongbo** [comment]
请使用最新版本验证
