### ISSUE TITLE
当前版本的druid是否支持postgreSql的多schema场景?

### ISSUE THREAD

**Issue by dairymix** [alibaba/druid#893]
我看代码发现DruidPooledConnection针对connection的实现中:  
public void setSchema(String schema) throws SQLException
  {
    throw new SQLFeatureNotSupportedException();
  }

  public String getSchema() throws SQLException {
    throw new SQLFeatureNotSupportedException();
  }
这两个方法会通告特性不支持.
那么postgreSql下的多schema场景是否需要支持?有什么处理的办法么?

**Comment by siaron** [comment]
可能是不支持 JDBC 4.1  的规范.

**Comment by lizongbo** [comment]
最新代码也不支持，需要加一下支持。
