### ISSUE TITLE
JdbcUtils 类 建议

### ISSUE THREAD

**Issue by sdcuike** [alibaba/druid#910]
public static String getDbType(String rawUrl, String driverClassName)
方法，是不是找不到抛出异常，而不是直接return null;呢。
今天就有人把jdbc中的j漏掉了，抛出LOG.error("init datasource error, url: " + this.getUrl(), ex);
感觉直接在getDbType方法抛出找不到合适的DbType，比较贴近错误地方。

**Comment by wenshao** [comment]
涉及的地方较多，不好改。因为很多地方使用了dbType == null来做判断的
