### ISSUE TITLE
wall filter拦截h2的sequence语句解析出错

### ISSUE THREAD

**Issue by myoss** [alibaba/druid#927]
<property name="filters" value="wall,stat" />  使用默认的拦截器

h2db的jdbc版本
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>1.3.176</version>
            
        </dependency>

ORM使用Hibernate 4.3.7

实体类主键的配置
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "Id2SeqGenerator")
    @SequenceGenerator(name = "Id2SeqGenerator",
                       sequenceName = "SEQ_T_QUESTION__ID",
                       initialValue = 1,
                       allocationSize = 1)
    @Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
    public Long getId() {
        return this.id;
    }

hibernate生成的sql语句
call next value for SEQ_T_SURVEY__ID

druid的violationMessage如下：
syntax error: syntax error, error in :'next value for SEQ_T_SURVEY__ID',expect IDENTIFIER, actual IDENTIFIER value

**Comment by JoinGit** [comment]
druid 版本信息如下： 
       <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid</artifactId>
            <version>1.0.14</version>
        </dependency>

**Comment by wenshao** [comment]
h2数据库还要用防注入啊？

**Comment by JoinGit** [comment]
web应用兼容H2数据库，支持多个数据库，默认配置了拦截
