### ISSUE TITLE
项目使用druid，数据库连接池经常满

### ISSUE THREAD

**Issue by zzd6436643** [alibaba/druid#940]
项目框架使用spring boot，数据库使用mysql，连接串配置了自动重连，useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false，
以下为各属性值的配置：
 // 配置初始化大小、最小、最大
    @Value("${druid.initialSize:1}")
    private int initialSize;
    @Value("${druid.minIdle:1}")
    private int minIdle;
    @Value("${druid.maxActive:100}")
    private int maxActive;

    // 配置获取连接等待超时的时间
    @Value("${druid.maxWait:20000}")
    private long maxWait;

    // 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    @Value("${druid.timeBetweenEvictionRunsMillis:60000}")
    private long timeBetweenEvictionRunsMillis;

    @Value("${druid.validationQuery:select 'x'}")
    private String validationQuery;

    @Value("${druid.testWhileIdle:true}")
    private boolean testWhileIdle;

    @Value("${druid.testOnBorrow:false}")
    private boolean testOnBorrow;

    @Value("${druid.testOnReturn:false}")
    private boolean testOnReturn;

我的activeCount配置的是100，结果每次第二天来的时候，这个值就到达100了，导致程序无法继续拿到连接，这个是我配置的数值有问题还是我少配置了属性呢？

**Comment by YaoYufeng** [comment]
可以问下是为什么吗？

**Comment by airrons** [comment]
同问

**Comment by shixw** [comment]
同问
