### ISSUE TITLE
java.sql.SQLException: connection holder is null， druid是1.0.13

### ISSUE THREAD

**Issue by toby2** [alibaba/druid#944]
HI,我们现在遇到上面这个异常。web应用运行1天后，就会出现这个问题，应用正常，但是登陆操作时就会报这个错。望大神帮看下这个问题。万分感谢
java.sql.SQLException: connection holder is null
    at com.alibaba.druid.pool.DruidPooledConnection.checkStateInternal(DruidPooledConnection.java:1109)
    at com.alibaba.druid.pool.DruidPooledConnection.checkState(DruidPooledConnection.java:1100)
    at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:305)

下面是tomcat的配置
                    <Parameter name="retention" value="PRODUCTION"/>
                    <Parameter name="username" value="develop"/>
                    <Parameter name="password" value="/MnG16eDcWanlRERTvFghNm9MobWvMSO0G6eJDRc78Y="/>
                    <Parameter name="url" value="jdbc:mysql://192.168.22.236:3306/S71?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true&amp;autoReconnectForPools=true&amp;noAccessToProcedureBodies=true"/>
                    <Parameter name="initialSize" value="10"/>
                    <Parameter name="maxActive" value="100"/>
                    <Parameter name="minIdle" value="20"/>
                    <Parameter name="maxWait" value="3000"/>
                    <Parameter name="timeBetweenEvictionRunsMillis" value="600000"/>
                    <Parameter name="minEvictableIdleTimeMillis" value="300000"/>
                    <Parameter name="testWhileIdle" value="true"/>
                    <Parameter name="testOnBorrow" value="false"/>
                    <Parameter name="testOnReturn" value="false"/>
                    <Parameter name="useUnfairLock" value="false"/>
                    <Parameter name="filters" value="config,stat,log4j"/>
                    <Parameter name="removeAbandoned" value="true"/>
                    <Parameter name="removeAbandonedTimeout" value="86400"/>
                    <Parameter name="logAbandoned" value="true"/>
                    <Parameter name="validationQuery" value="select 1 from dual"/>

**Comment by toby2** [comment]
<Parameter name="retention" value="PRODUCTION"/>
                    <Parameter name="username" value="develop"/>
                    <Parameter name="password" value="/MnG16eDcWanlRERTvFghNm9MobWvMSO0G6eJDRc78Y="/>
                    <Parameter name="url" value="jdbc:mysql://192.168.22.236:3306/S71?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true&amp;autoReconnectForPools=true&amp;noAccessToProcedureBodies=true"/>
                    <Parameter name="initialSize" value="10"/>
                    <Parameter name="maxActive" value="100"/>
                    <Parameter name="minIdle" value="20"/>
                    <Parameter name="maxWait" value="3000"/>
                    <Parameter name="timeBetweenEvictionRunsMillis" value="600000"/>
                    <Parameter name="minEvictableIdleTimeMillis" value="300000"/>
                    <Parameter name="testWhileIdle" value="true"/>
                    <Parameter name="testOnBorrow" value="false"/>
                    <Parameter name="testOnReturn" value="false"/>
                    <Parameter name="useUnfairLock" value="false"/>
                    <Parameter name="filters" value="config,stat,log4j"/>
                    <Parameter name="removeAbandoned" value="true"/>
                    <Parameter name="removeAbandonedTimeout" value="86400"/>
                    <Parameter name="logAbandoned" value="true"/>
                    <Parameter name="validationQuery" value="select 1 from dual"/>

**Comment by wenshao** [comment]
应该是存在跨线程使用连接的情况，升级到最新版本就好了。

**Comment by quyf** [comment]
Caused by: java.sql.SQLException: connection holder is null
        at com.alibaba.druid.pool.DruidPooledConnection.checkStateInternal(DruidPooledConnection.java:1107)
        at com.alibaba.druid.pool.DruidPooledConnection.checkState(DruidPooledConnection.java:1100)
        at com.alibaba.druid.pool.DruidPooledConnection.getMetaData(DruidPooledConnection.java:832)
        at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:294)
        ... 44 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 261,548 milliseconds ago.  The last packet sent successfully to the server was 10 milliseconds ago.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)......
我的也出现过类似的错误

**Comment by toby2** [comment]
升级到最新版本，这个问题依然存在

**Comment by kop-still** [comment]
是连接被abandoned了吗？

**Comment by ly01152000** [comment]
我也遇到了,是什么原因的?

**Comment by janchengwang** [comment]
我也遇到了，下面是我的异常信息
2162 [net.sf.ehcache.CacheManager@75815f28] INFO net.sf.ehcache.util.UpdateChecker - New update(s) found: 2.4.7 [http://www.terracotta.org/confluence/display/release/Release+Notes+Ehcache+Core+2.4]. Please check http://ehcache.org for the latest version.
17:47:14.381 [scheduler_Worker-1] INFO  com.alibaba.druid.pool.DruidDataSource - {dataSource-2} inited
com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@48177daa
17:47:18.334 [scheduler_Worker-1] INFO  org.wys.vol.service.JobService - 定时器开始
com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@48177daa
closed-conn-543449835
java.sql.SQLException: connection holder is null
	at com.alibaba.druid.pool.DruidPooledConnection.checkStateInternal(DruidPooledConnection.java:1122)
	at com.alibaba.druid.pool.DruidPooledConnection.checkState(DruidPooledConnection.java:1113)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareCall(DruidPooledConnection.java:518)
	at org.wys.vol.db.utils.JDBCUtils.callStoredProcedure(JDBCUtils.java:421)
	at org.wys.vol.service.JobService.test(JobService.java:26)

**Comment by soarpatriot** [comment]
我也遇到了？ 怎么解决的？

**Comment by zouguobing** [comment]
me too!
Cause: java.sql.SQLException: connection holder is null
; uncategorized SQLException for SQL []; SQL state [null]; error code [0]; connection holder is null; nested exception is java.sql.SQLException: connection holder is null
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:83) ~[spring-jdbc-3.2.13.RELEASE.jar:3.2.13.RELEASE]

**Comment by yikee** [comment]
同样的问题，升级到最新版本，问题依然存在！

**Comment by niejian** [comment]
将 removeAbandoned 属性设置为false就好了

**Comment by lubin1127** [comment]
可以监控一下运行时的线程数，我产生问题的是在定时器服务里面，定时器每隔一段时间去一个url获取信息，获取信息完没完全释放线程并且未使用线程池，运行一段时间后线程太多后产生的错误

**Comment by mobile664042** [comment]
> 将 removeAbandoned 属性设置为false就好了

默认就是false啊

**Comment by lizongbo** [comment]
请使用最新版本验证
