### ISSUE TITLE
如果Classpath不包含mysql的驱动，在Spring下面无法获取数据库连接也没有任何报错，一直在等待。

### ISSUE THREAD

**Issue by elveahuang** [alibaba/druid#948]
如果Classpath不包含mysql的驱动，在Spring下面无法获取数据库连接也没有任何报错，一直在等待。
在执行Junit测试的时候发现这个问题，加上驱动到pom.xml里面后，就可以正常获取连接。

**Comment by wenshao** [comment]
我测试了没有发现这个问题啊

**Comment by elveahuang** [comment]
奇怪，之前做的时候，确实有问题，先关了，我找个时间再验证一下。
