### ISSUE TITLE
当druid与spring boot配合使用时,会出现druid监控的servlet不能很好的配合浏览器工作

### ISSUE THREAD

**Issue by zhaohaolin** [alibaba/druid#952]
bug出现的版本: druid三个版本测试都如此,其它版本没有测试(1.0.4, 1.0.14, 1.0.15)
bug表现形式: 当请求http://xxxx/druid/index.html时,在浏览器中不能正确显示页面,而是显示了html源代码

因此问题一般是servlet没有返回text/html的响应头造成的,通过对浏览器请求包分析也论证了我这个怀疑,因此就好办了,直接看源代码,发现在源代码类com.alibaba.druid.support.http.ResourceSerlvet的方法protected void returnResourceFile(String fileName, String uri,
            HttpServletResponse response) throws ServletException, IOException最后一行,没有对返回html形式的文件进行设置响应头,
找到地方就好办了,直接在这里设置一下响应头,但注意不要所有都通通设置为text/html,要判断一下
我的fix代码如下:
if (fileName.endsWith(".html")) {
    response.setContentType("text/html;charset=utf-8");
}
response.getWriter().write(text);

当然,在修改过程发现,druid1.0.15里的这个类名变成了ResourceServlet

重新打包或是把这个类直接放到工程中就可以使用了(主要是类加载机制,优先加载了本工程中的代码)

**Comment by colddew** [comment]
我用springboot启动没有遇到这样的问题，可以访问后台页面，但是SQL监控没有任何显示，Spring监控也没有找到好的配置方法

@wenshao 请问有没有springboot和druid结合的demo可以提供，不使用xml配置，只使用annotation和jar启动方式网上找了很久没有找到类似的demo

**Comment by colddew** [comment]
问题解决了，使用纯annotation的方式，资源文件中的druid.filters=wall,stat配置项无效，必须在代码中显示的用dataSource.setFilters("wall,stat")这种方式才可以加载成功

**Comment by BigDuck** [comment]
@colddew @zhaohaolin @wenshao  不好意思打扰了问下有没有spring boot 和druid的demo。 我自己在弄的过程中好像没工作的的样子，我github有小demo，不知道你们有没有demo学习。万分感谢，我快放弃boot，心累

**Comment by colddew** [comment]
@BigDuck  可以看下我这个https://github.com/colddew/micro-service，micro-service-server子工程应该可以满足你的要求

**Comment by pengliaoye** [comment]
有人知道怎么解决么

**Comment by jameBoy** [comment]
dataSource.setFilters("wall,stat")  上面@colddew说的很好呀，你可以上他的project上看代码@pengliaoye

**Comment by zhaiyuyong** [comment]
springboot 加了security时候 druid 监控的servlet显示了html源代码

**Comment by Louistz** [comment]
可以参考@colddew的项目。不过我发现不用专门在代码中setFilters 。我的配置是：
`spring.datasource.filters=stat,wall,log4j`
可以正常注册进去。下面是完整的代码：解析参考了@colddew的代码，我之前是把配置注册一个bean中，datasource是一个一个属性set的。配置文件的格式如上面的filters配置。
`
@Configuration
@MapperScan("xxx.dao")
public class DruidConfig {

    private static final String DB_PREFIX = "spring.datasource.";

    @Autowired
    private Environment environment;

    @Bean
    @ConfigurationProperties(prefix = DB_PREFIX)
    public DataSource druidDataSource() {

        Properties dbProperties = new Properties();
        Map<String, Object> map = new HashMap<String, Object>();
        for (Iterator<PropertySource<?>> it =
                ((AbstractEnvironment) environment).getPropertySources().iterator(); it.hasNext();) {
            PropertySource<?> propertySource = it.next();
            getPropertiesFromSource(propertySource, map);
        }
        dbProperties.putAll(map);

        DruidDataSource dds = null;
        try {
            dds = (DruidDataSource) DruidDataSourceFactory.createDataSource(dbProperties);
            if (null != dds) {
                dds.init();
            }
        } catch (Exception e) {
            throw new RuntimeException("load datasource error, dbProperties is :" + dbProperties, e);
        }
        return dds;
    }

    private void getPropertiesFromSource(PropertySource<?> propertySource, Map<String, Object> map) {
        if (propertySource instanceof MapPropertySource) {
            for (String key : ((MapPropertySource) propertySource).getPropertyNames()) {
                if (key.startsWith(DB_PREFIX)) {
                    map.put(key.replaceFirst(DB_PREFIX, ""), propertySource.getProperty(key));
                } else if (key.startsWith(DB_PREFIX)) {
                    map.put(key.replaceFirst(DB_PREFIX, ""), propertySource.getProperty(key));
                }
            }
        }

        if (propertySource instanceof CompositePropertySource) {
            for (PropertySource<?> s : ((CompositePropertySource) propertySource)
                    .getPropertySources()) {
                getPropertiesFromSource(s, map);
            }
        }
    }

    @Bean
    public ServletRegistrationBean druidServlet() {
        return new ServletRegistrationBean(new StatViewServlet(), "/druid/*");
    }

    @Bean
    public FilterRegistrationBean filterRegistrationBean() {
        FilterRegistrationBean filterRegistrationBean = new FilterRegistrationBean();
        filterRegistrationBean.setFilter(new WebStatFilter());
        filterRegistrationBean.addUrlPatterns("/*");
        filterRegistrationBean.addInitParameter("exclusions",
                "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*");
        return filterRegistrationBean;
    }

    @Bean
    public SqlSessionFactoryBean sqlSessionFactoryBean() throws Exception {

        SqlSessionFactoryBean sqlSessionFactoryBean = new SqlSessionFactoryBean();
        sqlSessionFactoryBean.setDataSource(druidDataSource());
        sqlSessionFactoryBean.setTypeAliasesPackage("xxx.domain");
        return sqlSessionFactoryBean;
    }

    @Bean
    public DataSourceTransactionManager transactionManager() throws Exception {
        return new DataSourceTransactionManager(druidDataSource());
    }
} `

**Comment by colddew** [comment]
我之前用的是1.0.15版，更新为1.0.20版后，的确如@Louistz所说可以通过资源文件配置wall和stat过滤器，这样就不用硬编码了

**Comment by sunset535** [comment]
druid修改为最新的：

```
<groupId>com.alibaba</groupId>
<artifactId>druid-spring-boot-starter</artifactId>
<version>1.1.0</version>
```
本地用shiro  发现时报错：
org.apache.shiro.UnavailableSecurityManagerException: No SecurityManager accessible to the calling code, either bound to the org.apache.shiro.util.ThreadContext or as a vm static singleton.  This is an invalid application configuration.

有遇到过同样问题吗
