### ISSUE TITLE
com.alibaba.druid.pool.GetConnectionTimeoutException errorCode localizedMessage wait millis 10000 active 10

### ISSUE THREAD

**Issue by itliming** [alibaba/druid#966]
I am using the version 1.0.1,the follow exception happened to me,and I don't know the probable reason,please help me to fix it.thanks a lot!

error message:
{"@type":"org.springframework.transaction.CannotCreateTransactionException","cause":{"@type":"com.alibaba.druid.pool.GetConnectionTimeoutException","errorCode":0,"localizedMessage":"wait millis 10000, active 10","message":"wait millis 10000, active 10","stackTrace":[{"className":"com.alibaba.druid.pool.DruidDataSource","fileName":"DruidDataSource.java","lineNumber":1071,"methodName":"getConnectionInternal","nativeMethod":false},{"className":"com.alibaba.druid.pool.DruidDataSource","fileName":"DruidDataSource.java","lineNumber":898,"methodName":"getConnectionDirect","nativeMethod":false},{"className":"com.alibaba.druid.filter.FilterChainImpl","fileName":"FilterChainImpl.java","lineNumber":4534,"methodName":"dataSource_connect","nativeMethod":false},{"className":"com.alibaba.druid.filter.logging.LogFilter","fileName":"LogFilter.java","lineNumber":827,"methodName":"dataSource_getConnection","nativeMethod":false},{"className":"com.alibaba.druid.filter.FilterChainImpl","fileName":"FilterChainImpl.java","lineNumber":4530,"methodName":"dataSource_connect","nativeMethod":false},{"className":"com.alibaba.druid.filter.stat.StatFilter","fileName":"StatFilter.java","lineNumber":661,"methodName":"dataSource_getConnection","nativeMethod":false},{"className":"com.alibaba.druid.filter.FilterChainImpl","fileName":"FilterChainImpl.java","lineNumber":4530,"methodName":"dataSource_connect","nativeMethod":false},{"className":"com.alibaba.druid.pool.DruidDataSource","fileName":"DruidDataSource.java","lineNumber":880,"methodName":"getConnection","nativeMethod":false},{"className":"com.alibaba.druid.pool.DruidDataSource","fileName":"DruidDataSource.java","lineNumber":872,"methodName":"getConnection","nativeMethod":false},{"className":"com.alibaba.druid.pool.DruidDataSource","fileName":"DruidDataSource.java","lineNumber":97,"methodName":"getConnection","nativeMethod":false},{"className":"org.springframework.jdbc.datasource.DataSourceTransactionManager","fileName":"DataSourceTransactionManager.java","lineNumber":202,"methodName":"doBegin","nativeMethod":false},{"className":"org.springframework.transaction.support.AbstractPlatformTransactionManager","fileName":"AbstractPlatformTransactionManager.java","lineNumber":371,"methodName":"getTransaction","nativeMethod":false},{"className":"org.springframework.transaction.interceptor.TransactionAspectSupport","fileName":"TransactionAspectSupport.java","lineNumber":335,"methodName":"createTransactionIfNecessary","nativeMethod":false},{"className":"org.springframework.transaction.interceptor.TransactionInterceptor","fileName":"TransactionInterceptor.java","lineNumber":105,"methodName":"invoke","nativeMethod":false},{"className":"org.springframework.aop.framework.ReflectiveMethodInvocation","fileName":"ReflectiveMethodInvocation.java","lineNumber":172,"methodName":"proceed","nativeMethod":false},{"className":"org.springframework.aop.framework.adapter.ThrowsAdviceInterceptor","fileName":"ThrowsAdviceInterceptor.java","lineNumber":124,"methodName":"invoke","nativeMethod":false},{"className":"org.springframework.aop.framework.ReflectiveMethodInvocation","fileName":"ReflectiveMethodInvocation.java","lineNumber":161,"methodName":"proceed","nativeMethod":false},{"className":"org.springframework.aop.interceptor.ExposeInvocationInterceptor","fileName":"ExposeInvocationInterceptor.java","lineNumber":91,"methodName":"invoke","nativeMethod":false},{"className":"org.springframework.aop.framework.ReflectiveMethodInvocation","fileName":"ReflectiveMethodInvocation.java","lineNumber":172,"methodName":"proceed","nativeMethod":false},{"className":"org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor","fileName":"CglibAopProxy.java","lineNumber":634,"methodName":"intercept","nativeMethod":false},{"className":"com.wl.api.demander.service.impl.RegisterService$$EnhancerByCGLIB$$488175fd","fileName":"<generated>","lineNumber":-1,"methodName":"getLoginAccount","nativeMethod":false},{"className":"com.wl.api.demander.controller.WeiXinAccountController","fileName":"WeiXinAccountController.java","lineNumber":521,"methodName":"validateMobilePhone","nativeMethod":false},{"className":"com.wl.api.demander.controller.WeiXinAccountController","fileName":"WeiXinAccountController.java","lineNumber":303,"methodName":"generateToken","nativeMethod":false},{"className":"sun.reflect.GeneratedMethodAccessor488","lineNumber":-1,"methodName":"invoke","nativeMethod":false},{"className":"sun.reflect.DelegatingMethodAccessorImpl","fileName":"DelegatingMethodAccessorImpl.java","lineNumber":43,"methodName":"invoke","nativeMethod":false},{"className":"java.lang.reflect.Method","fileName":"Method.java","lineNumber":606,"methodName":"invoke","nativeMethod":false},{"className":"org.springframework.web.method.support.InvocableHandlerMethod","fileName":"InvocableHandlerMethod.java","lineNumber":219,"methodName":"invoke","nativeMethod":false},{"className":"org.springframework.web.method.support.InvocableHandlerMethod","fileName":"InvocableHandlerMethod.java","lineNumber":132,"methodName":"invokeForRequest","nativeMethod":false},{"className":"org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod","fileName":"ServletInvocableHandlerMethod.java","lineNumber":104,"methodName":"invokeAndHandle","nativeMethod":false},{"className":"org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter","fileName":"RequestMappingHandlerAdapter.java","lineNumber":745,"methodName":"invokeHandleMethod","nativeMethod":false},{"className":"org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter","fileName":"RequestMappingHandlerAdapter.java","lineNumber":686,"methodName":"handleInternal","nativeMethod":false},{"className":"org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter","fileName":"AbstractHandlerMethodAdapter.java","lineNumber":80,"methodName":"handle","nativeMethod":false},{"className":"org.springframework.web.servlet.DispatcherServlet","fileName":"DispatcherServlet.java","lineNumber":925,"methodName":"doDispatch","nativeMethod":false},{"className":"org.springframework.web.servlet.DispatcherServlet","fileName":"DispatcherServlet.java","lineNumber":856,"methodName":"doService","nativeMethod":false},{"className":"org.springframework.web.servlet.FrameworkServlet","fileName":"FrameworkServlet.java","lineNumber":936,"methodName":"processRequest","nativeMethod":false},{"className":"org.springframework.web.servlet.FrameworkServlet","fileName":"FrameworkServlet.java","lineNumber":838,"methodName":"doPost","nativeMethod":false},{"className":"javax.servlet.http.HttpServlet","fileName":"HttpServlet.java","lineNumber":646,"methodName":"service","nativeMethod":false},{"className":"org.springframework.web.servlet.FrameworkServlet","fileName":"FrameworkServlet.java","lineNumber":812,"methodName":"service","nativeMethod":false},{"className":"javax.servlet.http.HttpServlet","fileName":"HttpServlet.java","lineNumber":727,"methodName":"service","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":303,"methodName":"internalDoFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":208,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.tomcat.websocket.server.WsFilter","fileName":"WsFilter.java","lineNumber":52,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":241,"methodName":"internalDoFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":208,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.shiro.web.servlet.ProxiedFilterChain","fileName":"ProxiedFilterChain.java","lineNumber":61,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.shiro.web.servlet.AdviceFilter","fileName":"AdviceFilter.java","lineNumber":108,"methodName":"executeChain","nativeMethod":false},{"className":"org.apache.shiro.web.servlet.AdviceFilter","fileName":"AdviceFilter.java","lineNumber":137,"methodName":"doFilterInternal","nativeMethod":false},{"className":"org.apache.shiro.web.servlet.OncePerRequestFilter","fileName":"OncePerRequestFilter.java","lineNumber":125,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.shiro.web.servlet.ProxiedFilterChain","fileName":"ProxiedFilterChain.java","lineNumber":66,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.shiro.web.servlet.AbstractShiroFilter","fileName":"AbstractShiroFilter.java","lineNumber":449,"methodName":"executeChain","nativeMethod":false},{"className":"org.apache.shiro.web.servlet.AbstractShiroFilter$1","fileName":"AbstractShiroFilter.java","lineNumber":365,"methodName":"call","nativeMethod":false},{"className":"org.apache.shiro.subject.support.SubjectCallable","fileName":"SubjectCallable.java","lineNumber":90,"methodName":"doCall","nativeMethod":false},{"className":"org.apache.shiro.subject.support.SubjectCallable","fileName":"SubjectCallable.java","lineNumber":83,"methodName":"call","nativeMethod":false},{"className":"org.apache.shiro.subject.support.DelegatingSubject","fileName":"DelegatingSubject.java","lineNumber":383,"methodName":"execute","nativeMethod":false},{"className":"org.apache.shiro.web.servlet.AbstractShiroFilter","fileName":"AbstractShiroFilter.java","lineNumber":362,"methodName":"doFilterInternal","nativeMethod":false},{"className":"org.apache.shiro.web.servlet.OncePerRequestFilter","fileName":"OncePerRequestFilter.java","lineNumber":125,"methodName":"doFilter","nativeMethod":false},{"className":"org.springframework.web.filter.DelegatingFilterProxy","fileName":"DelegatingFilterProxy.java","lineNumber":343,"methodName":"invokeDelegate","nativeMethod":false},{"className":"org.springframework.web.filter.DelegatingFilterProxy","fileName":"DelegatingFilterProxy.java","lineNumber":260,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":241,"methodName":"internalDoFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":208,"methodName":"doFilter","nativeMethod":false},{"className":"org.springframework.web.filter.CharacterEncodingFilter","fileName":"CharacterEncodingFilter.java","lineNumber":88,"methodName":"doFilterInternal","nativeMethod":false},{"className":"org.springframework.web.filter.OncePerRequestFilter","fileName":"OncePerRequestFilter.java","lineNumber":107,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":241,"methodName":"internalDoFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":208,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.catalina.core.StandardWrapperValve","fileName":"StandardWrapperValve.java","lineNumber":220,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.core.StandardContextValve","fileName":"StandardContextValve.java","lineNumber":122,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.authenticator.AuthenticatorBase","fileName":"AuthenticatorBase.java","lineNumber":503,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.core.StandardHostValve","fileName":"StandardHostValve.java","lineNumber":170,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.valves.ErrorReportValve","fileName":"ErrorReportValve.java","lineNumber":103,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.valves.AccessLogValve","fileName":"AccessLogValve.java","lineNumber":950,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.core.StandardEngineValve","fileName":"StandardEngineValve.java","lineNumber":116,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.connector.CoyoteAdapter","fileName":"CoyoteAdapter.java","lineNumber":421,"methodName":"service","nativeMethod":false},{"className":"org.apache.coyote.http11.AbstractHttp11Processor","fileName":"AbstractHttp11Processor.java","lineNumber":1070,"methodName":"process","nativeMethod":false},{"className":"org.apache.coyote.AbstractProtocol$AbstractConnectionHandler","fileName":"AbstractProtocol.java","lineNumber":611,"methodName":"process","nativeMethod":false},{"className":"org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor","fileName":"JIoEndpoint.java","lineNumber":314,"methodName":"run","nativeMethod":false},{"className":"java.util.concurrent.ThreadPoolExecutor","fileName":"ThreadPoolExecutor.java","lineNumber":1145,"methodName":"runWorker","nativeMethod":false},{"className":"java.util.concurrent.ThreadPoolExecutor$Worker","fileName":"ThreadPoolExecutor.java","lineNumber":615,"methodName":"run","nativeMethod":false},{"className":"org.apache.tomcat.util.threads.TaskThread$WrappingRunnable","fileName":"TaskThread.java","lineNumber":61,"methodName":"run","nativeMethod":false},{"className":"java.lang.Thread","fileName":"Thread.java","lineNumber":745,"methodName":"run","nativeMethod":false}],"suppressed":[]},"localizedMessage":"Could not open JDBC Connection for transaction; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 10000, active 10","message":"Could not open JDBC Connection for transaction; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 10000, active 10","mostSpecificCause":{"$ref":"$.cause"},"rootCause":{"$ref":"$.cause"},"stackTrace":[{"className":"org.springframework.jdbc.datasource.DataSourceTransactionManager","fileName":"DataSourceTransactionManager.java","lineNumber":240,"methodName":"doBegin","nativeMethod":false},{"className":"org.springframework.transaction.support.AbstractPlatformTransactionManager","fileName":"AbstractPlatformTransactionManager.java","lineNumber":371,"methodName":"getTransaction","nativeMethod":false},{"className":"org.springframework.transaction.interceptor.TransactionAspectSupport","fileName":"TransactionAspectSupport.java","lineNumber":335,"methodName":"createTransactionIfNecessary","nativeMethod":false},{"className":"org.springframework.transaction.interceptor.TransactionInterceptor","fileName":"TransactionInterceptor.java","lineNumber":105,"methodName":"invoke","nativeMethod":false},{"className":"org.springframework.aop.framework.ReflectiveMethodInvocation","fileName":"ReflectiveMethodInvocation.java","lineNumber":172,"methodName":"proceed","nativeMethod":false},{"className":"org.springframework.aop.framework.adapter.ThrowsAdviceInterceptor","fileName":"ThrowsAdviceInterceptor.java","lineNumber":124,"methodName":"invoke","nativeMethod":false},{"className":"org.springframework.aop.framework.ReflectiveMethodInvocation","fileName":"ReflectiveMethodInvocation.java","lineNumber":161,"methodName":"proceed","nativeMethod":false},{"className":"org.springframework.aop.interceptor.ExposeInvocationInterceptor","fileName":"ExposeInvocationInterceptor.java","lineNumber":91,"methodName":"invoke","nativeMethod":false},{"className":"org.springframework.aop.framework.ReflectiveMethodInvocation","fileName":"ReflectiveMethodInvocation.java","lineNumber":172,"methodName":"proceed","nativeMethod":false},{"className":"org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor","fileName":"CglibAopProxy.java","lineNumber":634,"methodName":"intercept","nativeMethod":false},{"className":"com.wl.api.demander.service.impl.RegisterService$$EnhancerByCGLIB$$488175fd","fileName":"<generated>","lineNumber":-1,"methodName":"getLoginAccount","nativeMethod":false},{"className":"com.wl.api.demander.controller.WeiXinAccountController","fileName":"WeiXinAccountController.java","lineNumber":521,"methodName":"validateMobilePhone","nativeMethod":false},{"className":"com.wl.api.demander.controller.WeiXinAccountController","fileName":"WeiXinAccountController.java","lineNumber":303,"methodName":"generateToken","nativeMethod":false},{"className":"sun.reflect.GeneratedMethodAccessor488","lineNumber":-1,"methodName":"invoke","nativeMethod":false},{"className":"sun.reflect.DelegatingMethodAccessorImpl","fileName":"DelegatingMethodAccessorImpl.java","lineNumber":43,"methodName":"invoke","nativeMethod":false},{"className":"java.lang.reflect.Method","fileName":"Method.java","lineNumber":606,"methodName":"invoke","nativeMethod":false},{"className":"org.springframework.web.method.support.InvocableHandlerMethod","fileName":"InvocableHandlerMethod.java","lineNumber":219,"methodName":"invoke","nativeMethod":false},{"className":"org.springframework.web.method.support.InvocableHandlerMethod","fileName":"InvocableHandlerMethod.java","lineNumber":132,"methodName":"invokeForRequest","nativeMethod":false},{"className":"org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod","fileName":"ServletInvocableHandlerMethod.java","lineNumber":104,"methodName":"invokeAndHandle","nativeMethod":false},{"className":"org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter","fileName":"RequestMappingHandlerAdapter.java","lineNumber":745,"methodName":"invokeHandleMethod","nativeMethod":false},{"className":"org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter","fileName":"RequestMappingHandlerAdapter.java","lineNumber":686,"methodName":"handleInternal","nativeMethod":false},{"className":"org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter","fileName":"AbstractHandlerMethodAdapter.java","lineNumber":80,"methodName":"handle","nativeMethod":false},{"className":"org.springframework.web.servlet.DispatcherServlet","fileName":"DispatcherServlet.java","lineNumber":925,"methodName":"doDispatch","nativeMethod":false},{"className":"org.springframework.web.servlet.DispatcherServlet","fileName":"DispatcherServlet.java","lineNumber":856,"methodName":"doService","nativeMethod":false},{"className":"org.springframework.web.servlet.FrameworkServlet","fileName":"FrameworkServlet.java","lineNumber":936,"methodName":"processRequest","nativeMethod":false},{"className":"org.springframework.web.servlet.FrameworkServlet","fileName":"FrameworkServlet.java","lineNumber":838,"methodName":"doPost","nativeMethod":false},{"className":"javax.servlet.http.HttpServlet","fileName":"HttpServlet.java","lineNumber":646,"methodName":"service","nativeMethod":false},{"className":"org.springframework.web.servlet.FrameworkServlet","fileName":"FrameworkServlet.java","lineNumber":812,"methodName":"service","nativeMethod":false},{"className":"javax.servlet.http.HttpServlet","fileName":"HttpServlet.java","lineNumber":727,"methodName":"service","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":303,"methodName":"internalDoFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":208,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.tomcat.websocket.server.WsFilter","fileName":"WsFilter.java","lineNumber":52,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":241,"methodName":"internalDoFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":208,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.shiro.web.servlet.ProxiedFilterChain","fileName":"ProxiedFilterChain.java","lineNumber":61,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.shiro.web.servlet.AdviceFilter","fileName":"AdviceFilter.java","lineNumber":108,"methodName":"executeChain","nativeMethod":false},{"className":"org.apache.shiro.web.servlet.AdviceFilter","fileName":"AdviceFilter.java","lineNumber":137,"methodName":"doFilterInternal","nativeMethod":false},{"className":"org.apache.shiro.web.servlet.OncePerRequestFilter","fileName":"OncePerRequestFilter.java","lineNumber":125,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.shiro.web.servlet.ProxiedFilterChain","fileName":"ProxiedFilterChain.java","lineNumber":66,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.shiro.web.servlet.AbstractShiroFilter","fileName":"AbstractShiroFilter.java","lineNumber":449,"methodName":"executeChain","nativeMethod":false},{"className":"org.apache.shiro.web.servlet.AbstractShiroFilter$1","fileName":"AbstractShiroFilter.java","lineNumber":365,"methodName":"call","nativeMethod":false},{"className":"org.apache.shiro.subject.support.SubjectCallable","fileName":"SubjectCallable.java","lineNumber":90,"methodName":"doCall","nativeMethod":false},{"className":"org.apache.shiro.subject.support.SubjectCallable","fileName":"SubjectCallable.java","lineNumber":83,"methodName":"call","nativeMethod":false},{"className":"org.apache.shiro.subject.support.DelegatingSubject","fileName":"DelegatingSubject.java","lineNumber":383,"methodName":"execute","nativeMethod":false},{"className":"org.apache.shiro.web.servlet.AbstractShiroFilter","fileName":"AbstractShiroFilter.java","lineNumber":362,"methodName":"doFilterInternal","nativeMethod":false},{"className":"org.apache.shiro.web.servlet.OncePerRequestFilter","fileName":"OncePerRequestFilter.java","lineNumber":125,"methodName":"doFilter","nativeMethod":false},{"className":"org.springframework.web.filter.DelegatingFilterProxy","fileName":"DelegatingFilterProxy.java","lineNumber":343,"methodName":"invokeDelegate","nativeMethod":false},{"className":"org.springframework.web.filter.DelegatingFilterProxy","fileName":"DelegatingFilterProxy.java","lineNumber":260,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":241,"methodName":"internalDoFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":208,"methodName":"doFilter","nativeMethod":false},{"className":"org.springframework.web.filter.CharacterEncodingFilter","fileName":"CharacterEncodingFilter.java","lineNumber":88,"methodName":"doFilterInternal","nativeMethod":false},{"className":"org.springframework.web.filter.OncePerRequestFilter","fileName":"OncePerRequestFilter.java","lineNumber":107,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":241,"methodName":"internalDoFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":208,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.catalina.core.StandardWrapperValve","fileName":"StandardWrapperValve.java","lineNumber":220,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.core.StandardContextValve","fileName":"StandardContextValve.java","lineNumber":122,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.authenticator.AuthenticatorBase","fileName":"AuthenticatorBase.java","lineNumber":503,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.core.StandardHostValve","fileName":"StandardHostValve.java","lineNumber":170,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.valves.ErrorReportValve","fileName":"ErrorReportValve.java","lineNumber":103,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.valves.AccessLogValve","fileName":"AccessLogValve.java","lineNumber":950,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.core.StandardEngineValve","fileName":"StandardEngineValve.java","lineNumber":116,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.connector.CoyoteAdapter","fileName":"CoyoteAdapter.java","lineNumber":421,"methodName":"service","nativeMethod":false},{"className":"org.apache.coyote.http11.AbstractHttp11Processor","fileName":"AbstractHttp11Processor.java","lineNumber":1070,"methodName":"process","nativeMethod":false},{"className":"org.apache.coyote.AbstractProtocol$AbstractConnectionHandler","fileName":"AbstractProtocol.java","lineNumber":611,"methodName":"process","nativeMethod":false},{"className":"org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor","fileName":"JIoEndpoint.java","lineNumber":314,"methodName":"run","nativeMethod":false},{"className":"java.util.concurrent.ThreadPoolExecutor","fileName":"ThreadPoolExecutor.java","lineNumber":1145,"methodName":"runWorker","nativeMethod":false},{"className":"java.util.concurrent.ThreadPoolExecutor$Worker","fileName":"ThreadPoolExecutor.java","lineNumber":615,"methodName":"run","nativeMethod":false},{"className":"org.apache.tomcat.util.threads.TaskThread$WrappingRunnable","fileName":"TaskThread.java","lineNumber":61,"methodName":"run","nativeMethod":false},{"className":"java.lang.Thread","fileName":"Thread.java","lineNumber":745,"methodName":"run","nativeMethod":false}],"suppressed":[]}

**Comment by wenshao** [comment]
SQL执行慢，连接不够用

**Comment by kiwimg** [comment]
着这样吗，我也遇到同样的问题 解决了吗

**Comment by lizongbo** [comment]
https://developer.aliyun.com/article/407853

**Comment by lizongbo** [comment]
请使用最新版验证
