### ISSUE TITLE
Druid引起TOMCAT JVM CoreDump

### ISSUE THREAD

**Issue by xiongchen2012** [alibaba/druid#997]
不知道为什么 ，在日志中看到这一段。

229910459 2015-11-24 09:54:14 com.alibaba.druid.pool.DruidDataSource INFO -{dataSource-1} closed

A fatal error has been detected by the Java Runtime Environment:

  SIGBUS (0xa) at pc=0xfddf5a48, pid=15165, tid=29

 JRE version: Java(TM) SE Runtime Environment (7.0_79-b15) (build 1.7.0_79-b15)
 Java VM: Java HotSpot(TM) Server VM (24.79-b02 mixed mode solaris-sparc )
 Problematic frame:
 C  [libzip.so+0x5a48]  newEntry+0x74

Core dump written. Default location: //core or core.15165

 An error report file with more information is saved as:
 //hs_err_pid15165.log
Compiled method (c2) 305822502 1372   !         org.apache.catalina.loader.WebappClassLoader::findResourceInternal (1497 bytes)
 total in heap  [0xfc04e208,0xfc06189c] = 79508
 relocation     [0xfc04e2d4,0xfc04ef58] = 3204
 main code      [0xfc04ef60,0xfc055e60] = 28416
 stub code      [0xfc055e60,0xfc0564d0] = 1648
 oops           [0xfc0564d0,0xfc05689c] = 972
 scopes data    [0xfc05689c,0xfc05f648] = 36268
 scopes pcs     [0xfc05f648,0xfc0609f8] = 5040
 dependencies   [0xfc0609f8,0xfc060a88] = 144
 handler table  [0xfc060a88,0xfc061670] = 3048
 nul chk table  [0xfc061670,0xfc06189c] = 556

0 2015-11-24 10:10:05 com.alibaba.druid.pool.DruidDataSource INFO -{dataSource-1} inited

**Comment by lizongbo** [comment]
这个tomcat在应用停止时关闭了数据源，然后又有其它代码触发访问数据源，然后触发class加载导致的问题。
